### ISSUE TITLE
Command line args not sent to dotnet Projects when debugging

### ISSUE THREAD

**Issue by jaredthirsk** [dotnet/aspire#1000]
Steps to reproduce:
1. For a dotnet project that is a member of the Aspire AppHost, edit its `launchSettings.json`, and add a launch profile with `"commandLineArgs": "my args",`
2. In AppHost's Program.cs, set WithLaunchProfile  ( `builder.AddProject<Projects.___>("___").WithLaunchProfile("myprofile");`)
3. In Visual Studio, start debugging the Aspire AppHost project

Expected
1. the dotnet project receives "my args" as command line args

Actual
1. there are no command line args

Notes:
- It looks like the Launch profile is otherwise working, when debugging, for:
  - ApplicationUrl
  - Environment Variables, including DOTNET_LAUNCH_PROFILE
- When not debugging, ApplicationExecutor.cs PrepareProjectExecutables() will construct the command line arguments from the launchProfile.  It looks like this logic is either missing in Aspire when debugging, or dotnet.exe is supposed to be picking up the launch profile some other way (DOTNET_LAUNCH_PROFILE?) but it's not working for me.

**Comment by karolz-ms** [comment]
In `PrepareProjectExecutables()` the if/else case is really about are we running from IDE (Visual Studio) vs not. If Visual Studio is in the picture, it uses its own logic for handling launch profiles, and that is why Aspire AppHost code does not do anything in this case. I think VS folks should take a look @vijayrkn @BillHiebert

**Comment by mitchdenny** [comment]
I just checked, when we launch the project via dotnet run outside of VS the args do get passed through.

**Comment by BillHiebert** [comment]
This is a limitation in the interface used to talk with Visual Studio.  We'll need to do some work to support htis

**Comment by karolz-ms** [comment]
Not fixed yet...
