### ISSUE TITLE
Add "Back to Traces" Navigation Button in Structured Logs View

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire#1006]
### Description

**Context:** When users are navigating through the Structured Logs in our Blazor application, they currently lack a straightforward way to return to the Trace view for a specific `TraceId`. This limitation can lead to a less intuitive and efficient user experience, as users may have to manually alter the URL or use the browser's back button to navigate back to the Trace view.

**Problem:** The absence of a direct navigation option from the Structured Logs page back to the corresponding Trace page can be a point of friction for users, especially when dealing with complex logs and traces.

**Proposed Solution:** Introduce a "Back to Traces" button in the Structured Logs component. This button should only be visible when a `TraceId` is present in the URL, and clicking on it should take the user back to the Trace page associated with that `TraceId`.

**Expected Outcome:** 
- Enhanced user experience through improved navigation.
- Reduced time and effort to switch between Structured Logs and Trace views.

### Steps to Reproduce
(Currently, there is no direct way to navigate back via the user interface, hence an enhancement is needed.)

https://github.com/dotnet/aspire/assets/47674962/7782f8b8-fe64-40dc-8ae1-4a555fa891e7

### Related PR
- PR #1005 addresses this issue by implementing the proposed solution.

**Comment by davidfowl** [comment]
Does this still apply to the latest previews @JamesNK ?

**Comment by JamesNK** [comment]
Back buttons on the page have been removed. Now relying on the browser back button.
