### ISSUE TITLE
.net 8 apsire issue with AddAzureKeyVaultSecrets

### ISSUE THREAD

**Issue by maythamfahmi** [dotnet/aspire#1010]
I am following Microsoft [documentation](https://learn.microsoft.com/en-us/dotnet/aspire/security/azure-security-key-vault-component?tabs=dotnet-cli#get-started). 

```
var builder = DistributedApplication.CreateBuilder(args);
builder.AddAzureKeyVaultSecrets("secrets");
```
I have installed/added `Aspire.Azure.Security.KeyVault` package, but getting the following [issue](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1061?f1url=%3FappId%3Droslyn%26k%3Dk(CS1061))

![image](https://github.com/dotnet/aspire/assets/9260645/dc6df1e8-718f-4085-8069-45bb33efdccb)

I use Visual Studio Enterprise 2022 Preview 17.9.0 Preview 1.0
latest azd version "azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)"

**Comment by dwschreyer** [comment]
I had to use the daily build to get mine to work.

**Comment by davidfowl** [comment]
That’s the wrong project. There are 2 methods, one to be used in the apphost and on to be used in the service project itself.

**Comment by maythamfahmi** [comment]
I must agree with you @davidfowl  adding Aspire.Hosting.Azure to AppHost project will solve the issue. 

`<PackageReference Include="Aspire.Hosting.Azure" Version="8.0.0-preview.1.23557.2" />`

![image](https://github.com/dotnet/aspire/assets/9260645/e30ed4ad-2c0f-4ef5-bb26-daee3ac41d14)
