### ISSUE TITLE
Add AddNpmApp and AddNodeApp to Aspire.Hosting

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1017]
We should move this boilerplate to the core (we'll figure out refactorig of these packages later).

https://github.com/dotnet/aspire-samples/blob/main/samples/AspireWithNode/AspireWithNode.AppHost/NodeAppHostingExtensions.cs

cc @DamianEdwards

**Comment by OneCyrus** [comment]
that's pretty cool. especially the AppNpmApp makes it pretty clean for npm based projects.

We have also a lot of yarn based node projects. Would it be possible to have a simple native AppYarnApp method as well?

**Comment by davidfowl** [comment]
I don't think I want to add yarn, at least not in the core. I'd also other to ask for `pnpm run` and for bun support 😄. Did I miss anything? These methods are mostly to let people experiment so we can flesh out what needs to be done in the core infrastructure to make this work well.

**Comment by raix** [comment]
It would be fairly reasonable to add an option for configuring what package manager / command tool to execute Javascript

That said adding your own extension method is fairly easy - it's also completely reasonable for Microsoft to advocate C# tooling and attempt to migrate developers towards Blazor
