### ISSUE TITLE
Inconsistency and Usability Issues in Current Navigation Menu

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire#1032]
The current implementation of our navigation menu has significant inconsistencies in design and user experience, particularly when compared to refined examples such as the navigation menu in Azure DevOps. Our menu's visual and functional aspects are lacking in providing a cohesive and intuitive user interface.

**Reference for Comparison:**

Azure DevOps Menu:
![Azure DevOps Menu](https://github.com/dotnet/aspire/assets/47674962/b5971bf6-5395-4007-9184-c159083a9c79)

**Details:**

The primary issues revolve around the positioning and functionality of the settings button and sidebar toggle. The current layout does not effectively utilize space and fails to provide a clear navigation experience. The `NavMenuLink` component's restrictive properties limit our ability to mirror more dynamic and user-friendly designs, such as combining multiple icons in a single interactive element.

**Proposed Solution:**

PR [#1031](https://github.com/dotnet/aspire/pull/1031) has been created to address these concerns. It repositions the settings button and sidebar toggle to the bottom of the navigation menu, emulating the layout found in Azure DevOps. This change aims to enhance the usability and aesthetic appeal of our navigation system.

**Expected Outcome:**

With the implementation of PR #1031, the navigation menu will offer a more streamlined and intuitive interface, akin to the Azure DevOps example. The settings and toggle functionalities will be more accessible and visually distinct, significantly improving the user experience.

**Screenshots of Proposed Changes:**

NavMenu Expanded:
![NavMenu Expanded](https://github.com/dotnet/aspire/assets/47674962/42751eb6-f0ac-4731-a04d-faf2bef33998)

NavMenu Closed:
![NavMenu Closed](https://github.com/dotnet/aspire/assets/47674962/41174ac2-ccc1-4c5a-b3f6-f8f7b1afc1c8)

**Comment by ShreyasJejurkar** [comment]
Looks great tbh. 👍

**Comment by smitpatel** [comment]
@leslierichardson95 - Are we taking in proposed changes here? Based on PR discussion, I see no conclusive answer.

**Comment by davidfowl** [comment]
The design has changed quite a bit, I'm going to close this for now. @josephaw1022 feel free to reopen a new issue with new design suggestions.
