### ISSUE TITLE
Streamline Configuration of Prometheus and Grafana in Aspire

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire#1037]
I've noticed in the samples that the metrics app has Prometheus and Grafana configured directly within the application code. While this approach works, it heavily relies on external configuration files and detailed implementation specifics. I propose that we explore a more opinionated and code-centric way of configuring these services, specifically through C# methods, to improve clarity and ease of maintenance.

**Current Approach:**
- Prometheus and Grafana are set up and configured through external files and in-depth implementation within the app's code.
- This method can be cumbersome and less intuitive for developers who are not deeply familiar with these services.

**Suggested Enhancement:**
- Implement C# extension methods such as `AddGrafana()` and `AddPrometheus()` within the `DistributedApplicationBuilder`. 
- These methods would encapsulate the setup logic for each service, providing a more streamlined and intuitive interface.

**Example of Suggested Approach:**
```csharp
var builder = DistributedApplication.CreateBuilder(args);

// Simplified addition of Grafana and Prometheus
builder.AddGrafana();
builder.AddPrometheus();

// Continuation with other microservices and projects
// ...

using var app = builder.Build();
await app.RunAsync();
```

**Additional Consideration for Implementation:**

Alongside the proposed changes, it's important to address the handling of configuration files for Prometheus and Grafana. If we adopt the suggested approach, we'll need to:

1. **Decide on Default Config File Locations**: Determine where the configuration files for Grafana and Prometheus should be placed within the project's file structure by default. This decision impacts the ease of access and management of these files.

2. **Provide Flexibility for Config Path Customization**: Implement methods or options within `AddGrafana()` and `AddPrometheus()` to allow developers to specify alternative paths for these configuration files. This flexibility is essential to accommodate various project structures and specific requirements.

This consideration ensures that while we streamline the setup process, we also maintain the adaptability and configurability necessary for diverse development environments.

**Comment by mitchdenny** [comment]
I'd love to see an `AddGrafana` and `AddPrometheus` extension. Would you be interested it putting up a PR?

It was actually some of our early experimentation with prometheus that resulted in the `WithVolumeMount(...)` extension getting added but to be honest we haven't fully figured out how that is going to work outside the inner loop. How to create populate, and attach volume mounts to different component resources is very target environment specific. 

If you were going to explore this space it would probably help evolve our thinking a bit.

**Comment by samsp-msft** [comment]
One of the reasons that we implemented the dashboard is to simplify the need for configuration at development time. We expect prometheus, grafana, jaeger etc to be choices that are made for deployment, and so included the app part of the configuration as comments in the templates. There is still work required to configure each of the services that will be deployment specific. If/how you use those will depend heavily on the eventual deployment environment, and therefore out of scope. 

Aspire is not intended to be a general purpose deployment mechanism, and I think configuring those services would fall into that bucket.

**Comment by josephaw1022** [comment]
I just want an easy approach to setting up Grafana dashboards that removes the thinking. This isn't about locking someone into deploying Prometheus because they use it locally.

**Comment by prom3theu5** [comment]
Spitballing here. Mainly for how we handle deploy of config with K8s.

I think the dockerfile.v0 resource is the right way to go here.
That way - we can orchestrate volume creation in a cluster quite easily by treating the output resource in this case as an [`init-container`](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)
This container would then have its data copied into a volume during initialization of the main container. 

A dockerfile.v0 that gets built into a shippable container, and used as an init-container to essentially seed a volume feels much better.
There would need to be a clear way of expressing this in the manifest though so dockerfile.v0 resources to be used as init containers can be paired with an owning container.
Essentially a potentially shippable volume / volume container, agnostic of what storage class is going to be used on a  cluster.
Maybe we do actually need a new resource type here, that can have a parent on it, a slimmed down dockerfile.v0. containervolume.v0?

Now this would work fine with AKS, essentially populating whatever CSI you re using (like Azure disk / blob / files etc), Any k8s based cluster really.
The same approach could be used with compose based deployments, with an init container, and a main container both sharing the same volume at start up, and the main container depending on the startup of the init container

When it comes to container instances though - A similar route could be taken, however with a different base image that contains the tools  to write to azure storage and an entrypoint that populates...

**Comment by davidfowl** [comment]
Consider contributing this to https://github.com/CommunityToolkit/Aspire
