### ISSUE TITLE
Use tri-state feature in FluentCheckbox

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1042]
https://github.com/dotnet/aspire/pull/987 added a tri-state checkbox. It required some hacky code.

FluentUI adds better support for this feature in https://github.com/microsoft/fluentui-blazor/pull/1022. Use this feature when FluentUI is updated.

**Comment by JamesNK** [comment]
Unblocked with https://github.com/dotnet/aspire/pull/1152

**Comment by tlmii** [comment]
> Unblocked with #1152?

Yep. I knew I was missing one when I did that. Forgot that you added this issue not me, so it was missing from my query. #1159 handles it.
