### ISSUE TITLE
Supplying configuration for containers added with .AddContainer() 

### ISSUE THREAD

**Issue by gkfischer** [dotnet/aspire#1044]
In our scenario, we have 50+ microservices running from their dedicated docker images. To run these images - I call them application containers below - as a service to an application being developed, it would be necessary to supply: 

1. configuration from standard containers like RabbitMq or SqlServer to these application containers (e.g. the connection strings)
2. provide configuration for the application containers

re 1.) When supplying the connection string with `sqlServer.Resource.GetConnectionString` I get a connection string mapped in an environment variable for the application container but the container fails because it can't connect to the database with
`"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server: Could not open a connection to SQL Server)"`
Is this a scenario that isn't supported (yet), or did I miss something?

re 2.) Providing all configurations as environment variables using `.WithEnvironment` is not only a pain but unusable, because the configuration for an application container would have to be repeated in code in each project using that container. Is there a way to supply configs by some other means that I don't see?

**Comment by DamianEdwards** [comment]
This is likely a dupe of #850 and #128

**Comment by gkfischer** [comment]
Ok great , as far as I understand, there's something planned for a future release (like January) for the first question, but what about the second?

**Comment by gkfischer** [comment]
The containers get a lot of settings when running in Kubernetes through environment variables. These aren't present obviously when the image is started in Aspire. But I guess that can be remedied by using an appsettings file.

**Comment by davidfowl** [comment]
> The containers get a lot of settings when running in Kubernetes through environment variables. These aren't present obviously when the image is started in Aspire. But I guess that can be remedied by using an appsettings file.

OR use `WithEnvironment`
