### ISSUE TITLE
Support tracing when AddRedis used with a serviceKey

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspire#1045]
The `OpenTelemetry.Instrumentation.StackExchangeRedis` package needs an `IConnectionMultiplexer` instance for tracing and currently it is getting the instance from IoC container.

When we call `AddRedis` with a `serviceKey` the tracing would not work since the current implementation of the package get the instance without the service key.

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/c3a4f335f5a1f4fc784d44cc99b5bf44e872a66c/src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs#L135

This is blocked by https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1451 and when it got merged and published, this code could be changed to add the new API that gets the `serviceKey`

https://github.com/dotnet/aspire/blob/15c4446851d044ce6c8a66e7ab69e528e47f6c7b/src/Components/Aspire.StackExchange.Redis/AspireRedisExtensions.cs#L100-L108

**Comment by Kahbazi** [comment]
Thinking more about this it's not technically blocked by `OpenTelemetry.Instrumentation.StackExchangeRedis`. We should be able to copy [this method](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/c3a4f335f5a1f4fc784d44cc99b5bf44e872a66c/src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs#L114-L144) and change the implementation to include the keyed service. This way we don't need to wait for `OpenTelemetry.Instrumentation.StackExchangeRedis` to update the package and the code could use the new API when  it's ready.

I'm willing to send a PR for this issue.

**Comment by Kahbazi** [comment]
> We should do it in both places right?

By both do you mean in `OpenTelemetry.Instrumentation.StackExchangeRedis` and `Aspire`? Then yes. 

We might be able to support this without changes in `OpenTelemetry.Instrumentation.StackExchangeRedis` by copying some code in `OpenTelemetry.Instrumentation.StackExchangeRedis` package.

**Comment by eerhardt** [comment]
@Kahbazi - if you want to open a PR to fix this, that would be awesome.

**Comment by eerhardt** [comment]
> Should we wait for the open telemetry package to update its API or should we do the temporary fix for now?

I'd make the temporary fix (with tests) now. And we can update to the new version of OTel when it is available.
