### ISSUE TITLE
Additional text should have something in the title

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspire#1050]
![image](https://github.com/dotnet/aspire/assets/1528107/33ce23b3-0310-429f-a214-59de0f4c8cc8)

While hover over shows what the values in lighter font is (container id/ process id), we should have something in title too. Current display makes it confusing UI. 

Also since we are writing long text for container Id (whole guid), we should use Process Id rather than PID.

**Comment by danmoseley** [comment]
@smitpatel I'm hoping to add more help wanted and possibly good first issue to our issues -- anything that is shovel ready but we don't have immediate plans to do ourselves. It would be great to have many marked -- feel free to remove from this one/apply to others as you think best.
