### ISSUE TITLE
Don't start watching console logs if an existing resource isn't selected

### ISSUE THREAD

**Issue by tlmii** [dotnet/aspire#1055]
From https://github.com/dotnet/aspire/pull/1034#issuecomment-1828816555
> When you click on the console logs link in the menu, what decides which app to display?
>
> Structured logs and traces have an "All" option and select it by default. But that doesn't make sense for console logs. Metrics doesn't display anything by default and prompts you to choose a service (note: service should be renamed to resource)
> 
> ![image](https://github.com/dotnet/aspire/assets/9613109/b710eeff-e37d-4200-8cdc-7e14a1fc1a04)
> 
> I think the console logs could do the same thing. That page would also be displayed if a bad name is in the url, e.g. `http://localhost:15888/ConsoleLogs/ThisDoesntExist`

This is relevant with or without the combined console logs view (#1034 which as of this issue being filed has not gone in) since the behavior is the same before and after that PR.

@leslierichardson95 @kvenkatrajan for your thoughts on this as well

**Comment by JamesNK** [comment]
If there is a plan for combined console logs, then the default should be the `(All)` option is selected and combined data is shown.

Otherwise I think a UI asking the user to select a resource (like metrics) should be shown.

**Comment by tlmii** [comment]
> If there is a plan for combined console logs, then the default should be the `(All)` option is selected and combined data is shown.
> 
> Otherwise I think a UI asking the user to select a resource (like metrics) should be shown.

My language in the description was probably imprecise. No plans to show a combined view of all the logs at the same time. Just #1034 to have a single page regardless of type. I updated the issue description to hopefully clarify that. Agree that the UI asking the user to select a resource is the right direction (assuming we want to move away from selecting the first one).
