### ISSUE TITLE
Creating sample project into an output directory with periods in the name results in a non-compiling AppHost

### ISSUE THREAD

**Issue by rytmis** [dotnet/aspire#1066]
I followed the [getting started instructions](https://learn.microsoft.com/en-gb/dotnet/aspire/get-started/quickstart-build-your-first-aspire-app?tabs=dotnet-cli). The workload installer pulled in Aspire.ProjectTemplates.8.0.0-preview.1.23557.2.nupgk.

The only change I made to the instructions was to use a folder with a period in the name, and the result doesn't compile:

![image](https://github.com/dotnet/aspire/assets/121952/409db42c-0930-44f3-b69f-cef8c1a598fe)

Looks like the msbuild code generator handles the periods just fine, but the AppHost project's Program.cs comes from a template that doesn't. It generates this:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var apiservice = builder.AddProject<Projects.Some.Namespaced.Folder_ApiService>("apiservice");

builder.AddProject<Projects.Some.Namespaced.Folder_Web>("webfrontend")
    .WithReference(apiservice);

builder.Build().Run();
```

when it should be this:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var apiservice = builder.AddProject<Projects.Some_Namespaced_Folder_ApiService>("apiservice");

builder.AddProject<Projects.Some_Namespaced_Folder_Web>("webfrontend")
    .WithReference(apiservice);

builder.Build().Run();
```

Fortunately, the workaround is simple: correct the AddProject type arguments. :)

(Apologies if this is a duplicate--I tried searching, but while I found issues that looked to be very close to this, not one that matched this exactly)

**Comment by davidfowl** [comment]
Yep this is known and fixed in the next preview (https://github.com/dotnet/aspire/pull/953), spaces and dots 😄
