### ISSUE TITLE
[WebToolsE2E][Aspire] On the dashboard, collapse menu list, click the second icon (Monitoring), nothing happens.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#1070]
**REGRESSION INFO**: Also repro on 17.9 Preview 1 (includes Aspire.ProjectTemplates.8.0.0-preview.1.23557.2)
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install latest VS 17.9 P2 from [34327.208.main]
3. CLI workload update and install aspire workload:  [Aspire.ProjectTemplates.8.0.0-preview.2.23577.7]
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > .NET Aspire Starter Application > .NET 8.0 > Create.
2. Ctrl F5.
3. On the dashboard, collapse the menu list, then click the second icon (Monitoring).

**ACTUAL**
Click the second icon (Monitoring), nothing happens, selection locator doesn't change, the menu list also doesn't expand.
![issue2](https://github.com/dotnet/aspire/assets/82028229/fc6ab1be-8081-4b85-8249-6b07f097cc3a)

**EXPECTED**
It should expand the 'Monitoring' section.

**Comment by tlmii** [comment]
@vnbaaij I noticed this too (though I rarely collapse). Is there anything we can change now? Any plans to adjust the way this works?

**Comment by vnbaaij** [comment]
For v4.1.1 I'm adding functionality so the menu itself is collapsed and you click on an item (whether it has a link or not), the menu will go to the expanded state
![NavMenuBahaviorChange](https://github.com/dotnet/aspire/assets/1761079/15c43d7a-454b-46ed-b540-abdf48ada4f1)

**Comment by adamint** [comment]
@vnbaaij this is still an issue on 4.1.1, which we are using.

**Comment by adamint** [comment]
@vnbaaij I can confirm both that the Aspire Dashboard is using version 4.1.1, and that the behavior is still occurring.

![Animation](https://github.com/dotnet/aspire/assets/20359921/8ceded7e-d7b7-45b7-8422-f8448f1d90f0)

**Comment by tlmii** [comment]
Yeah I saw it too and was wondering if maybe my branch was just out of date. But I guess not.

**Comment by vnbaaij** [comment]
Ok, let me check

**Comment by vnbaaij** [comment]
Fixed with PR #1249 
![aspire-navmenu](https://github.com/dotnet/aspire/assets/1761079/ce78733b-da5a-44f3-a562-75da2fe54e4c)

**Comment by v-cazhang** [comment]
Verified on Aspire.ProjectTemplates.8.0.0-preview.3.23619.4, this issue has been fixed.
