### ISSUE TITLE
Should the dashboard be more reflective?

### ISSUE THREAD

**Issue by jmickeyd** [dotnet/aspire#1077]
When using Aspire for large, mixed C# and non-C# systems, the dashboard's Project vs Container vs Executable divide starts to seem a bit arbitrary. Being able to slice on and display other dimensions would be super useful.

I'd like to propose creating new Annotations to describe the UI without connection to other behaviors. This could also accelerate adoption of Aspire for new custom resources as they could be visualized without code changes to the dashboard.

**Comment by DamianEdwards** [comment]
The dashboard has been updated to combine all resources in a single page. This updated UX will be in preview.2. Thanks for the feedback!
