### ISSUE TITLE
Creating the .NET Aspire orchestrator project failed.

### ISSUE THREAD

**Issue by mikekistler** [dotnet/aspire#1083]
I'm attempting to add the Aspire orchestrator to an existing .NET project using Visual Studio.

I'm using Visual Studio 2022 17.9 Preview 2:

> Microsoft Visual Studio Enterprise 2022
> Version 17.9.0 Preview 2.0 [34327.274.main]
> VisualStudio.17.IntPreview/17.9.0-pre.2.0+34327.274.main
> Microsoft .NET Framework
> Version 4.8.09032

I select Add / .NET Aspire Orchestrator support... from the contextual menu for the project and it shows this dialog:

<img width="442" alt="Pasted Graphic" src="https://github.com/dotnet/aspire/assets/85643503/20994a2f-02ea-4968-bc8b-57474c4e6d14">

When I click "Ok" I get this error:

<img width="434" alt="Pasted Graphic 2" src="https://github.com/dotnet/aspire/assets/85643503/1597f287-001b-4254-bd0c-d3137054fcab">

I suspect this error might be because the "Framework" field in the Add Aspire dialog was empty, but the dropdown for that field gives no options:

<img width="443" alt="Pasted Graphic 1" src="https://github.com/dotnet/aspire/assets/85643503/db612747-74e8-45b1-aa95-8e1ecf61062c">

How do I get around this?

**Comment by tlmii** [comment]
@phenning @BillHiebert FYI

**Comment by BillHiebert** [comment]
The OK button is supposed to be disabled if there are no frameworks listed, but it appears that isn't working. The set of frameworks comes from the templates, so when this is empty it generally means VS thinks there are no Aspire templates.  The templates are delivered via the Aspire workload and may not be installed. From a command prompt you can run the following to see if the aspire workload is installed:
dotnet workload list

if Aspire is not listed try running

dotnet workload install aspire
dotnet workload update

**Comment by mikekistler** [comment]
Thanks ... that worked.

But I don't know why the Aspire workload was not already installed. I had followed the directions on this page:

https://learn.microsoft.com/en-us/dotnet/aspire/setup-tooling?tabs=visual-studio#install-net-aspire

**Comment by DamianEdwards** [comment]
@joperezr @danegsta any thoughts as to why the workload wouldn't be installed for Int Preview users?

**Comment by danegsta** [comment]
@DamianEdwards this looks to be related to making the Aspire component optional/recommended in VS setup. The `Add .NET Aspire Orchestration Support...` action in VS doesn't appear to be conditioned on the workload being installed. We should open up an issue on the tooling to check that the workload is installed (and guide the user to acquire it if not) during the add orchestration support flow.

**Comment by joperezr** [comment]
> @joperezr Jose Perez Rodriguez FTE @danegsta David Negstad FTE any thoughts as to why the workload wouldn't be installed for Int Preview users?

The only thing that comes to mind is that I recall someone telling me that for recommended features (like the Aspire) they would only be checked by default if you are installing that VS band for the first time, but not when you are doing a version update. Only required features get installed during version updates, so I wonder if this is why @mikekistler is hitting this.

**Comment by danmoseley** [comment]
Anything left here or can this be closed?

**Comment by DamianEdwards** [comment]
Yeah I think this is fine to close now?

**Comment by mikekistler** [comment]
Agreed. Closing.
