### ISSUE TITLE
Executable with WithDaprSidecar does not start sidecar 

### ISSUE THREAD

**Issue by JohnVottero** [dotnet/aspire#1091]
With code like this in AppHost:

```
builder.AddExecutable("sample-app", "C:/sample-app/sample-app.exe", "C:/sample-app/", [])
    .WithDaprSidecar("sample-app");

```
At run time, the sample-app.exe executable is started but the Dapr sidecar is not.

My workaround is to pass a complete Dapr command to AddExecutable but is an incomplete solution (i.e. I don't know the metrics port).

**Comment by davidfowl** [comment]
Can you make a full solution with a repro on github so we can reproduce the problem?

**Comment by JohnVottero** [comment]
Here is a full solution that reproduces the problem:

https://github.com/JohnVottero/AspireWithDaprAndExe

It is a clone of the AspireWithDapr sample with one change in AddHost's Program.cs. After the change, clicking the "Weather" link in the web front end gets nothing but "Loading..." and an exception in the log.

**Comment by davidfowl** [comment]
You have dapr installed an running right?

**Comment by JohnVottero** [comment]
Yes, I have Dapr installed. The unmodified AspireWithDapr sample works.

**Comment by davidfowl** [comment]
I notice your executable isn't listening on any ports (using WithServiceBinding). When you use a project, we have launch settings to determine what to listen on and bind to. When you call AddExecutable, you need to tell the system what to listen on.

**Comment by davidfowl** [comment]
> Looking at DaprDistributedApplicationLifecycleHook.cs in the Aspire.Hosting.Dapr project, the BeforeStartAsync method iterates through the Project resources and adds a Dapr Sidecar ExecutableResource for each project that needs it but, it doesn't iterate through the Executable resources to see if they need a Dapr sidecar. Isn't that the root problem?

Yes, this is the core of the issue. 

I think you still need to expose an http endpoint from your app (https://github.com/dotnet/aspire/blob/c694a69189cb1579c326944cf8cf2975b1971bea/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs#L1510.

There's some big churn happening right now to support dapr components and dapr deployment to aca (https://github.com/dotnet/aspire/pull/862). I think after this PR is in, you can send a PR or we'll attempt to fix it (either is fine).

Thanks for the report!
