### ISSUE TITLE
Use EffectiveEnv for ContainerViewModel computation

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspire#1114]
We are adding EffectiveEnv for Containers in dcp now, we need to start consuming it for ContainerViewModel.

**Comment by drewnoakes** [comment]
@smitpatel what's the desired approach here? Should we replace use of `Env` with `EffectiveEnv` or do we want to merge/fallback somehow?

**Comment by drewnoakes** [comment]
It's ok, I worked this out.

`EffectiveEnv` is available on the container status message.

While debugging this I found that the code we were using to call docker to get the effective environment variables was not working anyway. I'm removing it and using the data from DCP instead in #1288.
