### ISSUE TITLE
Accessibility and screen reader support for console logs

### ISSUE THREAD

**Issue by tlmii** [dotnet/aspire#1124]
We need to look at how keyboard support and screen reader support work in the console logs at the moment and if that meets the bar we have set for ourselves. One specific callout from the UX board was to make sure that the logs are read line-by-line (and can be navigated as such) and not as one long block of text.

**Comment by adamint** [comment]
this is actually subsumed by #168 as part of bullet 3: ensuring that live regions are added where appropriate. Here, it would be by using the `log` role. Closing this issue
