### ISSUE TITLE
Keyboard accessibility for Summary/Details View

### ISSUE THREAD

**Issue by tlmii** [dotnet/aspire#1126]
This came from the UX Board meeting today. 

We should add keyboard shortcuts for things like increase/decrease split (currently only available via mouse drag, toggling orientation (there's a button, but it'd be nice to have a more global handler so keyboard users don't have to tab all over the place to get to it) and closing the details panel (same as for the orientation toggle). 

This would be in addition to keyboard work done as part of #1081.

**Comment by adamint** [comment]
@tlmii How should we expose the list of keyboard shortcuts?
cc @leslierichardson95  @kvenkatrajan

**Comment by tlmii** [comment]
That's a good question. I don't know what the right thing is there. We don't have any in-product help at the moment, though I suppose this would be a good first thing to go in there. Some of them could be added to tooltips/aria-labels I suppose (e.g. for the details panel close button) but others don't have a great place for that (e.g. the splitter bar). @IEvangelist is that something that we'd ordinally want in the documentation as well?

**Comment by IEvangelist** [comment]
> @IEvangelist is that something that we'd ordinally want in the documentation as well?

No, not typically. I believe that's something that's best within the app itself. For example, if you hold <kbd>Alt</kbd>, then you could render characters over the top of certain elements that could be interacted with. Does that make sense?

Imagine for example, while holding <kbd>Alt</kbd> a button or link, or some element that is keyboard accessible would render a hint to the user, such as `1`. If the user was to press `1` while they were still holding <kbd>Alt</kbd>, that element would be engaged.

**Comment by leslierichardson95** [comment]
Maybe we can include a list of them in the settings tab somewhere or as part of related tooltips?

**Comment by kvenkatrajan** [comment]
I like that something - identical to the design in word while hovering over Bold, Italics etc.

![image](https://github.com/dotnet/aspire/assets/102772054/82273b5c-040b-49a1-b9cd-2396b9a473f7)

@leslierichardson95  do we have a list of items we would like to add keyboard short cuts to?

**Comment by kvenkatrajan** [comment]
I see what you mean - for the scenarios you mentioned might be a little undiscoverable.

github uses ? and outlook shift ? to display the list of shortcuts in the modal. Would that suffice for this experience?

**Comment by leslierichardson95** [comment]
I'm cool with having a modal or some other popup / page accessible via the settings menu to view a full list of user shortcuts.  @kvenkatrajan I'm a little confused by what you're referring to when you say "github uses" and "outlook shift" however.

**Comment by kvenkatrajan** [comment]
@leslierichardson95  - My apologies if I wanst clear, if you type "?" anywhere on a github page (for example this one) it will bring up a modal with a list of all the shortcuts.

**Comment by leslierichardson95** [comment]
The more I think about it, maybe we could also consider having a help icon (ie a question mark) next to the settings gear icon where users can view help info such as keyboard shortcuts. 🤔

**Comment by tlmii** [comment]
We have the help icon there already that takes you to the online documentation. I guess we could repurpose it to launch a dialog of some sort with a "more help" link to the full documentation?

**Comment by danmoseley** [comment]
> @leslierichardson95  - My apologies if I wanst clear, if you type "?" anywhere on a github page (for example this one) it will bring up a modal with a list of all the shortcuts. 

I've used GitHub for 10 years and didn't know that, so it might not be discoverable..

**Comment by IEvangelist** [comment]
> > @leslierichardson95  - My apologies if I wanst clear, if you type "?" anywhere on a github page (for example this one) it will bring up a modal with a list of all the shortcuts.
> 
> I've used GitHub for 10 years and didn't know that, so it might not be discoverable..

GitHub has a lot of hidden features that aren't very discoverable. Lots of time they share details to them at the bottom of a scrollable page with the info icon in tiny text.

**Comment by kvenkatrajan** [comment]
The keyboard shortcut to display a list of shortcuts is not specific to github, it was just an example sited - there are several other sites/platforms that have adoped that pattern. 
azure dev ops : ? - https://learn.microsoft.com/en-us/azure/devops/project/navigation/keyboard-shortcuts?view=azure-devops#web-portal-global-shortcuts
outlook : Shift + ?
While ? or shift + ?  is not a strict accessibility standard it is a widely accepeted convention for easily accessing the list of keyboard shortcuts for end users that use keyboard navigation coupled with screen reader support : https://www.w3.org/WAI/perspective-videos/keyboard/. If we are aiming for consistency with some of our existing products we should consider supporting Shift + ?
I hear you on the discoverability @danmoseley especially if users are not familiar with this convention. We should consider alternative approach for better discoverability in tandem, like what @tlmii suggested : 
> We have the help icon there already that takes you to the online documentation. I guess we could repurpose it to launch a dialog of some sort with a "more help" link to the full documentation?

Running this by UX board will be helpful :)  CC: @leslierichardson95
