### ISSUE TITLE
Add a hosting helper method for adding a persistent volume mount to containers

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#1132]
Related #974

As part of putting together the sample in dotnet/aspire-samples#52 it was suggested a new helper method could be added to `Aspire.Hosting` to make this scenario simpler, e.g.:

```csharp
var database = builder.AddSqlServerContainer("sqlserver", "abcdefg123_78")
    .WithPersistentVolume("/var/opt/mssql")
    .AddDatabase("appdb");
```

The method `WithPersistentVolume` would be a shortcut to `WithVolumeMount(string source, string target, VolumeMountType type, bool isReadOnly)` with `source` being generated from the application name and resource name, e.g. `$"{builder.Environment.ApplicationName}.{resourceName}.data"`, and `type` being `VolumeMountType.Named` and `isReadOnly` being `false`.

**Comment by mitchdenny** [comment]
Where would the volume mount be rooted? I like the idea generally, just need to figure out a few details.

**Comment by DamianEdwards** [comment]
It makes me wonder whether the current shape of `WithVolumeMount` is actually confusing and conflating "Bind mounts" with "Volumes". Perhaps we should be revisiting that.

**Comment by josephaw1022** [comment]
Similar to https://github.com/dotnet/aspire/issues/837#issuecomment-1849048553

**Comment by mitchdenny** [comment]
I think that there is an argument that volumes should be their own resource. In k8s volumes are a discrete resource often with a specific provider to get away from host specific volume mounts (e.g. ceph). In the cloud (using Azure as an example) you might use Azure Files or Azure Container Storage.

**Comment by DamianEdwards** [comment]
@mitchdenny as long as it doesn't complicate the really simple scenarios like the one this issue relates to.

**Comment by stbau04** [comment]
Created a seperate issure for splitting the current WIthVolumeMount into two methods (one for bind mounts and one for named volumes): https://github.com/dotnet/aspire/issues/1437

**Comment by DamianEdwards** [comment]
Now that #1437 is complete and we have separate `WithBindMount` and `WithVolumeMount` methods, I'm not sure there's anything left to do here. Folks who want a persistent volume on a container resource now do something like this:

```csharp
var database = builder.AddSqlServerContainer("sqlserver", "abcdefg123_78")
    .WithVolumeMount("data", "/var/opt/mssql")
    .AddDatabase("appdb");
```

The only thing I can think that might be worth adding is that right now it's hard to name the volume based on the application/resource names, but that might be better left to more domain-specific helper methods like #837.

Thoughts @davidfowl @JamesNK?

**Comment by davidfowl** [comment]
Agreed, I think we follow the model that @mitchdenny introduced for emulators (UsePersistence()) though maybe we rename it 😄
