### ISSUE TITLE
Postgres is wide open with super user access

### ISSUE THREAD

**Issue by robconery** [dotnet/aspire#1143]
I was inspecting the Postgres container and the `POSTGRES_HOST_AUTH_METHOD` is set to `trust`, which allows anyone with access to 5432 to do anything they want with the database. Given that we're not running inside of a network (like Docker Compose or K8s might give you), it seems like this might not be a good idea.

Here is a snapshot of `docker inspect`:

![screenshot_227](https://github.com/dotnet/eShop/assets/78586/959e240b-3cdf-4a08-858a-91f85f0e1695)

Given that I'm not totally familiar with Aspire just yet, there might be a setting I'm not seeing. If that's the case, I might recommend a README for sysadmin types so they understand what protections are in place.

**Comment by eerhardt** [comment]
> and definitely not suitable for a production setup.

All these Hosting containers are meant for local development.

cc @mitchdenny

**Comment by roji** [comment]
Thanks @eerhardt, in that case I guess the question is what exactly we want to show in eShop.. if it explicitly shows practices that are only suitable for local development, then we should be good.

**Comment by DamianEdwards** [comment]
To be super explicit, when one calls `builder.AddPostgresContainer` in their AppHost project, that results in a container being used when running the AppHost project locally. The AppHost project is never deployed anywhere. Instead, a manifest is produced from the AppHost project that details a `postgres.v0` resource (not a Postgres container specifically) and then it's the responsibility of the specific deployment toolchain to map that resource type to a suitable resource in the target environment. The auth method used by the container we produce for local development doesn't flow anywhere beyond that scenario.

**Comment by robconery** [comment]
I think if we make assumptions "X should never be used in Y" then it should be spelled out somewhere if this is to be called a "reference app". In this situation, the customer would have to undo what's been done in order to be safe in production which means they have to know it's there to begin with.

My suggestion would be to generate some kind of password in the environment, or in some secret place. Not sure how that's done here but hopefully it's not super hard.

**Comment by DamianEdwards** [comment]
> In this situation, the customer would have to undo what's been done in order to be safe in production which means they have to know it's there to begin with.

That's not true though. Sorry if I'm explaining it poorly, but the configuration of the local container we provision for Postgres does not in anyway relate to what's deployed. Those are separate concerns.

**Comment by robconery** [comment]
Thanks @DamianEdwards - yeah I can see the AppHost code here that you mention. I'm just getting to know Aspire and I guess I have to dig in a bit more as I'm not too sure how "cloud native" and deployment etc work. That's probably the gap I'm having on this - I'll dig in!

**Comment by sebastienros** [comment]
The resource accepts a password and generates one if not set. Can't we alter the connection string with this password and remove `POSTGRES_HOST_AUTH_METHOD = true`? Wouldn't it work locally too?

**Comment by DamianEdwards** [comment]
Yes, but we should consider whether that's actually a better local user experience. If the container lifetime is tied to the app session in inner-loop and connection is limited to the local machine then is the trade off worthwhile? Automatic trust can be useful as it's much easier to connect other tools to the instance for debug purposes as part of the dev inner-loop (think how using SQL localdb is super easy).

**Comment by mitchdenny** [comment]
We ended up making some changes during our rework of the API. We now require a password (no longer using trust). It still isn't suitable for use outside of local development for various reasons.

**Comment by mitchdenny** [comment]
https://github.com/dotnet/aspire/blob/818ac20c740c58d6d63694f26b90f48ba27e6fc8/src/Aspire.Hosting/Postgres/PostgresBuilderExtensions.cs#L33C35-L33C35
