### ISSUE TITLE
Publish Microsoft.NET.Sdk.Aspire.Manifest-8.0.100 = 8.0.0-preview.1.23551.7

### ISSUE THREAD

**Issue by iii-i** [dotnet/aspire#1144]
Building .NET 8.0.100 from source on the s390x platform fails with:
```
Unable to find package [Microsoft.NET](http://microsoft.net/).Sdk.Aspire.Manifest-8.0.100 with version (= 8.0.0-preview.1.23551.7)
```
And indeed, this version cannot be found neither on NuGet nor in .NET 8 repositories, even though it's referenced by the installer: https://github.com/dotnet/installer/blob/v8.0.100/eng/Version.Details.xml#L175

Please publish Microsoft.NET.Sdk.Aspire.Manifest-8.0.100 = 8.0.0-preview.1.23551.7.

**Comment by joperezr** [comment]
Thanks for reporting the issue @iii-i. I have pushed the missing version to nuget.org, and it is currently validating, but should be listed soon. Closing as this issue is resolved, but please do  feel free to re-open if you have any follow up questions.
