### ISSUE TITLE
AddDisableGrpcLoadBalancingFilter missing in UseServiceDiscovery?

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspire#1158]
I was checking the Service Discovery code and find something that looks like a bug. `HttpClientBuilderExtensions.UseServiceDiscovery`  method has two overload. One will get `IServiceEndPointSelectorProvider` from the input and the other get it from DI. It seems to me that theses two methods have to be the same, but only one of them have `AddDisableGrpcLoadBalancingFilter`. Wondering if this is a bug.

https://github.com/dotnet/aspire/blob/3bed3eab52767e5b201d2103f69951514d2810df/src/Microsoft.Extensions.ServiceDiscovery/Http/HttpClientBuilderExtensions.cs#L25

**Comment by DamianEdwards** [comment]
@ReubenBond

**Comment by ReubenBond** [comment]
Hi @Kahbazi, you're right - well spotted

**Comment by ReubenBond** [comment]
I've opened https://github.com/dotnet/aspire/pull/1160 to rectify this
