### ISSUE TITLE
Container vs. abstract resource rework

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#1164]
We are going to be reworking the API surface for the AppHost to reintroduce the concept of abstract resources (e.g. AddRedis and AddPostgres). We'll keep AddPostgresContainer and AddRedisContainer for folks that want to treat them like containers and manipulate them, but we want to encourage the use of the abstract APIs.

Here is the formula we want to apply (using Redis as an example):

1. New AddRedis method which returns an RedisResource 
2. Keep AddRedisContainer which returns RedisContainerResource
3. Nuke AddRedisConnection

RedisResource would be virtually identical to RedisContainerResource today, but it would not derive from ContainerResource. RedisContainerResource would be modified to emit container.v0 into the manifest (just like any other container). We don't think we need the XYZConnectionResource since these don't add any value above just setting an environment variable.

**Comment by davidfowl** [comment]
cc @ellismg @prom3theu5

**Comment by prom3theu5** [comment]
Sorry out travelling back home today from a meeting
Just playing catch up

WithConnectionString sounds like a nice builder extension to have, as long as it emits something thats unified across the container types - that way in downstream tools we can simply have it as a nullable string on deserialisation - if its populated then great, handle it - if not just treat as null and do nothing

That gives us the ability to just treat all the different container types as this abstract entity that *may* have certain properties etc, and we'd just need to know the parent aspire component type (container.v0), nothing more.

**Comment by prom3theu5** [comment]
Thats a good question really

Certainly from a downstream deployment point of view, cli tools like AZD and Aspir8 can handle this at configuration / deployment time - a user should be able to select if they require persistence, and ultimately then what persistence is used, its analogous, and opt in based on the flow.

For local startup / debugging though - it should probably also be opt in, i mean my dev environments can sometimes exist for days on end before I'll clear it down depending on what story I'm working on.

**Comment by davidfowl** [comment]
The main difference is that container resources will never turn into anything but container resources. redis.v0 might be azure redis or an aca addon, or a container, or a secret. The deployment environment decides what this abstract resource turns into. 

container.v0 will always be a container, locally and remotely.

**Comment by DamianEdwards** [comment]
> container.v0 will always be a container, locally and remotely.

Yep, understand that part.

But it seems like our paved-path scenario for things like Redis would now be `AddRedis` which doesn't expose container customization features for local dev anymore, e.g. using volume mounts, so now if I want to do that, I have to do the switching manually in my AppHost code, yes?

**Comment by davidfowl** [comment]
That's correct.

**Comment by DamianEdwards** [comment]
So would the plan be to update the current starter app template code to look something like the following then? Or would we just change it to `AddRedis` and leave it the customer to make this change if and when they want to customize the local container?

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.Environment.IsDevelopment()
    ? builder.AddRedisContainer("cache")
    : builder.AddRedis("cache");

var apiService = builder.AddProject<Projects.MyApp_ApiService>("apiservice");

builder.AddProject<Projects.MyApp_Web>("webfrontend")
    .WithReference(cache)
    .WithReference(apiService);

builder.Build().Run();
```

**Comment by prom3theu5** [comment]
> It would just be AddRedis in the starter template because we want people to think in terms of abstract resources for that because when it comes to deployment you want to use the target clouds managed service

> var cache = builder.Environment.IsDevelopment()
    ? builder.AddRedisContainer("cache")
    : builder.AddRedis("cache");

I think the main problem with this is going to be the starter template is first thing someone unfamiliar with aspire is likely to see outside of the docs. Right at that stage they're probably not thinking down the line - how will I deploy this, or what do i need etc. As soon as they go to add a resource they are going to be immediately hit with a wall of what appears to be duplicate methods:

- AddRedis
- AddRedisContainer
- AddPostgres
- AddPostgresContainer
- AddRabbitMq
- AddRabbitMqContainer
- Add SqlServer
- AddSqlServerContainer
etc

So much entropy

Has it been considered to possible retain only a single method for each type - AddRedis() etc, but with the ability to chain it with something like .AsContainer() or something like that, to mutate it to container.v0?

**Comment by prom3theu5** [comment]
> but this feels like a place where it's going to be really common for folks to have to change their code to get different behavior between inner-loop and deployment because our defaults aren't flexible enough.

Which is pretty bad imo - as straight away you are producing what is essentially two different bill of materials files, completely opinionated about where they are to run.  Feels regressive

**Comment by DamianEdwards** [comment]
It feels like we need more thinking around what we expect WRT to defaults and code patterns for differentiating config of resources running in the inner-loop vs. those published to the manifest. A similar question came up about the `.UseEmulator()` method on the Azure Storage resource, i.e. should it be guarded by the calling code to ensure it's only called during inner-loop, or does the method implementation self-guard based on the context/environment? I think we'd want some consistency, similar to how in ASP.NET Core we have defaults that only apply in the Development environment, and others where we expect the user to do the guarding.

**Comment by prom3theu5** [comment]
I think so too. Forgive me for over stepping lol (I know I was only cc-ed in to make me aware about the changes 😝 ) But I think anything that is guarded should also have a way to bypass the guard. That way everything can be guarded by default, but a client that requires more than the defaults can jump the fence / open the gate etc.

In the case of UseEmulator (not seen it) - does that actually launch the emulator (i'm guessing Azerite if its AS) and if so is that as an executable or as a container, or does it just change produced connection string to UseDevelopmentStorage?

**Comment by davidfowl** [comment]
The template uses abstract resources. Any container customization will require changing the default template code to use `AddRedisContainer`. In preview3, we'll experiment with [patterns like this](https://github.com/dotnet/aspire/issues/1164#issuecomment-1836720579) and get more feedback.
