### ISSUE TITLE
Automatically assigned a randomly generated application URL for ASP.NET Core projects with single replica to avoid launch profile conflicts

### ISSUE THREAD

**Issue by asimmon** [dotnet/aspire#1172]
Hi,

When adding an ASP.NET Core project with at least 2 replicas, each instance of the web app is assigned a random port, regardless of the defined launch profiles.

However, with a single replica, .NET Aspire typically attempts to retrieve the application URL from the first launch profile. This behavior persists unless `WithLaunchProfile()` is explicitly called or the `DOTNET_LAUNCH_PROFILE` environment variable is set.

In my case, there's no certainty that the launch profiles will not conflict. Therefore, I would prefer for .NET Aspire to automatically assign an URL with a randomly available port, similar to its approach with multiple replicas.

I know I can specify my own service binding (`WithServiceBinding` with a different name than the launch profile name), but then I would have to assign a random port myself. Although it is fairly trivial to determine a randomly available port, I would rather let .NET Aspire do the job for me and completely ignore any launch profiles.

EDIT 1: Wait a moment... `WithServiceBinding` doesn't throw, and it appears as a second URL in the dashboard, however it isn't used in `ASPNETCORE_URLS`. Only the URL from the launch profile is there.

**Comment by DamianEdwards** [comment]
I believe this has been changed/fixed for preview 2 already, such that the launch profile URL will always be used for the proxy tier whether configured to use replicas or not, @davidfowl?

**Comment by davidfowl** [comment]
Part of https://github.com/dotnet/aspire/pull/946. Also related to https://github.com/dotnet/aspire/issues/567

**Comment by davidfowl** [comment]
This was added in https://github.com/dotnet/aspire/issues/1849. You should be able to exclude the launch profile and define your own endpoints
