### ISSUE TITLE
How to do Containers database configuration before applications start?

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspire#1176]
So, I have this demo project where all of the apps use the same database.
I want to use the containers database easily configured by the Distributed Builder, however, the database requires some initial data inserted like supported cultures, default roles, etc.
Basically I need to do the following before the apps start
* Start the Database container
* Instantiate a DbContext
* Invoke EnsureDatabaseCreate methods
* Insert the data using the SqlRaw methods

I have done all of that from each app, the problem I have is that, since I have no control of the order in which they start, it works sometimes others it throws errors.

This is the sample host I currently have:
https://github.com/pticostaricags/FairPlayCombined/blob/main/src/FairPlayCombinedSln/FairPlayCombinedSln.AppHost/Program.cs

When I have tried to do it from the AppHost I get error like the one in the second screenshot
Screenshot 1
<img width="568" alt="image" src="https://github.com/dotnet/aspire/assets/3481899/482c99ed-3455-4020-8a95-44f483bc3ee0">

Screenshot 2
<img width="473" alt="image" src="https://github.com/dotnet/aspire/assets/3481899/acc0d890-1944-4d98-a1ae-8c965c225ff5">

Screenshot 3
<img width="532" alt="image" src="https://github.com/dotnet/aspire/assets/3481899/348d9ab6-bc29-451d-aca3-945a0b485a38">

Is there any way I could do the mentioned configuration before the applications start?
Even more than that, as for my knowledge, my attempt would probably work only for development environment, but what would be the recommended approach for having auto-configured containers, when you have multiple apps or microservices using the same database container, and that would actually work for a deployed platform.

**Comment by DamianEdwards** [comment]
Currently, no. We discussed this previously and felt it was better to not guarantee order and availability as it's antithetical to good distributed application design, i.e. apps should be resilient to dependencies being temporarily unavailable. If you look at our [eShopLite sample](https://github.com/dotnet/aspire-samples/tree/main/samples/eShopLite), you'll see that it has an app dedicated to initializing the database that runs alongside the other apps.

**Comment by efonsecab** [comment]
> Currently, no. We discussed this previously and felt it was better to not guarantee order and availability as it's antithetical to good distributed application design, i.e. apps should be resilient to dependencies being temporarily unavailable. If you look at our [eShopLite sample](https://github.com/dotnet/aspire-samples/tree/main/samples/eShopLite), you'll see that it has an app dedicated to initializing the database that runs alongside the other apps, and it uses EF execution strategies to ensure retries occur. Similarly, the frontend app is designed to be resilient to the basketservice being unavailable, not showing the associated UI unless the basketservice can be contacted.

Thanks, the sample worked great as a guide.
Closing this.
