### ISSUE TITLE
Make viewing exceptions inline better in dashboard

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1177]
Today the only way to get the entire exception is to hover over the text to see the full thing or to copy it and paste elsewhere:

<img width="997" alt="image" src="https://github.com/dotnet/aspire-samples/assets/95136/b10e7d50-4e76-466c-9cbc-9ee6495656b0">

Video:

https://github.com/dotnet/aspire-samples/assets/95136/69029664-2a2f-4ab3-a3c1-25f74088959e

**Comment by DamianEdwards** [comment]
YES! I went through this myself this week and was actually confused by how hard it was to find the exception message.

**Comment by smitpatel** [comment]
Would making exception stack trace value which can be multiline to be text area with n lines and scroll bar if large stack trace help?

**Comment by davidfowl** [comment]
Yes, I think so (like the console log output?)

**Comment by smitpatel** [comment]
Yes like the console output but not whole page height.

**Comment by leslierichardson95** [comment]
Couple ideas for improving this experience:

- Display preview of primary error when hovering over the error icon
- Click on the error icon to either display full error message in a new location (i.e. modal, inline with the graph, etc) or redirect the user to the additional info subpage containing the full error message.  Might be good to include a prompt telling the user to click on the trace for more info about the error for discovery purposes

**Comment by dersia** [comment]
a copy button would also be great, so I can copy it right away and search for it online. and if we can have a link to open my ide and take me to the file, line and column where the exception was thrown that would make the Dashboard even more powerfull.

when I think about that, I think for production or staging scenarios, it could also be very useful, if the link could take me to the SourceLink on my repo, if SourceLink data is available.

**Comment by davidfowl** [comment]
I love the idea but it’s out of scope for this issue.

**Comment by dersia** [comment]
well maybe just the copy button then 😅
