### ISSUE TITLE
The argument for AddDatabase represents a database and a connection string name at the same time

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspire#1199]
Let's take this example for PostgreSQL:

```csharp
var catalogDb = builder.AddPostgresContainer("postgres").AddDatabase("catalogdb");
```

![image](https://github.com/dotnet/aspire/assets/1165805/b5237fa7-59b0-45c8-b9e8-3d99adff4da6)

`"catalogdb"` is both the name of the database (a technical name), and the name of the resource (a logical name).
 
As a developer when I read `AddDatabase(string name)` I understand that is can be a database name, as in `CREATE DATABASE "catalogdb"`.
 
But in the app when I do `builder.AddNpgsqlDbContext<CatalogDbContext>("catalogdb")` it's asking for a `connectionName`.
 
Though the documentation for AddDatabase(string name) is clear:

> The name of the resource. This name will be used as the connection string name when referenced in a dependency.
 
It seems like we should be able to provide a database name and a resource name (or connection string name), because we might want them to be different, or change independently.

The `name` argument should also be changed to remove the ambiguity.

**Comment by davidfowl** [comment]
Are you going to make this change @sebastienros ?

**Comment by sebastienros** [comment]
I am willing to, was waiting for some kind of triage before, and maybe comments.

**Comment by sebastienros** [comment]
@davidfowl I don't think it an ship in next preview, right?

**Comment by DamianEdwards** [comment]
We should do this for next preview. Thoughts @mitchdenny?

**Comment by mitchdenny** [comment]
I think we need to do this (created an issue recently for the same thing). Next preview seems fine. I think the usage of IResource.Name is quite pervasive so each usage will have to be scrutinized, especially where connection strings are concerned.

There is a related aspect to this in the context of the proposed metadata field (#1619). For cloud deployment tools we may wish to have a different resource name than that specified in the app model - especially when approaching brownfields work.

**Comment by mitchdenny** [comment]
@sebastienros are you still working on this? Loop in @ellismg for the AZD side of things.

**Comment by sebastienros** [comment]
Yes I will work on that very soon.
