### ISSUE TITLE
Support homebrew installed dapr

### ISSUE THREAD

**Issue by onionhammer** [dotnet/aspire#1211]
Homebrew is one of the supported installation options ( https://docs.dapr.io/getting-started/install-dapr-cli/#install-from-homebrew ), but does not work with aspire.

fork/exec /usr/local/bin/dapr: no such file or directory

> which dapr
> /opt/homebrew/bin/dapr

**Comment by davidfowl** [comment]
cc @philliphoff

**Comment by onionhammer** [comment]
@davidfowl sure, I can do that

**Comment by philliphoff** [comment]
Just adding a note that, in the meantime, one can configure Aspire to point to an arbitrary path for the Dapr CLI, using the `DaprPath` property of the `DaprOptions` type.  That said, given it's a documented means of acquiring Dapr, the Aspire logic should look for it there if not found elsewhere (on MacOS).

**Comment by onionhammer** [comment]
@philliphoff Ok, also added some flexibility around user-installed paths (i.e. "Installing a specific CLI version without sudo")

**Comment by onionhammer** [comment]
This is still an issue in preview 2

**Comment by davidfowl** [comment]
That’s right it wasn’t fixed in preview 2

**Comment by onionhammer** [comment]
I feel like there's an echo in here 🤭
