### ISSUE TITLE
PID display in the dashboard in cloud scenarios

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1215]
Process ID (PID) is displayed on the resource grid:
![image](https://github.com/dotnet/aspire/assets/303201/87fde042-6efa-4f46-804e-f65c5e56f80a)

What should happen if PID isn't available? IMO, a quick fix is to not display anything if the PID is zero/null/empty.

**Comment by DamianEdwards** [comment]
> IMO, a quick fix is to not display anything if the PID is zero/null/empty.

👍

**Comment by JamesNK** [comment]
This might not be an issue. A deployed app will have containers instead of projects.

**Comment by davidfowl** [comment]
we removed this in the latest.
