### ISSUE TITLE
Allow to Use Aspire As OLTP Collector

### ISSUE THREAD

**Issue by jp1482** [dotnet/aspire#1219]
This is not an issue and this is up to product team to make decision. 

- Currently if OTLP exporter endpoint configured as environment variable then it export to endpoint listen to Aspire host and display OpenTelemetry ( Logging , Metrics , Trace)

Now even if I don't use entire Aspire ecosystem but my existing application just configure OTLP endpoint in environment variable and configure OpenTelemetry for Logging, Metrics and Trace like it will be done in ServiceDefaults then it can display those data and it does required other stuff. 

- Overall it is like separating Grpc service that receive data and UI component that display data but some configuration can allow this.

**Comment by davidfowl** [comment]
The dashboard will be runnable as a separate tool (and container image) that you can run https://github.com/dotnet/aspire/issues/1003. If you don't have a resource server, the resource view wont' work but the OTLP endpoint will still work. This will be part of a future release.

**Comment by jp1482** [comment]
@davidfowl Thanks for response. Yes, I am looking similar functionality that mention in #1003.  I am closing this.
