### ISSUE TITLE
Executable should show resolved args

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1226]
Maybe we should also show this in the details pain [described here](https://github.com/dotnet/aspire/issues/1208)

<img width="680" alt="image" src="https://github.com/dotnet/aspire/assets/95136/2d5e120f-69b1-420e-9b32-24fd0b7c80a2">

Seems like we get the raw args before the values are substituted. We should get the effective arguments.

cc @karolz-ms

**Comment by davidfowl** [comment]
Sounds like a feature request from dcp then!

**Comment by karolz-ms** [comment]
The feature is present; we just need to update the object definitions on the .NET side like @smitpatel said.
