### ISSUE TITLE
Otel service name not working with dapr scenario

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1228]
Seems like the names aren't right.

![image](https://github.com/dotnet/aspire/assets/95136/dc227d4e-82ac-41fc-a3e8-ebb8ef390ef0)

**Comment by davidfowl** [comment]
@philliphoff can you take this to the dapr team?

**Comment by philliphoff** [comment]
@davidfowl It looks like this has been asked for before (see: [dapr/dapr#5942](https://github.com/dapr/dapr/issues/5942)) but didn't make the cut in prior versions.  I've asked the maintainer if they're still interested.

(Just for fun I tried @danegsta's suggestion but it didn't seem to change the tracing behavior, though that may just be my poor Golang skills.)

**Comment by philliphoff** [comment]
Also submitted #1272 to make it easier to test changes to the Dapr runtime with Aspire.

**Comment by DamianEdwards** [comment]
Moving out of preview.2 given it's a DAPR issue.

**Comment by davidfowl** [comment]
This is an external issue we're waiting for the dapr team to resolve @philliphoff

**Comment by philliphoff** [comment]
The needed change is under review but, unfortunately, could not fit into 1.13.

**Comment by WhitWaldo** [comment]
The underlying change has been merged into 1.14
