### ISSUE TITLE
Identify replica sets for dashboard

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspire#1233]
We don't have proper display for replica set yet (see #567), but as mentioned in #1229, we need to know sometimes how many replicas a resource have. Having a proper mechanism to identify would be helpful.

**Comment by davidfowl** [comment]
It means "we want to do this before we ship GA but we don't know which preview this fits into as yet, but it's not being punted until after GA (which is future)".

**Comment by kvenkatrajan** [comment]
@davidfowl  you beat me to it :)

**Comment by smitpatel** [comment]
We should do this earlier. We are having more places where we need to identify replicas (endpoints and naming are 2). For every time we have to iterate over whole list. (The display of replica set can come later in UI)

**Comment by adamint** [comment]
@kvenkatrajan this should be re-triaged. I do not know what app-model/dcp work has been done, as currently we parse the specific resource name format to compute replicas. We shouldn't be doing that long-term

**Comment by DynConcepts** [comment]
Just an FYI:.... been (attempting) to get through eShop.... I *think* (right now me head hurts)  replicas (in the branch but not in main?!?!?!) had me chasing my tail most of the day.....

**Comment by davidfowl** [comment]
@kvenkatrajan moving to this to 8.1
