### ISSUE TITLE
Please include AddSqlServerDbContextFactory

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspire#1241]
Somewhat related to #1194 

When working with Blazor Server apps it is recommended to use IDbContextFactory for Dependency Injection.
It would be useful for the aspire component to have an additional method for this scenario: "AddSqlServerDbContextFactory".

**Comment by eerhardt** [comment]
Thanks for the suggestion.

This will be resolved when #1403 is done, as you will be able to call `builder.Services.AddDbContextFactory` directly. I'm going to close this for now and use #1403 to track the work.
