### ISSUE TITLE
Adding Aspire Orchestration Causes Errors When Using Directory.Packages.props

### ISSUE THREAD

**Issue by ardalis** [dotnet/aspire#1253]
Add support for solutions using:

```xml
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
```
and `Directory.Packages.props` files. Currently when adding Aspire Orchestrator Support to an existing web app you get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: OpenTelemetry.Instrumentation.AspNetCore;OpenTelemetry.Instrumentation.GrpcNetClient;OpenTelemetry.Exporter.OpenTelemetryProtocol;OpenTelemetry.Instrumentation.Runtime;Microsoft.Extensions.Http.Resilience;Microsoft.Extensions.ServiceDiscovery;OpenTelemetry.Extensions.Hosting;OpenTelemetry.Instrumentation
ServiceDefaults.csproj	1	
and AppHost.csproj (which only has one reference but still includes the version in the csproj file).

**Comment by DamianEdwards** [comment]
This is an issue for all .NET project templates, not just Aspire, and is being tracked by NuGet at https://github.com/NuGet/Home/issues/12967
