### ISSUE TITLE
Console logs: Remember last selected resource

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1261]
I added logic to the metrics page to remember the last selected resource. If you navigate away and come back, it is automatically re-selected. We should do the same thing on the console logs page.

![console-logs-remember](https://github.com/dotnet/aspire/assets/303201/46212d08-3c5c-42ae-b267-0e328c9a81d2)

Metrics page saves the selected state in `ProtectedSessionStorage`.

**Comment by adamint** [comment]
Note: this should also be done in Structured Logs and Traces

**Comment by drewnoakes** [comment]
The console logs page seems to try and do this. Changing a selected resource does update the URL, however reloading or navigating to such a page doesn't restore data from the URL. There's more detail about that in #1389.
