### ISSUE TITLE
Bring AppConfiguration component up to gold standard

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#1268]
We have an AppConfiguration extension for the AppModel but currently we don't have a proper Aspire component that provides a gold standard experience. We need an `Aspire.Azure.Data.AppConfigration` package which will allow us to easily wire up Azure AppConfig and bring in things like tracing and health checks.

**Comment by eerhardt** [comment]
Duplicate of https://github.com/dotnet/aspire/issues/787.
