### ISSUE TITLE
Add ability to configure NpgsqlDataSource

### ISSUE THREAD

**Issue by jack775544** [dotnet/aspire#1276]
## Description

When using the `AddNpgsqlDbContext` or `AddNpgsqlDataSource` extension methods, there is no way to configure the `NpgsqlDataSource` that is registered in the service collection.

Configuring the data source is important for things like [enum type mapping](https://www.npgsql.org/efcore/mapping/enum.html?tabs=with-datasource#mapping-your-enum) and [spatial support](https://www.npgsql.org/efcore/mapping/nts.html#setup) among other things.

## Proposed Solution

Add another configure option onto the methods to allow for modification of the data source.

**Comment by eerhardt** [comment]
This is now complete with https://github.com/dotnet/aspire/pull/2125.
