### ISSUE TITLE
[WebToolsE2E][Aspire]Create an Aspire Starter Application via CMD, open endpoint of 'webfrontend', the web page shows incorrectly.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#1277]
**REGRESSION INFO**: Works fine on Aspire.ProjectTemplates.8.0.0-preview.1.23557.2
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install the latest VS Code
3. Download the latest released C# DevKit [1.2.2]
4. Install 8.0.100 SDK
5. CLI workload update and install aspire workload: [Aspire.ProjectTemplates.8.0.0-preview.2.23606.12]
6. Apply NuGet Feeds

**REPRO STEPS**

1. Open CMD, creating an Aspire Starter App using following commands:
```
dotnet new aspire-starter -o aspirestarter
cd aspirestarter
code .
```
3. In the VS Code, click 'Extension' tab, click '...' to installl the C# DevKit. (Or simply do `dotnet run` of the AppHost project in the command line)
4. Under the solution explorer, right-click the aspirestarter.AppHost > Debug > Start New Instance
5. Go to http://localhost:18888/
6. On the dashboard, click the endpoint of webfrontend

**Some notes**:
1. This issue doesn't repro on VS.
2. This issue also repro on MacOS.

**ACTUAL**
The web page shows incorrectly.
![image](https://github.com/dotnet/aspire/assets/82028229/002280ec-090b-4568-9f6d-162421dd9c74)

**EXPECTED**
![image](https://github.com/dotnet/aspire/assets/82028229/a2881a43-0263-4429-8e79-e46cd741300b)

**Comment by balachir** [comment]
Note that I can reproduce this issue with simply doing `dotnet run` in the command-line too. I've updated the repro steps. This seems to be a recent regression because our validation team did not run into this issue during last week's validation using CLI.

**Comment by v-cazhang** [comment]
Verified on Aspire.ProjectTemplates.8.0.0-preview.2.23610.1, this issue has been fixed.
![image](https://github.com/dotnet/aspire/assets/82028229/23f64314-a50d-408b-8ebb-1c1b451d08b8)
