### ISSUE TITLE
With* methods don't work with containers

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#128]
I was testing a project converter to container locally and I realized that it doesn't work because we pass the localhost address instead of using the host address (host.docker.internal). Localhost is local to this container so this always blows up.

```C#
using Aspire.Hosting.Otlp;
using Aspire.Hosting.Redis;

var builder = DistributedApplication.CreateBuilder(args);

var pubsub = builder.AddRedisContainer("pubsub");

// Projects
//builder.AddProject<RedisPubSub.App.Projects.Publisher>()
//    .WithRedis(pubsub);

//builder.AddProject<RedisPubSub.App.Projects.Subscriber>()
//    .WithRedis(pubsub);

// Project published as containers
builder.AddContainer("publisher", "publisher")
    .WithRedis(pubsub)
    .WithOtlpExporter();

builder.AddContainer("subscriber", "subscriber")
    .WithRedis(pubsub)
    .WithOtlpExporter();

builder.Build().Run();
```

The easiest fix here would be to always use `host.docker.internal` instead of localhost for anything that runs in a container. Injecting different environment based on the consumer might be a bit more difficult...

cc @karolz-ms

**Comment by mitchdenny** [comment]
This is going to be a pain. It appears that `host.docker.internal` is not enabled by default on Linux hosts. So we would need to add platform specific logic here.

**Comment by mitchdenny** [comment]
related: https://github.com/moby/moby/pull/40007

**Comment by mitchdenny** [comment]
@karolz-ms for DCP on Linux we might need to invoke with ```--add-host=host.docker.internal:host-gateway``` when spinning up a container with Docker.

**Comment by danmoseley** [comment]
@adityamandaleeka is @BrennanConroy planning to pick up app model work? David suggests this might be a good one to start with. Preview 2 cc is Tues 12/5

**Comment by danmoseley** [comment]
We believe DCP work is done.

**Comment by karolz-ms** [comment]
I do not think so/don't recall us adding this option on DCP side

**Comment by davidfowl** [comment]
This wasn't the one @danmoseley , it was the command line args for containers 😄

**Comment by danmoseley** [comment]
argh -- thanks for the correction. don't mind me, just dropping in and causing chaos in the issues

**Comment by davidfowl** [comment]
Mitigation in place https://github.com/dotnet/aspire/pull/1203

**Comment by davidfowl** [comment]
This may end up being the long-term solution since we're going through proxies here. I'm going to close this as resolved for now and we can track another networking support in containers [here](https://github.com/dotnet/aspire/issues/850)
