### ISSUE TITLE
Started a community 'triagers' group for dotnet/aspire

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#1281]
In dotnet/aspnetcore, dotnet/runtime and others, we have a group of a few of the most active community contributors who have GitHub "triage" permissions. This is partly a small recognition for their contributions and support of a healthy and helpful community in the repo. It also allows them to set and fix labels on issues and PR's, and close duplicates of them. (It's not actually for triaging in the sense of prioritization -- that's just the name of the permissions -- see the [analogous aspnetcore announcement](https://github.com/dotnet/aspnetcore/issues/48512)).

Now this repo is getting busy we're starting a similar group here. @Kahbazi, who already helps with this role in dotnet/aspnetcore, has a agreed to be the first member. Over time we expect to add some more folks. I've seen several other contributors in this repo who already help do this in another dotnet repo.

Thanks @Kahbazi !

cc @mkArtakMSFT

**Comment by danmoseley** [comment]
Ironically this very issue illustrates that the bot is quite inaccurate as it doesn't yet have enough training material. @Kahbazi if you come across even closed issues/PRs that seem wrong and you feel like correcting them please feel free to. In a month or so we should retrain.

**Comment by danmoseley** [comment]
we currently have a couple wonderful folks in such a team. closing.

**Comment by danmoseley** [comment]
@afscrome , @Alirexaa , @davidebbo -- you've been super helpful and active on this repo the last 6 months. **thank you.** would you too like to have "triager" powers that would allow you to fix labels and close dupes? 

If so LMK here and I'll set it up and add you to area_owners.md.

**Comment by adamint** [comment]
Unlocked the conversation so that @Alirexaa and @davidebbo can reply. @afscrome is interested!

@danmoseley

**Comment by Alirexaa** [comment]
Hi @danmoseley, I like to help so yes doing that would be great.

**Comment by davidebbo** [comment]
I have not contributed much in the past few months, but I suppose it wouldn't hurt to do that in case I pick this up again. Thanks!

**Comment by danmoseley** [comment]
OK, all 3 of you should have invites to join orgs/dotnet in  your email. (Uh, maybe several since I had problems with the admin UI. The newest should be the right one).

Once you accept those, you have "triager" rights in this repo. Please use the powers only for the following (this isn't a prioritization role despite the name of the rights)
* applying/fixing routing labels, basically area-xxx and such on issues/PR's when you feel like it (even on old ones has value when we retrain the bot)
* closing clear duplicates

They're not mighty powers, it's as much to thank all three of you for being valued and active community members that help us make this repo healthy and productive.

**Comment by Alirexaa** [comment]
@danmoseley , this is the my newest email
```Your invitation to the .NET Platform organization has been canceled```

**Comment by afscrome** [comment]
I was able to successfully accept my invitation earlier today.

**Comment by Alirexaa** [comment]
ping @danmoseley
