### ISSUE TITLE
[WebToolsE2E][Aspire][Linux] Debugging the aspire project and clicking structured logs, the filter box format is incorrect.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#1291]
**REGRESSION INFO**: Also repro on Aspire.ProjectTemplates.8.0.0-preview.1.23557.2

**INSTALL STEPS**

1. Clean machine: Ubuntu / RedHat
2. Install 8.0.100 SDK
3. CLI workload update and install aspire: [Aspire.ProjectTemplates.8.0.0-preview.2.23606.12]
4. Apply NuGet Feeds

**REPRO STEPS**

1. Open CMD, creating and running an Aspire App using following commands:
  ```
  dotnet new aspire -o Aspire
  cd Aspire/Aspire.AppHost
  dotnet run
```

2. Go to Url 'https;//localhost:xxxxx' (use default Firefox browser)

**ACTUAL**
The filter box on the structured logs page is incorrectly formatted
![image](https://github.com/dotnet/aspire/assets/71361488/08e3d98a-62b4-4f4f-9c65-8eb06e7c03d6)

**Note**

- This issue only reproduce on linux os.

**EXPECTED**
![image](https://github.com/dotnet/aspire/assets/71361488/23737682-3414-4710-8949-ba565dafdf50)

**Comment by v-cazhang** [comment]
Verified on Aspire.ProjectTemplates.8.0.0-preview.3.24064.1,this issue has been fixed.
