### ISSUE TITLE
[CodeSpaces] Dashboard URIs is looking for a URL that may not work

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#1297]
The dashboard page literally seeks for `http://localhost:<port_number>` - It makes sense as long as it's on my local machine, but not on Codespaces. When it is running on GitHub Codespaces, it should open `https://xxxxx-<port>.app.github.dev`.

**Comment by timheuer** [comment]
I see what you are saying now -- misinterpreted as "the dashboard URI" -- you mean the endpoints of any apps listed in the dashboard are not going to 'just work' launched from the dashboard

**Comment by timheuer** [comment]
FWIW, when running in a codespace there are some env vars that may help build up the clickable URI:

- `CODESPACES` - true/false when running in a codespace
- `CODESPACE_NAME` - the rando name of the runnel

![image](https://github.com/dotnet/aspire/assets/4821/5fea97f5-9a25-4c3e-992e-f549fc99975a)

and thus the `localhost:port` portion of the scheme could be translated as `{env.CODESPACE_NAME}-{port}.app.github.dev`

**Comment by justinyoo** [comment]
> I see what you are saying now -- misinterpreted as "the dashboard URI" -- you mean the endpoints of any apps listed in the dashboard are not going to 'just work' launched from the dashboard

That's correct. For example, the dashboard shows web app with `http://localhost:5000`, within GitHub Codespaces, it should launch `{env.CODESPACE_NAME}-5000.app.github.dev`.

**Comment by davidfowl** [comment]
Do any of you have a repository with aspire that is codespace ready that I can try?

**Comment by timheuer** [comment]
@davidfowl Here's one https://github.com/timheuer/SimpleAspireStarterCodespace (has the devcontainer definition to install Aspire workloads)

**Comment by davidfowl** [comment]
Excellent! IT seems that after the vs code work lands one of the remaining pieces will be how we make the dashboard urls show the proxied addresses.

**Comment by timheuer** [comment]
@davidfowl if you see a few comments up (https://github.com/dotnet/aspire/issues/1297#issuecomment-1847976960) the env vars will be written when in a codespace environment so Dashboard could check for existence of that and replace localhost.

**Comment by mitchdenny** [comment]
Closing this in favor of #1178. In a comment I've left some code that works to remap the localhost addreses on the dashboard to proxied addreses.
