### ISSUE TITLE
[Codespaces] instance is recognised as `Production`

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#1298]
GitHub Codespaeces instance is recognised as `Production` - When I run the code on my local machine, both `appsettings.json` and `appsettings.Development.json` are respected. However, when it's running on GitHub Codespaces, it seeks for both `appsettings.json` and `appsettings.Production.json`, although the `lauchSettings.json` sets `ASPNETCORE_ENVIRONMENT` to `Development`.

**Comment by timheuer** [comment]
This is prob a byproduct of #1296 as well. 

But launch any aspire app in a code space (easy button from a repo)

**Comment by DamianEdwards** [comment]
Sorry, can you be more explicit on how to do this? Do I have to manually create a Code Space in a repo? Do I hit `.` on the keyboard? I'm not familiar with the nuances.

**Comment by timheuer** [comment]
Set up a repo, but @justinyoo I'm not seeing your bug here repro.

Setup: https://github.com/timheuer/repro-1298
In the web front end project I added a setting `MY_SETTING` and emit it on the homepage
Added appSettings.Production.json with a diff value
Run the AppHost project
Look at environment variables set in the web project in the dashboard -- shows `ASPNETCORE_ENVIRONMENT` as Development.
![image](https://github.com/dotnet/aspire/assets/4821/5db232e9-2581-49d2-a9fc-1ba6f54eacfe)

I can't seem to repro what @justinyoo is indicating here so need to get more info maybe.

FYI Damian to launch a codespace:
![image](https://github.com/dotnet/aspire/assets/4821/be7061f7-5d6a-433f-a65c-c49a84c876a7)

**Comment by justinyoo** [comment]
Oh, I might be using the nightly build of `azd`, instead of the latest release, `v1.5.0`.

**Comment by mitchdenny** [comment]
I just opened up your repro @timheuer and I can't see a problem. It looks like it is using the development setting as would be expected.

**Comment by timheuer** [comment]
Yep, nor can I -- Justin was the original reporter -- I feel like this is a no repro.

**Comment by mitchdenny** [comment]
OK closing as no repro. If we see it in the wild again we can open.
