### ISSUE TITLE
Add default `.gitignore` to templates

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#1299]
Templates for dotnet haven't historically added `.gitignore` by default but we should change that with Aspire. With the nature of cloud-native developers there is greater liklihood of being in a git-based respository. With the assets created here and subsquent tools we're looking to evolve, having the best practice of ignores by default feels like the right thing we should start doing.

**Comment by DamianEdwards** [comment]
Yeah I'm not convinced of this yet. I don't think any of our templates should have default .gitignores in them still. Feels like the wrong layering to me.

**Comment by DamianEdwards** [comment]
Because you don't even know if the solution is being added to the repo root, or is the only solution present. It's the wrong place to assume a .gitignore is required.

**Comment by timheuer** [comment]
gitignore are hierarchical so it would affect the known assets downward, so root doesn't matter in this case

**Comment by DamianEdwards** [comment]
Indeed, but in many cases this will just result in duplication and potential confusion as to why the root .gitignore isn't being honored. If we want better experiences for creating new solutions that are in source control we should focus on that, not just put the .gitignore in the template IMO.

**Comment by davidfowl** [comment]
I agree this isn't an aspire thing. Seems like the wrong layer of the stack.

**Comment by aherrick** [comment]
Azure Functions template adds a gitignore and i don't like it. I agree keep it out of Aspire not the responsibility of the template
