### ISSUE TITLE
Add ability to copy Source file path in dashboard resources page

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#1309]
With #1232 the file path is no longer available in the view. 

Add the ability to copy the file path:
![image](https://github.com/dotnet/aspire/assets/102772054/36d1f419-2375-47e4-a025-239e5899c5dd)
and a "Copy" option where it would copy the path to clipboard

**Comment by mitchdenny** [comment]
@drewnoakes PTAL

**Comment by drewnoakes** [comment]
There's a similar copy feature, on hover, for container IDs. We could reuse that for consistency.
