### ISSUE TITLE
Aspire-added web api controller gets hit twice

### ISSUE THREAD

**Issue by harleydk** [dotnet/aspire#1321]
I've attempted to add a new web API project to the Aspire starter-solution. This works well in as a reference automatically gets added to the AppHost's program.cs when adding the project with Aspire orchestrator support. I add that reference to the sample web-app, and can successfully call the new service's singular controller. However; for a single request from the web-app, my breakpoint on the controller is called twice - and the trace of the app-host GUI confirms as much. I don't believe this is supposed to happen, and if I add a minimal API get-method to the new web API that's only - as is the case with the existing, minimal-API-based _apiservice_ - called once.

I don't feel technically competent to delve deeper, but will put it out there as I am wondering if I've encountered a problem or perhaps - probably - am going about it the wrong way. I put together [a repo to reproduce the problem](https://github.com/harleydk/AspireAppWebApiAddTest), if at all helpful. Clicking this item...:

![image](https://github.com/dotnet/aspire/assets/1468788/51181f23-a80d-4d93-9960-4dff1bfaa06c)

... will hit the Get-method on the WeatherStatisticsController.cs twice,
![image](https://github.com/dotnet/aspire/assets/1468788/859ba112-db8c-4bba-a47b-664a223a1e85)

I'll assume, though, you're all tremendously busy and wouldn't easily find time to sift through some random repo, yet couldn't find a different way to bring attention to the matter. If you could offer guidance on a better approach I'd be happy to try that. Thanks in advance.

**Comment by mitchdenny** [comment]
What you are describing can happen when you are using interactive server mode with pre-rendering enabled (default). Here is an issue in the aspnetcore repo with some background. Closing this issue as it isn't an Aspire issue:

https://github.com/dotnet/aspnetcore/issues/52208
