### ISSUE TITLE
AddSqlServerConnection is missing from the latest daily builds

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspire#1328]
I currently have a solution which has the option while in development to use either an existent database or a container.
"builder.AddSqlServerConnection" is used to create the connection to an already existent database.
When trying to use the latest daily build for .NET Aspire, the "AddSqlServerConnection" does not show up anymore, and the only available options to configure SQL are the ones which create containers.

Screenshot 1
<img width="282" alt="image" src="https://github.com/dotnet/aspire/assets/3481899/0be83663-6ad1-44c4-9067-8d7504c678c5">

Screenshot 2
<img width="825" alt="image" src="https://github.com/dotnet/aspire/assets/3481899/a0fbdd38-25e4-4eab-a295-72ef1b1dc70c">

Screenshot 3
<img width="582" alt="image" src="https://github.com/dotnet/aspire/assets/3481899/739ca10d-aaa8-48b3-a8ec-b4c334179d7d">

**Comment by davidfowl** [comment]
It was removed in favor of just adding environment variables. 

@mitchdenny We should have considered adding a WithConnectionString or something similar as a replacement though. Having to know the format is a PITA

**Comment by efonsecab** [comment]
> It was removed in favor of just adding environment variables.
> 
> @mitchdenny We should have considered adding a WithConnectionString or something similar as a replacement though. Having to know the format is a PITA

Thanks, I agree, a WithConnectionString would come handy. Using Environment Variables is not a big deal, though I can say I initially had the project sending the ConnectionString as Environment Variables and then converted it to use the AddSqlServerConnection, since it looked more in sync with the way the Distributed Builder is designed.

**Comment by DamianEdwards** [comment]
Let's get a new method `WithConnectionString` added for preview.2

**Comment by davidfowl** [comment]
>  though I can say I initially had the project sending the ConnectionString as Environment Variables and then converted it to use the AddSqlServerConnection, since it looked more in sync with the way the Distributed Builder is designed.

We're still in the process of trying to figure out which things should be resources and which things are just values. We have enough examples now to come to some conclusion about that. We'll be making more changes in this area in the coming previews.

**Comment by DamianEdwards** [comment]
Seems it should be one or the other:
1. Have resources for everything and call `WithReference` to setup relationships for service discovery, environment variable setting, etc.
2. Have specific methods for adding different relationship types

**Comment by davidfowl** [comment]
The problem is a connection string is just a string, so making it a `WithReference` overload feels bad.

**Comment by mitchdenny** [comment]
I personally vote for option 2 because option 1 has created lots of pain and I don't think it has conceptually improved our lives :)

**Comment by mitchdenny** [comment]
But then you get back to `WithServiceReference`

**Comment by davidfowl** [comment]
My only problem with doing nothing is that people have to write `WithEnvironment("ConnectionStrings__Name", value)` but maybe it a fine compromise for now?

**Comment by mitchdenny** [comment]
If with think we'll move away from WithReference to WithConnectionString I'm OK with it.

**Comment by DamianEdwards** [comment]
Feels still up in the air to me at this point (could go either way). I think a `WithConnectionString` method for now is a good compromise even if it ultimately goes away again in preview.3 or preview.4

**Comment by mitchdenny** [comment]
We didn't add `WithHttpReference`, we added `WithReference(this IResourceBuilder<T>, Uri uri)`. The overloads for `WithReference ` are going to get pretty crowded.

**Comment by DamianEdwards** [comment]
> We didn't add WithHttpReference, we added WithReference(this IResourceBuilder<T>, Uri uri). The overloads for WithReference  are going to get pretty crowded.

Ah, OK, snap. Yeah I agree, that was one of my concerns with changing HTTP services from resources to overloads of `WithReference`. We somewhat painted ourselves into a usability corner for preview.2 it seems. Well, if we `WithConnectionString` now we could at least get some feel/feedback for how it compares to `WithReference` overloads.

**Comment by mitchdenny** [comment]
For now we have `WithReference(ConnectionString)` for preview 2. TBH I don't hate it :)
