### ISSUE TITLE
[Azure Provisioner] Allow configuration for DefaultAzureCredentialOptions used by AddAzureProvisioning

### ISSUE THREAD

**Issue by sandrohanea** [dotnet/aspire#1329]
It seems that currently the `AddAzureProvisioning` is creating a new defaultAzureCredential with some predefined options [here](https://github.com/dotnet/aspire/blob/2b6951810bc781e5ff71edd5815b4fd2cba05a7e/src/Aspire.Hosting.Azure.Provisioning/Provisioners/AzureProvisioner.cs#L69)

However, that is blocking me from using a different subscription (e.g. my personal one where I have VS Enterprise credits) as the default one will be loaded from VS signed-in account.

**Comment by davidfowl** [comment]
I assume your application is also configured with these same credentials?

**Comment by sandrohanea** [comment]
Hey David,
Yes, in the app I'm using different credential based on `IsDevelopment()`:
![image](https://github.com/dotnet/aspire/assets/40202887/e3b8a404-2b65-401f-b18e-d96c0c585658)

An alternative to the configuration with the PR above (where the credential is using the IConfiguration to update the properies of the DefaultAzureCredential, would be to have some similar delegate for provisioning as well. If that sounds better, I can update the PR to use some delegate.
