### ISSUE TITLE
Dapr - wrong parameters passed to the executable after upgrading to `8.0.0-preview.3.23611.3`

### ISSUE THREAD

**Issue by L-Sypniewski** [dotnet/aspire#1333]
After upgrading packages from `8.0.0-preview.1.23557.2` to `8.0.0-preview.3.23611.3` wrong parameters are passed. C# code is exactly the same:

```csharp
var daprComponentsFolder = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "..", "dapr_components"));
_ = builder.AddProject<Projects.MyProject>("myproject")
    .WithDaprSidecar(new DaprSidecarOptions
    {
        AppId = "myapp",
        AppPort = 5000,
        AppProtocol = "http",
        LogLevel = "debug",
        ResourcesPaths = ImmutableHashSet.Create<string>(daprComponentsFolder, $"{daprComponentsFolder}/local", $"{daprComponentsFolder}/aspire"),
        DaprHttpPort = 3500,
        DaprGrpcPort = 50001,
        MetricsPort = 9090,
        Config = $"{daprComponentsFolder}/config.yaml"
    });
```

At the beginning of a parameters list `--dapr-grpc-port`, `--dapr-http-port` and `-metrics-port` have correct values, but at the end of the list they are defined again with values that look like some kind of placeholders:
- `--dapr-grpc-port {{- portForServing "<ProjectName>-dapr_grpc" -}}` 
- `--dapr-http-port {{- portForServing "<ProjectName>-dapr_http" -}}`
- `--metrics-port {{- portForServing "<ProjectName>dapr_metrics" -}}`

Here's the full list of arguments:
`run --app-port 5000 --dapr-grpc-port 50001 --dapr-http-port 3500 --metrics-port 9090 --app-id myapp --app-protocol http --config <ProjectPath>/dapr_components/config.yaml --log-level debug --resources-path /<ProjectPath>/dapr_components --resources-path<ProjectPath>/dapr_components/aspire --resources-path <ProjectPath>/dapr_components/local --dapr-grpc-port {{- portForServing "<ProjectName>-dapr_grpc" -}} --dapr-http-port {{- portForServing "<ProjectName>-dapr_http" -}} --metrics-port {{- portForServing "<ProjectName>dapr_metrics" -}}`

**Comment by karolz-ms** [comment]
@L-Sypniewski have you updated the Aspire workload on your machine? `dotnet workload update` is what you want I think.

**Comment by L-Sypniewski** [comment]
Yes I have, the problem still persists.

```
Installing pack Aspire.Hosting.Sdk version 8.0.0-preview.3.23611.3...
Pack Aspire.Hosting.Sdk version 8.0.0-preview.3.23611.3 is already installed.
Writing workload pack installation record for Aspire.Hosting.Sdk version 8.0.0-preview.3.23611.3...
Installing pack Aspire.ProjectTemplates version 8.0.0-preview.3.23611.3...
Pack Aspire.ProjectTemplates version 8.0.0-preview.3.23611.3 is already installed.
Writing workload pack installation record for Aspire.ProjectTemplates version 8.0.0-preview.3.23611.3...
Installing pack Aspire.Hosting.Orchestration.linux-x64 version 8.0.0-preview.3.23611.3...
Pack Aspire.Hosting.Orchestration.linux-x64 version 8.0.0-preview.3.23611.3 is already installed.
Writing workload pack installation record for Aspire.Hosting.Orchestration version 8.0.0-preview.3.23611.3...
Installing pack Aspire.Hosting version 8.0.0-preview.3.23611.3...
Pack Aspire.Hosting version 8.0.0-preview.3.23611.3 is already installed.
Writing workload pack installation record for Aspire.Hosting version 8.0.0-preview.3.23611.3...
Garbage collecting for SDK feature band(s) 6.0.400 7.0.400 8.0.100...

Successfully updated workload(s): aspire.
```

**Comment by karolz-ms** [comment]
I see. Would it be possible for you to share a repro?

**Comment by L-Sypniewski** [comment]
Here's an example repo: https://github.com/L-Sypniewski/aspire-dapr-issue
To reproduce the problem just start `Aspire.AppHost` project:
![1](https://github.com/dotnet/aspire/assets/29946802/d8018344-5867-4d27-b1d7-2cf2c02ef16d)

**Comment by karolz-ms** [comment]
I am able to reproduce. Working on a fix...

**Comment by karolz-ms** [comment]
Fix available
