### ISSUE TITLE
Consider specific method for overriding the container entry point

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#1342]
Today we have the `WithArgs` extension method that isn't constrained to a resource type and simply adds an annotation that carries a `string[]` args. When applied to a container-based resource, the first arg is seemingly taken as an override for the container entry point, vs. being passed to the container as arguments. Given these are [separate concepts in containers](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact), we should consider having separate methods that are clear with regards to what they apply to and how they behave, e.g. `WithEntryPoint` that only applies to container-based resources and sets the container entry point, `WithArgs` that applies to container-based or executable-based resources and sets the args to pass to the resource on start, or perhaps `WithCmd` for container-based resources and `WithArgs` for executable-based resources.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspire/pull/1341
