### ISSUE TITLE
Improve usability of WithServiceBinding

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#1343]
Configuring service bindings on resources has some usability issues today.

The `WithServiceBinding` method could be better named to more directly convey what it represents and does. Also the current overloads and use of optional args makes it a bit cumbersome to browse the method via IntelliSense to understand its different use cases and requirements.

This method instructs the app model that a resource exposes an endpoint (i.e. listens on a socket). Doing so facilitates proxy spin-up during local dev (required for supporting replicas, etc.), and provides the values required to facilitate configuration injection into other resources for service discovery to work, i.e. those configured with `.WithReference(someOtherResource)`.

The arguments supported differ based on the resource kind. Some arguments are optional in some cases but required in others, depending on what behavior is desired, e.g.:

- A port can be optionally specified, and if not a random port is assigned.
- The port can be injected into the resource as an environment variable by specifying a name.
- If the endpoint is resolvable via a URI, a URI scheme can be provided, e.g. http, https
- An endpoint name can be specified. If the name is not specified, but a scheme is, the scheme will be used as the name.
- If the resource is container-based, a container port is required and the other options (minus the environment variable to inject the assigned host port into) are optional

Note that project resources automatically call this method under the covers based on default convention, i.e. `AddProject` based on the project's *launchSettings.json* if it has one.

In some scenarios it can be desirable to control the proxying behavior too (e.g. databases running in containers) which is not something that is controllable via a parameter today but we might want to consider as part of this.

Some alternate method names to consider:

- `WithEndpoint`
  - Makes it clearer this it about configuring a resource to expose an endpoint, whether it's scheme-based (http/https) or not (tcp)
  - Not as closely aligned with the concept of a "service" in the sense of "service discovery", could be good or bad depending on perspective
- `ExposesEndpoint`
  - More aligned with the terminology used in containers ([EXPOSE](https://docs.docker.com/engine/reference/builder/#expose))
  - Introduces a new prefix which impacts consistency
- `WithHttpEndpoint` / `WithHttpsEndpoint` / `WithUriEndpoint` / `WithTcpEndpoint` / `WithUdpEndpoint`
  - More specific methods that make it clearer the kind of endpoint being exposed and then which parameters are supported
  - Perhaps results in different defaults for things like proxying behavior, e.g. defaults to enabled for HTTP/URI endpoints, disabled for TCP/UDP endpoints, etc.

We should ensure the doc comments on the method overloads and parameters are sufficiently detailed so that it's easier to discover and call the right method and pass the correct values.

Related:

- #693

**Comment by mitchdenny** [comment]
I like the more specific extension method names as a way of making the service binding type less of a pain to work with. I'm wavering a bit on the term `Endpoint` but given we've already got `GetEndpoint` .. there is symmetry there.

**Comment by mitchdenny** [comment]
@davidfowl made some initial changes here: https://github.com/dotnet/aspire/commit/88190a025a79c60bde26fee05427e5ef9860dc6e

That was mostly a rename so there is more to do.

**Comment by mitchdenny** [comment]
Assigning to @davidfowl since he has already started, but we can re-assess in the next sync up.

**Comment by mitchdenny** [comment]
@JamesNK

**Comment by davidfowl** [comment]
The remaining work is adding WithHttpEndpoint which is just a nice wrapper over WithEndpoint with an HTTP scheme

**Comment by davidfowl** [comment]
@JamesNK I'm thinking we should add back WithServiceBinding and mark it obsolete for p3. Thoughts? It can forward to WithEndpoint.

**Comment by JamesNK** [comment]
Sure https://github.com/dotnet/aspire/pull/1748
