### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/aspire#1351]
What do you think about database migration? 
I think it would be great if it were possible to start some task to run migration of databases as well as data seeding. 
It would definitely help in development.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/issues/398

**Comment by eerhardt** [comment]
Also see https://github.com/dotnet/aspire-samples/tree/main/samples/DatabaseContainers for a sample for seeding data.

I'm going to close this in favor of #398.
