### ISSUE TITLE
Endless loop in DcpHostService reading logs from socket

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1355]
While investigating #760 I found another source of high CPU in the app host.

The scenario is this:

![image](https://github.com/dotnet/aspire/assets/350947/3e50ee2a-adeb-46ec-9f2d-8b232f26fe75)

It's happening in this code when running eShopLite and repros easily for me:

https://github.com/dotnet/aspire/blob/734c3dc2247b937c1f2bf97ebe826c51653639b9/src/Aspire.Hosting/Dcp/DcpHostService.cs#L477-L502

A debugger shows:

- The call to `PipeReader.ReadAsync` returns a buffer of 4096 bytes
- This is passed to `LogLines`
- A `SequenceReader<byte>` is constructed to find lines by `\n` bytes
- No `\n` is found, so the `while` loop does nothing.
- The position is updated to itself (zero)
- The loop continues

Here's an example of the content from the buffer:

> 2023-12-12T23:52:00.983+1100	info	dcpctrl.ExecutableReplicaSetReconciler	created Executable	{"Controller": "usvc-dev.developer.microsoft.com/executable-replica-set-reconciler", "ExecutableReplicaSet": {"name":"basketservice"}, "Reconciliation": 9, "exe": {"metadata":{"name":"basketservice-nam1l48","uid":"712161e0-1d13-4e14-b852-bd8591565844","resourceVersion":"50","creationTimestamp":"2023-12-12T12:52:00Z","annotations":{"csharp-project-path":"D:\\repos\\aspire\\samples\\eShopLite\\BasketService\\BasketService.csproj","otel-service-name":"basketservice","service-producer":"[{\"serviceName\":\"basketservice\",\"address\":null,\"port\":null}]"},"ownerReferences":[{"apiVersion":"usvc-dev.developer.microsoft.com/v1","kind":"ExecutableReplicaSet","name":"basketservice","uid":"9244108a-8116-4615-92f3-c9481c879f85","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"dcpctrl.exe","operation":"Update","apiVersion":"usvc-dev.developer.microsoft.com/v1","time":"2023-12-12T12:52:00Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:csharp-project-path":{},"f:otel-service-name":{},"f:service-producer":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"9244108a-8116-4615-92f3-c9481c879f85\"}":{}}},"f:spec":{"f:env":{".":{},"k:{\"name\":\"ASPNETCORE_ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ASPNETCORE_URLS\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ConnectionStrings__basketcache\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ConnectionStrings__messaging\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DOTNET_LAUNCH_PROFILE\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOGGING__CONSOLE__FORMATTERNAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOGGING__CONSOLE__FORMATTEROPTIONS__TIMESTAMPFORMAT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_BLRP_SCHEDULE_DELAY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_BSP_SCHEDULE_DELAY\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_EXPORTER_OTLP_ENDPOINT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_METRIC_EXPORT_INTERVAL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_RESOURCE_ATTRIBUTES\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"OTEL_SERVICE_NAME\"}":{".":{},"f:name":{},"f:value":{}}},"f:executablePath":{},"f:executionType":{},"f:workingDirectory":{}}}}]},"spec":{"executablePath":"dotnet","workingDirectory":"D:\\repos\\aspire\\samples\\eShopLite\\BasketService","env":[{"name":"DOTNET_LAUNCH_PROFILE","value":"http"},{"name":"ASPNETCORE_URLS","value":"http://localhost:{{- portForServing \"basketservice\" -}}"},{"name":"ASPNETCORE_ENVIRONMENT","value":"Development"},{"name":"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES","value":"true"},{"name":"OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES","value":"true"},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://localhost:16031"},{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"service.instance.id={{- .UID -}}"},{"name":"OTEL_SERVICE_NAME","value":"{{- index .Annotations \"otel-service-name\" -}}"},{"name":"OTEL_BLRP_SCHEDULE_DELAY","value":"1000"},{"name":"OTEL_BSP_SCHEDULE_DELAY","value":"1000"},{"name":"OTEL_METRIC_EXPORT_INTERVAL","value":"1000"},{"name":"DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION","value":"true"},{"name":"LOGGING__CONSOLE__FORMATTERNAME","value":"simple"},{"name":"LOGGING__CONSOLE__FORMATTEROPTIONS__TIMESTAMPFORMAT","value":"yyyy-MM-ddTHH:mm:ss.fffffff "},{"name":"ConnectionStrings__basketcache","value":"localhost:50902"},{"name":"ConnectionStrings__messaging","value":"amqp://guest:36299ad1cfa645d0b9e98e2be61ec7c9@localhost:50903"}],"executionType":"IDE"},"status":{"executionID":"","state":"","startupTimestamp":null

This is one long (and incomplete) line of JSON that doesn't fit within the 4096 byte buffer.

**Comment by davidfowl** [comment]
I'll take a look.
