### ISSUE TITLE
Review use of icons throughout the dashboard

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1384]
Some UI might benefit from adding icons to clarify types of entities.

For example, the list of resources on the console log page:

![image](https://github.com/dotnet/aspire/assets/350947/bab82d7a-b538-475f-8eff-d89e86d1d2b4)

Adding an icon would help differentiate between different resource types.

Similarly in the resource grid. We have a resource name (which is easy to scan and has intuitive sorting options) but an icon would take less horizontal space.

![image](https://github.com/dotnet/aspire/assets/350947/904fc0ec-7a70-44eb-b160-3d1a8d19afcb)

One challenge here would be how to make the set of icons extensible, so that future resource types can be added without needing dashboard changes. The API design in #1274 could be extended to allow the dashboard to receive icon data (i.e. SVG strings) from the back end, and display whatever it receives (i.e. via the `ResourceType` message).

cc @leslierichardson95

**Comment by drewnoakes** [comment]
Another way of thinking about this would be to allow icons to be specified by the user. You could have different icons for the different components in your system, based on your own understanding of those components.

**Comment by leslierichardson95** [comment]
Closing this issue since I think there's no longer a need for it.  For more relevant todos regarding icons, refer to this issue: https://github.com/dotnet/aspire/issues/462.
