### ISSUE TITLE
Volume mounts not persisting data

### ISSUE THREAD

**Issue by adamtrip** [dotnet/aspire#1388]
I've been doing some tests with volume mounts on a PSQL database. However, with this config every time I restart the application (in development) the database is wiped but the volume still exists in my docker volumes.
I'm not quite sure if I misconfigured something on the code bellow or if I need to configure something on my docker instance, or even if this is the expected behaviour.

```
var appointmentDb = builder.AddPostgresContainer("appointment")
    .WithVolumeMount("CalGest.appointment.data", "/var/lib/postgresql", VolumeMountType.Named)
    .AddDatabase("appointmentdb");
```

Thanks in advance!

**Comment by KieranFoot** [comment]
Perhaps it's the named volume. I use an absolute path for storage and it works fine.

`var configDb = builder.AddPostgresContainer("config-db")
    .WithVolumeMount("./postgres/config", "/var/lib/postgresql/data");`

**Comment by adamtrip** [comment]
I've tried with your approach and now I have a password error:

```
var authDb = builder.AddPostgresContainer("auth")
    .WithVolumeMount("../calgest/auth/psql", "/var/lib/postgresql/data")
    .AddDatabase("authdb");
```

```
2023-12-14T11:18:06.8151140 fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      Npgsql.PostgresException (0x80004005): 28P01: password authentication failed for user "postgres"
      (...)
```

With this approach I have to setup a manual password?

**Comment by KieranFoot** [comment]
You can add a password parameter to the `AddPostgresContainer()` call, IntelliSense should show you this.

**Comment by adamtrip** [comment]
Yeah I know that it allows me to do so, I was asking if it's a requirement for this to work? Because on my setup, with no password defined it runs just fine the first time and after restart it just says incorrect password

**Comment by KieranFoot** [comment]
I would suggest, that when using persisted storage that the password is in-fact stored within the database files and therefore possibly does not match with the generated one. You might try deleting the current database files and start again with a specified password for testing purposes.

**Comment by DamianEdwards** [comment]
Did you look at https://github.com/dotnet/aspire-samples/tree/main/samples/VolumeMount? Does that work for you when you run it?

**Comment by adamtrip** [comment]
> Did you look at https://github.com/dotnet/aspire-samples/tree/main/samples/VolumeMount? Does that work for you when you run it?

Yes, after reading that and defining password secrets, it worked perfectly.
`dotnet user-secrets set authDbPassword <password>`
