### ISSUE TITLE
Reloading the console logs doesn't re-select the resource correctly

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1389]
See GIF:

![reload-console-logs-selected-resource-bug](https://github.com/dotnet/aspire/assets/350947/ca49c896-b403-4d1e-bc77-4da469f56144)

- Open console logs
- Select a resource
- <kbd>F5</kbd>
- The selected resource is cleared, yet the URL still shows a resource's name

Once in this state, attempts to re-select the same resource do not work. You must select something else first.

**Comment by drewnoakes** [comment]
For anyone considering doing this, please wait until my imminent console logging PR is merged.

**Comment by leslierichardson95** [comment]
@adamint and @leslierichardson95 try reproing this

**Comment by leslierichardson95** [comment]
Can no longer repro this issue.
