### ISSUE TITLE
Cosmos DB Create Container throws Request url is invalid error 

### ISSUE THREAD

**Issue by pantanuj** [dotnet/aspire#1393]
When using configuration 

```json
 "Microsoft": {
   "Azure": {
     "Cosmos": {
       "AccountEndpoint": "https://{accountname}.documents.azure.com:443/"
}}}
```

Cosmos operations through Request Url is invalid after successfully getting database.

However, if we switch to Connection String with AccountName and Account key, the operation succeeds.

```json
  "Microsoft": {
    "Azure": {
      "Cosmos": {
        "ConnectionString": "AccountEndpoint=https://{accountname}.documents.azure.com:443/;AccountKey={accountkey}"
}}}
```
          
Default Credential is configured in Azure tooling.

**Comment by eerhardt** [comment]
Can you attach the stacktrace and potentially any other repro information?

**Comment by ealsur** [comment]
Is there a Forbidden (HTTP 403) exception? If so, does it have an `aka.ms` link in the message?

Container creation is not allowed from Data Plane SDKs when AAD/MSI authentication is used -> https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#permission-model

That would explain why using Connection String works.

**Comment by eerhardt** [comment]
I'm going to close this issue because it needs more info. @pantanuj - please reopen when you can answer the above questions.
