### ISSUE TITLE
Redesign EF components public API

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#1403]
We've gotten feedback about missing EF scenarios - it started with [Npgsql component doesn't allow configuration of the NpgsqlDbContextOptionsBuilder](https://github.com/dotnet/aspire/issues/438). We we fixed this by allowing to configure the `DbContextOptionsBuilder`, but this had the problem that the user needed to call `UseNpgsql` again to configure Npgsql specific options. Npgsql and SqlServer work this way, but CosmosDB doesn't - the [UseCosmos API](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.cosmosdbcontextoptionsextensions.usecosmos) forces callers to pass a connection string, or other connection information.

Then more feedback came in that we don't support all the options that EF allows w.r.t. DependencyInjection:

* https://github.com/dotnet/aspire/issues/1276
* https://github.com/dotnet/aspire/issues/1241
* https://github.com/dotnet/aspire/issues/1194
* https://github.com/dotnet/aspire/issues/744 (the error happens because the scaffolding injects EF code into Program.cs)

Given all this feedback, and diving into the EF APIs, we think we need to redesign the Aspire EF component's public APIs. Today we are wrapping the EF APIs for Pooling or regular DbContext.

But instead, we should have the dev user call directly into the EF DependencyInjection APIs, so they have full control over what they want to add to the app. Then the Aspire EF Component can just have an extension method to add the other things:

* Health Checks
* Tracing
* Metrics
* Tracing
* Logging
* etc

The hard part will be coming up with the naming of that Aspire extension method. It can't be called `AddNpgsqlDbContext` anymore, since it doesn't add the DbContext.

**Comment by eerhardt** [comment]
Some other options I thought of. Not that I like any of them, but listing them here for completeness:

### Add Settings properties to control behavior

Following the current design, which has 

https://github.com/dotnet/aspire/blob/cce39149529f3388d5ab9fbc36f3d5e10feac3ab/src/Components/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL/NpgsqlEntityFrameworkCorePostgreSQLSettings.cs#L23

that controls how we add the DbContext to the ServiceCollection

https://github.com/dotnet/aspire/blob/cce39149529f3388d5ab9fbc36f3d5e10feac3ab/src/Components/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL/AspireEFPostgreSqlExtensions.cs#L80-L87

We could change this into an `enum` with `Context, Pool, Factory` options. This would solve #1241. And then for #1194 we add a ServiceLifetime property like in https://github.com/dotnet/aspire/pull/1218.

The downfall of this approach is that if/when EF adds more options to adding DbContexts to the ServiceCollection we would need to add more options in Aspire. This is basically wrapping the EF API, which we don't want to do. It also doesn't solve #1276.

### Take a optional Action<ServiceCollection> callback

When an EF Aspire component wants to add to the ServiceCollection, it checks if this callback is set. If it is, it delegates to the user callback do to add the DbContext in whatever way it wants to the collection. For example:

```C#
builder.AddNpgsqlDbContext<MyContext>("connectionName", addDbContext: services =>
{
    services.AddDbContextFactory<MyContext>(... /* whatever the user wants to configure it */);
});
```

### Have both simple and complex methods

In this option, we would still have the simple `AddNpgsqlDbContext<MyContext>("connection")` method, but also add the new complex method above for the cases when a dev wants to customize their DbContext adding to the ServiceCollection. So simple devs can just use our current APIs, and the more complex cases can use the full ability of EF overloads, and then call into the `builder.AddAspireNpgsqlDbContextServices<MyContext>()` proposed in the top comment.

cc @DamianEdwards @davidfowl @roji @ajcvickers @sebastienros - any thoughts on this issue?

**Comment by DamianEdwards** [comment]
I'm leaning towards requiring two methods to be called in all cases as it's the most consistent experience no matter how much of the EF Core call you need to customize.

**Comment by sebastienros** [comment]
Draft PR created with Npgsql changes https://github.com/dotnet/aspire/pull/1706

`AddNpgsqlDbContext` doesn't add the `DbContext` anymore so it needs to be renamed. I used `AddNpgsqlEntityFrameworkCore` for now. It only registers and configures telemetry/tracing/metrics.

**Comment by sebastienros** [comment]
Following up on [this PR](https://github.com/dotnet/aspire/pull/1706) that attempted to refactor the EF apis in order to allow users to configure the `DbContext` lifetime and other options, it appears that we should keep the current behavior with pre-configured instrumentation and common EF default (retries, connection string support, pooling) while adding the new `Enrich` (name TBD) methods from the PR that will let users register their own DbContext before.

```c#
/// <summary>
/// Registers the given <see cref="DbContext" /> as a service in the services provided by the <paramref name="builder"/>.
/// Configures the connection pooling, health check, logging and telemetry for the <see cref="DbContext" />.
/// </summary>
public static void AddNpgsqlDbContext<TContext>(
        this IHostApplicationBuilder builder,
        string connectionName,
        Action<NpgsqlEntityFrameworkCorePostgreSQLSettings>? configureSettings = null,
        Action<DbContextOptionsBuilder>? configureDbContextOptions = null) where TContext : DbContext

/// <summary>
/// Configures health check, logging and telemetry for the <see cref="DbContext" />.
/// </summary>
public static IServiceCollection EnrichNpgsqlEntityFrameworkCore<TContext>(
        this IHostApplicationBuilder builder,
        Action<NpgsqlEntityFrameworkCorePostgreSQLSettings>? configureSettings = null) where TContext : DbContext
```

Furthermore the `EnrichNpgsqlEntityFrameworkCore` will still try to update properties like `MaxRetryCount` or `CommandTimeout` by looking for `DbContext` options in the DI, and otherwise throw an exception if not registered before.

Usage with user-driven `DbContext` registration:

```c#
var connectionString = builder.Configuration.GetConnectionString("catalogdb")
    ?? throw new InvalidOperationException("Connection string is not configured.");

// User configures the DbContext with custom lifetime and options.
builder.Services.AddNpgsqlDataSource(connectionString);
builder.AddDbContextPool<CatalogDbContext>(dbContextOptionsBuilder => dbContextOptionsBuilder.UseNpgsql());

// Instrumentation using Aspire settings is added to the DbContext, including retries and timeouts.
builder.EnrichNpgsqlEntityFrameworkCore<CatalogDbContext>(settings => settings.MaxRetryCount = 2);
```

Automatic registration of a pooled DbContext as a scoped service (opinionated defaults):

```c#
builder.AddNpgsqlDbContext<CatalogDbContext>("catalogdb", settings => settings.MaxRetryCount = 2);    
```

**Comment by eerhardt** [comment]
I think this approach sounds good. It is basically the `Have both simple and complex methods` option listed [above](https://github.com/dotnet/aspire/issues/1403#issuecomment-1858668392).

My only comment on the API shape is I would rename `EnrichNpgsqlEntityFrameworkCore` to more closely match the Add method. So `EnrichNpgsqlEntityFrameworkCore` => `EnrichNpgsqlDbContext<TContext>`.

Then we would have `builder.AddNpgsqlDbContext<TContext>` and `builder.EnrichNpgsqlDbContext<TContext>`.

**Comment by AndriySvyryd** [comment]
> Furthermore the `EnrichNpgsqlEntityFrameworkCore` will still try to update properties like `MaxRetryCount` or `CommandTimeout` by looking for `DbContext` options in the DI, and otherwise throw an exception if not registered before.

You don't need to depend on DI details, just call `ConfigureDbContext`, see https://github.com/dotnet/efcore/pull/32518, https://github.com/dotnet/aspnetcore/pull/52910

**Comment by eerhardt** [comment]
> You don't need to depend on DI details, just call ConfigureDbContext

We are still targeting `net8.0`.

**Comment by eerhardt** [comment]
Re-opening as this was only done for Npgsql. We need to do the other EF providers to follow this same pattern as well.
