### ISSUE TITLE
Flaky test: Aspire.Hosting.Tests.Dashboard.ResourcePublisherTests.ProducesExpectedSnapshotAndUpdates

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1410]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=500597&view=results

Error message
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   (No exception was thrown)
```

Stack trace
```
   at Aspire.Hosting.Tests.Dashboard.ResourcePublisherTests.ProducesExpectedSnapshotAndUpdates() in /_/tests/Aspire.Hosting.Tests/Dashboard/ResourcePublisherTests.cs:line 53
--- End of stack trace from previous location ---
```

cc @drewnoakes

**Comment by drewnoakes** [comment]
This one's interesting. I ran the unit test 100 times on my PC using the "Run until failure" command, and it didn't fail. This will require some deeper investigation.

**Comment by drewnoakes** [comment]
For now we can just disable the test so we don't waste time on builds having unrelated changes.
