### ISSUE TITLE
Unit Tests for Resource Name display text

### ISSUE THREAD

**Issue by tlmii** [dotnet/aspire#1411]
We've got a few pieces of code that modify the resource name display text:

1. `DcpDataSource.ComputeExecutableDisplayName`, which sometimes removes the replica id if present
2. `ResourceFormatter.GetName`, which adds a uid
3. `ResourceViewModel.GetResourceName`, which calls ResourceFormatter.GetName under some circumstances
4. `OtlpApplication.GetResourceName`, which calls ResourceFormatter.GetName under some circumstances

We should consolidate this code into a common location as appropriate, make it testable (currently some of it is private methods) and write unit tests for it to ensure we're covering the various naming nuances. We already hit one with #1408, I'm sure we'll hit more.

**Comment by davidfowl** [comment]
Is this still relevant @tlmii ?

**Comment by kvenkatrajan** [comment]
There are no references to : ResourceFormatter per say. 
@JamesNK are you aware of any names display logic that may require validation?

**Comment by JamesNK** [comment]
This is simplified with https://github.com/dotnet/aspire/pull/2282

There is still code around calculating names for single replicas vs replica sets. That needs to either be tested or improved so a good name is returned from the resource server.
