### ISSUE TITLE
Can't debug Blazor WebAssembly project launched via AppHost

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#1418]
### Discussed in https://github.com/dotnet/aspire/discussions/1402

<div type='discussions-op-text'>

<sup>Originally posted by **pnorriscd** December 14, 2023</sup>
Not sure if this is the right place to put this.

In VS2022 17.9 Preview 2, when you create a new Blazor WebAssembly project, it asks if you want Aspire orchestration. If you click yes, it creates a new solution where you can't debug the WebAssembly app. 

I haven't been able to find any way to debug WebAssembly run under app host.

Looking for any ideas or suggestions.</div>

**Comment by mip1983** [comment]
Same issue here for a .NET 8 Blazor Web project, with any 'rendermode InteractiveWebAssembly' components, I don't hit my breakpoints (where as I do if I start the project directly), VS 2022 Version 17.9.0 Preview 4.0.

May be incidental but I do see a number of 'Exceptions thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll' and 'Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll' when starting up the aspire appHost.

**Comment by davidfowl** [comment]
@vijayrkn can you have somebody look into this?

**Comment by Alundra828** [comment]
Chiming in here as I believe I am experiencing this issue too.

I have a mono repo, and when running aspire my backend projects hit breakpoints just fine, however my Blazor WASM (standalone, not interactive auto) front end consistently cannot load symbols. 

My workaround is that I comment out my front end in my AppHost's program.cs like so

``` csharp
var builder = DistributedApplication.CreateBuilder(args);

//builder.AddProject<Projects.Frontend>("WASM Frontend");
builder.AddProject<Projects.BackendOne>("Backend 1");
builder.AddProject<Projects.BackendTwo>("Backend 2");
builder.AddProject<Projects.BackendThree>("Backend 3");

...
```

I then run my aspire AppHost project in visual studio to debug all of my back end projects.

Then in vscode, I run my blazor wasm front end with ```dotnet watch``` and attach a debugger to it manually. Only then can I debug both "types" of projects at once.

**Comment by gptucci** [comment]
Hi
Any news about this issue ??
Tnx

**Comment by mip1983** [comment]
Still problematic in VS 17.10.0 Preview 1.0, can't debug web assembly.

**Comment by vijayrkn** [comment]
This issue is fixed pending release. Will update here once the release version is available.

**Comment by joperezr** [comment]
Moving to Preview 5 in favor of removing milestone preview TBD.

**Comment by davidfowl** [comment]
This is fixed in the latest VS

**Comment by SimonGeering** [comment]
Can anyone confirm is this was fixed on the Visual Studio side of the underlying SDK Tooling side please, I'm using Rider on Ubuntu Desktop and would be interested to know if this will work for me in the next release or if it will be and issue that will require a release from JetBrains Rider team.

**Comment by mip1983** [comment]
I've just updated to aspire preview 5 and vs2022 preview 3 and can now hit my web assembly break points, woohoo!

It does now spin up another browser window on launch to the web project, with a different url and randomized looking port to the endpoint I've defined in aspire.

This is ok now I've figured out how to enable CORS for any localhost port on my API rather than the fixed ports I'd set before,
but it'd be useful to know if that random port number can be controlled somewhere?

**Comment by FritzTheCat9** [comment]
Blazor WASM works now with aspire, but i have problems when i try to make an API call from Blazor WASM project. I get "failed to fetch error" when i try to access API from Blazor WASM application (both Blazor WASM and API projects are added to the aspire project):
![image](https://github.com/dotnet/aspire/assets/62745092/ea884af3-af71-44a7-a5a2-922af15e09d1)

**Comment by mip1983** [comment]
@FritzTheCat9 At the moment the service discovery part doesn't work client side on wasm. I currently need to put the non-aspire url in the wwwroot/appsettings.json and pick it up in Program.cs (both in the client project) where I'm registering http clients.

https://github.com/dotnet/aspire/issues/1659

**Comment by Antaris** [comment]
I'm using the following bits:

.NET SDK 8.0.300-preview.24203.14
Aspire.Hosting, Aspire.Hosting.AppHost 8.0.0-preview.5.24201.12
Visual Studio Enterprise 17.10.3 Preview 3.0

I'm trying to use InteractiveAuto with my components, and no breakpoints currently get hit. When switching back to InteractiveServer they work fine.

@mip1983 You noted you've got it working on VS2023 Preview 3 with Aspire 5 bits, I wonder if you can confirm what version of `Microsoft.AspNetCore.Components.WebAssembly*` nuget packages you have installed? Mine is `8.0.2` for the following:

```
<ItemGroup Label="Third Party">
	<PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.2" />
	<PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.2" />
	<PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.2" />
</ItemGroup>
```

**Comment by mip1983** [comment]
@Antaris 

On the .Web project:

`<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.4" />`

On the Client project

```
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.4" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.4" />
```

At this point in time I'm now on Aspire preview 6 and VS 2022 17.10.0 Preview 5.0, but it was working prior.
