### ISSUE TITLE
Secure Supply Chain Analysis violations in samples

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspire#1419]
Builds of Aspire are causing violations in the Secure Supply Chain Analysis step:

```
##[warning]Discovered a reference to an image from an unapproved registry that violates the security policies and standards for containers within Microsoft. Reference to image 'localhost:5001/api-gateway' on line 19 of samples/eShopLite/Deployment/api-gateway.yml.
##[warning]Discovered a reference to an image from an unapproved registry that violates the security policies and standards for containers within Microsoft. Reference to image 'localhost:5001/basket-service' on line 19 of samples/eShopLite/Deployment/basket-service.yml.
##[warning]Discovered a reference to an image from an unapproved registry that violates the security policies and standards for containers within Microsoft. Reference to image 'localhost:5001/catalog-service' on line 19 of samples/eShopLite/Deployment/catalog-service.yml.
##[warning]Discovered a reference to an image from an unapproved registry that violates the security policies and standards for containers within Microsoft. Reference to image 'localhost:5001/my-frontend' on line 19 of samples/eShopLite/Deployment/my-frontend.yml.
```

This seems to be occurring after the Secure Supply Chain Analysis task was automatically upgraded from 0.2.192 to 0.2.193

**Comment by DamianEdwards** [comment]
@davidfowl is this yaml still relevant? I think it was from early experiments of @bradygaster using pre-Aspire azd logic.

**Comment by mthalman** [comment]
Can we get this cleaned up for Preview 1? It's causing Secure Supply Chain Analysis warnings for the [VMR](https://github.com/dotnet/dotnet) builds because this source gets included there.

**Comment by ReubenBond** [comment]
I wrote this YAML to test Service Discovery in k8s using the SRV provider and to test deployment to k8s in general.

**Comment by ellahathaway** [comment]
This is now occuring in 8.0.1xx builds. [Link to internal build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2368577&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=edf6ea5d-8fa9-5661-2fd8-1370b24b9911).

**Comment by eerhardt** [comment]
> @eerhardt - This is now occurring in 8.0.1xx builds. [Link to internal build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2368577&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=edf6ea5d-8fa9-5661-2fd8-1370b24b9911).

What branch of dotnet/aspire is the 8.0.1xx build using? It needs to be updated to include the fix.

**Comment by ellahathaway** [comment]
Latest the VMR pulled was https://dev.azure.com/dnceng/internal/_git/dotnet-aspire/commit/48e42f59d64d84b404e904996a9ed61f2a17a569 from main on Nov 7, 2023. I'll backport the PR with the fix. Thanks!

**Comment by mthalman** [comment]
Aspire doesn't flow to the release/8.0.1xx branch of installer:

```
$ darc get-subscriptions --source-repo aspire --target-repo installer
https://github.com/dotnet/aspire (.NET 9) ==> 'https://github.com/dotnet/installer' ('9.0.1xx-preview1')
  - Id: 13b61006-d12e-4279-5e1d-08dc174faa6d
  - Update Frequency: EveryBuild
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies: []
https://github.com/dotnet/aspire (.NET 8) ==> 'https://github.com/dotnet/installer' ('main')
  - Id: 70610cde-d4b7-4e3d-336c-08dc11d8c62b
  - Update Frequency: EveryWeek
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies: []
  - Last Build: 20240205.1 (5b98bff86e66fe9d5cc19d6b670505fdef25449d)
```

So the only way to do this would be via a patch in installer.

**Comment by mthalman** [comment]
@eerhardt - What's the plan for servicing in Aspire if there's no dependency flow to 8.0?

**Comment by eerhardt** [comment]
I don't know the answer. But @joperezr should. Aspire is on preview3 and we have no plans on servicing preview1 or preview2. Honestly I'm not sure why dotnet/aspire code should even be affecting the 8.0 VMR. Aspire doesn't ship in the .NET box.

**Comment by joperezr** [comment]
Aspire has been declared a toolset dependency as of 8.0.3 release of .NET. The only thing that ships in the product that comes from Aspire is the Aspire's workload baseline manifest, which hasn't really been updated in a while. @marcpopMSFT can explain, but it is normal for workload baseline manifests to not get updated after initial release unless they have to(for instance they changed the IPA targets and need to service them, etc), which we don't. When a user tries to use and install aspire, the SDK is automatically configured to do an update check to see if the manifest is outdated, which it will find that it is, and then it will fetch the latest manifest and install it, which is why it is not necessary to setup dependency flow.

**Comment by mthalman** [comment]
Thanks, that all makes sense.

**Comment by marcpopMSFT** [comment]
Following up on what Jose said, only the aspire baseline manifests should be included in the source build and SSCA going forward. The change to move it into toolset dependency section was made net9. That change is probably needed in net 8 as well as I don't think there are plans to continue updating the baseline manifest.

CC @joperezr @mmitche should we port the change to mark the aspire component as a toolset dependency to 1xx and 2xx?

The baseline manifest mostly just tells the SDK that there is a set of workload packs that could be installed and today we always update to the latest manifest before installing any packs (by default). The contents of the manifest are just two targets files and a json and so don't have any of the code that is reviewed by SSCA. It's aspires responsibility to ensure their packs are separately checked before pushed to nuget.org.

Does that all makes sense?
