### ISSUE TITLE
Rare deadlock when processes exit

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspire#1420]
When a `Process` exits it kicks off running the `Exited` event on a background thread. If we are currently processing output/error data at the same time we can hit a race where we have acquired the `processEventLock` in our data handler and we call `process.HasExited` which will see that the process is exited and attempt to also call the `Exited` event. The background thread calling our `Exited` event will attempt to acquire the `processEventLock` which is being held by the output/error data event and that event is attempting to also call the `Exited` event which will try to acquire the `Process` internal lock creating a deadlock.

Relevant code:
https://github.com/dotnet/aspire/blob/f93cc1661d7bb5de234ce0fcb7e1bb4bf12f371c/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs#L52-L54
https://github.com/dotnet/aspire/blob/f93cc1661d7bb5de234ce0fcb7e1bb4bf12f371c/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs#L82-L84

https://github.com/dotnet/runtime/blob/8725a6e2320a9862b43458c8bffcf96f462270a3/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L1147-L1154

**Comment by DamianEdwards** [comment]
I hit this while debugging a new starter app yesterday. I had a breakpoint in the ServiceDefaults project, and another in the Program.cs of the API project.
