### ISSUE TITLE
Unable to use WithServiceBinding when specifying a port and AsDockerfileInManifest

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1430]
We didn't update the WithServiceBinding overload that takes a `containerPort` to support the `env` parameter. As a result, it's difficult to create a manifest with a docker file that has the right binding information. You have to drop to using a `ServiceBindingAnnotation` directly.

```C#
builder.AddNpmApp("frontend", "../NodeFrontend", "watch")
    .WithReference(weatherapi)
    .WithReference(cache)
    // .WithServiceBinding(scheme: "http", env: "PORT")
    .WithAnnotation(new ServiceBindingAnnotation(System.Net.Sockets.ProtocolType.Tcp, uriScheme: "http", containerPort: 3000, env: "PORT"))
    .AsDockerfileInManifest();
```

We should add env to that overload.

**Comment by davidfowl** [comment]
@DamianEdwards we should consider this for p2

**Comment by DamianEdwards** [comment]
How involved is the fix?

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/pull/1432
