### ISSUE TITLE
Show the host port for container images

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1431]
Today I have to use docker desktop to see the host port bindings:

<img width="1030" alt="image" src="https://github.com/dotnet/aspire/assets/95136/d76cf013-702f-4e44-b111-cc228f17e9dd">

vs

<img width="854" alt="image" src="https://github.com/dotnet/aspire/assets/95136/863d7577-bc90-4626-9f49-dbdf81dc32cc">

We need to figure out if this will be confusing considering we also have proxy ports 🤔

**Comment by leslierichardson95** [comment]
@leslierichardson95 think about going the tooltip, inline with source column, or details view route with this one

**Comment by davidfowl** [comment]
Closing this as a dupe of https://github.com/dotnet/aspire/issues/1489
