### ISSUE TITLE
Split WithVolumeMount into two seperate methods

### ISSUE THREAD

**Issue by stbau04** [dotnet/aspire#1437]
WithVolumeMount is mixing two different concepts: named volumes and bind mounts. They should probably be seperated into two methods.

Mentioned in https://github.com/dotnet/aspire/issues/1132 and https://github.com/dotnet/aspire/issues/837

Suggestion for usage:
```
var database = builder.AddPostgresContainer("database")
    .WithBindMount("../../data/database/data", "/var/lib/postgresql/data") // currenty equal to VolumeMountType.Bind
    .WithVolume("volume-name", "/var/lib/postgresql/data") // currenty equal to VolumeMountType.Named
```

**Comment by josephaw1022** [comment]
What if the volume path for every aspire component had a default value for each resource (redis, postgres, rabbitmq, etc...)? And, you would only need to specify the name by default and the path was an optional parameter. With the approach that I am describing, the devs wouldn't need to look and figure out the volume path for containers but could change it if they wanted to. 


 builder.addPostgresContainer().withvolumemount("postgresVolume");

builder.addRabbitmqContainer().withvolumemount("rabbitmqVolume");

builder.addrediscache().withvolumemount("rabbitmqVolume", "<some non default path>");

**Comment by stbau04** [comment]
@josephaw1022 I think you are describing https://github.com/dotnet/aspire/issues/837

**Comment by josephaw1022** [comment]
@stbau04  You're right. I misread it initially.

**Comment by josephaw1022** [comment]
@mitchdenny, I think that would be interesting. I am curious exactly that would mean? Do you mean having them be independent of container creation and having more 1-1 mapping of methods to volume functionality? Or do you have something else in mind?

Not related in the sense that it's not directly related to volumes specifically, but I do think it relates to this 
https://github.com/dotnet/aspire/discussions/1575
as it pushes the ball towards the existing principles in place with kubernetes and containers.

**Comment by stbau04** [comment]
Probably we should wait for https://github.com/dotnet/aspire/pull/1521 and then see if this issue is still necessary

**Comment by mitchdenny** [comment]
Tagging for offsite because we need to figure out what we are doing in the app model around volumes and how that translates to deployment.
