### ISSUE TITLE
Add resource name annotation to dcp resources

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1441]
It's hard to get the apphost's resource name from the Kubernetes resource. 

@karolz-ms are annotations free form? Can we add this without dcp changes?

**Comment by karolz-ms** [comment]
Yes you can add any annotation you want without DCP change. Just make a reasonable effort to choose a name that won't clash with anything else.

**Comment by mitchdenny** [comment]
Did you still want this for GA @davidfowl punting to Preview 4 until I hear back.

**Comment by davidfowl** [comment]
You can assign this to me.

**Comment by davidfowl** [comment]
Added you on this one @BrennanConroy
