### ISSUE TITLE
Azurite does not work with latest Azure storage SDK component

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1444]
Error response [48d1d41c-5b4c-4bc8-a084-10da00c74a4e] 400 The API version 2023-11-03 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error.  (00.0s)
      Server:Azurite-Blob/3.26.0

**Comment by mitchdenny** [comment]
I'm aiming to do a PR for this today.

**Comment by mitchdenny** [comment]
Discussed in a teams thread. So far I haven't been able to reproduce this issue. Best guess right now is that it was a specific version compatibility between the Azure SDK and Azurite.

**Comment by davidfowl** [comment]
OK this works when if I manually pull the image. @karolz-ms this begs the question, what image pull policy does dcp use by default?

**Comment by karolz-ms** [comment]
I is the Docker/container orchestrator default. We do not override the image pull policy of the orchestrator. Meaning, if you already have the image with a given tag in the local Docker cache, Docker will not check if a newer image with the same tag is available in a remote registry; it will use what you have.

**Comment by davidfowl** [comment]
Closing this one
