### ISSUE TITLE
Resource subscriptions are never removed

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1451]
`ResourcePublisher` is [relying on a CT to stop a subscription](https://github.com/dotnet/aspire/blob/375645de437076c2a1a3b0fc643342d5f0b9d369/src/Aspire.Hosting/Dashboard/ResourcePublisher.cs#L45-L55), but the CT is coming from the constructor and has a lifetime of the Blazor session. The CT passed to the enumerable with `WithCancellation` isn't used. That means as you navigate around the app, the outgoingChannels collection will keep growing.

See https://github.com/dotnet/aspire/pull/1348#discussion_r1428707324

**Comment by drewnoakes** [comment]
I'm rewriting a lot of this code at the moment so will revisit and test to make sure everything cleans up properly, both on the client and server.
