### ISSUE TITLE
Show trace events with attributes

### ISSUE THREAD

**Issue by rolfik-mycronic** [dotnet/aspire#1463]
We use OT span events holding additional data or exceptions.
I do not see it in dashboard now.
Could You please add it?
Thank You

**Comment by JamesNK** [comment]
> @JamesNK don't we show all span details in the details view?

This is piece of information wasn't.

Span events aren't that common, but I think we should at least show them in the span detail pane: https://github.com/dotnet/aspire/pull/1522

In future, if more people ask for better span event support, then we could add UI to the span graph.

**Comment by rolfik-mycronic** [comment]
By the way, when OpenTelemetry Tracer/TelemetrySpan is used, TelemetrySpan.RecordException adds exception as span event so better visualisation showing that exception would be useful.

Visualising span events together with the span would be nice as well so that we could open an event from the visualisation as well.
