### ISSUE TITLE
Set Dapr Log Level

### ISSUE THREAD

**Issue by tonysneed** [dotnet/aspire#1468]
How is it possible to set the log level for Dapr in an Aspire project?

When running Dapr projects from the command line, it can be done as follows:

```
dapr run --app-id api --app-port 5096 --log-level debug --enable-api-logging -- dotnet run
```

Can this, for example, be performed via config in the Aspire AppHost project?

**Comment by davidfowl** [comment]
You can do this today by setting the `DaprSidecarOptions` in the call to `WithDaprSideCar`

**Comment by tonysneed** [comment]
Here is the code from Program.cs in the .AppHost project.

```csharp
builder.AddProject<Projects.AspireWithDapr_ApiService>("apiservice")
       .WithDaprSidecar(new DaprSidecarOptions { AppId = "api", LogLevel = "debug", EnableApiLogging = true });

builder.AddProject<Projects.AspireWithDapr_Web>("webfrontend")
    .WithDaprSidecar(new DaprSidecarOptions { AppId = "web", LogLevel = "debug", EnableApiLogging = true });
```
