### ISSUE TITLE
CLI : Users can simply `dotnet publish` an Aspire app to get all services ready for deployment

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#147]
A CLI user can `dotnet publish` an Astra orchestration project to have all the configured service projects published in an appropriate directory layout, ready for deployment.

**Comment by davidfowl** [comment]
@DamianEdwards I'm going to close this as not planned. I think we want an experience where there's a way to publish the manifest. Publishing the apphost and gathering the outputs hasn't come up as a thing people want to do. We can revisit when we have an end to end scenario.
