### ISSUE TITLE
Dashboard certification and authorization

### ISSUE THREAD

**Issue by GreenShadeZhang** [dotnet/aspire#1483]
Is it possible to add openid connect and oauth2 configurations to the dashboard, so that we can limit the permissions of people who log in to the dashboard? I don’t know if the official has any ideas, because I see that many open source projects will provide such functions.

**Comment by mitchdenny** [comment]
Currently the dashboard only runs locally and binds to localhost so only users on the local machine should be able to access it. Are you seeing something else?

**Comment by GreenShadeZhang** [comment]
> Currently the dashboard only runs locally and binds to localhost so only users on the local machine should be able to access it. Are you seeing something else?

I want to know whether the final dashboard can be released to the production environment along with the project. If it will be released to the production environment, I think the authentication and authorization of the dashboard are needed. If it is only run in the local development stage, then my suggestion does not make much sense. , I hope you can evaluate it.

**Comment by mitchdenny** [comment]
At this point in time the dashboard is only intended for local use. In the future this may change and we'll evaluate appropriate authentication and authorization mechanisms at that point in time. I'll leave this issue open on the backlog.

**Comment by leslierichardson95** [comment]
TODO: investigate other issues about auth

**Comment by kvenkatrajan** [comment]
Addressed with #3033
