### ISSUE TITLE
Unable to make grpc connection to Tempo

### ISSUE THREAD

**Issue by Depechie** [dotnet/aspire#1485]
I'm trying to push the traces from the API to an OpenTelemetry Collector through to Tempo.
But receiving grpc connection refused messages / unavailable messages.

![log](https://github.com/Depechie/aspiresample/raw/main/screenshots/Screenshot06.png)

I guess I miss the guidance on how to configure the correct paths, but the same setup in docker compose does work.

The demo application can be found here: [https://github.com/Depechie/aspiresample](https://github.com/Depechie/aspiresample)
My thoughts, I guess it will be a combination of tweaking [https://github.com/Depechie/aspiresample/blob/main/config/otel.yml](https://github.com/Depechie/aspiresample/blob/main/config/otel.yml) and [https://github.com/Depechie/aspiresample/blob/main/config/tempo.yml](https://github.com/Depechie/aspiresample/blob/main/config/tempo.yml) together with the correct aspire host config [https://github.com/Depechie/aspiresample/blob/main/aspiresample.AppHost/Program.cs](https://github.com/Depechie/aspiresample/blob/main/aspiresample.AppHost/Program.cs).

I did try changing the paths using: **localhost, 0.0.0.0, host.docker.internal** but always got different logs but not a working version

For reference, I pushed several commits, to indicate that only using the OpenTelemetry Collector does work. Commit [https://github.com/Depechie/aspiresample/commit/8b2dc0208f527638b9ce5b8919d85178f4d9b402](https://github.com/Depechie/aspiresample/commit/8b2dc0208f527638b9ce5b8919d85178f4d9b402) has the setup without Tempo and uses a Debug exporter in the OpenTelemetry Collector.
When viewing the logs, you will see the traces are pushed to OTEL.

![log](https://github.com/Depechie/aspiresample/raw/main/screenshots/Screenshot04.png)

**Comment by davidfowl** [comment]
I couldn't get it to work with tempo, but I could get it to work with the dashboard (Which is an otlp endpoint). That makes me think there's something fishy going on with the proxy... @karolz-ms

**Comment by davidfowl** [comment]
I wonder if container startup order has anything to do with the reason this might not be working...

**Comment by Depechie** [comment]
That is something I actually wanted to ask if we could have the same feature like in docker compose 'depends on'.

https://github.com/Depechie/OpenTelemetryGrafana/blob/main/docker-compose-mac.yml ( this is the docker version of what I'm trying to achieve )

**Comment by davidfowl** [comment]
Hmm come to think of it, I might have gotten it working but I don't have grafana wired up so I don't know if it does work 😄 .

Here are some of my changes https://github.com/Depechie/aspiresample/pull/1/files

**Comment by davidfowl** [comment]
Looks like it does work, hit http://localhost:3200/api/search in the browser and you'll see traces in tempo.

**Comment by Depechie** [comment]
Will check it out when I’m at a pc later today!!
But thank you very much already!

**Comment by Depechie** [comment]
Works great thanks for the PR on the repo!!

**Comment by Depechie** [comment]
hey @davidfowl merry Christmas and all :)
Almost do not dare to ask, but if you ever find some time again, can you maybe also work you magic on getting the connection to Loki working? ( https://github.com/Depechie/aspiresample/tree/loki )
So the traces are great, but the logs are not flowing through...
I imitated the same setup as you did for Tempo, so pushing the Loki URL to the OpenTelemetry Collector.
But again when I set the debugger for OTEL, I do not see logs appearing, seems somehow the API is not pushing them correctly?

**Comment by davidfowl** [comment]
Death by yaml, you were configuring the wrong url for the loki exporter, see https://github.com/Depechie/aspiresample/pull/2
