### ISSUE TITLE
Adding a project by path does not work in Visual Studio

### ISSUE THREAD

**Issue by bastiennoel93** [dotnet/aspire#1486]
Hi,
An error occurs when I run aspire in multi repositories. 

Here is my test case: 
![image](https://github.com/dotnet/aspire/assets/18250350/bcc8aa14-dae3-43bc-8ceb-244a5c9d8102)

The error loops indefinitely in the console.
I receive a 500 error with no details. 
![image](https://github.com/dotnet/aspire/assets/18250350/42a3dac9-b901-4818-b74e-fc056c39c17e)

On the dashboard, I see that the project is starting up:
![image](https://github.com/dotnet/aspire/assets/18250350/120ec3a8-dd2e-4716-8eb6-15094953ec04)

Have you ever had this problem? 

Thanks.

**Comment by davidfowl** [comment]
What do the logs say for the dapr side car in the dashboard?

**Comment by bastiennoel93** [comment]
The dapr side logs indicate that it does not find the remote application.

The problem does not come from dapr because when I do without the problem persists.

**Comment by rem-coding** [comment]
@bastiennoel93 - when using the new AddProject() syntax from Preview 2, I seem to be hitting very similar when running from Visual Studio, but it works fine from the dotnet run command line. 

@davidfowl - is there something different between VS and dotnet command line environments that will help reproduce?

**Comment by bastiennoel93** [comment]
@rem-coding  Yes, when i use the dotnet run command line, it works fine. 👍 
The problem comes from execution with visual studio.

**Comment by davidfowl** [comment]
Can you provide a sample that reproduces the problem?

**Comment by rem-coding** [comment]
Hi @davidfowl , it can be reproduced with the aspire-starter template as follows:

1. dotnet new aspire-starter --project AspireStarter
2. Replace AddProject<>() with AddProject() using the new reference path feature.
3. Remove the AspireStarter.ApiService from the Visual Studio Solution.

Fails to run from Visual Studio, works fine running from command line dotnet run.

The 2 changes to the Solution in below screenshot:
<img width="1003" alt="image" src="https://github.com/dotnet/aspire/assets/39296150/cce18a1b-c837-4dfb-981a-422a6d337a59">

Repeating error when run from Visual Studio:
<img width="676" alt="image" src="https://github.com/dotnet/aspire/assets/39296150/2d77df02-7b67-4967-a649-e8cc1e3d58a5">

**Comment by dbreshears** [comment]
@BillHiebert.  Looks like this is something on the VS side since it works on the command line.

**Comment by DamianEdwards** [comment]
@vijayrkn looks like this is an issue in the VS support for Aspire.

**Comment by jonathanpickard3sq** [comment]
Hi - just to let you know that in the meantime, if I do a dotnet run in the AppHost project directory then I can get the AppHost running without errors and can see all microservices spinning up successfully.  I've been able to get one API (a backend for frontend API) to call another microservice and let Aspire take care of service discovery.  I've also been able to manually attach a debugger using Visual Studio 2022 Preview and hit breakpoints.  The only thing that doesn't work is launch/debug directly in Visual Studio using AppHost as the startup project.  If that could be fixed then that would be great (perhaps current working directory has something to do with the issue?).

**Comment by DamianEdwards** [comment]
@jonathanpickard3sq thanks for the update. We've identified the root cause in the VS support for launching Aspire AppHost projects and are investigating.

**Comment by tlmii** [comment]
We're looking into what our options would be here. In the meantime, another workaround that you could potentially use here is to create another VS solution that includes all of the projects you're interested in using together with Aspire. The overload with the path to the project should work fine as long as the project is loaded in VS.

**Comment by davidfowl** [comment]
@vijayrkn @BillHiebert This one is pretty important to find a solution for.

**Comment by joperezr** [comment]
from @vijayrkn this is now done.

**Comment by davidfowl** [comment]
TBH this isn't fully fixed, you can track https://github.com/dotnet/aspire/issues/2154 for a follow up. There's work remaining in the app host https://github.com/dotnet/aspire/issues/2154#issuecomment-1974845081.
