### ISSUE TITLE
Show endpoints even if they aren't http

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1489]
We only show http endpoints in the dashboard now. We should show any endpoint but http endpoints should be hyperlinks.

**Comment by adamint** [comment]
@drewnoakes are we just getting http endpoints from dcp?

**Comment by drewnoakes** [comment]
Take a look at the use of `Aspire.Hosting.Dcp.Model.Endpoint` in the `Aspire.Hosting.Dashboard.DcpDataSource` class, specifically the `GetEndpointsAndServices` method. The call to `UsesHttpProtocol` causes non-HTTP endpoints to be filtered out.

**Comment by JamesNK** [comment]
Will be done in https://github.com/dotnet/aspire/pull/1542

**Comment by davidfowl** [comment]
Re-opening, these should show up in the grid under endpoints as well.

**Comment by davidfowl** [comment]
This feels like something we should do in P4. Currently it says "None" when there are endpoints. That feels like a bug.

**Comment by JamesNK** [comment]
What should the UI be? This is a column in a table. It's not possible to display a list.

This is what docker UI does:
![image](https://github.com/dotnet/aspire/assets/303201/dd4538a4-491f-4d95-94eb-485e68bfae1b)

We should also think about how to display the proxy and non-proxy URL. It's confusing why there is two and there is no information about what the difference is between them.

**Comment by davidfowl** [comment]
The UI should display the proxy url, the non-proxy url can be in the details view. 

> It's not possible to display a list.

We already show a list of URLs today so this shouldn't be a problem. Put HTTP and HTTPS in the launch profile and see what it does.

**Comment by JamesNK** [comment]
> The UI should display the proxy url, the non-proxy url can be in the details view.

👍 

> We already show a list of URLs today so this shouldn't be a problem. Put HTTP and HTTPS in the launch profile and see what it does.

It's _**possible**_, but showing 3+ endpoints in a row will look bad. That's why I don't think the current approach scales. Row heights become uneven.

Docker makes it a button click to expand/collapse the endpoints.

Another option is to have an overflow control, e.g. it would show however endpoints fit, and then a count of additional endpoints, e.g. `(+3)`. The additional endpoints can be shown in a tooltip and accessed in details view.

**Comment by leslierichardson95** [comment]
@leslierichardson95 respond to this later

**Comment by leslierichardson95** [comment]
@davidfowl I agree with James that showing all of those additional endpoints would make the Resources page look too busy.  @JamesNK I do like the quick view of additional endpoints via tooltip idea however.

**Comment by davidfowl** [comment]
1. We should fix "no endpoints", that's just wrong (there are endpoints)
2. We should show prioritize the proxy endpoint because that's what is user facing (pushed into configuration etc).
3. People get confused about what shows up in the docker desktop tools and how that differs from the endpoints in the dashboard (there are several issues and discussions about this).

**Comment by davidfowl** [comment]
Can we get closure here?
