### ISSUE TITLE
Incorrect port binding when using AddSqlServerContainer

### ISSUE THREAD

**Issue by thijscornelis** [dotnet/aspire#1490]
Hi, 

I had an aspire host that was working perfectly fine before updating to the latest preview nuget packages / sdk's 

The project has a SQL container, with an explicit binding on port 1433:

```
var sql = builder
	.AddSqlServerContainer("sql", builder.Configuration.GetValue<string>("MSSQL_PASSWORD"), 1433)
	.WithVolumeMount("sqldata", "/var/opt/mssql", VolumeMountType.Named);
```

but, when the container is created a random port is assigned:

![image](https://github.com/dotnet/aspire/assets/47213986/0cd47ac5-f36e-48a4-8745-da9eb8acc14c)

When running the code, the DbContextOptions in my DbContext do have a reference to the expected port:

![image](https://github.com/dotnet/aspire/assets/47213986/eec4ce76-042d-400d-acfb-d2dfa296fddb)

**Comment by davidfowl** [comment]
Oh great you can read the networking doc we're working on an tell give feedback as to if it makes sense 😄 https://github.com/dotnet/docs-aspire/issues/232

**Comment by thijscornelis** [comment]
@davidfowl I now understand that there is always a proxy in between, no matter how I set things up.
