### ISSUE TITLE
Expose WebHost on IDistributedApplicationBuilder

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/aspire#1491]
It would be really nice so that we can do things like configure the kestrel instance for the dashboard to have access to the webhost.

I.e. we keep our https certificates differently and don't set kestrel up with it's appsettings.config section because Kestrel doesn't support Environment Variable expansion from appsettings.config so for developers, it becomes very difficult (insane relative pathing) to get pathing on their machines correct if not doing this.

This would let us customize a ton of things about how the dashboard is served as well especially if this was just a jumping off point and was like DashboardWebHost that was both IWebHostBuilder and also IAspireWebHostBuilder or something that gave additional options for configuring the dashboard and adding plugins etc.

**Comment by davidfowl** [comment]
The dashboard is decoupled from the distributed application, in fact [it's being further decoupled in the next preview](https://github.com/dotnet/aspire/issues/1003). So it seems like you're asking for the dashboard itself to be configurable as an API . This isn't something we'd want to expose on the `IDistributedApplicationBuilder` itself.

**Comment by JohnGalt1717** [comment]
OK, how would you suggest that I phrase this request?  Basically the Dashboard host needs to be configurable, and ultimately, it would be great if it then allowed all kinds of configuration itself over time off of that same IWebApplicationBuilder interface that it would inherit from.

**Comment by davidfowl** [comment]
The dashboard as a separate package is configurable but it won't be configurable in process while using it as part of aspire orchestration process. 

What are you trying to accomplish?

**Comment by JohnGalt1717** [comment]
I want to programmatically set the kestrel settings for it.

**Comment by davidfowl** [comment]
Right, I'm just asking what's the scenario? Are you self hosting the dashboard?

**Comment by JohnGalt1717** [comment]
I'm running multiple solutions that all have the aspire host.  As a result they clash unless you set the kestrel settings in the appsettings or pass args or set environment variables.

And because Kestrel doesn't expand environment variables, getting to a shared https certificate is a serious pita because of relative pathing and where it's executing etc. without being able to set an environment variable to expand. So we just use a separate config section and expand the environment variable and that gives the path to the certificate and then we set it in kestrel.

This works super well especially when deploying to k8s because you'll use Cert Manager or similar and generate the certificates internally for the internal services (i.e. you shouldn't be trusting http for internal coms in k8s) and then we set the environment variable to the mounted certificate in the container and it all just works transparently.  Otherwise we have to have all kinds of complex mess of pathing in every environment version of appsettings.json for pathing for kestrel which gets narly.

Ultimately, we want to be able to use the Dashboard in k8s as well as locally and just do a kubectl port-forward for it when needed.

And of course because we have multiple solutions running at the same time, we need to get the pathing sorted and ports all taken care of for the whole thing and right now the dashboard WebHost is a black box as far as I can tell and we can't get to it to set it manually.

**Comment by davidfowl** [comment]
I guess I don't understand the setup. Are you deploying the dashboard somewhere? It sounds like you are doing something custom and I don't quite understand the current set of challenges. 

Right now, we're working through a big dashboard refactoring so it can run in multiple environments, maybe that will help you accomplish what you are trying to do.

**Comment by JohnGalt1717** [comment]
Consider you're working on 2 solutions. Solution a has a bunch of things like RabbitMQ shared hosts in it.

Solution b has a website in it that talks to those mq endpoints.

They're completely decoupled (in this case it's because the customer as a custom solution we built for them but it uses our standard tooling).  Right now, if you do this, you get a runtime error because the dashboard ends up on the same endpoint for both.

The only way I've found to override that is to in the appsettings set the kestrel area:

```
	"Kestrel": {
		"Endpoints": {
			"Http": {
				"Url": "http://localhost:5166"
			},
			"HttpsFromPem": {
				"Certificate": {
					"KeyPath": "../../../../.dev/certificates/https.key",
					"Path": "../../../../.dev/certificates/https.crt"
				},
				"Protocols": "Http1AndHttp2AndHttp3",
				"Url": "Https://localhost:6153"
			}
		}
	},
```

This then gives us 2 separate dashboards and allows all of the services to startup.

But notice those horrific paths for https certs?

That's because the kestrel options read doesn't expand environment variables in the strings.  We would just do %CERTIFICATE_PATH% but it doens't allow us.

So with our normal setup for web sites, we have a ConfigureKestrel method that pulls the https from another part of the config, and we don't have a kestrel section, and we set it at runtime and expand the environment variables.

There's a ton of other reasons, but Development in this pretty common requirement of 2 solutions open and running at the same time is the prime one.

If you're running in k8s for production you'll also have this https issue because you'll want to inject the certificate that was generated from the CertManager using the shared root authority that it generates, which means that you can, service to service, have encrypted coms inside of k8s and verify the certs generated against the shared root authority.  This fixes the trust issue that most people ignore in k8s automatically, but you still end up with magic relative pathing etc. for the mapped certs.  

This could, for this limited use case just be fixed in .net 9 by enabling environment variable expansion in the Kestrel appsettings.config load, but I suspect there is lots more you might want to do with the Dashboard host than just that and I would assume at some point you're going to have the ability to add plugins into the Dashboard, so it makes sense that there is one management endpoint for this that allows you to do all of that, just like you can with any of the other Host.XXX builders.

**Comment by davidfowl** [comment]
> Consider you're working on 2 solutions. Solution a has a bunch of things like RabbitMQ shared hosts in it.

> Solution b has a website in it that talks to those mq endpoints.

> They're completely decoupled (in this case it's because the customer as a custom solution we built for them but it uses our standard tooling). Right now, if you do this, you get a runtime error because the dashboard ends up on the same endpoint for both.

Are these 2 solutions using the same app host project?

**Comment by JohnGalt1717** [comment]
No. Different. But they end up defaulting to the same port. And if you set it in the launchSettings it messes with everything that gets launched.

**Comment by davidfowl** [comment]
> No. Different. But they end up defaulting to the same port. And if you set it in the launchSettings it messes with everything that gets launched.

Why isn't the dashboard port being set in launchSettings to different ports? How are you creating these projects that they end up not having that setting or that the ports end up conflicting?

**Comment by davidfowl** [comment]
> If you're running in k8s for production you'll also have this https issue because you'll want to inject the certificate that was generated from the CertManager using the shared root authority that it generates, which means that you can, service to service, have encrypted coms inside of k8s and verify the certs generated against the shared root authority. This fixes the trust issue that most people ignore in k8s automatically, but you still end up with magic relative pathing etc. for the mapped certs.

The dashboard doesn't run outside of your local machine (until we do lots of refactoring). That's why I was asking how this was a concern right now.

**Comment by JohnGalt1717** [comment]
The other part is still applicable. (can't wait for the dashboard to work outside of the local machine)

**Comment by drewnoakes** [comment]
@JohnGalt1717 the dashboard has been refactored into its own project and the expectation is that user code won't run directly in that executable. It connects via gRPC to a service (in the app host) to obtain its data. Both the HTTP endpoint that browsers bind to and the gRPC endpoint it connects to are set via environment variables. We're investigating adding auth at the moment, and I suggest you add any comments you have about that on #1483.

This refactoring means there's no way for us to expose the WebHost as per the original request here, so I'll close this out.
