### ISSUE TITLE
Is there any resiliency support in .NET Aspire when using gRPC?

### ISSUE THREAD

**Issue by takashiuesaka** [dotnet/aspire#1494]
I know .NET Aspire has resiliency support, but it seems only works with using http.

**Comment by davidfowl** [comment]
Yes it works for gRPC as well (gRPC also uses http under the covers). Why do you think it only works for http?

**Comment by takashiuesaka** [comment]
@davidfowl 
According to this blog written by Glenn Condron, the resiliency feature is supported for HTTP calls via  IHttpClientFactory.

https://devblogs.microsoft.com/dotnet/introducing-dotnet-aspire-simplifying-cloud-native-development-with-dotnet-8/

> You can see here that I name my API apiservice, then pass that as a reference to the front-end and can then use apiservice as a name when making HTTP calls via IHttpClientFactory. The calls made using this method will also automatically retry and handle transient failures, thanks to an integration with the [Polly project](https://github.com/App-vNext/Polly).

And I also checked eShop sample and I realized WebApp Project uses GrpcClient to invoke Basket.BacketClient. But I cloud not find gRPC resiliency implements.

Here is http resiliency implements for http in eShop sample, but there is no implementation for gRPC.
```
// eShop.ServiceDefaults.Extensions.cs
// AddStandrdReselienceHander method is for http

builder.Services.ConfigureHttpClientDefaults(http =>
{
    // Turn on resilience by default
    http.AddStandardResilienceHandler();

    // Turn on service discovery by default
    http.UseServiceDiscovery();
});
```

**Comment by davidfowl** [comment]
GRPC uses the http client factory under the covers so this applies to both types of calls

**Comment by takashiuesaka** [comment]
Oh, I see. Then I understood that Service Discovery is also performed when gRPC is used.
Thank you for your answer.
