### ISSUE TITLE
Allow generic parameters to differ the contract and implementation with AddSqlServerDbContext and AddCosmosDbContext

### ISSUE THREAD

**Issue by christiannagel** [dotnet/aspire#1495]
With the `AddSqlServerDbContext` and `AddCosmosDbContext` methods, please add a version to supply two generic types to differ the contract from the implementation.

The `AddDbContext` extension method allows specifying generic types `TContextService` and `TContextImplementation`, e.g. `builder.Services.AddDbContext<IGamesRespository, GamesSqlServerContext>`.

This allows to programmatically change the implementation at startup using configuration, e.g. `GamesCosmosContext` `GamesInMemoryContext`.

When just the context type is offered, for every context type a proxy class is needed which just forwards methods to the context.

Thanks!

**Comment by christiannagel** [comment]
With the planned redesign of the EF components public API #1403, this scenario is not listed, but if the redesign is done using 2 calls as mentioned by @eerhardt https://github.com/dotnet/aspire/issues/1403#issue-2042691815, this will solve this issue as well.

**Comment by mitchdenny** [comment]
Triaging into preview three along with #1403

**Comment by sebastienros** [comment]
@christiannagel it's merged, you can know register the `DbContext` like you wanted and then call `EnrichSqlServerDbContext` (with SqlServer for instance). Here is sample inspired from the README in the component.

```c#
var connectionString = builder.Configuration.GetConnectionString("catalogdb");
builder.Services.AddDbContextPool<ICatalogDbContext, CatalogDbContext>(dbContextOptionsBuilder => dbContextOptionsBuilder.UseSqlServer(connectionString));
builder.EnrichSqlServerDbContext<CatalogDbContext>();
```
