### ISSUE TITLE
AddRedis method from RedisBuilderExtensions in Aspire.Hosting version 8.0.0-preview.2.23619.3 is now the same as AddRedisContainer

### ISSUE THREAD

**Issue by exe1337** [dotnet/aspire#1497]
The method AddRedis in RedisBuilderExtensions has changed between versions 8.0.0-preview.1.23557.2 and 8.0.0-preview.2.23619.3

Im using the plain aspire-starter --use-redis-cache template.

With the current version i cannot longer use my redis server which i have running on a VM.
Starting the apphost results with following error:

```
info: Aspire.Dashboard.DashboardWebApplication[0]
      Now listening on: http://localhost:15272
info: Aspire.Dashboard.DashboardWebApplication[0]
      OTLP server running at: http://localhost:16048
Docker could not be found. The error from Docker invocation was: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'docker.exe' with working directory 'C:\Users\XXX\AspireSample\AspireSample.AppHost'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Aspire.Hosting.Dcp.Process.ProcessUtil.Run(ProcessSpec processSpec) in /_/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs:line 102
   at Aspire.Hosting.Dcp.DcpHostService.EnsureDockerIfNecessaryAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 228
```

Version 8.0.0-preview.1.23557.2
![rider64_VAlt2euYTf](https://github.com/dotnet/aspire/assets/20195218/ecc271db-7bb5-403e-9c67-ae5ab93b7487)

Version 8.0.0-preview.2.23619.3 
![rider64_vHyt7CT7Gk](https://github.com/dotnet/aspire/assets/20195218/e75b743b-28be-4f74-978c-ce11773e9774)

Was this change intended or do i have to rely on docker desktop?

**Comment by mitchdenny** [comment]
That is confusing. Docker Desktop was _always_ required in preview 1 and preview 2. The `AddRedis` and `AddRedisContainer` methods past present and future all use Docker containers under the covers for local development.

The API change was intentional to signify that `AddRedis` is more about adding the "concept of a Redis instance" to your app, wherewas `AddRedisContainer(...)` means you literally want a container, and you want to do containery things to it like mutate environment variables and add data volumes.

**Comment by exe1337** [comment]
At this point of time i have moved away from aspire and trying to implement opentelemetry on my own. With the OTEL collector, Prometheus, Grafana and so on. 

But let me know if i can provide you with anything. 
At least for me this issue can be closed since im no longer using aspire directly.
