### ISSUE TITLE
How to add local script file?

### ISSUE THREAD

**Issue by Arthur-Lee** [dotnet/aspire#1499]
I want to use aspire to orchestrate one service including local PowerShell executable script. However, the error is observed.
![image](https://github.com/dotnet/aspire/assets/9337816/5bdd4f15-1c32-4213-a771-5d28ac719c26)

The snippet code just shows my usage:
`var builder = DistributedApplication.CreateBuilder(args);
var test = builder.AddExecutable("test", "one.ps1", "./");`

So, how can I add local script file to the executable resource?

**Comment by davidfowl** [comment]
The executable would be powershell, the argument would be the ps1 file.

**Comment by Arthur-Lee** [comment]
> The executable would be powershell, the argument would be the ps1 file.
> 
> ```cs
> var test = builder.AddExecutable("test", "powershell",  ".", "one.ps1");
> ```

Thanks, I can execute the local powershell script like this way:
`var test = builder.AddExecutable("test", "powershell", ".", "one.ps1", "-ExecutionPolicy", "Bypass");`
