### ISSUE TITLE
KubernetesClient.Model FiIe Missing

### ISSUE THREAD

**Issue by oduwole** [dotnet/aspire#1501]
### Type of issue

Other (describe below)

### Description

Could not load file or assembly 'KubernetesClient.Models, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/get-started/aspire-overview.md

### Document Version Independent Id

1b7d0d68-ea99-ae77-0b30-0bafb0195096

### Article author

@IEvangelist

**Comment by davidfowl** [comment]
Related to #1074

**Comment by danmoseley** [comment]
closing as seems no work required
