### ISSUE TITLE
Consider renaming component or resource methods to disambiguate and reduce confusion 

### ISSUE THREAD

**Issue by rawuser** [dotnet/aspire#1510]
I am following the steps from:
[https://learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-component?tabs=dotnet-cli](url)

However I am not able to add ServiceBus (screen below). 
![image](https://github.com/dotnet/aspire/assets/51515738/60cb1e5e-fc42-43ea-84ee-7a2da6e780cd)

Text:
`Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS1061	'IDistributedApplicationBuilder' does not contain a definition for 'AddAzureServiceBus' and no accessible extension method 'AddAzureServiceBus' accepting a first argument of type 'IDistributedApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	AspireStarter2.AppHost	G:\Aspire\AspireStarter2\AspireStarter2.AppHost\Program.cs	4	Active	
`

Thanks for input

**Comment by sebastienros** [comment]
Things you can check:
- The package reference and version to the in the csproj
- `<ImplicitUsings>enable</ImplicitUsings>` and `<IsAspireHost>true</IsAspireHost>` are present in the csproj, ensuring that you are adding it to the correct project type (Orchestrator). This will include the `Microsoft.Extensions.Hosting` automatically which is the one in which the `AddAzureServiceBus` extension is.

**Comment by davidfowl** [comment]
Our docs need some work. They should mention added that package to the apphost project

**Comment by alexhiggins732** [comment]
Same issue here. After browsing the source I found the extension method: `Microsoft.Extensions.Hosting.AspireServiceBusExtensions.AddAzureServiceBus` is excepting an `IHostApplicationBuilder` yet the builder is an `IDistributedApplicationBuilder` which does not implement `IHostApplicationBuilder`

![image](https://github.com/dotnet/aspire/assets/2246388/be55d1fa-3629-4005-a8c6-e47d11c09967)

![image](https://github.com/dotnet/aspire/assets/2246388/8ac60ec5-54c0-4aa8-afc3-41ea93032544)

![image](https://github.com/dotnet/aspire/assets/2246388/0dd3b8e3-a85e-4688-913b-4832c974c1b4)

![image](https://github.com/dotnet/aspire/assets/2246388/617010bc-e057-4fd0-b55b-398a578cbe1d)

**Comment by alexhiggins732** [comment]
Another issue: the method is `void AddAzureServiceBus` which prevents it from being used in orchestration:

![image](https://github.com/dotnet/aspire/assets/2246388/902535e5-97de-490d-bdf2-f282cf8e559d)

![image](https://github.com/dotnet/aspire/assets/2246388/dd03f897-af8e-41a5-8e99-da42919fdd94)

**Comment by davidfowl** [comment]
There are 2 different methods. One is in the AppHost (Aspire.Hosting.Azure) this is where the right `AddAzureServiceBus` is.

**Comment by alexhiggins732** [comment]
> There are 2 different methods. One is in the AppHost (Aspire.Hosting.Azure) this is where the right `AddAzureServiceBus` is.

That was the issues. The docs say: `dotnet add package Aspire.Azure.Messaging.ServiceBus --prerelease` but it should say

>  `dotnet add package Aspire.Hosting.Azure`, 

or possibly:

> In your project: `dotnet add package Aspire.Azure.Messaging.ServiceBus --prerelease` 
> 
> And in AppHost  `dotnet add package Aspire.Hosting.Azure --prerelease` 

Not sure which is needed.

![image](https://github.com/dotnet/aspire/assets/2246388/5b078d1f-ff23-46ac-936f-964ee5360729)

**Comment by bradygaster** [comment]
> Our docs need some work. They should mention added that package to the apphost project

cc @IEvangelist and @alistairmatthews

**Comment by jjhayter** [comment]
I am glad I kept digging at this issue to find this post, I was literally about to go to bed and shelve my aspire sandbox.

If I could offer one point of clarity. Show full sections in appsettings.json in their entirety, not just the ConnectionString section. IMHO that'll avoid ambiguity in Azure SDK (I noticed that Aspire wraps it) especially as search engines don't really see the differences.

It's not verbose, it's terse. :)
```
  "Aspire": {
    "Azure": {
      "Messaging": {
        "ServiceBus": {
          "ConnectionStrings": {
            "serviceBusConnectionName": "https://somethingsomethingdarkside.servicebus.windows.net"
          }
        }
      }
    }
```
I am also a bit unclear on the instance naming section but that's for a different day. Overall, I am floored by this tooling, I am looking forward to more as it rolls out!

**Comment by IEvangelist** [comment]
> > Our docs need some work. They should mention added that package to the apphost project
> 
> cc @IEvangelist and @alistairmatthews

I will say this again here, we keep building APIs with the exact same name - that do different things from different NuGet packages. Docs will always struggle to disambiguate this. We should really consider renaming these APIs before GA. That's my recommendation. I have heard from lots of folks, that they get confused (and I admit, I do too) and I believe it's because the APIs are the same name.

It's not an easy thing to tackle, naming things is hard. And it's easy to argue that the current names are meaningful in their current context, but the docs can only do so much. The component articles for example, have instructions to install the NuGet package for the component. Azure specific component articles include explicit instructions to install the appropriate hosting NuGet package in the **App host** section. But when the APIs are named the same, it's going to be confusing regardless.

/cc @davidfowl @eerhardt @mitchdenny

**Comment by eerhardt** [comment]
Any suggestion on what the naming pattern should be?

For the Azure specific components, this might just solve itself when the CDK work comes in. See https://github.com/dotnet/aspire/pull/2252

**Comment by davidfowl** [comment]
We can go with `AddXXResource` in the AppHost as a way to disambigutate.

**Comment by mitchdenny** [comment]
After thinking through this I think we should just disambiguate on the component side APIs where a change in name could actually add more clarity:

1. `AddAzureServiceBus(...)` => `AddAzureServiceBusClient(...)`
2. `AddAzureOpenAI(...)` => `AddOpenAIClient(...)`
3. `AddAzureCosmosDB(...)` => `AddCosmosClient(...)`

Thoughts @eerhardt @DamianEdwards @davidfowl ?
