### ISSUE TITLE
Pressing CTRL on the Dashboard Console Logs clear the output

### ISSUE THREAD

**Issue by laurentkempe** [dotnet/aspire#1518]
While browsing the Aspire Preview 2 Dashboard Console Logs, and pressing CTRL key
1. For project, the log output is cleared and reappear
2. For executable (Dapr), the output is cleared

You can see it in the following screen capture

https://github.com/dotnet/aspire/assets/272612/09a344ab-dee9-47ef-9b4a-f10760931e2a

**Comment by drewnoakes** [comment]
@laurentkempe thanks for the bug report. The code's changed a lot since then. I can no longer repro this bug. I'll close this.

If you still see this in preview 3 (once it's released) let us know and we'll re-open.

**Comment by laurentkempe** [comment]
@drewnoakes i am working with preview of preview 3 i will try it

**Comment by laurentkempe** [comment]
@drewnoakes I confirm that I don't see this problem anymore with preview.4.24102.19
