### ISSUE TITLE
Make manifest writing more annotation driven

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#1520]
Currently when we are writing the manifest we basically hand over a JsonWriter and have a callback annotation serialize whatever it wants into the manifest. We drive consistency by reusing various helper methods. I think the callback mechanism is good but I think that we can reduce the need to even call the helper methods if we automatically write more to the manifest based on what annotations are present on the resource.

A simple example might be the `type` field which is present on every resource but every custom callback needs to emit it. instead we should just have an annotation (or a property) on the resource which specifies the type string and it is done for us assuming the resource is actually written to the manifest.

**Comment by mitchdenny** [comment]
Tagging **tentatively** for offsite. This might just be an improvement we go and do so that manifest callbacks don't quite need to do as much (or are exclusively used for overriding the whole resource block).

**Comment by mitchdenny** [comment]
Moving to P5 tentatively as this is not a user facing feature. Some elements might happen in P4 as we look at PublishAs.

**Comment by davidfowl** [comment]
Concretely I think there are 2 things left:

Inputs which @eerhardt is working on
value.v0 We don't have a resoruce type for this and maybe we should

**Comment by eerhardt** [comment]
> Inputs which @eerhardt is working on

I believe this part is now complete with https://github.com/dotnet/aspire/pull/2546, https://github.com/dotnet/aspire/pull/2627, and https://github.com/dotnet/aspire/pull/2642.

> value.v0 We don't have a resoruce type for this and maybe we should

This is where I see this being used:

```
C:\git\aspire\src\Aspire.Hosting.Azure\AzureBlobStorageResource.cs(55):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting.Azure\AzureBlobStorageResource.cs(106):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting.Azure\AzureQueueStorageResource.cs(51):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting.Azure\AzureQueueStorageResource.cs(98):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting.Azure\AzureTableStorageResource.cs(51):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting.Azure\AzureTableStorageResource.cs(98):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting\MongoDB\MongoDBDatabaseResource.cs(50):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting\MySql\MySqlDatabaseResource.cs(50):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting\Oracle\OracleDatabaseResource.cs(49):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting\Postgres\PostgresDatabaseResource.cs(66):context.Writer.WriteString("type", "value.v0");
C:\git\aspire\src\Aspire.Hosting\SqlServer\SqlServerDatabaseResource.cs(67):context.Writer.WriteString("type", "value.v0");
```

All these cases are for "child" resources of some sort of "parent". I'm not sure how much we should do here. The only thing I can think of is to introduce a `abstract class ValueResource : Resource` class that has:

```C#
public virtual void WriteToManifest(ManifestPublishingContext context)
{
    context.Writer.WriteString("type", "value.v0");
```

But I'm not certain "burning the base class" here is worth this one line. But maybe it gives more structure for these "child" resources.

Thoughts?

**Comment by davidfowl** [comment]
Agreed. I'm also not sure if we need to do anything here.

**Comment by eerhardt** [comment]
The _other_ possibility is to have a simple method on `ManifestPublishingContext`:

```
public void WriteValueType()
{
    Writer.WriteString("type", "value.v0");
}
```

And all these places call that method instead of hard-coding it themselves. At least then you can easily see all the places that are using this.

**Comment by davidfowl** [comment]
Not worth it yet. I'm more interested in the value property than the type. We don' have a way to model that yet.

**Comment by eerhardt** [comment]
> I'm more interested in the value property than the type. We don' have a way to model that yet.

You mean for the ParameterResource?

**Comment by davidfowl** [comment]
No, the value.v0 resource. I'm going to close this as done @eerhardt
