### ISSUE TITLE
The `WithVolumeMount` extension method doesn't work with Azurite

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/aspire#1533]
If you want to persist your Azurite table/queue/blob data between app restarts you need to mount a volume from the host ([see the docs on how to do that](https://learn.microsoft.com/azure/storage/common/storage-use-azurite?tabs=docker-hub%2Cqueue-storage#run-azurite)).

With other container options you can use the extension method `WithVolumeMount`, like so:

```c#
IResourceBuilder<PostgresContainerResource> postgresContainerDefinition = builder
    .AddPostgresContainer("db")
    .WithEnvironment("POSTGRES_DB", "my_data")
    // Mount the database scripts into the container that will configure pgvector
    .WithVolumeMount("./database", "/docker-entrypoint-initdb.d", VolumeMountType.Bind);
```

But the extension method doesn't work for Azurite because it's signature is:

```csharp
public static IResourceBuilder<T> WithVolumeMount<T>(this IResourceBuilder<T> builder, string source, string target, VolumeMountType type = default, bool isReadOnly = false) where T : ContainerResource
```

And `AzureStorageResource`, which is the type when working with Azure Storage, isn't `ContainerResource`.

To solve this the `UseEmulator` method should return a type that can support `WithVolumeMount` while not accidentally supporting it if you're deploying to Azure Storage _without_ the emulator.

## Workaround

The workaround is to write out the full `WithAnnontation` call, like so:

```csharp
storage.UseEmulator()
.WithAnnotation(new VolumeMountAnnotation("./data/azurite", "/data", VolumeMountType.Bind));
```

**Comment by davidfowl** [comment]
I think the way to handle this is to give access to customize the container based resources in a callback:

```
storage.UseEmulator(container => container.WithVolumeMount(...))
```

**Comment by aaronpowell** [comment]
Providing a callback to configure emulator-specific options would be a good idea.

**Comment by davidfowl** [comment]
@aaronpowell would you like to send a PR?

**Comment by aaronpowell** [comment]
Should be able to get a PR up for review

**Comment by aaronpowell** [comment]
PR #1631 opened for it. I ended up providing a new argument to the `UseEmulator` that takes the path for the emulator data rather than a callback function to configure it because the callback wouldn't have added any additional functionality to address the problem.

Since `AzureStorageResource` doesn't inherit `ContainerResource`, which `WithVolumeMount` is tied to, we'd still need to introduce a new type like `AzureStorageEmulatorResource` to have an extension method made available via. This seemed overly complex for the solution required when an argument would address the needs just as well.
