### ISSUE TITLE
Date formats on Dashboard aren't consistently honoring regional config

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#1551]
My setup:
Dates: dd-Mmm-YYYY
Time: HH:mm

Resources view (correct):
![image](https://github.com/dotnet/aspire/assets/4821/983ed55f-9a55-41b6-abc1-578d0ec99319)

Structured Logs/Traces timestamp:
![image](https://github.com/dotnet/aspire/assets/4821/73ccba6d-fd0c-4762-8a3c-cfb8302b0bd2)

Metrics:
![image](https://github.com/dotnet/aspire/assets/4821/c448710e-caaa-476e-b688-7d62d144f106)

Likely because of this US-centric hard-code format: https://github.com/dotnet/aspire/blob/1cbea342b307da55f83aa001ef6bce7a6fbaf9d6/src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs#L47

**Comment by leslierichardson95** [comment]
Consider adding time format options in the future.  Honor the date format

**Comment by drewnoakes** [comment]
The challenge here is wanting the user's preferred time format, but to also show milliseconds on the time span.

From https://learn.microsoft.com/en-us/dotnet/standard/base-types/how-to-display-milliseconds-in-date-and-time-values:

> A problem with defining a complete custom format specifier that includes the millisecond component of a date and time is that it defines a hard-coded format that might not correspond to the arrangement of time elements in the application's current culture. A better alternative is to retrieve one of the date and time display patterns defined by the current culture's [DateTimeFormatInfo](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo) object and modify it to include milliseconds. The example also illustrates this approach. It retrieves the current culture's full date and time pattern from the [DateTimeFormatInfo.FullDateTimePattern](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.fulldatetimepattern) property and then inserts the custom pattern fff along with the current culture's millisecond separator. The example uses a regular expression to do this operation in a single method call.

**Comment by drewnoakes** [comment]
Fix in review with https://github.com/dotnet/aspire/pull/2135
