### ISSUE TITLE
IServiceMetadata types aren't generated for projects referenced when ReferenceOuputAssembly=false

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#1563]
From an AppHost project, when referencing a service project via a `<ProjectReference />` in the .csproj file, types are generated by the Aspire targets that implement `IServiceMetadata` such that calls to `AddProject<TProject>(...) where TProject : IServiceMetadata` can be used to configure the app topology.

If the service project has an incompatible TFM or other issue that prevents it from being referenced as a "standard" `ProjectReference`, then metadata can be added to the reference to prevent the output assembly being passed to the compiler, effectively turning the project into a simple build dependency but not a "reference", e.g.:

```csproj
<ItemGroup>
  <ProjectReference Include="..\ClientAppsIntegration.ApiService\ClientAppsIntegration.ApiService.csproj" />
  <ProjectReference Include="..\ClientAppsIntegration.WinForms\ClientAppsIntegration.WinForms.csproj"
                    SkipGetTargetFrameworkProperties="true"
                    ReferenceOutputAssembly="false" />
  <ProjectReference Include="..\ClientAppsIntegration.WPF\ClientAppsIntegration.WPF.csproj"
                    SkipGetTargetFrameworkProperties="true"
                    ReferenceOutputAssembly="false" />
</ItemGroup>
```

When doing this however, the `IServiceMetadata` types are not generated so the project has to be added to the `DistributedApplicationBuilder` using the project path instead:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var apiService = builder.AddProject<Projects.ClientAppsIntegration_ApiService>("apiservice");

// Register the client apps by project path as they target a TFM incompatible with the AppHost so can't be added as
// regular project references (see the AppHost.csproj file for additional metadata added to the ProjectReference to
// coordinate a build dependency though).
builder.AddProject("winformsclient", "../ClientAppsIntegration.WinForms/ClientAppsIntegration.WinForms.csproj")
    .WithReference(apiService);

builder.AddProject("wpfclient", "../ClientAppsIntegration.WPF/ClientAppsIntegration.WPF.csproj")
    .WithReference(apiService);

builder.Build().Run();
```

**Comment by mitchdenny** [comment]
Tagging for offsite because this talks to some of the challenges with the project reference model.

**Comment by DamianEdwards** [comment]
Proposal for potential fix for this general issue:

Introduce a new MSBuild item definition, e.g. `AspireProjectResource`. Targets brought in to AppHost projects from the Aspire SDK bits will generate `ProjectReference` items for these with the `SkipGetTargetFrameworkProperties="true"` and `ReferenceOutputAssembly="false"` metadata properties (maybe `ExcludeAssets="all"` too?). Additionally, the existing targets that code generate the `IServiceMetadata` types will be changed to use the `ProjectReference` items themselves, rather than the resultant referenced assembly items.

We'd update the templates and VS tooling to emit `AspireProjectResource` items into the AppHost .csproj when performing Aspire orchestration gestures.

This way, existing AppHost projects using `ProjectReference` items will still work, and folks not using VS can still use `dotnet add reference` to add references to service projects from the AppHost project. If they hit a case where a default `ProjectReference` causes an issue in the AppHost, they can manually change it to an `AspireProjectResource` to resolve it.

/Cc @baronfel

**Comment by rainersigwald** [comment]
That seems fine to me. You'll have to be careful to do the transformation either at evaluation time in `.targets` (if possible) or at latest `BeforeTargets="$(PrepareProjectReferencesDependsOn)"` (we don't provide a nice single hook for that layer of customization--even though `PrepareProjectReferences` sounds like it should be it, it assumes `@(ProjectReference)` is fully populated).

I do think you'll want `ExcludeAssets="all"`.

**Comment by eerhardt** [comment]
Another idea I had is if we could do some defaulting logic based on if the `ProjectReference` was pointing to an `Exe` or `Library`. If it is pointing at a `Library`, then we default to be a "true" ProjectReference - you still get `ReferenceOutputAssembly="true"`, `SkipGetTargetFrameworkProperties="false"`, `ExcludeAssets="none"`.

This might be too _magical_, but it could give us the intended user experience.

From my perspective there are 3 high-level approaches we could take:

1. Introduce a new item type like `AspireProjectResource`
2. Always default `ProjectReferences` in the AppHost to be `ExcludeAssets="all"`, et.al
    - If we take this approach, we would also introduce a single "opt-out" item, so if users needed a "true" ProjectReference, they could just say `<ProjectReference Include="..." AspireHostReference="true" />` (name TBD). `AspireHostReference="true"` would tell our defaulting logic to keep it a "normal" ProjectReference.
3. Try to detect what kind of `ProjectReference` it is, and default based on that

An option we can take is to do (2) for .NET Aspire 8.0, with the option that we upgrade to (3) in the future if we think more people need real ProjectReferences from their AppHost. I think needing a real ProjectReference is a valid scenario, but it is definitely less than 20% use case.

thoughts @davidfowl @DamianEdwards @rainersigwald @baronfel ?

**Comment by DamianEdwards** [comment]
> An option we can take is to do (2) for .NET Aspire 8.0, with the option that we upgrade to (3) in the future if we think more people need real ProjectReferences from their AppHost. I think needing a real ProjectReference is a valid scenario, but it is definitely less than 20% use case.

I think this is a good compromise. Default `ProjectReference` to the Aspire behavior and add an opt-out metadata property. It also means we don't have to change anything in the Visual Studio experience as all the existing gestures to add a project reference just work.

**Comment by eerhardt** [comment]
> I do think you'll want ExcludeAssets="all".

It looks like this isn't respected by NuGet. See https://github.com/NuGet/Home/issues/10907. Following approach (2) above, even though we don't reference the assembly coming from a ProjectReference, the AppHost still gets references to the PackageReferences pulled in transitively through this ProjectReferences.

For example,

`AppHost` => `ApiService` => `Aspire.StackExchange.Redis`

When `AppHost` is getting compiled, it doesn't get a reference to `ApiService`, but it still gets a reference to `Aspire.StackExchange.Redis`. I'm not sure if this is a blocker or not. In order to fix it (without the NuGet fix to respect ExcludeAssets), I think we would have to take approach (1) and not use ProjectReference at all (even under the covers).
