### ISSUE TITLE
Create integration tests for the rest of the Components

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#1566]
We are missing the EntityFramework components in our functional integration tests added in #1217. We should add them, plus any other missing components that would be valuable.

TODO:
- [x] efsqlserver
- [x] efcosmos
- [x] eforacle
- [x] efpostgres

**Comment by radical** [comment]
Is this referring to:

https://github.com/dotnet/aspire/blob/eb08a4ab513215503ec4a4b87dba8ceae17e368b/tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs#L18-L34

So, essentially connect, and try some basic operation?

**Comment by eerhardt** [comment]
Correct. There are components that aren't covered in those tests - like the EF postgres and sql server components.

**Comment by joperezr** [comment]
@eerhardt is this issue stale? Are we still missing some test coverage here? If so, is 8.1 the right milestone? I don't think that Ankit is currently looking into this.

**Comment by eerhardt** [comment]
> is this issue stale? Are we still missing some test coverage here?

I'm not sure what you mean by "stale", but this issue is still relevant. We don't have these integration tests yet. So yes we are missing some test coverage here.

> If so, is 8.1 the right milestone?

Yes, I believe so. We want better test coverage in 8.1.

**Comment by radical** [comment]
Last ones completed by https://github.com/dotnet/aspire/pull/4758 .
