### ISSUE TITLE
Propose & Evaluate New Components For Aspire

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire#1569]
I didn't feel like writing out a bunch of individual issues for each and every component, so I am just going to list some ideas out for some components that I think would be nice to haves for Aspire and am looking for feedback on potential ideas, push back on certain ones, which ones seem the easiest or realistic, or whatever is on your mind. Anyway here's what I've came up with. 

## Database
- Mariab DB with and without EF Core

## Storage
- Minio (for those on AWS and on prem)

## Secrets / Config
- Vault (for those who can't utilize azure keyvault for whatever the reason)

## Messaging
- Kafka (issue already exists, having it include the Kafka UI image too)
- NATS
- MQTT

## Feature Flags
- Unleash

## Emails
- Mailpit (local email smtp server)

## Data Aggregating
- fluentd
- Logstash
- Debezium

## Api Gateways
- Kong

## Feature Flags
- Unleash

## Emails
- Mailpit (local email smtp server)

## Search
- Elastic Search and Kibana
- Meilisearch
- Solr 

## Container Registries
- Registry2
- Harbor Registry

## CI/CD
- Jenkins
- Gitlab CI/CD workers

## Devtools
- Data API builder for Azure Databases
- Kusto emulator
- Rancher
- Portainer
- Semaphore

## CLIs
- Azure CLI
- AWS CLI
- etc... 

### Note
Some of these I think I would are more suited to be more additions / iterations to what's in place like search and emails.

Some of these I items aren't necessarily tied to a typical 'developer' workflow, but things that I do or have done locally and that I think would be nice to haves like cloud cli and or rancher. Just so that a non dev could easily spin up some dev ops containers and resources and see the relationship between the resources, the same way aspire is doing for .web, api, db, cache, and queue applications right now.

**Comment by davidfowl** [comment]
This might make more sense as a discussion because most of the items aren’t things that can just be added and require lots of new design. Much of this is out of scope for v1.

**Comment by josephaw1022** [comment]
moved over to discussion

**Comment by MatsM16** [comment]
Link to discussion: https://github.com/dotnet/aspire/discussions/1570
