### ISSUE TITLE
Display short container ID

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1584]
The full docker container ID is long. 64 characters. Ain't nobody got time for that.

Docker command line tools and UI tooling such as Docker for Windows display the short container ID. The short container ID is the first 12 characters of the ID, and realistically will always be enough to uniquely identify a container.

See https://www.baeldung.com/ops/docker-container-id-from-name

Examples:

```
$ docker container ls -a
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS     NAMES
80f1bc1e7feb   nginx:alpine   "/docker-entrypoint.…"   36 seconds ago   Up 36 seconds   80/tcp    web-server-11
acdea168264a   nginx:alpine   "/docker-entrypoint.…"   36 seconds ago   Up 36 seconds   80/tcp    web-server-10
0cbfc6c17009   nginx:alpine   "/docker-entrypoint.…"   37 seconds ago   Up 36 seconds   80/tcp    web-server-1
```

![image](https://github.com/dotnet/aspire/assets/303201/a04dce10-10c2-4162-a839-36edde76669f)

The Aspire dashboard should display the short ID. The copy button should copy the full 64-character value.

**Comment by JamesNK** [comment]
I see we already were shortening the ID in places to 8 chars. It should be shortened to 12 chars.

**Comment by danmoseley** [comment]
What about the text name like wizardly-moser in your screen shot? They might be easier to eyeball.

**Comment by JamesNK** [comment]
I don't think that's necessary. The Aspire project has a name the user has specified for the container resource, e.g. "CatalogDB" for a postgres DB container.

But now that you point it out, why does the Docker UI have those silly names for Aspire containers? "CatalogDB" in the Docker UI would be more useful than wizardly-moser...

**Comment by JamesNK** [comment]
Issue for the name in Docker: https://github.com/dotnet/aspire/issues/1587
