### ISSUE TITLE
Create threat model for app model

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/aspire#1603]
@mitchdenny 

Relates to #237

- [ ] Enable ability to globally override image registry
    - https://github.com/dotnet/aspire/pull/3037
- [ ] Can we produce an SBOM with a closure of our dependencies (container)
- [x] Increase entropy on password generation beyond 128 bits.
    - https://github.com/dotnet/aspire/pull/2717
    - https://github.com/dotnet/aspire/pull/2740
- [ ] Ensure that port conflicts on container and process launch results in failure from DCP that we must respond to (port squatting)
- [ ] Investigating securing comms between AppHost to DCP to Docker/Podman
- [ ] Investigating securing comms between Dashboard to AppHost.

**Comment by GrabYourPitchforks** [comment]
> Increase entropy on password generation beyond 128 bits.

BTW, here's how I performed the entropy calculation. The parameters _a_, _b_, _c_, _d_ are the arguments to this function:

https://github.com/dotnet/aspire/blob/813fc19c3acf1a644f23157f608a40a2f4ce829f/src/Aspire.Hosting/Utils/PasswordGenerator.cs#L29

```math
\log_2( \frac{23^a \cdot 23^b \cdot 10^c \cdot 11^d \cdot (a + b + c + d)!}{a! \cdot b! \cdot c! \cdot d!} )
```

With _a := 6_, _b := 6_, _c := 2_, _d := 2_, this shakes out at ~91 bits of entropy.
