### ISSUE TITLE
Suspect argument on FileNotFoundException in DistributedApplicationOptions.ResolveAssembly()

### ISSUE THREAD

**Issue by epsitec** [dotnet/aspire#1607]
When `DistributedApplicationOptions.ResolveAssembly()` fails to find the assembly with the given `AssemblyName`, the following exception gets thrown:

https://github.com/dotnet/aspire/blob/8aa6c1822a8400db5772e563b54847e239d7cc88/src/Aspire.Hosting/DistributedApplicationOptions.cs#L61

I suspect this is not the intended message. I'd rather have this piece of code instead:

```cs
throw new FileNotFoundException($"No assembly with name '{AssemblyName}' exists in the current AppDomain.");
```

**Comment by danmoseley** [comment]
Thanks. Would you like to offer a PR?

**Comment by epsitec** [comment]
Sorry for the noise, I messed up by initially referencing the issue in a merge request done on my fork, rather than on the official repository. I hope my second attempt will be fine.
