### ISSUE TITLE
Consistent behavior of subscription cancellation and OperationCanceledException

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1618]
Subscriptions are represented by `IAsyncEnumerable` in many places. Canceling the enumerable has flaky behavior. Canceling the token can cause the foreach to finish or throw `OperationCanceledException`. They should have consistent behavior in one direction or the other.

More info: https://github.com/dotnet/aspire/pull/1589#discussion_r1446686636

**Comment by drewnoakes** [comment]
There's no known outstanding work here now.
