### ISSUE TITLE
Ship the dashboard as a container image

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1621]
As part of https://github.com/dotnet/aspire/issues/1003, we should be producing container images for the dashboard so it can be deployed into any environment that supports the resource server or just wants an easy to deploy otlp server.

**Comment by danmoseley** [comment]
Image for ACA

**Comment by joperezr** [comment]
This is now done. We will continue to iterate with the ACA team to ensure the image we produce meets their needs.
