### ISSUE TITLE
AddRabbitMQContainer uses wrong default password

### ISSUE THREAD

**Issue by rolfik-mycronic** [dotnet/aspire#1626]
AddRabbitMQContainer uses null as default password instead of `guest`.

Aspire.Hosting 8.0.0-preview.2.23619.3

**Comment by mitchdenny** [comment]
Oh I think I see where you are getting this from. It is true that the default value for the password parameter on the `AddRabbitMQContainer(...)` method is null. however inside the implementation we do this:

https://github.com/dotnet/aspire/blob/33331a086b1688355fb3f421fef1bf359553f907/src/Aspire.Hosting/RabbitMQ/RabbitMQBuilderExtensions.cs#L25

**Comment by rolfik-mycronic** [comment]
Yes.
So either change the parameter argument comment or use "guest" instead of new guid, please.
But it worked with "guest" before in older Aspire version so now it is a braking change in current one.
It was changed in
https://github.com/dotnet/aspire/commit/1ae3c4001647d68a5d1cc44f477ccb5bfa64a5b8#diff-ea2cfbd98543b54b3dd6aab6148f4ddcda0fd9c1ffe57ff8ff73693752060057

**Comment by mitchdenny** [comment]
This change was intentional. Can you describe why you would like the password hardcoded to guest?

**Comment by rolfik-mycronic** [comment]
We are using the password in development. Why not :-)

**Comment by rolfik-mycronic** [comment]
This is not about any password, but about inconsistency in parameter documentation and actual behavior.

**Comment by DamianEdwards** [comment]
@rolfik-mycronic can you please send a PR to fix the parameter documentation?

**Comment by mitchdenny** [comment]
> This is not about any password, but about inconsistency in parameter documentation and actual behavior.

That was the detail I was missing. Thanks!

**Comment by mitchdenny** [comment]
Fixed in PR: https://github.com/dotnet/aspire/pull/1643
