### ISSUE TITLE
[WebToolsE2E][Aspire] In the dashboard, the "Hide Values" button is not available.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#1634]
**REGRESSION INFO**: Worked fine on Aspire template 8.0.0-preview.1 / 8.0.0-preview.2 (latest-released)

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 from [34509.254.main]
3. CLI workload update and install aspire 8.0.0-preview.3.24060.9
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web API > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Build and F5
3. In the dashboard, click View > click 'Hide values' button

**ACTUAL**

![Animation](https://github.com/dotnet/aspire/assets/71361488/a217ee89-58b2-4341-aea5-c4121509d76f)

**EXPECTED**

![image](https://github.com/dotnet/aspire/assets/71361488/e920c4e6-a853-4442-9d00-20b3a124b0ff)

**Comment by davidfowl** [comment]
I think this button only applies to the environment variables section in the joint details view.

**Comment by drewnoakes** [comment]
@v-sherryfan if you scroll down, do you see environment variables?

If not, we may wish to disable the button when none are available, similar to what was done in https://github.com/dotnet/aspire/pull/1293.

**Comment by v-sherryfan** [comment]
@drewnoakes Yes, if I scroll down , I do see environment variables. Deatils are as below.
![issue1](https://github.com/dotnet/aspire/assets/71361488/0e7aa6bb-e3c8-4ffa-9716-074b0d7c8fd8)

**Comment by drewnoakes** [comment]
@v-sherryfan thanks, in that case I don't think there's a bug here. We just changed the presentation a little. I'll close this. Please re-open if I've misunderstood.
