### ISSUE TITLE
[WebToolsE2E][Aspire] Running an aspire project, the endpoint url is http://127.0.0.1:xxx instead of http://localhost:xxx in the dashboard.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#1635]
**REGRESSION INFO**: Worked fine on Aspire template 8.0.0-preview.1 / 8.0.0-preview.2 (latest-released)

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 from [34509.254.main]
3. CLI workload update and install aspire 8.0.0-preview.3.24060.9
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web API > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Build and F5
3. In the dashboard, the Endpoints url is 'http://127.0.0.1:xxx'

**ACTUAL**
![image](https://github.com/dotnet/aspire/assets/71361488/9e0b8d77-4490-4d7c-90c6-0fa7182cb82a)

**EXPECTED**
![image](https://github.com/dotnet/aspire/assets/71361488/b34d291f-b558-4d1e-9567-915d8ea262c5)

**Comment by davidfowl** [comment]
@drewnoakes Did this change happen when we moved out of process?

**Comment by drewnoakes** [comment]
Not that I'm aware of. It's late here, but I can bisect back tomorrow or early next week to find out (if no one beats me to it).

**Comment by davidfowl** [comment]
@David-Engel  @karolz-ms could this be a dcp change?

**Comment by karolz-ms** [comment]
Yes, this is a DCP change and it is by design. I can explain in detail, but in short, `localhost` is an ambiguous reference, so DCP now always returns specific IP address for allocated endpoints.

**Comment by davidfowl** [comment]
Seems undesirable.

**Comment by DamianEdwards** [comment]
We need to understand the reasoning behind this change so we can best determine a path forward. This experience isn't an acceptable regression IMO.

**Comment by karolz-ms** [comment]
OK. `localhost` is not a single address, it is a set of addresses that are bound to "loopback" interfaces on the machine. Majority of the machines these days are dual-stack (IPv4 and IPv6), and so they get at least 2 addresses associated with localhost name, `127.0.0.1` and `[::1]`. When a program resolves localhost, what address gets used/preferred, depends on the resolver library that the program uses. Some (.NET included) prefer IPv4, some prefer IPv6.

In DCP, when a Service spec says the address to bind to is "localhost", the DCP will bind to all addresses that are associated with localhost name, to maximize the chance that clients can connect to the service. Then, if the spec for the Service does not include a port, a dynamic port will be auto-allocated for each address, but it won't necessarily be the same port for each address. So when the Service status is updated with the address and port to use by clients, DCP uses one of the specific addresses and corresponding port. This is guaranteed to work, unlike `localhost:port` combination, which can mean different things depending on how `localhost` is resolved.

If the use of real IP in the dashboard UI is undesirable, the dashboard service could recognize that the reported Service address is one of localhost addresses and modify the display portion of the link to use `localhost`, that is, use something like

`<a href="http://127.0.0.1:1234">http://localhost:1234</a>`

**Comment by DamianEdwards** [comment]
> If the use of real IP in the dashboard UI is undesirable, the dashboard service could recognize that the reported Service address is one of localhost addresses and modify the display portion of the link to use localhost, that is, use something like <a href="http://127.0.0.1:1234">http://localhost:1234</a>

This falls over as soon as it's clicked though as now a tab is opened with the 127 address in the address bar.

Can you point to some concrete cases where the port would be different between IPv4 vs. IPv6 for localhost? I don't quite understand that part of the reasoning.

**Comment by karolz-ms** [comment]
This is because when a program code says "I want to listen on localhost", or "I want to connect to localhost", under the covers one of the localhost addresses is chosen. If the client and the server choose different addresses, or even prefer different addresses, at best you get a significant delay, and at worst you can't communicate at all.

**Comment by DamianEdwards** [comment]
In the "I want to listen on localhost" case, it's normal for the program to bind to both IPv4 and IPv6 loopback addresses. As you point out, in the "I want to connect to localhost" case, on systems with IPv6 enabled, it seems it's normal to first attempt to connect to IPv6 loopback before falling back to IPv4.

This doesn't address the point you made about ports though. In what case would DCP bind to both IPv4 and IPv6 loopback based on being asked to bind to localhost, but use different ports for each? At any rate, that's not happening here, and that seemingly edge-case scenario is greatly impacting the UX for the very mainline scenarios. Perhaps DCP can track if both addresses (IPv4 and IPv6) used the same port, it can report the endpoint as simply being "localhost" with the port used, only in the case where different ports end up being assigned would it return separate endpoints for localhost. Better yet, why not just not commit to a random port until it can be used by both IPv4 and IPv6 loopback (when applicable), to avoid the split-port problem altogether?

**Comment by karolz-ms** [comment]
@DamianEdwards and I had a chat offline. Here is what we learned and the plan

> on systems with IPv6 enabled, it seems it's normal to first attempt to connect to IPv6 loopback before falling back to IPv4.

This is by no means a universal rule. E.g. .NET client will prefer IPv4, we learned that early in Aspire development cycle.

>  Perhaps DCP can track if both addresses (IPv4 and IPv6) used the same port, it can report the endpoint as simply being "localhost" with the port used, only in the case where different ports end up being assigned would it return separate endpoints for localhost. 

This is what we are going to do. In other words, DCP will try to use the same port for all "localhost" addresses. If that succeeds (which should be majority of cases), great, we can tell the clients to use "localhost" as the endpoint address. If not, we will fall back to the current behavior (use specific IP address/port combination).

**Comment by rozbo** [comment]
The IP address might be a more logical choice for the endpoint, but not for the URL. Let me elaborate on how bad the current situation is for practical use.

* It does not respect the applicationUrl field in launchSettings.json. Even if we set the applicationUrl to https://localhost:4444, after starting with Aspire, it becomes https://127.0.0.1:4444.
* It causes the HTTPS certificate to be invalid. During development, dotnet always recommends us to use a self-signed certificate, i.e., dev-certs, to use https://localhost:4444(as shown above). But if you access through https://127.0.0.1:4444, an error will occur, i.e., the certificate is invalid.
* It will cause serious problems with service discovery. Service discovery will automatically inject the monitored endpoint, and as mentioned above, it will inject an incorrect address that cannot be accessed at all, causing the entire service to be paralyzed.

**Comment by rozbo** [comment]
Assuming we can't change the decision of DCP , thinking from the premise of usability, we should at least change the service discovery logic to inject its URL instead of the endpoint.
Or, a simpler idea is to give the user the chance to choose and provide a simpler callback for adding environment variables for service discovery, with providing necessary parameters such as the listening port, so that the developer can add the environment in the callback. This will also have the added benefit of being able to customize the format of the injected environment variables.
eg.
for anyone who use the abp.net framework.
```c#
builder.WithEnvironment((context) =>
                        {
                            //
                            if (context.EnvironmentVariables.TryGetValue($"services__{discoveryName}__0", out var url))
                            {
                                context.EnvironmentVariables[$"RemoteServices__{discoveryName}__BaseUrl"] = url.Replace("127.0.0.1","localhost");
                            }
                        });
```

**Comment by karolz-ms** [comment]
The fix is part of the new DCP, which should be integrated into Aspire workload later today.

**Comment by v-sherryfan** [comment]
Verified that this issue is not reproduced on 17.10.0 Preview 1.0 [34522.204.main] + Aspire.ProjectTemplates.8.0.0-preview.3.24072.7

**Comment by GMouaad** [comment]
I know this not related to this issue, but can the DCP (i.e. api-server?) be configured to listen on an ipv4 interface, e.g. 127.0.0.1 rather than [::1]?
I think is causing some problems when using a proxy.

**Comment by davidfowl** [comment]
> I know this not related to this issue

File a new issue please.
