### ISSUE TITLE
Support proxy-less endpoints

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1637]
This issue outlines how networking works in aspire https://github.com/dotnet/docs-aspire/issues/232. Today we spin up a proxy for each endpoint which means the application being proxied needs to be amenable to accepting a port to listen on. The proxy is important for 2 reasons:
1. We can avoid forwarding the connection until the underling endpoint is ready
2. We can route to multiple replicas of the underlying service

The scenario that does not work is the one described here https://github.com/dotnet/docs-aspire/issues/232#issuecomment-1884575748

> We have also a legacy java http service running on specific port on Windows.
We add the service as a console project managing its execution.
How can I specify its port in WithServiceBinding if it is not running in a container?
If i set the hostPort to the service port, the proxy blocks the port and the service cannot be started.

In this scenario, there can be no proxy because the underlying process can't listen to anything but the port it already has. The only work around for this today is to avoid using WithEndpoint (formerly WithServiceBinding) but that breaks the ability to add references to other resources (WithReference) and it also means the dashboard doesn't show the url for the service.

Open questions:

- What happens when a resource has endpoints that are proxy-less and proxied? This probably shouldn't be allowed.

**Comment by DamianEdwards** [comment]
Does DCP already support a way to disable proxying or will this require work there too?

**Comment by mitchdenny** [comment]
I think that perhaps proxy support is a per endpoint option rather than a per resource option. So perhaps we could do something like this:

`WithEndpoint(....other args..., bool? proxy = true)`

@karolz-ms can comment on whether DCP still supports proxyless executables/containers.

**Comment by karolz-ms** [comment]
Yes, DCP supports proxyless mode. It currently designed for singletons, but could be enhanced to support replicated services too.

**Comment by mitchdenny** [comment]
@JamesNK

**Comment by davidfowl** [comment]
Giving this to you @JamesNK

**Comment by davidfowl** [comment]
I think the design here needs to be based on the resource itself being proxyless. It solves many of the ambiguities.
