### ISSUE TITLE
Container resource.exitCode=-1.00

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1641]
The new resource details UI allows display of all properties. Containers display a `resource.exitCode` property of `-1.00`. Is this expected? The container is running so I'm not sure what it represents.

![image](https://github.com/dotnet/aspire/assets/303201/33f5b3a0-9891-49a9-a360-5b98ac659e82)

**Comment by drewnoakes** [comment]
@JamesNK #1994 fixes the weird number format. I cannot repro what you're seeing above though. The `resource.*` items do not show for me. Looking at the code, I'm not sure how they would appear. Can you still repro this?

**Comment by JamesNK** [comment]
Click the show all button:

![image](https://github.com/dotnet/aspire/assets/303201/71ed8bbc-d133-4a5e-af56-addb50d7df1b)
