### ISSUE TITLE
Replica resource names in dashboard - Name displayed in UI doesn't match resource.name property

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1642]
A resource has two name properties:
* resource.name - It always includes the complete name ID, including the suffix. e.g. catalogservice-fuqslcg.
* resource.displayName - It just has the name supplied in the Aspire host. e.g. catalogservice.

The resource.name property doesn't match the resource name displayed throughout the UI. This is confusing. Is it a bug or is it expected?

The UI is doing some hacking of strings to calculate the name displayed in the UI. Shouldn't the resource server just return a good value in resource.displayName and the UI displays that?

![image](https://github.com/dotnet/aspire/assets/303201/60ae5e32-bdc5-404e-8723-a684fbddba16)

**Comment by JamesNK** [comment]
cc @karolz-ms

**Comment by JamesNK** [comment]
The reason is the name in the UI includes the uid: https://github.com/dotnet/aspire/blob/e3fc7cc96166078b27ba9e63558761ef265a2fcd/src/Aspire.Dashboard/Model/ResourceFormatter.cs#L8

Should it be resource.name instead?

**Comment by drewnoakes** [comment]
See also https://github.com/microsoft/usvc/issues/124. That provides a less cryptic display name for replicas, and needs to be wired through to the UI.

**Comment by kvenkatrajan** [comment]
@tlmii have we removed ResourceName from the resource section of the details view?

![image](https://github.com/dotnet/aspire/assets/102772054/f249c7d7-80f3-40a0-9895-16416c15ad20)
This aligns with : 
![image](https://github.com/dotnet/aspire/assets/102772054/aa2e8e4d-06e7-4a2d-a0fc-cad655c95d97)
Does this issue still manifest or we can close this one?

**Comment by JamesNK** [comment]
Was done here - https://github.com/dotnet/aspire/pull/2282
