### ISSUE TITLE
Metrics filter is missing a scrollbar

### ISSUE THREAD

**Issue by raffaeler** [dotnet/aspire#1652]
In the metrics view, the values added through the `KeyValuePair`s related to the custom metrics are added to the filter fields automatically.
If the value list is very long, I can go through any of them with the left and right arrows and eventually delete the values.
I deleted them all but I can only add the values that are visible in the list, which does not provide any scrollbar.
As a result, most of the values cannot be added back.

In the following picture, I can only add the values from `-1` to `-17` and nothing more (even if using the keyboard).
![image](https://github.com/dotnet/aspire/assets/5183152/021090f2-63db-4edc-83e7-fe401b50b5ea)

As of today, I updated the workload and all thet NuGet preview packages.

**Comment by JamesNK** [comment]
This UI has been replaced with a popup + checkboxes. You can wait for the next Aspire release or try out a daily build - https://github.com/dotnet/aspire/blob/main/docs/using-latest-daily.md

**Comment by raffaeler** [comment]
Got it, thank you @JamesNK
