### ISSUE TITLE
[WebToolsE2E][Aspire] After adding '.WithReplicas();', opening endpoint http://127.0.0.1:xxx of webfrontend, clicking 'Counter' will show an unhandled error.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#1660]
**REGRESSION INFO**: Worked fine with Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1[34511.213.main]
3. Install Aspire Preview 3 latest build 8.0.0-preview.3.24064.1
4. Apply NuGet Feeds

**REPRO STEPS**

1. Open VS, create a new project > Aspire Starter Application > .NET 8.0 (Preview) > Create 
2. Open Program.cs of xxx.AppHost project, add following codes: 
`.WithReplicas();`
3. Ctrl F5
4. On the dashbooard, click the endpoint url http://127.0.0.1:xxx/ of webfrontend
5. On the page, click 'Counter' and 'Weather' multiple times.

**NOTE**:
1. Sometimes, it just need to click 'Counter' once, this issue can repro easily.
2. This issue also repro on Aspire Starter Application with redis checked.

**ACTUAL**
It will show an unhandled error.
![image](https://github.com/dotnet/aspire/assets/82028229/f1e9d959-2a0a-4775-99e4-08cd738610cc)

**EXPECTED**
No error shows

**Comment by davidfowl** [comment]
This is failing because of lack of sticky load balancing when making requests to replicas through the TCP proxy. SignalR requires stickyness to work. Not sure what the best solution is here for now.

cc @karolz-ms

**Comment by karolz-ms** [comment]
@davidfowl adding stickyness based on (IP address + port) hashing should not be very difficult, as long as we can say that all guarantees are off if the set of backends (server replicas) is stable.

**Comment by davidfowl** [comment]
I was thinking the same. I was also wondering if it should be opt in via some switch on the resource.

**Comment by DamianEdwards** [comment]
Opt-in would be best I think.

**Comment by karolz-ms** [comment]
Yep, opt-in. It would be a spec property on the Service object.

**Comment by dbreshears** [comment]
Corresponding item in DCP is post GA so moving to backlog

**Comment by efonsecab** [comment]
I'm also getting this error in some deployed applications, I'm not using WithReplicas though.
It stops happenning if I Enable Session Affinity in the Container App, however, the flag resets every time I do a subsequent deployment.
Is there anyway to configure the Session Affinity through the AppHost?
![image](https://github.com/dotnet/aspire/assets/3481899/77329598-55b0-400e-90f8-f8a13b6bd18b)

![image](https://github.com/dotnet/aspire/assets/3481899/1ca76891-cb1a-462e-8095-046864351a3d)

**Comment by karolz-ms** [comment]
@mitchdenny @ellismg is there a way to configure ACA ingress sticky sessions flag via Aspire app model?

**Comment by mitchdenny** [comment]
We don't have this yet. We won't get it until we can customize the container apps in Aspire.

You could use infra synth though.

**Comment by v-bennettyue** [comment]
This issue not repro on Dev17.10 with Aspire 8.0.0,so close this issue
