### ISSUE TITLE
npmrc file missing for test project

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspire#1670]
The Secure Supply Chain Analysis build step is warning of a missing npmrc file:

```
##[warning]tests/testproject/nodeapp/package.json - CFS0001: Missing sibling .npmrc file. (https://aka.ms/cfs/npm)
```

Related to https://github.com/dotnet/aspire/issues/1419

Let's get these SCCA warnings cleaned up for Preview 1. These show up in [VMR](https://github.com/dotnet/dotnet) builds, causing warnings which makes it difficult to identify when another new warnings pop up.

**Comment by eerhardt** [comment]
cc @davidfowl - who added the test.

(To anyone who knows) Is there a normal/default npmrc registry we can use? The internal documentation says to make a file that looks like:

```
registry=https://pkgs.dev.azure.com/[YOUR-ORGANIZATION]/[YOUR-PROJECT]/_packaging/[YOUR-PROJECT]_PublicPackages/npm/registry/

always-auth=true
```

But what should we put for `[YOUR-ORGANIZATION]/[YOUR-PROJECT]`? I don't think we need or want to make a brand new registry just for this test app.
