### ISSUE TITLE
Aspire templates not available in Visual Studio

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspire#1673]
After having the intro to .Net Aspire bookmarked for 2 months, I finally decided it was time to start learning more.

I didn't get very far.

I added the Aspire SDK to VS 17.9.0 P2.1 using the Visual Studio installer.  I then updated the workflows with the workload update commands.

I then went to a VS session and tried to create an Aspire project. There are no Aspire templates available in Visual Studio.

```
C:\Users\ms>dotnet workload list

Installed Workload Id      Manifest Version                     Installation Source
-----------------------------------------------------------------------------------
wasm-tools                 8.0.1/8.0.100                        SDK 8.0.100
aspire                     8.0.0-preview.2.23619.3/8.0.100      VS 17.9.34414.90

Use `dotnet workload search` to find additional workloads to install.
```

**Comment by DamianEdwards** [comment]
Can you please run `dotnet workload install aspire` from the command line and see if that resolves the problem?

**Comment by MarkStega** [comment]
@DamianEdwards -- That didn't help but a system reboot did...
