### ISSUE TITLE
Make it easier to tell client and server spans apart in tracing

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1675]
The server span (the parent span) is rendered with just the path segment after the name, whereas the client spans are rendered with "HTTP GET 200". It's very easy for folks to assume that the "HTTP GET 200" might be referring to incoming requests (i.e. server spans) rather than outgoing requests.

Make the distinction clearer between client and server.

A possible idea is to replace the color bar with an incoming arrow icon (colored using the color of the bar) next to server and producer spans:

![image](https://github.com/dotnet/aspire/assets/303201/48c72770-abf3-4057-a863-ae1d9b3d70a7)

This wouldn't be limited to HTTP. It would apply to all server and producer spans.

Indentation of child spans might need to increase to handle the larger UI here.

**Comment by timheuer** [comment]
a11y note: don't only rely on color...make sure the aria information informs what it is intending to portray.

**Comment by timheuer** [comment]
Cool. I was also referring to the new arrow elements that describe the relationship of the request also.
