### ISSUE TITLE
Mounted volume information isn't respected when generating deployment templates

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/aspire#1676]
I'm building an app with a Postgres database which I need to ensure some extensions are installed into Postgres for the app to work.

This is a pretty easy solved problem locally, you just add `.WithVolumeMount("./database", "/docker-entrypoint-initdb.d", VolumeMountType.Bind)` to the resource builder for Postgres (copied from [this sample](https://github.com/dotnet/aspire-samples/blob/ef6868b0999c6eea3d42a10f2b20433c5ea93720/samples/DatabaseContainers/DatabaseContainers.AppHost/Program.cs)).

But when I scaffold out the infrastructure with `azd infra synth` (because I wanted to check it before deployment) I noticed that there was no analogy to the `WithVolumeMount` that would run my SQL script for me.

I don't think that mounting a volume is the right solution when deploying to Azure (given the transient nature of storage), I was thinking that it might generate something that uses the [`deploymentScripts`](https://learn.microsoft.com/azure/azure-resource-manager/bicep/deployment-script-bicep?tabs=CLI) feature of Bicep.

**Comment by davidfowl** [comment]
It's unlikely that we'll ship anything for deploying volumes in aspire v1. @mitchdenny [has done some thinking here](https://github.com/dotnet/aspire/pull/1521), but it's not baked enough to make it.

**Comment by davidfowl** [comment]
Bringing this back into preview 5 and assigning to @DamianEdwards. We want to scope this to container resources and a representation in the manifest that is viable that is enough information to make work in deployment environments like ACA and Kuberenetes.

Not sure how much we will need to scope, but we just need an initial investigation.

Related to https://github.com/dotnet/aspire/pull/1521

**Comment by aaronpowell** [comment]
I wonder if there's a way Aspire can try to determine what the objective of the volume mount is to then make that objective available to the metadata and then the IaC generator can generate the appropriate output.

If we use the example [in the DatabaseContainers sample](https://github.com/dotnet/aspire-samples/blob/main/samples/DatabaseContainers/DatabaseContainers.AppHost/Program.cs) the reason for introducing a volume mount is to run a SQL script on startup of the container (to, say, pre-provision the db).

Expanding this objective out to an Azure context, we'd be wanting a PostgreSQL db and we can then use a [`deploymentScript` resource](https://learn.microsoft.com/azure/azure-resource-manager/bicep/deployment-script-bicep?tabs=CLI) to run the script against the Azure PostgreSQL service that's been deployed.

**Comment by davidfowl** [comment]
The goal is to represent the existing information in the model since what we have today is lossy. Then we need to figure out if reflecting what we have in the manifest is enough for the container scenario. Mapping deployment scripts that run against the cloud database is magical and out of scope. 

However, it would OK if that were an explicit API on top of the existing model being built in preview4 and beyond:


```C#
var pg = builder.AddPostgres("pg")
                          .WithVolumeMount(...)
                          .PublishAsAzurePostgresFlexibleServer(azurePg => 
                          {
                                 azurePg.RunDeploymentScript(.....);
                          })
                          .AddDatabase("db");
```

**Comment by DamianEdwards** [comment]
Closing this done via #2742 as the scope was constrained to writing out the volume details to the manifest.
