### ISSUE TITLE
Ensure dashboard is accessible

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#168]
Need to make sure that all aspects of dashboard pass a11y requirements.  Likely Fluent UI lib handles a lot of this but let's make sure we don't wait until last minute

- [x] Run web a11y checker for report
- [x] Use `aria-*` labels on non-standard controls or where we use images as buttons, etc. (make sure nav menu is appropriate, etc.)
- [ ] Any real-time updates announcing changes, etc.
- [x] Use title/labels on actions

**Comment by adamint** [comment]
we are good on everything except #3 - [add live regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions)
