### ISSUE TITLE
The "samples" folder does not contain samples from a user-perspective

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1682]
Our samples folder contains what appear to be apps for .NET Aspire users to reference, where in fact they're intended more as integration tests for developers of this repo.

They're not great examples for users to reference, as we do things in these projects that we don't expect users to do. For example, in #1667 we have the app host projects reference the dashboard project directly.

We should rename the `samples` folder, or move its children somewhere else to avoid this confusion. 

Actual user samples are located in https://github.com/dotnet/aspire-samples

**Comment by drewnoakes** [comment]
Moving `dapr`, `eShopLite` and `orleans` under `tests` (alongside the existing `testproject` app) would help avoid this confusion.

![image](https://github.com/dotnet/aspire/assets/350947/18b846d5-936a-497f-9ded-211454a90bb3)

**Comment by drewnoakes** [comment]
`testproject` is used from `Aspire.Hosting.Tests`, so does feel a bit different from the current `samples`.

Also the `samples` folder has a `Directory.Build.props` file that sets...

```xml
  <!-- Enable Azure ActivitySources so Azure Components participate in tracing. -->
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="Azure.Experimental.EnableActivitySource"
                                    Value="true" />
  </ItemGroup>
```

...which likely doesn't apply to `tests`.

Any ideas @DamianEdwards @davidfowl @mitchdenny? I've heard this come up twice in discussions and #1667 will push these further from being useful references for users.

**Comment by pjmagee** [comment]
When I noticed this, I then realised I had to pull down the specific nuget feeds that allowed me to kind of, make use of those samples externally. e.g the Orleans stuff. I certainly agree - Maybe it should be renamed to integrations? or clearly state to only refer to the external samples repository.
