### ISSUE TITLE
Force dashboard resource startup within orchestrator ahead of other aspire resources

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#1688]
After the dashboard split (#1003), ensure the dashboard is run as an executable resource ahead of the other DCP resources to ensure telemetry to ensure readiness to receive OTEL data.

**Comment by davidfowl** [comment]
This is yours @mitchdenny

**Comment by mitchdenny** [comment]
For end users we've got this working now in the feature/dashboard-oop branch. For inner loop I just found a bug that I'll fix before we merge it in.
