### ISSUE TITLE
@joeloff please correct me if this statement is not accurate.

### ISSUE THREAD

**Issue by prateek121212** [dotnet/aspire#1690]
@joeloff please correct me if this statement is not accurate.

_Originally posted by @joperezr in https://github.com/dotnet/aspire/pull/1259#discussion_r1418169534_

**Comment by danmoseley** [comment]
@joeloff can we close this. ..

**Comment by joperezr** [comment]
I did confirm with him offline, and it is expected that we need to run as admin if you are in the 8.0.100 SDK. 8.0.200 SDK and onwards shouldn't hit this. Closing for now as resolved, but @prateek121212 feel free to reopen if you have any follow up questions, we are happy to help.
