### ISSUE TITLE
Aspire component in VS installer needs better description

### ISSUE THREAD

**Issue by dbreshears** [dotnet/aspire#1699]
Moved this from internal VS work item since this string comes from the workload itself...

the suggestion is "Need a better description instead of just the title reproduced.   would probably suffice: ".NET SDK Workload including templates for building Aspire applications"

![image](https://github.com/dotnet/aspire/assets/3432571/143ef344-2cbf-449f-852f-429adf66b8b8)

**Comment by timheuer** [comment]
Recommend (consistent with others): ".NET SDK workload for building Aspire cloud-native web applications"

https://github.com/dotnet/aspire/blob/6fe5242f1ccc8352809519643d1e4402b0cd538b/eng/workloads/workloads.csproj#L57

**Comment by danmoseley** [comment]
@joperezr closing as complete. LMK if I misunderstand.

**Comment by v-sherryfan** [comment]
Fixed in the final 8.0 GA VS insertion PR
