### ISSUE TITLE
DistributedApplicationModel.Name isn't used

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1709]
It's never set or used.

https://github.com/dotnet/aspire/blob/7a840b500deea4b1eea2f9a8a1ee01c5bbf27bdc/src/Aspire.Hosting/ApplicationModel/DistributedApplicationModel.cs#L20-L23

**Comment by mitchdenny** [comment]
I think we can probably remove it. That said the dashboard does display a name which it derives automatically I think. Given this is probably only going to ever be cosmetic I'd be in favor of removing unless we have a strong need for it.
