### ISSUE TITLE
UI issues with Dashboard on Safari

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#1724]
1. `Copy` icon on line for `Log entry details` fails with `Could not copy to clipboard`

![Screenshot 2024-01-19 at 15 04 56 (2)](https://github.com/dotnet/aspire/assets/1472/1b38a8da-8d67-4453-bd0d-bc23d3db744d)

2. The copy icon does always appear when hovering over the line. If I try to move the mouse over the lines then it appears only some times.

This works fine in Chrome/Mac.

This is on `Sonoma 14.2.1` with Safari `17.2.1`.

**Comment by leslierichardson95** [comment]
TODO: We need someone with a mac to help repro here
