### ISSUE TITLE
Customize icon based on server type 

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#1725]
Please refer to suggestion here : 
![image](https://github.com/dotnet/aspire/assets/102772054/0acaac64-1af6-403d-82d5-2bca53036692)

https://github.com/dotnet/aspire/pull/1684#issuecomment-1899357018

**Comment by adamint** [comment]
Since we have this icon now, will this be a long-lived issue?

**Comment by kvenkatrajan** [comment]
Yes thats correct :) This one is tracking any future icon updates (DB etc.)

**Comment by JamesNK** [comment]
Peer icon is customized. Can still customize server icon.

**Comment by mitchdenny** [comment]
Moving this to preview 4 since it is going to be a long lived issue?

**Comment by JamesNK** [comment]
I don't think we have any sitiations right now in our sample projects where the server/consumer is not HTTP. I will change when the .NET rabbitmq library supports OTEL. Just merged but not yet available: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1261

Look at this again when a package is available: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1261

**Comment by davidfowl** [comment]
@JamesNK You can run eShop, the rabbitmq event bus is instrumented.

**Comment by davidfowl** [comment]
>Do you want me to create an issue for someone to improve it, or leave it as-is and remove when new rabbitmq with built in OTEL support is used?

Yes to both things.

**Comment by JamesNK** [comment]
https://github.com/dotnet/eShop/issues/168
