### ISSUE TITLE
[Proposal] `AzureStorageResource` should implement `IResourceWithConnectionString`

### ISSUE THREAD

**Issue by philliphoff** [dotnet/aspire#1727]
Currently, `AzureStorageResource` (through `AddAzureStorage()`) enables references to (and connection strings for) only to its individual storage components (i.e. blobs, queues, tables). Some libraries, however, require a connection string that contains all three component endpoints.

I propose `AzureStorageResource` implement `IResourceWithConnectionString` which then allows it to be directly referenced by other resources.  In that case, it returns a single connection string with the endpoints for all three components.

Current behavior:

```csharp
var storage = builder.AddAzureStorage("storage");

var blobs = storage.AddBlobs("blobs");

builder.AddProject<Projects.DaprServiceA>("servicea")
       .WithReference(blobs);  // Injects a blob-specific connection string called "blobs" into the configuration
```

Desired behavior:

```csharp
var storage = builder.AddAzureStorage("storage");

builder.AddProject<Projects.DaprServiceA>("servicea")
       .WithReference(storage);  // Injects a general connection string called "storage" into the configuration
```

**Comment by davidfowl** [comment]
> I propose AzureStorageResource implement IResourceWithConnectionString which then allows it to be directly referenced by other resources. In that case, it returns a single connection string with the endpoints for all three components.

Does the azure sdk support this?

**Comment by philliphoff** [comment]
@davidfowl See: https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount.parse?view=azure-dotnet

**Comment by eerhardt** [comment]
In the Blobs component we just pass the ConnectionString directly into the BlobServiceClient:

https://github.com/dotnet/aspire/blob/835daf90ab61092d83c13aa8538fe56a018b8c3d/src/Components/Aspire.Azure.Storage.Blobs/AspireBlobStorageExtensions.cs#L72-L80

**Comment by mitchdenny** [comment]
> @davidfowl See: https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount.parse?view=azure-dotnet
> 
> In my case, I'm using the connection string with the Durable Task framework, specifically its Azure Storage backend, which requires a single connection string with all component endpoints (as it uses blobs, queues, and tables).

Isn't this the legacy track 1 storage framework?

**Comment by ellismg** [comment]
> Isn't this the legacy track 1 storage framework?

Indeed it is - the track 2 .NET Frameworks are all in the `Azure.` namespace, not `Microsoft.Azure.`

**Comment by philliphoff** [comment]
I suppose, given that, I can see the argument for not supporting a combined connection string.  Unfortunately, updating Azure storage libraries isn't something under my control, so I'll have to use a workaround.

**Comment by philliphoff** [comment]
I've got a reasonable workaround, so yes.
