### ISSUE TITLE
Dashboard should use responsive layout for devices with smaller displays

### ISSUE THREAD

**Issue by dotnetian** [dotnet/aspire#1740]
.NET Aspire dashboard is not being displayed well on small resolutions, and as it's being planned to make Aspire dashboard shippable to production, I think making it mobile-friendly is very important, because many developers like me like to have the metrics in their pocket.

![image](https://github.com/dotnet/aspire/assets/70327745/16cdd29a-fcc6-4923-9db3-c8d4e78ed16d)

**Comment by adamint** [comment]
Closing as completed
