### ISSUE TITLE
Improve dashboard displaying telemetry from old projects

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#175]
The dropdown on the Semantic Logs page is driven by services reported in OTLP. Each .NET project maps to a service with a configured service name and service instance id.

That's done here:
https://github.com/dotnet/astra/blob/835e1634a8d36bee67755c611b149711b6d37482/samples/Conventions/Extensions.cs#L43-L50

It's possible to create duplicate resources by running the aspire project multiple times with Ctrl+F5:
![image](https://github.com/dotnet/astra/assets/303201/ededd55f-92d7-484a-b92a-7906eef6507f)

The service for the project has a different instance id so shows up as a different item in the dropdown.

For example, Ctrl+F5 launches the dashboard with its set of apps and they report telemetry to the dashboard which it saves. Then Ctrl+F5 is used again to launch apps again. They have new instance ids and data shows up with a duplicate name in the dropdown.

Possible fixes:
1. The instance id is generated in the hosting model and passed to the projects using an env var. Then only known projects are shown in the dropdown. Telemetry from other apps (perhaps they're out of date and running in the background) can't be viewed.
    * Pros: Pretty simple and foolproof. Only telemetry from projects the dashboard knows about is visible. Data from old projects isn't displayed.
    * Cons: Can't display telemetry from other sources, e.g. containers. Is that desirable? Might be able to use the same pattern to support containers/executables.
2. Another option is to merge telemetry from application instances together. That doesn't seem desirable to me, especially if they end up running side-by-side.
3. Some kind of hybrid model where known projects are displayed at the top of the dropdown with an icon and other unknown services are displayed below.
    * Unfortunately, fluent blazor doesn't support [optgroups](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) 😢 
    * Maybe display older telemetry as `MyFrontend (old dotnet/aspire-private-planning#1)`, `MyFrontend (old dotnet/aspire-private-planning#2)`
    * Need to consider memory usage. If old telemetry sticks around then it could use up a lot of memory over time.

**Comment by davidfowl** [comment]
What do you think we should do here @JamesNK ?

**Comment by JamesNK** [comment]
I think the original PR - https://github.com/dotnet/aspire/pull/402 - has merit:
* If the solution has resources, then only display telemetry for resources (the difference is resources are coming from service instead of DCP)
* If the solution doesn't have resources, then there is no filtering of telemetry.

**Comment by davidfowl** [comment]
I think we have a reasonable solution now then, now that it is possible to use the dashboard with and without a resource server. As long as the OTLP server accounts for that then yeah.

**Comment by JamesNK** [comment]
I'm confused. The problem used to be that multiple items showed up in telemetry if the dashboard hung around. See original screenshot.

Is that no longer a problem? If it isn't then there isn't a need to do anything.

**Comment by davidfowl** [comment]
I don't know if it is still a problem. I haven't seen it recently.

**Comment by JamesNK** [comment]
Ok! If everything is working, then I'll close. If it becomes a problem then we can revisit.

**Comment by davidfowl** [comment]
It might be a problem when the dashboard is hosted externally. It will be persistent in those cases
