### ISSUE TITLE
Scenario: Ability to run as a container locally and deploy a managed azure service

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1757]
e.g. Developing against a redis container and deploying an azure redis instance.

Related https://github.com/dotnet/aspire/issues/1680
Related https://github.com/dotnet/aspire/issues/1736
Related https://github.com/dotnet/aspire/issues/616

**Comment by bradygaster** [comment]
Can we start with this one today? cc @mitchdenny @davidfowl

**Comment by eerhardt** [comment]
I believe this is complete. @davidfowl @mitchdenny - is there anymore work needed here?

**Comment by davidfowl** [comment]
No, this is good. This is a scorecard issue though.

**Comment by eerhardt** [comment]
What milestone do scorecard issues get? This one doesn't have a milestone.

**Comment by davidfowl** [comment]
None?

**Comment by eerhardt** [comment]
@joperezr asked for all issues to have a milestone set.

**Comment by mitchdenny** [comment]
I'm glad I'm not the only one struggling with this ;)

**Comment by joperezr** [comment]
ohhh, good point, I'll adjust the board to filter out scorecard issues from the Needs Milestone view

**Comment by mitchdenny** [comment]
Closing this scenario down as this was a GA scenario. I don't think we are keeping these open forever are we?

**Comment by davidfowl** [comment]
No, we dont.
