### ISSUE TITLE
Support specifying the args for running a container

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#177]
I want to be able to use the redis image, but run the redis-cli  in that container e.g.:

```C#
builder.AddContainer("redis-cli", "redis")
    .WithArgs("redis-cli -h redis MONITOR");
```

@karolz-ms Does DCP support this?

**Comment by davidfowl** [comment]
Putting this in preview2 as it's blocking a few scenarios.

**Comment by MeikelLP** [comment]
@davidfowl Thanks for prioritizing this. I'm using Typesense which requires overriding the command thus I cannot use Aspire at the moment :(

**Comment by davidfowl** [comment]
Sure we’ll get it for the next preview.
