### ISSUE TITLE
Scenario: Add the ability to branch based on the publisher

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1770]
It should be possible to determine if a manifest is being published or if the code is going to execute regardless of the environment. This would let developers change the app model based on what "mode" the app mode is being executed in.

**Comment by mitchdenny** [comment]
@davidfowl the execution context stuff I did was a first pass at this. I think we should do it even if we weren't doing everything in that first pass of the parameters PR.

**Comment by davidfowl** [comment]
Agreed, can we scope this to a top level API on IDistributedApplicaitonBuilder and one in the DI container that you can grab and check. Also flowing it to the environment callback.
