### ISSUE TITLE
Add hierarchical tree view component to fluentui-blazor to replace our existing data grids

### ISSUE THREAD

**Issue by adamint** [dotnet/aspire#1782]
We need several things that the data grid component doesn't allow:
- row-wide focus
- an action to be performed on row focus (ie open a details panel)
- hierarchy (such as with replicas)

The tree view component is also not a good fit for `Resources`, as we still want data to be displayed in columns

**Comment by JamesNK** [comment]
We can probably simulate a tree view by building on top of DataGrid - there is an example of doing that [here](https://github.com/dotnet/aspire/pull/1323). We can do something similar on the resource grid.
