### ISSUE TITLE
Dashboard can take a long time to show anything when loaded on slow machine

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#1784]
On slower machines (e.g. 11th gen Intel laptop) when launching a reasonably sized Aspire app (e.g. eShop) the dashboard can be launched in the browser by VS but then appear blank for a long period of time before finally everything appears all at once. During this time it can seem like the dashboard is unresponsive or broken and on more than one occasion I've shut it down and re-launched thinking something was going wrong.

My guess is this is due to the dashboard using interactive server rendering with pre-rendering disabled, so any delay in the initial render over the circuit (or establishment of the circuit itself) will result in a completely blank page until the initial render is complete.

We should consider adjusting how the dashboard is rendered to allow for shell elements like the header, menu, and a loading screen to be displayed very quickly to improve this experience. The various pages could then use the [Skeleton component](https://www.fluentui-blazor.net/Skeleton) as the initial placeholder until data is ready.

**Comment by DamianEdwards** [comment]
FYI @JamesNK

**Comment by JamesNK** [comment]
Might be this: https://github.com/microsoft/fluentui-blazor/issues/1621

**Comment by joperezr** [comment]
per @DamianEdwards, this is now improved so closing.
