### ISSUE TITLE
Reduce hosting resource logging output

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1806]
Hosting writes a lot of large logs about resources at the info level. All info logs are written to the Aspire console:

![image](https://github.com/dotnet/aspire/assets/303201/e898cdae-987c-4e88-8c7a-810d19ce2002)

This is page 1 of 10+ of DCP resource logs. There is too much information here to be useful and it hides other logs amongst the noise.

Options:
1. Hosting reduces log level from info to debug for resources. The Aspire log level is based on the hosting log level.
2. Dashboard adds a log filter to DCP messages to be warning or above.

**Comment by mitchdenny** [comment]
If I recal correctly the default logging is less verbose. We turn the logging up inside the playground projects.

**Comment by JamesNK** [comment]
It looks like a normal project doesn't see any DCP logging.

My feedback is I find it actively harmful in playground projects 😄

**Comment by mitchdenny** [comment]
I would agree that we could turn it down a lot ;)

**Comment by mitchdenny** [comment]
Moving to P5. I think we are in a pretty good place for end developers in P4. But we might still want to do more for inner loop in our repo.

**Comment by davidfowl** [comment]
This was fixed in p4 by reducing the DCP noise in general.
