### ISSUE TITLE
Understand why aspire-dashboard not displayed in CosmosEndToEnd playground

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1812]
While testing #1774 I noticed that it's inconsistent when we display the `aspire-dashboard` resource in playground applications.

Orleans shows:

![image](https://github.com/dotnet/aspire/assets/350947/71491587-2edb-480c-a40f-88ed498eb2a2)

CosmosEndToEnd shows:

![image](https://github.com/dotnet/aspire/assets/350947/1222af81-fd2b-4289-afea-7aa8cff756f7)

Why is it not visible in CosmosEndToEnd? The configuration in each's `Program.cs` looks identical, and I can't see anything significant in the `.csproj` files.

**Comment by davidfowl** [comment]
cc @mitchdenny

**Comment by drewnoakes** [comment]
Thanks @mitchdenny for the fix. The difference was in the launch profiles, not the project files.
