### ISSUE TITLE
[WebToolsE2E][Aspire] With clean install of VS 17.10 P1 + Aspire 8.0 P3, Ctrl+F5 of Aspire app fails because application host is not installed

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#1822]
**REGRESSION INFO**: Works fine with Aspire 8.0.0-preview.2

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install latest VS 17.10 P1 build from [main-34524.14] (Web workload with 8.0 SDK and runtime, 6.0 runtime and 7.0 runtime checked)
3. CLI workload update and install aspire workload: [version 8.0.0-preview.3.24071.6]
4. Apply NuGet Feeds

**REPRO STEPS**
1. New Project > Web App > name it 'WebAppRp1' > check 'Enlist in Aspire' checkbox during project creation
2. Build
3. Ctrl+F5

**ACTUAL**
Hosting failed to start. DCP does not seem to be installed
System.IO.FileNotFoundException: The Aspire application host is not installed at "C:\Users\balach\.dcp\dcp.exe". The application cannot be run without it.

![image](https://github.com/dotnet/aspire/assets/8246794/0b94ffc1-dcf4-4361-89db-34a208ffa09a)

**Note**: I can also reproduce this using command line

![image](https://github.com/dotnet/aspire/assets/8246794/466b61ab-fee9-4170-b3d6-f794640c0a34)

**Comment by danegsta** [comment]
Can you run `dotnet workload list` and `dotnet --list-sdks` from the project folder and share the output? That error indicates that at least the orchestration package in the workload isn't loading.

**Comment by danegsta** [comment]
Targets were missing in the latest workloadmanifest package. Should be fixed by https://github.com/dotnet/aspire/pull/1827/
