### ISSUE TITLE
Missing API to distinguish between local run and deployment manifest generation in AppHost

### ISSUE THREAD

**Issue by VincentH-Net** [dotnet/aspire#1823]
Currently distinguishing between a local run and deployment manifest generation in `AppHost` requires checking for the command-line parameter `--publisher manifest`:

```csharp
if (args.Contains("--publisher")) // AZD UP passes in --publisher manifest
```

As discussed in #1669 in [this thread](https://github.com/dotnet/aspire/pull/1669#discussion_r1454667759) with  @davidfowl, @mitchdenny and @ReubenBond, there is a need for this and it would be better to add an API in the Aspire App Model for this purpose.

Note that `Environment` seems less suitable to expose this API on, because of a conceptual mismatch:
- Today `Environment` means _current runtime environment_
- However Aspire adds a concept of _target environment_, which can either be the same as the runtime environment for local running, or different for deployment manifest generation.

**Comment by mitchdenny** [comment]
We've got some API surface changes coming in preview 4 which will require this to be addressed.
