### ISSUE TITLE
"DependsOn"-like relationships between components

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#183]
We should expose a way to express dependencies between resources. This won't have any immediate impact on startup order but will come in handy for other things (diagrams and the manifest). 

### Original

Do we need to implement depends on like relationships between components. Right now, we've just added ```AddExecutable(...)``` to support things like running arbitrary executables as part of bringing up the dev host. But it has been pointed out that for things like migrations we might want to hold starting a project until the executable finishes running (kind of like an init container).

For other dependencies (between projects) we might want to express startup dependencies, but because they are long running we would probably need to introduce the concept of health probes.

**Comment by Alirexaa** [comment]
Is there any plan to add this?

I want to migrate the database when the application starts but because the database is not already up, the application start failed.

see [this](https://github.com/Alirexaa/AspirePostgisSample/blob/2139d2a73aeb99661cf2bb4abe3fc2fef37a377c/AspirePostgisSample.API/Program.cs#L22-L26). 

Here I just created a delay for a temporary fix.

A lot of scenarios need this feature to work.

**Comment by mitchdenny** [comment]
@Alirexaa we are working on this. In Aspire 8.1 we are adding a `WaitForResourceAsync(...)` extension for use in testing scenarios which is very similar to what we need here. We just need to figure out how we want this API to work outside of test scenarios.

It's in our list of day-0 issues that we want to fix :)

**Comment by kwaazaar** [comment]
@mitchdenny Can we expect it in a prerelease package any time soon?

If my DB is not up and running, the application does not crash (as it should), but a background process keeps failing in a loop. This is a third-party component I have no control over, so this WaitForResourceAsync seems exactly what I need..

**Comment by mitchdenny** [comment]
This didn't make the cut for 8.1 I'm afraid. It is still high on the priority list and will be considered for 8.2

**Comment by kwaazaar** [comment]
I'm using the sample code by @davidfowl for now, which worked like a breeze btw 🥇

**Comment by mitchdenny** [comment]
Closing this in favor of: https://github.com/dotnet/aspire/issues/5275
