### ISSUE TITLE
Increase target frameworks

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/aspire#1831]
## Is your feature request related to a problem? Please describe.
I am unable to consider moving steeltoe to use Microsoft service discovery due to the very limited target frameworks supported.

## Describe the solution you'd like
I would like to be able to use Microsoft service discovery library with projects older than net 8 in a similar manner to which configuration etc works.

## Describe alternatives you've considered
N/a

## Additional context
Is a Blocker for https://github.com/SteeltoeOSS/Steeltoe/issues/1254

**Comment by maddymontaquila** [comment]
@thompson-tomo Hey there! Is Steeltoe still using netstandard/net6 or are you on net8? If you've moved to net8, we can close this issue, right?

**Comment by thompson-tomo** [comment]
@maddymontaquila it appears that in the latest preview branches Steeltoe has moved to only dotnet 8. hence will close this issue.
