### ISSUE TITLE
Implement UI support for dashboard commands

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1839]
The resource service protocol allows the server to expose various commands that may be invoked by the client. For example, to stop or start a resource, or increase the number of replicas, etc. ACA may have their own ideas, and can expose a different set of commands if they want to.

We currently don't show these commands in the UI.

---

No resource server implementation uses commands yet. There's a chicken/egg thing here, where I think we need the UI support before anyone will use it.

**Comment by kvenkatrajan** [comment]
Dupe of : https://github.com/dotnet/aspire/issues/2278
Fixed by : #2572
