### ISSUE TITLE
Ability to disable dashboard from user's app host project

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1840]
https://github.com/dotnet/aspire/blob/3cd891a57338b0a5bafc39c4586c54fc94989afe/src/Aspire.Hosting/DistributedApplicationOptions.cs#L32-L35

We use `DistributedApplicationOptions.DisableDashboard` to turn off dashboard logic, but nothing seems to be setting this property.

`DistributedApplicationOptions` is public, but I can't see where we would expose it in a typical DAB construction. If that is possible, then we can close this issue, otherwise we should find and document a way to do this for those who don't want a dashboard.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/blob/3cd891a57338b0a5bafc39c4586c54fc94989afe/tests/testproject/TestProject.AppHost/TestProgram.cs#L10
