### ISSUE TITLE
How should container version/revision and replica/instance be modeled for the dashboard proto?

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspire#1857]
When hosting containers, there are 2 aspects we should consider in the model:

a) Scale out - my service is busy so there are N instances running - they should probably all have the same name, but a different field to represent the instance/replica info
b) Versioning - each change to a container in ACA will create a new revision, and depending on the model selected for the resource, it may be running old and new revisions at the same time, with a portion of the traffic between them.

These could be modeled using the ResourceProperty - but ideally the UI should know the meaning of these properties so it can group the instances togther, and provide operations that apply to all instances of the service, or to specific versions etc. Should these be top level properties on the Resource definition?

```proto
message ResourceProperty {
    // Name of the data item, e.g. "container.id", "executable.pid", "project.path", ...
    string name = 1;
    // TODO move display_name to reference data, sent once when the connection starts
    // Optional display name, may be localized
    optional string display_name = 2;
    // The data value. May be null, a number, a string, a boolean, a dictionary of values (Struct), or a list of values (ValueList).
    google.protobuf.Value value = 3;
}

// Models the full state of an resource (container, executable, project, etc) at a particular point in time.
message Resource {
    string name = 1;
    string resource_type = 2;
    string display_name = 3;
    string uid = 4;
    optional string state = 5;
    optional google.protobuf.Timestamp created_at = 6;
    repeated EnvironmentVariable environment = 7;
    optional int32 expected_endpoints_count = 8;
    repeated Endpoint endpoints = 9;
    repeated Service services = 10;
    repeated ResourceCommandRequest commands = 11;

    // Properties holding data not modeled directly on the message.
    //
    // For:
    // - Containers: image, container_id, ports
    // - Executables: process_id, executable_path, working_directory, arguments
    // - Projects: process_id, project_path
    repeated ResourceProperty properties = 12;
}
```

**Comment by drewnoakes** [comment]
Does this only apply to replicas?

How might you expect this data to be presented in the UI?

> provide operations that apply to all instances of the service

Can you give an example of this?

**Comment by samsp-msft** [comment]
I am going to want to see the list of instances grouped by the service - if there are 14 instances of a service, I want to be able to see them as a block
Stopping a service should probably be possible for all the instances as one. (Startup is a little different)
Health information (ready, shutting down etc) should be shown for the instances as a group
I can see us wanting to be able to do diagnostic commands on the group as a whole, (for pre-emptive operations such as turning on diagnostic modes) and individual instances - like collecting a dump.

**Comment by drewnoakes** [comment]
This feels like a bigger request than a change to the proto, but focussing on the proto for now: do you have any concerns that we wouldn't be able to add this to a future version of the proto?

**Comment by davidfowl** [comment]
I agree this is out of scope for v1.

**Comment by samsp-msft** [comment]
I'm thinking once we are hosted in environments like ACA, we'll need to have a way of representing these. It could all be done with the ResourceProperty, and having well known names for them, but I suspect we'll want to have trees at some point, so it should be modeled now.

In ACA you get a revision for each version of the app, or update of its configuration:
![revisions](https://github.com/dotnet/aspire/assets/54915162/74bcc7cb-8050-4471-b081-92cc29d45eb4)
Each is represented by its own "airline booking code", in this case `8waqf0c`

When scale out occurs, you get replica's - that will come and go as the scale up and down occurs.
![replicas](https://github.com/dotnet/aspire/assets/54915162/573b79e9-f298-4e2f-97b0-b3be5ae1006d)
In this case `6fb978cdf9-tkphf`

The Aspire dashboard shouldn't have commands to manage either of these, they are based on the operations of the underlying platform. Any commands should be links back to the Azure portal for management.

**Comment by davidfowl** [comment]
I don't think we need to. We just need to show the active one in the dashboard.

**Comment by drewnoakes** [comment]
The discussion in #4908 concluded that no protocol change was required here. With that PR merged, I'm not sure we need any additional work here.

I'm closing this. We can re-open it if there are objections.
