### ISSUE TITLE
End user experience improvements for using Application Insights with Aspire

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspire#1867]
Premises:
- Azure customers will want to be able to use Application Insights for monitoring their Aspire applications
  - During deployment they can pick either an existing Application Insights instance or create a new one
  - Deployment in these cases will be via the AZD Aspire integration
  - Other deployment tools can make the same determinations about resource requirements from the model
  - Application insights instances created by AZD will use the same log analytics workspace as the ACA instances it deploys
    - Customers can select a different log analytics workspace using a specific resource property

The code for invoking the export of data to Application Insights will be done by using (one of) the Azure Monitor SDKs as part of the shared project, sending the data to AI via their OTel exporter. For example:

``` c# 
using Azure.Monitor.OpenTelemetry.AspNetCore;
...

private static IHostApplicationBuilder AddOpenTelemetryExporters(this IHostApplicationBuilder builder)
{
...
       // Uncomment the following lines to enable the Azure Monitor exporter (requires the Azure.Monitor.OpenTelemetry.AspNetCore package)
        builder.Services.AddOpenTelemetry().UseAzureMonitor();
```

This assumes that there is an APPLICATIONINSIGHTS_CONNECTION_STRING environment variable set for the apps.

Unlike the other components, it doesn't seem to make sense to have an Aspire specific Application Insights / Azure Monitor component as that would just be a very thin veneer over the above.

The main change is in the metadata in the host project:

## Scenario 1 - provision an Application Insights resource for both dev and production usage.

``` c#
    var builder = DistributedApplication.CreateBuilder(args);
 
    var ai = builder.AddAzureApplicationInsights("ai").UseExisting(rid);
 
    var db = builder.AddAzureCosmosDB("cosmos")
                    .AddDatabase("db");
 
    builder.AddProject<Projects.CosmosEndToEnd_ApiService>("api")
           .WithReference(db);
 
    builder.Build().Run();
```

## Scenario 2 - Use a connection string during local dev and provision a new instance during deployment

``` c#
   var builder = DistributedApplication.CreateBuilder(args);
 
    var ai = builder.AddAzureApplicationInsights("ai");
 
    var db = builder.AddAzureCosmosDB("cosmos")
                    .AddDatabase("db");
 
    builder.AddProject<Projects.CosmosEndToEnd_ApiService>("api")
           .WithReference(db)
           .WithReference(ai);
 
    builder.Build().Run();
```

## Scenario 3 - No Application Insights during dev, but deploy in production:

``` c#
    var builder = DistributedApplication.CreateBuilder(args);
 
    var db = builder.AddAzureCosmosDB("cosmos")
                    .AddDatabase("db");
 
    var app = builder.AddProject<Projects.CosmosEndToEnd_ApiService>("api")
           .WithReference(db);
 
    if (builder.ExecutionContext.Operation == DistributedApplicationOperation.Publish)
    {
        app.WithReference(builder.AddAzureApplicationInsights("ai"));
    }
 
    builder.Build().Run();
```

## Scenario 4 - Use a connection string in prod and provision when in dev (UGLY)

``` c#
    var builder = DistributedApplication.CreateBuilder(args);
    builder.AddAzureProvisioning();
 
    var ai = builder.AddAzureApplicationInsights("ai").PublishAsConnectionString();
 
    var db = builder.AddAzureCosmosDB("cosmos")
                    .AddDatabase("db");
 
    builder.AddProject<Projects.CosmosEndToEnd_ApiService>("api")
           .WithReference(db)
           .WithReference(ai);
 
    builder.Build().Run();
```

## Scenario 5 - Enable customization of the Log Analytics Workspace (LAW)

``` c#

var ai = builder.AddApplicationInsights("ai")
                .WithLogWorkspace("azd-special-var-name", "lawfoo");
```

**Comment by samsp-msft** [comment]
@davidfowl

**Comment by davidfowl** [comment]
@BrennanConroy will work on this. @mitchdenny does this depend on the AddParameter work?

**Comment by mitchdenny** [comment]
Yes it will. Seems like that might be a good change to get in to main soon after we snap for P3.

**Comment by davidfowl** [comment]
Are we missing the scenario where app insights is provisioned by azd without parameters?

**Comment by ellismg** [comment]
> Are we missing the scenario where app insights is provisioned by azd without parameters?

We do have coverage on this in some of the eShop samples and it should be working in `azd` today (but you need to use a custom manifest writer to emit a `azure.appinsights.v0` resource in the manifest).

**Comment by davidfowl** [comment]
> The AddApplicationInsights will implicitly, under the covers create a parameter
var parameter = builder.AddParameter("APPLICATIONINSIGHTS_CONNECTION_STRING", secret: true); and flag it in the metadata as the connection string for Application Insights.

We need 2 resources:
1. azure.appinsights.v0 - Provision my AI resource and wire it up appropriately.
2. parameter.v0 - Specify the connection string to an existing resource.

**Comment by ellismg** [comment]
> parameter.v0 - Specify the connection string to an existing resource.

Yup - we'll start working this on the `azd` side so it's ready for use at the start of Preview 4 when @mitchdenny starts landing the work on the Aspire side.

**Comment by BrennanConroy** [comment]
I guess this is replacing https://github.com/dotnet/aspire/issues/778?

Reference for where we use appinsights today in eshopOnAzure: https://github.com/Azure-Samples/eShopOnAzure/blob/main/src/AzureServices/AppInsightsBuilderExtensions.cs

**Comment by samsp-msft** [comment]
> Are we missing the scenario where app insights is provisioned by azd without parameters?

I don't know whether this should be represented in the model or as a choice by AZD during initialization?

**Comment by davidfowl** [comment]
It needs to be in the app model which is how it gets into the manifest for azd to provision it.

**Comment by samsp-msft** [comment]
> It needs to be in the app model which is how it gets into the manifest for azd to provision it.

Not quite the answer to the question - regardless of whether AZD provisions a new instance, or the user selects an existing one - I think Application Insights still needs to be in the app model (and resulting manifest) so that the connection strings/secrets can be managed for each of the consuming projects. The question is whether the "create new" or "use existing" is answered in the app model or by AZD when it gets to the metadata saying that Application Insights is needed.

This is probably more similar to questions for a database connection than redis which will almost always want a new one.

**Comment by davidfowl** [comment]
Yes and we know how this is going to work, outlined by https://github.com/dotnet/aspire/issues/1867#issuecomment-1911564523.

**Comment by davidfowl** [comment]
Also depends on https://github.com/dotnet/aspire/issues/1958

**Comment by samsp-msft** [comment]
Updated to account for RunAs and PublishAs variants.

**Comment by davidfowl** [comment]
@BrennanConroy @samsp-msft  once we update this issue with what we ended up doing? That will help us upgrade the documentation as well.

**Comment by davidfowl** [comment]
Seems like we still have some outstanding changes to make:
1. Make sure we attach provisioned app insights resources to the container apps log analytics workspace - https://github.com/dotnet/aspire/pull/2374 (also requires and azd change @vhvb1989)
2. And this one - https://github.com/dotnet/aspire/issues/2395

**Comment by samsp-msft** [comment]
Added updated code based on discussion last week.

**Comment by DamianEdwards** [comment]
@samsp-msft the code samples in the issue description seem to have some typos in them, can you verify they're up to date and reflective of the goals please?

**Comment by samsp-msft** [comment]
Cleaned up. I copied and pasted from notes that were not as clean as I thought they were.

**Comment by joperezr** [comment]
@samsp-msft  as agreed offline can you add a list in here of the things that were done in P4 and the ones left for P5?

**Comment by DamianEdwards** [comment]
@samsp-msft

In the first example, no resources appear to use the `"ai"` resource. Is that intentional?

In the second example, I'm not following how that code results in using an existing AppInsights resource during dev and provisions a new one on publish. Is it missing something, or am I?
