### ISSUE TITLE
duplicate service name when using OTLP logging

### ISSUE THREAD

**Issue by irpg7** [dotnet/aspire#1872]
Hello,

I decided to try aspire in my current project, however i was using the Serilog for logging. so for structured logs i needed to install OpenTelemetry sink for it otherwise i wasn't able to see structured logs. after implementing the write to OTLP, i have faced with this issue naming my service-thinking it will match my app name :) -  
![image](https://github.com/dotnet/aspire/assets/46024555/3c5a10f3-f013-4af5-9d2d-35cbbb1c63f6)
however its working for filtering in this case, but also discovered that if i put WithOtlpExporter() in the end of AddProject, filters not working as well.
![image](https://github.com/dotnet/aspire/assets/46024555/d5da1a74-7ff6-488d-89d7-aa362a48181c)
this is the filter working version. 

btw, it was super easy to add aspire to my existing 2+ yrs old project. i appreciate the team.

**Comment by davidfowl** [comment]
Can you share the project code? Are you writing duplicate logs because both the open telemetry logger provider and serilog are writing to the dashboard?

**Comment by irpg7** [comment]
Hello sir, i can't share the project code but i can share the lines i added to make it work. also i am not writing duplicate logs, all my app wrapped by Serilog. So here are the thing i've done.
Normally i expected it to write structured logs menu but instead i got this screen,
![image](https://github.com/dotnet/aspire/assets/46024555/e72fce34-fff5-420b-9a43-502534279f3a)
So i knew the problem is that i am using Serilog. (I reverted back to Microsoft Logger and i got the logs successfully before so i reverted back to serilog since i have multiple apps) the screen you see upside is what i initially got. so knowing the Open Telemetry can bring my logs, i installed the sink for it. Here is the configuration i am using 
![image](https://github.com/dotnet/aspire/assets/46024555/fa09e755-b4b9-4ba6-b962-866776100906)
so i successfully populated the list under the "Structured Logs" using this one. but it came as "unknown_service:webapi.exe" so i needed to rename it. and done the "service.name" thing. so, even if i click both of them it shows same structured logs. Tracing also working fine. i think if service names are same it should merge the logs ? shouldn't it ?

**Comment by davidfowl** [comment]
Can you make a new project based on the aspire template with the code you added so we can reproduce the issue?

**Comment by irpg7** [comment]
Sure i can do that. I will post here when i am done.

**Comment by irpg7** [comment]
hello again sir, 
https://github.com/irpg7/aspire-issue-repro 
here you can pull the project for repro. i had exact same result. you can check on API Service. i haven't done anything to frontend project.

**Comment by davidfowl** [comment]
> Could we use aspire for on premise distributed environments ?

https://github.com/dotnet/aspire/discussions/1819 should answer that.

**Comment by vanwx** [comment]
@irpg7 I got the same issue.
I had to forward Serilog to OpenTelemetry like you did.

I guess your code missed the `service.instance.id`

This below code work for me

```csharp
public static void ConfigureSerilogOpenTelemetrySink(this LoggerConfiguration serilog, IConfiguration configuration)
{
    var otlpEndpoint = configuration["OTEL_EXPORTER_OTLP_ENDPOINT"];
    if (!string.IsNullOrWhiteSpace(otlpEndpoint))
    {
        serilog.WriteTo.OpenTelemetry(otlp =>
        {
            otlp.Endpoint = otlpEndpoint;
            try
            {
                var otelResourceAttribute = configuration["OTEL_RESOURCE_ATTRIBUTES"];
                otlp.ResourceAttributes["service.name"] = configuration["OTEL_SERVICE_NAME"];
                otlp.ResourceAttributes["service.instance.id"] = otelResourceAttribute[(otelResourceAttribute.IndexOf("=") + 1)..];
            }
            catch (Exception e)
            {
                Console.WriteLine($"Failed to configure openTelemetry serilog sink: {e}");
            }
        });
    }
}
```
