### ISSUE TITLE
Regression: When process exits, the dashboard status still shows Running

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1878]
My API crashed on startup:

<img width="1200" alt="image" src="https://github.com/dotnet/aspire/assets/95136/e3e5a488-cde9-4a95-97d1-4bcb112b5387">

Status is running:

<img width="1200" alt="image" src="https://github.com/dotnet/aspire/assets/95136/ce568af5-51a4-46e8-b4d1-6e225d89a7dc">

cc @karolz-ms  see the spinning window, what does the proxy do when the backend crashes?

**Comment by karolz-ms** [comment]
If the process crashes at startup, it should not be reported as running, that is a bug somewhere.

As for the proxy, the design behavior is, once the process crashes, the status of the Project should be stopped, which means the endpoint for the service(s) that the Project implemented is no longer available, which means the Service is unhealthy. The Service itself is still accepting connections, but these connections will be "parked" (no response), waiting for a new endpoint to appear. This might result in the clients timing out on their request(s).

**Comment by karolz-ms** [comment]
This has been fixed and the fix is on its way to be included in Preview 3.
