### ISSUE TITLE
Scenario: Service discovery guidance and support for various scenarios

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1916]
- [ ] - https://github.com/dotnet/aspire/issues/1659
- [ ] - https://github.com/dotnet/aspire/issues/1536
- [ ] - https://github.com/dotnet/aspire/issues/1356
- [ ] - https://github.com/dotnet/aspire/discussions/1075

**Comment by prochnowc** [comment]
Maybe #1831 is also a candidate for this task ?

**Comment by danmoseley** [comment]
this issue doesn't seem to be adding much over listing some separate service disovery issues. @davidfowl can we close it now

**Comment by davidfowl** [comment]
Sure
