### ISSUE TITLE
SQL and CosmosDB don't resolve the resource name in trace view

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1919]
It's because the host and port are separated by a comma not a colon (not sure why...). We might need to implement a custom peer resolver for SQL. The address is 127.0.0.1 not localhost and the separator is `:` not `,`.

<img width="1200" alt="image" src="https://github.com/dotnet/aspire/assets/95136/1c7c49e3-92ab-4d9a-846d-e3d190edd286">

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by davidfowl** [comment]
Hmm cosmos isn't resolving either. I wonder if we broke peer service resolution when we changed the address from 127.0.0.1 to localhost...

<img width="1028" alt="image" src="https://github.com/dotnet/aspire/assets/95136/9824808e-858a-4ff3-a985-dc0c3b77de7f">

**Comment by davidfowl** [comment]
Maybe it's just these 2 dependencies. Mongo seems to work.

**Comment by JamesNK** [comment]
SQL Server uses a comma for port 🤷 Simple fix is to retry on failure with a comma instead of a colon.

Is cosmos a resource? An outgoing peer is only resolved if it is a resource and has an endpoint that matches the client span address.

**Comment by davidfowl** [comment]
Yea they are both resources. Trying with a comma doesn’t work as the address is 127.0.0.1 vs localhost. Just needs some massaging I guess
