### ISSUE TITLE
Add support for mongo express

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1920]
We have support for redis commander and pgadmin, we should add support for mongo express.

https://hub.docker.com/_/mongo-express/

**Comment by mitchdenny** [comment]
@timheuer did you want to take a stab at this? Note that there was an issue with mongo express where it wasn't possible to access it without logging it. But I note that the container image was recently updated so maybe that bug was fixed.

**Comment by timheuer** [comment]
Yeah, likely same pattern as others I would imagine.

**Comment by JamesNK** [comment]
@timheuer Does your PR address this issue? Can it be closed?
