### ISSUE TITLE
Can no longer click on resource error

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1926]
https://github.com/dotnet/aspire/pull/1886 removed the link to get to the error logs if there are errors. Now there is no way to get to the errors at all from the dashboard. A user now sees the red badge against a resource on the dashboard and has no idea what it is or how to action it. Every time I've seen a badge like that in a UI there is always a way to click on it.
 
https://m3.material.io/components/badges/guidelines

**Comment by davidfowl** [comment]
Fixed in https://github.com/dotnet/aspire/pull/1957
