### ISSUE TITLE
Don't copy the output of dependent projects into the AppHost's output

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1927]
Follow up to https://github.com/dotnet/aspire/pull/1726. When you build the apphost project, normal reference output still ends up being copied to the output folder. We should avoid that copy if it's `IsAspireResourceProject` is true.

**Comment by davidfowl** [comment]
cc @eerhardt

**Comment by mitchdenny** [comment]
@joperezr can you help with this?

**Comment by mitchdenny** [comment]
@eerhardt can you take a look as well given your recent changes in this area.

**Comment by davidfowl** [comment]
@baronfel is there something we can set on a project reference to do this?

**Comment by baronfel** [comment]
Yeah, there's a metadata you set on ProjectReferences to control this behavior. From the docs here: https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#projectreference

> ReferenceOutputAssembly	
> Optional boolean. 
> if set to false, does not include the output of the referenced project as a Reference of this project, but still ensures that the other project builds before this one. Defaults to true.

**Comment by baronfel** [comment]
oh, try `Private=true` as well, then.

**Comment by davidfowl** [comment]
Giving you this one @BrennanConroy
