### ISSUE TITLE
[WebToolsE2E][Aspire] After installing .NET 9 SDK + Aspire 9.0 workload, the 'Enlist in .NET Aspire orchestration' checkbox disappears when creating a new 9.0 web app

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#1935]
**REGRESSION INFO:** Worked in 17.10 P1 Without installing .NET 9.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU 
2. Install VS 17.10 P1 from [[main-34524.221]
3. Install .NET SDK 9.0 Preview 1
4. CLI workload update and install aspire 9.0.0-alpha.1.24074.8
5. Apply NuGet dotnet9 Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web App (Razor Pages) > select .NET 9.0 and the 'Enlist in .NET Aspire orchestration' checkbox will disappear

**Note**

- After installing .NET 9 SDK, it works fine when creating .net8.0 web apps.

**ACTUAL**

The 'Enlist in .NET Aspire orchestration' checkbox disappears after selecting .NET 9.0
   
![image](https://github.com/dotnet/aspire/assets/71361488/40bd27bb-a129-47b6-a407-035981262f28)

**EXPECTED**

There is a 'Enlist in .NET Aspire orchestration' checkbox after selecting .NET 9.0
 
![image](https://github.com/dotnet/aspire/assets/71361488/4cbd10db-8cfb-4eb4-ad0f-80b01f223190)

**Comment by davidfowl** [comment]
cc @phenning

**Comment by v-elenafeng** [comment]
No repro with the latest released builds.
