### ISSUE TITLE
[WebToolsE2E][Aspire] Add a web project to .NET Aspire App Host project, the dropdowns of 'Structured logs', 'Traces' and 'Metrics' on the dashboard don't contain the web project.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#1942]
**REGRESSION INFO**: New project templates o Aspire 8.0 preview 3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 1.0 [34528.15.main]
3. Install SDK 8.0.200
4. Install Aspire Preview 3 latest build 8.0.0-preview.3.24078.5
5. Apply NuGet Feeds
6. Install Docker Desktop

**REPRO STEPS**

1. Open VS, create a new project > .NET Aspire App Host > .NET 8.0 > Create.
2. Right-click the solution > Add > New Project > ASP.NET Core Web App(Razor Page) > .NET 8.0 > 'Enlist in .NET Aspire orchestration' was checked by default > Create.
3. Ctrl + F5
4. On the dashboard, open 'Structured logs' board, and click dropdown.

**Notes**:

1.'Traces' and 'Metrics' board also repro this issue.
2. 'Console logs' contains the web project

**ACTUAL**
The dropdown doesn't contain web project.
'Structured logs':
![image](https://github.com/dotnet/aspire/assets/82028229/03161b18-8037-4ad8-ada2-52d93843c7de)
'Traces':
![image](https://github.com/dotnet/aspire/assets/82028229/47ea0b16-8f7f-48b4-ab88-e0b1ebf34323)
'Metrics':
![image](https://github.com/dotnet/aspire/assets/82028229/30671f14-7a0e-4e38-b105-c7707e8624ba)

**EXPECTED**
Like 'Console logs':
![image](https://github.com/dotnet/aspire/assets/82028229/748075d8-776c-4741-bef0-2675427ad82f)

**Comment by davidfowl** [comment]
This is by design. That telemetry will only show up if the service defaults are wired up. When you use a standalone apphost project, they are not wired up, so no telemetry will show up.
