### ISSUE TITLE
Redundant AddBuiltInMeters methods?

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspire#1945]
Looking at the playground and templates, the [`AddBuiltInMeters()`](https://github.com/search?q=repo%3Adotnet%2Faspire%20AddBuiltInMeters&type=code) method _seems_ to be redundant in the face of just using [`AddAspNetCoreInstrumentation()`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/0b9cf42e9af668fe6d3af86254f9758c7c821f5e/src/OpenTelemetry.Instrumentation.AspNetCore/AspNetCoreInstrumentationMeterProviderBuilderExtensions.cs#L22) and [`AddHttpClientInstrumentation()`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/0b9cf42e9af668fe6d3af86254f9758c7c821f5e/src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentationMeterProviderBuilderExtensions.cs#L25) for metrics.

Unless these were specifically used because they're a subset of what is added by these extensions, it seems like it would be good to swap them out so that anything generated/copied from the playground/templates would get anything added in future to the OpenTelemetry NuGet packages automatically through upgrading.

**Comment by davidfowl** [comment]
Ah great catch! This was before these changes were made. We might be able to revert our changes now and just use the latest version of these packages.

I'm assigning @samsp-msft, but @martincostello if you would like to send a PR that would be great. @samsp-msft can be the reviewer. Let me know!

**Comment by martincostello** [comment]
Sure, it _seems_ like a simple change. I'll push something up shortly and if it all goes horribly wrong I'll defer to @samsp-msft 😄.
