### ISSUE TITLE
[WebToolsE2E] With Aspire 8.0 P3 installed, if we then install .NET SDK 9.0 P1, we cannot create Aspire app using Aspire 8.0 P3 templates anymore

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#1951]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install .NET SDK 8.0.200
    - Install using pipeline builds
    - Apply feed for 8.0.200
3. Install Aspire 8.0 P3
    - Install using ps1 from https://github.com/dotnet/aspire/blob/main/eng/installLatestFromReleaseBranch.ps1
    - Apply feed 'dotnet-tools-feed'

![image](https://github.com/dotnet/aspire/assets/8246794/0c3f7945-c259-4018-ba44-c8102469e9a3)

![image](https://github.com/dotnet/aspire/assets/8246794/545c5426-4cbd-451e-9683-77ce5e20cad8)
 
**REPRO STEPS**
1. Using CLI, create new 8.0 P3 Aspire app  'AspireStarterApp2', and build and run
    - Open Command prompt
    - dotnet new aspire-starter -o AspireStarterApp1

2. Install .NET SDK 9.0 Preview 1
    - Install using daily 9.0 P1 builds
    - Apply feed for 9.0 P1

![image](https://github.com/dotnet/aspire/assets/8246794/440ebf4f-764f-4caf-b1b9-e35c92905059)

3. Using CLI, create new 8.0 P3 Aspire app 'AspireStarterApp3'

**ACTUAL**
Unable to create Aspire Starter Application. The aspire workload is not installed
![image](https://github.com/dotnet/aspire/assets/8246794/2faa97ef-fd3b-4a9e-b5ff-13bdf0949e81)

![image](https://github.com/dotnet/aspire/assets/8246794/a39bdd5d-79e2-43b4-a37c-3ffbacbf0702)

**Workaround**
- Use global.json to pin the SDK version to the 8.0.2xx version (eg: 8.0.200) that you have installed 
```
{
  "sdk": {
    "version": "8.0.200"
  }
}
```
- Eg: With both SDK 8.0.200 and SDK 9.0.0 preview.1 installed, if you add the above global.json to your solution folder `Solution01`, you can see that the SDK in use is now 8.0.200 and project creation will work successfully.
- ![image](https://github.com/dotnet/aspire/assets/8246794/e01faa02-91dc-487d-95f8-b047fc957210)

**EXPECTED**
Aspire workload should be installed and we can create Aspire Starter Application

**Comment by dsplaisted** [comment]
This looks like the same thing as https://github.com/dotnet/aspire/issues/2172

**Comment by balachir** [comment]
I've [updated](https://github.com/dotnet/aspire/issues/1951#issue-2105883589) the Repro Steps with the recommended workaround.

**Comment by DamianEdwards** [comment]
@joperezr over a month since this was last updated. Is there any action for us on this one?

**Comment by joperezr** [comment]
No real action from us. There are two workarounds that can be used now:

- If you already have a solution/project, then add a global.json which forces the use of the 8.x SDK. This will make it so that the template locator will also use the 8.x version, and find the 8.0 templates.
- If you don't have a solution/project and starting from scratch, you can use the suggestion from @phenning [here](https://github.com/dotnet/aspire/issues/2186#issuecomment-1967502080), which essentially suggests to set env variable `VS_TEMPLATELOCATOR_SDKVERSION` to the 8.0 SDK you have in order to show the right templates.

**Comment by DamianEdwards** [comment]
What's the proper fix though? What's the plan to enable creating Aspire 8.0 projects once .NET 9 SDK is installed, especially in VS?

**Comment by phenning** [comment]
This is actionable. The proper fix is to fix the aspire manifests like described on other threads like the Maui workloads does. The global.json and env var workarounds are not customer friendly and should not be the proposed solution. After this is done, VS will display both net 8 and net 9 versions of the templates.

**Comment by DamianEdwards** [comment]
Thanks @phenning. @joperezr are you the right assignee for this then? We should get this fixed as part of 9.0 preview.4 I guess?

**Comment by joperezr** [comment]
I see, thanks for the clarification @phenning. Yes, the work to allow targeting .NET 8 with 9.0 workloads is planned for 9.0 Preview 4.

**Comment by radical** [comment]
This issue is linked from https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio%2Cunix . It should be updated with the plan for `work to allow targeting .NET 8 with 9.0 workloads`. cc @joperezr

**Comment by davidfowl** [comment]
No longer relevant.
