### ISSUE TITLE
PublishAs pattern

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#1960]
### Azure resources

- [x] - Azure Redis
- [x] - Azure SQL
- [x] - Azure Postgres SQL (Flexiable Server)
- [ ] - MySQL (https://github.com/dotnet/aspire/issues/2130)
- [ ] - MongoDB (https://github.com/dotnet/aspire/issues/2348)

### Other
- [x] - PublishAsConnectionString (https://github.com/dotnet/aspire/pull/2052) (https://github.com/dotnet/aspire/pull/2373)
- [x] - PublishAsContainer

Code sample:

```csharp
// Scenario: Use an Azure resource for inner loop
var builder = DA.CreateBuilder(args);
var pg = builder.AddPostgres("mypostgres")
                .PublishAsPostgresFlexibleServer();
                // What does this do?
                // conditional on operation mode = Publish
                    // Adds a ConnectionStringCallbackAnnotation that knows how to get provisioned secret from secrets.json
                    // Removes container annotations.
                    // Adds metadata to the resource
```

**Comment by mitchdenny** [comment]
See some initial exploration on `Azure.Provisioning` integration here: #2252

**Comment by davidfowl** [comment]
@mitchdenny I added mongo and MySQL as resources to add in preview5. We should close this issue and track those 2 issues.

**Comment by mitchdenny** [comment]
Yeah. I think mongo is a higher priority. But MySQL does unlock some CMS scenarios.
