### ISSUE TITLE
End to end integration tests for Dashboard URL output.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#1961]
We need a series of end to end integration tests which make sure we don't regress logic around emitting `Now listening on` text to make sure we don't accidentally break `dotnet watch` scenarios that depend on that text.

**Comment by davidfowl** [comment]
@eerhardt @radical  do we have a good way to test this with the new testing infrastructure?

**Comment by davidfowl** [comment]
Ping @radical

**Comment by radical** [comment]
We have the infrastructure to test this now. cc @adamint and @JamesNK who have been adding dashboard tests.

**Comment by davidfowl** [comment]
The test here would be verifying apphost logs output

**Comment by radical** [comment]
There is an existing test which happens to test the string - https://github.com/radical/aspire/blob/f3569ce824ca777c460a028116800086328229e7/tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs#L373-L453

.. but a dedicated test for this would be good.

**Comment by davidfowl** [comment]
Hmm, this might be good enough.
