### ISSUE TITLE
Dashboard should gracefully handle the resource server going offline

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1980]
Today the gRPC calls retry for few seconds and then this error happens:

<img width="1200" alt="image" src="https://github.com/dotnet/aspire/assets/95136/9e41b5b2-affc-4e74-85e0-fc6b12f1a60a">

We should fail more gracefully, tell the user the resource server is unavailable and avoid unhandled exceptions.

**Comment by davidfowl** [comment]
@JamesNK This is fixed right?

**Comment by kvenkatrajan** [comment]
@drewnoakes  please confirm if this is fixed. If not please move over to preview 6

**Comment by davidfowl** [comment]
This is fixed. We retry.
