### ISSUE TITLE
Dashboard - Metrics - Persist the selected view (chart vs table) in state 

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#1989]
On review : https://github.com/dotnet/aspire/pull/1755, @JamesNK  had a recommendation to make the selected view (chart vs table) a query string parameter to allow it to be a persisted setting in state.

https://github.com/dotnet/aspire/pull/1755#issuecomment-1915708202

**Comment by adamint** [comment]
closed via #1755
