### ISSUE TITLE
Add support for incoming Cosmos client change for ignoring certificate on connection string

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#2006]
The Cosmos team is making a change to the Cosmos client to make emulator usage easier by ignoring the emulator certificate. Once this is done we can remove some workarounds we added to the Aspire Cosmos components. Tracking in P3 but we won't hold P3 for it if it doesn't make it.

**Comment by mitchdenny** [comment]
@JamesNK assigning this to you as part of the broader database epic. Ping me if you need extra background. Basically we would be removing the `IgnoreEmulatorCertificate` property on the aspire components and relying on what is on the connection string. It also means that the connection string we generate for the emulator would need to include this so it works end to end.

**Comment by JamesNK** [comment]
Too many open questions for this to be in P3. Moving to P4. cc @mitchdenny @davidfowl

**Comment by mitchdenny** [comment]
I think this is the right decision.
