### ISSUE TITLE
Don't hang for a minute waiting for the dashboard to respond if it failed to start

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2017]
See https://github.com/dotnet/aspire/issues/2007#issuecomment-1918974894. Today we ping the dashboard for a minute, but if the executable fails to start all together, we can fail faster.

**Comment by mitchdenny** [comment]
Punting to P5 - may bring it back if feature work is done.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/aspire/issues/2422
