### ISSUE TITLE
Dashboard gives healthy status on failing startup

### ISSUE THREAD

**Issue by BartNetJS** [dotnet/aspire#2032]
Startup code failed but dashboard gives a healthy status

To Reproduce
`
...
Environment.Exit(-1); //exit early to simulate a startup issue

app.run();
`

Expected behavior
An error or even better fatal level

![image](https://github.com/dotnet/aspire/assets/4865355/4237b736-2a43-415b-84a8-b120c3985af7)

**Comment by davidfowl** [comment]
This will work in the next preview. There might have been a bug in preview 2.

**Comment by davidfowl** [comment]
cc @karolz-ms

**Comment by karolz-ms** [comment]
Duplicate of https://github.com/dotnet/aspire/issues/1878
