### ISSUE TITLE
Document and host the JSON schema for the Aspire manifest

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#2040]
Now that the manifest types that we support in the core of Aspire are being bedded down we need to document the JSON schema and get it hosted somewhere, and get the manifest writer to write it out into the manifests that we produce. The schema will need to be versioned so that when we make breaking changes to existing resources the tools processing them can warn/fail.

**Comment by danmoseley** [comment]
Will this schema ship in the product or be hosted/separate, ie., is it on the codeflow schedule

**Comment by danmoseley** [comment]
Looks like several pieces tracked here -- hosting, documentation (do you mean traditional docs? or comments in the schema..), and putting it in manifests.

Would it make sense to replace this with individual issues @mitchdenny ? Some of that can have a GA milestone but anything that's product changes would not.

**Comment by mitchdenny** [comment]
Schema is down and published. We should consider linking to it from the manifests but it works for now on any file named **aspire-manifest.json**
