### ISSUE TITLE
Cloud role names missing with App Insights when running from Azure Container Apps

### ISSUE THREAD

**Issue by christiannagel** [dotnet/aspire#2047]
Using App Insights, running an application locally on the dev system, the cloud role name (cloud_RoleName column) is set to the application name. 
Running the application with Azure Container Apps, the cloud role name is set to **unknown_service:dotnet**.

With the image, *gameapis* and *bot* results from local runs, the same services running in Azure Container Apps show *unknown_service:dotnet*.

Do I miss a configuration? Should this work with the default settings? 

![appinsights-cloudrolename](https://github.com/dotnet/aspire/assets/1908285/bb60194e-1ef7-4ffb-868b-c87ac0d4ea95)

**Comment by davidfowl** [comment]
@samsp-msft is looking into this. The azure telemetry package doesn't pick up environment variables from ACA as yet.

**Comment by samsp-msft** [comment]
Change is in the contrib package. https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1565

Just waiting on the release process to produce a package for this and have it be picked up by the Azure.Monitor.AspNetCore package as a dependency

**Comment by davidfowl** [comment]
@samsp-msft Is it updated yet?

**Comment by samsp-msft** [comment]
> @samsp-msft Is it updated yet?

Yes. https://github.com/Azure/azure-sdk-for-net/blob/Azure.Monitor.OpenTelemetry.AspNetCore_1.2.0-beta.1/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/CHANGELOG.md#120-beta1-2024-02-09

**Comment by davidfowl** [comment]
@samsp-msft Can you follow up here https://github.com/dotnet/aspire/discussions/3006
