### ISSUE TITLE
P4 dotnet watch not work

### ISSUE THREAD

**Issue by rozbo** [dotnet/aspire#2050]
after upgrade to `8.0.0-preview.4.24081.10`
```
dotnet watch run MyProject.AppHost 
```

only changes in MyProject.AppHost  will trigger hot reload, but no project resource can hot reload.
Not only that, this version also lacks many methods， like `Dictionary.GetOrAdd`, `this.JoinAsString`, `args.FindIndex`....

this may cause by workload, just downgrade "Aspire.Hosting" to p3 not works too

**Comment by rozbo** [comment]
```
dotnet workload list 
```
```
aspire           8.0.0-preview.4.24081.10/8.0.100      SDK 8.0.100
```

**Comment by rozbo** [comment]
by the way , anyone know how can I downgrade the aspire workload ?

**Comment by davidfowl** [comment]
Preview 4 is being actively developed so bugs are expected. Though I’m not exactly sure what is broken you should expect instability if you install daily builds. Preview3 is feature complete, and we’re pretty much done with it.

I you could detail more repro steps that would be great. We can take a look.

As for downgrading your workload @joperezr can help

**Comment by rozbo** [comment]
Yeh, I expected there might be a lot of bugs haha

In p3,I use
```
dotnet watch run MyProject.AppHost 
# MyProject.AppHost  boot many resources such as HttpApi project, db/redis/rabbitmq container 
```
it basically works very well, except that the database container is started but not listening yet, which will cause the project can't connect to db/redis/rabbitmq etc, but fortunately, I only need to change any code, the program will restart, and then everything will be perfect.
I didn't change anything, except that I updated the workload to the latest version by
```
dotnet workload update --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --skip-sign-check
```
and then update the project reference

```
<PackageReference Include="Aspire.Hosting" Version="8.0.0-preview.4.24081.10" />
```

use the same command `dotnet watch run MyProject.AppHost`, now MyHttpApi project can't hot reload anymore, just MyProject.AppHost  hot reload works.


aspire is awesome, thanks!

**Comment by rozbo** [comment]
by `eng/installLatestFromReleaseBranch.ps1` downgrade aspire workload to `8.0.0-preview.3.24081.13`, now hot reload works again.

even  I use newest Aspire.Host

hope this can be useful

**Comment by joperezr** [comment]
I was about to reply but saw you already found how to downgrade. Running those scripts will automatically put you on the latest build produced from our release branches, so today, it means it would put you on our latest ship candidate for preview 3

**Comment by mitchdenny** [comment]
Has anyone been able to repro this in main?

**Comment by joperezr** [comment]
After chatting with @phil-allen-msft, moving this to preview 5. @tmat will likely pick this up.

**Comment by davidfowl** [comment]
Is watch more broken? We have an issue tracking this already

**Comment by joperezr** [comment]
I'm not sure if this is a dupe, I was only taking a look at issues in the P4 milestone. If this is a dupe, feel free to close.

**Comment by davidfowl** [comment]
@rozbo we're going to verify that dotnet watch works as part of the preview 4 release.

cc @balachir

**Comment by balachir** [comment]
I've asked our validation team to try dotnet watch scenarios using P4.

**Comment by v-reinawang** [comment]
I tried dotnet watch and hot reload following the steps below:

1. Create a .NET Aspire Starter Application project, name it 'AspireStarterApp1'
2. Right-click the apphost project > open in a integrated terminal > dotnet watch, **the project can be run successfully**
3. On the dashboard, click the endpoint of webfrontend
4. In the AspireStarterApp1.Web project, open Components/Pages/Home.razor, change 'Hello, world!' to 'Hello, world123!' , Ctrl + S to save file, no changes in the browser page
5. Refresh browser and the changes will appear

**Comment by davidfowl** [comment]
I'm guessing this was an issue with an early daily build of preview4. Closing this.
