### ISSUE TITLE
Add phpMyAdmin option for MySql 

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#2051]
Similar to how RedisCommander and pgAdmin are available as options for those resources, consider adding phpMyAdmin for the MySql resource type.

Enabling:
```
var mysql = builder.AddMySqlContainer("mysql")
    .WithPhpMyAdmin();
```

**Comment by davidfowl** [comment]
Dupe of https://github.com/dotnet/aspire/issues/1936
