### ISSUE TITLE
Review README for Cosmos DB components.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#2062]
@samsp-msft wasn't able to pull enough from the READMEs for the Cosmos DB app model/component packages to write the P3 blog post. For P4 we should review the READMEs for these just to make sure they are giving developers what they need.

**Comment by davidfowl** [comment]
Yep

**Comment by eerhardt** [comment]
The CosmosDB READMEs follow the same pattern as the other components and hosting resources. Closing since the other READMEs have been deemed acceptable.
