### ISSUE TITLE
Add method to enable the RabbitMQ management plugin

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#2067]
Comment says that tag is `3-management` but we are just using `3`: https://github.com/dotnet/aspire/blob/73b9e0bede781852e6a980284b22b0003ec1591e/src/Aspire.Hosting/RabbitMQ/RabbitMQBuilderExtensions.cs#L16

Should we be using `3-management`? (note: Visual Studio connected services uses `rabbitmq:3-management-alpine` for local dev)

**Comment by davidfowl** [comment]
This changed in preview3. We forgot to update the comment https://github.com/dotnet/aspire/pull/1985

cc @mitchdenny

**Comment by timheuer** [comment]
Cool, it looks like it uses the right binding now for connection string even with an additional management endpoint:

```
"messaging": {
  "type": "container.v0",
  "image": "rabbitmq:3-management",
  "env": {
    "RABBITMQ_DEFAULT_USER": "guest",
    "RABBITMQ_DEFAULT_PASS": "{messaging.inputs.password}"
  },
  "bindings": {
    "tcp": {
      "scheme": "tcp",
      "protocol": "tcp",
      "transport": "tcp",
      "containerPort": 5672
    },
    "management": {
      "scheme": "http",
      "protocol": "tcp",
      "transport": "http",
      "containerPort": 15672
    }
  },
  "connectionString": "amqp://guest:{messaging.inputs.password}@{messaging.bindings.tcp.host}:{messaging.bindings.tcp.port}",
  ```
Would we want to add that back in? or have an option to enable the management image (as I could see not wanting to turn on the admin interface in non-dev).  I didn't see some RabbitMQ stats in the traces view (eShopLite), which is why I went looking

**Comment by davidfowl** [comment]
No, we want to use a separate container (if possible).

**Comment by timheuer** [comment]
Cool, just took a look at the `rabbitmqadmin` tools docs...it might not be 'simple' versus just exposing an option to use the management container.  The default experience is that the admin tool (a CLI plugin basically) connects to the instance where rabbitmq is running.  Else much more auth config looks needed to be done (rather than simple user/pass).  And there doesn't look like a rabbit-owned super slim image as well.

**Comment by mitchdenny** [comment]
The reason we had to change it was that it was causing a problem with AZD deployment. But we always planned to get off that management image anyway.

**Comment by timheuer** [comment]
According to docs, `rabbitmqadmin` communicates with the HTTP management UI and not directly with the AMQP port. So even a separate management container still needs the `rabbitmqadmin` plugin to me on the main instance…to me kinda defeating the purpose of using two containers versus and option that would switch to use the management image and ensure that the endpoint doesn’t get into manifest

**Comment by mitchdenny** [comment]
Do you happen to know whether you can have a single rabbitmqadmin instances talking to multiple rabbitmq nodes, that is kind of what we are going for. If we can't make that work then we could potentially look at differentiating the way we configure the container based on whether we are in publish mode or run mode.

**Comment by timheuer** [comment]
Based on what I'm reading, "yes" :-) -- but it still requires the management plugin to be installed on the nodes (https://www.rabbitmq.com/management.html#usage-ui-clusters) which isn't in the non-management containers by default.  In my reading the Management UI communicates via HTTP API which is available via the management plugin.

>differentiating the way we configure the container based on whether we are in publish mode or run mode

This feels like the better approach to me.

**Comment by mitchdenny** [comment]
Moving to P5 but may come back in based on where we get to with the slab of feature work we've scheduled.

**Comment by attilah** [comment]
The current code at: 

https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/RabbitMQ/RabbitMQServerResource.cs#L29

blows up AppHost startup if someone uses the `management` image and registers the RabbitMQ dashboard with a  name other than "management". This is not mentioned anywhere in the docs I think.

registration code:
```
    .WithAnnotation(new ContainerImageAnnotation { Image = "rabbitmq", Tag = "3-management" })
    .WithAnnotation(new EndpointAnnotation(ProtocolType.Tcp, uriScheme: "http", name: "ui", port: 15672, containerPort: 15672))
```

Error:
```
^Cfail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
         at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 148
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+MoveNext() in /_/src/Aspire.Hosting/Dcp/KubernetesService.cs:line 148
         at Aspire.Hosting.Dcp.KubernetesService.WatchAsync[T](String namespaceParameter, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Aspire.Hosting.Dcp.ApplicationExecutor.CreateServicesAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 344
         at Aspire.Hosting.Dcp.ApplicationExecutor.CreateServicesAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 344
         at Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 104
         at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 65
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

Instead of using `Single()`, with some checks added could help the developer to figure out what is wrong.

**Comment by davidfowl** [comment]
@attilah https://github.com/dotnet/aspire/issues/844

**Comment by davidfowl** [comment]
So, to the original issue it seems like the change here will be to use the "rabbitmq:3-management-alpine" in run mode, but rabbitmq:3 in publish mode?

**Comment by DamianEdwards** [comment]
@sebastienros are you still planning on doing this one? If not, I might be able to grab it from you.

**Comment by sebastienros** [comment]
Currently finishing the unstable packages removal so feel free. I have other issues for preview 5 before it's too latae.

**Comment by davidfowl** [comment]
We could make the method to opt into the RabbitMQ management much like we do with the other management tools. This method would check the mode and change the image and tag and add the endpoint only in publish mode. 

```C#
builder.AddRabbitMQ("rabbit").WithManagementUI();
```

**Comment by timheuer** [comment]
Like this? 

```csharp
    public static IResourceBuilder<RabbitMQServerResource> WithManagementUI(this IResourceBuilder<RabbitMQServerResource> builder)
    {
        if (!builder.ApplicationBuilder.ExecutionContext.IsPublishMode)
        {
            var containerAnnotation = builder.Resource.Annotations.FirstOrDefault(a => a is ContainerImageAnnotation) as ContainerImageAnnotation;
            containerAnnotation!.Tag = $"{containerAnnotation.Tag}-management";
            builder.WithHttpEndpoint(containerPort: 15672, name: "management");
        }
        return builder;
    }
```

**Comment by DamianEdwards** [comment]
I wouldn't assume the existing tag is correct, it could already have been changed. So it would just call `WithImage` and pass the full image name. I'm going to make this change now.

**Comment by DamianEdwards** [comment]
I think we should just go back to the original (simple) idea, i.e. use the management tag if in run mode, otherwise use the regular tag. Having a separate `WithManagementUI()` method adds a bunch of complexity if folks start customizing the image and/or tag before they call the `WithManagementUI()` method.

**Comment by davidfowl** [comment]
Hmm, that changes the security posture a bit. All of our other dashboards are opt in...

**Comment by DamianEdwards** [comment]
We can make it a bool parameter?

**Comment by mitchdenny** [comment]
All of the effort right now is on finalizing .NET Aspire 8.0 for GA. Once we are past .NET Aspire 8.0 you can expect .NET Aspire 9.0 to start getting more focus.
