### ISSUE TITLE
Use Polly.Core resilience strategies

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspire#2077]
The RabbitMQ component still uses the Polly "v7" APIs, rather than the [new performance optimised](https://www.thepollyproject.org/2023/09/28/polly-v8-officially-released/) v8 APIs.

https://github.com/dotnet/aspire/blob/1b9465617392ea5cdf3575178c590b7da66e3270/src/Components/Aspire.RabbitMQ.Client/AspireRabbitMQExtensions.cs#L154-L156

This component, as well as the playground and tests ([code search](https://github.com/search?q=repo%3Adotnet%2Faspire%20polly&type=code)), should be updated to the more efficient Polly.Core APIs. Details can be found in the [migration guide](https://www.pollydocs.org/migration-v8.html).

Alternatively, the [new .NET 8 resilience packages](https://learn.microsoft.com/en-gb/dotnet/core/resilience/?tabs=dotnet-cli) could be used.

**Comment by bgrainger** [comment]
I opened a PR to migrate to Polly V8 following the [migration guide](https://www.pollydocs.org/migration-v8.html#retry-results-in-v8): https://github.com/dotnet/aspire/pull/2400.

I didn't see the need to bring in Microsoft.Extensions.Resilience at this time.
