### ISSUE TITLE
Add `AddTable` method for setup database tables.

### ISSUE THREAD

**Issue by wu-yafeng** [dotnet/aspire#2098]
Here is a sample:

``` csharp
// Sample.AppHost/Program.cs

public record MySqlTableDescriptor(string Name, string Description,IEnumerable<MySqlColumnDescriptor> Columns);
public record MySqlColumnDescriptor(string Name, string Description, string DataType, bool IsPrimaryKey, bool IsNullable);


var builder = DistributedApplication.CreateBuilder(args);

var catalogDbName = "catalog"; 
var catalogDb = builder.AddMySqlContainer("mysql")
    .AddDatabase(catalogDbName);

catalogDb.AddTable(catalogDbName, new MySqlTableDescriptor(....)).AddSeedData(....);
catalogDb.AddTable(catalogDbName, new MySqlTableDescriptor(....)).AddSeedData(....);

builder.AddProject<Projects.MySql_ApiService>("apiservice")
    .WithReference(catalogDb);

builder.Build().Run();

```

**Comment by davidfowl** [comment]
This is a little too application specific to go into the application model. We won't be adding this but feel free to build it and make it a nuget package.

**Comment by wu-yafeng** [comment]
It's easier to deploy database with given state. such as a game server project. 

We have a tables like 

``` csharp

public class HeroBase
{
    public int Id { get; set; }
    public string Name { get; set; }

    public double BaseAttack { get; set; }

    public double BaseHealth { get; set; }
}

public class PlayerHero
{
    public HeroBase Base { get; set; }

    public int PlayerId { get; set; }

    public int Level { get; set; }
}
```

`HeroBase` is value object but referenced by player hero.etc

It's much easier to manage `HeroBase` with `AddTable(...)` than `Migrations script`. Declarative definitions like Aspire also help reduce the technical debt of maintaining imperative code, such as deployment scripts, that can accrue over time.

**Comment by davidfowl** [comment]
> Aspire also help reduce the technical debt of maintaining imperative code, such as deployment scripts, that can accrue over time.

This is an entire framework in itself. Aspire has no plans to build a migration seeing framework for arbitrary databases. We'd much rather make existing tools easier to orchestrate in this scenario.
