### ISSUE TITLE
Add ability to express exposed services in app host

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2099]
See https://github.com/Azure/azure-dev/issues/3284

cc @mitchdenny

**Comment by mitchdenny** [comment]
When we looked at this last time we were debating whether we needed some kind of top level IsExternal flag on the resource or whether we should do it on the endpoint. 

Whether this works is highly dependent on what the target compute platform supports which might have been why we pushed this down to the deployment tool.

**Comment by timheuer** [comment]
I kinda like this...something like:
```
builder.AddProject<Projects.MyFrontend>("frontend", IngressType.External)
       .WithReference(basketService)
       .WithReference(catalogService.GetEndpoint("http"));
```

**Comment by davidfowl** [comment]
Moving to preview 5. We want to model this on endpoints, not on projects. Then we can decide if we want syntax sugar for marking all endpoints on a project as external.

**Comment by mitchdenny** [comment]
Now that we have the endpoint callback we could do this:

```csharp
app.WithEndpoint("foo", (endpoint) => {
  endpoint.IsExternal = true;
});
```

We would need to figure out how to defer execution of it though because some endpoints are injected via lifecycle hook (specifically for projects).

**Comment by davidfowl** [comment]
Giving this to @BrennanConroy since he's familiar with this area now.

**Comment by timheuer** [comment]
Do we think this is the way we will go for sure and not need the `azd` flow again...asking because I wanted to track running a 're-scan' on `azd` when the appmodel changes to prompt for what changes in exposed services would be needed.

**Comment by davidfowl** [comment]
Yes, this is the way we will go.

**Comment by DamianEdwards** [comment]
For making it easy to mark a project's endpoints as external with minimal ceremony (on top of the primitive of external endpoints), something like an extension method on `IResourceBuilder<ProjectResource>` like `IsExternal()` or `WithExternalEndpoints()`, e.g.:

```csharp
builder.AddProject<Projects.AspireApp32_Web>("webfrontend")
    .WithReference(cache)
    .WithReference(apiService)
    .WithExternalEndpoints();
```

@timheuer RE your suggestion of a top-level enum `IngressType`, I don't think we should "burn" the term "ingress" here, given the AppHost itself has no concept of ingress today.

@mitchdenny I think your suggestion makes sense for the cases where endpoints are added via the `WithEndpoint` method.

**Comment by mitchdenny** [comment]
@BrennanConroy I thought we might need to get a solution for this in for P4 quickly but it looks like we are going with another mitigation, but here is a PR with a partial solution to this:

#2448

**Comment by DamianEdwards** [comment]
Should this one be assigned to you too @davidfowl?
