### ISSUE TITLE
Unable to change ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2101]
Changing this environment variable doesn't seem to have any effect on the application. It seems like something is setting DOTNET_ENVIRONMENT to development no matter what.

Tested this in preview 3:

```C#
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject("web", "..\\WebApplication20\\WebApplication20.csproj");

builder.Build().Run();
```
Launch settings:

```JSON
{
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5139",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      }
    },
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "https://localhost:7231;http://localhost:5139",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      }
    }
  }
}
```

**Comment by davidfowl** [comment]
@karolz-ms @mitchdenny

**Comment by karolz-ms** [comment]
> Changing this environment variable doesn't seem to have any effect on the application. It seems like something is setting DOTNET_ENVIRONMENT to development no matter what.

@davidfowl  so just to clarify: is the problem with ASPNETCORE_ENVIRONMENT or DOTNET_ENVIRONMENT?

**Comment by davidfowl** [comment]
Setting ASPNETCORE_ENVIRONMENT  is ineffective because something in the stack (I didn't check) is setting `DOTNET_ENVIRONMENT`.

**Comment by mitchdenny** [comment]
Still happens with CTRL-F5 so I would suggest it is DCP?

**Comment by mitchdenny** [comment]
OK ... so it appears if you set `DOTNET_ENVIRONMENT` it works as expected.

**Comment by mitchdenny** [comment]
@davidfowl the `launchSettings.json` that you showed just confirming that is from your service project?

**Comment by karolz-ms** [comment]
> Still happens with CTRL-F5 so I would suggest it is DCP? Which doesn't make sense at all.

Even if you do CTRL-F5, the Visual Studio is still responsible for launching projects.
Does this repro when you run the app via `dotnet run`?

**Comment by dbreshears** [comment]
Looks like this is coming from the launch settings of the AppHost Project and are set when DCP is launched through DCPHostService.  

DOTNET_ENVIRONMENT is set to "Development" in the launch settings of the default template for AppHost project.   Is there a reason this needs to be set in the AppHost project in the template?   Workaround would be to set it explicitely in the service project (or AppHost) to "Production" or remove from the AppHost launchSettings after project creation. 

The could be ignored potentially in DCPHostService when creating DCP process, not sure if that would be desirable.

**Comment by davidfowl** [comment]
Sounds like a bug in the template.

**Comment by DamianEdwards** [comment]
It's set in the AppHost template I believe cos that's the variable the DistributedApplicationBuilder honors. There was a bug logged a while back to stop that variable flowing to project processes I thought. If DAB works with the aspnet variable we could change the template to use that, but I wouldn't expect it to.

**Comment by davidfowl** [comment]
It shouldn’t flow to the projects we launch then. We should exclude it from the flow.

**Comment by dbreshears** [comment]
> There was a bug logged a while back to stop that variable flowing to project processes I thought

It looks like the code sets a few variables to empty but only when there is no Launch Profile. 

> It shouldn’t flow to the projects we launch then. We should exclude it from the flow.

We lose the ability to have a global profile to define these though.
