### ISSUE TITLE
Reuse code between table and graph views for metrics 

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#2104]
The [suggestion ](https://github.com/dotnet/aspire/pull/1755#issuecomment-1929535000)spun from a code review to have one source of truth for a metrics value at each point in time can then be used by both views.
The views work slightly different for the user scenarios - plot re-generates the data model every update; in contrast, the table updates the existing model on presence of new data. The table view was designed this way on purpose for the screen readers to be able to identify the delta in the changes to be read instead of re-reading the entire data model. 
We need to determine what pieces of code can be reused between the 2 views.

**Comment by leslierichardson95** [comment]
Need more investigation here to determine the cost of this work.

**Comment by kvenkatrajan** [comment]
@adamint  I think this can be closed. please confirm
