### ISSUE TITLE
Build 24107 (daily) : azd init and up fails for resource types rabbitmq.server.0 and azure.openai.account.v0

### ISSUE THREAD

**Issue by pedershk** [dotnet/aspire#2122]
After adding these resource types, I'm unable to do azd up, they fail with the message

ERROR: unsupported resource type: rabbitmq.server.v0
and
ERROR: unsupported resource type: azure.openai.account.v0

After deleting .azure and azure.yaml and attempting azd init again, they now fail during init instead and have to be removed from the AppHost in order for init to work. The .azure directory is still created - but no azure.yaml.

In AppHost Program.cs, they are constructed like this:

```
var rabbitMq = builder.AddRabbitMQ("rabbitmq");

var plannerOpenAi = builder
    .AddAzureOpenAI("openai-planner");

var docGenOpenAi1 = builder
    .AddAzureOpenAI("openai-docgen1");

var docGenOpenAi2 = builder
    .AddAzureOpenAI("openai-docgen2");
```

Example usage on a Background Worker project further down:

```
var workerDocumentGeneration = builder
    .AddProject<Projects.ProjectName_V2_Worker_DocumentGeneration>("worker-documentgeneration")
    .WithReference(documentGenerationStorage)
    .WithReference(serviceBus)
    .WithReference(apiMain)
    .WithReference(plannerOpenAi)
    .WithReference(docGenOpenAi1)
    .WithReference(docGenOpenAi2)
    .WithReference(rabbitMq);
```

I've also attempted .ExcludeFromManifest() which results in a different error

```
ERROR: failed registering service hooks, failed getting services: importing services: generating app host manifest: generating app host manifest: dotnet run --publisher manifest on project 'C:\dev\personal\aspire\src.v2\ProjectName.V2.AppHost\ProjectName.V2.AppHost.csproj' failed: exit code: 1, stdout: Building...
C:\dev\personal\aspire\src.v2\ProjectName.V2.AppHost\Program.cs(62,20): error CS0103: The name 'plannerOpenAi' does not exist in the current context [C:\dev\personal\aspire\src.v2\ProjectName.V2.AppHost\ProjectName.V2.AppHost.csproj]
C:\dev\personal\aspire\src.v2\ProjectName.V2.AppHost\Program.cs(63,20): error CS0103: The name 'docGenOpenAi1' does not exist in the current context [C:\dev\personal\aspire\src.v2\ProjectName.V2.AppHost\ProjectName.V2.AppHost.csproj]
C:\dev\personal\aspire\src.v2\ProjectName.V2.AppHost\Program.cs(64,20): error CS0103: The name 'docGenOpenAi2' does not exist in the current context [C:\dev\personal\aspire\src.v2\ProjectName.V2.AppHost\ProjectName.V2.AppHost.csproj]
, stderr:
The build failed. Fix the build errors and run again.
```

**Comment by davidfowl** [comment]
Aspire preview3 (the next version) supports deploying rabbitmq (as a container). You'll need to call `AddRabbitMQContainer`.

**Comment by pedershk** [comment]
> Aspire preview3 (the next version) supports deploying rabbitmq (as a container). You'll need to call `AddRabbitMQContainer`.

Thanks, David.

Is this is a replacement for `AddRabbitMQ`? (since that also runs in a container).

Unfortunately I can't find `AddRabbitMQContainer` - and I'm on daily builds (24107).

Also - about `AddAzureOpenAI` - as mentioned in the initial report, that also generates an error when deployment/init is attempted.

**Comment by davidfowl** [comment]
Oh if you're on daily builds then you have to keep up with the commits! The latest change is `AddRabbitMq(...).PublishAsContainer()`

**Comment by davidfowl** [comment]
This changed again 😄. You no longer need `PublishAsContainer`. This is the default.

**Comment by pedershk** [comment]
> This changed again 😄. You no longer need `PublishAsContainer`. This is the default.

Yeah.. I decided to stick with Preview 3 for now - too many deadlines on internal project coming along to go with daily builds for now. But I'm following everything that's happening surrounding deployment with great interest :)

**Comment by pedershk** [comment]
[heart]         Henning Kilset reacted to your message:
________________________________

**Comment by davidfowl** [comment]
Closing this one out for p4
