### ISSUE TITLE
Allow specifying the username for RabbitMQ when using the component

### ISSUE THREAD

**Issue by wtulloch** [dotnet/aspire#2133]
The current RabbitMQ component allows for providing a password but `guest`  is hardcoded   as the username. It would be good to also be able to specify the username so that it matches what is defined elsewhere for example a Dapr pubsub yaml configuration

**Comment by davidfowl** [comment]
@wtulloch Do you want to send a pull request for this?

**Comment by wtulloch** [comment]
@davidfowl Happy to take a shot at it.

**Comment by nickna** [comment]
This appears to be fixed in Eric's commit on 3/20/2024: [Make username and password defaults consistent (#3023)](https://github.com/dotnet/aspire/commit/717e03a19dea1bcc7cd8f8659730188b1da6f6e5)

RabbitMQServerResource.cs
 ```
$"amqp://{UserNameReference}:{PasswordParameter}@{PrimaryEndpoint.Property(EndpointProperty.Host)}:{PrimaryEndpoint.Property(EndpointProperty.Port)}");

```

**Comment by davidfowl** [comment]
Great, we can close this.
