### ISSUE TITLE
Container ports sometimes get wrong

### ISSUE THREAD

**Issue by paule96** [dotnet/aspire#2137]
Hi Aspire team,

I guess I found a problem. I currently try to use gremlin server for my project. So I added it to my aspire host and was writing code for it. But my code was always telling me that there is no server answering. The Problem here is that the port Aspire finds out is different what is really assigned by docker desktop. Like you see in this screenshot:

![Shows aspire and docker desktop on the same site, where aspire shows the port `57267` and docker desktop shows the port `57285`](https://github.com/dotnet/aspire/assets/11291885/63c3a0a5-3d26-4a25-bc7a-fcecb737e4c6)

I tryed this behavior with the 'stable' preview 2 and the daily builds of preview 4.

I have also create the following code to make it easy to replicate the error. At the comment in the code you should set a breakpoint, then you can see the problem too.

```csharp
var builder = DistributedApplication.CreateBuilder(args);
var graph = builder.AddContainer("graph", "tinkerpop/gremlin-server")
    .WithHttpEndpoint(8182);

var apiService = builder.AddProject<Projects.someapi>("someapi")
    .WithEnvironment("ConnectionStrings__graph", () =>
    {
        graph.Resource.TryGetEnvironmentVariables(out var env);
        if (env == null)
        {
            return string.Empty;
        }
        graph.Resource.TryGetAllocatedEndPoints(out var endpoints);
        var address = endpoints?.First().Address;
        var port = endpoints?.First().Port;
        // set a breakpoint here
        return $"Host={address};Port={port};";// Username=postgres;Password={graphPw};Database=postgres;";
    });
```

**Comment by davidfowl** [comment]
See https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/networking-overview for more details on how networking works with aspire.

**Comment by paule96** [comment]
Hm okay. So it's basically like:

random port from proxy --> random port from docker host --> actual container port


But then I maybe have a different problem. You can't connect over the proxy to the gremlin api of the gremlin server. I guess because he tries to use we sockets. (p.s. I tryed this code before without `AddHttpEndpoint` but without it, it was not nice to screenshot, I used AddEndpoint on my other try)

**Comment by davidfowl** [comment]
The proxy is a tcp proxy so it should proxy anything. It's likely that you need to use host.docker.internal. If you want to model this container like the others, you could do something like this:

```C#
static class GremlinExtensions
{
    public static IResourceBuilder<GremlinResource> AddGremlinContainer(this IDistributedApplicationBuilder builder, string name, int? hostPort = null)
    {
        return builder.AddResource(new GremlinResource(name))
            .WithAnnotation(new ContainerImageAnnotation { Image = "tinkerpop/gremlin-server", Tag = "latest" })
            .WithHttpEndpoint(containerPort: 8182, hostPort: hostPort);
    }
}

class GremlinResource(string name) : ContainerResource(name), IResourceWithConnectionString
{
    public string? GetConnectionString()
    {
        if (!this.TryGetAllocatedEndPoints(out var endpoints))
        {
            throw new InvalidOperationException("Resource has not been allocated yet");
        }

        return $"Host=localhost;Port={endpoints.Single().Port};";
    }
}
```

Usage:

```C#
var builder = DistributedApplication.CreateBuilder(args);
var graph = builder.AddGremlinContainer("graph");

var apiService = builder.AddProject<Projects.someapi>("someapi")
                                     .WithReference(graph);
```

**Comment by paule96** [comment]
@davidfowl I will give it a try tomorrow.

**Comment by paule96** [comment]
for some reason it worked today... Maybe yesterday was just to late. 🤷‍♀️
@davidfowl thanks for your help.
