### ISSUE TITLE
Structured logs error tooltip is closed by copy tooltip popup

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2146]
The structured logs error tooltip is closed if the mouse goes over the copy to clipboard tooltip:

![exception-popup-close](https://github.com/dotnet/aspire/assets/303201/bec58d77-2224-4637-a465-d6dd20c20c63)

@vnbaaij Have you seen this before? Suggestions for a fix?

If there isn't a fast solution, then we can remove the tooltip from the copy button. It's not necessary.

**Comment by adamint** [comment]
it’s possible that only one tooltip is supported at once. Your suggestion of just removing the tooltip is probably best

**Comment by vnbaaij** [comment]
Nope, not seen that before! Tooltip does seem to be a bit of overkill.
