### ISSUE TITLE
Execute arbitrary code once a resource is up and running (some kind of "after start" event)

### ISSUE THREAD

**Issue by asimmon** [dotnet/aspire#2155]
Currently, the `IDistributedApplicationLifecycleHook` hook only allows us to modify the app model before starting the resources. Is there a plan to add a hook that allows us to respond to an event indicating that a resource is up and running (or has failed to start, or any status change)? Does the orchestrator (DCP) support such a feature?

**Comment by davidfowl** [comment]
I think we should add a hook that runs after the resources were told to start, but it doesn't mean they are healthy. Your code would still need to be resilient to that.

**Comment by asimmon** [comment]
It makes sense that my code should be resilient, as we cannot predict the behavior of the resources. However, I'm trying to understand the precise definition of "executing code after the resources were told to start."

Does this mean it would trigger immediately after the .NET Aspire part has finished its job of pushing the desired state to the orchestrator?

Or does the .NET Aspire part wait to receive at least some indication that the orchestrator attempted to start the resource, which could result in various states, such as: process not found, container not found, or resource has started (which doesn't mean it's healthy)? Thinking about it, it reminds me of [CliWrap](https://github.com/Tyrrrz/CliWrap), which returns a [CommandTask](https://github.com/Tyrrrz/CliWrap/blob/3.6.6/CliWrap/CommandTask.cs) containing the process information if started (although the process could fail miserably) or throws an exception if the process wasn't found.

If we cannot rely on such a signal, I could implement today an `IDistributedApplicationLifecycleHook.AfterEndpointsAllocatedAsync`, start my resilient code in a "detached" task whose lifetime is secured by using the provided cancellation token, and wait for the resource to actually become available.

**Comment by davidfowl** [comment]
> Does this mean it would trigger immediately after the .NET Aspire part has finished its job of pushing the desired state to the orchestrator?

This. We tell the orchestrator to start, but we there's no [concept of health in the system as yet](https://github.com/dotnet/aspire/issues/890)

**Comment by BrennanConroy** [comment]
So we're thinking somthing like
```diff
interface IDistributedApplicationLifecycleHook
{
     // Runs after resources have been orchestrated. There is no guarantee that the resources are healthy or ready for use at this point.
+    Task AfterStartAsync(DistributedApplicationModel appModel, CancellationToken cancellationToken = default);
}
```
Or `AfterResourcesCreatedAsync`/`AfterResourcesProvisionedAsync`?
