### ISSUE TITLE
Remove 'preview' label from Aspire SDK component in VS 17.10 installer

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#2173]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU 
2. Install VS 17.10 P1, Web workload

**ACTUAL**
The component ".NET Aspire SDK" in VS installer is marked as "(Preview)"

**EXPECTED**
Preview label should removed from the suffix

**Comment by mitchdenny** [comment]
@joperezr assigning this to you. Looks like you've already done the work but I just downloaded the latest IntPreview build and the workload still has the old name so maybe it hasn't flowed through?

**Comment by joperezr** [comment]
Yup, we haven't inserted into VS yet, so this would get fixed sometime next week when we do 😃

**Comment by v-sherryfan** [comment]
Fixed in the final 8.0 GA VS insertion PR
