### ISSUE TITLE
Move all 3rd party resources types to a separate package

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2174]
We should start refactoring all of the 3rd party resources (any container image we get from docker hub) to a single package Aspire.Hosting.Docker (naming tbd). We should move all of the resource types and their extension methods to this new project. It will still be referenced by Aspire.Hosting until we complete the refactoring and make that package a meta package.

This means, the resources for redis. mongo, mysql, sql etc, all get moved out of the core package.

**Comment by darren-clark** [comment]
Shouldn't they get moved into their own packages? e.g. Aspire.Hosting.MongoDB, Aspire.Hosting.Redis, etc...  Seemed odd to have them in the core package, but also seems odd to just have them piled into a single "other stuff" package.

**Comment by davidfowl** [comment]
Likely in the long run. Having a whole nuget for 2 method types feels really bad though. In theory, we could codegen most of these packages from a configuration file. I’m not 100% sure of the granularity yet.
