### ISSUE TITLE
Consider shipping a Aspire.OpenTelemetry.ServiceDefaults package

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2180]
Today we have a default otel setup in service defaults with [these methods](https://github.com/dotnet/aspire/blob/6bff6e129c434f90da173bae1d37e35760571890/src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/Extensions.cs#L34-L88) and [these dependencies](https://github.com/dotnet/aspire/blob/6bff6e129c434f90da173bae1d37e35760571890/src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/Aspire.ServiceDefaults1.csproj#L16-L22). We should consider building a package that encapsulates these baseline otel dependencies (and versions). 

PS: I'm not sure if this package should have any API as yet but we could consider it assuming there was a simple way to override.

cc @eerhardt @samsp-msft

**Comment by eerhardt** [comment]
Is this something OTel should consider doing? That way people wouldn't need to reference all these packages (even outside of Aspire).

**Comment by davidfowl** [comment]
I don't think so, unless they were OK being "opinionated", which I think is why we have these sorts of packages in the first place.

**Comment by davidfowl** [comment]
Assigning to @samsp-msft for P5 to see if it makes sense to do this or not.

**Comment by samsp-msft** [comment]
I am going to say that we shouldn't be packaging this up the code in ServiceDefaults. While the code is boilerplate it is all something that is subject to customer modification. We want the customer to see what polices we are applying. If you add additional metrics/traces, change the exporter, or wish to add /change the sampling policy (#4825), then you will want to have access to this code. 

I don't think we should be trying to package up the references either as they all ship on potentially different timelines from Aspire. The customer should be able to update these packages when new versions / patches are released without waiting on us to repackage them.

**Comment by davidfowl** [comment]
> I don't think we should be trying to package up the references either as they all ship on potentially different timelines from Aspire. The customer should be able to update these packages when new versions / patches are released without waiting on us to repackage them.

This problem exists for every package aspire ships, telemetry isn't unique.
