### ISSUE TITLE
Unable to add project with multiple endpoints with the same scheme in launchSettings

### ISSUE THREAD

**Issue by WolfspiritM** [dotnet/aspire#2207]
Hi,

I have a project (a gateway) that has multiple http and https endpoints defined in launchSettings.

When I try to add it I get the following exception:
`DistributedApplicationException: Endpoint with name 'https' already exists.`
https://github.com/dotnet/aspire/blob/4006c2f321d09846a6acdada4dcbf5182220bcca/src/Aspire.Hosting/Dcp/DcpDistributedApplicationLifecycleHook.cs#L48

I tried the following but this doesn't change anything:
```
builder.AddProject<Projects.Gateway>("gateway")
    .WithEndpoint(4000, "https", "first-https")
    .WithEndpoint(4001, "https", "second-https")
    .WithEndpoint(4100, "http", "first-http")
    .WithEndpoint(4101, "http", "second-http");
```

I think there should be a way to skip adding endpoints if "withEndpoint" is used manually.
Especially if the endpoint has already been added with a different name.

**Comment by DamianEdwards** [comment]
There is a method to not use the launch profile coming in preview.4: `ExcludeLaunchProfile`

For preview.3, you can create an empty launch profile (one with no endpoints) and call `WithLaunchProfile("empty")`.

**Comment by WolfspiritM** [comment]
@DamianEdwards Thanks a lot!
