### ISSUE TITLE
RabbitMQ extension method hides the async configuration possibilities for the client

### ISSUE THREAD

**Issue by attilah** [dotnet/aspire#2221]
[Here](https://github.com/dotnet/aspire/blob/v8.0.0-preview.3.24105.21/src/Components/Aspire.RabbitMQ.Client/AspireRabbitMQExtensions.cs#L78) the type that is passed to the `configureConnectionFactory` action is `IConnectionFactory`, while the `ConnectionFactory` implementation in the 6.x RabbitMQ client is the implementing the [`IAsyncConnectionFactory`](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/6.x/projects/RabbitMQ.Client/client/api/ConnectionFactory.cs#L90) directly, which enables to configure RabbitMQ client to use the async consumers.
Unfortunately, `IAsyncConnectionFactory` is removed in the upcoming 7.x RabbitMQ client and the `DispatchConsumersAsync` property moved up to `IConnectionFactory` interface.

I was wondering if an `EnableAsyncConsumers` or similar setting would make sense to make this configuration option more discoverable or it should be a documentation enhancement which shows casting the factory to the async interface type and then set the `DispatchConsumersAsync` to true there?

**Comment by eerhardt** [comment]
> I was wondering if an EnableAsyncConsumers or similar setting would make sense to make this configuration option more discoverable or it should be a documentation enhancement which shows casting the factory to the async interface type and then set the DispatchConsumersAsync to true there?

We have the setting in the configuration schema:

https://github.com/dotnet/aspire/blob/f07a34179c6078b8965e110a16ba2b7005dfb3c0/src/Components/Aspire.RabbitMQ.Client/ConfigurationSchema.json#L105-L108

This can be set in the appsettings.json file (or any configuration source). Visual Studio will show intellisense in the appsettings.json file:

![image](https://github.com/dotnet/aspire/assets/8291187/ffd5ba8a-32f7-43dc-8296-3b2affba5662)

I'm not sure how the Aspire documentation would help here. Customers are still expected to read the underlying library's documentation. Do you have a specific suggestion?

**Comment by attilah** [comment]
@eerhardt This [single line](https://github.com/dotnet/aspire/blob/f07a34179c6078b8965e110a16ba2b7005dfb3c0/src/Components/Aspire.RabbitMQ.Client/AspireRabbitMQExtensions.cs#L86) is the only way to know how that `ConnectionFactory` element will be bound to the `ConnnectionFactory` instance.

On the [RabbitMQ](https://learn.microsoft.com/en-us/dotnet/aspire/messaging/rabbitmq-client-component?tabs=dotnet-cli#use-configuration-providers) section of Aspire it is not mentioned anywhere, so by reading the documentation of Aspire and RabbitMQ you can't really find the missing puzzle piece (or it's just me ;-)).

Based on this Today there is no standard - what is usual with the .NET configuration API - to setup this from code. If the `configureConnectionFactory` callback would receive the `ConnectionFactory` (especially as it is created by the extension method calling it) and not an `IConnectionFactory`, that would solve this problem.

Other than that you can only do this:
```
builder.AddRabbitMQ(
    "queue",
    configureConnectionFactory: factory =>
    {
        if (factory is IAsyncConnectionFactory asyncFactory)
        {
            asyncFactory.DispatchConsumersAsync = true;
        }
    }
);
```

Perhaps it would be help with discoverability to link the configuration schema for each component from the documentation pages, as the schema is not mentioned anywhere, also Intellisense is a VS only feature.

I hope if helps to clarify what was I missing and what I was looking for.

**Comment by eerhardt** [comment]
@radical - this seems like a simple fix. Can you take it for preview5?
