### ISSUE TITLE
EntityFramework Components Timeout setting consistency

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#2227]
We currently have 5 EF components:

* Npgsql
* SqlServer
* Oracle
* MySql
* Cosmos

2 of these components have a `int? Timeout` setting:

https://github.com/dotnet/aspire/blob/f07a34179c6078b8965e110a16ba2b7005dfb3c0/src/Components/Aspire.Microsoft.EntityFrameworkCore.SqlServer/MicrosoftEntityFrameworkCoreSqlServerSettings.cs#L54-L57

https://github.com/dotnet/aspire/blob/f07a34179c6078b8965e110a16ba2b7005dfb3c0/src/Components/Aspire.Oracle.EntityFrameworkCore/OracleEntityFrameworkCoreSettings.cs#L46-L49

But the other 3 don't.

We should make this consistent across all EF providers. Either we have this setting on all of them, or we remove it from these 2.

cc @sebastienros @DamianEdwards @roji @AndriySvyryd

**Comment by AndriySvyryd** [comment]
Also consider renaming them to `CommandTimeout` to distinguish from other, like connection timeout
