### ISSUE TITLE
[Bug] No integration tests possible - Reference not found

### ISSUE THREAD

**Issue by MiTschMR** [dotnet/aspire#2229]
Just for clarification, this worked previously in the second preview of Aspire, but stopped yesterday randomly before the preview 3 release and I don't know why. I can't get it to work even with a previously restored branch of my repository...

Aspire: Preview 3 (Aspire.Hosting 8.0.0-preview.3.24105.21)
VS: 17.10.0 Preview 1.0

A reproduction project is attached to this report.

Steps: Follow all the steps until `Run test` in the https://medium.com/@a.skuratovich/write-integration-tests-with-net-aspire-582f1e7da94c to set up an integration project. You will notice the following error: 
```
Error CS0234: The type or namespace name 'ApiService' does not exist in the namespace 'AspireSample' (are you missing an assembly reference?) <Path to project>\AspireSample\AspireSample.Tests\ApiServiceFixture.
```

When removing the line `<IsAspireHost>true</IsAspireHost>` from the `AspireSample.Test` project file everything compiles.

My guess is that there can not be two Aspire hosting projects within the same solution referencing the same project, in this case `AspireSample.ApiService`.

[AspireSample.zip](https://github.com/dotnet/aspire/files/14284048/AspireSample.zip)

**Comment by MiTschMR** [comment]
A workaround can be found here: https://github.com/dotnet/aspire/issues/2234#issuecomment-1944735484

**Comment by eerhardt** [comment]
Appending `IsAspireProjectResource="false"` isn't the "workaround", it is how this is designed to work now. If your AppHost needs to actually reference another project, you need to opt-in to it. The default `ProjectReference` in an AppHost is to reference service application (i.e. an 'exe') and not actually reference it at compile time.

See 

* https://github.com/dotnet/aspire/issues/1074
* https://github.com/dotnet/aspire/issues/1563

For more discussion.

Also check out https://github.com/dotnet/aspire/pull/2310/ for new work that will make integration testing better. cc @ReubenBond 

Closing.
