### ISSUE TITLE
.NET Aspire with APIM

### ISSUE THREAD

**Issue by Arslan007** [dotnet/aspire#2235]
Can I use Aspire with my api's behind the APIM so I can have centralized monitoring and analytics along with my client facing webs and apps

**Comment by davidfowl** [comment]
Can you? Yes! Will aspire help you provision an APIM? No it won’t. 

Thats out of scope for the first release.

**Comment by eerhardt** [comment]
Closing for now as we don't have plans for enabling this. But you can do it yourself.
