### ISSUE TITLE
Which endpoints should be propagated to ASPNETCORE_URLS env var?

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/aspire#2241]
In #2239, I changed the logic to exclude endpoints which either:
* Don't have a "http" or "https" URI scheme
* Have an EnvironmentVariable set

Is this the logic we want to stick with or is there a more robust check we could make?

**Comment by kvenkatrajan** [comment]
@ReubenBond can you provide more details on what work is needed from the dashboard here?

**Comment by ReubenBond** [comment]
@kvenkatrajan the bot mislabeled this - thanks for drawing my attention to it

**Comment by davidfowl** [comment]
Moving this back into p6. After https://github.com/dotnet/aspire/pull/3305 all http or https endpoints are part of ASPNETCORE_URLS. We might want to introduce another API for this.
