### ISSUE TITLE
Error while deploying React App to Azure (azd)

### ISSUE THREAD

**Issue by adamtrip** [dotnet/aspire#2246]
Hi there. Not sure if to post here or on `azd` repo but here it goes.

While deploying to azure with github actions using the example provided [here](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio#add-the-github-actions-workflow-file), i'm getting the following error deploying a react app:

`ERROR: failed packaging service 'drcpwebapp': failing invoking action 'package', parsing source container image: empty image URL provided`

I'm using version `8.0.0-preview.3.24076.8`.

```
builder.AddNpmApp("drcpwebapp", "../drcp-frontend", "dev")
    .WithEndpoint(3000, scheme: "http", env: "PORT")
    .WithReference(authService)
    .WithReference(machineService)
    .AsDockerfileInManifest();
```

Thanks in advance!

**Comment by adamtrip** [comment]
Just a quick update. Decided to try and deploy manually using `azd up` directly on my machine. Everthing deploys however, I get the error that .NET is not installed on every dotnet service.

**Comment by davidfowl** [comment]
Can you file this here https://github.com/Azure/azure-dev/issues

**Comment by timheuer** [comment]
I just hit this as well, logged https://github.com/Azure/azure-dev/issues/3391.  I'm not getting past this locally even like you are @adamtrip

**Comment by davidfowl** [comment]
Did you set the container port? 

https://github.com/dotnet/aspire-samples/blob/0f07e991cc2c0f4a8935040d39d64b68c66039ba/samples/AspireWithNode/AspireWithNode.AppHost/Program.cs#L10

**Comment by timheuer** [comment]
Yep, I'm using the same sample https://github.com/timheuer/js-aspire
