### ISSUE TITLE
Service application gets dashboard url injected if there's no launch settings

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#225]
Make an ASP.NET Core application and delete the launch settings. Run the app host and observe that the application fails to run. This is because applicationUrl from the app host is being injected as ASPNETCORE_URLS which flows to the child process.

**Comment by davidfowl** [comment]
I can take this one @karolz-ms

**Comment by karolz-ms** [comment]
Would appreciate the help, thank you @davidfowl 🤗

**Comment by davidfowl** [comment]
@BrennanConroy and this one

**Comment by davidfowl** [comment]
This required dcp changes to fix.

**Comment by davidfowl** [comment]
@karolz-ms we're not doing this for P3 right?

**Comment by karolz-ms** [comment]
> @karolz-ms we're not doing this for P3 right?

Not for P3. Scheduled for P4 https://github.com/microsoft/usvc/issues/118
