### ISSUE TITLE
Aspire Projects Boot fails with Randon K8 Configuration Error

### ISSUE THREAD

**Issue by Sen-Gupta** [dotnet/aspire#2251]
Environment:

Latest Preview 3  <AspireVersion>8.0.0-preview.3.24105.21</AspireVersion>
Visual Studio Professional 17.9.0

Issues: Random failures to boot proojects. AppHost boots but keeps waiting! 
Solution: Close AppHost, Run again!

'Insights.AppHost.exe' (CoreCLR: clrhost): Loaded 'D:\Trade\InsightsOnDaprAspire\src\Aspire\AppHost\bin\Debug\net8.0\YamlDotNet.dll'. 
Exception thrown: 'k8s.Exceptions.KubeConfigException' in KubernetesClient.dll
Exception thrown: 'k8s.Exceptions.KubeConfigException' in System.Private.CoreLib.dll
Exception thrown: 'k8s.Exceptions.KubeConfigException' in System.Private.CoreLib.dll
'Insights.AppHost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Diagnostics.StackTrace.dll'. 
'Insights.AppHost.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Reflection.Metadata.dll'. 
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll

**Comment by davidfowl** [comment]
Those look like normal first chance exceptions. Are you just looking at the debug output window?

**Comment by Sen-Gupta** [comment]
Yes. Debut Output Window!

I would share more details when I resume on the project again.

Thanks!

**Comment by davidfowl** [comment]
There are some exceptions that come from the apphost code. This is by design and they are caught.
