### ISSUE TITLE
Safari 16.5 - view button on each trace line istn't clickable 

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#2272]
While testing with Safari 16.5 it was noticed that View link on individual trace lines was not clickable 

![image](https://github.com/dotnet/aspire/assets/102772054/f68eb886-65ce-4faf-94ff-e9a92da8aa2c)

CC: @timheuer

**Comment by adamint** [comment]
This does not reproduce for me on Safari 17.3.1. 16.5 is almost a year old, users should upgrade.

![image](https://github.com/dotnet/aspire/assets/20359921/7ca94ad2-c58f-4ffc-b1d1-d824dc9a8c80)

**Comment by adamint** [comment]
cc @kvenkatrajan

**Comment by v-polly** [comment]
@adamint @kvenkatrajan We reproduced this issue again today when we were doing Aspire 8.0.0-preview.4.24129.7 on macOS with Safari 17.3.1(18617.2.4.11.12, 18617), If you also reproduce the problem, does this issue need to be reactive?

**Comment by kvenkatrajan** [comment]
@adamint  reopening - please circle back with @v-polly  on repro steps.

**Comment by adamint** [comment]
I still cannot reproduce. @kvenkatrajan

**Comment by adamint** [comment]
For me, the rest of the row is not clickable, but the button is.

**Comment by adamint** [comment]
Update: I can now reproduce. Additionally, though quite amusing, the table just completely doesn't render correctly, as you can see in the image below. Investigating now 

<img width="1494" alt="image" src="https://github.com/dotnet/aspire/assets/20359921/8f832716-c56e-4f45-b057-6dd3f866eb48">

**Comment by adamint** [comment]
I have isolated the issue to [here](https://github.com/dotnet/aspire/blob/1e856ca1e580a6e6d5f687cc0d02a9e9cb52f490/src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css#L43)
