### ISSUE TITLE
Review container image versions for .NET Aspire 8.0 preview 6

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#2276]
This is a recurring issue for reviewing container image dependencies for upcoming releases. Please follow the following process:

- [x] Review all ContainerImageAnnotation usages and determine whether the container image tag that is being used needs to be updated for the upcoming release.
- [ ] If updates are required update the image tag, doc comments, and test cases.
- [ ] Create a copy of this issue for the next release and assign it to the appropriate milestone.

**Comment by timheuer** [comment]
tbh when I was navigating the code I kinda wanted all these values in some type of constants location :-)

**Comment by mitchdenny** [comment]
Yeah. Not a bad idea. Next time we update them we'll do this. But it'll be marked internal because they are going to change every month ;)

**Comment by danmoseley** [comment]
when closing this please create another issue for next preview.

**Comment by mitchdenny** [comment]
@radical I noticed you were going through extracting some of the hardcoded image tag version strings into a separate static class? If so could you check to see whether the image versions need to be updated at the same time?

**Comment by danmoseley** [comment]
@radical what remains here now https://github.com/dotnet/aspire/pull/3847 was merged?
Well once that is in main  as well.

**Comment by mitchdenny** [comment]
I think this can now be closed for GA.
