### ISSUE TITLE
Name validation with Azure Cosmos DB component

### ISSUE THREAD

**Issue by christiannagel** [dotnet/aspire#2288]
With a previous version of .NET Aspire and azd I could successfully connect to an existing Cosmos database using 

```csharp
var cosmos = builder.AddAzureCosmosDB("GamesCosmosConnection", cosmosConnectionString);
```

Using Aspire Preview 3 with azd 1.6.1, the Cosmos-connection string resource is not known from azd.

Changing this to 

```csharp
var cosmos = builder.AddAzureCosmosDB("GamesCosmosConnection")
   .AddDatabase("codebreaker");
```

azd failed with an error about the uppercase `G` character. Changing this to all lowercase, it succeeded.

I think there should be name validation with the Aspire Cosmos component to fix this long before `azd up`.

**Comment by timheuer** [comment]
Related https://github.com/dotnet/aspire/issues/1209#issuecomment-1905468811

**Comment by davidfowl** [comment]
@mitchdenny with the cdk based resources, do we always generate valid resource names?

**Comment by mitchdenny** [comment]
@davidfowl yes. Part of the name generation logic is a `tolower(...)`. All resources should be consistent in that regard now.

**Comment by mitchdenny** [comment]
Now that we've transitioned over to using CDK to generate the resources we force the resource name to lowercase so this shouldn't be an issue anymore.
