### ISSUE TITLE
Improve trace name column tooltip

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspire#2304]
![image](https://github.com/dotnet/aspire/assets/5714438/807b39d1-83cc-4b64-840e-2242e13379b1)

**Comment by JamesNK** [comment]
Why do you want a trace ID column? A column takes up more horizontal space and we want to keep as much space as possible for the name and spans.

**Comment by JamesNK** [comment]
Ok. An improvement to make here is give more detail in the tooltip.

**Comment by davidfowl** [comment]
@Varorbc if you want to send a PR for this feel free!
