### ISSUE TITLE
Suggestions for project templates

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspire#2305]
The default value of the output type is the `Library`, which is not necessarily defined repeatedly.Also, why does the project need to reference `Microsoft.AspNetCore.App`, I found that it can still work well after removal. Is this reference necessary? If so, can `IsAspireSharedProject `be implicitly referenced when it is `true`?

https://github.com/dotnet/aspire/blob/ea2315c8917cb2a5be570654720cd88c978508c1/src/Aspire.ProjectTemplates/templates/aspire-starter/AspireStarterApplication.1.ServiceDefaults/AspireStarterApplication.1.ServiceDefaults.csproj#L1-L12

The default value of the output type is the `Exe`, which is not necessarily defined repeatedly.

https://github.com/dotnet/aspire/blob/ea2315c8917cb2a5be570654720cd88c978508c1/src/Aspire.ProjectTemplates/templates/aspire-starter/AspireStarterApplication.1.ApiService/AspireStarterApplication.1.ApiService.csproj#L1-L4
https://github.com/dotnet/aspire/blob/ea2315c8917cb2a5be570654720cd88c978508c1/src/Aspire.ProjectTemplates/templates/aspire-starter/AspireStarterApplication.1.Web/AspireStarterApplication.1.Web.csproj#L1-L4

Can the output type be set to `Exe ` when `IsAspireHost ` is `true`, just like a web project

https://github.com/dotnet/aspire/blob/ea2315c8917cb2a5be570654720cd88c978508c1/src/Aspire.ProjectTemplates/templates/aspire-starter/AspireStarterApplication.1.AppHost/AspireStarterApplication.1.AppHost.csproj#L1-L8

using https instead of http
https://github.com/dotnet/aspire/blob/ea2315c8917cb2a5be570654720cd88c978508c1/src/Aspire.ProjectTemplates/templates/aspire-starter/AspireStarterApplication.1.Web/Properties/launchSettings.json#L2

All other templates have the issues I mentioned above, so I will not describe them one by one

**Comment by davidfowl** [comment]
You can't switch to https, instead of http. There are lots of reasons we chose http. That requires other feature work and design to get right. The other changes are fine (as long as they are consistent with normal asp.net core projects).

**Comment by eerhardt** [comment]
Not worth it - IMO.
