### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.Azure.Hosting package and builder.AddAzureKeyVault call to AppHost, F5 failed with exception: A connection string for 'xxx' could not be retrieved.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2315]
**REGRESSION INFO**: Worked fine on Aspire version 8.0.0-preview.3.24105.21

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34619.48.main] (includes Aspire 8.0.0-preview.3.24105.21)
3. Install Aspire 8.0 P4 workload version 8.0.0-preview.4.24118.7
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. New Project > ASP.NET Core Empty template > name it 'EmptyApp3' > .NET 8.0 > check 'Enlist in Aspire orchestration'> Create 
2. Build and run > works fine
3. Right-click EmptyApp3.AppHost project > Manage NuGet Packages > Aspire.Azure.Hosting > install version 8.0.0-preview.4.24118.7 (i.e. matching the Aspire version that's installed)
4. Open appsettings.json of EmptyApp3.AppHost project, add ConnectionStrings configuration section: 
       
```
       "ConnectionStrings": { 
            "secretConnectionName": "https://{keyvault_account_name}.vault.azure.net/" 
          } 
        } 
```
5. Open Program.cs of xxx.AppHost project, add following code:
        
```
var keyVault = builder.AddAzureKeyVault("secretConnectionName");
builder.AddProject<Projects.EmptyApp3>("emptyapp3")
    .WithReference(keyVault);
```
6. Build and F5 

**Notes**:
1. This issue also reproduces on .NET Aspire Starter Application.
2. This issue also reproduces on Aspire.Azure.Messaging.ServiceBus/Aspire.Azure.Storage.Blobs/Aspire.Azure.Storage.Queues components

**ACTUAL**
F5 failed with exception 
DistributedApplicationException: A connection string for 'secretConnectionName' could not be retrieved.

**Full call stack**
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (A connection string for 'secretConnectionName' could not be retrieved.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in System.Threading.Tasks\Task.cs:line 1912
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in System.Threading.Tasks\Task.cs:line 2402
   at System.Threading.Tasks.Task.Wait() in System.Threading.Tasks\Task.cs:line 2352
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 141
   at Program.<Main>$(String[] args) in C:\Users\balach\source\repos\EmptyApp3\EmptyApp3.AppHost\Program.cs:line 7

  This exception was originally thrown at this call stack:
    Aspire.Hosting.ResourceBuilderExtensions.WithReference.AnonymousMethod__0(Aspire.Hosting.ApplicationModel.EnvironmentCallbackContext) in ResourceBuilderExtensions.cs
    Aspire.Hosting.Dcp.ApplicationExecutor.CreateExecutablesAsync(System.Collections.Generic.IEnumerable<Aspire.Hosting.Dcp.AppResource>, System.Threading.CancellationToken) in ApplicationExecutor.cs
    Aspire.Hosting.Dcp.ApplicationExecutor.CreateContainersAndExecutablesAsync(System.Threading.CancellationToken) in ApplicationExecutor.cs
    Aspire.Hosting.Dcp.ApplicationExecutor.RunApplicationAsync(System.Threading.CancellationToken) in ApplicationExecutor.cs
    Aspire.Hosting.Dcp.DcpHostService.StartAsync(System.Threading.CancellationToken) in DcpHostService.cs
    Microsoft.Extensions.Hosting.Internal.Host.StartAsync.AnonymousMethod__15_1(Microsoft.Extensions.Hosting.IHostedService, System.Threading.CancellationToken) in Host.cs
    Microsoft.Extensions.Hosting.Internal.Host.ForeachService<T>(System.Collections.Generic.IEnumerable<T>, System.Threading.CancellationToken, bool, bool, System.Collections.Generic.List<System.Exception>, System.Func<T, System.Threading.CancellationToken, System.Threading.Tasks.Task>) in Host.cs
    Microsoft.Extensions.Hosting.Internal.Host.StartAsync(System.Threading.CancellationToken) in Host.cs
    Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(Microsoft.Extensions.Hosting.IHost, System.Threading.CancellationToken) in HostingAbstractionsHostExtensions.cs
    Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(Microsoft.Extensions.Hosting.IHost, System.Threading.CancellationToken) in HostingAbstractionsHostExtensions.cs
    ...
    [Call Stack Truncated]

Inner Exception 1:
DistributedApplicationException: A connection string for 'secretConnectionName' could not be retrieved.

![image](https://github.com/dotnet/aspire/assets/8246794/cbce291e-c782-49e9-b28c-a95fb46d6315)

**EXPECTED**
Run successfully.

![image](https://github.com/dotnet/aspire/assets/8246794/c94a60e3-15e2-480a-a40a-e8d934455ba9)

**Comment by davidfowl** [comment]
This area is currently undergoing lots of changes. I'll leave it open for now though.

**Comment by v-cazhang** [comment]
Update the repro steps which can read a value from the KeyVault and get it to show up in the browser on Aspire P3 but failed on Aspire P4.

**Comment by balachir** [comment]
Simplified the repro steps some more and updated title. With my updated repro steps, it works fine with 8.0 P3 but this exception is thrown with 8.0 P4 builds.

cc: @eerhardt @mitchdenny for awareness

**Comment by eerhardt** [comment]
I believe what broke it is this change:

https://github.com/dotnet/aspire/commit/bfd9376dc61c59971a2abad79ee7a546d3e93087#diff-7fd7862ce12369547085d74b5813ae529b1cdee8ab4024a4dbb23c2680539f3aL196-R193

![image](https://github.com/dotnet/aspire/assets/8291187/00668815-40fb-48d9-9488-227f69e6097d)

WithReference is no longer falling back to the AppHost's configuration to get the connection information.

**Comment by davidfowl** [comment]
Right this was an intentional change. We still need to work through the end to end though. We're moving away from this model for p4.

**Comment by eerhardt** [comment]
> We're moving away from this model for p4.

And moving towards what? I've used this functionality in the past, and it makes it nice to keep this configuration in a single place.

We are even using it in eshop with https://github.com/dotnet/eShop/pull/153. See 

https://github.com/dotnet/eShop/blob/857fc5d18ea4e081b9e8a069763b037e3c695dec/src/eShop.AppHost/appsettings.json#L9-L11

**Comment by davidfowl** [comment]
`builder.AddConnectionString`

**Comment by eerhardt** [comment]
Closing as this was an intentional change. Please use `builder.AddConnectionString` to make a connection string for an existing resource.
