### ISSUE TITLE
[WebToolsE2E][Aspire] For an ASP.NET Core Web App Ind Auth project with Aspire, package restore fails when adding Aspire component Aspire.Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#2317]
**REGRESSION INFO**: Worked fine on Aspire.ProjectTemplates.8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34619.48.main]
    - Includes SDK 8.0.300-preview.24101.10
    - Includes Aspire version 8.0.0-preview.3.24105.21
    - Includes ASP.NET Core templates version 8.0.1
    - ![image](https://github.com/dotnet/aspire/assets/8246794/e87dc8e6-4333-4001-a2f8-e5b9af80caa9)

3. Install Aspire 8.0 P4
    - Version 8.0.0-preview.4.24118.7
4. Apply NuGet Feeds

**REPRO STEPS**
1. New Project > ASP.NET Core Web App > .NET 8.0 > Individual Auth > checked 'Enlist in Aspire orchestration'> give name as 'WebApp2' > Create
    - WebApp2 gets created with Aspire orchestration
    - As Ind Auth was chosen, the 8.0.1 version of the Microsoft.EntityFrameworkCore.SqlServer package gets added to csproj
    - ![image](https://github.com/dotnet/aspire/assets/8246794/093f2520-ed87-4311-bd84-3774f36b1322)

3. Right-click web project > Add >  Aspire component > Aspire.Microsoft.EntityFrameworkCore.SqlServer > choose version 8.0.0-preview.4.24118.7 (i.e. the version that's matching the installed Aspire version)

**ACTUAL**
A package restore error occurs and it fails to add the Aspire component. The reason is because the latest version of Aspire.Microsoft.EntityFrameworkCore.SqlServer depends on Microsoft.EntityFrameworkCore.SqlServer (>= 8.0.2). But as shown in the csproj, the WebApp1 is pinned to Microsoft.EntityFrameworkCore.SqlServer version 8.0.1. 

_From Output Window > Package Manager pane_
NU1605: Warning As Error: Detected package downgrade: Microsoft.EntityFrameworkCore.SqlServer from 8.0.2 to 8.0.1. Reference the package directly from the project to select a different version. 
 WebApp2 -> Aspire.Microsoft.EntityFrameworkCore.SqlServer 8.0.0-preview.4.24118.7 -> Microsoft.EntityFrameworkCore.SqlServer (>= 8.0.2) 
 WebApp2 -> Microsoft.EntityFrameworkCore.SqlServer (>= 8.0.1)
Package restore failed. Rolling back package changes for 'WebApp2'.
			
![image](https://github.com/dotnet/aspire/assets/8246794/a49e9925-5c61-43e7-a08f-436e227a3c3c)

![image](https://github.com/dotnet/aspire/assets/8246794/73513c84-1f5c-4de8-b66b-7a98f104958a)

**Workaround**: Update version of 'Microsoft.EntityFrameworkCore.SqlServer' in WebApp1 to 8.0.2. Then the package 'Aspire.Microsoft.EntityFrameworkCore.SqlServer' can be installed successfully.

**EXPECTED**
Package 'Aspire.Microsoft.EntityFrameworkCore.SqlServer' can be installed successfully without manually updating the package versions.

**Comment by balachir** [comment]
Updated title and Repro Steps. @eerhardt @davidfowl this is an interesting case where the Aspire component fails to add because the ASP.NET Core template has a pinned dependency on an older version. Is it By Design?

cc: @v-cazhang @v-bennettyue @v-sherryfan @v-elenafeng

**Comment by eerhardt** [comment]
> Includes ASP.NET Core templates version 8.0.1

I think this is the issue. 8.0.2 is out now. Using the latest version of the templates would fix this.

**Comment by balachir** [comment]
@eerhardt yes. If the user's project has the latest version of the templates, this won't repro. My high-level question is - what will we recommend to customers when they hit issues like this one? Should they always make sure that their package dependencies are on the latest version before trying to add Aspire components?

**Comment by eerhardt** [comment]
Our general strategy here is to always update our Aspire libraries' dependencies with the latest versions every time we ship. That strategy will cause these kinds of situations all over the place. When users see that error, they will need to update their direct dependencies to match.

cc @joperezr @DamianEdwards

**Comment by eerhardt** [comment]
This no longer repros. We are building against the latest: `8.0.4`
