### ISSUE TITLE
Dashboard: Not all tags recorded / shown?

### ISSUE THREAD

**Issue by christophwille** [dotnet/aspire#2354]
https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#optional-add-status

```
activity?.SetTag("otel.status_code", "ERROR");
activity?.SetTag("otel.status_description", "Use this text give more information about the error");
```

I added this. The Dashboard shows the error icon (so otel.status_code is evaluated properly), however, I cannot find the status description anywhere (funny aside: I set "enduser.id" tag for that very activity, and that displays nicely in the Span section). 

Am I looking in the wrong places or is this really not there?

**Comment by christophwille** [comment]
Addendum: using `activity?.SetStatus(ActivityStatusCode.Error, "my message");` (which is the shorthand) same result, no status description in Dashboard.

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by christophwille** [comment]
If the only modification I make to an activity, the StatusDescription shows up, sample:

https://github.com/christophwille/OTel-de-Wille/blob/a1a3df28cf432d1d435a73eedaa01ce19ebded45/aspnet-aspiredashboard/Program.cs#L75-L89

![image](https://github.com/dotnet/aspire/assets/344208/f46439ab-89cb-41ca-bbaf-af53c9f9fa51)

However, in a more convoluted real-life implementation, it doesn't. I have to dig deeper whether this really is Dashboard or Activity or OpenTelemetry behavior. Roughly the code:

```
using var activity = SampleConfig.ActivitySource.StartActivity("SampleActivity");
activity?.SetTag("enduser.id", "my value");

// some http call

if (!response.IsSuccessStatusCode)
{
  activity?.SetStatus(ActivityStatusCode.Error, "I failed here");
}
```

I need to build a pared-down sample of the actual code.

**Comment by JamesNK** [comment]
Do you see your activity at all? You need to explicitly tell OpenTelemetry that you want it to listen to an activity.

**Comment by christophwille** [comment]
https://github.com/christophwille/OTel-de-Wille/blob/8f28cc1b4aec77354ba0938dd0e7a0bb57ce94ec/aspnet-aspiredashboard/Program.cs#L115

I tried to rebuild the code that is used in the production application. However, although similar, in this case it works as expected:
![image](https://github.com/dotnet/aspire/assets/344208/aae25fa3-0035-4e2d-92b0-a36656a34a08)

Maybe, just maybe, up in the call chain there is somewhere a SetStatus for Error but without message. But it most likely is the code and not the Dashboard then.
