### ISSUE TITLE
[WebToolsE2E][Aspire] Clicking the link on the Metrics page cannot jump to the corresponding page.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#2356]
**REGRESSION INFO**: Worked on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34621.221.main]
3. Install Aspire 8.0 P4 [Version 8.0.0-preview.4.24118.7]
4. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > .NET 8.0 > Create
2. Build and F5
3. Go to Metrics page, select any project in the resource drop-down box

**ACTUAL**
Clicking the link on the Metrics page cannot jump to the corresponding page.
![Metrics1](https://github.com/dotnet/aspire/assets/109339894/84692375-d39b-48a0-a0cf-2750a1768180)

**EXPECTED**
 Should jump to the corresponding page.
![Metrics2](https://github.com/dotnet/aspire/assets/109339894/0df690b6-af29-4a40-9faa-6ded1e9249f0)

**Comment by JamesNK** [comment]
Hi, I fixed this yesterday. It will be fixed in P4.

**Comment by v-reinawang** [comment]
Verify on Aspire.ProjectTemplates.8.0.0-preview.4.24122.8, this issue has been fixed.
