### ISSUE TITLE
[AzureTools][Aspire] No response after clicking drop down icon for first select box again in the opened "Add filter" window

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#2359]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10 Preview 2 from [34618.16.main]
**Aspire Version**: 8.0.0-preview.4.24118.7
Apply NuGet Feeds

**REPRO STEPS:**

1. Create a Aspire starter project with "Use Redis for caching (requires Docker) checked.
2. F5
3. In the dashboard, click "Structured".
4. Click the "Filter" icon -> Click drop down icon for first select box -> The drop down list expand. 
    ![image](https://github.com/dotnet/aspire/assets/62053665/bb37182d-21ae-43fc-ab31-fbd8cfa6bbda)
5. Click drop down icon for first select box again.
    ![image](https://github.com/dotnet/aspire/assets/62053665/4fa2c4e7-6bf0-4b8d-9a81-91601ade1033)

**Expect:**
Drop down list hidden.

**Actual:**
1. There are two filters in the opened page of step 3 and I'm confused by some options.
    ![image](https://github.com/dotnet/aspire/assets/62053665/fbb305a1-5f6e-48fd-a6cc-89c320627722)
2. No response after clicking drop down icon for first select box again.

**Comment by kvenkatrajan** [comment]
Maybe consider changing verbiage on Right side filter to Advanced/Custom

**Comment by adamint** [comment]
@v-mengwe I'm a little unclear on the repro steps. I cannot reproduce when performing the following steps:
1. Click the icon in your repro step 4
2. Click the select in repro step 5
3. Click the X in repro step 5
4.Repeat steps 1-2

**Comment by v-mengwe** [comment]
Please get the details form the animation below:
Actual:
![Actual](https://github.com/dotnet/aspire/assets/62053665/a29bf766-5b7f-4f6a-871e-3dce829ffc7c)
Expect:
![Expect](https://github.com/dotnet/aspire/assets/62053665/338e7c00-9a99-4abb-964c-2f05d950327f)

**Comment by adamint** [comment]
@v-mengwe I confirmed this is an issue with the fluentui-blazor library, not directly Aspire code. I filed https://github.com/microsoft/fluentui-blazor/issues/1693, so this can be closed.

cc @vnbaaij

**Comment by v-mengwe** [comment]
Got it, Thanks for your updates.
