### ISSUE TITLE
[WebToolsE2E] Unable to use builder.AddAzureKeyVaultSecrets to add and retrieve secret from Azure Key Vault

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#2362]
**REGRESSION INFO**: Reproduces with latest-released Aspire 8.0 P3, so not a regression in 8.0 P4

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 (includes .NET SDK 8.0.200 and .NET workload Aspire 8.0.0-preview.3.24105.21)

**REPRO STEPS**
1. New Project > ASP.NET Core Empty template > name it 'EmptyApp5withAspire' > .NET 8.0 > check 'Enlist in Aspire orchestration'> Create 
2. Build and run > works fine
3. Right-click EmptyApp5withAspire > Add Aspire Component > Aspire.Azure.Security.KeyVault version 8.0.0-preview.3.24105.21 (matching the version of Aspire that's installed)
4. Open appsettings.json of EmptyApp5withAspire project, add the following section with the VaultUri
```
  "ConnectionStrings": {
    "secretConnectionName": "https://<vault_account_name>.vault.azure.net/"
  },
```
5. Open Program.cs of EmptyApp5withAspire project, add the following code after the line `builder.AddServiceDefaults();`
```
builder.AddAzureKeyVaultSecrets("secretConnectionName", static settings =>
{
    settings.Credential = new VisualStudioCredential();
});
```
6. In Program.cs of EmptyApp5withAspire project, replace the 'Hello world' line with the following code
```
//app.MapGet("/", () => "Hello World!");
string? _mySecret = builder.Configuration["myAppSetting"];

var result = string.IsNullOrEmpty(_mySecret) ? "Null" : _mySecret;
app.MapGet("/", async context =>
{
    await context.Response.WriteAsync($"Secret is {result}");
});
```
7. Build and run

**ACTUAL**
Dashboard works fine but unable to get the secret from the key vault. It shows 'Secret is Null'

![image](https://github.com/dotnet/aspire/assets/8246794/7f107a7e-f46d-475e-9ead-3ae138b40371)

**Workaround**:
1. In launchSettings.json of EmptyApp5withAspire project, in the http profile, add the following as environment variables.
```
        "VaultUri": "https://<vault_account_name>.vault.azure.net/",
        "AZURE_USERNAME": "<azure_user_name>@microsoft.com"
```
2. Open Program.cs of EmptyApp5withAspire project, add the following code after the line `builder.AddServiceDefaults();` to load the VaultUri from the environment variable and pass that to builder.Configuration
```
var keyVaultEndpoint = new Uri(Environment.GetEnvironmentVariable("VaultUri"));
builder.Configuration.AddAzureKeyVault(keyVaultEndpoint, new VisualStudioCredential());
```

**EXPECTED**
`builder.AddAzureKeyVaultSecrets("secretConnectionName", ..)` call should work correctly

**Comment by davidfowl** [comment]
This isn't a regression right?

**Comment by balachir** [comment]
No, it's not. I can reproduce it with P3.

**Comment by eerhardt** [comment]
`AddAzureKeyVaultSecrets` XML docs say:

> Registers <see cref="SecretClient"/> as a singleton in the services provided by the builder.
> Enables retries, corresponding health check, logging and telemetry.

This method just adds a `SecretClient` object to DI, which you would need to grab out of DI and use to get the secrets on demand.

If you want the Configuration to be populated with _all_ the secrets from the KeyVault. Then you should use:

`builder.Configuration.AddKeyVaultSecrets("secretConnectionName");`

Maybe one change we can make here is to rename `builder.AddAzureKeyVaultSecrets("")` => `builder.AddAzureKeyVaultSecretClient("")`.

Thoughts?

**Comment by eerhardt** [comment]
@sebastienros - I think this can be fixed at the same time as https://github.com/dotnet/aspire/issues/1510. They both should be fixed by the same rename.

**Comment by sebastienros** [comment]
Just looked into this one and I see you are suggesting to update the name, I had done it already but with `AddAzureKeyVaultClient`, so dropping the "Secrets" part which I didn't find meaningful in that case. Are we good with that?

**Comment by eerhardt** [comment]
Thanks @sebastienros. I believe this issue can now be closed with https://github.com/dotnet/aspire/pull/2630 being completed.
