### ISSUE TITLE
Dapr --app-port argument not consistently passed to the dapr executable

### ISSUE THREAD

**Issue by darraghjones** [dotnet/aspire#2367]
I see the following error in the dapr logs because the app-port argument is not passed to the dapr executable.

time="2024-02-23T00:06:55.4110487Z" level=warning msg="App channel is not initialized. Did you configure an app-port?" app_id=web instance=DESKTOP-SE6C36R scope=dapr.runtime.channels type=log ver=1.12.5

You can see this happening below running the AspireWithDapr sample 

<img width="1830" alt="image" src="https://github.com/dotnet/aspire/assets/431192/da5743e0-a767-4adc-9f4e-2c9feb5f7b73">

The app-port argument is being passed to the API service dapr instance, but I couldn't see any reason why it would behave differently.

**Comment by darraghjones** [comment]
Ah, it seems this has to do with the web running on https. If i change this to http, the app-port argument is passed along to dapr.

**Comment by davidfowl** [comment]
Not sure what we can do about this

**Comment by davidfowl** [comment]
Allowed specifying the endpoint to use for the sidecar resource. This determines the app port. 

Fixed in https://github.com/dotnet/aspire/pull/3184
