### ISSUE TITLE
Padding required for Aspire content

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2371]
Aspire doesn't have any padding around content in the page. UI feels like it needs some more space

Page title and top content bar:
![image](https://github.com/dotnet/aspire/assets/303201/85b1135d-a977-410e-b944-5bc6fe1fe660)

Should the page title be smaller or a different font? More padding to top and left?

Footer:
![image](https://github.com/dotnet/aspire/assets/303201/994142d6-6529-4b54-bdae-ead7658c0ec1)

Visible on structured logs and traces. Needs padding.

**Comment by JamesNK** [comment]
cc @tlmii

**Comment by tlmii** [comment]
Definitely agree on the footer. Meant to go back and do that after the other layout changes. I'll take care of that.

I don't really feel that the layout is too dense at the top. I'll also caution that it looks weird when the grid lines don't go all the way to the edge, so any global padding may be off the table. I'll play around with the content header areas and see what might work.
