### ISSUE TITLE
Multiple csproj with same name only generate 1 metadata instance

### ISSUE THREAD

**Issue by NicoVermeir** [dotnet/aspire#2377]
We have two projects with the same name, but different namespaces in our solution. (two microservices with same structure)
This is a redacted snippet of the csproj of the apphost

```
  <ItemGroup>
    <ProjectReference Include="..\Certificates\src\Presentation.API\Presentation.API.csproj" />
    <ProjectReference Include="..\Configuration\src\Presentation.API\Presentation.API.csproj" />
    <ProjectReference Include="..\Configuration\src\Presentation.UI\Presentation.UI\Presentation.UI.csproj" />
  </ItemGroup>
```

When building this the sourcegenerator only generates 1 project metadata for Presentation_API

![image](https://github.com/dotnet/aspire/assets/3177418/2bce3040-181c-42ff-bd9f-217f689b1c81)

Expected result: having an instance for all projects generated in the metadata.

I would expect this to be fixed automatically with #2036 but is there a timeline on that?
Meanwhile: is the only workaround for now to use hardcoded paths in the Aspire builder?

We are currently on preview 3 of Aspire, this was working just fine in preview 2

**Comment by eerhardt** [comment]
You can use 

```xml
    <ProjectReference Include="..\Certificates\src\Presentation.API\Presentation.API.csproj" AspireProjectMetadataTypeName="CertificatesAPI" />
    <ProjectReference Include="..\Configuration\src\Presentation.API\Presentation.API.csproj" AspireProjectMetadataTypeName="ConfigurationAPI" />
```

And it will generate 2 classes, one for the Certificates and one for the Configuration.
