### ISSUE TITLE
PublishAsAzurePostgresFlexibleServer shouldn't require a user and password

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#2389]
```C#
var usr = builder.AddParameter("usr");
var pwd = builder.AddParameter("pwd", secret: true);

var db1 = builder.AddPostgres("pg1")
                 .PublishAsAzurePostgresFlexibleServer(usr, pwd)
                 .AddDatabase("db1");
```

https://github.com/dotnet/aspire/blob/98950280f176b5908fc985fe441d9d7a6ae84ae7/src/Aspire.Hosting.Azure/Extensions/AzurePostgresExtensions.cs#L24

That method requires a parameter for the user name and password. We shouldn't require this, and instead just generate one if the user doesn't specify it. That way users can easily provision a PostgreSQL db without getting prompted during `azd up`.

@mitchdenny @davidfowl

**Comment by eerhardt** [comment]
@mitchdenny - I assigned this to myself since @davidfowl assigned me https://github.com/dotnet/aspire/issues/2403, which is basically the generalized (for all resources) version of this.

**Comment by mitchdenny** [comment]
@eerhardt I think I found a bug with this. It appears that when you do this:

```csharp
builder.AddPostgres("pgsql").PublishAsAzurePostgresFlexibleServer(usernameParameter, passwordParameter);
```

The `"inputs":` field is still generated. It looks like it is because the old InputAnnotation isn't removed.

**Comment by eerhardt** [comment]
> The "inputs": field is still generated.

Correct. That was intentional. See https://github.com/dotnet/aspire/pull/2627#discussion_r1511794605
