### ISSUE TITLE
Accessing named Key Vault secrets pulled by Aspire host

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspire#2398]
What I take from the discussion [here](https://github.com/dotnet/aspire/discussions/1579) and in the documentation is that one can call their secrets "connectionstrings-<name>", put a Key Vault reference in the appsettings.json file in the AppHost for a key "<name>" and then simply reference that to a component as the name value so the secret from Key Vault is resolved downstream.

For example:
```json
//appsettings.json
{
  "ConnectionStrings": {
    "secrets": "VaultUri=https://<vaultName>.vault.azure.net/",
    "cosmosdb": "@Microsoft.KeyVault(SecretUri=https://<vaultName>.vault.azure.net/secrets/connectionstrings-cosmosdb/)"
  }
}
```

```cs
//Program.cs
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");
var keyVault = builder.AddAzureKeyVault("secrets");
var cosmosdb = builder.AddAzureCosmosDB("cosmosdb");

builder.AddProject<Projects.MyEdventureLabWeb>("webfrontend")
    .WithReference(cache)
    .WithReference(cosmosdb)
    .WithReference(keyVault);

builder.Build().Run();
```

And in my application's Program.cs, I need only register the same connection name for my component:
```cs
var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();
builder.AddRedisOutputCache("cache");
builder.AddKeyedAzureKeyVaultSecrets("secrets");
builder.AddAzureCosmosDB("cosmosdb");
```

I would like to request that there be a way to pass arbitrary connection strings through the AppHost as well beyond through the registered resources. For example, say I want to access a SendGrid API key - there's not (yet?) a SendGrid component in Aspire, but I've got the API key saved to another Key Vault secret. I'd like to be able to do something like the following in my AppHost Program.cs:

```cs
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");
var keyVault = builder.AddAzureKeyVault("secrets");
var sendGridApiKey = builder.AddAzureKeyVaultSecret("sendgrid"); //Added this
var cosmosdb = builder.AddAzureCosmosDB("cosmosdb");

builder.AddProject<Projects.MyEdventureLabWeb>("webfrontend")
    .WithReference(cache)
    .WithReference(cosmosdb)
    .WithReference(keyVault)
    .WithReference(sendGridApiKey); //Added this

builder.Build().Run();

```

And pair this with the Key Vault reference in the AppHost appsettings.json:
```json
{
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "secrets": "VaultUri=https://<vaultName>.vault.azure.net/",
    "cosmosdb": "@Microsoft.KeyVault(SecretUri=https://<vaultName>.vault.azure.net/secrets/connectionstrings-cosmosdb/)",
    "sendgrid": "@Microsoft.Keyvault(SecretUri=https://<vaultName>.vault.azure.net/secrets/connectionstrings-sendgrid/)",
  }
}
```

And then ideally, in Program.cs in my application then:
```cs
var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();
builder.AddRedisOutputCache("cache");
builder.AddAzureKeyVaultSecrets("secrets");
builder.AddAzureCosmosDB("cosmosdb");

//Access from the configuration - ideally, this should yield the Key Vault reference, then automatically follow it via the injected Key Vault secret client to retrieve whenever the `SendGridClient` is first injected.

builder.Services.AddSingleton(new SendGridClient(builder.Configuration.GetConnectionString("sendgrid"));
```

Enabling something like this would ensure that I can access the connection strings via the Key Vault client (which is otherwise already available to other resources) and let me easily register other DI services that aren't part of the Aspire universe just yet.

Thanks for the consideration!

**Comment by davidfowl** [comment]
> I would like to request that there be a way to pass arbitrary connection strings through the AppHost as well beyond through the registered resources. 

In the next preview, it'll be possible to just add a connection string as a resource via `builder.AddConnectionString`.

> And pair this with the Key Vault reference in the AppHost appsettings.json:

I saw your other issue with this keyvault syntax in configuration but I think if we do something like this it won't be expressed this way. It would be expressed in C#. Today there's no real support for doing anything interesting with keyvault in the apphost.

Here's what I think we would do:

### Scenario 1: Pushing connection strings into keyvault.

```C#
var builder = DistributedApplication.CreateBuilder();

var db = builder.AddAzureCosmos("cosmos")
                .AddDatabase("db");

var kv = builder.AddAzureKeyVault("kv")
                         .AddSecret(db); // Add the secret to keyvault called connectionstrings--cosmos

builder.AddProject<Projects.Api>("api").WithReference(kv); // Only need a keyvault reference
```

### Scenario 2: Referencing Secrets from keyvault

```C#
var builder = DistributedApplication.CreateBuilder();

var kv = builder.AddAzureKeyVault("kv");
var cosmos = kv.GetConnectionString("cosmos"); // Get a secret called connectionstrings--cosmos

builder.AddProject<Projects.Api>("api")
           .WithReference(cosmos); // Push the connection string from keyvault into an environment variable
```

In scenario 2, the application doesn't have a reference to keyvault, the compute environment will pull from keyvault and push it into the application.


### Scenario 3: Referencing Secrets from KeyVault already provisioned

```C#
var builder = DistributedApplication.CreateBuilder();

var kv = builder.AddAzureKeyVault("kv");

builder.AddProject<Projects.Api>("api")
           .WithReference(kv);
```

This is the same as scenario 1 and it's what you can do today. The application code needs to use the right naming convention for connection strings to get loaded into the right section (which is what was mentioned [here](https://github.com/dotnet/aspire/discussions/1579))

**Comment by WhitWaldo** [comment]
I'm at a loss for when I'd ever use scenario 1 - I've never found a good reason to keep secrets in my application code, so why would the application have the values that necessitated storing in the Key Vault to set them in the first place? Given, I can entirely understand the downstream application post-registration generating secrets worth saving via the SecretsClient, but that's well into runtime and not just at application start.

That said, I think Scenario 2 is precisely what I'm looking for. Would the syntax in appsettings be the same as today for adding the Key Vault reference, e.g. 
```json
{
  "ConnectionStrings":  {
    "kv": "VaultUri=https://<myVault>vaults.azure.net/"
  }
}
```

Finally, is there any way to configure the Azure.Identity used? It's my understanding this uses a DefaultAzureCredential, but I'd ideally like to make it a ChainedTokenCredential populated with a ManagedIdentityCredential and a VisualStudioCredential, so I can directly specify the UAI it should use (in prod) with the fallback to the VS credential locally.

Thank you!

**Comment by davidfowl** [comment]
> I'm at a loss for when I'd ever use scenario 1 - I've never found a good reason to keep secrets in my application code, so why would the application have the values that necessitated storing in the Key Vault to set them in the first place? 

Not sure what you mean by the application code would have secrets. Think about the apphost as modeling the application requirements for deployed environments. You're stating to the system that you want to use a cosmosdb and that you want to store the connection string in a keyvault. When this application is deployed, that process will be automated by putting secrets into the keyvault and making sure the application can access them at runtime. This normally and exercise left to the reader.

> That said, I think Scenario 2 is precisely what I'm looking for. Would the syntax in appsettings be the same as today for adding the Key Vault reference, e.g.

What's missing for me from seeing your scenario are 2 things:

1. Are you pre-populating a keyvault for secrets for developing?
2. Are you using keyvault in your application?
3. Are you using aspire for deployment?

Based on your answers, it seems like you'd want 1 or 2.

> Finally, is there any way to configure the Azure.Identity used? It's my understanding this uses a DefaultAzureCredential, but I'd ideally like to make it a ChainedTokenCredential populated with a ManagedIdentityCredential and a VisualStudioCredential, so I can directly specify the UAI it should use (in prod) with the fallback to the VS credential locally.

I'm assuming you mean the API used in the application code, not in the apphost right? If so yes, there are overloads of various methods to enable this:

```C#
builder.Configuration.AddKeyVaultSecrets("kv", settings =>
{
    settings.Credential = new ChainedTokenCredential();
});
```

**Comment by WhitWaldo** [comment]
I follow your first paragraph right up until "that process will be automated by putting secrets into the keyvault". Is the idea that in the long-run, none of the resources actually exist in the target environment, so you need to deploy the instances (e.g. via Bicep), collect their connection strings and that's where you're getting them from to save into the vault? If that's the case, neat, but I guess I'd hope that there's a fallback scenario that lets me simply specify some existing resources. Again, I typically will already have a Key Vault deployed and containing non-Azure secrets that were populated either manually or by another process, so I'd generally prefer the ability given in Scenario 2 to retrieve those secrets and use them in my applications from existing resources.

To your questions:
1. Yes, I typically already have a Key Vault to which Bicep has written secrets from prior deployments and to which I've manually saved secrets (e.g. API keys for non-Azure, third-party resources that couldn't be deployed from Bicep).
2. Yes, all secrets and certificates are pulled from Key Vault.
3. Yes, I'm building small scale app to trial the experience before migrating a much more complex application. I'm targeting ACA right now, though at some point I may have to switch to Kubernetes.

I think a lightbulb just went off - correct me if I've got it wrong: the AppHost only registers components so application code can use it (e.g. service discovery) and doesn't itself do any authentication. All authentication happens in the application code, so if I pass a Cosmos DB reference into multiple services from the AppHost, I still have to pull the connection string for Cosmos in each application so it can actually authenticate to it (meaning I can use my credential there as I want). Is that right?

**Comment by davidfowl** [comment]
> I follow your first paragraph right up until "that process will be automated by putting secrets into the keyvault". Is the idea that in the long-run, none of the resources actually exist in the target environment, so you need to deploy the instances (e.g. via Bicep), collect their connection strings and that's where you're getting them from to save into the vault?

That's right. If you choose to deploy with aspire with [azd](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth), then it can provision infrastructure for you and populate configuration as well.

This means creating the keyvault resource and setting up default role assignments.

> I think a lightbulb just went off - correct me if I've got it wrong: the AppHost only registers components so application code can use it (e.g. service discovery) and doesn't itself do any authentication. All authentication happens in the application code, so if I pass a Cosmos DB reference into multiple services from the AppHost, I still have to pull the connection string for Cosmos in each application so it can actually authenticate to it (meaning I can use my credential there as I want). Is that right?

That's right, the "reference" is just configuration. The apphost's job is to model the application infrastructure and provide configuration to the applications. 

> I still have to pull the connection string for Cosmos in each application so it can actually authenticate to it (meaning I can use my credential there as I want)

This is what "aspire components" do. They are wrappers over the underlying SDK that pull information and glue other libraries together to make them more usable in real world scenarios (wiring up telemetry, configuration, DI, health checks etc).

So your scenario is really 3 and to make it work you just need wire up keyvault on both sides.

**Comment by WhitWaldo** [comment]
I follow - this all makes a lot more sense now. I guess I'd just ask that future iterations consider repurposing existing Azure resources. I just re-deployed a website with `azd` and while it runs all right locally, it needed additional stuff that didn't make it into the package (e.g. a Front Door instance, the DNS zone) and as I was accessing a Key Vault it didn't deploy with, the container app initially failed to launch because it was trying to use its own user-assigned managed identity to authenticate and, of course, my Key Vault RBAC wasn't set up to allow it.

**Comment by davidfowl** [comment]
> I guess I'd just ask that future iterations consider repurposing existing Azure resources.

Yes, this is a big-ticket item. In preview 4 it's possible to reference any connection string using a new method. This allows you to specify connection information in dev via configuration in the app host (user secrets) and then specify it also when deploying (you can stick the keyvault URL in there).

>  just re-deployed a website with azd and while it runs all right locally, it needed additional stuff that didn't make it into the package (e.g. a Front Door instance, the DNS zone) and as I was accessing a Key Vault it didn't deploy with, the container app initially failed to launch because it was trying to use its own user-assigned managed identity to authenticate and, of course, my Key Vault RBAC wasn't set up to allow it.

Remember we're still in preview 😄, lots of things don't work. That said, we've made some big strides in the next preview that allow you to weave any piece of bicep and as a result, any azure resource into the apphost. That means you'll be able to model things you couldn't before and you don't need to wait for us to add a C# wrapper for it.

We're still missing the ability to easily set the container app properties from the app host. You can run [azd infra synth](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?tabs=windows#generate-bicep-from-net-aspire-app-model) as the ultimate escape hatch. Keep in mind the apphost won't be in sync if you make changes though.

This stuff is brand new and still baking (but it's exciting), bare with us as we try to figure out how much we can support.

**Comment by WhitWaldo** [comment]
Our back and forth today has been _huge_ in understanding both what Aspire is and is striving to do, so thank you very much for taking the time to respond to me. 

I think I now properly understand Aspire as being a leap forward in deploying containers and resource instances as one uniform collection without requiring all the plumbing we've traditionally needed (writing your own Bicep, writing complex build and publish scripts, eliminating a lot of the manual documentation tracking interdependencies between microservices, etc).

But it now makes a lot more sense to me why this pairs really nicely with Dapr - it simplifies their deployment (which assumes strictly existing resources) and (will eventually) support new and existing resources, greatly simplifying ongoing maintenance of it all. 

Very exciting! Again - huge thank you!

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/aspire/issues/2587
