### ISSUE TITLE
Setting webproject to https locally, blazor websocket not upgrading

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2406]
### Discussed in https://github.com/dotnet/aspire/discussions/2266

<div type='discussions-op-text'>

<sup>Originally posted by **mip1983** February 16, 2024</sup>
Hi there,

In my aspire app I set my Blazor Web project to have an https endpoint (for debugging against my oidc server) i.e.

```
builder.AddProject<Projects.yourprojecthere_Web>("web")
	.WithHttpsEndpoint(hostPort: 7167)

```

This seems to generally work fine, except with Blazor server components where it's establishing a websocket connection, the response is 200 rather than 101. While it operates, I get a few signalR dropouts this way and would rather it got the full fat websocket connection, which seems to work better if I switch back to regular http.

![image](https://github.com/dotnet/aspire/assets/2116108/fcc1bfa6-f7c1-4bab-b7f3-4b518dfbbb6f)

Is there any additional config I can add to allow websockets to work with https locally?

If it helps, this is the more detailed error I get with 'just my code' disabled:

> System.Net.WebSockets.WebSocketException: 'The remote party closed the WebSocket connection without completing the close handshake.'
> 
> Win32Exception: The specified data could not be decrypted.
> IOException: The decryption operation failed, see inner exception.
> ConnectionAbortedException: The HTTP/2 connection faulted.
> IOException: The request stream was aborted.

</div>

**Comment by mitchdenny** [comment]
I haven't' been able to repro this. Did you @davidfowl ?

**Comment by davidfowl** [comment]
Nope.
