### ISSUE TITLE
Resource server protocol changes

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2415]
As part of the work to support custom resources in the dashboard (https://github.com/dotnet/aspire/pull/2390) there are several improvements that we should consider making to the resource server API:
 
- [ ] #5065
- [x] Make the list of endpoints/urls more general purpose and support named urls. For e.g. we want to be able to navigate to the portal for azure resources.
- [x] Feedback here about the service and endpoints split (https://github.com/dotnet/aspire/pull/2413#issue-2153052580) cc @JamesNK 
- [ ] Model replicas explicitly. Today we have a flat list of resources and replicas are found based on naming. We can make this explicit.
- [x] Allow setting both the state and the state icon or icon type (https://github.com/dotnet/aspire/pull/3210)
- [x] #4849

**Comment by kvenkatrajan** [comment]
@davidfowl , I am not sure I understand this request : 

> Make the list of endpoints/urls more general purpose and support named urls. For e.g. we want to be able to navigate to the portal for azure resources.

Can you give example of variations of urls for local/azure resources you would expect? 

The other 2 are clear - Thanks!

**Comment by JamesNK** [comment]
What about adding references to resources? i.e. what resources is a resource referencing. We can show that in the resource detail pane.

```cs
builder.AddProject<Projects.MyFrontend>("frontend")
       .WithReference(basketService)
       .WithReference(catalogService.GetEndpoint("http"));
```

In the example above, the `frontend` resource would have two references. A reference would have:

* Resource name
* Endpoint name
* Value - URI string?

You could try to reverse engineer this by looking at environment variables, but it would be a pain in the butt. Much easier to model it explicitly.

**Comment by drewnoakes** [comment]
Another potential addition is window size for logs. The server can limit the amount of history it sends easily enough, and I believe ACA does this today. The dashboard client currently appends logs without rolling old messages out of the window, which will eat memory indefinitely. We should synchronise the window size between client and server, so the server doesn't send data the client won't display, and so the client can roll old messages out. Perhaps the client specified the window size in the request.

**Comment by davidfowl** [comment]
I'm going to punt this to the backlog for now.

**Comment by davidfowl** [comment]
If anyone has cycles to work on this, I would like the status change for p5 😄

**Comment by eerhardt** [comment]
@drewnoakes - this issue is marked as "Medium" priority in 8.2. Since it affects external resources from following security best practices, should this be moved higher and commited for 8.2?

**Comment by drewnoakes** [comment]
@eerhardt I'm not sure what you mean by

> affects external resources from following security best practices

Can you provide more context please?

There are two pending proposed changes left on this issue. One relates to richer modelling of replicas, the other to allowing properties to be marked as secret so that they're treated the same way as environment variables in the UI (hidden by default).

**Comment by eerhardt** [comment]
> @eerhardt I'm not sure what you mean by
> 
> > affects external resources from following security best practices
> 
> Can you provide more context please?
> 
> There are two pending proposed changes left on this issue. One relates to richer modelling of replicas, the other to allowing properties to be marked as secret so that they're treated the same way as environment variables in the UI (hidden by default).

"allowing properties to be marked as secret" is exactly what I'm talking about. Custom (i.e. "external") resources can't mark properties as secret if they need to.

**Comment by drewnoakes** [comment]
Thanks for clarifying. I've pulled it out into https://github.com/dotnet/aspire/issues/5065, and targeted it at 8.2 with high priority.

@adamint the other item above is to model replicas explicitly. You have PR https://github.com/dotnet/aspire/pull/4908 open for this now, and there are no protocol changes there. Do you anticipate us needing proto changes for that in future, or is that unnecessary. If unnecessary, then we can close this out.

**Comment by leslierichardson95** [comment]
Closing this since all issues have either been resolved or have been made into their own work item.
