### ISSUE TITLE
[WebToolsE2E] Run Aspire Starter Application for the first time, the dashboard shows some errors saying UnableToConnect

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#2430]
**REGRESSION INFO**: TBD

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 2 build main-34626.03 (includes .NET SDK 8.0.300-preview and .NET workload Aspire 8.0.0-preview.3.24105.21)
3. Install Aspire P4 build 8.0.0-preview.4.24125.5 + Apply feeds

**REPRO STEPS**
1. New Project > Aspire Starter Application > name it 'AspireStarterApp1' > .NET 8.0 > Create 
2. Ctrl+F5

**ACTUAL**
Dashboard shows some errors for webfrontend when run for the first time

![image](https://github.com/dotnet/aspire/assets/8246794/c4dcbec4-4101-4862-8138-be148e37e27a)

![image](https://github.com/dotnet/aspire/assets/8246794/bd918a64-8e17-4d32-baa0-a63ba0a34f56)

**EXPECTED**
Dashboard doesn't show any errors when we run the application

**Comment by balachir** [comment]
Applied preview 4 milestone for consideration. Please triage and move it out if needed

**Comment by davidfowl** [comment]
Is this a clean machine?

**Comment by davidfowl** [comment]
Yep. When the redis image isn't pulled yet, there will be errors. @karolz-ms can you comment on whether we can improve DCP in the future WRT not allowing connections to go through until the image has been pulled?

**Comment by davidfowl** [comment]
Oh wait karol replied here https://github.com/dotnet/aspire/issues/1695#issuecomment-1912786435. 

Yes, we can close as by design. We'll improve this with health checks in the future.
