### ISSUE TITLE
Rename eShopLite in playground to AspireShop

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2439]
It's not based on [eShop](https://github.com/dotnet/eshop) and the name currently just causes confusion.

**Comment by eerhardt** [comment]
It's named "TestShop" now:

https://github.com/dotnet/aspire/blob/25e20449fb1f86706fa1e4b9e80ead44047cbc67/playground/TestShop/MyFrontend/Components/Pages/Home.razor#L9

I don't think we need to rename it again.

**Comment by DamianEdwards** [comment]
Oh perfect :)
