### ISSUE TITLE
Support build args in docker file resources

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/aspire#2441]
It's commonplace to provide `--build-arg` when building container images with `docker build`. In fact, certain scenarios require it, such as Node.js apps that expect certain env vars to be available when they build. Aspire will need to expose an API that allows developers to express that their container images are built with specific environment variables, provided as `--build-arg`.

This is related to https://github.com/Azure/azure-dev/issues/3432

See https://docs.docker.com/reference/cli/docker/image/build/#build-arg

**Comment by DamianEdwards** [comment]
I assume this means new overloads of the `PublishAsDockerFile` method, something like the following perhaps?

```csharp
public static IResourceBuilder<NodeAppResource> PublishAsDockerFile(
    this IResourceBuilder<NodeAppResource>,
    IEnumerable<DockerBuildArg> buildArgs);

public class DockerBuildArg
{
    public DockerBuildArg(string name);
    public DockerBuildArg(string name, string value);

    public required string Name { get; set; }
    // Value is optional, if omitted it means it will be flowed from the environment
    public string string? Value { get; set; }
}
```

Consumption would be something like:

```csharp
builder.AddNodeApp("apiapp", "../apiapp/app.js")
    .PublishAsDockerFile([new("HTTP_PROXY"), new("FTP_PROXY", "http://40.50.60.5:4567)")]);
```

**Comment by davidfowl** [comment]
Maybe more than string/string we need to store reference to other resources?

**Comment by DamianEdwards** [comment]
> Maybe more than string/string we need to store reference to other resources?

Can you elaborate on the scenarios? I admit I'm not super clear on them here, other than Docker supports build args so we should.

**Comment by IEvangelist** [comment]
To my knowledge, all we'd need is env vars. I'm curious too, what scenario would we need anything more than string/string pairs?
