### ISSUE TITLE
[WebToolsE2E][Aspire] Running "azd init" to initialize aspire-samples/DatabaseContainers solution fails with error: "Unsupported resource type: mysql.database.v0".

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#2445]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [ includes Aspire 8.0.0-preview.3.24105.21 ]
3. Install Docker Desktop for Windows
4. Install azd [1.6.1]

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Open samples\DatabaseContainers.sln
3. Build
4. Right-click solution > Open Folder in File Explorer. In the opened folder, click any place > Open in Terminal
5. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app > type a new environment name, press enter

**ACTUAL:**
ERROR: unsupported resource type: mysql.database.v0
![image](https://github.com/dotnet/aspire-samples/assets/71361488/3ec7dfa8-02bd-4520-8db4-bce0bbdca9fe)

**EXPECTED**
Running 'azd init' successfully.

**Comment by DamianEdwards** [comment]
This is by design right @davidfowl? Or are we planning to have azd support mapping MySql to something in Azure?

**Comment by davidfowl** [comment]
This by design for preview 3 yes

**Comment by v-sherryfan** [comment]
Not repro on latest `preview.5` branch using VS 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12]
