### ISSUE TITLE
[WebToolsE2E][Aspire] When deploying aspire-samples/VolumeMount solution, running 'azd up' fails with error: "AccountNameInvalid: Storagexxx is not a valid storage account name. Storage account names must use numbers and lower-case letters only."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#2446]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [ includes Aspire 8.0.0-preview.3.24105.21 ]
3. Install Docker Desktop for Windows
4. Install azd [1.6.1]

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Open samples\VolumeMount.sln
3. Build
4. Set the sqlpassword key in the User Secrets store of the VolumeMount.AppHost project using the dotnet user-secrets command in the AppHost project directory: `dotnet user-secrets set sqlpassword <password>`
5. Right-click solution > Open Folder in File Explorer. In the opened folder, click any place > Open in Terminal
6. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app > type a new environment name, press enter
7. Running 'azd up'

**ACTUAL:**
![image](https://github.com/dotnet/aspire-samples/assets/71361488/ca2a538a-732a-472a-b418-1b0d34b198f2)

**Workaround**

1. If I manually change 'Storage' to lower-case 'storage' in Program.cs and try again, it works fine.

**EXPECTED**
Running 'azd up' successfully.

**Comment by danmoseley** [comment]
@mitchdenny can you help route

**Comment by mitchdenny** [comment]
This is app model. I've got it solved in the new CDK based resources.

**Comment by mitchdenny** [comment]
This is fixed in preview 5 now as part of the CDK integration.

**Comment by v-sherryfan** [comment]
Not repro on latest `preview.5` branch using VS 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12]
