### ISSUE TITLE
Keyboard shortcuts for non-latin keyboards

### ISSUE THREAD

**Issue by tlmii** [dotnet/aspire#2468]
What happens to shortcuts if you have non-latin keyboard setup? Do people with those keyboards know they need to go into latin mode for `r` for example?

Should the ToLower's here have `InvariantCulture`? I'm surprised culture code analysis isn't complaining about it.

_Originally posted by @JamesNK in https://github.com/dotnet/aspire/pull/2466#discussion_r1503753161_

**Comment by JamesNK** [comment]
If keyboard shortcuts are calculated in JS then we should consider this problem when detecting keys in JS instead of .NET.

**Comment by JamesNK** [comment]
> Keyboard shortcuts are not calculated in JS, only the keypresses are detected in JS and then passed back to .NET.

I know, but that will likely change because of https://github.com/dotnet/aspire/issues/2469

**Comment by leslierichardson95** [comment]
Closing because this is not an issue after investigation
