### ISSUE TITLE
Connection String Name In Aspire EntityFrameworkCore

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspire#2471]
When I Give It Connection String Name Like This
It Stays The Same Connection String Or They Both DbContexts Go For The Same Database Like This

As You See Here In The Tables

![image](https://github.com/dotnet/aspire/assets/104096256/5b67280d-9bfc-48e4-97e4-e902ec30ff3e)

![image](https://github.com/dotnet/aspire/assets/104096256/1998e7fb-53ae-4ce3-a446-7e724d61c9a8)

This Databases
![image](https://github.com/dotnet/aspire/assets/104096256/74fa998a-8c57-4e5b-8f03-18cc46e80591)

![image](https://github.com/dotnet/aspire/assets/104096256/fec8a8b3-641d-4954-9b5a-67a6de09ab33)

And Here I Told It Like This

![image](https://github.com/dotnet/aspire/assets/104096256/2bb24ad7-9245-41f1-a03d-0d553ef6cbf3)

And As You See The With Refrence I'm Using Contains Connection String
![image](https://github.com/dotnet/aspire/assets/104096256/33375a95-77c5-4377-a243-4f19499057f7)

And I Can't Upload Zip Of Project Cause It's Private Application

**Comment by davidfowl** [comment]
You're saying the connection string name is being ignored? Can you clarify? Also can you look at the values in the environment to see what is flowing from the apphost to the application?

**Comment by wisamidris7** [comment]
I Have Got It
It's Just The DbContext Options I Was Injecting The Non Generic One

Thanks!
