### ISSUE TITLE
Adding Migration In Aspire Projects

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspire#2478]
![image](https://github.com/dotnet/aspire/assets/104096256/db9332c6-7f39-43be-8e86-b4921df0ca87)

Or 

```
The exception 'ConnectionString is missing. It should be provided in 'ConnectionStrings:tenantdb' or under the 'ConnectionString' key in 'Aspire:Npgsql:EntityFrameworkCore:PostgreSQL' or 'Aspire:Npgsql:EntityFrameworkCore:PostgreSQL:TenantDbContext' configuration section.' was thrown while attempting to find 'DbContext' types. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

And I'm Just Doing That

![image](https://github.com/dotnet/aspire/assets/104096256/a5a90e57-2514-40ce-9032-8884ce8c3870)

This Is Injection

![image](https://github.com/dotnet/aspire/assets/104096256/6e2d927f-9db3-4b28-9f08-d8cab389d2ef)

And This Is WithRefrence

![image](https://github.com/dotnet/aspire/assets/104096256/0c46c907-9b02-40d5-b541-64c6fe413fb6)

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by wisamidris7** [comment]
what do you mean by 'cc'

**Comment by davidfowl** [comment]
I'm mentioning @JamesNK because he did some work here to enable the migration CLI to work in the next preview version.

Long thread here https://github.com/dotnet/aspire/issues/398

**Comment by wisamidris7** [comment]
Is The

```
app.UseMigrationEndPoint();
```

Important Cause When I Was Exploring Some Project And I Have Found This Does This Related
But I Cloned The EShop Orginal Project And Migration Is In Identity.API Project

**Comment by wisamidris7** [comment]
For Now I Did Fake ConnectionString For It

**Comment by wisamidris7** [comment]
And You Can Close This Issue Whatever You Want!
👍
