### ISSUE TITLE
Dashboard console logs - High CPU usage with large amount of logs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2507]
1. Start TestShop
2. Configure Aspire dashboard to log everything with a debug level
3. View Aspire dashboard console logs. There are 1000s of lines.
4. Scrolling up and down isn't smooth. CPU usage for the tab is constant 20% (max?)

**Comment by JamesNK** [comment]
This page doesn't appear to use virtualization in the console output. Virtualization is required for good performance.

**Comment by davidfowl** [comment]
Feels like we should attempt this before we ship.

**Comment by captainsafia** [comment]
+1 to this. I'm playing around with applications that constantly poll an Azure Storage Queue and the log spew quickly overloads my browser.

**Comment by davidfowl** [comment]
cc @kvenkatrajan

**Comment by JamesNK** [comment]
> This page doesn't appear to use virtualization in the console output. Either virtualization or paging is required to limit rendered content for good performance. This UI should use virtualization.

Complication: Virtualization should be used to support infinite scrolling, but row heights are variable. If a log line is long then it will wrap and increase the size of a line.

**Comment by JamesNK** [comment]
I think to do virtualization properly would be complicated:

We'd need to:
* Do some JS interop to figure out how many characters fit in a line in the browser (fortunatly we're monospace text) then use that to calculate the height of each console line.
* Have the complete console data in memory. We can't say "give me console lines starting at 2000 and ending at 2100" because we need the first 2000 lines to look at how many characters there are to calculate height correctly.
* Take a copy of [Blazor's virtualizaiton](https://github.com/dotnet/aspnetcore/tree/main/src/Components/Web/src/Virtualization) and improve it to support variable heights.
