### ISSUE TITLE
[WebToolsE2E][Aspire] After installing SDK 9.0 Preview 2, the Aspire sdk-manifests don't match the latest released version of 9.0.0-preview.1

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#2512]
**REGRESSION INFO:** doesn't match either in SDK 9.0 Preview 1

**REPRO STEPS**
1. Clean machine: Win11 x64 23h2 ENU 
2. Install the latest SDK 9.0 Preview 2
3. After SDK is installed, look in C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.aspire
    
**ACTUAL**
The version is 9.0.0-preview.1.24116.3
![image](https://github.com/dotnet/aspire/assets/78580199/b5be2247-647e-4c35-b4d6-de01bc7d8057)

**EXPECTED**
The latest released version in nuget.org is 9.0.0-preview.1.24113.3.

**Comment by balachir** [comment]
@joperezr FYI on this. I'm not sure how impactful this is, so we got this issue opened to let you triage.
