### ISSUE TITLE
[WebToolsE2E][Aspire][Mac arm64][Unstable] Create an Aspire / Aspire Starter App, build and run, the Aspire icon display incompletely in safari browser.

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#2513]
**REGRESSION INFO:** Worked on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Mac arm64 Sonoma[14.3.1]
2. Install VS Code[1.86.2] and C# Dev Kit[1.4.2]
3. Install SDK 8.0.202
4. Install Aspire 8.0 P4 workload version 8.0.0-preview.4.24127.16
5. Apply NuGet Feeds

**REPRO STEPS**

1. Open CMD, creating an Aspire App using following commands:
`dotnet new aspire -o aspire1`
2. Run 'cd aspire1'
3. Right-click xxx.AppHost > Debug > Start New Instance

**ACTUAL:**
After running, The Aspire icon display incompletely in safari browser.
![image](https://github.com/dotnet/aspire/assets/88425944/1fb9d587-2e27-4acd-a8c0-ca5d3a571235)

**NOTE:**
1. This issue is unstable and It has a 60% chance of reproducing and the safari version is 17.3.1(19617.2.4.11.12).
2. It is not repro with Edge / Firefox / Google Chrome.

**EXPECTED**
Running project, The Aspire icon appear fully in safari browser.
![image](https://github.com/dotnet/aspire/assets/88425944/d8ca22c0-b042-40be-8661-1776f0f9eb2b)

**Comment by balachir** [comment]
@joperezr @davidfowl should we consider this for P4?

**Comment by davidfowl** [comment]
yep! @tlmii @kvenkatrajan

**Comment by joperezr** [comment]
We probably don't want to hold the current insertion until a fix is ready for this, but once we know what the fix is and we have a build ready we can do a bar check and depending on the time we can likely still take it.

**Comment by tlmii** [comment]
@timheuer Since you worked with the designers on this latest iteration of the icon, do you have any idea what's going on with this? Does safari not support something in the svg? At a glance it looks like maybe its only rendering the path that doesn't have a filter specified? Or maybe just rendering the first path not in a nested `<g>`? I don't have access to safari to test those theories

**Comment by tlmii** [comment]
@adamint I think you have access to a mac - can you see if you can repro and if you can determine which parts of the svg might be causing issues?

**Comment by adamint** [comment]
@v-polly Please share the safari version you are testing with. This does not reproduce on Safari 17.3.1

<img width="1241" alt="image" src="https://github.com/dotnet/aspire/assets/20359921/e3a5a462-edb0-4ca9-aeec-ef877c50ea76">

**Comment by davidfowl** [comment]
cc  @kvenkatrajan

**Comment by adamint** [comment]
I have been testing on Safari 17.3.1 as well. I can confirm as well that this is just a safari issue and does not repot on Chrome/Edge.

This issue does not reproduce stably, but only occurs about 10-20% of the time on my machine.

It appears that once you have a tab where the SVG renders incorrectly, refreshing that tab will have a high likelihood of also incorrectly rendering the SVG.

Removing the filters inside the SVG itself does not affect the prevalence of this issue.

**Comment by timheuer** [comment]
Dang you Safari 🤬

**Comment by tlmii** [comment]
I'm going to attempt to convert it to an inline svg via FluentIcon to see if maybe the safari issue is specific to external svg files. Will have Adam test and we will report back shortly.

**Comment by kvenkatrajan** [comment]
@adamint  lets revert to png on this. Sent you the image. And thanks for the alt text fix ;)

**Comment by kvenkatrajan** [comment]
Actually hold off till you test @tlmii's fix
