### ISSUE TITLE
Aspire.Hosting does not correctly set service discovery configuration for endpoints

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2520]
I noticed this a while back but forgot to log it and now just noticed it again when explicitly trying to use named endpoints.

When referencing one project resource from another for the purposes of service discovery in an Aspire AppHost project, `Aspire.Hosting` injects configuration values (via environment variables) into the referencing project so that service discovery can be configured. The key names are being set correctly, but the values aren't correctly encoding the endpoint name into the URI host name.

In the following example, this project resource is referencing another project resource named "apiservice" which has two endpoints: "http" and "internalhealthchecks". That should result in **three** config values being set, 2 for the endpoint named "http" (1 using the compact form and 1 using the expanded form), and 1 for the endpoint named "internalhealthchecks" (1 using the expanded form). Instead, we're only getting 1 entry for the "http" endpoint (it's missing the expanded form entry), and 1 for the "internalhealthchecks" endpoint that's using the compact form which is just wrong.

**What I see**

![image](https://github.com/dotnet/aspire/assets/249088/ec998a82-2eca-42c3-b68b-f3aa86fdc496)

**What it should be**

Name | Value
---- | ----
services__apiservice__0 | http://localhost:5301
services__apiservice__1 | http://_http.localhost:5301
services__apiservice__2 | http://_internalhealthchecks.localhost:61890

**Comment by GarretWayne** [comment]
We found the same issue, and it seems to be related to this part in `ResourceBuilderExtensions.cs`/  `CreateEndpointReferenceEnvironmentPopulationCallback` method: 

![CreateEndpointReferenceEnvironmentPopulationCallback_IsAmbiguousProblem](https://github.com/dotnet/aspire/assets/47498450/408504b8-109c-478d-9be5-8611117a5f93)
![ContainsAmbiguousEndpoints_method](https://github.com/dotnet/aspire/assets/47498450/15cdf3c0-8197-4428-afa1-c4353a7bed44)

We only had 1 service referenced by "`WithReference(...)`", and the referenced service's only port was duplicated perfectly, with a naming convention exactly as of the example listed before.
