### ISSUE TITLE
Enrich EF APIs overwrite an existing ExecutionStrategy by default

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#2524]
When someone calls `EnrichSqlServerDbContext` after they have configured their DbContext with an execution strategy, for example:

```C#
builder.Services.AddDbContext<MyDb1Context>(options =>
{
    options.UseNpgsql(npgsql =>
    {
        npgsql.ExecutionStrategy(c => new MyExecutionStrategy(c));
    });
});
builder.EnrichNpgsqlDbContext<MyDb1Context>();
```

We are overwriting the ExecutionStrategy by default (since settings.Retry is true by default)

https://github.com/dotnet/aspire/blob/c5f1b95332f4e462b2e608dfc006afca0f629661/src/Components/Aspire.Microsoft.EntityFrameworkCore.SqlServer/AspireSqlServerEFCoreSqlClientExtensions.cs#L111-L119

We should consider if this is the best behavior. Other options I can think of would be to detect if the ExecutionStrategy is already set, and log a warning.

cc @DamianEdwards

**Comment by eerhardt** [comment]
@sebastienros - I know we had this conversation during the first PR. But @DamianEdwards hit this and we might want to rethink the behavior here.

**Comment by sebastienros** [comment]
If we can detect it was set (we might be able AFAIR) I would suggest to not set it then, and log a warning that we are not configuring retries and users should do it in their code.

We could also have a setting that tells Enrich that the execution strategy was configured on purpose and to not log the warning. Like `SkipExecutionStrategyCustomization`. Setting this flag could be suggested in the warning. Could even be an exception, like we do when a DbContext is registered but users still call `AddSqlServerDbContext`.
