### ISSUE TITLE
Version the defaults used in AppHost resources

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/aspire#2527]
We have values in some of our resources which we will inevitably need to change as time progresses. Currently, we have no way to do this without potentially breaking working applications.

Things which we will want to version:

* Container image repos/tags
* Azure resource properties (SKUs, configuration)

We should add a facility which allows us to version these things by embedding the version used in a file alongside the app host project which is kept in source control.

Eg, as a strawman, the file could be a JSON-formatted mapping of resource names to versions:

```json
{
  "my-redis": "1",
  "my-compute": "3"
}
```

We could alternatively store this in the AppHost's appsettings.json or adjacent. That gives us a simple way to distinguish defaults used in each environment.

Resources would need to be given a way to consume the stored version, if there is one, and to specify a version to write to the file. When a developer wants to upgrade from one version of the defaults to another, they could either delete the entry in the file (at which point the resource would use the latest version which it knows about) or they could use an app model gesture (eg, `.WithDefaults(version: "2")`)

cc @mitchdenny

**Comment by mitchdenny** [comment]
Did some early experimentation around this on the Azure resource side of things:

https://github.com/dotnet/aspire/pull/3124

**Comment by davidfowl** [comment]
We decided to go with picking specific container tags tied to the nuget package version.
