### ISSUE TITLE
Consider renaming WithVolumeMount to WithVolume

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2528]
We should consider renaming `WithVolumeMount` to `WithVolume`.

While at the lowest layer in Docker, the "mount" term is used in context of "bind", "volume", and "tmpfs", at the higher levels the term "mount" is only associated with "bind mounts". The term "volume" is not used with "mount" unless in the context of the lower-level "mount" concept.

e.g. `docker volume create my-vol`

See https://docs.docker.com/storage/volumes/ and https://docs.docker.com/storage/bind-mounts/

If we wanted to more closely follow how Docker represents these concepts we could add a more verbose `WithMount` method that accepts all the args (basically what `WithVolumeMount` did originally). Then we'd have `WithMount`, `WithBindMount`, and `WithVolume`, where the latter two are convenience methods over the first.

**Comment by davidfowl** [comment]
This is kind of a now or never API change. 

@JamesNK any thoughts?

**Comment by JamesNK** [comment]
> While at the lowest layer in Docker, the "mount" term is used in context of "bind", "volume", and "tmpfs", at the higher levels the term "mount" is only associated with "bind mounts". The term "volume" is not used with "mount" unless in the context of the lower-level "mount" concept.
>
> e.g. `docker volume create my-vol`

That command creates a volume. If we're talking about volumes by themselves, then they should just be called volume. But I think you then use a volume with a container by mounting it.

I chose the name based on language at https://docs.docker.com/storage/. The docs talk about mounts, with options being volume vs bind mount.

**Comment by DamianEdwards** [comment]
> That command creates a volume. If we're talking about volumes by themselves, then they should just be called volume. But I think you then use a volume with a container by mounting it.

 > I chose the name based on language at https://docs.docker.com/storage/. The docs talk about mounts, with options being volume vs bind mount.

If you look at https://docs.docker.com/storage/volumes/, it's clear they use "mount" as both a noun in that context only of comparing "volumes" to "bind mounts", and as a verb in the context of "mounting a volume". Given our method is of the form `WithNoun`, I think it should just be `WithVolume`.

**Comment by JamesNK** [comment]
Ok, good point. You're convincing me. I'll make the change and see what it looks like in the PR. We can make a final decisions there.

**Comment by mitchdenny** [comment]
At one point in time I would have said that by doing this we are potentially removing room for a first class volume resource type. But the way things are going with the PublishAs APIs I think it is probably more likely that we would have APIs to define volumes and their mounts for deployment time scenarios.

For example, we might end up with something like this for doing a volume mount in ACA (total pseudo code to illustrate the concept - API shape will definitely be different).

```csharp
var storage = builder.AddAzureStorage("storage", storageAccount)
{
  storageAccount.AddOutput("filesUri", sa => sa.Properties.PrimaryEndpoints.FilesEndpoint);
});

builder.AddProject<Projects.MyApp>("myapp")
       .PublishAsAzureContainerApp(containerApp => {
         // mutate containerApp to use output from storage account.
         containerApp.AssignParameter(...storage.GetOutput("filesUri");
       });
```
