### ISSUE TITLE
[WebToolsE2E][Aspire] After added 'Aspire.Azure.Storage.Blobs' and use '.RunAsEmulator()', there are three URLs under the Endpoints of storage.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#2538]
**REGRESSION INFO**: New feature for Aspire 8.0 Preview 4

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34628.166.main] (Includes Aspire 8.0.0-preview.4.24128.4)
3. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > named it 'AspireApp1' > .NET 8.0 > Create
2. Right-click AspireApp1.web project > Add >  Aspire component > Aspire.Azure.Storage.Blobs > add a component and try to use it in the code
3. Open appsettings.json > make changes related to Aspire component

```
{ 
  "Aspire": { 
    "Azure": { 
      "Storage": { 
        "Blobs": { 
          "HealthChecks": false, 
          "Tracing": true, 
          "ClientOptions": { 
            "Diagnostics": { 
              "ApplicationId": "myapp"} 
          } 
        } 
      } 
    } 
  } 
} 
```

4. In the Program.cs of web project, type following codes: 
        `builder.AddAzureBlobService("blobsConnectionName"); `

5. Open appsettings.json of AspireApp1.AppHost project, add ConnectionStrings configuration section: 

```
{ 
  "ConnectionStrings": { 
    "blobsConnectionName": "https://{account_name}.blob.core.windows.net/" 
  } 
} 
```

6. Open Program.cs of AspireApp1.AppHost project, add following codes: 

```
var blobs = builder.AddAzureStorage("storage")
    .RunAsEmulator()
    .AddBlobs("blobs");

var myService = builder.AddProject<Projects.AspireApp1_Web>("webfrontend")
                       .WithReference(blobs);
```

**Note**: If you replace the code in step 6 with the following code, the result is as shown below
```
var blobs = builder.AddConnectionString("blobs");

var myService = builder.AddProject<Projects.AspireApp1_Web>("webfrontend")
                       .WithReference(blobs);
```
![image](https://github.com/dotnet/aspire/assets/109339894/f440e1db-eb77-4791-89ae-ad06e2c55af1)

**ACTUAL**
There are three URLs under the Endpoints of storage.
![image](https://github.com/dotnet/aspire/assets/109339894/a4364043-2008-4c56-bc52-f71355669812)

**EXPECTED**
Only one url.

**Comment by davidfowl** [comment]
This is by design. We made changes to show all of the endpoints for a resource in the dashboard. These are the exposed endpoints for the azure storage emulator.
