### ISSUE TITLE
Dashboard is appending the path from "launchUrl" on launch profile to endpoints that weren't added from the launch profile

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2548]
If I add a custom HTTP endpoint to a project resource in addition to the default endpoints discovered from the launch profile, and the launch profile has a path set on the `"launchUrl"` property, the dashboard includes that path on the hyperlink rendered for the custom endpoints. The path from the launch profile should only be appended to the endpoint addresses from the launch profile.

```csharp
var apiService = builder.AddProject<Projects.HealthChecksUI_ApiService>("apiservice")
    .WithHttpEndpoint(name: "healthchecks");
```

![image](https://github.com/dotnet/aspire/assets/249088/fc3ef7a2-781b-418e-92f1-1f9913aafb06)

**Comment by davidfowl** [comment]
This happens in the app model currently. We don't know where endpoints come from today.

cc @BrennanConroy

**Comment by davidfowl** [comment]
https://github.com/dotnet/aspire/blob/525c59ad9d58de54c71071e248b060061dfecd56/src/Aspire.Hosting/Dashboard/DcpDataSource.cs#L446-L468

I can take a look at fixing this.
