### ISSUE TITLE
[WebToolsE2E][Aspire] F5/Ctrl F5 an Azure Function project with aspire checked, there is no function app option shows under 'Structured logs', 'Traces' and 'Metrics' board.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2562]
**REGRESSION INFO**: New feature for Aspire 8.0 Preview 4

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34629.172.main] (Includes Aspire 8.0.0-preview.4.24128.4)
3. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > Azure Function > named it 'FunctionApp1' > .NET 8.0 Isolated > Http trigger > check 'Enlist in Aspire orchestration' > Create
2.Build solution
3.F5/Ctrl F5
4. Click 'Yes' on the popped dialog 

**ACTUAL**
There is no function app option shows under 'Structured logs', 'Traces' and 'Metrics' board.
![image](https://github.com/dotnet/aspire/assets/82028229/187e4a1f-de18-447b-bbbf-3bf0254632e7)
![image](https://github.com/dotnet/aspire/assets/82028229/0270ac31-3643-4a8f-8c08-960a2e4c7fe8)
![image](https://github.com/dotnet/aspire/assets/82028229/4e2819a3-574c-4069-812d-ed9e2642666f)

**EXPECTED**
Shows the function app like 'Console logs'
![image](https://github.com/dotnet/aspire/assets/82028229/d8974a0c-0cd2-47ee-a7e5-7292f19ab7f7)

**Comment by davidfowl** [comment]
This is by design. Functions doesn't support emitting structured logs and traces via otel without manual intervention.

**Comment by davidfowl** [comment]
Work will be done as part of #5563
