### ISSUE TITLE
Dashboard resource dropdowns max height

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2566]
Resource dropdowns on various pages needs a maximum height. Currently the list of resources disappears off the screen:

![image](https://github.com/dotnet/aspire/assets/303201/1701c16d-d1f6-4b9d-a82c-1249502709e2)

**Comment by MatsM16** [comment]
@JamesNK   
Did you have a maximum height or item-count in mind?  
_(If not, I suggest 24 items as I presume this would avoid the scrollbar for most projects while still fitting on the screen.)_

Should this maximum be shared with `Metrics`, `Traces` and/or `StructuredLogs`?  
_(I suggest yes.)_

**Comment by JamesNK** [comment]
Make the height allow for 10 items. That displays a lot at once and should work with lower resolution monitors.

> Should this maximum be shared with Metrics, Traces and/or StructuredLogs?

Yes

**Comment by MatsM16** [comment]
@JamesNK Could you help me look at #2678 when you get the time?
