### ISSUE TITLE
[WebToolsE2E][Aspire] Running the Aspire project, the browser page is not localized.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#2567]
**REGRESSION INFO**: Repro on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 22h2 CHS
2. Install Dev17.10 Preview 2 from [[34629.198.main] (Includes Aspire 8.0.0-preview.4.24128.4)
3. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > .NET 8.0 > Create
2. Build and F5

**ACTUAL**
The browser page is not localized.
![Browser](https://github.com/dotnet/aspire/assets/109339894/5bd5e62c-b64a-442f-bdda-55f63decc2ea)

**EXPECTED**
Browser pages should be localized.

**Comment by kvenkatrajan** [comment]
Localization infra onboarding in progress: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/948961/
@adamint  please verify (post 3/15)  and close end of preview 5

**Comment by adamint** [comment]
These pages are now localized 😄
