### ISSUE TITLE
Dashboard not loading Executables (sometimes)

### ISSUE THREAD

**Issue by adamtrip** [dotnet/aspire#2569]
Sometimes on app startup the dashboard does not list the executables like npm apps. This behaviour is not consistent and happens randomly from what I've seen. The executable is working, if I open a new tab with the url of the executable, it works.

No errors on console or network tabs.

Might be because I have a lot of aspire components. On the sample with React/Vue/Angular I'm unable to replicate.
I have the following components:

- 1 container
- 4 parameters
- 8 projects
- 1 executable (not showing)

Sometimes I'm able to fix it by changing something on my `AppHost\Program.cs` file (forcing recompile).
Might be related with https://github.com/dotnet/aspire/issues/2539

On: `8.0.0-preview.5.24128.10`

![image](https://github.com/dotnet/aspire/assets/59871955/9227194f-920b-40eb-91cb-6a142ed29c3a)

**Comment by davidfowl** [comment]
@balachir can you keep an eye out for this one as well? This is on the main branch so not urgent right now.

**Comment by balachir** [comment]
@davidfowl sure, we'll try it and see if we can repro with main branch builds.

**Comment by davidfowl** [comment]
I was able to reproduce this and fix it

**Comment by v-sherryfan** [comment]
@davidfowl @balachir I tried to verify this issue with the AspireWithNode and AspireWithJavaScript samples from aspire-samples repo but was unable to reproduce it using the latest Aspire 8.0 P5 (8.0.0-preview.5.24154.5).
![image](https://github.com/dotnet/aspire/assets/71361488/c7f0d22f-8760-4a30-9ac7-412f1f7900ef)
![image](https://github.com/dotnet/aspire/assets/71361488/9cfda737-2fcd-43d7-9b68-0e747b6b7165)
