### ISSUE TITLE
WithImage and WithImageTag assume a single ContainerImageAnnoation exists

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2580]
The `WithImage` and `WithImageTag` methods assume the `ContainerResource` has a single `ContainerImageAnnotation` but by default they have none, and they could have more than one. Calling either of these methods in these states results in a LINQ exception.

We should make these methods more user friendly, e.g. add the `ContainerImageAnnotation` if it doesn't exist. If there's more than one then perhaps it should just get the last one and update that.

**Comment by GMouaad** [comment]
I have a small draft PR (#2588) that fixes the first part of `WithImage`.

For the `WithImageTag`, there isn't a (simple) way to create the annotation without knowing the image name, do you have an idea how to tackle this?

**Comment by DamianEdwards** [comment]
> For the WithImageTag, there isn't a (simple) way to create the annotation without knowing the image name, do you have an idea how to tackle this?

I guess we just make it throw `InvalidOperationException` or `DistributedApplicationException` with an appropriate message. @davidfowl @mitchdenny?

**Comment by mitchdenny** [comment]
This could be a problem with the `AsXYZ` extension methods:

```csharp
builder.AddRedis(...).WithImageTag(...).PublishAsAzureRedis(); // OK
builder.AddRedis(...).PublishAsAzureRedis().WithImageTag(); // Throws
```

This proposal means that the second line would throw. The net effect would be that the container for Redis would get launched in DCP, and the Azure resource would be provisioned.

**Comment by DamianEdwards** [comment]
> This proposal ...

Which proposal exactly @mitchdenny? Making `WithImageTag` throw if there's no existing annotation? What do you suggest?

**Comment by davidfowl** [comment]
Closing this as it was fixed with https://github.com/dotnet/aspire/pull/2588.

WithImage supports both an image name and tag (it'll default to latest)
WithImageTag will throw if there's no existing ContainerImageAnnotation.
