### ISSUE TITLE
Refactor and clean up the bicep files for azure resources

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2584]
From https://github.com/dotnet/aspire/issues/2100#issuecomment-1965001188

@jongio 

> I reviewed the bicep code in: https://github.com/dotnet/aspire/tree/main/src/Aspire.Hosting.Azure/Bicep
> 
> Here's my feedback:
> 
> 1. resourceToken should be more unique, otherwise there will be collisions: var resourceToken = toLower(uniqueString(subscription().id, environmentName, location))
> 2. Use consistent naming for resources, I see camel and pascal
> 3. Consider adding a role.bicep like this:
> https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/security/role.bicep
> 
> 4. Consider adding default retention and sku to appinsights.bicep/workspaces
> 5. cosmos is hardcoded to docdb, consider adding a param if you want to ever use the mongo api.  
> https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/cosmos/cosmos-account.bicep#L10
> 
> 6. Consider cosmos serverless as it is MUCH cheaper.  
> https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/cosmos/cosmos-account.bicep#L30
> 
> 7. consider adding kv secret bicep:
> https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/security/keyvault-secret.bicep
> 
> 8. consider using amv module references instead of shipping bicep modules, the source is here:
> https://github.com/Azure/bicep-registry-modules/tree/main/avm/res
> 
> example of how to use it:
> https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/app/container-app#example-1-using-only-defaults

This is a maybe based on how far we get with https://github.com/dotnet/aspire/issues/2423

**Comment by davidfowl** [comment]
We'll decide if we need to do this by Thursday

**Comment by ctolkien** [comment]
I'd add to this, the sql firewall is hardcoded to open up 0.0.0.0 to 255.255.255.255 ....not ideal imo.

**Comment by davidfowl** [comment]
That’ll be for the local dev scenario only.

**Comment by mitchdenny** [comment]
We are missing firewall rules for a few of the CDK based resources. We will need to close this gap (ideally for P5 but definitely for GA).
