### ISSUE TITLE
The AddServiceDefaults method leads to confusion

### ISSUE THREAD

**Issue by jscarle** [dotnet/aspire#2589]
Even after reading [Quickstart: Build your first .NET Aspire app](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app) and [.NET Aspire service defaults](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/service-defaults), the method `AddServiceDefaults` leads to confusion.

Perhaps `AddAspireDefaults` may be a better name?

**Comment by christiannagel** [comment]
Why does `AddServiceDefaults` lead to confusion - the defaults for all services of the solution?

I prefer the name `AddServiceDefaults`. I'm also adding defaults to this method needed for all the services of the solution and customize `AddOpenTelemetryExporters` and `MapDefaultEndpoints` as needed.

**Comment by jscarle** [comment]
I understand that this is part of the user's code and that we're free to rename this as we wish. In fact, it's not even needed for Aspire to work technically. However when you look at the following code, there's absolutely no indication as what those extension methods are for.

```cs
var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();

var app = builder.Build();

app.MapDefaultEndpoints();

app.Run();
```

There's no context to the name of the methods. What service defaults? Who's service defaults? Should I override those service defaults? Do I need those service defaults? What do the service defaults do? What if the service defaults are in another repository? What if the service defaults are in a NuGet package? What if the service defaults are determined by another team?

There's so much ambiguity to the terminology and the concept of centralizing all of the configuration for all of the services. If you take a look at all of the other services that are built into the SDK, just to name a few:

```cs
builder.Services.AddAntiforgery();
builder.Services.AddAuthentication();
builder.Services.AddAuthorization();
builder.Services.AddControllers();
builder.Services.AddCors();
builder.Services.AddDataProtection();
builder.Services.AddDistributedMemoryCache();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddExceptionHandler();
builder.Services.AddHealthChecks();
builder.Services.AddHsts();
builder.Services.AddHttpClient();
```

Every one of those clearly indicates its purpose. There's no confusing `AddAuthorization()` for `AddHealthChecks()` for example. At first glance, I may no know _exactly_ what Authorization is added or what Health Checks are added, but at least I know what Authorization and Health Checks are being added to my DI container.

I have no clue what `AddServiceDefaults` adds. If it were named `AddAspireDefaults`, then I know right away that this is an Aspire solution, so I should look for the orchestrator. If were named `AddOpenTelemetry`, then I know right away that this adds Open Telemetry support to my application, thus it's safe to remove it if I don't need or want that.

The same applies to `MapDefaultEndpoints`. There's absolutely no indication as to what endpoints those are and all of the same questions applies.

Never mind the fact that throughout all of this, there's no `builder.Services.Configure<AspireOptions>` which means that either all of my services have to completely opt-in, completely opt-out, or I have to write my own Options to be able to choose which and how each service is configure for my different services in my solution (if they're in the same solution to begin with).

One of the recurring themes that is often discussed in our industry is the concept of high cohesion and low coupling, this goes in the opposite direction as this push for all services to adopt the same configuration and settings.

Look, personally, I think Aspire is awesome and it's an incredible tool that fills a gap in .NET that's long overdue to be filled. I hear a lot of complaints about Aspire which, for the most part, are completely unfounded and nothing more than FUD. Nonetheless, the fact that Aspire continues to be presented this way is why developers come to ridiculous conclusions such as _"Aspire is just a distributed monolith builder"_ or _"It's just another Microsoft toy that will fizzle out"_. Discussions like these may seem asinine, but these types of issues shouldn't just be brushed under the carpet.

**Comment by christiannagel** [comment]
@jscarle - when you need these DI registrations with all the service projects in the solution, to get rid of the duplicate code, how would you name this method instead? `AddAntiforgeryAuthenticationAuthorizationControllersCorsDataProtectionDistributedMemoryCacheAndMore`?

```csharp
public static IHostApplicationBuilder AddDefaultServices(this IHostApplicationBuilder builder)
{
  builder.Services.AddAntiforgery();
  builder.Services.AddAuthentication();
  builder.Services.AddAuthorization(); 
  builder.Services.AddControllers();
  builder.Services.AddCors();
  builder.Services.AddDataProtection();
  builder.Services.AddDistributedMemoryCache();
  builder.Services.AddEndpointsApiExplorer();
  builder.Services.AddExceptionHandler();
  builder.Services.AddHealthChecks();
  builder.Services.AddHsts();
  builder.Services.AddHttpClient();
  return builder;
}
```

**Comment by jscarle** [comment]
> @jscarle - when you need these DI registrations with all the service projects in the solution, to get rid of the duplicate code, how would you name this method instead? `AddAntiforgeryAuthenticationAuthorizationControllersCorsDataProtectionDistributedMemoryCacheAndMore`?

Such a method shouldn't exist in the first place. Why would you obligatorily force all of your services to have the same set of built-in services with the same configuration?

**Comment by christiannagel** [comment]
True, I don't register all these services to the DI container - but I do register the ones I need with all the services of the solution, such as:

- OpenTelemetry
- Health checks
- Service discovery
- HTTP client defaults
- and some more functionality that's needed by all the services.

I don't see an advantage renaming this method to `AddAspireDefaults`. This could be used independent of .NET Aspire. You can also remove this library and add the code to every single app if these are not needed.

I also don't see an advantage needing to add

```csharp
builder.AddOpenTelemetryDefaults();
builder.AddServiceDiscoveryDefaults();
builder.AddHttpClientDefaults();
builder.AddXXXDefaults();
```

instead of just

```csharp
builder.AddServiceDefaults();
```

Of course, adding documentation to the method `AddServiceDefaults` would help to see what's done here.

**Comment by DamianEdwards** [comment]
The method is intended to represent the set of defaults related to configuration of the DI container (i.e. what services are registered and how they're configured) shared by all app projects in a solution. We feel it's a good starting point (hence in the template) based on what we've observed when reviewing the code bases of numerous distributed apps inside and outside of Microsoft. It also matches directly the project name that contains the implementation of the method in Aspire solutions (e.g. `MyApp.ServiceDefaults`) so keeping the names consistent helps to reinforce the idea of this pattern.

**Comment by jscarle** [comment]
@DamianEdwards Thank you for taking the time to share this insight.
