### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.Azure.Security.KeyVault component, F5 failed with an exception: Caller is not authorized to perform action on resource......

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2610]
**REGRESSION INFO**: Also repro on 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34701.141.d17.10] (Includes Aspire 8.0.0-preview.4.24129.7)
3. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > ASP.NET Core Empty project > name it 'AspireKeyVault'> 8.0 > check 'Enlist in Aspire Orchestration'
2. Right-click AspireKeyVault project > Add > Aspire component > Aspire.Azure.Security.KeyVault
3. Open Azure portal, search 'Key Vault' and create a new key vault.
4. Open launchSettings.json of AspireKeyVault project, add vaulturi to the http{}:
         
       "VaultUri": "https://xxx.vault.azure.net/",
       "AZURE_USERNAME": "xxx@microsoft.com"

5. Update the Program.cs of AspireKeyVault project with following codes:
        
        using Azure.Identity; 

        var keyVaultEndpoint = new Uri(Environment.GetEnvironmentVariable("VaultUri"));
        builder.Configuration.AddAzureKeyVault(keyVaultEndpoint, new VisualStudioCredential());
        
        //app.MapGet("/", () => "Hello World!");
       string? _mySecret = builder.Configuration["myAppSetting"];
       var result = string.IsNullOrEmpty(_mySecret) ? "Null" : _mySecret;
       app.MapGet("/", async context =>
       {
             await context.Response.WriteAsync($"Secret is {result}");
       });

6. Build and F5
7. On the dashboard, click the endpoint url of AspireKeyVault project.

**Notes**:

1. It will meet [Bug 1985774](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1985774) when adding the aspire component.

**ACTUAL**
It throws an exception: Caller is not authorized to perform action on resource when opening the endpoint url of AspireKeyVault.
![image](https://github.com/dotnet/aspire/assets/82028229/3aedfa6f-b600-46ab-80e8-4fc9b5089280)
Azure.RequestFailedException
  HResult=0x80131500
  Message=Caller is not authorized to perform action on resource.
If role assignments, deny assignments or role definitions were changed recently, please observe propagation time.
Caller: appid=04f0c124-f2bc-4f59-8241-bf6df9866bbd;oid=2d040a87-fe37-4b78-b777-d3a28028f590;iss=https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/
Action: 'Microsoft.KeyVault/vaults/secrets/readMetadata/action'
Resource: '/subscriptions/xxx/resourcegroups/carolineaspireweek/providers/microsoft.keyvault/vaults/aspkeyva'
Assignment: (not found)
DenyAssignmentId: null
DecisionReason: null 
Vault: aspkeyva;location=eastus

Status: 403 (Forbidden)
ErrorCode: Forbidden

Content:
{"error":{"code":"Forbidden","message":"Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=04f0c124-f2bc-4f59-8241-bf6df9866bbd;oid=2d040a87-fe37-4b78-b777-d3a28028f590;iss=https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/\r\nAction: 'Microsoft.KeyVault/vaults/secrets/readMetadata/action'\r\nResource: '/subscriptions/xxx/resourcegroups/carolineaspireweek/providers/microsoft.keyvault/vaults/aspkeyva'\r\nAssignment: (not found)\r\nDenyAssignmentId: null\r\nDecisionReason: null \r\nVault: aspkeyva;location=eastus\r\n","innererror":{"code":"ForbiddenByRbac"}}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: eastus
x-ms-client-request-id: 6b34c481-8739-46ef-8925-7ce374e962b2
x-ms-request-id: 7e2d27d9-8c9a-4c62-adb2-6df338eec506
x-ms-keyvault-service-version: 1.9.1300.1
x-ms-keyvault-network-info: conn_type=Ipv4;addr=104.44.112.249;act_addr_fam=InterNetwork;
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Date: Mon, 04 Mar 2024 08:46:23 GMT
Content-Length: 746
Content-Type: application/json; charset=utf-8
Expires: -1

  Source=Azure.Security.KeyVault.Secrets
  StackTrace:
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__29.MoveNext()
   at Azure.Security.KeyVault.KeyVaultPipeline.<GetPageAsync>d__17`1.MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.<AsPages>d__2.MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.<AsPages>d__2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.<LoadAsync>d__11.MoveNext()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.<LoadAsync>d__11.MoveNext()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, SecretClient client, AzureKeyVaultConfigurationOptions options)
   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, Uri vaultUri, TokenCredential credential, KeyVaultSecretManager manager)
   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, Uri vaultUri, TokenCredential credential)
   at Program.<Main>$(String[] args) in C:\Users\v-cazhang\source\repos\WebApplication5\WebApplication5\Program.cs:line 7

**EXPECTED**
No exception shows

**Comment by balachir** [comment]
@v-cazhang this seems like a possible permission issue where your account does not have access to the key vault. Let's sync up again tomorrow and understand why you're getting this authorization error. 

> Content:
{"error":{"code":"Forbidden","message":"Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.

**Comment by v-cazhang** [comment]
Hi @balachir , I tried again this morning, and I found that, this issue reproduces when I used the key vault created from Azure portal. When I open the key vault which I created using Azure portal, it shows 'You are unauthorized to view these contents.'
![image](https://github.com/dotnet/aspire/assets/82028229/ff5d2f55-d9d9-48b7-a0a5-c994adb18b4e)

But if I created key vault using VS, this issue doesn't reproduce. I also can add secret from Azure portal:
![image](https://github.com/dotnet/aspire/assets/82028229/bff2d13c-29ff-4aba-a9da-770735fb6e81)

And I have updated the repro steps.

**Comment by balachir** [comment]
Hi @v-cazhang thanks for trying this. I suspect that the issue might not be aspire related. Can you also try our E2E test for Azure key vault without aspire when the key vault has been created using the Azure portal? Does this error reproduce for that scenario too?

**Comment by v-cazhang** [comment]
@balachir, I tried our E2E test for Azure key vault on the razor project without aspire. 
It stuck on verifying access to the key vault when adding 'Azure Key Vault' as services dependency
![image](https://github.com/dotnet/aspire/assets/82028229/9ba9e8cd-93cd-431a-bf62-542c37183545)

**Comment by eerhardt** [comment]
Closing as this doesn't appear to be Aspire related. Feel free to reopen if an Aspire change is needed.
