### ISSUE TITLE
[WebToolsE2E][Aspire][Linux arm64] After adding an Blazor Web App project to an existing Aspire project's solution, two errors occurs "Cannot convert lambda expression to intended delegate type xxx".

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#2611]
**REGRESSION INFO:** Repro on Aspire 8.0.0 preview 3.24105.21

**INSTALL STEPS**

1.Clean machine: Linux arm64 machine
2.Install VS Code[1.87.0]
3.Install C# Dev Kit[1.4.2]
4.Install SDK 8.0.202
5.Install Aspire.ProjectTemplates.8.0.0-preview.4.24156.9
6.Apply NuGet Feeds

**REPRO STEPS**

1.Open CMD, creating an Aspire App using following commands:
```
dotnet new aspire -o aspire1
cd aspire1
code .
```
2.'Ctrl-Shift-P' to add a new Blazor Web App project under this solution > give a name 'blazor1'
3.Wait a little while for the project to load

**ACTUAL**
Two errors occurs: 
"Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type"
"The type or namespace name 'Layout' could not be found(are you missing a using directive or an assembly reference?)"
![image](https://github.com/dotnet/aspire/assets/88425944/82aa395d-6ebe-43a6-95c2-aaf117c58aaa)

**NOTE**
1.Close and re-open the project, there will have no errors.
2.This issue was not repro on Win x64 machine
3.On Win x64 and Linux arm64 machine, if coutinue to Right-click the xxx.AppHost > Add project reference to blazor after the step 3, will met this issue [#2609](https://github.com/dotnet/aspire/issues/2609)

**EXPECTED**
There won't be any errors.

**Comment by balachir** [comment]
@v-polly if you give your Blazor Web App a different name, eg: `blazor1` instead of `blazor`, then do the issues mentioned in this report still reproduce? I'm trying to understand whether this issue is another case of issues due to using reserved keywords as project names (similar to #2609).

**Comment by v-polly** [comment]
@balachir Thanks for your suggestion, I have verified this issue use the repro steps and give Blazor Web App a different name, eg: blazor1, it still repro:
![image](https://github.com/dotnet/aspire/assets/88425944/82aa395d-6ebe-43a6-95c2-aaf117c58aaa)

**Comment by balachir** [comment]
@v-polly thanks for confirming. Can you go ahead and update the Repro Steps to mention `blazor1` instead of `blazor` as the project name? That will remove confusion about whether this issue was caused due to naming the project with a keyword.

One more question. Do the errors described in the Repro Steps also reproduce when you build the solution using command line? If yes, can you share a screenshot of the command-line output?

**Comment by v-polly** [comment]
@balachir I have updated the Repro Steps.
When I follow the repro steps on Linux arm64 RedHat 9.2 to create aspire and blazor projects using cmd, there is no error message in the command line.
![image](https://github.com/dotnet/aspire/assets/88425944/77b55bcf-48cc-403c-998b-fda28d7ee778)
![image](https://github.com/dotnet/aspire/assets/88425944/2aca6d04-7e76-4b41-887a-d8a53501c962)

But after using vs code to open the project created by cmd earlier, there will be 2 error messages in vs code.
![image](https://github.com/dotnet/aspire/assets/88425944/11809d02-4a2a-4719-9b17-773dc730cdd0)

**Comment by v-polly** [comment]
@balachir Thanks, I have closed this issue and opened a new one in AzDO: [Bug 2003792](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2003792): [WebToolsE2E][Aspire][Green]On Linux Arm64, After adding an Blazor Web App project to an existing Aspire project's solution, two errors occurs "Cannot convert lambda expression to intended delegate type xxx".
