### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.StackExchange.Redis.DistributedCaching component, build failed with error: The type or namespace name 'IDistributedCache' could not be found shows in the output window but doesn't show in the error list window.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2612]
**REGRESSION INFO**: Also repro on 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34701.141.d17.10] (Includes Aspire 8.0.0-preview.4.24129.7)
3. Apply NuGet Feeds
4. Install Docker Desktop

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > name it 'AspireRedis'> 8.0 > uncheck 'Use Redis for caching'
2. Update the Program.cs file of the AspireRedis.AppHost project to match the following code:

       var builder = DistributedApplication.CreateBuilder(args);
       var redis = builder.AddRedis("cache");
       var apiservice = builder.AddProject<Projects.AspireRedis_ApiService>("apiservice")
             .WithReference(redis);
       builder.AddProject<Projects.AspireRedis_Web>("webfrontend")
             .WithReference(apiservice)
             .WithReference(redis);
       builder.Build().Run();

3. Add the Redis connection string in each project's appsettings.json file:
      
       {
             "ConnectionStrings": {
                   "cache": "localhost:6379"
               }
       }
4. Right-click AspireRedis.ApiService project > Add > Aspire component > install Aspire.StackExchange.Redis.DistributedCaching
5. Towards the top of the Program.cs file of AspireRedis.ApiService project, add a call to AddRedisDistributedCache:

         builder.AddRedisDistributedCache("cache");

6.  replace the existing /weatherforecast endpoint code with the following:
```
app.MapGet("/weatherforecast", async (IDistributedCache cache) =>
{
    var cachedForecast = await cache.GetAsync("forecast");
    if (cachedForecast is null)
    {
        var summaries = new[] { "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching" };
        var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
        await cache.SetAsync("forecast", Encoding.UTF8.GetBytes(JsonSerializer.Serialize(forecast)), new ()
        {
            AbsoluteExpiration = DateTime.Now.AddSeconds(10)
        }); ;
        return forecast;
    }
    return JsonSerializer.Deserialize<IEnumerable<WeatherForecast>>(cachedForecast);
})
.WithName("GetWeatherForecast");
```
7. Build solution

**Notes**:

1. It will meet [Bug 1985774](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1985774) when adding the aspire component.

**ACTUAL**
Build failed and shows the message: error CS0246: The type or namespace name 'IDistributedCache' could not be found (are you missing a using directive or an assembly reference?) in the output window, but doesn't show error in the error list.
![image](https://github.com/dotnet/aspire/assets/82028229/12382cc1-80a8-451a-8ec6-000f89c19e61)
![image](https://github.com/dotnet/aspire/assets/82028229/b90c9c2c-0fe2-4f65-b404-b94ae41cf4ef)

**EXPECTED**
Error list should show the same error in the output window.

**Comment by v-sherryfan** [comment]
Verified this issue that is not reproduced on latest 17.10 P2 [34705.46.d17.10, also include Aspire 8.0.0-preview.4.24129.7]. closed it as fixed.
