### ISSUE TITLE
[WebToolsE2E][Aspire] There is no intellisense of 'RunAsXXX' and 'AsXXX', but has intellisense of 'PublishAsXXX'.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2637]
**REGRESSION INFO**: New feature on Aspire 8.0 Preview 4

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34701.141.d17.10] (Includes Aspire 8.0.0-preview.4.24129.7)
3. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > .NET 8.0 > check 'Use Redis for caching (requires Docker)' > create
2. Open Program.cs of AppHost project, type '.As' behind the 'AddRedis("redis")' 

**ACTUAL**
The intellisense only contains 'PublishAsXXX', doesn't contain 'RunAsXXX' or 'AsXXX'
![image](https://github.com/dotnet/aspire/assets/82028229/11405fbe-1252-4f31-b0fb-0318ffc971bd)

**EXPECTED**
Should contain 'RunAsXXX' and 'AsXXX' in the intellisense

**Comment by davidfowl** [comment]
There’s

PublishAsConnectionString
PublishAsContainer 

then in the azure packages 

(Publish)AsAzureRedis
(PublishAs)AzurePostgresFlexibleServer
(PublishAs)AzureSql

RunAsEmulator for cosmos and azure storage

This is by design
