### ISSUE TITLE
Resolve the correct container runtime and chose appropriate host name

### ISSUE THREAD

**Issue by thangchung** [dotnet/aspire#2639]
When I tried to run `AddPostgres` with `WithPgAdmin` as well as `AddRedis` with `WithRedisCommander`, nothing worked on Podman native.

I struggled to find the root cause and finally found the problem when I ran:

```sh
> podman ps
> podman exec -it <pg admin container id> sh
> cat servers.json
{"Servers":{"1":{"Name":"postgreSQL","Group":"Aspire instances","Host":"host.docker.internal","Port":5432,"Username":"postgres","SSLMode":"prefer","MaintenanceDB":"postgres","PasswordExecCommand":"echo \u0027<password>\u0027"}}} 
```

Look at the `Host`, it still pointed to `host.docker.internal` although I run on `Podman`. And the same thing happened to `Redis` with `RedisCommander` And I think this is a bug.

OS: Windows 11
.NET 8.0.200
.NET Aspire version: `8.0.0-preview.4.24127.7+2cbacd4bf15147d0ce67e915f6932bffb3f7e720`
Podman version: `4.9.0`

/cc @davidfowl

**Comment by davidfowl** [comment]
Seems like we should be using **host.containers.internal** for podman. There's an override but I think we hard code these for redis commander and pgadmin.

@danegsta Is there a way to query the container runtime from dcp?

https://github.com/dotnet/aspire/blob/184b1297c324a310930c05aca37b2b66cbcc222e/src/Aspire.Hosting/Redis/RedisCommanderConfigWriterHook.cs#L34

https://github.com/dotnet/aspire/blob/184b1297c324a310930c05aca37b2b66cbcc222e/src/Aspire.Hosting/MySql/PhpMyAdminConfigWriterHook.cs#L37

https://github.com/dotnet/aspire/blob/184b1297c324a310930c05aca37b2b66cbcc222e/src/Aspire.Hosting/Postgres/PgAdminConfigWriterHook.cs#L38

https://github.com/dotnet/aspire/blob/184b1297c324a310930c05aca37b2b66cbcc222e/src/Aspire.Hosting/MongoDB/MongoDBBuilderExtensions.cs#L78

**Comment by DamianEdwards** [comment]
We'll need this exposed in the app model during lifecycle callbacks to allow other resources to do this too.

**Comment by karolz-ms** [comment]
@davidfowl we have this thing called [DcpDependencyCheck](https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs) that is run as part of [DcpHostService startup](https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dcp/DcpHostService.cs#L66). It gathers the information about container runtime. I am not sure if the result of the check is readily available to the callbacks, but it should be pretty easy to make it available.

**Comment by karolz-ms** [comment]
`IDcpDependencyCheckService` is already part of the `DistributedApplicationBuilder` https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/DistributedApplicationBuilder.cs#L95

**Comment by davidfowl** [comment]
It’s not currently not those callbacks run a bit too early today. If we have the information then we can figure out how to make it work.

**Comment by danegsta** [comment]
We do provide the identified runtime from DCP as part of those dependency checks, but something to consider is that there are ways to bind a custom local machine address in a container if we wanted to make this work consistently across runtimes.

**Comment by davidfowl** [comment]
I'm going to do a cheap fix for preview 4 to make this configurable. We have this same problem in other parts of the stack but it's centralized. I'm going to make this use the same logic. In preview 5, we can make it more automatic based on the container runtime.

**Comment by davidfowl** [comment]
PR is up. It will still require manual work for preview4, we'll make it more automagic in p5.

**Comment by davidfowl** [comment]
> We do provide the identified runtime from DCP as part of those dependency checks, but something to consider is that there are ways to bind a custom local machine address in a container if we wanted to make this work consistently across runtimes.

Lets' chat about doing this @danegsta

**Comment by karolz-ms** [comment]
I am a little surprised that `host.docker.internal` did not work with Podman. These PRs should have enabled it, if I understand things correctly: https://github.com/containers/common/pull/1592 and https://github.com/containers/common/pull/1549

**Comment by davidfowl** [comment]
@karolz-ms that PR adds `host.containers.internal` it seems.
