### ISSUE TITLE
[Aspire.targets] The remote server returned an error: 503 Server unavailable

### ISSUE THREAD

**Issue by Mortana89** [dotnet/aspire#2641]
Started last friday, we can't compile our solution anymore.
We receive on each project the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The remote server returned an error: (503) Server Unavailable.	Configuration.Api	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\WebTools.Aspire\Microsoft.WebTools.Aspire.targets	47	

Also timeouts:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The operation has timed out	Admin	C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\WebTools.Aspire\Microsoft.WebTools.Aspire.targets	47	

Really baffled here, think it has to do with nuget because I can see an exclamation mark under Packages and Analyzers:
<img width="412" alt="image" src="https://github.com/dotnet/aspire/assets/45714001/f03f08f2-f9ee-4fbf-9629-b6239adbae3a">

Can't find out, cleared nuget packages as well, even reinstalled VS, any idea? At this moment we're stuck :(

**Comment by Mortana89** [comment]
Apparently it's the JSON schema validator website being down ...
https://schemastore.org/json/

Is there a way to circumvent this, since it's coming from the aspire targets?

**Comment by wisamidris7** [comment]
Solution One (This Worked With Me)

You Have To Just Try This It Worked With Me Go To .nuget Folder

C:\Users\{UserName}\.nuget

And You Can Delete The  .nuget Folder Or You Can Rename It Like I Do
![image](https://github.com/dotnet/aspire/assets/104096256/e1543e32-f33a-4f5e-a85b-e159b29e00d6)

And Delete Bin And Obj Of Your Solution And Rebuild Or ```dotnet restore``` And Everything Done

**Comment by wisamidris7** [comment]
Solution Two 

![image](https://github.com/dotnet/aspire/assets/104096256/ec524527-54c2-42e4-81f5-bf32530623cd)

Go To Here By Going To Options And Remove All Package Sources This Is If The Solution One Does Not Worked And Thanks

You Was With @wisamidris7

**Comment by wisamidris7** [comment]
I Have Been Two Days Trying To Solve This Problem

**Comment by mip1983** [comment]
> Solution One (This Worked With Me)
> 
> You Have To Just Try This It Worked With Me Go To .nuget Folder
> 
> C:\Users{UserName}.nuget
> 
> And You Can Delete The .nuget Folder Or You Can Rename It Like I Do ![image](https://private-user-images.githubusercontent.com/104096256/310139431-e1543e32-f33a-4f5e-a85b-e159b29e00d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDYzODAsIm5iZiI6MTcwOTY0NjA4MCwicGF0aCI6Ii8xMDQwOTYyNTYvMzEwMTM5NDMxLWUxNTQzZTMyLWYzM2EtNGY1ZS1hODViLWUxNTliMjllMDBkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMzQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2QwODY0ZmMzZDkyYzk2MGNlZDlmZjc2YmFlOGZiYjg4MjM4YmMzMjkwMGE0NzI3OTEyNzI0MzFkYmE0ZmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zpgB3Uw1EbRoRmROTgfEbSUaAhwwxD7JsJsI8yVLhOM)
> 
> And Delete Bin And Obj Of Your Solution And Rebuild Or `dotnet restore` And Everything Done

Similar thing worked for a short while for me on Friday but stopped working yesterday. The 'Clear all Nuget Storage' button does a similar sort of thing, but no longer helping for me.

![image](https://github.com/dotnet/aspire/assets/2116108/1f6bb0b7-d029-4f24-9f9d-8a49e9441146)

Interesting finding with the schema @Mortana89, how did you discover that?

**Comment by Mortana89** [comment]
I booted up Fiddler 

> > Solution One (This Worked With Me)
> > You Have To Just Try This It Worked With Me Go To .nuget Folder
> > C:\Users{UserName}.nuget
> > And You Can Delete The .nuget Folder Or You Can Rename It Like I Do ![image](https://private-user-images.githubusercontent.com/104096256/310139431-e1543e32-f33a-4f5e-a85b-e159b29e00d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDYzODAsIm5iZiI6MTcwOTY0NjA4MCwicGF0aCI6Ii8xMDQwOTYyNTYvMzEwMTM5NDMxLWUxNTQzZTMyLWYzM2EtNGY1ZS1hODViLWUxNTliMjllMDBkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMzQxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2QwODY0ZmMzZDkyYzk2MGNlZDlmZjc2YmFlOGZiYjg4MjM4YmMzMjkwMGE0NzI3OTEyNzI0MzFkYmE0ZmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zpgB3Uw1EbRoRmROTgfEbSUaAhwwxD7JsJsI8yVLhOM)
> > And Delete Bin And Obj Of Your Solution And Rebuild Or `dotnet restore` And Everything Done
> 
> Similar thing worked for a short while for me on Friday but stopped working yesterday. The 'Clear all Nuget Storage' button does a similar sort of thing, but no longer helping for me.
> 
> ![image](https://private-user-images.githubusercontent.com/2116108/310141556-1f6bb0b7-d029-4f24-9f9d-8a49e9441146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDY3ODgsIm5iZiI6MTcwOTY0NjQ4OCwicGF0aCI6Ii8yMTE2MTA4LzMxMDE0MTU1Ni0xZjZiYjBiNy1kMDI5LTRmMjQtOWY5ZC04YTQ5ZTk0NDExNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTM0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTlhNTJmMzJmOWE0Y2ZkZDI5NjljYTgwNmVkYzhmODUyNzA2ZDQ2NGQ2ZWJlNGZjMzFkNjYxODAxMmMxMGU3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u27lJWe-2rnAnEbyoIzpnA-OmP-wfP77rAg-L20BS8g)
> 
> Interesting finding with the schema @Mortana89, how did you discover that?

I booted up Fiddler to see if I could trace it back to nuget or something else, and found out it was the schemastore (there's a ticket open there since friday apparently). What I did now was remove the mentioned section from the aspire targets file. Don't know what the impact will be but I can continue for now without these errors.
I also tried disabling/removing the schemastore source from the VS settings but to no avail, only removing this from the targets file seems to do the trick

**Comment by mip1983** [comment]
Thanks @Mortana89, just done the same modifying the aspire targets file, seems to have got me up n running without side effect so far.

**Comment by yajiegithub** [comment]
> 解决方案一（这适用于我）
> 
> 你必须试试这个，它和我一起去.nuget文件夹
> 
> C：\Users{用户名}.nuget
> 
> 您可以删除 .nuget 文件夹，也可以像我一样重命名它 ![image](https://private-user-images.githubusercontent.com/104096256/310139431-e1543e32-f33a-4f5e-a85b-e159b29e00d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTQ1MTYsIm5iZiI6MTcwOTY1NDIxNiwicGF0aCI6Ii8xMDQwOTYyNTYvMzEwMTM5NDMxLWUxNTQzZTMyLWYzM2EtNGY1ZS1hODViLWUxNTliMjllMDBkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxNTU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTI1MWYzNGU5NTE4NWVmNmM3Zjg4Njk2NDMwN2ViZGU5NTJlZDc4NTZhYmUxNDU4NTYwNjZhYmQ3MmE5MTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7iJneBaMVqmi0XexkrrCAqR4bp3Ue-XCLs07Odh5LDE)
> 
> 并删除解决方案的 bin 和 obj 并重建或完成所有操作`dotnet restore`

Thank you ，I waste 2 week

**Comment by mip1983** [comment]
It looks like 'https://schemastore.org/json/' is back up now, so will try restoring the targets file.

I guess this file is part of the aspire workload? Hopefully this can be updated with a more graceful fallback if this site goes down again, or get built in so it doesn't have this web dependency that essentially takes down visual studio 2022 if it's down.

**Comment by danmoseley** [comment]
@Mortana89 is this good to close now? for this below it might be clearer to open a new issue and close this one.

> Hopefully this can be updated with a more graceful fallback if this site goes down again, or get built in so it doesn't have this web dependency that essentially takes down visual studio 2022 if it's down.
