### ISSUE TITLE
Consider renaming `AddOracleDatabase`.

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/aspire#2646]
There are several variations of database server resources modeled within .NET Aspire. Many of the APIs that exist support chaining from a container/server resource to add a database. The `AddDatabase` extension lights up for these resource types. Consider the following names:

- SQL: `AddSqlServer` and `AddDatabase`
- MySQL: `AddMySql` and `AddDatabase`
- Postgres: `AddPostgres` and `AddDatabase`
- MongoDB: `AddMongoDB` and `AddDatabase`

Currently, this API stands out as the `AddOracleDatabase` adds the server resource as a container but not a database as the name might imply:

- Oracle: `AddOracleDatabase` and `AddDatabase`

For the sake of consistency, I propose a rename API as follows:

- Oracle: `AddOracle` and `AddDatabase`

```diff
-IResourceBuilder<OracleDatabaseServerResource> AddOracleDatabase
+IResourceBuilder<OracleDatabaseServerResource> AddOracle
```

**Comment by davidfowl** [comment]
Good point! Obsolete the old API and add new one.
