### ISSUE TITLE
Review use of ArgumentException/ArgumentNullException in all public APIs

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2649]
I noticed we seem to have lots of public APIs that accept reference type parameters not marked as nullable but then don't check that they're actually non-null and throw an `ArgumentNullException` when necessary. We should decide what we're doing and review all public APIs for appropriate argument validation.

e.g. https://github.com/dotnet/aspire/blob/240cde74a83cc5378a90c2b6eeb8d65f43658d80/src/Aspire.Hosting/Extensions/ResourceBuilderExtensions.cs#L92-L98

**Comment by mitchdenny** [comment]
@JamesNK your PR mentioned this issue, do you think we've got 100% coverage here now from your #2809 PR?

**Comment by JamesNK** [comment]
Probably not. And there have been new APIs since then.
