### ISSUE TITLE
Bug: Failed to deploy because of error listing connection strings off deployed Cosmos instance

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspire#2668]
I've got a very simple deployment that failed. You can see it spans Cosmos, adds an annotation to the utilities project to bundle Playwright with it and.. that's it.

```cs
var builder = DistributedApplication.CreateBuilder(args);

var cosmos = builder.AddAzureCosmosDB("cosmos");

builder.AddProject<Projects.Utilities>("utilities")
    .WithAnnotation(new ContainerImageAnnotation
    {
        Image = "mcr.microsoft.com/playwright",
        Tag = "v1.42.0-jammy"
    })
    .WithReference(cosmos);

builder.Build().Run();
```

I ran the following commands:
```shell
azd login
azd init
azd up
```

This successfully completed the step that reads "SUCCESS: Your application was provisioned in Azure in 2 minutes 6 seconds." and I see that it deployed a Container Registry, a Container Apps environment, Cosmos DB, Log Analytics, and a Managed Identity. 

It failed upon attempting to deploy the services:

```
ERROR: failed deploying service 'utilities': failing invoking action 'deploy', failed executing template file: template: containerApp.tmpl.yaml:21:19: executing "containerApp.tmpl.yaml" at <connectionString "cosmos">: error calling connectionString: POST https://management.azure.com/subscriptions/5cec4120-f436-4a94-8a6e-************/resourceGroups/rg-myapp-web/providers/Microsoft.DocumentDB/databaseAccounts/cosmosholua67mc6kj2/listConnectionStrings
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: InvalidAuthenticationTokenTenant
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidAuthenticationTokenTenant",
    "message": "The access token is from the wrong issuer 'https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-************/'. It must match the tenant 'https://sts.windows.net/efbbaae1-f282-4ff1-8f02-************/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/efbbaae1-f282-4ff1-8f02-************' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
  }
}
--------------------------------------------------------------------------------
```

I haven't transferred anything on this tenant in months (years?) and this is my first attempt to ever try deploying anything to it. Notably weird here too is that I have this message only after successfully creating all the other resources. It's only when it attempts to get the connection strings from one of those deployed resources that it all comes apart.

Anyway, filing as a bug report in hopes it can be resolved sooner than later. Thanks!

**Comment by davidfowl** [comment]
Can you file this on https://github.com/Azure/azure-dev/issues?

**Comment by davidfowl** [comment]
Also radom question, what is the purpose of this logic:

```
builder.AddProject<Projects.Utilities>("utilities")
    .WithAnnotation(new ContainerImageAnnotation
    {
        Image = "mcr.microsoft.com/playwright",
        Tag = "v1.42.0-jammy"
    })
    .WithReference(cosmos);
```

**Comment by WhitWaldo** [comment]
> Also radom question, what is the purpose of this logic:
> 
> ```
> builder.AddProject<Projects.Utilities>("utilities")
>     .WithAnnotation(new ContainerImageAnnotation
>     {
>         Image = "mcr.microsoft.com/playwright",
>         Tag = "v1.42.0-jammy"
>     })
>     .WithReference(cosmos);
> ```

Oh, I saw it in the Intellisense and wanted to see what it would do. Just an experiment I neglected to remove. 

The idea was to see if I could deploy Playwright alongside the .NET application in one container instead of explicitly making a separate resource and figuring out how to connect to it, but as it's not deploying, I've had some difficulty testing it.

**Comment by davidfowl** [comment]
Got it, well that doesn’t work at all 😅

**Comment by WhitWaldo** [comment]
Yeah, I noticed... is there anything on the roadmap for something like that? A way to add additional instructions to the container that's built for each application since there's no explicitly separate Docker file?

**Comment by davidfowl** [comment]
> Yeah, I noticed... is there anything on the roadmap for something like that? A way to add additional instructions to the container that's built for each application since there's no explicitly separate Docker file?

That would be building your own docker file. We don't have an API for programmatically building up the docker file.
