### ISSUE TITLE
Accessibility onboarding for .NET Aspire Dashboard

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#2681]
@adamint 

- [x] Ensure that all bugs identified by Accessibility Insights tool are fixed
- [x] Review the application and scenarios with the accessibility testing team
- [x] Document the scenarios and review the test case document provided by testers
- [ ] <del>Validate and fix  Sev1 and Sev2  bugs identified</del>

**Comment by adamint** [comment]
@kvenkatrajan Since 1-3 are complete, does this issue need to be kept open as testers file issues? Or should we just mark those when they come in as sev1/2

**Comment by kvenkatrajan** [comment]
@adamint - I am closing this for the accessibility onboarding request for .NET Aspire dashboard. I will request individual issues to be created for the issues identified.
