### ISSUE TITLE
Update to stable OpenTelemetry packages before GA

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2688]
We currently depend on a [number of unstable (i.e. preview) OpenTelemetry packages](https://github.com/dotnet/aspire/blob/100e3914a76bf2d1e3adf8dcc9242fe4517064c0/Directory.Packages.props#L112-L120) in various places including templates and components. We can't ship NuGet packages with stable versions or the Aspire project templates for GA while they depend on unstable packages. While it's planned that some component packages will remain in preview after the initial GA (#2541) the project templates and components like Redis need to have the unstable package references removed before we can ship the GA.

**Comment by eerhardt** [comment]
Yes, this work is now done with:

* https://github.com/dotnet/aspire/pull/2864
* https://github.com/dotnet/aspire/pull/3027
* https://github.com/dotnet/aspire/pull/3059
* https://github.com/dotnet/aspire/pull/3110
* https://github.com/dotnet/aspire/pull/3104
