### ISSUE TITLE
Could not query logs on the docker container (microcks or any docker image that we pull in our local dev env) running on Podman native

### ISSUE THREAD

**Issue by thangchung** [dotnet/aspire#2701]
Currently, when running the app with Podman native, we got the exception below

![image](https://github.com/dotnet/aspire/assets/422341/a2b92e9a-0ef5-458a-a634-bff07b6457e0)

```cs
Error when executing service method 'WatchResourceConsoleLogs'.
      System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'docker.exe' with working directory '<our app-host file path>'. The system cannot find the file specified.
```
I think because some places still hard code to `docker.exe` in the Aspire code base at the moment:

https://github.com/dotnet/aspire/blob/07a5044c1f512bf3034259cd03224e7179e964d6/src/Aspire.Hosting/Dashboard/DockerContainerLogSource.cs#L27

https://github.com/dotnet/aspire/blob/07a5044c1f512bf3034259cd03224e7179e964d6/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs#L163

It did not make the `Aspire Dashboard` crash, but it did not show any logs as in the picture below.

![image](https://github.com/dotnet/aspire/assets/422341/7fc4fbfa-ca02-4302-8809-bcf914fb91b0)

/cc @davidfowl And this issue is related to https://github.com/dotnet/aspire/issues/2639 as well.

**Comment by davidfowl** [comment]
Ah I forget we didn't get streaming logs into preview 4. This will work in preview 5.  Unfortunate here for podman though.

cc @karolz-ms @danegsta

**Comment by karolz-ms** [comment]
@thangchung can you try adding a symlink from `docker` to `podman`? I believe this should unblock you.

**Comment by thangchung** [comment]
@karolz-ms I created the symlink `fsutil hardlink create docker.exe "C:\Program Files\RedHat\Podman\podman.exe"`, but it could not work

**Comment by davidfowl** [comment]
This is a miss on our part @thangchung, it'll be in the known issues list for preview 4 but will be fixed in preview 5.

**Comment by davidfowl** [comment]
@karolz-ms I'll assign this to you because your streaming logs change will fix it.

**Comment by thangchung** [comment]
> @thangchung can you try adding a symlink from `docker` to `podman`? I believe this should unblock you.

@karolz-ms  I could make it work around as you suggest by using the command:

For example, set the variable environment (`PATH`) into `C:\sw`

Then

```sh
cmd /c mklink "C:\sw\docker.exe" "C:\Program Files\RedHat\Podman\podman.exe"
```

And now it worked:

![image](https://github.com/dotnet/aspire/assets/422341/fb9ef8ac-1b6c-4158-923e-792123650984)


> This is a miss on our part @thangchung, it'll be in the known issues list for preview 4 but will be fixed in preview 5.
@davidfowl It would be great to make it work natively in Preview 5. Thanks

**Comment by balachir** [comment]
@davidfowl sure. Good to know about this workaround.

**Comment by davidfowl** [comment]
I assume we will need instructions for the MacOS and Linux too. Though tbh this partially defeats the purpose of using podman because you cant install docker 😢.

**Comment by karolz-ms** [comment]
> I assume we will need instructions for the MacOS and Linux too. Though tbh this partially defeats the purpose of using podman because you cant install docker 😢.

Not sure what you mean. Aliasing `docker` to `podman` is a very well-known workaround among Podman users https://docs.podman.io/en/latest/index.html#what-is-podman

**Comment by davidfowl** [comment]
Ah I wasn't thinking straight,  this is just aliasing the name docker to podman to make it work, not haivng to install docker to make  podman work. That's a good workaround and we can point to those docs 😄

**Comment by davidfowl** [comment]
This should be resolved with https://github.com/dotnet/aspire/pull/2744.
