### ISSUE TITLE
[AzureTools][Aspire] Pop up an error in the Terminal after clicking "View" in the "Logs" of container on Podman Desktop

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#2705]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS rel.d17.10-34706.200
**Aspire Version:** 8.0.0-preview.4.24156.9
Apply NuGet Feeds
**Regression:** Not a regression
**Podman Desktop:** 1.7.1
**Podman:** 4.9.2

**REPRO STEPS:**

1. Create a Aspire starter project with command 
    > _dotnet new aspire-starter --use-redis-cache_
2. F5
3. In the dashboard, click "View" in the "Logs" of container.

**Expect:**
You can see the container’s logs in the automatically redirected web page.
![image](https://github.com/dotnet/aspire/assets/62053665/04f756b1-b3f9-4a26-b73a-0c3322de98a5)

**Actual:**
Pop up an error in the Terminal and there are no logs in the automatically redirected web page.
![image](https://github.com/dotnet/aspire/assets/62053665/f609b06b-6228-468a-9466-514deaaecc45)

**More Info:**
1. This issue also **reproduces** on the VS 17.10.0 Preview 2.0 [34705.46.d17.10] (Includes Aspire 8.0.0-preview.4.24129.7).
2. This issue **doesn't reproduce** with Docker Desktop installed.

**Comment by v-mengwe** [comment]
There is a workaround：
On Windows:
1. set the variable environment () into `PATHC:\sw`
2. execute the command
    `cmd /c mklink "C:\sw\docker.exe" "C:\Program Files\RedHat\Podman\podman.exe"`

On MacOS:
1. Find the path of podman
2. Check there is no docker in the /usr/local/bin, and then execute the command in the Terminal:
    `sudo ln -s "#the path of podman" "/usr/local/bin/docker"`

**Comment by balachir** [comment]
Setting this to P5 milestone as it impacts the E2E experience using Podman

**Comment by davidfowl** [comment]
This should be fixed now
