### ISSUE TITLE
[WebToolsE2E][Aspire] Some contents in the Aspire template are not localized in CHS OS.

### ISSUE THREAD

**Issue by Coleen17** [dotnet/aspire#2722]
**REGRESSION INFO:** Repro on Dev17.10 Preview 1 (Includes Aspire 8.0.0-preview.3.24105.21)

**TESTCASES AFFECTED**
Aspire Templates

**INSTALL STEPS**

1. Clean machine: Win11 x64 22h2 CHS
2. Install 17.10.0 Preview 2.0 [34629.198.main] (Includes Aspire 8.0.0-preview.4.24128.4)
3. Apply NuGet Feeds

**REPRO STEPS**
1. Open VS > click "Create new project" > Type "Aspire" in the search bar.

**ACTUAL:**

The project template is not localized.

![image](https://github.com/dotnet/aspire/assets/154579712/2ceb2b2e-24cd-454f-b162-95ea351e70cd)

Select '.NET Aspire Starter Application' > Next

![image](https://github.com/dotnet/aspire/assets/154579712/f049685f-7a51-408e-aaa3-4b8fc282585c)

**EXPECTATION:**
Aspire Templates should be localized in CHS OS.

**Comment by balachir** [comment]
@joperezr @danegsta @dbreshears I don't know if we have the infrastructure in the aspire repo already to localize template UI. I'm proactively setting the milestone to P5 for this issue, please triage and move out if needed.

**Comment by joperezr** [comment]
We had an email thread about this. We do have the required infrastructure for localization, but it looks like these templates require additional changes to support this. Thanks for triaging as P5, we should get to this by then.
