### ISSUE TITLE
Expose ability to run containers with access to GPUs

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/aspire#2737]
One of the prerequisites for running AI container workloads on NVIDIA GPUs is the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).

Once that's installed, when you run the container, you need to pass the `--gpus` flag. 

Right now there doesn't appear to be a way to configure a container resource in the AppHost project such that it can be started with GPU support, e.g. on Docker for Windows, the container must be run like `docker run -d --gpus=all ...`.

**Comment by dbreshears** [comment]
This is tracked by https://github.com/microsoft/usvc/issues/141

**Comment by dbreshears** [comment]
@davidfowl.   Looks like this is going to need to be pushed to Preview 6?  Any objections?

**Comment by dbreshears** [comment]
Moving to P6.  I don't see us getting the PR through on the app model side for P5.
