### ISSUE TITLE
RabbitMQ password

### ISSUE THREAD

**Issue by pedershk** [dotnet/aspire#2755]
It seems like the ability to set a fixed password for RabbitMQ disappeared sometime between Preview 3 and later nightly builds. The (generated) password on initial startup (no volumes/new volume) is correctly exposed in connection string, but any subsequent runs results in clients not being able to connect, as the password seems to change across reboots.

So, two questions:
1) Why was the ability to set a fixed password removed?
2) Is the behavior above expected, and if so, does any remedy exist when connecting from clients?

**Comment by mitchdenny** [comment]
Its back in preview 5. Here is an example:

```csharp
var rabbitMqPassword = builder.AddParameter("rabbitmq-password", secret: true);
var messaging = builder.AddRabbitMQ("messaging", password: rabbitMqPassword)
                       .WithDataVolume()
                       .WithManagementPlugin()
                       .PublishAsContainer();
```

Try it out and let us know if it works for you.

**Comment by pedershk** [comment]
> Its back in preview 5. Here is an example:
> 
> ```cs
> var rabbitMqPassword = builder.AddParameter("rabbitmq-password", secret: true);
> var messaging = builder.AddRabbitMQ("messaging", password: rabbitMqPassword)
>                        .WithDataVolume()
>                        .WithManagementPlugin()
>                        .PublishAsContainer();
> ```
> 
> Try it out and let us know if it works for you.

Great!

(Preview 5 isn't out yet, right? - has the "release build" been cut on nightlies? If so - which one :D)

**Comment by mitchdenny** [comment]
Preview 5 will be released VERY soon :)
