### ISSUE TITLE
Azure Dashboard OTLP Receiver - Verify HTTP Header Key before accepting telemetry

### ISSUE THREAD

**Issue by iphdav** [dotnet/aspire#2757]
@JamesNK and @davidfowl Can we please add a HTTP Header key *optional* check for the received OTLP telemetry.  When emitting telemetry it is very easy to add a HTTP Header with a key.  Can we please use the configuration system to obtain the name of the HTTP Header to use, and the value that must be matched before accepting telemetry?  This would only be a 1-2 line change in the project.  

I have mocked this up by reading the key from config during startup like this:
```cs
// OTLP services.
var telemetryKey = builder.Configuration["Telemetry:Key"];
builder.Services.AddGrpc(options => options.Interceptors.Add<OtlpInterceptor>(telemetryKey!));
```

Then I changed the OtlpInterceptor.cs to this:
```cs
internal sealed class OtlpInterceptor(string? telemetryKey) : Interceptor
{    
    public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
        =>  telemetryKey is null || (context.GetHttpContext().Request.Headers.TryGetValue("X-Telemetry-Key", out var key) && key == telemetryKey)
            ? base.UnaryServerHandler(request, context, continuation)
            : throw new RpcException(new Status(StatusCode.PermissionDenied, "OTLP telemetry header key not provided or not correct.")); 
}
```

Obviously we should allow the user to specify the name of the HTTP Header to use in the config system.  But could we please add something like this to a future version of the Aspire Portal?

**Comment by JamesNK** [comment]
Good news, that's something we plan to do. Here is a PR with some auth stuff that is in progress: https://github.com/dotnet/aspire/pull/2316

It's useful for us to understand how people are using Aspire. Where are you running the dashboard? Why is securing OTLP useful for you?

**Comment by iphdav** [comment]
@JamesNK Thanks and that PR looks great (doing the API Key auth the standard dotnet way).

**Comment by iphdav** [comment]
@JamesNK I am running the Dashboard as an Azure App Service (Windows with the new GRPC support enabled), unrelated to the rest of Aspire, but capturing telemetry from our dev environment.  So I needed to add Entra ID for the Blazor UI login, plus added the API Key stuff for the inbound telemetry.  I love Blazor and this Dashboard is a nice UI to have in-memory (dev) telemetry be delivered to in-memory (Aspire Dashboard) UI that is almost real time.  We use Application Insights for the production stuff.  I don't want the complexity of a separate collector or anything else.

**Comment by kvenkatrajan** [comment]
Closing based on auth PR merge #2316
