### ISSUE TITLE
Azure Dashboard - Entra ID / Microsoft Identity Login

### ISSUE THREAD

**Issue by iphdav** [dotnet/aspire#2758]
The new .NET 8 blazor web project template seems to have dropped support for Microsoft.Identity auth, and it is currently planned for .NET 9.  Thus setting up Entra ID authentication is a little tricky the first time with the Dashboard UI.  I think we should have clear documentation for how this can be added to the Aspire Dashboard project, as it took me a little bit of playing around to set this up (so I could host the Aspire Dashboard as an Azure Web Application).

It is probably reasonable we keep this as *instructions* and not incorporate identity in the default dashboard project, given it requires taking a dependency on the Microsoft.Identity.Web and Microsoft.Identity.Web.UI nuget packages.  I would love it though if the Aspire Dashboard could become a nuget package (again), with hooks such that we could provide instructions to set this up simply by referencing the Aspire Dashboard nuget package, along with the Microsoft Identity packages (and a custom start-up class)

We can work on getting some instructions added to the official aspire documentation, but in general these steps worked for me:
* Adding the Microsoft Identity nuget packages
* Adding the appropriate AzureAd configuration to appSettings.json.
* Creating a LoginDisplay.razor component the provides a logout link, and putting it in the FlexHeader inside the MainLayout.razor.

When starting up, adding ```_app.UseAuthorization();``` and because we want the Microsoft Identity controller login/logout razor pages, I needed to add ```_app.MapControllers();``` and finally the blazor UI needed authorization, which I did via a policy like this:
```cs
_app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode()
    .RequireAuthorization("StaffPolicy"); 
```

Note: The reason I defined a specific policy "StaffPolicy" was because I only wanted to apply the policy to the Dashboard UI, and not the OTLP telemetry (the default policy was not to require auth).  When adding the Microsoft Identity services to the services collection, you do this the same way you would have done in .NET 7, but do not forget to add: 
```cs
builder.Services.AddCascadingAuthenticationState();
```

I now have the Aspire Dashboard running as an Azure Web Application, using Microsoft Identity auth, all running over a single HTTPS port (used for both OTLP receiver and the Dashboard UI), plus we are verifying a HTTP Header key in the inbound telemetry.  If the team wants help getting any official documentation together for this, let me know.  But my preference would be to get the Aspire Dashboard back as a nuget package, then we work on some documentation on how to use the aspire.dashboard and microsoft.identity nuget packages with some custom startup login to hook this all together.

**Comment by kvenkatrajan** [comment]
#3033 (in preview 5 release) - this has some oidc support for integration for Entra ID.

**Comment by kvenkatrajan** [comment]
@drewnoakes please confirm if we are good to close this.

**Comment by drewnoakes** [comment]
@iphdav we now have support in the dashboard for OIDC-based auth. The README file details the configuration options.

I'm going to close this as completed, but please let us know if there's anything else you'd expect to see here.
