### ISSUE TITLE
Write host bind mounts to the Manifest

### ISSUE THREAD

**Issue by prom3theu5** [dotnet/aspire#2761]
This is a feature request to expand on the groundwork merged in with #2742
Following on from that work it would be beneficial for downstream deployment tool creators if host bind mounts were output to the manifest as a lot of the time local bound host mount folders contain configuration data

Examples of these (but not limited to):
- Loki Config
- Promtail Config
- Postgres-Exporter config
- Grafana Dashboards
- Grafana Datasources
- Mounted .net configuration files

 Any static file really
 
 Having the paths, and type (host for example) within the manifest would allow bundling these assets within init-containers that could be used in both k8s and docker-compose.

**Comment by DamianEdwards** [comment]
Proposed format for bind mounts in the manifest:

```json
...
  "bindMounts": [
    {
      "source": "./some/dir/or/file",
      "target": "/mount/here/pls",
      "readOnly": false
    },
    {
      "source": "./another/path/initdb",
      "target": "/docker-entrypoint-initdb.d",
      "readOnly": true
    }
  ],
...
```

- Source paths will always be relative to the AppHost project directory unless they're fully qualified (e.g. `D:\some\path`) and always in forward-slash notation
- `"readOnly"` matches the naming of the same flag in the volumes section
