### ISSUE TITLE
[WebToolsE2E][Aspire] 9.0 P2 build is branded as preview.1 instead of preview.2

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#2774]
**INSTALL STEPS**

Clean machine: Win11 x64 23h2 ENU

1. Install SDK 9.0 Preview 2

   - Apply feed for SDK 9.0 P2 

1. Install Aspire SDK 9.0 P2 workload

   - Download installLatest90p2FromReleaseBranch.ps1 to your Downloads folder  
   - Open/Run Powershell as an administrator, change the execution policy to run the script 
     `Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine` 
   - Run the installLatest90p2FromReleaseBranch.ps1 script 
     `powershell.exe "C:\Users\<user-name>\Downloads\installLatest90p2FromReleaseBranch.ps1"`

**ACTUAL**
The Aspire version is 9.0.0-preview.1.24160.5

**EXPECTED**
The Aspire version should be branded as 9.0.0-preview.2

**Comment by v-elenafeng** [comment]
The milestone should be '8.0 preview 4' and this issue needs to be fixed before this week's Tuesday release. @joperezr

**Comment by joperezr** [comment]
Yes, I'll fix this today.

**Comment by joperezr** [comment]
Fixed via #2784.
