### ISSUE TITLE
[BUG] The .NET Aspire dashboard resource filter doesn't remove selections

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/aspire#2776]
When you're on the .NET Dashboard Resources tab, and you apply a filter, the selected detail view isn't reset. I would have expected that when I apply a filter that removes a resource (filters it out) that if it was previously selected for details, it would be no longer selected.

I only have **Container** resource types selected, however, my previous **Project** details view is still displayed. This isn't a huge problem, so low priority, just not the behavior I expected.

![image](https://github.com/dotnet/aspire/assets/7679720/2eb7fad4-f1bf-4b18-882b-cf7b78df07d2)

**Comment by tlmii** [comment]
Assuming we'd like this to apply to all pages with filters and selection, not just `/resources`. @JamesNK in case you have any thoughts on the functionality or alternatives in those other pages.

**Comment by JamesNK** [comment]
I think this would just apply to resources and structured logs.

Traces opens a new page. Trace detail doesn't have filtering (yet)

**Comment by tlmii** [comment]
@JamesNK Thinking more about the structured logs case:

1. I had the resources page only closing the details panel if the selected resource was not in the filtered list
2. It doesn't seem like the selected log entry being outside of the current page of data should cause the details pane to close, so
3. Determining if the selected log entry is still in the updated filtered list would require checking the entire (filtered) unpaged log set. Which depending on the filter could still be a very large set

Do you think it makes more sense to just always clear the selected log entry when the filter changes (and possibly change my implementation for resources to always clear as well)?
