### ISSUE TITLE
Do not allow `-` for builder.AddBicepTemplate().WithParameter() function.

### ISSUE THREAD

**Issue by vhvb1989** [dotnet/aspire#2783]
Something like this is currently valid for the AppHost code:

```csharp
var bicep1 = builder.AddBicepTemplate("test", "test.bicep")
                   .WithParameter("param-01", parameter)
```

However, `param-01` is an invalid name for a parameter and the program should return an error here.

**Comment by davidfowl** [comment]
@mitchdenny giving this to you
