### ISSUE TITLE
Update to final versions of our dependencies

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#2785]
Stuff in directory.packages.props.

**Comment by joperezr** [comment]
Target date for version update: 4/25

cc: @eerhardt

**Comment by mitchdenny** [comment]
Assigning to @joperezr since he'll probably be the whip in this case :)

But this is 90% done for the Aspire.Hosting.Azure.* packages, just waiting for AppInsights.

**Comment by tg-msft** [comment]
@mitchdenny - is there anything left here now that we've got AppInsights too?

**Comment by mitchdenny** [comment]
No. Closing this
