### ISSUE TITLE
Dashboard should remember user's page on restart

### ISSUE THREAD

**Issue by terrajobst** [dotnet/aspire#2787]
I love the dashboard. However, for many of the standard things I'm doing I find I can't use hot reload and therefore need to re-launch the process.

Then it's frequently annoying if I have to change the view in the dashboard (e.g. from `Resources` to `Traces`) and having to change the combo box value (e.g. `myapiservice12`).

Couldn't we make the dashboard use cookies to retain the current view (page and whatever else is relevant, such as combo box selections)?

**Comment by eerhardt** [comment]
Another example of this is when you have a filter set on the `Structured Logs`, and then navigate to a Trace. When you are done looking, you navigate "back" and your filter is lost.

**Comment by adamint** [comment]
This has been completed in the past, we just forgot to close this ticket.
