### ISSUE TITLE
Dashboard should request log streams only when the user gestures to display them (for given resource)

### ISSUE THREAD

**Issue by karolz-ms** [dotnet/aspire#2789]
With https://github.com/dotnet/aspire/pull/2731/ the dashboard requests log streams for all application resources at the startup or shortly after. This is not efficient, especially for Containers, where each log stream is associated with a separate container orchestrator (CLI) running in the background.

**Comment by davidfowl** [comment]
Made progress on this here https://github.com/dotnet/aspire/tree/davidfowl/on-demand-logs. Not seeing DCP kill the docker logs command on cancellation.
