### ISSUE TITLE
Testing: allow logs to flow into test output

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/aspire#2790]
When developers use `Aspire.Hosting.Testing`, they would benefit from seeing logs in test output. We should add this. Logs are accessible via `Aspire.Hosting.ResourceLoggerService`. See also `ResourceNotificationService`

**Comment by davidfowl** [comment]
We're going to move this to the backlog and instead write a sample showing how to flow logs via xunit's `ITestOutputHelper`.

**Comment by DamianEdwards** [comment]
Can you update the issue to add a testing sample in the samples repo please to capture this?

**Comment by davidfowl** [comment]
https://github.com/dotnet/aspire-samples/issues/164
