### ISSUE TITLE
Startup error about Docker being in an unhealthy state

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/aspire#2794]
_Using Aspire Preview 4_

When trying to launch, I received an error message that Docker was in an unhealthy state and the response from the daemon was:

> Error response from daemon: failed to retrieve container list: rw layer snapshot not found for container 6f38831b07a4ce9f59b2ffde6a4180d93cf703659f8134b787b30df9aa7d77ec

This prevented the AppHost from launching.

Here's the full log output:

```
{"level":"debug","ts":"2024-03-12T11:09:33.266+1100","logger":"info","msg":"runtime status","runtime":"podman","status":{"Installed":false,"Running":false,"Error":"exec: \"podman\": executable file not found in %PATH%"}}
{"level":"debug","ts":"2024-03-12T11:09:35.092+1100","logger":"info","msg":"runtime status","runtime":"docker","status":{"Installed":true,"Running":false,"Error":"Error response from daemon: failed to retrieve container list: rw layer snapshot not found for container 6f38831b07a4ce9f59b2ffde6a4180d93cf703659f8134b787b30df9aa7d77ec"}}
{"level":"debug","ts":"2024-03-12T11:09:35.093+1100","logger":"info","msg":"docker"}
{"level":"debug","ts":"2024-03-12T11:09:36.617+1100","msg":"exiting"}
```

## Fix

I looked at that container ID provided in the logs and noticed it was in a **Dead** status (partially deleted) and after manually deleting that container the AppHost launches successfully.

While it's a _simple fix_, it's not something that will be obvious to someone who isn't familiar with Docker.

**Comment by karolz-ms** [comment]
Unfortunately there is not much that we can do here beyond giving you the output of the docker/podman command (error message), which we do. There is A LOT of ways Docker or Podman can end up in a bad state ☺️
