### ISSUE TITLE
Azure OpenAI connection string not detected

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/aspire#2796]
I just upgraded https://github.com/aaronpowell/hanselminutesbot to using Preview 4 (`4.24156.9` package versions) but when I run the application I get an error:

`A connection string for 'AzureOpenAI' could not be retrieved`

This app was working with Preview 3 on the same machine with no problems - I just flipped over the NuGet package versions.

Attempting to debug myself it seems that the `ConnectionString` property of `AzureOpenAIResource` is returning `null`.

**Comment by aaronpowell** [comment]
I think the problem comes from this line change: https://github.com/dotnet/aspire/commit/bfd9376dc61c59971a2abad79ee7a546d3e93087#diff-7fd7862ce12369547085d74b5813ae529b1cdee8ab4024a4dbb23c2680539f3aR193

It removed the lookup to `builder.ApplicationBuilder.Configuration.GetConnectionString` if the resource failed to provide the connection string itself.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/issues/2395. This is one of the big changes in preview 5 that we need to resolve in P5.

**Comment by davidfowl** [comment]
Docs here https://github.com/dotnet/docs-aspire/pull/485

**Comment by aaronpowell** [comment]
Thanks, should have checked this before bugging @mitchdenny 🤣
