### ISSUE TITLE
Reconcile resource extensions and IResourceBuilder extensions

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2798]
Right now we have a split of methods that mutate annotations that live on the `IResouceBuilder<T>`. This means and lifecycle hook authors or anything looking at the raw resource list has to manually manipulate the underlying annotation collection instead of using the resource methods. We should build extensions on resources and call them from the resource builder methods. 

cc @mitchdenny

**Comment by mitchdenny** [comment]
Related #2988

**Comment by mitchdenny** [comment]
@davidfowl did you still want this for P6/GA? I think the best option here is to make the distributed application builder available on the execution context or via DI. The IDAB is actually available in many places after `Build()` has been called, so its not like this isn't something we already do.

Doing anything after `Build()` is always going to run into some corner cases unless we change the AppModel to be more reactive as resources are added to the model.

**Comment by davidfowl** [comment]
This ship has sailed
