### ISSUE TITLE
Argument validation in model

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2799]
The model is annotated properly for null. However, there is no runtime validation. If someone is configuring the model without nullable analysis enabled, then they could quite easily get hard to solve NRE.

The model should validate arguments. If something shouldn't be null then add `ArgumentNullException.ThrowIf(xxx)`.

**Comment by davidfowl** [comment]
Dupe of https://github.com/dotnet/aspire/issues/2649
