### ISSUE TITLE
Remove dependencies on OpenTelemetry.Instrumentation.EntityFrameworkCore

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#2814]
We use the [OpenTelemetry.Instrumentation.EntityFrameworkCore](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.EntityFrameworkCore/) nuget package in the following components:

* Aspire.Microsoft.EntityFrameworkCore.Cosmos
* Aspire.Microsoft.EntityFrameworkCore.SqlServer
* Aspire.Oracle.EntityFrameworkCore

As our plan is to stabilize .NET Aspire for `v8.0.0` we need to remove unstable dependencies. The `OpenTelemetry.Instrumentation.EntityFrameworkCore` package doesn't have a stable version, and there is no plan to make it stable by the time we ship `v8.0.0`. We need to remove this dependency from these 3 components.

@roji said in an offline conversation:

> This instrumentation library ([main code](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.EntityFrameworkCore/Implementation/EntityFrameworkDiagnosticListener.cs)) basically emits database client tracing (not metrics AFAIK) for command execution. This is something that we usually think belongs more at the lower ADO.NET layer (i.e. SqlClient, Npgsql..) rather than at the EF level - there's info at the lower levels that EF doesn't have, and EF doesn't necessarily have added value in emitting this tracing data.
> 
> In other words, an option here is to remove this library, and make it each provider's Aspire ADO.NET component's concern to enable tracing
> 
> Npgsql is already instrumented, so that's already there; for SqlClient we could use OpenTelemetry.Instrumentation.SqlClient

We should take this plan to remove this unstable dependency in the above components.

For `Aspire.Microsoft.EntityFrameworkCore.SqlServer`, it appears pretty straight-forward. We remove this dependency and instead replace it with `OpenTelemetry.Instrumentation.SqlClient`.

For the other 2 components, we need to work with the underlying ADO.NET layer to have the same instrumentation as Npgsql and SqlClient. (cc @Pilchie @kirankumarkolli for the Cosmos component. @andrevlins for the Oracle component)

cc @AndriySvyryd

**Comment by andrevlins** [comment]
Hi @eerhardt

In the case of Oracle, this change can only be implemented when they release the new version of the ADO library for Oracle (OPD.NET) that supports OTEL and metrics.

It is currently under development and its nuget package is a prerelease version.

If you remember, this was the reason we closed #1004 for now.

**Comment by Pilchie** [comment]
Tagging @kundadebdatta who is going to start looking at Cosmos DB/Aspire stuff soon.
