### ISSUE TITLE
Dashboard "Removed" state still shows green status

### ISSUE THREAD

**Issue by adamint** [dotnet/aspire#2816]
We should probably change this to a warning or error status 
<img width="469" alt="image" src="https://github.com/dotnet/aspire/assets/20359921/712264c2-d4bd-415d-94f1-ae5eaf7aa915">

**Comment by MatsM16** [comment]
What icon (if any) should be shown?

**Comment by davidfowl** [comment]
I think we need to let the resource server control the icon. The dashboard does a bit too much today. This is one of the protocol changes I want to make.

cc @drewnoakes

**Comment by davidfowl** [comment]
I think this problem still exists. The removed state *can* come from DCP directly and we don't set the icon for it anywhere.

**Comment by davidfowl** [comment]
@adamint we fixed this right?
