### ISSUE TITLE
Console logs doesn't support multiple ANSI arguments

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2838]
The console log doesn't support multiple ANSI arguments. See https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797

For example:
* `\x1b[31m` sets the text color to red
* `\x1b[44m` sets the background color to blue
* `\x1b[31;44m` sets the text color to red _and_ the background color to blue.

Multiple arguments aren't supported, and the ANSI escape code is displayed in the output:

![image](https://github.com/dotnet/aspire/assets/303201/8dd2877c-3892-44f0-9a4b-8414a885ae40)

**Comment by JamesNK** [comment]
cc @tlmii

**Comment by JamesNK** [comment]
I think we should ignore all the effects (bold, italics) and just think about colors. At the very least we should support background and foreground at the same time. Do we care about 256 colors/RGB colors? If simple to do, yes.

The escape sequence should never be shown.

**Comment by JamesNK** [comment]
This issue is visible in the RabbitMQ console logs in TestShop:

![image](https://github.com/dotnet/aspire/assets/303201/095c707b-c55c-471b-b4d1-15d431cba2a4)

**Comment by pierrebelin** [comment]
Does someone working on this one? I can take it if needed !
