### ISSUE TITLE
Console logs: Continuous !!! content in doesn't wrap

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2839]
![image](https://github.com/dotnet/aspire/assets/303201/94c254bd-10af-4f0a-8065-f37e2af30a2e)

See line 109.

Perhaps `overflow-wrap: anywhere;` will fix.

**Comment by tlmii** [comment]
@JamesNK I was thinking about the line wrapping in terms of the virtualization too. AzDO doesn't do line wrapping for the logs - that's how they support virtualization. Looks like GitHub does, not sure how they calculate their virtualization then...

**Comment by JamesNK** [comment]
Discuss virtualization here: https://github.com/dotnet/aspire/issues/2507

**Comment by tlmii** [comment]
My comment was a little half baked. My point was: an alternative to ensuring wrapping in these scenarios as suggested here is to match AzDO and not wrap at all. And that has the side benefit of easing the virtualization process. If we think virtualization is easy enough with variable height, then fixing this is no problem.

**Comment by JamesNK** [comment]
I don't think variable height + virtualization is easy.

AzDO doesn't wrap but everything else I've seen does: Terminals, GitHub actions, Docker Win UI
