### ISSUE TITLE
Console logs: Different color for line numbers and text

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2842]
AZDO has a slightly different color for line numbers:
![image](https://github.com/dotnet/aspire/assets/303201/24f59be9-0bee-4aa3-9b0c-5df6f50a3312)

GitHub actions has a slightly different color for line numbers:
![image](https://github.com/dotnet/aspire/assets/303201/5f8209cf-0ad3-4657-92ed-5740efbefa5d)

Aspire currently **doesn't**:
![image](https://github.com/dotnet/aspire/assets/303201/d3ebd03f-4dc3-4206-8167-e78ce81ccd2a)

IMO the line number text should be slightly different to show that's not part of the content and won't be selected with other text.

**Comment by tlmii** [comment]
One thing to consider, we already show the timestamp in a different color:

![image](https://github.com/dotnet/aspire/assets/9613109/9ad8dfb7-bf69-4bbe-89b4-69bf1e4da9ce)

This was similar to (though I guess opposite of) what docker desktop shows for logs:

![image](https://github.com/dotnet/aspire/assets/9613109/ccd24969-96d6-40f3-b816-da5fa787ba65)

Should the line number be the same gray as the timestamp? lighter/darker? should we change the way timestamps are displayed?

cc @leslierichardson95 @DamianEdwards

**Comment by tlmii** [comment]
@leslierichardson95 Any additional thoughts here? Not sure what to do. Could make line numbers the same color as timestamps, but the timestamps are selectable. Could try to find something in-between?
