### ISSUE TITLE
[WebToolsE2E][Aspire] An error occurs when installing the Aspire.Hosting.Azure package: "Package restore failed. Rolling back package changes for 'AspireApp1.AppHost'".

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#2843]
**REGRESSION INFO**: Not repro on Dev17.10.0 Preview 3.0 (Includes Aspire 8.0.0-preview.4.24156.9)

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [34712.219.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24162.15]
4. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > named it 'AspireApp1' > .NET 8.0 > Create
2. Right-click AspireApp1.AppHost project > Manage NuGet Packages > Search for Aspire.Hosting.Azure package and install the same version as Aspire

**ACTUAL**
Cannot add Aspire.Hosting.Azure package.
Error		Package restore failed. Rolling back package changes for 'AspireApp1.AppHost'.

Error	NU1102	Unable to find package Azure.ResourceManager.KeyVault with version (>= 1.3.0-alpha.20240310.2)
   Found 14 version(s) in nuget.org [ Nearest version: 1.2.0 ]
   Found 0 version(s) in Microsoft Visual Studio Offline Packages
   Found 0 version(s) in C:\Program Files\dotnet\library-packs
   Found 0 version(s) in dotnet8feed	AspireApp1.AppHost	C:\Users\v-reinawang\source\repos\AspireApp1\AspireApp1.AppHost\AspireApp1.AppHost.csproj	1	

Error	NU1102	Unable to find package Azure.ResourceManager.Authorization with version (>= 1.2.0-alpha.20240309.1)
   Found 6 version(s) in nuget.org [ Nearest version: 1.1.0 ]
   Found 0 version(s) in Microsoft Visual Studio Offline Packages
   Found 0 version(s) in C:\Program Files\dotnet\library-packs
   Found 0 version(s) in dotnet8feed	AspireApp1.AppHost	C:\Users\v-reinawang\source\repos\AspireApp1\AspireApp1.AppHost\AspireApp1.AppHost.csproj	1	

Error	NU1102	Unable to find package Azure.ResourceManager.Resources with version (>= 1.8.0-alpha.20240309.1)
   Found 18 version(s) in nuget.org [ Nearest version: 1.7.0 ]
   Found 0 version(s) in Microsoft Visual Studio Offline Packages
   Found 0 version(s) in C:\Program Files\dotnet\library-packs
   Found 0 version(s) in dotnet8feed	AspireApp1.AppHost	C:\Users\v-reinawang\source\repos\AspireApp1\AspireApp1.AppHost\AspireApp1.AppHost.csproj	1	

Error	NU1101	Unable to find package Azure.Provisioning. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, dotnet8feed, Microsoft Visual Studio Offline Packages, nuget.org	AspireApp1.AppHost	C:\Users\v-reinawang\source\repos\AspireApp1\AspireApp1.AppHost\AspireApp1.AppHost.csproj	1	

![image](https://github.com/dotnet/aspire/assets/109339894/6525560e-b7ca-4b6a-854b-9798fd8d44ea)

**EXPECTED**
Aspire.Hosting.Azure package can be added successfully.

**Comment by Dona278** [comment]
We have the same issues since ~two weeks. No latest nightly-preview can be installed
