### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2877]
I looked around the app in another language and spotted some parts that weren't translated. Double check that this text is all in resource files. If it already is then it might be new, and the translation isn't provided yet.

Level on structured logs:

![image](https://github.com/dotnet/aspire/assets/303201/56cda230-75a9-4b2b-9ce1-9b4125dcd795)

**Comment by JamesNK** [comment]
And "Graph" tab in metrics

![image](https://github.com/dotnet/aspire/assets/303201/cba51226-005a-48d4-a377-619d79ee4589)

**Comment by JamesNK** [comment]
![image](https://github.com/dotnet/aspire/assets/303201/1277469a-540c-494b-a53c-7e86c0fcc6cd)

"contains" and "not contains" in the structured logs advanced search.

**Comment by adamint** [comment]
> And "Graph" tab in metrics
> 
> ![image](https://private-user-images.githubusercontent.com/303201/312722842-cba51226-005a-48d4-a377-619d79ee4589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzk3NjMsIm5iZiI6MTcxMjE3OTQ2MywicGF0aCI6Ii8zMDMyMDEvMzEyNzIyODQyLWNiYTUxMjI2LTAwNWEtNDhkNC1hMzc3LTYxOWQ3OWVlNDU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QyMTI0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGE4NDlhZDg2YmNhNzAyZjYxYzkyMjc4MGEyMGE5ZDEyOWI2MDE5YThmZmExYzFkOTljNDc3N2QyMDFmNDhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X0P0HSrIB_6KyBr_GcVn6wDo1bd8ddI43Re0KJXFono)

This string is in resx, but just hasn't been localized yet.
