### ISSUE TITLE
[WebToolsE2E][Aspire] When using configuration providers to set the connection string, typing "ConnectionString": { }, it shows 'Value must be one of the following types: string'

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2881]
**REGRESSION INFO**: Also repro on Aspire 8.0.0-preview.3.24105.21 and Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 3.0 [34713.193.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire.ProjectTemplates.8.0.0-preview.5.24163.18
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. New Project > ASP.NET Core Web API > name it WebApplication1 > .NET 8.0 > None > check 'Enlist in Aspire Orchestration' > create
2. Right-click the WebApplication1 project > Add > .NET Aspire Component > install the Aspire.Azure.Messaging.ServiceBus with matched version.
3. Open appsettings.json of WebApplication1 project, following the README file to use configuration providers:
```
"Aspire": {
  "Azure": {
    "Messaging": {
      "ServiceBus": {
        "ConnectionString": { }
      }
    }
  }
}
```

**Note**:

1. This issue also repro on other components.
2. If type ` "ConnectionString": [serviceBusConnectionName]` , it won't show a warning.

**ACTUAL**
It will show warning of 'Connection string', not clear how to set the connection string when doing 'Use configuration providers' step.
![image](https://github.com/dotnet/aspire/assets/82028229/a4d37aa5-ef32-4f57-aca6-0f7d74ed33a8)

**EXPECTED**
Maybe should be similar with regular connection string setting
![image](https://github.com/dotnet/aspire/assets/82028229/72c78e00-8508-41f4-b7b3-54265bacb018)

**Comment by eerhardt** [comment]
> ACTUAL
> It will show warning of 'Connection string', not clear how to set the connection string when doing 'Use configuration providers' step.

That ConnectionString property on line 6 in your appsettings.json above is a string. So you should just set a string for that setting. 

But the recommended way of setting a connection string is by setting it like:

```
{
  "ConnectionStrings": {
    "serviceBusConnectionName": "{your_namespace}.servicebus.windows.net"
  }
}
```

That is what is described in the README.

The warning you are getting is because the JSON schema validation ensures you are setting it to a string, and you are setting it to an object.
