### ISSUE TITLE
How to support dacpac/sql proj installations

### ISSUE THREAD

**Issue by dotnetwizard** [dotnet/aspire#2888]
I currently have a system that runs locally using Docker and Docker Compose. It's a simple minimalist API and entity framework with an SQL server container. We are using a SQL server project that I can run, upload the dacpac to the SQL Docker container, and init the database for debugging. What options do we have with Aspire that would be able to work with a SQL project/dacpac? Unfortunately, we are not considering migrations now, which was a snap to get working with Aspire. Kudos btw. This is wonderful so far.

Here is the docker file I use for the SQL project:

`FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

RUN apt-get update \
    && apt-get install unzip libunwind8 libssl-dev -y

RUN wget -progress=bar:force -q -O sqlpackage.zip https://aka.ms/sqlpackage-linux \
    && unzip -qq sqlpackage.zip -d /opt/sqlpackage \
    && chmod +x /opt/sqlpackage/sqlpackage \
    && chown -R mssql /opt/sqlpackage \
    && mkdir /tmp/db \ 
    && chown -R mssql /tmp/db

COPY /AwesomeProject/bin/Debug/AwesomeProject.dacpac /tmp/db/db.dacpac

ARG DBNAME="DbName"
ARG PASSWORD="P@ssw0rd!"

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=$PASSWORD

RUN ( /opt/mssql/bin/sqlservr & ) | grep -q "Service Broker manager has started" \
    && /opt/sqlpackage/sqlpackage /a:Publish /tsn:localhost /tdn:DbName /tu:sa /tp:P@ssw0rd! /TargetTrustServerCertificate:true /sf:/tmp/db/db.dacpac \
    && rm -r /tmp/db \
    && pkill sqlservr \
    && rm -r /opt/sqlpackage`

**Comment by DamianEdwards** [comment]
I don't know much about SQL Server projects and dacpac but based on the docker file you showed, it should be possible to configure a SQL container in an Aspire AppHost project in a similar way. You can use the `WithBindMount` method to mount the dacpac file to the desired location in the container, and then the `WithEntrypoint` method to set the container entry command, either to your one-liner or put it in a bash script that's also mounted into the container and run that. Take a look at this example for a starting point

https://github.com/dotnet/aspire-samples/blob/31c6b9a6f6aacd06de31bc95d2af13867d57e64a/samples/DatabaseContainers/DatabaseContainers.AppHost/Program.cs#L25-L35

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/discussions/1696

**Comment by mitchdenny** [comment]
I think it might be interesting to try and make this work as if the sqlproj template was just a regular .NET project that could detect that it is running in the context of Aspire and auto apply itself to a sql instance that we pass the connection string in for?
