### ISSUE TITLE
Enable forwarded headers when publishing projects by default

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#290]
Given the primary deployment target for Aspire apps are container-based PaaSs that will very likely be using reverse proxies for ingress including TLS termination, etc., we should consider adding the [forwarded headers middleware](https://learn.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer) to the Aspire templates.

Thinking we put a method like the following in the ServiceDefaults project:

```csharp
public static WebApplication UseDefaultForwardedHeaders(this WebApplication app)
{
    app.UseForwardedHeaders(new()
    {
        ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost
    });

    return app;
}
```

We'll still need to figure out what the story is for configuring the `KnownProxies` property so that it actually works once deployed.

**Comment by DamianEdwards** [comment]
I don't think we have as strong a signal to do this now as we initially thought so moving to backlog.

**Comment by mip1983** [comment]
One vote for this from me, was certainly a tripping hazard that took a little while to figure out. Either including the env variable by default or just having  something in the project template that’s commented out as a hint (like the lines for telemetry)

```
var apiservice = builder.AddProject<Projects.ecoDriverAnalytics_Api>("ecodriver-analytics-api").WithEnvironment("ASPNETCORE_FORWARDEDHEADERS_ENABLED", "true")
```

**Comment by DamianEdwards** [comment]
@davidfowl thoughts here? Should we handle this on the deployment side as that's where the required knowledge about the destination platform and its behavior resides? Do you recall how known proxies factors into this if we just use the environment variable to enable the middleware, e.g. do we also have to configure known proxy hosts and hop count?

**Comment by davidfowl** [comment]
No, I think we should make it a method on the app model that isn't automatic. I also think we need to move the ingress or not to the app model.

**Comment by DamianEdwards** [comment]
Be careful not to conflate ingress with external/internal access. ACA has ingress for all containers that do networking, but external access is optional. As I understand it, we'd want the forwarded headers on for all apps with HTTP endpoints in ACA, not just those exposed to the Internet. Are you saying you'd want all apps with endpoints to opt-in to declaring ingress in the app model in order to get the env var set? Seems like boilerplate.

**Comment by davidfowl** [comment]
> Be careful not to conflate ingress with external/internal access.

They are independent flags. I just want to move them both into the apphost. I worry about baking it into azd where there's less user control to determine what happens.

> Are you saying you'd want all apps with endpoints to opt-in to declaring ingress in the app model in order to get the env var set? Seems like boilerplate.

We can make it a one liner to have it apply to all projects if that is indeed the default.

**Comment by DamianEdwards** [comment]
preview 5 then?

**Comment by davidfowl** [comment]
Yes. We can make this a lifecycle hook that only applies during publish.

**Comment by DamianEdwards** [comment]
Moving into preview.5

We should update `Aspire.Hosting` to set the `ASPNETCORE_FORWARDEDHEADERS_ENABLED` environment variable to `true` when publishing project resources by default and add a way to opt-out of it, e.g. `builder.AddProject<Projects.Frontend>().DisableFordwardedHeaders()`
