### ISSUE TITLE
Add `AddProject<T>()` overload?

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspire#2903]
Just doing _Baby's First Aspire App_ with only a reference to an existing app to use the dashboard for the local dev loop (there's nothing to orchestrate for this particular app), and I wondered if adding a convenience overload for the _"add my project and use its name as the name"_ would be worth adding?

With what I'm thinking, this would be the diff for the code I just wrote for my app host:

```diff
- builder.AddProject<Projects.RuntimeSupportScout>("RuntimeSupportScout");
+ builder.AddProject<Projects.RuntimeSupportScout>();
```

I get that using a short name is better when you want to keep re-using it as the key for references etc, but in the case of a simple app for just using the dashboard, it would be terser when you want the dashboard to use the app's proper name, rather than a short name (e.g. `rss`/`app`).

**Comment by davidfowl** [comment]
We moved away from this because the naming rules are difficult to predict from looking at the method. They auto generated names are also not friendly URIs for service discovery.
