### ISSUE TITLE
Add support for MSTest to Aspire test project templates

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2908]
Follow up to #2905

Update the option on the starter template and add another standalone template for MSTest-based tests for an Aspire app.

**Comment by pavelhorak** [comment]
It would be great if you could use [MSTest runner](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro) (MSTest 3.2+) a with a new [MSTest SDK](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-sdk) in the template.

**Comment by Evangelink** [comment]
@DamianEdwards How do you want to select the test framework to use?

**Comment by DamianEdwards** [comment]
@Evangelink not quite following what you mean? For the Starter App template I'll change the Boolean option to a multi-choice, and then depending on what's chosen include the appropriate test project.

**Comment by Evangelink** [comment]
> I'll change the Boolean option to a multi-choice, and then depending on what's chosen include the appropriate test project.

That was my question :) 

Do you have any example of a multi-choice option template I could use as reference? Otherwise no worries, I am sure I can find it somewhere.

**Comment by DamianEdwards** [comment]
See docs at https://github.com/dotnet/templating/wiki/Reference-for-template.json#multi-choice-symbols-specifics

**Comment by Evangelink** [comment]
@DamianEdwards I have a few problems with the PR, if you (or anyone else) could help it'd be awesome.
