### ISSUE TITLE
Option to write dashboard console logs in the host console

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2911]
When users run an Aspire app, they run the host. Output from the host is written to the console. If there is an error in the host, such as from the resource service, these errors are written to the console.

The dashboard is started with the host, but it runs out of process. The dashboard is launched by the DCP. Its logs aren't written to a console the user can see. If an error occurs in the dashboard, then there is no way to access the details. Errors reported to us won't have any logging information.

There should be a host config option to output dashboard logs to the console.

**Comment by kvenkatrajan** [comment]
@JamesNK  - assuming this needs to move to preview 6 (prior to GA)

**Comment by davidfowl** [comment]
I'll take this one @JamesNK
