### ISSUE TITLE
Use ExperimentalAttribute

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#2918]
https://github.com/dotnet/aspire/pull/2875 brought in "preview" APIs (specifically Azure CDK APIs) that we want to warn consumers may change in a later release. These APIs have been marked with `[RequiresPreviewFeatures]`.

We should instead be using `[ExperimentalAttribute]` on these APIs. This attribute fits this scenario more. You can read about the distinction between the two attributes at https://github.com/dotnet/runtime/issues/77869.

cc @mitchdenny @joperezr @terrajobst

**Comment by joperezr** [comment]
The main drawback of `RequiresPreviewFeatures` is that it is a global on/off switch, so you either allow using All of the APIs marked with it, or None, but there is no in-between. `ExperimentalAttribute` was added later, given we realized that `RequiresPreviewFeatures` should really only be used by .NET platform itself, while .NET Libraries should instead use Experimental and assign different diagnostic IDs for groups of APIs so consumers can choose which experimental APIs to depend on.
