### ISSUE TITLE
Unable to run aspire using Podman

### ISSUE THREAD

**Issue by iantasker** [dotnet/aspire#2922]
I am trying to run aspire starter application using podman to avoid the license requirement of docker desktop. 

I have updated Visual Studio 2022 to 17.10 Preview 2.0 and updated the dotnet workloads but when trying to run the the application I get the following modal,

![vs docker warning](https://github.com/dotnet/aspire/assets/17986190/454a79dd-17f2-4816-83e8-59b84a2b5b9f)

I have also cloned the latest version of the eshop demo and get the following warning

![image](https://github.com/dotnet/aspire/assets/17986190/8b8e035f-18c3-4b66-9c77-77db020b6961)

From the documentation podman is a drop in replacement for docker desktop. Docker desktop is not installed on my machine so unsure  why are these warning being displayed when podman is installed? 

Have I missed any additional documentation on how podman should be setup?

**Comment by afscrome** [comment]
Same issue if you use [Rancher Desktop](https://rancherdesktop.io/) to set up docker installed rather than Docker Desktop.

Aspire still works fine, and spins up containers successfully with Rancher, but it's a pain having to click through the "Unable to start Docker Desktop" message every time.

**Comment by timheuer** [comment]
@iantasker can you set this setting? https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=visual-studio%2Cwindows#container-runtime

**Comment by iantasker** [comment]
This issue has been resolved in preview 5.
