### ISSUE TITLE
Remove InternalsVisibleTo from Aspire.Hosting to Aspire.Hosting.Testing

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#2930]
Today we have InternalsVisibleTo from Aspire.Hosting to Aspire.Hosting.Testing

https://github.com/dotnet/aspire/blob/9073e0788b830aafa1e0dede786e861143e1a8b9/src/Aspire.Hosting/Aspire.Hosting.csproj#L59

We need to remove this because we aren't guaranteed that these 2 nuget packages version in lock step, or that users will always have the exact same matching versions (they could upgrade their Aspire.Hosting without updating the Aspire.Hosting.Testing). When this happens, and we refactor some internal APIs, users will get weird errors above types/methods not existing.

cc @davidfowl @ReubenBond @mitchdenny

**Comment by mitchdenny** [comment]
I would have thought that they would go together.

**Comment by davidfowl** [comment]
Still we should not couple their internals like this. We should expose the appropriate APIs.

**Comment by eerhardt** [comment]
> I would have thought that they would go together.

Since they ship as separate NuGet packages, you can't guarantee this. Imagine you pull in some reference like `Aspire.Hosting.Azure` or `Aspire.Hosting.MongoDB` and it lifts your version of `Aspire.Hosting` to a new version. Now your tests start breaking because you have a different version of `Aspire.Hosting` and `Aspire.Hosting.Testing`.
