### ISSUE TITLE
Consider allowing warning/error/critical messages to be shown in the console of a launched AppHost project

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2936]
Right now, all logs from ASP.NET Core/Kestrel in the AppHost process are hidden in the console. This makes it difficult to diagnose issues when including things like HTTPS dev cert status. We should consider allowing logs of warning or above through.

**Comment by mitchdenny** [comment]
This is what is in the template:

![Image](https://github.com/dotnet/aspire/assets/513398/d50e751f-6e1f-44c0-af75-55075201fe39)

This was the message we were filtering with the option in code:

![Image](https://github.com/dotnet/aspire/assets/513398/f509f304-9be6-4bc1-9746-ba83f92a7e2b)

We could update the templates to filter this instead to make it easier for folks to enable the diagnostics?

**Comment by DamianEdwards** [comment]
I'm not sure there's a way to filter that specific message via config though and we definitely wouldn't want to suppress all warnings from Kestrel in the template, as that includes HTTPS warnings. Was there a specific approach you had in mind?

**Comment by davidfowl** [comment]
I made a late change that lets users override our defaults via configuration. I dunno if that helps here.

**Comment by davidfowl** [comment]
We did this
