### ISSUE TITLE
BIG Changes to Aspire.Hosting

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2938]
A *huge* change is coming we're working on changes to refactor the packages for **Aspire.Hosting** into 2 main packages:

**Aspire.Hosting** - The core APIs (libraries will compile against this)
**Aspire.Hosting.AppHost** - What aspire apphost projects will reference.

We also want to remove all resources from these core packages and put them into the project templates (what list ends up in the project templates is still TBD). This resource split will happen next week Monday:
 
- Aspire.Hosting.Redis
- Aspire.Hosting.Postgres
- Aspire.Hosting.SqlServer
- Aspire.Hosting.Kafka
- Aspire.Hosting.MongoDB
- Aspire.Hosting.MySql
- Aspire.Hosting.Oracle
- Aspire.Hosting.RabbitMQ
- Aspire.Hosting.Seq
- Aspire.Hosting.Node

We're preparing for the future when both the Aspire component and the Aspire hosting package live outside of the aspire repository.

**Comment by mitchdenny** [comment]
Our little baby is all grown up and moving out of home.

**Comment by mitchdenny** [comment]
regarding the Aspire.Hosting.AppHost assembly name ... that won't be the namespace right? I can imagine that being painful.

**Comment by eerhardt** [comment]
> regarding the Aspire.Hosting.AppHost assembly name ... that won't be the namespace right? 

I would say no. We keep the namespaces the way they are today.

**Comment by DynConcepts** [comment]
Curious: does this have any impact on the eShop flagship Demo for .Net 8.0? 
[I am having lots of problems there, and beginning to think I am narrowing them down to aspire - at least in part.

**Comment by eerhardt** [comment]
> Curious: does this have any impact on the eShop flagship Demo for .Net 8.0?

It does. You can see the impact at https://github.com/dotnet/eShop/pull/257 which is updating eShop to use preview5.

**Comment by davidcorbin-atmosera** [comment]
> > Curious: does this have any impact on the eShop flagship Demo for .Net 8.0?
> 
> It does. You can see the impact at [dotnet/eShop#257](https://github.com/dotnet/eShop/pull/257) which is updating eShop to use preview5.

OK, that helped quite a bit (thanks!!!).  I can now do both "azd init" and "azd up"... but get an error after the WebApp starts to load.... Still digging, but here is the stack trace..

![image](https://github.com/dotnet/aspire/assets/83300052/99e6b66e-0c07-4e13-abed-d29c2fe2b153)
