### ISSUE TITLE
Review AppHost command line switches

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#2945]
DCP options should be prefixed with dcp, stale options should be deleted

https://github.com/dotnet/aspire/blob/2acf1903643d9b9e02a80a74862334dc322d381b/src/Aspire.Hosting/DistributedApplicationBuilder.cs#L122-L129

**Comment by mitchdenny** [comment]
@danegsta any concerns if we rename `--container-runtime` to `--dcp-container-runtime` (same for the timeout switch).
