### ISSUE TITLE
Find common places we will need to integrate with HttpClient service discovery

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#296]
We should have a list of common components in and out of framework that we want to integrate with service discovery. As an example, the JwtBearer middleware has a ConfigurationManager API that retrieves OIDC metadata documents. We'd like that to work with service discovery so we need a nice way to get the handler in there.

We should make a list of common in box and popular 3rd party components that will need this treatment.

**Comment by codymullins** [comment]
HttpClient in Blazor WASM projects may be another

**Comment by FritzTheCat9** [comment]
Aspire dont work with Blazor Webassembly for me i got the error: "There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'"

**Comment by DamianEdwards** [comment]
@FritzTheCat9 
> Aspire dont work with Blazor Webassembly for me i got the error: "There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'"

This is fixed in preview.2 (#424)

**Comment by aherrick** [comment]
where can we see when preview 2 is to be released? will preview 2 be shipped with VS or will you have to opt into the daily bits? https://github.com/dotnet/aspire/blob/main/docs/using-latest-daily.md

**Comment by DamianEdwards** [comment]
Preview 2 will be out in early December and will require you to update from the command line, e.g. `dotnet workload update`. This will update the version carried with the VS preview channel for now. Closer to our GA next year, we'll align the version carried in the VS preview with the bits we're shipping to nuget.org.

**Comment by aherrick** [comment]
cool hoping for clear instructions on how to update once its ready. thanks!

**Comment by davidfowl** [comment]
This issue needs to be broken down into specific work items. Closing.
