### ISSUE TITLE
Startup detection may be a little flakey? 

### ISSUE THREAD

**Issue by oising** [dotnet/aspire#2985]
![image](https://github.com/dotnet/aspire/assets/1844001/ad153cb1-5062-4c59-97d9-74de490c7165)

As depicted, "api" is still starting but it has already started successfully. I had "consumer" briefly in a debugger pause (1 minute?) but they are not dependent on each other. Thread freeze somewhere?

**Comment by davidfowl** [comment]
I have a theory 😄

**Comment by davidfowl** [comment]
How often do you see this @oising ?

**Comment by oising** [comment]
Right now I can't get Aspire to run again. Hitting this repeatedly:

Application orchestrator dependency check had an unexpected error System.TimeoutException: The operation has timed out.
   at Aspire.Hosting.Dcp.DcpDependencyCheck.EnsureDcpDependenciesAsync(CancellationToken cancellationToken) in C:\p\github\aspire\src\Aspire.Hosting\Dcp\DcpDependencyCheck.cs:line 67

I'm going to log this as a separate issue.

**Comment by oising** [comment]
Figured out the Dcp issue -- I've left https://github.com/dotnet/aspire/issues/3003 open as it should probably result in a work item for Aspire release notes.

**Comment by oising** [comment]
> How often do you see this @oising ?

Not very often at all. I haven't seen it since last reporting it.

**Comment by mitchdenny** [comment]
@oising just checking in again to see if you've seen this recently. We've made some changes in the P5 bits to make a bunch of things with DCP spin up more resilient, and a few more coming in P6. 

If you aren't' seeing this anymore I'm inclined to close this issue.

**Comment by oising** [comment]
> @oising just checking in again to see if you've seen this recently. We've made some changes in the P5 bits to make a bunch of things with DCP spin up more resilient, and a few more coming in P6. 
> 
> If you aren't' seeing this anymore I'm inclined to close this issue.

I have not seen this for quite some time. You may close it.
