### ISSUE TITLE
Make dashboard configuration align with standard .NET configuration

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2996]
Most configuration in .NET uses Microsoft.Extensions.Configuration, which supports great features such as sections.

Aspire dashboard has a rapidly growing number of configuration options:
* Endpoints
* Auth
* OTLP limits
* Logging (built-in config)
* Kestrel (built-in config)

Right the config options we've added to Aspire don't follow the .NET naming standard for config or sections. For example, setting OTLP auth mode has a key called `DOTNET_DASHBOARD_OTLP_AUTH_MODE` instead of something like `AspireDashboard__Otlp__AuthMode` (double underscores indicates a section delimiter in env vars).

There are pros and cons to each. `DOTNET_DASHBOARD_OTLP_AUTH_MODE` is optimized for command line and env var usage, but it doesn't match built-in config values, and isn't nested into sections in JSON files.

We should consider consistently using the .NET standard for naming and organizing dashboard configuration.

**Comment by JamesNK** [comment]
@davidfowl @drewnoakes What do you think?

**Comment by drewnoakes** [comment]
Seems reasonable. Not a huge fan of the double-underscore syntax (mostly because it could be mistaken for a single underscore and lead to confusion), but using configuration in the way it was intended wins out for me.

**Comment by davidfowl** [comment]
I think we can add top level env variable alternative to commonly used env variables to avoid double underscore but we should default to the normal configuration model.

**Comment by drewnoakes** [comment]
With two ways to configure the same thing, which would win if both were provided?

**Comment by davidfowl** [comment]
We pick one 😄
