### ISSUE TITLE
DAPR Code Sample Not Working

### ISSUE THREAD

**Issue by jkears** [dotnet/aspire#3000]
A previously running Aspire AppHost with DAPR sidecars no longer runs the sidecars, but services standup.  

**Aspire version**
Version 8.0.0-preview.4.24156.9

**DAPR versions** 
CLI version: 1.8.1
Runtime version: 1.13.0

To reproduce run the [Aspire DAPR sample ](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithDapr), which at least on my machine fails with same results in sample as my project.

This is the log from the DAPR sidecar from the DAPR sample project...

![image](https://github.com/dotnet/aspire/assets/1290937/8b500510-0589-49ef-85c6-749fdf9e6fc4)

Notes: 

1. All DARP sidecars fail to run
2. Paired services run.
3. My Services run via Tye, suggest DAPR env is fine.

**Comment by davidfowl** [comment]
What version of dapr do you have installed?

**Comment by jkears** [comment]
@davidfowl 

**DAPR versions**
CLI version: 1.8.1
Runtime version: 1.13.0

**Comment by lou8566** [comment]
@davidfowl  I too have the issue. In my case I started from scratch, installed VS 2022 Preview and related bits.
Initially I has running an older version of DAPR and when I run the Aspire DAPR sample it fails identically as @jkears  explained. 
I then upgraded DAPR to 1.13.0 and see the same error.   Please try sample and let us know if you witness similar behavior.

**Comment by davidfowl** [comment]
cc @philliphoff

**Comment by davidfowl** [comment]
I just realized this is the main repo, which is using the daily aspire bits, not the released ones.

**Comment by davidfowl** [comment]
Sorry I noticed the link again 😄

**Comment by philliphoff** [comment]
@jkears Is there a reason you have version 1.8.1 of the Dapr CLI (which is nearly 2 years old and may not support the `--app-channel-address` argument).  Could you try with 1.13.0 of the CLI.

There are some significant differences between how Tye ran Dapr sidecars vs. Aspire (the latter which uses `--app-channel-address` as a way to get calls from the sidecar to the application to go through the application's Aspire proxy).

**Comment by danmoseley** [comment]
I'm going to close feel free to open if you are able to answer q above.
