### ISSUE TITLE
Change visibility for AzureStorageResource.GetTableConnectionString() methods

### ISSUE THREAD

**Issue by razvangoga** [dotnet/aspire#3001]
I'm trying to onboard Aspire to an existing project that uses Azure Blobs in prod and the Azurite emulator for local dev.

At the moment due to various reasons, I can't introduce the lower level components (via _Aspire.Azure.Storage.Blobs_) so i have to rely on the connection string.

Trying to do that i noticed that the **_AzureStorageResource.GetTableConnectionString()_** method is marked as internal
https://github.com/dotnet/aspire/blob/36e40f89e15f1b049bd81c4bffbe7ec7b5a29ece/src/Aspire.Hosting.Azure/AzureStorageResource.cs#L43

So instead of 

``` csharp
builder.AddProject<Projects.Web>("web")
    .WithEnvironment("ApplicationSettings__AzureStorageConfigurations__ConnectionString", () => blobStorage.Resource.GetTableConnectionString());
```

i have to do

``` csharp
builder.AddProject<Projects.Web>("web")
    .WithEnvironment("ApplicationSettings__AzureStorageConfigurations__ConnectionString", "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;");
```

-----

Would it possible to change the visibility for these 3 methods?
Is there any reason they are internal (other then to get people to use the components) ?

**Comment by davidfowl** [comment]
I see you filed https://github.com/dotnet/aspire/issues/3002 so I'll close this one and respond there. You can call GetConnectionString on the resource.

**Comment by davidfowl** [comment]
Storage has no connection string, you have to call AddBlobs/AddTables/AddQueues and those resources have connection strings.

**Comment by davidfowl** [comment]
This looks related to https://github.com/dotnet/aspire/pull/1728, which we're not supporting in aspire.

**Comment by razvangoga** [comment]
> This looks related to #1728, which we're not supporting in aspire.

it's not - this has nothing to do with the publication side - **i'm trying to get the local dev part working**

----

> Storage has no connection string, you have to call AddBlobs/AddTables/AddQueues and those resources have connection strings.

once i understood that herr you mean the aspire resource types and not the azure cloud resources you meant with the other link it clicked into place

``` csharp
IResourceBuilder<AzureBlobStorageResource> blobStorage = builder.AddAzureStorage("blob-storage")
    .RunAsEmulator(c =>
    {
        c.UseTablePort(10000);
        c.UsePersistence(blobPath);
    }).AddBlobs("dev");

builder.AddProject<Projects.Web>("web")
    .WithEnvironment("ApplicationSettings__AzureStorageConfigurations__ConnectionString", () => blobStorage.Resource.GetConnectionString())
```

i'm in the same situation as in #3002 now 👍

**Comment by razvangoga** [comment]
> This issue is about exposing a single connectionstring for storage in local dev, exactly what you were trying to do. If you look at your original post, you have a connection string that has all 3 endpoints embedded.

it's from [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage#https-connection-strings) - my docker compose setup i'm trying to migrate to Aspire was written some time ago (2020 maybe?)... something might have changed with azurite in the meanwhile... in any case the full conn-string is still the first choice give in the current docs

**Comment by davidfowl** [comment]
> it's from [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage#https-connection-strings) - my docker compose setup i'm trying to migrate to Aspire was written some time ago (2020 maybe?)... something might have changed with azurite in the meanwhile... in any case the full conn-string is still the first choice give in the current docs

What does the client code look like using that connection string? Are you using the old azure sdk?

**Comment by razvangoga** [comment]
i'm using the latest version of https://www.nuget.org/packages/Azure.Storage.Blobs like this (which is basically the first sample fro mm the nuget readme) or here https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/samples/Sample02_Auth.cs#L48:

``` csharp
public StorageClient(StorageConfigurations storageConfigurations)
{
    BlobServiceClient blobServiceClient = new(storageConfigurations.ConnectionString);
    this._container = blobServiceClient.GetBlobContainerClient(storageConfigurations.Container);
}
```

since the code works and there is no deprecation warning and the nuget is alive and getting updates I haven't really looked if there is another way for a long time (the app is a former dotnet 4.6 that was migrated successively to 3.1, 5, 6, 7 and now 8) and where i've always kept the nuget dependencies updated to the latest.
