### ISSUE TITLE
IResourceBuilder.WithReference - Allow passing of a env variable name that will not be nested under ConnectionStrings__

### ISSUE THREAD

**Issue by razvangoga** [dotnet/aspire#3002]
I'm trying to onboard Aspire in some existing projects that do not pull the connection strings from keys nested under the **ConnectionStrings__** root.

I wanted to go the idiomatic way and configure the project dependencies but:

`builder.AddProject<Projects.Web>("web").WithReference(redis, "Session-RedisCache")` 

will put the connection string under **_ConnectionStrings__Session-RedisCache_** and the configs binding will fail, so i have to configure things via env vars:

`builder.AddProject<Projects.Web>("web").WithEnvironment("Session-RedisCache", () => redis.Resource.GetConnectionString())`

which works fine but somehow feels like a hack

LE : i'm on preview 4

-------

Would it be possible to add an overload or some config to allow the user to fully control under which env var would the referenced service's connection sting end up? 

It would be helpful for moving existing codebases to aspire, codebases that for some reason or another have other config structures.

**Comment by davidfowl** [comment]
We could add a `WithEnvironment` overload.

Thoughts @mitchdenny @eerhardt?

**Comment by razvangoga** [comment]
but i'm already on `WithEnvironment ` and it works as expected

**Comment by davidfowl** [comment]
It could look like this:

```C#
builder.AddProject<Projects.Web>("web").WithEnvironment("Session-RedisCache", redis)
```

**Comment by razvangoga** [comment]
definitely better (because of the lack of the lambda), but still not idiomatic

i mean in the codebase  where i am introducing aspire now, due to the configs not using the **ConnectionStrings__** root, i'm in effect not using `WithReference`

**Comment by davidfowl** [comment]
Yes, I understand.

**Comment by eerhardt** [comment]
I feel like this is where the "opinionated" comes in. It is Aspire's opinion that connection strings are best passed in the `ConnectionStrings:<name>` config section. You're going to have the easiest time following that approach.

Other ways are possible (as illustrated above), but they aren't as easy. You need to do some work yourself to have other schemes.

If we were to change `WithReference` to not put things under `ConnectionStrings:<name>`, the fallout from that would be that we would need to change Components to not read the connection info from under `ConnectionStrings:<name>`.

**Comment by davidfowl** [comment]
I don't think we would change WithReference, I think we'd add an overload of WithEnvironment.

**Comment by davidfowl** [comment]
@razvangoga Feel free to send a PR for this.

**Comment by razvangoga** [comment]
For which version? 😀

**Comment by davidfowl** [comment]
A WithEnvironment overload

**Comment by mitchdenny** [comment]
I can see @eerhardt's argument here about encouraging people to use `ConnectionStrings:connname` particularly if they are using .NET. Although I think a `WithEnvironment(string, IResourceWithConnectionString)` overload is a good idea particularly for brownfields scenarios.

I suggested making it an overload of `WithReference` but we already have an optional string parameter there to allow for overriding the connection name.

**Comment by razvangoga** [comment]
@davidfowl sure i'll take a crack at it time permitting

@mitchdenny if that's what passes as _encouraging_ i wouldn't want to see what _forcing_ looks like /s
