### ISSUE TITLE
Use new UseOtlpExporter  method from the OTEL library

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3017]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/5400

**Comment by DamianEdwards** [comment]
Currently available in [1.8.0-beta.1](https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.8.0-beta.1)

**Comment by CodeBlanch** [comment]
Really the whole point of putting out that beta was for Aspire to take it for a spin and provide feedback 🤣 Please do!

Here's the things in 1.8.0-beta.1 which should be of interest to Aspire:

* Addition of UseOtlpExporter
* Removal of `OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES`
* Addition of `OTEL_DOTNET_EXPERIMENTAL_OTLP_ENABLE_INMEMORY_RETRY`

This one didn't make the first beta but will come in the next drop: https://github.com/open-telemetry/opentelemetry-dotnet/pull/5448

**Comment by DamianEdwards** [comment]
@CodeBlanch great! I'll try it out to get a sense of how it would impact our experience, thanks.

**Comment by DamianEdwards** [comment]
@CodeBlanch I can't seem to find the new method in the 1.8.0-beta.1 package. Did it actually make it in or am I doing something wrong?

**Comment by DamianEdwards** [comment]
OK so yeah, this allows us to simplify the ServiceDefaults code to enable OTLP quite a bit:

```diff
private static IHostApplicationBuilder AddOpenTelemetryExporters(this IHostApplicationBuilder builder)
{
+    builder.Services.AddOpenTelemetry()
+       // Enable OTLP exporter for all telemetry based on defaults and environment variables
+       .UseOtlpExporter();
+       // Uncomment the following lines to enable the Prometheus exporter (requires the OpenTelemetry.Exporter.Prometheus.AspNetCore package)
+       //.WithMetrics(metrics => metrics.AddPrometheusExporter());
    
-    var useOtlpExporter = !string.IsNullOrWhiteSpace(builder.Configuration["OTEL_EXPORTER_OTLP_ENDPOINT"]);
    
-    if (useOtlpExporter)
-    {
-        builder.Services.Configure<OpenTelemetryLoggerOptions>(logging => logging.AddOtlpExporter());
-        builder.Services.ConfigureOpenTelemetryMeterProvider(metrics => metrics.AddOtlpExporter());
-        builder.Services.ConfigureOpenTelemetryTracerProvider(tracing => tracing.AddOtlpExporter());
-    }

-    // Uncomment the following lines to enable the Prometheus exporter (requires the OpenTelemetry.Exporter.Prometheus.AspNetCore package)
-    // builder.Services.AddOpenTelemetry()
-    //    .WithMetrics(metrics => metrics.AddPrometheusExporter());
    
    // Uncomment the following lines to enable the Azure Monitor exporter (requires the Azure.Monitor.OpenTelemetry.AspNetCore package)
    //if (!string.IsNullOrEmpty(builder.Configuration["APPLICATIONINSIGHTS_CONNECTION_STRING"]))
    //{
    //    builder.Services.AddOpenTelemetry()
    //       .UseAzureMonitor();
    //}

     return builder;
}
```

**Comment by DamianEdwards** [comment]
I'll move this to preview.6 as I'm not expecting we're going to get a stable version of the package with this change in time for preview.5

**Comment by DamianEdwards** [comment]
rc.1 is out now https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.8.0-rc.1

**Comment by CodeBlanch** [comment]
@DamianEdwards Does Aspire use something like `appSettings.Development.json`? Asking because FYI using rc.1 you could remove this...

https://github.com/dotnet/aspire/blob/93a1efbc4d8798903828eb5da7ffb50b873dc513/src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/Extensions.cs#L58-L62

...and do it via config:

appSettings.Development.json
```json
{
   "OTEL_TRACES_SAMPLER": "always_on"
}
```

If you wanted to 😄

**Comment by davidfowl** [comment]
We can set environment variables.

cc @JamesNK

**Comment by samsp-msft** [comment]
https://github.com/dotnet/aspire/pull/3316

**Comment by CodeBlanch** [comment]
Stable 1.8.0 OTel packages should be on Nuget now.

**Comment by davidfowl** [comment]
Done in https://github.com/dotnet/aspire/pull/3359

**Comment by martincostello** [comment]
FYI I've found a bunch of trim warnings related to this: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5518#issuecomment-2042579743
