### ISSUE TITLE
[WebToolsE2E][Aspire] After building a .NET Aspire Starter application that check "Use Redis for caching (requires Docker)", an error occurs: 'IDistributedApplicationBuilder' does not contain a definition for 'AddRedis' ...

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3042]
**REGRESSION INFO**: Not repro on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [34719.218.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24169.12]
4. Apply NuGet Feeds
5. Install Docker

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > named it 'AspireApp1' > .NET 8.0 > Check "Use Redis for caching (requires Docker)" > Create
2. Wait for all packages to be restored > Build

**NOTE**: Add the Aspire.Hosting.Azure package to the AspireApp1.AppHost project and build again. This error will disappear.

**ACTUAL**
An error will appear.
Error (active)	CS1061	'IDistributedApplicationBuilder' does not contain a definition for 'AddRedis' and no accessible extension method 'AddRedis' accepting a first argument of type 'IDistributedApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)
![image](https://github.com/dotnet/aspire/assets/109339894/2fa90424-e641-40d2-b8d2-0b4841c20ae2)

**EXPECTED**
There are no errors after creating and building the project.

**Comment by davidfowl** [comment]
cc @eerhardt Guessing something is busted with the starter template?
