### ISSUE TITLE
[WebToolsE2E][Aspire] Click the http link under Endpoints of webfrontend, but the https link is opened.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3068]
**REGRESSION INFO**: Running with HTTPS is new feature on Aspire 8.0 preview 5

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [34719.218.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24170.8]
4. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > .NET Aspire Starter Application > named it 'AspireApp1' > .NET 8.0 > Create
2. F5 with https, click the http link under Endpoints of webfrontend

Note: This issue also repro on ASP.NET Core Web App/Blazor Web App with 'Enlist in.NET Aspire orchestration' checked.

**ACTUAL**
Click http://localhost:xxxx, but it opens https://localhost:xxxx.
![image](https://github.com/dotnet/aspire/assets/109339894/e22170eb-6491-4f6c-bf53-f38a5a4acd96)
![http](https://github.com/dotnet/aspire/assets/109339894/3300b319-20af-4768-8c65-b63cb1433d6d)

**EXPECTED**
Click the http link under Endpoints of webfrontend, open the corresponding http link.

**Comment by balachir** [comment]
I believe that this is By Design. I'll let triage confirm.

**Comment by davidfowl** [comment]
It is. Thats the https redirection middleware doing its job ! 😅
