### ISSUE TITLE
feat: Add IServiceProvider to AddSqlServer options action 

### ISSUE THREAD

**Issue by Hona** [dotnet/aspire#3069]
I'm trying to add Aspire to my solution template.

Moving from the old code:

```cs
services.AddDbContext<AppDbContext>((sp, options) =>
{
    options.UseInMemoryDatabase("InMemoryDbForTesting");

    options.AddInterceptors(sp.GetServices<ISaveChangesInterceptor>());
});
```

to this

```cs
services.AddSqlServer<AppDbContext>(configureDbContextOptions: options =>
{
    options.AddInterceptors(sp.GetServices<ISaveChangesInterceptor>());
});
```

Fails because I cannot get the `sp` variable. It could be provided as a parameter of the optionsAction.

Unless I'm missing something :)

**Comment by DamianEdwards** [comment]
`services.AddSqlServer<AppDbContext>` is not an Aspire method, it's the provider-first method in the EF Core provider package for SQL Server. The Aspire component method is on the `IHostApplicationBuilder` interface so would be `builder.AddSqlServer<AppDbContext>`. In case that was just a typo, the alternative way is to keep the first block of code and then call `builder.EnrichSqlServerDbContext<DbContext>`.

**Comment by giri-hp** [comment]
I am still not clear. How to use options.AddInterceptors(sp.GetServices<ISaveChangesInterceptor>()) even with builder.EnrichSqlServerDbContext<DbContext>

**Comment by davidfowl** [comment]
```C#
services.AddDbContext<AppDbContext>((sp, options) =>
{
    options.UseInMemoryDatabase("InMemoryDbForTesting");

    options.AddInterceptors(sp.GetServices<ISaveChangesInterceptor>());
});

builder.EnrichSqlServerDbContext<DbContext>();
```

**Comment by Hona** [comment]
Thanks team! :)
