### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.Azure.Security.KeyVault component, using inline delegates to configure the Azure Key Vault connection in the web project, the secret value cannot be shown.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#3073]
**REGRESSION INFO**: Also repro on Aspire 8.0 preview 4

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 3.0 [34720.177.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire.ProjectTemplates.8.0.0-preview.5.24170.9
4. Apply NuGet Feeds

**REPRO STEPS**

1. New > Project >ASP.NET Core Empty project > Enter a Project name of AspireKeyVault01 > .NET 8.0 > check 'Enlist in Aspire Orcheatration' > Create
2. Right-click the AspireKeyVault01 > Add > .NET Aspire Component > check 'Include prerelease' > change 'Package source' to 'All' > install Aspire.Azure.Security.KeyVault with matched version
3. Open Program.cs of AspireKeyVault01 project, add following codes
```
builder.AddAzureKeyVaultClient("secretConnectionName", configureClientBuilder: clientBuilder => clientBuilder.ConfigureOptions(options => options.Diagnostics.ApplicationId = "myapp"));
```

4. Then add following codes in the Program.cs of AspireKeyVault01 project:
```
	string? _mySecret = builder.Configuration["[secretName]"];
	var result = string.IsNullOrEmpty(_mySecret) ? "Null" : _mySecret;
	//app.MapGet("/", () => "Hello World!");
	app.MapGet("/", async context =>
	{
	    await context.Response.WriteAsync($"Secret is {result}");
	});

```
5. Open appsettings.json of AspireKeyVault01 project:
```
  "ConnectionStrings": {
    "secretConnectionName": "https://{account_name}.vault.azure.net/"
  }
```

6. Build and F5
7. On the dashboard, open endpoint link.

**ACTUAL**
Secret value cannot be shown
![image](https://github.com/dotnet/aspire/assets/82028229/022b4363-9275-49b6-822d-cbbb77db3d60)

**Note**:

1. This issue also repro on Aspire 8.0 preview 4.
2. Use 'configuration providers' also repro this issue.

**EXPECTED**
Shows the secret value successfully.

**Comment by eerhardt** [comment]
`AddAzureKeyVaultClient` will not add the secrets to the `builder.Configuration`. You want to use `builder.Configuration.AddAzureKeyVaultSecrets("secretConnectionName");`

See the README under "Usage examples" and "Add secrets to configuration".

https://github.com/dotnet/aspire/blob/1d56885690145ecefd829dd2cff7c74818d91f2e/src/Components/Aspire.Azure.Security.KeyVault/README.md?plain=1#L20-L28
