### ISSUE TITLE
[WebToolsE2E][Aspire] Open an existing 8.0 P4 aspire project and update the package to P5, the "Aspire.Hosting" package is not recognized and "Aspire.Hosting.AppHost" needs to be installed manually.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#3074]
**REGRESSION INFO**: Aspire.Hosing.AppHost" is a new update for 8.0 P5

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [34720.177.main] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24170.9]
4. Apply NuGet dotnet8 Feed

**REPRO STEPS**

1. Open an existing 8.0 P4 version of Aspire project 
2. Right click the solution > Manage NuGet Packages for Solution > check 'Include prerelease' checkbox and set Package source to All
3. Update the packages "Aspire.Hosting" and "Microsoft.Extensions.ServiceDiscovery" version to 8.0.0-preview.5.24170.9
4. Build solution

**ACTUAL**
![image](https://github.com/dotnet/aspire/assets/71361488/ee7f68ad-314e-4f35-a9bc-af78da14f757)

**Workaround**:
Manually update the package "Aspire.Hosing" to "Aspire.Hosing.AppHost"
![image](https://github.com/dotnet/aspire/assets/71361488/f25b986d-2db9-486a-a61c-7e8b03bb08b6)

**EXPECTED**

**Comment by DamianEdwards** [comment]
This is an expected breaking change. All existing AppHost projects will need to have their reference to `Aspire.Hosting` changed to `Aspire.Hosting.AppHost` as part of upgrading to preview.5

See #2938 for details.
