### ISSUE TITLE
Test OTEL retries works

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#3086]
Test https://www.nuget.org/packages/OpenTelemetry.Exporter.OpenTelemetryProtocol/1.8.0-beta.1 retry logic works.

Can test by delaying startup of dashboard and then ensuring that telemetry from apps is eventually correctly recorded.

**Comment by DamianEdwards** [comment]
rc.1 is out now https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/core-1.8.0-rc.1

**Comment by vishweshbankwar** [comment]
@JamesNK - Just the heads up. A change is coming for this https://github.com/open-telemetry/opentelemetry-dotnet/pull/5495

It should be released tomorrow. I will update here, once the package is available with the change.

**Comment by vishweshbankwar** [comment]
It is available now: https://www.nuget.org/packages/OpenTelemetry.Exporter.OpenTelemetryProtocol/1.8.0

**Comment by JamesNK** [comment]
To test out retries I updated OTEL to 1.8.0, added the env var, and a 20 second delay to starting up the server.

I don't see startup logging from .NET projects in the server:

![image](https://github.com/dotnet/aspire/assets/303201/9180f8ef-34cc-4d5a-aecb-7d3282170297)

What I expected to see:

![image](https://github.com/dotnet/aspire/assets/303201/a3d99e8c-a9d1-41d5-9f5f-b8a90e1f212a)

Retries don't appear to be working. How many times does it retry? How long does it try to retry?

**Comment by JamesNK** [comment]
PR to update to 1.8.0 - https://github.com/dotnet/aspire/pull/3351

**Comment by vishweshbankwar** [comment]
@JamesNK - Could you try increasing the timeout period? https://github.com/open-telemetry/opentelemetry-dotnet/blob/9b246750ab76e94986fc433d5c7af046a137e477/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L113-L117?

How long does it try to retry? - The retries will continue until the total time does not exceed the configured timeout for each export.

How many times does it retry - There is no defined # of retires, it is only controlled by the timeout period (which is max time the exporter can spend on exporting the batch).

**Comment by JamesNK** [comment]
Thanks. I tested with a 10 second startup delay and it works with the retry env var and doesn't work without the retry env var. That means it's working as expected.

10 second timeout is fine as a default.
