### ISSUE TITLE
[WebToolsE2E][Aspire] When using .NET Aspire with Application Insights in VS and running, only one project option will be displayed in the Structured Logs/Tracing/Metrics dropdown box

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#3094]
**REGRESSION INFO**: Also repro on Aspire P5

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU 
2. Download Install-Preinstall.ps1 file from - https://aka.ms/vspreinstall.
3. Install VS Dev17.10 P3 from [[main-34720.177](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9277942&view=ms.vss-build-web.run-extensions-tab)] Preview channel
Web workload
Includes Aspire 8.0.0-preview.4.24156.9
Includes .NET SDK 8.0.300-preview.24122.6 and runtime 8.0.2
5. Install Docker desktop and open

**REPRO STEPS**
1. New Project > Aspire Starter Application > name it 'AspireApp1' > check 'Use redis' checkbox > Create
2. Configure the AspireApp4.ServiceDefaults project
Right-click the ServiceDefaults project > Manage NuGet Packages > Select "Azure.Monitor.OpenTelemetry.AspNetCore" > install
Open the Extensions.cs file, add a using statement:
`using Azure.Monitor.OpenTelemetry.AspNetCore;`
Uncomment the line in AddOpenTelemetryExporters to use the Azure Monitor exporter:
![image](https://github.com/dotnet/aspire/assets/72899617/c5bcad21-c05f-4e30-8352-a88be2a9ebb7)
3. Configure the AspireApp4.AppHost project
Right-click xx.AppHost project > Add >  Aspire component >  Aspire.Hosting.Azure.Provisioning > add a component
Right-click the AppHost project and select "Manage User Secrets" to open the secrets.json file, Replace with the following code ('aaBlazor' is is an existing Application Insights):
```
{
  "ConnectionStrings": {
"aaBlazor": "InstrumentationKey=c9bd551e-1ee3-41be-a162-6f0e6e393a48;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/"
  }
}
```
Open Program.cs file of the AppHost project, update the app host code to use the Application Insights resource, and reference it from each project:
```
builder.AddAzureProvisioning();
var insights = builder.AddConnectionString("aaBlazor", "APPLICATIONINSIGHTS_CONNECTION_STRING");
var apiService = builder.AddProject<Projects.AspireApp4_ApiService>("apiservice").WithReference(insights);
builder.AddProject<Projects.AspireApp4_Web>("webfrontend").WithReference(apiService).WithReference(insights);
```
![image](https://github.com/dotnet/aspire/assets/72899617/83c25466-2f0f-4b41-ad4c-144034faae73)
4. F5 to run

**Notes**: 
1. This issue can be reproduced using the latest release of VS 17.10 P2 (using Aspire P4),
2. This issue can be reproduced if I execute "dotnet run" using the CLI.
3. If you only add `.WithReference(insights)` to one of these two lines of code, this problem will not repro.
![image](https://github.com/dotnet/aspire/assets/72899617/9084468a-de79-4c58-ac71-3f4d5b6b8416)

**ACTUAL**
There are two projects displayed on the Resources interface, and Application Insights functions normally
![image](https://github.com/dotnet/aspire/assets/72899617/9c2f80e2-01fe-4be1-9db4-72b32eb092ca)

But only one project will be displayed in the Structured logs / Traces / Metrics drop-down box
![image](https://github.com/dotnet/aspire/assets/72899617/63b1e94d-3893-485f-a63c-098a8c9e9535)

**EXPECTED**
There will be two projects displayed in the Structured logs / Traces / Metrics drop-down box

**Comment by mitchdenny** [comment]
@v-bennettyue I cannot reproduce this on preview 5. Can you retest on that version and report back?

**Comment by v-bennettyue** [comment]
@mitchdenny Thanks, I also cannot reprodue this issue on latest Aspire P5, so close this issue.
