### ISSUE TITLE
Fix hanging DCP tests when running locally

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3122]
For a while now, when running locally, some of the DCP tests hang forever. These tests are skipped on the CI so they don't get caught. We should have a timeouts so it's likely a poorly written test.

**Comment by dbreshears** [comment]
@ReubenBond ,  is this something you are investigating for 8.1?

**Comment by dbreshears** [comment]
The underlying hang issue has been resolved.   @karolz-ms , can you open a new issue for designs involving multiple DCP processes and tests.

**Comment by karolz-ms** [comment]
Done https://github.com/microsoft/usvc/issues/158
