### ISSUE TITLE
More precise timestamps in structured log view of dashboard

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/aspire#3127]
In Aspire 8.0.0-preview.4.24156.9, the "Timestamp" column of the "Structured logs" page of the dashboard shows only one-second precision, e.g. "19.01.29".  I'd like to see timestamps with more precision, like "19.08.17,7547722".  That would let me see how much time passed between consecutive log entries, even if they occurred during the same second.  In OpenTelemetry Protocol, [LogRecord appears to support nanosecond precision](https://github.com/open-telemetry/opentelemetry-proto/blob/4ca4f0335c63cda7ab31ea7ed70d6553aee14dce/opentelemetry/proto/logs/v1/logs.proto#L137-L157).

I found a related issue <https://github.com/dotnet/aspire/issues/115> but that one seems to concern how the Dashboard configures the _console_ loggers of other processes, rather than how it displays the timestamps it has received over OTLP.

**Comment by leslierichardson95** [comment]
@JamesNK what's your take on this scenario?

**Comment by JamesNK** [comment]
I think showing up to 3 decimal places in the UI is good. That's what most people want, most of the time, while keeping a clean UI. However, I think the tooltip can be improved to show the full precision.

Current:

![image](https://github.com/dotnet/aspire/assets/303201/9b61a869-113c-4552-b867-26ef70eda0d4)

**Comment by JamesNK** [comment]
What culture are you using? Can you show a screenshot of what you see?

**Comment by JamesNK** [comment]
Thanks, that's a bug. Fix looks pretty simple: https://github.com/dotnet/aspire/pull/3215

**Comment by drewnoakes** [comment]
We should file an issue with the docs repo too, as this approach came from there.
