### ISSUE TITLE
Arrow key in the structured log filter edit box moves the focus to a different control

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/aspire#3136]
In the Aspire 8.0.0-preview.4.24156.9 dashboard, on the "Structured logs" page, click the "Filter…" box and type "hello".  Then press the Left arrow key.  This should move the insertion point within the "hello" text but instead moves the focus to the resource dropdown box.

Reproduced on Microsoft Edge 123.0.2420.53.

**Comment by tlmii** [comment]
I can repro this as well. Same thing happens with other controls (e.g. give focus to the resource select and then use the right arrow and it'll move over to the filter box). For a lot of those controls it makes sense as an accessibility thing. But not for the text box. 

I'm actually able to repro this on the Fluent UI Blazor demo site as well. Go to https://www.fluentui-blazor.net/Toolbar and put the focus in either of the search boxes in the first two examples. The arrow keys will move to another control within the toolbar.

@vnbaaij Any ideas at what layer this might be happening?

**Comment by vnbaaij** [comment]
Not sure if the  https://www.fluentui-blazor.net/Toolbar example is representative. The search box there is inside a radio group so it kind of makes sense the keys navigate between thw=e radio buttond

**Comment by tlmii** [comment]
> Not sure if the https://www.fluentui-blazor.net/Toolbar example is representative. The search box there is inside a radio group so it kind of makes sense the keys navigate between thw=e radio buttond

I get what you're saying with the normal behavior for radio buttons, but I don't think that's right. Arrow keys should never move you out of a textbox. That'd be completely unexpected behavior to the user.



> If I use the developer features of a Web browser to disable the "keydown" event handler on the "fluent-toolbar" element, then the focus doesn't move. Likewise if I press the Shift key with the arrow key. The JavaScript debugger of the browser shows that the event goes to `node_modules/@fluentui/web-components/dist/web-components.js`, which has code similar to this: https://github.com/microsoft/fast/blob/5b2b801208a86c1d342feff49961f5c490ad247e/packages/web-components/fast-foundation/src/toolbar/toolbar.ts#L186-L206

Hrm... so maybe a function of the toolbar implementation in the underlying web components.

**Comment by adamint** [comment]
I'm with @tlmii, the toolbar should never switch focus to another element on left/right arrow key inside an input. I think this needs a fluentui-blazor fix. @vnbaaij thoights?

**Comment by adamint** [comment]
This should no longer be an issue.

**Comment by adamint** [comment]
We moved the popover out of the toolbar, which had been causing the issue.

**Comment by adamint** [comment]
Please use the latest aspire preview.
