### ISSUE TITLE
Dashboard panel size keyboard shortcuts on Finnish keyboard layout

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/aspire#3142]
The Aspire 8.0.0-preview.4.24156.9 dashboard help shows:

> Increase panel size `+`
>
> Decrease panel size `-`

However, when I open the trace details panel and press <kbd>+</kbd> or <kbd>-</kbd> on a Finnish keyboard layout, there is no effect.  If I press <kbd>Shift</kbd>+<kbd>-</kbd> instead, i.e. `_`, then the details panel shrinks, but even this doesn't work reliably; it seems to depend on which control has the focus and which controls have had the focus earlier.  I have not found a key combination to increase the panel size.

Reproduced on Microsoft Edge 123.0.2420.53 on Windows 10 version 22H2, Finnish locale, Finnish keyboard layout.

**Comment by adamint** [comment]
Closed via #2902
