### ISSUE TITLE
`ParameterResource` shows on Dashboard and not terribly useful

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#3149]
Should `ParameterResource` show on Dashboard alongside other resources? While technically a 'resource' it isn't terribly useful int he dashboard:
![image](https://github.com/dotnet/aspire/assets/4821/da9d418d-08b5-4007-b7ab-f33561e99352)

No run state, no logs, no details, it's just taking up real estate if not more useful.

Should it be:
- removed 
- Parameters moved to some diff grouping/view
- add the value in the details (e.g., the value)

I'd personally vote for removal as the resolved info is likely already available in the other resources details, etc.

**Comment by adamint** [comment]
@davidfowl should the resource server be telling us which resources to show?

**Comment by davidfowl** [comment]
Yea this isn’t a dashboard issue.
