### ISSUE TITLE
WithOtlpExporter should set the otel_exporter_otlp_protocol to grpc

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3166]
We only support gRPC OTLP endpoints in the dashboard (https://github.com/dotnet/aspire/blob/370581feced51bfdff6c037f08b6857d2517d920/src/Aspire.Hosting/OtlpConfigurationExtensions.cs#L24).

https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_protocol

**Comment by JamesNK** [comment]
We don't need to set this in WithOtlpExporter. `OTEL_EXPORTER_OTLP_PROTOCOL` env var can be used to set this value.
