### ISSUE TITLE
Make dashboard print a good error message when configuration is invalid

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#3168]
See https://github.com/dotnet/aspire/pull/3119#discussion_r1538599584

**Comment by leslierichardson95** [comment]
@JamesNK what configuration are you referring to here?  Is it authentication related?

**Comment by JamesNK** [comment]
Configuration here: https://github.com/dotnet/aspire/tree/main/src/Aspire.Dashboard#net-aspire-dashboard
