### ISSUE TITLE
[WebToolsE2E][Aspire] Add a web project to .NET Aspire Application project, the dropdowns of 'Structured', 'Traces' and 'Metrics' on the dashboard don't contain the web project. 

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3169]
**REGRESSION INFO**: Not repro on Dev17.10 Preview 2 (Include Aspire 8.0.0-preview.4.24156.9)

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [34725.203.main] (Includes Aspire 8.0.0-preview.4.24156.9)

**REPRO STEPS**

1. New Project > .NET Aspire Application > named it 'AspireApp1' > .NET 8.0 > Create
2. Right-click Solution > Add > New Project > Choose 'ASP.NET Core Web App (Razor Pages)' > Check 'Enlist in .NET Aspire orchestration' > Create
3. Build and F5
4. On the dashboard, open 'Structured logs' board, and click dropdown.

**ACTUAL**
The dropdown doesn't contain web project.
'Structured':
![image](https://github.com/dotnet/aspire/assets/109339894/848e6b40-369a-4ffd-8393-8db061d2f4de)
'Traces':
![image](https://github.com/dotnet/aspire/assets/109339894/2dc079e9-a7aa-4b08-a99b-8aa415366bf9)
'Metrics':
![image](https://github.com/dotnet/aspire/assets/109339894/2f224d49-526f-4768-9dc1-fbb23ae12e29)

**EXPECTED**
The dropdown contain web project.
'Structured':
![image](https://github.com/dotnet/aspire/assets/109339894/0ce6512c-eeb0-4144-aad1-52be83a01514)
'Traces':
![image](https://github.com/dotnet/aspire/assets/109339894/56c3fd56-4f96-46ea-a3a4-4fba93dba352)
'Metrics':
![image](https://github.com/dotnet/aspire/assets/109339894/f548df0b-fbf9-44fb-88e6-56ecd8a3f15e)

**Comment by balachir** [comment]
@v-reinawang I'm unable to reproduce this issue anymore using latest Aspire 8.0 P5 build (version 8.0.0-preview.3.24175.10). Can you re-try this scenario and let me know if you can still reproduce this consistently? If you cannot reproduce this using latest builds, this issue can be closed.

cc: @v-cazhang

**Comment by v-reinawang** [comment]
@balachir I still repro in VS 17.10.0 Preview 3.0 [34726.233.main] + Aspire 8.0.0-preview.5.24176.9

**Comment by davidfowl** [comment]
Are the service defaults properly wired up?

**Comment by adamint** [comment]
Does not reproduce on VS Version 17.10.0 Preview 3.0 [34725.55.main]

**Comment by v-reinawang** [comment]
Verify that this issue still reproduces in VS 17.10.0 Preview 3.0 [34802.167.d17.10] [includes Aspire 8.0.0-preview.5.24201.12].

**Comment by davidfowl** [comment]
This doesn't repro. Can we get a video? The only way this would happen is if the tooling didnt inject the code to wire up service defaults and I don't see that happening.

**Comment by v-reinawang** [comment]
@davidfowl This is the video: 
![aspire](https://github.com/dotnet/aspire/assets/109339894/bd4099de-332d-4cab-8710-7de1fa67c6ac)

**Comment by davidfowl** [comment]
Can you show the Program.cs for the Razor pages application?

**Comment by davidfowl** [comment]
I can reproduce this, it's a tooling issue. Enlist in aspire orchestration doesn't seem to be working.

cc @phenning @BillHiebert @vijayrkn

**Comment by BillHiebert** [comment]
This has been fixed in latest builds (and will be backported to 17.10-preview5).   Original issue is here https://github.com/dotnet/aspire/issues/3574

**Comment by v-reinawang** [comment]
This is the Program.cs for the Razor pages application.
![image](https://github.com/dotnet/aspire/assets/109339894/574598cc-ec42-4e0e-b3f1-539cbfdd1a8f)

**Comment by balachir** [comment]
@v-reinawang as Bill Hiebert mentioned above, this should be fixed using the final build of VS 17.10 P5. Can you verify and close this issue? Thanks!

cc: @v-elenafeng

**Comment by v-reinawang** [comment]
Verify that this issue has been fixed in the final build of VS 17.10 P5, so close it.
