### ISSUE TITLE
Add Stop button in dashboard.

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspire#3171]
I have an Aspire solution with about 20 projects (from about 10 different solutions).

I want to have a Stop button on each resource so I can stop one of the projects whist leaving the others running.

This will allow me to open the individual solution I want to work on, use `dotnet run` on my Aspire app to get everything running locally, and then click Stop on the project I am about to work on in my IDE.

Additional benefit:
It'd also allow us to simulate other services being offline (a Start button might be good for bringing them back online).

**Comment by davidfowl** [comment]
We'll be added start/stop/restart as part of 295
