### ISSUE TITLE
Verify versioning strategy for AppHost to DCP communication and DCP to IDE communication

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3181]
We need to support the Apphost working with an older DCP or and older version of the IDE protocol (until we GA).

**Comment by karolz-ms** [comment]
That is done with what we currently have for Aspire P6/GA. App host will probe DCP for version info and use different annotations accordingly. DCP will probe VS for protocol support and talk new protocol only if VS supports it.
