### ISSUE TITLE
Embiggen API key

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#3195]
`Guid.NewGuid().ToString()` isn't secure enough. What API should be used to generate the right level of randomness?

**Comment by danegsta** [comment]
Should be using methods from the `System.Security.Cryptography` namespace for getting random bytes. `System.Security.Cryptography.RandomNumberGenerator.GetBytes(32);`, for example. Then use something like `Convert.ToBase64String` to encode.

**Comment by kvenkatrajan** [comment]
@JamesNK  is this being done in the current auth PR for securing localhost?
