### ISSUE TITLE
Add integration tests for resource service auth

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#3200]
Following #3033 and #3400, we need integration test coverage for auth between the dashboard and a resource service.

This includes both API-key and certificate based auth. We don't currently ship a resource service that uses certificates, so we'd likely need to mock one for test purposes.

- [ ] Unsecured https://github.com/dotnet/aspire/pull/3824
- [ ] ApiKey https://github.com/dotnet/aspire/pull/3824
- [ ] Certificate

**Comment by kvenkatrajan** [comment]
@drewnoakes  - are all the scenarios covered with #3824 ?

**Comment by drewnoakes** [comment]
This was duped in #3739. Closing this as a dupe.
