### ISSUE TITLE
Create a playground app that integrates the dashboard with keycloak

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#3201]
https://github.com/keycloak/keycloak

**Comment by leslierichardson95** [comment]
@drewnoakes Can you please provide some more info here?

**Comment by drewnoakes** [comment]
The idea is to explore integration of keycloak under Aspire. PR #4289 does that exploration and would close this issue if merged.

**Comment by radical** [comment]
@drewnoakes should this be closed now as #4289 has merged?
