### ISSUE TITLE
[AzureTools][Aspire] Fail to F5 with an error when creating a .NET Aspire Starter App Application on 17.10 preview 2 and then running on 17.10.0 Preview 3.0 with Aspire 8.0.0-preview.5.24176.9

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#3209]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version**: 17.10.0 Preview 3.0 [34726.240.main]
**Aspire Version:** 8.0.0-preview.5.24176.9
Apply NuGet Feeds
**Regression:** Not a regression
**Podman Desktop:** 1.8.0
**Podman:** 5.0.0

**REPRO STEPS:**

1. Create a .NET Aspire Starter App Application on 17.10 preview 2.
2. Open this project on 17.10 preview 3 main-34726.240 with Aspire 8.0.0-preview.5.24176.9 -> F5.
3. Check whether succeeds to F5 without any error.

**Expect:**
Succeed to F5 without any error.

**Actual:** 
Fail to F5 with an error.
![image](https://github.com/dotnet/aspire/assets/62053665/923d3af3-9e89-4acc-a887-9d4f0c235b37)

**More Info:**
1. This issue also **reproduces** for ASP.NET Core web API project with 'Enlist in Aspire orchestration' checked.
2. This issue also **reproduces** for .NET Aspire Starter App Application with redis checked.

**Comment by davidfowl** [comment]
This code is gone from aspire in preview 5, you are using preview 4, it's in your screenshot.

**Comment by davidfowl** [comment]
No. We'll be keeping compatibility after preview 6. You can't run preview 4 aspire.hosting with the preview 5 workload.

**Comment by v-mengwe** [comment]
Got it,  I will add an unsupported comment and close it, does it make sense?

**Comment by davidfowl** [comment]
I think this can be closed, but want to test this scenario generally when we GA.

**Comment by v-mengwe** [comment]
Close this issue and wait for support before verifying again.
