### ISSUE TITLE
[WebToolsE2E][Aspire] Creating and building an Aspire project encountered an error: 'ServiceDiscoveryHttpCli entBuilderExtensions.UseServiceDiscovery(IHttpClientBuilder)' is obsolete.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3211]
**REGRESSION INFO**: Not repro on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24176.15]
3. Apply NuGet Feeds

**REPRO STEPS**

1. Open Command Prompt, run the following commands to create and build an Aspire application

```
dotnet new aspire -o AspireApp1
cd AspireApp1
dotnet build
```

**ACTUAL**
The build failed with an error.
 error CS0619: 'ServiceDiscoveryHttpCli
entBuilderExtensions.UseServiceDiscovery(IHttpClientBuilder)' is obsolete: 'This method is obsolete and will be removed
 in a future version. The recommended alternative is to use the 'AddServiceDiscovery' method instead.'
![image](https://github.com/dotnet/aspire/assets/109339894/4828511b-52d6-4244-bab4-74e6bac0487e)

**Workaround**: Use the 'AddServiceDiscovery' method instead of the 'UseServiceDiscovery' method to solve this error.

**EXPECTED**
The build can succeed without any errors.
![image](https://github.com/dotnet/aspire/assets/109339894/2d52fe34-5024-4a2b-805b-01e4237842ef)

**Comment by DamianEdwards** [comment]
This is fixed.

**Comment by v-reinawang** [comment]
This issue has been fixed on Aspire 8.0.0-preview.5.24177.11
