### ISSUE TITLE
Generate and persist random resource group names, don't use the machine name.

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3259]
Right now, we're using the machine name to get a stable resource group name if one wasn't specified. We should instead generate a random name and store it in user secrets.

**Comment by mitchdenny** [comment]
I've been thinking about this a bit. I am wondering whether we don't create a default resource group name. My reasoning is that through Aspire people are potentially going to create a few resource groups, and if you have a team of developers sharing a subscription, like we do with our R&D sub then it will be hard to know who owns which resource group and which ones are old and safe to be deleted.

By forcing the user to input the resource group name we give them the ability to use "their system" for naming them, and right now we already have to ask for the sub ID and location so getting them to input the resource group name is not a big issue IMHO.

**Comment by eerhardt** [comment]
I think we need a better input mechanism all together here. The current solution has the following drawbacks:

1. It is "one at a time" experience. F5 - get an error. Fix the error. F5 - get a new error. Fix the new error. Repeat until finally satisfied.
2. I have to somehow know the magic strings and format (and where to put them). `westus3`? What's my subscription ID again?

If we had a more interactive mechansim (think like `azd` does), the experience would be MUCH better, and prompting for an "environment name" wouldn't have such friction. Imagine if you F5 or `dotnet run` and these values are needed, you got a CLI experience like `azd` which listed the subscriptions you had access to, the locations available, and one thing you needed to make up: an environment name. This would be an acceptable UX for me.

**Comment by davidfowl** [comment]
For GA, lets settle on throwing a better error that encapsulates *all* of the required information instead of doing the one at time thing. Let’s also resolve the issue of storing the machine name in the sub (maybe it can be an opt-in tag).

Post GA, let’s design the interactive experience that works both on the command line and in IDEs (@mitchdenny and several others have been exploring this).

**Comment by mitchdenny** [comment]
We already say all the information you need in the error :) 
![image](https://github.com/dotnet/aspire/assets/513398/1c461a6b-1d48-4b25-968d-3621905d3066)

We'll also have a doc page (pending):
https://learn.microsoft.com/dotnet/aspire/deployment/azure/local-provisioning
