### ISSUE TITLE
Expose Aspire.Hosting.Utils.PasswordGenerator class

### ISSUE THREAD

**Issue by danbopes** [dotnet/aspire#3263]
The `Aspire.Hosting.Utils.PasswordGenerator` class is currently marked as internal, limiting its accessibility to external developers. I propose making it public for the following reasons:

Custom Extensions: We want to encourage developers to create their own Aspire resources. By exposing `PasswordGenerator`, we can help them to build custom resources efficiently and securely.
Security: Rolling custom password generation methods can introduce vulnerabilities. A publicly available, battle-tested utility ensures better security practices.
Code Duplication: I'm currently duplicating this code to make my own extension. Making `PasswordGenerator` public encourages code reuse and maintainability.

Thank you for your consideration <3

**Comment by danbopes** [comment]
Looks like this was recently added. I was looking at the rabbitmq source for the latest preview, and it used the PasswordGenerator class to generate it's passwords. I can use this now instead.

**Comment by davidfowl** [comment]
@eerhardt we should improve this API
