### ISSUE TITLE
Endpoint allocation can get stuck some times

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#3265]
This code in `ApplicationExecutor.CreateServicesAsync` should have a timeout to either fail or at least log a message that it is still waiting on address allocation for some services, and list those services.

https://github.com/dotnet/aspire/blob/93a1efbc4d8798903828eb5da7ffb50b873dc513/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs#L826-L845

This was hit in running `Aspire.EndToEnd.Tests` where 1/20 runs fails where it gets stuck waiting for a service to get allocated.

<img width="990" alt="Screenshot 2024-03-28 at 15 25 23" src="https://github.com/dotnet/aspire/assets/1472/87fd7148-fb75-43b8-88f3-d3c03a83ec00">
In the above run it is stuck waiting for `redis`, till the test infrastructure times out after 5 minutes.

[Full log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-pull-2800-merge-6d339efb36ed4a7986/Aspire.EndToEnd.Tests-5/1/console.af9c471f.log?helixlogtype=result). And corresponding dcp logs are [here](https://helix.dot.net/api/jobs/6d339efb-36ed-4a79-862f-93fb9c517d6c/workitems/Aspire.EndToEnd.Tests-5?api-version=2019-06-17) in `logs/dcp-diag-logs`, and the corresponding [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=622703&view=results).

Note that this is not specific to redis.

cc @karolz-ms @eerhardt

**Comment by karolz-ms** [comment]
CC @dbreshears @danegsta 

In a way similar to what @mitchdenny has done, we should probably retry this watch a few times before timing out. Alternative (or last-ditch effort, we could do both) could be to explicitly query the remaining resources and see if they have the address information we are looking for.
