### ISSUE TITLE
Put all database connection strings in keyvault

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3299]
Today database connection string always grab the parent connection string (the database server) and they append the database portion of the connection string. This is fine for resources that don't put their connection strings in key vault, but we can optimize the experience so that the deployment tool never needs to grab keyvault secrets to create container apps.

**Comment by davidfowl** [comment]
Huge benefit as the secrets are auto pulled from keyvault every 30 mins https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=azure-portal

**Comment by mitchdenny** [comment]
Need to have some more discussion about this.
