### ISSUE TITLE
[WebToolsE2E][Aspire] Add Azure Key Vault to Aspire project, publish failed with 'ContainerCrashing' error: System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3311]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [34730.35.d17.10] (Includes Aspire 8.0.0-preview.5.24178.3)
3. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24179.3]
4. Apply NuGet Feeds
5. Install Docker Dektop
6. Install azd

**REPRO STEPS**

1. New Project > ASP.NET Core Empty project > name it 'AspireKeyVault'> 8.0 > check 'Enlist in Aspire Orchestration'
2. Update the Program.cs of AspireKeyVault project with following codes:
```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

string? _mySecret = builder.Configuration["myAppSetting"];

var result = string.IsNullOrEmpty(_mySecret) ? "Null" : _mySecret;
app.MapGet("/", async context =>
{
await context.Response.WriteAsync($"Secret is {result}");
});
app.Run();
```

3. Right-click the AspireKeyVault > Add > Connected Services > Click the Add button under 'Service Dependencies' and select "Azure Key Vault", click Next > Finish
4. After the Azure key Vault configured, click "..." beside the configured Azure Key Vault, and select "Manage in Azure portal", In the portal, go to Secrets tab and click "+ Generate/Import". Add a secret called "myAppSetting" and give a value like "Hello tester".
5. Build and F5
6. Right-click solution > Open folder in file explorer, In the opened folder, right-click any place > open in terminal
7. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter
8. Running 'azd up'
9. Open the resource group, click the container app , open 'Application Url'

**NOTE**: F5 can show the secret value

**ACTUAL**
Open AspireKeyVault container app shows 'ContainerCrashing'.

 Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Uri..ctor(String uriString)
   at Program.<Main>$(String[] args) in C:\Users\v-reinawang\source\repos\AspireKeyVault\AspireKeyVault\Program.cs:line 4

![image](https://github.com/dotnet/aspire/assets/109339894/4f2b8d07-1d37-450b-bd65-3ccf0e5bec5d)

**EXPECTED**
Doesn't show container crashing error.

**Comment by v-reinawang** [comment]
Because there is no problem with Debug, I don't know how to find the full stacktrace.

When I add Azure Key Vault in Connected Services, the code `new Uri` is automatically added to the Program.cs file: 
![image](https://github.com/dotnet/aspire/assets/109339894/8be2836b-a711-4ba0-aaf9-598583f29db9)

**Comment by eerhardt** [comment]
> When I add Azure Key Vault in Connected Services, the code new Uri is automatically added to the Program.cs file:

That seems to be a problem with Connected Services. I'm not sure who is supposed to set that `VaultUri` environment variable, but Aspire doesn't. This isn't how you use Key Vault with Aspire.

Closing this as external. This isn't a problem with Aspire.
