### ISSUE TITLE
Extra TAB is required to activate the links present in the table.:A11y_A11y_.NetAspireDashboard_Resources_Grid_Keyboard

### ISSUE THREAD

**Issue by PoojaNamde** [dotnet/aspire#3315]
"[Check out Accessibility Insights](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0)! - Identify accessibility bugs before check-in and make bug fixing faster and easier."

### Tags:
#A11yTCS; #A11yMAS; #A11ySev3 #Win11; #ChromiumEdge; #FTP; #DesktopWeb; #.NET Core; #SH_.Net Aspire Dashboard_Web_Mar2024; #WCAG2.4.3; #Keyboard;

### Environment Details:
Application Name: .Net Aspire Dashboard
URL: https://localhost:19888/
Chrome Version 122.0.2365.80 (Official build) (64-bit)
Window Version: Win 11
OS Build: 22621.3085

### Repro Steps:

1. Hit the URL: http://localhost:15888/.
2. TAB to "Resources" tab item and hit select the tab by pressing Enter key.
3. Navigate to any 'View' link and press ENTER key.
4. Observe that when we navigate using TAB key and hit ENTER key the link is not getting activated.

### Actual Results:
Extra TAB is required to activate the links present in the table.

**Similar issue is observed in throughout the application for the table links.**

### Expected Results:
Extra TAB should not be needed to activate interactive controls in the table.

### User Impact:
Keyboard users will not be able to interact with the control with one TAB, they will need to press one more TAB every time.

### Attachment:
[3315_A11y_.NetAspireDashboard_Resources_Grid_Keyboard.webm](https://github.com/dotnet/aspire/assets/90901519/e3a9ddb2-2958-4bc3-89c7-c637ff01923e)

**Comment by adamint** [comment]
This is now by design, since enter/click on a cell will open the details view. Whereas, to invoke an action on cell content, you will need to actually enter the cell.
