### ISSUE TITLE
Improve browser token auth to use handler instead of middleware

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#3347]
Browser token auth is implemented using cookies auth + middleware. It's possible to move it into an auth handler.

Expert care should be applied when doing this as there are many moving pieces to Aspire auth.

**Comment by davidfowl** [comment]
@JamesNK you did this right?

**Comment by JamesNK** [comment]
No. This is still a thing: https://github.com/dotnet/aspire/blob/332a0ccbf9ce4ad8a48862c886989f53b3f9340a/src/Aspire.Dashboard/Model/ValidateTokenMiddleware.cs

Doing this really isn't important. The middleware works fine.
