### ISSUE TITLE
Add support for pooled DbContext factory

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/aspire#3356]
`AspireSqlServerEFCoreSqlClientExtensions` has a `AddSqlServerDbContext` method that registers a `DbContext` pool, but there's no way to register a `DbContext` factory pool.

To register a `DbContext` factory pool, I had to copy a lot of Aspire code, because it's unnecessarily internal.

**Comment by davidfowl** [comment]
https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-4#new-enrich-methods

**Comment by paulomorgado** [comment]
@davidfowl,

> https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-4#new-enrich-methods

I found that going through the source code. But I want to use that on a library the I want to depend on `IServiceCollection` and `IConfiguration` and do not restrict to `IHostApplicationBuilder`.

**Comment by eerhardt** [comment]
Pooled DbContext factory is supported by adding your DbContext factory yourself using the "normal" EF APIs. Then you can call "EnrichSqlServerDbContext" to add the Aspire dependencies (OpenTelemetry and HealthChecks).

We decided to only support pooled DbContext in `AddXXDbContext` and for every other situation, the developer uses the EF APIs to tweak how they want to add the DbContext to the service collection, and then call "Enrich" to add the Aspire dependencies.

See the conversation in https://github.com/dotnet/aspire/issues/1403 and https://github.com/dotnet/aspire/pull/2125.
