### ISSUE TITLE
Feature Idea: Connecting Metrics to Traces

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#336]
Now that we have both Metrics and Traces in the dashboard, we should consider connecting the two, so I can drill in to data I see in my Metrics graphs, and figure out why something is taking so long.

For example, in the sample app, the first time I click the cart button on the top right, it causes a spike in duration of HTTP requests.

![image](https://github.com/dotnet/aspire/assets/8291187/3a6d246f-a269-417b-bb80-bac99b60e225)

It would be great if I could drill in to that request to see what took so long.

One idea is to use [exemplars](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exemplars), which is a feature in OpenTelemetry that allows getting a value in a histogram bucket and being able to see the trace ID for that value, so you can jump to a trace.

cc @davidfowl @JamesNK @samsp-msft

**Comment by samsp-msft** [comment]
The exemplar support is going to be shipped with the OpenTelemetry.NET 1.9 release next week.

@JamesNK

**Comment by samsp-msft** [comment]
I would suggest something like: 
![image](https://github.com/dotnet/aspire/assets/54915162/45a7c442-b52b-4022-b18e-4658888f34e2)
Where the exemplars are shown as points on the graph. Hovering over the point will show the value and time.

Clicking a point will bring up a popup panel showing the details of the point, and the ability to link off to the traces page or logs for the SpanId associated with the exemplar.
![image](https://github.com/dotnet/aspire/assets/54915162/b8492bed-fffc-4728-8780-da25354f9fbc)

**Comment by samsp-msft** [comment]
Clearing milestone so we can re-triage

**Comment by mitchdenny** [comment]
@samsp-msft I'm assuming this is something we will do eventually right? So can go back on Backlog (its not something we would _not_ do ... its just about resources & priorities).

**Comment by samsp-msft** [comment]
@mitchdenny Exemplars is the cool new feature for OTel and something we will be making noise about. I want people to be able to use/view them for Aspire from the dashboard. 
The OTel library support has shipped, what's missing at this point is support in the dashboard.
