### ISSUE TITLE
IAsyncEnumerable returned from ResourceNotificationService.WatchAsync doesn't end when the host shuts down

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#3378]
The `IAsyncEnumerable` returned by `ResourceNotificationService.WatchAsync()` doesn't end when the host is shutting down. This means if you have a `BackgroundService` consuming `ResourceNotificationService` in its `ExecuteAsync` method, it will cause the app shutdown to hang until the host's shutdown timeout kicks in (30 seconds). Ideally the `IAsyncEnumerable` should automatically complete when the host is shutting down, rather than the caller having to pass a `CancellationToken` in to `WatchAsync` to force it to stop, so that a consumer can get all the notifications right up until the underlying stream is closed due to the host shutting down.

**Comment by davidfowl** [comment]
This was done in https://github.com/dotnet/aspire/pull/4444
