### ISSUE TITLE
When publishing manifest, dashboard URL with token is output

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#3387]
Started happening after adding auth to the dashboard.

![image](https://github.com/dotnet/aspire/assets/513398/42d005fe-edec-4f4e-9585-9c4b59ce8ff2)

**Comment by mitchdenny** [comment]
@JamesNK PTAL

**Comment by JamesNK** [comment]
Is there an assumption that the last console output is the path? That seems flaky.

And are there no until tests that there is no other console output? That's a recipe for constant regressions. If this is the behavior then there MUST be tests here.

**Comment by mitchdenny** [comment]
The fact that it is last isn't really the issue, its more that its outputting the URL even when the dashboard isn't spinning up. The output is unnecessary :)

**Comment by JamesNK** [comment]
I misunderstood the issue. The problem is just incorrect console output. Will omit for publish.
