### ISSUE TITLE
Update Azure SignalR hosting readme to note ConnectionString usage and client methods to use

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#3390]
The SignalR resource sets the connection string information as a `ConnectionStrings__{name}`  But the Microsoft.Azure.SignalR client by default looks for `Azure:SignalR:ConnectionString` -- there is an override to supply it and the developer would have to know now to use 

```
.AddAzureSignalR(builder.Configuration.GetConnectionString("signalr"));
```

Should we emit the default expected config setting instead? If not, convert this to an issue to update readme/docs on this resource to note the client consumption side

**Comment by christiannagel** [comment]
Instead of using `.AddAzureSignalR()`, I was using `.AddNamedAzureSignalR("signalr")` which is documented to read form connectionstrings.

**Comment by timheuer** [comment]
Perfect. Converting this to updating the readme to point this out
