### ISSUE TITLE
Ensures role attribute has an appropriate value for the element.:A11y_.NetAspireDashboard_Resources_Resources_AI4W.

### ISSUE THREAD

**Issue by PoojaNamde** [dotnet/aspire#3397]
"[Check out Accessibility Insights](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0)! - Identify accessibility bugs before check-in and make bug fixing faster and easier."

**Please do not close this bug. This bug should only be closed by Trusted Tester after verification.**

### Tags:
#A11yTCS; #A11yMAS; #A11ySev2; #A11yAuto; #FTP; #Win11; #ChromiumEdge; #FTP; #DesktopWeb; #.NET Core; #SH_.Net Aspire Dashboard_Web_Mar2024; #WCAG1.3.1; #AI4W; #Element:TabItems;

### Environment Details:
Application Name: .Net Aspire Dashboard
URL: https://localhost:19888/
Chrome Version 122.0.2365.80 (Official build) (64-bit)
Window Version: Win 11
OS Build: 22621.3085

### Repro Steps:

1. Hit the URL: https://localhost:15887/ and login with valid credentials.
2. Turn on Automated checks toggle button in "Accessibility Insights for Web".
3. Observe the issue.

### Issue: 
Ensures role attribute has an appropriate value for the element (aria-allowed-role - https://dequeuniversity.com/rules/axe/4.7/aria-allowed-role?application=msftAI)

### Target application: 
TestShop structured logs - http://localhost:15888/structuredlogs

### Element path: 
#f41db7144

### Snippet: 
<nav id="f41db7144" class="nav-menu-container" style="display: flex;" role="list" b-dkkdhxy2t7="">

### How to fix: 
Fix any of the following:
  ARIA role list is not allowed for given element

### Environment: 
Microsoft Edge version 123.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.41.0 (axe-core 4.7.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

### Attachment:
![3397_A11y_ NetAspireDashboard_Resources_Resources_AI4W](https://github.com/dotnet/aspire/assets/90901519/9aeec355-9ebe-4345-9bdd-304d10b7c9c9)

**Comment by adamint** [comment]
This is an issue with fluentui-blazor. See https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Components/AppBar/FluentAppBar.razor for the incorrect roles being applied. Linking to created issue over on that repository

**Comment by adamint** [comment]
@PoojaNamde please re-test

**Comment by adamint** [comment]
@PoojaNamde

**Comment by SwatiJo** [comment]
![image](https://github.com/dotnet/aspire/assets/167469595/585f6425-cb41-427b-a03a-6aaaadd570cb)

**Comment by SwatiJo** [comment]
Issue has been fixed.

**Comment by Yash14j** [comment]
GithubTags: #Closed;
