### ISSUE TITLE
OrleansService generates a new GUID each time.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#3399]
@ReubenBond @benjaminpetit  I noticed that every time we run manifest generation on the Orleans playground sample, the cluster ID is recreated. This is probably not what we want for deployment scenarios. Instead we should probably be auto injecting a parameter into the app model like @eerhardt did for Postgres admin usernames and passwords.

**Comment by ReubenBond** [comment]
@mitchdenny parameters are added to resources, but the OrleansService type is not currently a resource - there was opposition to making it one. Should we reconsider that? Otherwise, what do you suggest?

**Comment by davidfowl** [comment]
Not sure it needs to be a resource, but maybe it should add a parameter for cluster id though.

**Comment by ReubenBond** [comment]
Opened a PR https://github.com/dotnet/aspire/pull/3433
