### ISSUE TITLE
Cannot override default HttpClient resiliency settings when using CreateHttpClient from Aspire.Hosting.Testing

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#3431]
The `CreateHttpClient` extension method on `Aspire.Hosting.Testing.DistributedApplicationHostingTestingExtensions` uses the `IHttpClientFactory` registered in the `DistributedApplication` instance's `IServiceProvider` to create an `HttpClient` for the specified resource (and optionally endpoint name). This `HttpClient` is pre-configured with the standard resiliency handler but this isn't always sufficient for testing scenarios where longer timeouts, etc. might be desired. Unfortunately there doesn't seem to be a way to modify the resiliency handler that's added by default, only add another one (i.e. every call to `IHttpClientBuilder.AddStandardResilencyHandler()` adds another resiliency pipeline to the `HttpClient`).

In the Aspire Samples tests and integration tests in this repo, extra methods have been added to enable creating an `HttpClient` without using the `IHttpClientFactory` that is registered in the `DistributedApplication`'s `IServiceProvider` because of this issue.

We should consider ways to make it easier to create an `HttpClient` instance for a resource/endpoint with custom configuration, or remove the automatic registration of the standard resiliency handler and leave it to the consumer to add the resilience they want.

/Cc @ReubenBond @radical @martincostello @eerhardt 

Related: dotnet/extensions#4814

**Comment by DamianEdwards** [comment]
@ReubenBond this is fixed now I think yes?

**Comment by ReubenBond** [comment]
Fixed by #3845
