### ISSUE TITLE
Update to OpenTelemetry.Instrumentation.AspNetCore v1.8.0

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#3439]
https://github.com/open-telemetry/opentelemetry-dotnet/releases/tag/Instrumentation.AspNetCore-1.8.0

FYI @samsp-msft

**Comment by davidfowl** [comment]
Done in https://github.com/dotnet/aspire/pull/3351

**Comment by DamianEdwards** [comment]
Are you sure? This is the AspNetCore instrumentation package that was released a few days later.

**Comment by davidfowl** [comment]
Woops

**Comment by davidfowl** [comment]
NOTE: When you run this as a container, the URL will be wrong.

**Comment by JamesNK** [comment]
OpenTelemetry.Instrumentation.AspNetCore is 1.8.1.
