### ISSUE TITLE
Log streams not showing up

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#3458]
Seems like after #3343 the log streams are not responding and printing to the screen. 

https://github.com/dotnet/aspire/assets/4821/e0f8f872-5154-4473-b19d-47d49ea293ec

**Comment by davidfowl** [comment]
Bug was caused by the [log virtualization changes](https://github.com/dotnet/aspire/pull/3075): Surprised nobody has seen this until now.

```
System.InvalidOperationException: 'The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.'
```

**Comment by ReubenBond** [comment]
Thanks for investigating @davidfowl. Let's revert it and apply it only to the non-Blazor bits, which are the ones the test was complaining about anyway.

**Comment by davidfowl** [comment]
I think most of them are fine, I reverted the one that touches ui.

**Comment by davidfowl** [comment]
Moving this out of p6 since it wasn't backported.
