### ISSUE TITLE
Seq component is broken with latest UseOtlpExporter (Does the `UseOtlpExporter` change prevent other Aspire components changing OTEL config?)

### ISSUE THREAD

**Issue by liammclennan** [dotnet/aspire#3546]
The [Seq Aspire component](https://learn.microsoft.com/en-us/dotnet/aspire/logging/seq-component?tabs=dotnet-cli) relies on the OTEL `AddOtlpExporter` method to extend telemetry configuration and this has now [been made incompatible with the ServiceDefaults generated code](https://github.com/open-telemetry/opentelemetry-dotnet/pull/5400) (as `UseOtlpExporter` makes `AddOtlpExporter` throw an exception). 

Is there a way that an Aspire component can extend the telemetry configuration?

**Comment by davidfowl** [comment]
cc @reyang

**Comment by CodeBlanch** [comment]
@liammclennan Are you trying to add additional OtlpExporters or change the settings for the ones added by Aspire?

**Comment by liammclennan** [comment]
@CodeBlanch to add additional OtlpExporters

**Comment by CodeBlanch** [comment]
@liammclennan You could do something like this: https://github.com/dotnet/aspire/compare/main...CodeBlanch:seq-otel-otlp-registration?expand=1

There is a slight behavioral difference when retrieving settings that way (I dropped a note about it in there) but otherwise it will work the same as calling the extension.

**Comment by davidfowl** [comment]
cc @eerhardt

**Comment by liammclennan** [comment]
@CodeBlanch thanks for putting that together. 

Is there a way that can use the normal .NET configuration system? Given how much OpenTelemetry relies on configuration I think it would be hard to explain to consumers of the component why their OTEL configuration is not being applied.

**Comment by eerhardt** [comment]
@liammclennan - do you think that the Seq component can be updated to support this? If so, do you want to send a PR? We are in the middle of locking down for preview6. If we get a change quickly, it can still make `8.0.0` GA.

Or is the ask to change opentelemetry?

**Comment by nblumhardt** [comment]
Hi @eerhardt! It just clicked over to Saturday here, so not sure whether @liammclennan will be online this morning, but I think it's fair to say we'll assemble a PR for preview6 with as much as we can get working (whether we're able to incorporate JSON configuration support or not).

This would likely be Monday in our time zone (so Sunday evening in yours), let me know if we'd miss the boat in that case 😄

**Comment by eerhardt** [comment]
Reopening to track backporting to release/8.0.
