### ISSUE TITLE
UI endpoints, dashboard UI truncation

### ISSUE THREAD

**Issue by pmdot** [dotnet/aspire#3550]
![image](https://github.com/dotnet/aspire/assets/39914325/c53ac7f1-fae8-4788-a9bc-f338a68db776)

Hey everybody! Something about the ui. With preview 5, as you see at the picture above, the endpoints of the first resource are hidden. Mae by the first point has to be shown and trimmed, as text href, by default. And the others, if any,  shown in a pickable dropdown list. Thank you!

Greetings,
Petar

**Comment by kvenkatrajan** [comment]
@JamesNK  you have a PR for this..thanks!- assigning it over to you.
