### ISSUE TITLE
[WebToolsE2E][Aspire] When running Aspire app with http, In the pop-up browser, move the mouse to the "Where can I find the token?" and then the image cannot be displayed in the pop-up box.

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#3603]
**REGRESSION INFO:** This is a new feature on Aspire 8.0.0-preview.6.24210.28

**INSTALL STEPS**

1.Clean machine: Win11 x64 23h2 ENU
2.Install VS Code[1.88.0] and C#[2.26.9 main], C# Dev Kit[1.4.139 main]
3.Install SDK 8.0.204(latest-released-build)
4.Install Aspire 8.0 P6 workload version 8.0.0-preview.6.24210.28
5.Apply NuGet Feeds

**REPRO STEPS**

1.Open CMD, creating an Aspire App using following commands:
```
dotnet new aspire -o aspire1
cd aspire1
code .
```
2.Open launchSettings.json under Properties folder in xxx.AppHost, add below code:
`"ASPIRE_ALLOW_UNSECURED_TRANSPORT": "true"`
![image](https://github.com/dotnet/aspire/assets/88425944/fe48b6c2-f909-4f4c-9bd7-a7c05a7474bf)
3.Press 'Ctrl+shift+P' > Debug: Select and Start Debugging > C# > C#: xxx.AppHost[http]
4.In the pop-up browser, move mouse to 'Where do I find the token?'

**ACTUAL:**
the image cannot be displayed in the pop-up box.
![image](https://github.com/dotnet/aspire/assets/88425944/308e859f-4a51-4418-af3d-b7eb7c34df30)
![image](https://github.com/dotnet/aspire/assets/88425944/3e56e38b-26c7-4fe9-a1f7-3f31cbd9c0ed)

**NOTE:**
1.Run aspire project with https, it works well.
2.This issue also repro on Mac OS.

**EXPECTED**
the image can be displayed normally.
![image](https://github.com/dotnet/aspire/assets/88425944/5625b473-5dca-4ad1-868a-7dcfdc5a6dbe)

**Comment by tlmii** [comment]
It looks like this is caused by this line:

https://github.com/dotnet/aspire/blob/19ed207c8bd9f44c789f9bba1ca76ec4c9115500/src/Aspire.Dashboard/Model/BrowserSecurityHeadersMiddleware.cs#L29

From the browser console logs:

> Refused to load the image 'http://localhost:15888/img/TokenExample.png' because it violates the following Content Security Policy directive: "img-src data: https:".

@JamesNK Do you know, is it possible to change that to only be present (or only take effect) when the site is running under https?

@v-polly To ease getting a repro in similar cases, it would be helpful to also check the browser console logs and networking tab for any relevant errors messages.

**Comment by v-polly** [comment]
@tlmii Thanks for reminder, I have updated the 'ACTUAL' picture in this issue above.

**Comment by JamesNK** [comment]
Fix: https://github.com/dotnet/aspire/pull/3635

**Comment by v-polly** [comment]
Verified this issue with the latest aspire preview 6 [8.0.0-preview.6.24214.1], it is not reproduced and fixed.
