### ISSUE TITLE
[WebToolsE2E][Aspire][Mac x64]When running Aspire app with http/https, move the mouse to the "Where can I find the token?" and the code is displayed incompletely in the pop-up box on safari browser.

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#3604]
**REGRESSION INFO:** This is a new feature on Aspire 8.0.0-preview.6.24210.28

**INSTALL STEPS**

1.Clean machine: Mac x64
2.Install SDK 8.0.204(latest-released-build)
3.Install Aspire 8.0 P6 workload version 8.0.0-preview.6.24210.28
4.Apply NuGet Feeds

**REPRO STEPS**

1.Open Terminal, run the following commands to create and run the project using https:
```
dotnet new aspire -o aspire1
cd aspire1/aspire1.AppHost
dotnet run -lp https
```
2.In the pop-up browser, move mouse to 'Where do I find the token?'

**ACTUAL:**
The code is displayed incompletely
![image](https://github.com/dotnet/aspire/assets/88425944/2280e920-da93-4596-b923-a17c6691965d)

**NOTE:**
1.This issue only repro on Mac x64 with safari browser [version 17.4.1(19618.1.15.11.14)]
2.This issue not repro on Edge browser.
3.This issue not repro on Mac arm64/Win x64.

**EXPECTED**
The code is displayed completely and in the pop-up white text box
![image](https://github.com/dotnet/aspire/assets/88425944/281440b3-f108-4f5e-afbc-ffbec564a29c)

**Comment by v-polly** [comment]
I verified this issue on Mac x64's Safari browser[version 17.4.1 (19618.1.15.11.14)].
Configuration:  aspire 8.0GA [8.0.0-preview.7.24229.8] + C# [[2.29.3](https://dev.azure.com/dnceng/internal/_build/results?buildId=2440823&view=results) main] + C# Dev Kit [[1.4.182](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=9498899&view=results) main] + SDK 8.0.204(latest-released-build).It still reproduce.
(Worked well on Edge/Chrome)

**Comment by adamint** [comment]
This does not reproduce on `8.1`, however a separate issue does: the popup gets cut off and you are not able to scroll
<img width="1035" alt="image" src="https://github.com/dotnet/aspire/assets/20359921/159c0c38-6b10-419a-8523-d10aa49cd559">

@v-polly please test with 8.1

**Comment by v-sherryfan** [comment]
@adamint Verified this issue still repro with latest Aspire 8.1 on Mac x64.
![image](https://github.com/user-attachments/assets/465ae540-3903-4bb7-892f-1b8e041f6945)

**Comment by adamint** [comment]
Ah, I see it's x64 not arm64

**Comment by adamint** [comment]
This is evidently a bug in Safari and there is no obvious fix for this, we should file an external bug against Safari and close.
@v-sherryfan

**Comment by adamint** [comment]
Per above comment, closing
