### ISSUE TITLE
[WebToolsE2E] Using CLI, dotnet new Aspire Starter App and dotnet run, then wait for 30 seconds, we will see a warning saying it failed to get the dashboard logs

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#3612]
**REGRESSION INFO:** This is a new feature on Aspire 8.0.0-preview.6.24210.28

**INSTALL STEPS**
1.Clean machine: Win11 x64 23h2 ENU
2.Install SDK 8.0.204 (latest-released-build)
3.Install Aspire 8.0 P6 workload version 8.0.0-preview.6.24211.5, apply feeds

**REPRO STEPS**
1. Open Command Prompt
2. Create new app `dotnet new aspire-starter -o AspireStarterApp03`
3. Go to folder `cd AspireStarterApp03\AspireStarterApp03.AppHost`
4. Run the app `dotnet run`
5. Wait for about 30 seconds

**ACTUAL**
We will see a warning saying it failed to get the dashboard logs
![image](https://github.com/dotnet/aspire/assets/8246794/6f88bd6b-8198-4809-8479-b06d79bc2439)

Before opening the URL of the dashboard in the browser, I was doing something else. When I came back to open the URL, I see this warning which is a bit confusing.

**EXPECTED**
The warning message should be more clear about what timed out and after how long

**Comment by davidfowl** [comment]
Is it consistent?

**Comment by davidfowl** [comment]
I can reproduce.
