### ISSUE TITLE
[WebToolsE2E] After doing dotnet run, I'm able to view the dashboard even without needing to provide the token in the URL

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#3613]
**REGRESSION INFO:** This is a new feature on Aspire 8.0.0-preview.6.24210.28

**INSTALL STEPS**
1.Clean machine: Win11 x64 23h2 ENU
2.Install SDK 8.0.204 (latest-released-build)
3.Install Aspire 8.0 P6 workload version 8.0.0-preview.6.24211.5, apply feeds

**REPRO STEPS**
1. Open Command Prompt
2. Create new app `dotnet new aspire-starter -o AspireStarterApp03`
3. Go to folder `cd AspireStarterApp03\AspireStarterApp03.AppHost`
4. Run the app `dotnet run`
- You will see the following output
![image](https://github.com/dotnet/aspire/assets/8246794/6f88bd6b-8198-4809-8479-b06d79bc2439)
5. Now, instead of clicking the full URL, manually type in `https://localhost:17021` in the browser and hit Enter

**ACTUAL**
Dashboard shows up successfully
![image](https://github.com/dotnet/aspire/assets/8246794/4b1f22ea-7ec8-4e2a-8c23-8f558b1ba2f6)

**EXPECTED**
It should prompt to login to the dashboard because I didn't provide the token in the URL

**Comment by davidfowl** [comment]
It might mean you have the cookie already? Is this a clean machine?

**Comment by JamesNK** [comment]
It's probably the cookie. It is saved for 3 days (rolling expiry).

Delete it from your browser with dev tools and try again:

![image](https://github.com/dotnet/aspire/assets/303201/deb506c6-3bbf-47ae-b8f1-1aa36cdef3ec)

You can delete all or just `.AspNetCore.Cookies` specifically.

**Comment by mitchdenny** [comment]
@JamesNK what is the status of the browser launching with the auth token pre-provided? I thought when the browser launched the token would be in the URI so it wouldn't need to be pasted in. I'm running VS main with preview 6 bits and if I clear the cookies in the browser and launch a project based on the starter kit I get prompted to provide the token.

**Comment by JamesNK** [comment]
It’s in int preview

**Comment by mitchdenny** [comment]
Then it should be in main too then right?

**Comment by balachir** [comment]
@mitchdenny yes, at the moment, int preview should give you the latest builds from vs/main branch

**Comment by balachir** [comment]
@JamesNK 

> It's probably allowing you because the cookie. 

Yes, there was a cookie saved in my Edge browser. Once I removed it, it prompts for the token again when I try to navigate to https://localhost:17021. That's good.

**Couple more questions** - 
1. If I go to my CLI and now create a second Aspire Starter app and run it with the dashboard bound to https://localhost:17005, that also works without asking for a token. Is that because the cookie is shared between all sites running under localhost? When I review the cookie data for localhost, Edge shows 'Send for' = `Secure same-site connections only` (see screenshot pasted below). i.e. both apps running at 'https://localhost:17021' and 'https://localhost:17005' belong to the same site. Correct?

2. You mentioned 'It is saved for 3 days (rolling expiry)'. But the Edge settings shows that the cookie is valid only until the browser session ends. Is that expected?

![image](https://github.com/dotnet/aspire/assets/8246794/69eb18e8-b11d-4dca-a52f-5dcb47b8ae36)

**Comment by JamesNK** [comment]
For expiry, see https://github.com/dotnet/aspire/pull/3654

**Comment by JamesNK** [comment]
Persistence fixed with https://github.com/dotnet/aspire/pull/3654

**Comment by balachir** [comment]
@JamesNK with this PR https://github.com/dotnet/aspire/pull/3754, this fix should now be in Aspire 8.0 P6, am I correct?
