### ISSUE TITLE
[WebToolsE2E][Aspire][Mac arm64]When running the Aspire application using http, after pasting the login token and clicking the "Log in" button in the pop-up Aspire dashboard, there is no response on safari browser.

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#3634]
**REGRESSION INFO:** This is a new feature on Aspire 8.0.0-preview.6.24210.28

**INSTALL STEPS**

1.Clean machine: Mac arm64
2.Install VS Code[1.88.0] and C#[2.26.9 main], C# Dev Kit[1.4.139 main]
3.Install SDK 8.0.204(latest-released-build)
4.Install Aspire 8.0 P6 workload version 8.0.0-preview.6.24210.28
5.Apply NuGet Feeds

**REPRO STEPS**

1.Open CMD, creating an Aspire App using following commands:
```
dotnet new aspire -o aspire1
cd aspire1
code .
```
2.Open launchSettings.json under Properties folder in xxx.AppHost, add below code:
`"ASPIRE_ALLOW_UNSECURED_TRANSPORT": "true"`
![image](https://github.com/dotnet/aspire/assets/88425944/1be367dd-c76d-48fd-bd0b-46932adb7d58)
3.Press 'Ctrl+shift+P' > Debug: Select and Start Debugging > C# > C#: xxx.AppHost[http]
4.Copy the login token from debug console:
![image](https://github.com/dotnet/aspire/assets/88425944/9d435dfc-f63b-4ac8-ad43-b3d469e3e382)
5.Paste the login token in the pop-up Aspire dashboard > click the "Log in" button. 

**ACTUAL:**
After pasting the login token and clicking the "Log in" button in the pop-up Aspire dashboard, there is no response.
![image](https://github.com/dotnet/aspire/assets/88425944/1ed9969c-8cf6-4bf0-a090-3c3ea1ebb83a)

**NOTE:**
1.Run aspire project with https or run 'dotnet watch', it works well.
2.This issue only repro on Mac arm64 with safari browser [version 17.4.1(19618.1.15.11.14)], I have attached an extension log.
[extensionTelemetry.log](https://github.com/dotnet/aspire/files/14953548/extensionTelemetry.log)
3.This issue not repro on Edge browser.
4.This issue not repro on Mac x64.

**EXPECTED**
The aspire dashboard page can log in normally and enter.

**Comment by JamesNK** [comment]
I can't repo with http + Chrome + windows. I don't have macOS to properly reproduce this.

**Comment by JamesNK** [comment]
What happens if you copy and paste the token plus URL into the browser and hit enter? Does that log you in?

**Comment by v-polly** [comment]
@JamesNK , I tried to paste the token plus URL, but it reminder me it's invalid token and cannot sign-in. 
![image](https://github.com/dotnet/aspire/assets/88425944/1ccfb7d9-49cf-449c-b279-bdf67ddffa06)

**Comment by JamesNK** [comment]
Put the full URL in the browser address box and hit enter. It should log you in and take you to the app. Clear cookies to log out again.

What is the browser console output when the Log in button is pressed with the correct token?

**Comment by v-polly** [comment]
@JamesNK When I Put the login **token** in the browser address box and hit enter, the console log in safari browser:
![image](https://github.com/dotnet/aspire/assets/88425944/e8852cc3-8c2c-4a14-8fc6-abf97eb19b14)
When I Put the **full URL plus login token** in the browser address box and hit enter, the console log in safari browser:
![image](https://github.com/dotnet/aspire/assets/88425944/79480eda-352e-48b3-8ca9-09a9fdf2b59e)

**Comment by balachir** [comment]
@v-polly couple of questions:
1. On macOS arm64, can you confirm whether this also reproduces when you do `dotnet run -lp http` using the CLI (i.e. the macOS Terminal)? If it works using the CLI and reproduces only when debugging using VS Code, we should open an issue in AzDO.
2. You mention that this issue reproduces with Safari and does not reproduce with Edge browser. What about Chrome browser?

**Comment by JamesNK** [comment]
> When I Put the full URL plus login token in the browser address box and hit enter, the console log in safari browser:

This is what I mean by browser address box:

![image](https://github.com/dotnet/aspire/assets/303201/381eece4-6f84-4b5b-a746-4236c540afe9)

Put the URL there and hit enter. Are you logged in and redirected to the dashboard? Or do you stay on the login page?

**Comment by v-polly** [comment]
@balachir @JamesNK , Verified this issue today with the latest aspire preview 6 [8.0.0-preview.6.24214.1], this issue is not reproduce on Mac arm64 (safari/edge/firefox/chorme all works well), so closed this issue.
