### ISSUE TITLE
[AzureTools][Aspire] The log time is displayed incompletely and ends with all 0s for a container running with Podman Desktop

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#3641]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10.0 Preview 4.0 [34811.107.d17.10]
**Aspire Version:** 8.0.0-preview.5.24201.12
Apply NuGet Feeds
**Podman Desktop:** 1.9.1
**Podman CLI:** 5.0.1

**REPRO STEPS:**

1. Create an Aspire starter project with "Use Redis for caching (requires Docker)" checked.
2. F5.
3. In the dashboard, click "View" under the "Logs" for the container.

**Expect:**
The log time is displayed completely.
![image](https://github.com/dotnet/aspire/assets/62053665/b919e468-944a-4c72-875d-5add24babf3d)

**Actual:**
The log time is displayed incompletely and ends with all 0s.
![image](https://github.com/dotnet/aspire/assets/62053665/9e592b34-d27a-494b-aa3e-9868bd6de40d)

**More Info:**
1. The log of the container shows in the Podman Desktop:
![image](https://github.com/dotnet/aspire/assets/62053665/7325a1ef-4a0d-4573-821a-550413e3ab95)
2. This issue doesn't reproduce for Docker Desktop 4.28.0 (139021).

**Comment by mitchdenny** [comment]
@karolz-ms are you injecting these timestamps or are you just taking something that podman is giving you?

**Comment by v-mengwe** [comment]
Verified on the 17.10.0 Preview 6.0 [34823.181.d17.10] with Aspire 8.0.0-preview.7.24223.12, this issue also reproduces for other samples:

1. "mysql" container of DatabaseContainers sample
2. "grafana", "prometheus" containers of MetricsApp sample
3. "basketcache" container of AspireShop sample
4. "voting-redis" container of OrleansVoting sample

**Comment by dbreshears** [comment]
Closing as this is external to podman,  we are just calling podman  logs -t <cid> which isn't giving millisecond resolution like docker does.  Couldn't find in the docs how to set more resolution.   

Podman
2024-04-26T20:49:26.Z
 
Docker 
2024-04-26T20:49:26.710470215
