### ISSUE TITLE
AddPostgres with postgis

### ISSUE THREAD

**Issue by romaluca** [dotnet/aspire#3644]
Hi, before Aspire i had a dockerfile for postgres:

`FROM postgres:15.4

RUN apt-get update && apt-get  install -y postgresql-15-postgis-3  

CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]`

Now i use `AddPostgres` in AppHost but i don't know how can i add postgresql postgis.
Can you help me?
Thanks

**Comment by mitchdenny** [comment]
Assuming you found the WithX methods where you can modify the image names, tags etc?
