### ISSUE TITLE
Azd init fails for demo project: "ERROR: configuring ingress for resource prometheus: binding "tcp" has scheme "tcp" but no container port"

### ISSUE THREAD

**Issue by g-martin772** [dotnet/aspire#3675]
I am using the demo project showcasing the Redis output cache and I get the following error when running `azd init`:
`ERROR: configuring ingress for resource redis: binding "tcp" has scheme "tcp" but no container port`

I also get a very similar error with every other container resource that has an endpoint, like this metrics example from the samples repo:
```cs
var prometheus = builder.AddContainer("prometheus", "prom/prometheus")
    .WithBindMount(GetFullPath("../prometheus"), "/etc/prometheus")
    .WithEndpoint(containerPort: 9090, hostPort: 9090);
```
`ERROR: configuring ingress for resource prometheus: binding "tcp" has scheme "tcp" but no container port`
Even though the container port is specified. 

Running the app locally and generating the manifest works fine and the manifest itself seems to be correct as well.

**Comment by davidfowl** [comment]
2 things first:
1. Upgrade to the latest preview of aspire (preview 5 came out this week) - https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5
1. Upgrade to the latest azd (https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-april-2024-release/)


We don't yet support deploying bind mounts to azure via azd. This app will only work locally (see https://github.com/Azure/azure-dev/issues/3706)

**Comment by g-martin772** [comment]
Thanks for the reply!
I am already on the latest version for both .NET SDK, workloads, and Azd.
I understand that BindMounts can't be deployed yet (I only added this example to have a second one).
However, the issue described above occurs with all container resources that have a TCP endpoint. (For example the builtin Redis component)
For HTTP endpoints it doesn't complain. I understand this is still all in preview but I figured why not report it because I didn't find any other mentions of this issue anywhere.

**Comment by davidfowl** [comment]
If you’re in the latest, containerPort was removed from the API. Can you share your project code and can you show the versions in the project file, workload version and and version?

**Comment by g-martin772** [comment]
azd version:
azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)

aspire workload:
aspire                     9.0.0-preview.3.24210.17/9.0.100-preview.1      SDK 9.0.100-preview.3, VS 17.10.34607.79

Code:
```cs
using MyProjectName.Aspire.AppHost;
var builder = DistributedApplication.CreateBuilder(args);
var redis = builder.AddRedis("redis");
builder.Build().Run();
```

csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0-preview.3.24210.17" />
        <PackageReference Include="Aspire.Hosting.Redis" Version="9.0.0-preview.3.24210.17" />
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.0.0-preview.3.24210.17" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.62.0" />
        <PackageReference Include="KubernetesClient" Version="13.0.26" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0-preview.3.24172.9" />
        <PackageReference Include="Polly" Version="8.3.1" />
    </ItemGroup>

</Project>
```

**Comment by davidfowl** [comment]
I think the 9.x version of aspire isn't updated to the preview 5 version. If you can, switch to the 8.x preview 5 version.

**Comment by g-martin772** [comment]
Since I can use all the features described in the preview 5 release notes I would think it is. Since I am also using other features from .NET 9 switching back to .NET 8 isn't an option for the project I am currently working on but I could try it to see if the "azd init" part works on the .NET 8 version.

**Comment by davidfowl** [comment]
The code in the sample is the one that throws an error on azd init?

**Comment by g-martin772** [comment]
I just created a new Aspire project using the starter application template, added the Aspire.Hosting.Redis package and added a `var redis = builder.AddRedis("redis");` to the Program.cs

When running azd init, I am prompted to select the detected aspire app and enter an environment name, after pressing enter I get the following error message: `ERROR: configuring ingress for resource redis: binding "tcp" has scheme "tcp" but no container port`

This happens with all container resources that expose TCP endpoints, the building redis component is just a simple example here.

**Comment by davidfowl** [comment]
Try 8.0 preview 5 and let me know if you see the same thing.

**Comment by g-martin772** [comment]
I was not able to reproduce this issue using 8.0, so it seams to be specific to 9.0

**Comment by davidfowl** [comment]
Closing this.
