### ISSUE TITLE
sample: disable catalog service OpenTelemetry.Instrumentation.EventCounters metrics

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#368]
For a reason that I can't find, the catalog service outputs `OpenTelemetry.Instrumentation.EventCounters` counters. As far as I can tell the OTEL configuration is the same between catalog service and other services yet `OpenTelemetry.Instrumentation.EventCounters` are displayed.

These are the old counters. We should disable `OpenTelemetry.Instrumentation.EventCounters` and prefer new metrics everywhere.

![image](https://github.com/dotnet/aspire/assets/303201/cc1ddcc7-e939-4064-8baa-41c178c6e056)

**Comment by JamesNK** [comment]
It’s because EF and SQL Server providers enable counters because they don’t have metrics

**Comment by joperezr** [comment]
@JamesNK do we still need to do something here? Seems like it hasn't been updated in a while.

**Comment by JamesNK** [comment]
No longer an issue because old event counters were removed - https://github.com/dotnet/aspire/pull/3110
