### ISSUE TITLE
[preview 5] WithDataVolume breaks application when published to Azure

### ISSUE THREAD

**Issue by mmacka** [dotnet/aspire#3685]
After upgrading to preview 5 and replacing `WithVolumeMount()` with `WithDataVolume()` application works locally but once `azd up`-ed database shows different errors in Log Stream from `Database "MyDatabase" does not exist` to various mounting and permissions error.

This is my db config in AppHost:
```
var postgres = builder
    .AddPostgres("postgres")
    .WithDataVolume()
    .AddDatabase("MyDatabase");
```
Issues happen even with completely new resource group and newly `azd init`-ialized.

Am I missing something in configuration?

**Comment by davidfowl** [comment]
This worked before because volumes were not expressed in the manifest nor were they deployed. We're still digging into why ACA + Postgres + azure backed volumes don't work. If you want to go back to preview 4 behavior, you can do this:

```C#
var pgServer = builder
    .AddPostgres("postgres");

if (builder.ExecutionContext.IsRunMode)
{
    pgServer.WithDataVolume();
}

var postgres = pgServer
    .AddDatabase("MyDatabase")
``

**Comment by mmacka** [comment]
Thank you David!. I am looking forward to next previews when this will work out of the box.

You guys did amazing work with Aspire. Really appreciated.

**Comment by joperezr** [comment]
@davidfowl will log an issue in aspire-docs repo to add info about this.

**Comment by joperezr** [comment]
Closing this as per @davidfowl
