### ISSUE TITLE
Add support for http OTLP endpoint in the dashboard

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3688]
Right now the dashboard supports the grpc OTLP endpoint, we could support http as well but it's unclear how much demand or need there is for it. Filing this issue so others can upvote.

**Comment by JamesNK** [comment]
Work involved:

* Add new endpoint for OTLP http. See https://opentelemetry.io/docs/specs/otlp/#otlphttp-default-port. HTTP protocol will be Http1AndHttp2 (default's to HTTP/1.1 when there isn't TLS).
* Protobuf over HTTP. Existing Protobuf data over HTTP instead of gRPC.
* JSON over HTTP. New JSON DTOs plus mapping data.

**Comment by kvenkatrajan** [comment]
@davidfowl / @JamesNK  this is for post GA correct?

**Comment by davidfowl** [comment]
Correct. This can stay in the backlog

**Comment by JamesNK** [comment]
Related: Documentation to make it clear only OTLP/grpc is supported: https://github.com/dotnet/docs-aspire/pull/678

**Comment by thangchung** [comment]
+1 for this feature

**Comment by ThomasPiskol** [comment]
Support for http is required in case you want to use OTLP from the browser. Currently the OTLP SDK doesn't support gRPC from the browser:

![image](https://github.com/dotnet/aspire/assets/38790465/5db62c27-9607-417c-a1ea-bb58544170aa)


https://opentelemetry.io/docs/languages/js/exporters/#usage-in-the-browser

**Comment by leslierichardson95** [comment]
Keeping this in the backlog because it's needed for non-Aspire services.

**Comment by pksorensen** [comment]
Nor AzureMonitorTraceExporter or OTLPTraceExporter works in the browser, so its a bit of sad face when using some hours getting into otel and finally getting things up and running, then to realize there is no real path atm to export from browser frontend :D Would be cool to have this implementet so we can use http protocol, or alternative fix those exports to use grpc :)

**Comment by martinjt** [comment]
For those wanting this, especially those looking at it from a Browser perspective. In production, you'll be using the collector as an entrypoint for browser based telemetry from a security perspective etc.

I built a library that should allow you to do this right now by adding an Otel Collector to aspire.

https://www.nuget.org/packages/PracticalOtel.OtelCollector.Aspire/0.9.3-rc

**Comment by davidfowl** [comment]
@sharpSteff sent a PR!

**Comment by JamesNK** [comment]
Merged! https://github.com/dotnet/aspire/pull/4197

The dashboard supports OTLP/HTTP with Protobuf as the payload. It currently doesn't support JSON payloads, which is more difficult.

I'm going to close this as done. If there is feedback that JSON support is important then we can revisit it.

**Comment by davidfowl** [comment]
@JamesNK can you file the JSON issue with as much detail as possible. Contributors can take it on if it’s clear what need a to happen.
