### ISSUE TITLE
[WebToolsE2E][Aspire] Adding Aspire.Azure.Messaging.ServiceBus component and related codes to the solution, F5 running shows 'Missing subscription configuration' under the console logs of ServicesBus

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#3696]
**REGRESSION INFO**: Also repro on Aspire 8.0 preview 5

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 4.0 [34814.37.d17.10] includes Aspire 8.0 P6 [8.0.0-preview.6.24214.1]
3. Apply dotnet-tools Feed
4. Install docker desktop

**REPRO STEPS**
1. Create an ASP.NET Core Web API > Enter a Project name of AspireSerBus01 > .NET 8.0 > check 'Enlist in Aspire Orcheatration' > Create.
2. Open appsettings.json of AppHost project, add following codes:
```
	"ConnectionStrings": { 
	  "[ServiceBusName]": "Endpoint=sb://[ServiceBusName].servicebus.windows.net/;SharedAccessKeyName=AspireTest;SharedAccessKey=xxx" 
	}, 
```
3. In your AppHost project, install the Aspire.Hosting.Azure.ServiceBus library
4. Open Program.cs of AspireSerBus01.AppHost project, add following code:
```
var serviceBus = builder.AddAzureServiceBus("[ServiceBusName]");
var myService = builder.AddProject<Projects.MyService>()
                       .WithReference(serviceBus);
```
6. Right-click the AspireSerBus01 > add > .NET Aspire Package > install Aspire.Azure.Messaging.ServiceBus with matched version
7. Open Program.cs of AspireSerBus01 project, add following code:
```
using Azure.Messaging.ServiceBus;

builder.AddAzureServiceBusClient("sb");

app.MapPost("/notify", static async (ServiceBusClient client, string message) =>
{
	 var sender = client.CreateSender("[ExactTopicName]");
	
	 // Create a batch
	 using ServiceBusMessageBatch messageBatch =
	 await sender.CreateMessageBatchAsync();
	
	  if (messageBatch.TryAddMessage(
	    new ServiceBusMessage($"Message {message}")) is false)
	  {
	        // If it's too large for the batch.
	        throw new Exception(
	            $"The message {message} is too large to fit in the batch.");
	   }
	
	   // Use the producer client to send the batch of
	   // messages to the Service Bus topic.
	   await sender.SendMessagesAsync(messageBatch);
	
	   Console.WriteLine($"A message has been published to the topic.");
});
```

8. Build and F5

**ACTUAL**
It shows 'Missing subscription configuration' under the console logs of Services bus
 Resource could not be provisioned because Azure subscription , location, and resource group information is mising...
![image](https://github.com/dotnet/aspire/assets/82028229/1475b517-8144-4d72-9c3a-632167a16231)

**Note**

1. After selecting the app host project, right-click on the Connected Services node, and select Azure Resource Provisioning Settings and also sign in the VS, then build and F5 again will shows another error"

Failed to provision:
Using Azure resources during local development requires the installation of the Azure CLI. See https://aka.ms/dotnet/aspire/azcli for instructions.
![image](https://github.com/dotnet/aspire/assets/82028229/c26d5bb3-b650-4284-8c8c-b811107a651b)

2. After installed Azure CLI, then click the endpoints link of project, excute a message under '/notify', it will show exception:
![image](https://github.com/dotnet/aspire/assets/82028229/103718db-5cf8-4477-9775-a97c8d1d8d3a)
System.UnauthorizedAccessException: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://aspserbuswkg5elfz3cb5s.servicebus.windows.net/mytopic'. TrackingId: SystemTracker:gateway7, Timestamp: For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot. at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose) at Azure.Messaging.ServiceBus.Amqp.AmqpSender.CreateMessageBatchAsync(CreateMessageBatchOptions options, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.ServiceBusSender.CreateMessageBatchAsync(CreateMessageBatchOptions options, CancellationToken cancellationToken) at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in C:\Users\v-cazhang\source\repos\AspireSerBus01\AspireSerBus01\Program.cs:line 24 --- End of stack trace from previous location --- at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) HEADERS ======= Accept: */* Host: localhost:7080 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0 Accept-Encoding: gzip, deflate, br, zstd Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7 Cookie: .AspNetCore.Antiforgery._uA1z2T2JAg=CfDJ8KFno1aB6f5Dtz0CRwkOiGC1LWhAnjS6ZpbzRu2ks02VtcPOXYzPSIv64HzqN7zGlhrFyTV4EeyxrNG6LD1PIchbfjhDBnGIVkZxUtPAgNHPbMcjGiGbj6RSqvcD9CP3eaCBeUWUZ_Z2v0O9Qr0I0Gk; .AspNetCore.Cookies=CfDJ8KFno1aB6f5Dtz0CRwkOiGD2227m3J3-9RLqpKlLlaoASdVloOz607by81yEfWcgQ2QVqHvXwBBZ9ihkra7TQpLCc-17U2wi31FzlposFAGs7MA380mVKZNMVCNXUWUiT2gfzfWJYw0Jyudk1QP-Kr0UO2515IdXd6pBF5O_fZ5u8C0b9-wlcCUOLOGVx4ymZ7RNvz1-DZrdBBPZXlR73elYN4TnO_TAIof1HVtsz9zFg1-3c3itedrBNbxOWhhowx9-Wzpz9lDOIgbWlpUMmRBYchHTtmvQk82xohQLwQAa0SnJt2wNX7tCCMrTiEKRxL42gWAYFDB3Jt-Ef0tSFj_ub5FMLbLCoTEjsOQ0SRBLMaJrfxruEpUpcKpBwUf6OkejPgS7GuRO-heAX4GNEa6DO39XuoC735os7us330Cd Origin: https://localhost:7080 Referer: https://localhost:7080/swagger/index.html Content-Length: 0 sec-ch-ua: "Microsoft Edge";v="123", "Not:A-Brand";v="8", "Chromium";v="123" sec-ch-ua-mobile: ?0 sec-ch-ua-platform: "Windows" sec-fetch-site: same-origin sec-fetch-mode: cors sec-fetch-dest: empty

**EXPECTED**
No error and can send a test message
![image](https://github.com/dotnet/aspire/assets/82028229/e62f3638-ceeb-4416-a696-7eea42c44e32)

**Comment by davidfowl** [comment]
Step 2 should be removed from the repro. There are 2 different scenarios:

1. Testing local azure provisioning https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/local-provisioning
2. Using an existing azure resource (see https://learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-component?tabs=dotnet-cli#app-host-usage)

For number 2, the only call in the apphost (if any is AddConnectionString). 

Which scenario is being tested?

**Comment by v-cazhang** [comment]
Hi @davidfowl, thanks for your explanation. I tested with `Using an existing azure resource` .

I tried again with following steps:

1. Commented out the connection string from appsettings.json of AppHost project:

![image](https://github.com/dotnet/aspire/assets/82028229/ba58d4af-47a9-49f1-85e4-990298342bc8)

2. Then add the codes from the https://learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-component?tabs=dotnet-cli#app-host-usage:

![image](https://github.com/dotnet/aspire/assets/82028229/6d5685f4-0f40-4d29-a8a5-c8a21479480a)

3. Update the program.cs of API project.

![image](https://github.com/dotnet/aspire/assets/82028229/132c9958-63d6-4e70-953b-47480ffad60f)

**Results**: F5 shows 'Connection string parameter resource could not be used because connection string 'xxx' is missing.'
![image](https://github.com/dotnet/aspire/assets/82028229/90ef4dd9-9b95-44cc-83e9-3ebf86b07d1d)


**Note**: I added the connection string back to the appsettings.json file, then F5 again, project can start successfully, but when I tried to execute a test message, it shows 'System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Azure.Messaging.ServiceBus.ServiceBusClient' '
![image](https://github.com/dotnet/aspire/assets/82028229/967d59dd-c41a-42f7-bce8-cc79f7dbe9dd)

**Comment by davidfowl** [comment]
> Note: I added the connection string back to the appsettings.json file, then F5 again, project can start successfully, but when I tried to execute a test message, it shows 'System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Azure.Messaging.ServiceBus.ServiceBusClient' '

Why did you remove the call to `AddServiceBusClient`? That's still required.

**Comment by v-cazhang** [comment]
> > Note: I added the connection string back to the appsettings.json file, then F5 again, project can start successfully, but when I tried to execute a test message, it shows 'System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Azure.Messaging.ServiceBus.ServiceBusClient' '
> 
> Why did you remove the call to `AddServiceBusClient`? That's still required.

Oh, yes, thanks for your help, the project can work fine now after I added connection string to appsettings.json and updated `AddServiceBusClient` the program.cs of web project:
![image](https://github.com/dotnet/aspire/assets/82028229/71896ae3-0c0a-4eba-a7d8-481dc70ea016)

If don't apply connection steing to the appsettings.json, it will show error like below:
![image](https://github.com/dotnet/aspire/assets/82028229/da146439-74d1-4c87-802f-e76946cd7914)


One more question here. the [README ](https://github.com/dotnet/aspire/tree/main/src/Components/Aspire.Azure.Messaging.ServiceBus)file doesn't contain the new `App host usage` contents, does the README file need to be updated? 
![image](https://github.com/dotnet/aspire/assets/82028229/e07e1aac-62b2-4b40-aef5-5f42b948d466)

**Comment by PaybackMan** [comment]
Same issue here.

**Comment by davidfowl** [comment]
What issue is that?

**Comment by dzejsien** [comment]
@davidfowl I understood, when azure resource already exists, we can only attach it by 
.AddConnectionString().

The issue, which I can see, is that after it, I don't see it as a service bus resource in the dashboard, which makes this operation useless. 

So I back to usage of .AddAzureServiceBus()

To handle that, I went to user-secrets, and I've changed the entry and indicated my existing service bus resource. It works. Nevertheless, I think such option should be possible via fluent code.

I have other question, 
I have an api, which is attached to the Aspire app, but it uses "not aspire" service bus client. I'm wondering why I don't see traces for the handling of messages - does the calling of AddServiceBusClient() obligatory? If yes, why? I thought that Azure.Messaging.ServiceBus is already integrated with OTEL. Please share, what is missing if we don't want to couple the API with aspire (ofc ServiceDefaults is added in default implementation to the api)?

Thanks for clarifications.

**Comment by dzejsien** [comment]
I've added to ServiceDefaults

![image](https://github.com/dotnet/aspire/assets/5199166/6c4c0088-0506-4283-871b-3ba6a35677a6)

but still I don't see consumption of the messages in traces.

**Comment by davidfowl** [comment]
> The issue, which I can see, is that after it, I don't see it as a service bus resource in the dashboard, which makes this operation useless.

Using an external resource means you have already done the work to provision and you just want specify the value in configuration. We don't show connection string resources or parameters in the dashboard by default. Also when you go to deploy, the tool will ask you for a value for that connection string.

> I have an api, which is attached to the Aspire app, but it uses "not aspire" service bus client. I'm wondering why I don't see traces for the handling of messages - does the calling of AddServiceBusClient() obligatory? If yes, why? I thought that Azure.Messaging.ServiceBus is already integrated with OTEL. Please share, what is missing if we don't want to couple the API with aspire (ofc ServiceDefaults is added in default implementation to the api)?

That's the purpose of aspire components, to turn on the things that the underlying SDK doesn't turn on or do by default. The Azure sdk's service bus tracing support is still experimental:

https://github.com/dotnet/aspire/blob/40a1675a45c2c86e82e3829801f114ce339047cf/src/Components/Aspire.Azure.Messaging.ServiceBus/AzureMessagingServiceBusSettings.cs#L66-L80

If you set either of these it should work.

**Comment by eerhardt** [comment]
This issue is stale and I can't really make out exactly what speciifc problem this issue is talking about. Closing.

If there still is an issue that needs to be addressed, feel free to reopen it and add a clear description of the issue.
