### ISSUE TITLE
Add Functional tests for Seq Integration

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#3705]
We don't have any end-to-end coverage for the Seq integration in our tests

We should add functional and unit tests for the Aspire.Hosting.Seq library. For an example functional test, see:

https://github.com/dotnet/aspire/blob/9d504bf4ed75cb007dabee259dbd6e666ee861fe/tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs#L17-L51

@liammclennan @nblumhardt

**Comment by radical** [comment]
@eerhardt can we close this as we are not adding new `EndToEnd` tests?

**Comment by eerhardt** [comment]
It looks like Aspire.Hosting.Seq doesn't have any tests. I updated this issue to track adding functional tests to it.

**Comment by radical** [comment]
> It looks like Aspire.Hosting.Seq doesn't have any tests. I updated this issue to track adding functional tests to it.

Yeah, only the playground test.

**Comment by radical** [comment]
Closing this in favor of the tracking issue - https://github.com/dotnet/aspire/issues/4741 .
