### ISSUE TITLE
How to make connection work locally and in Azure

### ISSUE THREAD

**Issue by mmacka** [dotnet/aspire#3718]
I am trying to use postgres in container locally and to connect to Azure Database for PostgreSQL -Flexible server when deployed but I can't seem to make it work with connection strings.

If I add connection string in appsettings.json and use it in the main app without any mention in AppHost like this, it works in local and in Azure.
```csharp
builder.AddNpgsqlDbContext<AppDbContext>(
    "my-db",
    null,
    contextOptions =>
    {
        contextOptions.UseSnakeCaseNamingConvention();
    }
);
```

However, since I fell in love with Aspire, I was trying to to achieve appsettings.json without connection string (AppHost):
```
var pgServer = builder
    .AddPostgres("postgres")
    .PublishAsConnectionString()
    .WithPgAdmin()
    .AddDatabase("my-db");
```
It properly asks for connection string during provisioning/deployment, but it breaks container app after deployment. It refuses to start.

Then I tried:
`var postgres = builder.AddConnectionString("my-db");` with connection string in appsettings.Development.json, but then local app fails to start complaining that resource is not running.

Connection in appsettings.Development.json:
```
    "ConnectionStrings": {
        "my-db": "Server=localhost;Database=my-db;Port=5432;User Id=postgres;Password=postgres;"
    }
```

How to reconcile local and Azure with any of the 2 approaches (local db in container or not and published version connecting to Azure PostgreSQL flexible server)?

**Comment by davidfowl** [comment]
> but it breaks container app after deployment. It refuses to start.

Do you have the error?

> Then I tried:
var postgres = builder.AddConnectionString("my-db"); with connection string in appsettings.Development.json, but then local app fails to start complaining that resource is not running.

In the appsettings of the AppHost project?

> How to reconcile local and Azure with any of the 2 approaches (local db in container or not and published version connecting to Azure PostgreSQL flexible server)?

```C#
var pgServer = builder
    .AddPostgres("postgres")
    .PublishAsConnectionString()
    .WithPgAdmin()
    .AddDatabase("my-db");
```

This looks right, provided that you've provisioned the postgres on azure already and have configured the auth to work with your container app.

**Comment by papaja** [comment]
Sorry David, my bad. Apparently I misconfigured something. Now when I did it again `PublishAsConnectionString()` works.

**Comment by mmacka** [comment]
Sorry David, my bad. Now I tried to do it again and `PublishAsConnectionString()` works as expected.
