### ISSUE TITLE
[AzureTools][Aspire] An error message flashes and disappears when entering any letter or number or token in the input box for the first time and then pressing the keyboard "Enter" key

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#3719]
**Clean machine**: Win11 x64 23h2 ENU
**VS Version**: VS 17.10.0 Preview 4.0 [34814.37.d17.10]
**Aspire Version:** 8.0.0-preview.6.24214.1 
Apply NuGet Feeds
**Podman Desktop:** 1.9.1
**Podman CLI:** 5.0.1

**REPRO STEPS:**
1. Create an Aspire starter project with "Use Redis for caching (requires Docker)" checked.
2. F5.
3. In the pop-up browser -> Enter any letter or number or token in the input box for the first time -> Press the keyboard "Enter" key.

**Expect:**
The error message pops up directly below the input box.
![image](https://github.com/dotnet/aspire/assets/62053665/3c503628-2468-49d1-a2a6-c8f003603814)

**Actual:**
An error message flashes and disappears. (I'm sorry it's flickering so fast that the video and gif can't be captured.)
![Actu](https://github.com/dotnet/aspire/assets/62053665/b40d7188-7d09-4aff-a961-dd44d1d7d70f)

**More Info:**
1. Pressing the "Enter" key directly on the keyboard when the input box is empty does not reproduce the problem.
    ![image](https://github.com/dotnet/aspire/assets/62053665/494d4596-8630-4e80-abcc-6d57e039678e)
2. The error message pops up after pressing the "Enter" key again.

**Comment by tlmii** [comment]
This appears to have been fixed with #3743
