### ISSUE TITLE
"Microsoft.Extensions.ServiceDiscovery" Version="9.0.0-preview.3.24210.17" BUG

### ISSUE THREAD

**Issue by PaperHammer** [dotnet/aspire#3721]
When I use that version of service discovery in the ASP.NET Core Web API, I run "var app = builder.build();" This line of code， an error has occourred:
"System.MissingMethodException: Method not found: 'System.TimeSpan System.TimeSpan.FromSeconds(Int64)'. at Microsoft.Extensions.Http.DefaultHttpClientFactory..ctor..."
Earlier versions will not

当我在 ASP.NET Core Web API 中使用该版本的服务发现时，在执行“var app = builder.build（）;”这行代码时报错：
"System.MissingMethodException: Method not found: 'System.TimeSpan System.TimeSpan.FromSeconds(Int64)'. at Microsoft.Extensions.Http.DefaultHttpClientFactory..ctor..."
早期版本不会

**Comment by dominik246** [comment]
Install latest [dotnet 9 sdk](https://dotnet.microsoft.com/en-us/download/dotnet/9.0)
Then if needed do `dotnet workload update` in terminal.
This fixed the issue for me.

**Comment by PaperHammer** [comment]
It works! Install latest version. Thank you for your solution! But the official 9.0.0 version of this package is no longer available on the Nuget server, and the use needs to be installed through the command line, only the 8.0.0 version, I don't know why

**Comment by davidfowl** [comment]
We unlisted the 9.0 versions
