### ISSUE TITLE
[AzureTools][Aspire] Two error messages "Token required" and "Invalid token. Please try again" are both below the input box when using any number or letter login first and then using the empty press the enter key

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#3722]
**Clean machine**: Win11 x64 23h2 ENU
**VS Version**: VS 17.10.0 Preview 4.0 [34814.37.d17.10]
**Aspire Version:** 8.0.0-preview.6.24214.1 
Apply NuGet Feeds
**Podman Desktop:** 1.9.1
**Podman CLI:** 5.0.1

**REPRO STEPS:**
1. Create an Aspire starter project with "Use Redis for caching (requires Docker)" checked.
2. F5.
3. In the pop-up browser -> Enter any letter or number in the input box -> Click "Log in" button -> Pop up an error **"Invalid token. Please try again**" below the input box.
4. Delete all letters or numbers in the input box -> Press the keyboard "Enter" key.

**Expect:**
Only one error message "Token is required" below the input box.
![image](https://github.com/dotnet/aspire/assets/62053665/ae6124e1-53a6-4aba-9e61-88837634ba6b)

**Actual:**
Two error messages "Token required" and "Invalid token. Please try again" are both below the input box.
![image](https://github.com/dotnet/aspire/assets/62053665/526ab965-b65b-4558-b1ac-b5c54aba9163)

**More Info:**
1. This issue **doesn't reproduce** when clicking on "Log in" button in step 4 instead of pressing "Enter" key on the keyboard.
2. This issue **doesn't reproduce** when using the empty login first and then using any number or letter press the enter key.

**Comment by leslierichardson95** [comment]
@danmoseley would this issue meet the GA bar?

**Comment by tlmii** [comment]
This appears to have been fixed with #3743
