### ISSUE TITLE
Incorrect `WithEnvironment` generic constraint?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#3723]
https://github.com/dotnet/aspire/blob/3a601cb87276f0d5401bdcbb5a84a151cf6d5de8/src/Aspire.Hosting/ResourceBuilderExtensions.cs#L25

Should the constraint here be `IResourceWithEnvironment`? All the other `WithEnvironment` overloads use that constraint.

**Comment by davidfowl** [comment]
cc @mitchdenny
