### ISSUE TITLE
Extend `dotnet run` to work from the root folder of a solution with an AppHost

### ISSUE THREAD

**Issue by onionhammer** [dotnet/aspire#3724]
It would be cool to not have to specify the AppHost project if there is an AppHost present in the solution within the folder you're in

Today:

```
> ls
YourSolution.sln
/src
> dotnet run
Couldn't find a project to run. Ensure a project exists in ..., or pass the path to the project using --project.
```

Proposal:
Instead of erroring, see if there's a project with `IsAspireHost` true, and run that.

**Comment by davidfowl** [comment]
Seems like a far future SDK request. I'm not sure how practical this is.

cc @baronfel

**Comment by joperezr** [comment]
Closing this per the above, as this is probably a feature on the SDK itself and there isn't something we can do in this repo to help facilitate this. @onionhammer please let us know if you think otherwise.
