### ISSUE TITLE
[Preview 6] - Dapr sidecar doesn't start

### ISSUE THREAD

**Issue by ngruson** [dotnet/aspire#3726]
I've using the latest preview 6 bits to work around https://github.com/dotnet/aspire/issues/3435.
My Dapr sidecar won't start anymore.

This is what the dashboard shows:
![image](https://github.com/dotnet/aspire/assets/3188323/70d5f29b-19d5-4c1c-ac53-3cd40b2e0918)
No further logs or details are to be seen in the dashboard.
No exceptions in VS either.

I have a Blazor app enlisted with Aspire:
```csharp
builder.AddProject<Projects.UI_Blazor>("frontend")
    .WithReference(identityServer)
    .WithReference(api)
    .WithDaprSidecar(new DaprSidecarOptions
    {
        AppId = "frontendDapr",
        AppPort = 5001,
        ResourcesPaths = ImmutableHashSet.Create("./components"),
        LogLevel = "debug"
    })
    .WithEnvironment("IdentityServer__Authority", identityServer.GetEndpoint("https"));
```

The Blazor app starts, but the sidecar won't.
Do I need to modify the passed-in `DaprSidecarOptions` in some way?

[EDIT]
I do see this output in Visual Studio:
```
The gRPC server for Durable Task gRPC worker is unavailable. Will continue retrying.
```
[/EDIT]

**Comment by karolz-ms** [comment]
Without a specific repro it is hard to tell what might be broken here.

I tried the following with the [Aspire dapr playground sample](https://github.com/dotnet/aspire/tree/main/playground/dapr)

1. Open `DaprAppHost/Program.cs`
2. Change the part that sets up `servicea` to

```csharp
builder.AddProject<Projects.DaprServiceA>("servicea")
       .WithDaprSidecar(new DaprSidecarOptions
       {
           AppId = "servicea",
           AppPort = 7077,
           LogLevel = "debug"
       })
       .WithReference(stateStore)
       .WithReference(pubSub);
```
(the port 7077 is what the `servicea` `https` project launch profile prescribes)

3. Make sure `DaprAppHost` is set as startup project, and that `https` launch profile is set, then F5

Result: works

**Comment by ngruson** [comment]
My Aspire packages in the AppHost where on version `8.0.0-preview.6.24178.5`.
I now updated to the latest package versions `8.1.0-preview.1.24217.12` which solves the problem.
Now I don't see any resources with a unknown status and everything is started correctly.
