### ISSUE TITLE
[Auth Integration Testing] Validate OIDC integration for dashboard frontend authentication and authorization

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#3730]
Create integration tests to validate the following : 

- [ ] User can authenticate using oidc configuration
- [ ] User is authorized via required claim logic
- [ ] User name is available for display in profile via the user configuration

**Comment by kvenkatrajan** [comment]
@drewnoakes  please confirm if this can be closed with PR : https://github.com/dotnet/aspire/pull/3692

**Comment by drewnoakes** [comment]
Fixed in #3692
