### ISSUE TITLE
[Auth Integration Testing] Validate dashboard configuration to support ResourceService auth 

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#3733]
Add integration test coverage for : 
- [ ] Dashboard:ResourceServiceClient:AuthMode is required if URL configured
- [ ] Dashboard:ResourceServiceClient:ApiKey is required required auth mode is API key
- [ ] Dashboard:ResourceServiceClient:ClientCertificate:* is required if auth mode is certificate
- [ ] Validate certificate errors incase invalid cert is provided

**Comment by kvenkatrajan** [comment]
@drewnoakes can you confirm if this : https://github.com/dotnet/aspire/pull/3824 covers all the scenarios above and can be closed?

**Comment by drewnoakes** [comment]
#3824 tested the use of auth, not the validation of configuration. Testing of option validation is in #4620.
