### ISSUE TITLE
Issue when trying to run Aspire starter template

### ISSUE THREAD

**Issue by islamkhattab** [dotnet/aspire#3738]
**Environment**

- **OS:** Windows 10 Enterprise
- **Visual Studio:** 2022 64-bit Version 17.10.0 Preview 4.0
- **Aspire:** 8.0.0-preview.5.24201.12
- **dotnet:** 8.0.300-preview.24203.14

**Repro Steps**
[Quickstart: Build your first .NET Aspire app](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?tabs=visual-studio)

**Error**
When trying to start the app host
```
Microsoft.Extensions.Hosting.Internal.Host: Error: Hosting failed to start

System.InvalidOperationException: Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.5.24201.12\tools\dcp.exe info returned non-zero exit code -1
   at Aspire.Hosting.Dcp.Process.ProcessUtil.ProcessDisposable.DisposeAsync() in /_/src/Aspire.Hosting/Dcp/Process/ProcessUtil.cs:line 155
   at Aspire.Hosting.Dcp.DcpDependencyCheck.GetDcpInfoAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs:line 115
   at Aspire.Hosting.Dcp.DcpHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Aspire.Hosting/Dcp/DcpHostService.cs:line 67
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
The thread '[Thread Destroyed]' (31464) has exited with code 0 (0x0).
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll
One or more errors occurred.
```

**dcp info**
```
C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.5.24201.12\tools>dcp.exe info
```

```
{
  "version": "0.1.62",
  "commitHash": "7f2cb7dea2784573bc2f273ebe07768ea016fb18",
  "buildTimestamp": null,
  "containers": {
    "runtime": "docker",
    "hostName": "host.docker.internal",
    "installed": true,
    "running": false,
    "error": "context deadline exceeded"
  }
}
```

**Comment by islamkhattab** [comment]
Not sure if this is related to #3435 or it is irrelevant

**Comment by davidfowl** [comment]
Can you show all of the console output?

**Comment by davidfowl** [comment]
@karolz-ms ?

**Comment by islamkhattab** [comment]
@davidfowl When I tried to run the app today it worked to get out the output logs, it worked fine without any issues 👀, No changes in the neither the code or the env, below is the onl difference in dcp info, will close the issue for now and report back if the issue surfaced again

![image](https://github.com/dotnet/aspire/assets/3328233/df85d1b7-7a7d-4d84-aad4-895806496ae9)

**Comment by karolz-ms** [comment]
Glad it is working now. Looks like Docker was in a bad state, but then recovered.

I will open an issue to have the DCP error message be more informative than "context deadline exceeded". Thank you for the bug report @islamkhattab , this is quite helpful.
