### ISSUE TITLE
[Auth Integration Testing] Validate Dashboard-resource client

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#3739]
Validate transport
- [x] http support 
- [x] https 

Validate auth
- [x] Unsecured
- [x] API Key
- [ ] Client certificate

**Comment by radical** [comment]
Is the intention here to have automated tests running on CI? Is there anything needed from the testing infrastructure side for this which is missing right now?

**Comment by kvenkatrajan** [comment]
@drewnoakes  please confirm if these are covered

**Comment by drewnoakes** [comment]
https://github.com/dotnet/aspire/pull/3824 added tests for `Unsecured` and `ApiKey` auth modes over HTTP.

https://github.com/dotnet/aspire/pull/4621 adds HTTPS coverage.

We don't have any client cert tests currently. There's just a thin layer of code to load the certs, after which point it's all framework code. Setting up certs in automated integration tests seems a bit fiddly and might not run on Linux without considerable investment. I'm not certain it's worth adding these tests.

**Comment by kvenkatrajan** [comment]
@radical have we solved for certs for automated integration tests infra in linux?

**Comment by radical** [comment]
We install dev certs for test on linux using https://github.com/BorisWilhelms/create-dotnet-devcert on both Helix, and the build machine. The latter was added yesterday.

**Comment by kvenkatrajan** [comment]
Thanks

@drewnoakes please add a new issue tracking client certificate tests and for the 8.2 milestone and we can close this one.

**Comment by drewnoakes** [comment]
Thanks @radical. That's great timing :)
