### ISSUE TITLE
Set HTTP/HTTPS_PORTS on projects in publish mode by default

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3749]
Today if you define multiple endpoints on a project resource, none will be bound to ASPNETCORE_URLs in publish mode. We're currently relying on the base container image to do this. This causes a difference in behavior in run mode vs publish mode that creates confusion.

**Comment by DamianEdwards** [comment]
@davidebbo yes, number 3 is what I had in mind too. I hit this issue when building out a sample (which reminds me I still need to merge it) and had to workaround this: https://github.com/dotnet/aspire-samples/blob/14a2127f6bbf4904ba0acf66e228c7fff6085639/samples/HealthChecksUI/HealthChecksUI.AppHost/HealthChecksUIResource.cs#L119-L133

The HTTPS question is a good one and I think the answer is simply that it's up to the publish tool to decide how to map the endpoints to the destination configuration based on its knowledge of how things like ingress work there, e.g. AZD maps additional HTTP endpoints as additional ingress TCP ports as ACA only supports a single HTTP and HTTPS port for ingress. That logic would need to be updated to coordinate with the `HTTP_PORTS` / `HTTPS_PORTS` environment variables in the manifest.

**Comment by davidebbo** [comment]
Thanks @DamianEdwards, it's quite helpful to have your code to illustrate what's needed.

In terms of doing things for number 3 (WithHttpEndpoint) and not number 2 (profile), it seems we're already doing this backwards today for manifest bindings. i.e. if you have profile bindings, you end up with manifest bindings:

```json
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http"
        },
        "https": {
          "scheme": "https",
          "protocol": "tcp",
          "transport": "http"
        }
      }
```

But if you don't have a profile, and instead use `WithHttpEndpoint`, then you don't get manifest bindings, which seems wrong.

Maybe part of the problem is that the logic that adds the bindings happens in `AddProject`, and by that time the calls to `WithHttpEndpoint` haven't happened yet, e.g.:

```c#
builder.AddProject<Projects.AspireApp2_Web>("webfrontend")
    .WithHttpEndpoint(5002, name: "http")
    .WithHttpsEndpoint(5003, name: "https")
```

**Comment by davidebbo** [comment]
I'm also confused about why we want to set `HTTP/HTTPS_PORTS` at publish time (manifest), but we instead set `ASPNETCORE_URLS` at runtime. Why can't we do the same in both cases? It ends up in Kestrel either way, either directly (Run mode), or indirectly (Publish).

One other inconsistency: if you define endpoints using `.WithHttpEndpoint()`, your port makes it to the manifest in the binding. But if it comes from the profile, we omit the port. Why?

And one more: we have logic that checks for http2 in Kestrel: `config["Kestrel:EndpointDefaults:Protocols"] == "Http2"`. In that case, we set the binding transport to http2, but **only if the binding comes from the profile**. If it comes from `.WithHttpEndpoint()`, we don't do that. Doesn't that feel arbitrary?

**Comment by DamianEdwards** [comment]
> I'm also confused about why we want to set HTTP/HTTPS_PORTS at publish time (manifest), but we instead set ASPNETCORE_URLS at runtime. Why can't we do the same in both cases? It ends up in Kestrel either way, either directly (Run mode), or indirectly (Publish).

I believe it's because the ASP.NET Core container images specify HTTP_PORT and it wins over URLS. @davidfowl?

> One other inconsistency: if you define endpoints using .WithHttpEndpoint(), your port makes it to the manifest in the binding. But if it comes from the profile, we omit the port. Why?

Launch profiles are strictly for local dev scenarios only, so nothing from the launch profile makes it into the manifest.

> And one more: we have logic that checks for http2 in Kestrel: config["Kestrel:EndpointDefaults:Protocols"] == "Http2". In that case, we set the binding transport to http2, but only if the binding comes from the profile. If it comes from .WithHttpEndpoint(), we don't do that. Doesn't that feel arbitrary?

Yes agreed. Seems we should check this in both cases.

**Comment by davidebbo** [comment]
> I believe it's because the ASP.NET Core container images specify HTTP_PORT and it wins over URLS. @davidfowl?

Right, that's what I discussed with @davidfowl (to be precise, it sets `ASPNETCORE_HTTP_PORTS=8080`). But the question is then: why not set `HTTP/HTTPS_PORTS` for runtime as well? Maybe the one drawback is that this would lose any host names. And maybe we care about host names at runtime, but we're ok to ignore them at deploy time, when it ends up running in a container.

> Launch profiles are strictly for local dev scenarios only, so nothing from the launch profile makes it into the manifest.

Yes, that's what I would expect, but it's not quite the case today, as per my earlier comment. The presence of endpoints in the launch profile results in the addition of the (port-less) bindings in manifest.

**Comment by davidfowl** [comment]
> I'm also confused about why we want to set HTTP/HTTPS_PORTS at publish time (manifest), but we instead set ASPNETCORE_URLS at runtime. Why can't we do the same in both cases? It ends up in Kestrel either way, either directly (Run mode), or indirectly (Publish).

Because HTTP/HTTP_PORTS bind to all interfaces not just localhost. ASPNETCORE_URLS lets you control what interfaces are bound.

> One other inconsistency: if you define endpoints using .WithHttpEndpoint(), your port makes it to the manifest in the binding. But if it comes from the profile, we omit the port. Why?

https://github.com/dotnet/aspire/issues/3786

> Yes, that's what I would expect, but it's not quite the case today, as per my earlier comment. The presence of endpoints in the launch profile results in the addition of the (port-less) bindings in manifest.

We want port-less endpoints to mean "the environment gets to decide on what the default ports are". The launch profile serves as a template for which endpoints you want, the names but not the data (no port info).

**Comment by davidebbo** [comment]
I sent initial PR, and added various PR comments in there for discussion. PTAL.
