### ISSUE TITLE
[Nats]: WithJetStream method takes a mount path that assumes a bind mount

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3756]
https://github.com/dotnet/aspire/blob/4829f56034c6ea799743c0550cdbd6c3d64e3ac5/src/Aspire.Hosting.Nats/NatsBuilderExtensions.cs#L36-L47

Seems like we should remove the path from this method and instead follow the pattern we've established for containers that have well known directories for persistence. 

e.g.

https://github.com/dotnet/aspire/blob/4829f56034c6ea799743c0550cdbd6c3d64e3ac5/src/Aspire.Hosting.Kafka/KafkaBuilderExtensions.cs#L40-L51

cc @mtmk

**Comment by mitchdenny** [comment]
Same for Seq.

**Comment by mtmk** [comment]
happy to put a PR in if it's not planned
