### ISSUE TITLE
[WebToolsE2E][Aspire] When using .NET Aspire with Application Insights in VS, running with F5 fails: "The application is in break mode and something does not have an implementation..."

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#3760]
**REGRESSION INFO**: Also reproduced on VS 17.10.0 Preview 4 [including .NET Aspire 8.0.0-preview.5.24201.12]

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 5 [rel.d17.10-34816.249] [including .NET Aspire 8.0.0-preview.5.24201.12]

**REPRO STEPS**
1. New Project > Aspire Starter Application > name it 'AspireApp1' > check 'Use redis' checkbox > Create
2. Configure the AspireApp4.ServiceDefaults project
> - Install the package "Azure.Monitor.OpenTelemetry.AspNetCore" to the ServiceDefaults project
> - Open the Extensions.cs file, add a using statement:
 `using Azure.Monitor.OpenTelemetry.AspNetCore;`
> - Uncomment the line in AddOpenTelemetryExporters to use the Azure Monitor exporter:
 > ![image](https://github.com/dotnet/aspire/assets/72899617/32bae488-17fd-4b53-819c-4ae638f318a0)

3. Configure the AspireApp4.AppHost project

> - Right-click xx.AppHost project > Add >  Aspire component >  Aspire.Hosting.Azure.Provisioning > add a component
> - Right-click the AppHost project and select "Manage User Secrets" to open the secrets.json file, Replace with the following code 
> ```
> {
> {
>   "ConnectionStrings": {
>     "aapt0412appinsights": "InstrumentationKey=696c79f0-d7bc-45df-a5c9-539ab1ab7dde;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=d024bb13-c44a-4ed5-b0c3-5bd108d4901c"
>   }
> }
> }
> ```

> - Open Program.cs file of the AppHost project, update the app host code to use the Application Insights resource, and reference it from each project:
`builder.AddAzureProvisioning();`
`var insights = builder.AddAzureApplicationInsights("aa05Web");`
`var apiService = builder.AddProject<Projects.AspireApp4_ApiService>("apiservice").WithReference(insights);`
`builder.AddProject<Projects.AspireApp4_Web>("webfrontend").WithReference(apiService).WithReference(insights);`
> ![image](https://github.com/dotnet/aspire/assets/72899617/ec259c7f-30f9-4455-aa3c-7d6c8a5466e9)

4. F5 to run

**Note**: The version of package 'Aspire.Hosting.Azure.Provisioning' is 8.0.0-preview.4.24156.9, lower than the Aspire P5 version.

**ACTUAL**
Failed to run
![image](https://github.com/dotnet/aspire/assets/72899617/b8b72f4c-0c07-466e-bfd0-606a233d2de3)
The application is in break mode
Your app has entered a break state, but no code is currently executing that is supported by the selected debug engine (e.g. only native runtime code is executing).

System.TypeLoadException
  HResult=0x80131522
  Message=Method 'get_ConnectionStringExpression' in type 'Aspire.Hosting.Azure.AzureApplicationInsightsResource' from assembly 'Aspire.Hosting.Azure, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' does not have an implementation.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**EXPECTED**
After running F5, the web page loads successfully and Application Insights functions normally.

**Comment by davidfowl** [comment]
> Right-click xx.AppHost project > Add > Aspire component > Aspire.Hosting.Azure.Provisioning > add a component

What package versions are you using?

**Comment by v-bennettyue** [comment]
@davidfowl The version of package 'Aspire.Hosting.Azure.Provisioning' is 8.0.0-preview.4.24156.9 on 'nuget.org' feed, and there is no P5 version.

**Comment by v-bennettyue** [comment]
@davidfowl @balachir After install the "Aspire.Hosting.Azure.ApplicationInsights" package, this issue will not repro, but F5 to run, the resources failed to start as follow:
![image](https://github.com/dotnet/aspire/assets/72899617/c1e6bfad-75d2-424c-9c9f-1daa36be92c1)
![image](https://github.com/dotnet/aspire/assets/72899617/15da0bb0-be76-484f-95c5-2ab318d7a52a)

If using "AddConnectionString", all resources running successfully, but after creating some errors on web page, the errors cannot be displayed on portal.
![image](https://github.com/dotnet/aspire/assets/72899617/285174e5-ec18-4b72-8ecc-bdcf8bf84978)

**Comment by davidfowl** [comment]
The instructions on how to use app insights is here https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/application-insights

**Comment by v-bennettyue** [comment]
@davidfowl Yes, now there is no need to install this package, so can this bug be closed directly?

**Comment by davidfowl** [comment]
Yep
