### ISSUE TITLE
Dotnet publish broken in preview 5

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/aspire#3766]
I noticed my CI stopped building images after I upgraded to preview 5.

See https://asciinema.org/a/XBd5yCk1SHPISVNrJKgb3Bfgb

Repro steps:

1. dotnet new aspire
2. dotnet publish mynewaspire.csproj
3. Try to find the output of the publish operation 🕵🏼‍♂️

**Comment by davidfowl** [comment]
Publishing the apphost project doesn’t work and has never worked AFAIK.

**Comment by ElanHasson** [comment]
Perhaps a poor example, I can't get an "aspire" web API project to publish either.

**Comment by ElanHasson** [comment]
@davidfowl i can't repro with a `dotnet new aspire-starter` when i try to publish the API project that is in the template.

However, myself and another eng on the team can't publish, neither can our GHA which works on main (preview4), but in our preview5 upgrade branch, fails to publish any output. 

It's a private repo, so i can't link here, but I will try to clone + remove all non-relevant stuff to get a repro sample i can share.

I am also happy to zip up and share with you privately.

**Comment by davidfowl** [comment]
I guess I still don't understand what worked before and what doesn't work now. A minimal repro showing the problem would be great.

**Comment by ElanHasson** [comment]
I'll get on that minimal.

Let me try to explain a bit better.

I used to be able to do: 
```shell
dotnet restore System.sln
dotnet build System.sln --no-resource -c Release
dotnet publish "src/InfinityFlow.Hosting.WebAPI/InfinityFlow.Hosting.WebAPI.csproj" -c Release --no-build --no-restore -o /app/publish
```

Which would, as expected output the publish output to `/app/publish`.

Now, `dotnet publish` does not output anything at all, nor does it result in any error output or a non-zero exit code.

I also can't get right click =>publish to output anything for the same project.

I'll update here with the repro app.

**Comment by davidfowl** [comment]
Doesn't look related to aspire. Looks like a .NET SDK issue.

**Comment by ElanHasson** [comment]
Thanks @davidfowl.

I dug a bit deeper.  I'm attaching some binlogs.
[publish-with-webconfigtransform-error.zip](https://github.com/dotnet/aspire/files/15031158/publish-with-webconfigtransform-error.zip)

I tried producing a binlog when `IsWebConfigTransformDisabled` is set to `true` to bypass the webconfig transform error, and it seems msbuild isn't even called as no binlog is produced.


![image](https://github.com/dotnet/aspire/assets/234704/895b9f92-c82a-4987-9d9c-22d8ebe97a18)

Running `dotnet` with `-d` didn't seem to do much.

![image](https://github.com/dotnet/aspire/assets/234704/467a789f-7923-40ca-a8df-a4e93c1e16f7)

I figured out what is "causing it": Add a reference to a package I make: [InfinityFlow.Aspire.Temporal](https://github.com/InfinityFlowApp/aspire-temporal). 

Also reproducible when you reference `Aspire.Hosting.AppHost`. 

For my `InfinityFlow.Aspire.Temporal` i think it's because of the transitive dependency on `Aspire.Hosting.AppHost`. 

:)

**Comment by timheuer** [comment]
@ElanHasson why are you referencing `Aspire.Hosting` in the API project?

**Comment by ElanHasson** [comment]
> @ElanHasson why are you referencing `Aspire.Hosting` in the API project?

Heh, I'm not-- it came in via a package I make indirectly.

A better experience might be to detect that it's referenced in a non app host project and display an error vs the current behavior of a Web.config transform error + fail silently.

I admit, it's my fault for probably missing it in the docs.

**Comment by timheuer** [comment]
Ok, looking at the repo I see a direct pacakge ref not a transitive one...but might result in the same thing. It's definitely odd either would affect publish of the project.  I see the error and was looking at the binlog, but after opening your solution in VS, I then could no longer repro the error?!?!

**Comment by timheuer** [comment]
But it's definitely InfinityFlow.Aspire.Temporal causing the issue.

**Comment by ElanHasson** [comment]
@timheuer yeah thanks for taking a look. I tried many, many things so it might have actually snuck in there the direct reference. 

Tried everything the last thing I did was 1x1 remove every package and try.

**Comment by timheuer** [comment]
Okay to close this one @ElanHasson ?

**Comment by ElanHasson** [comment]
Go ahead @timheuer 

Should the output of this report be to add a publish time error or warning when `Aspire.Hosting` is referenced in a non-apphost project and is attempted to be published?

Not sure if that is something to do with the sdk preview or if aspire's msbuild stuff is interfering (for example, the web.config transform stuff).

I'll defer to you on that stuff-- but yes you may close this one.

**Comment by timheuer** [comment]
I might take another stab at trying to repro this with a simpler solution, but couldn't detect easily what the specific issue was.

**Comment by ElanHasson** [comment]
Yeah i just don't want anyone else to lose time to something like this.

Thanks

**Comment by timheuer** [comment]
I tried to recreate the scenario (apphost referencing a library that has a reference to Aspire.Hosting.AppHost) and cannot trigger that error.  I do want to know if there is an issue here with targets as triggering that web.config one is absolutely odd here.  But I can't get a smaller repro...

**Comment by ElanHasson** [comment]
hm. Did you try with the package i used? btw it's oss, https://github.com/InfinityFlowApp/aspire-temporal/ 

so maybe i'm doing something wrong in that package which is "spilling over" into the repro?

were you able to repro with what i sent though? It's not environmental, as in limited to just me, right?

**Comment by timheuer** [comment]
I tried with a starter app and adding your package to the web api project...but i also can repro with your zip file.  I'm a bit confused on what the specific trigger is but the simple recursion of references doesn't seem to be it.

**Comment by davidfowl** [comment]
Is this still an issue? Are we tracking anything here to be fixed?

**Comment by ElanHasson** [comment]
Don't think so. Go ahead and close @davidfowl, I'm not expecting anything from here as the answer is in the comments.
