### ISSUE TITLE
Azure Storage should expose a "WithStorageExplorer" API

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/aspire#3778]
Similar to pgAdmin and RedisCommander, it would be convenient to expose an [Azure Storage Explorer](https://azure.microsoft.com/en-us/products/storage/storage-explorer/) webpage (similar to the one in the Azure Portal) that allows us to browse our Azurite emulator managed instances

**Comment by davidfowl** [comment]
That sounds great, how would it work? Is there a container that runs the storage explorer that exposes an http endpoint?

**Comment by csharpfritz** [comment]
The team has a slimmed down version that runs in the Azure Portal.  I don't think its available as a container though.

I'm exploring the image at https://github.com/sebagomez/azurestorageexplorer to attach and work with my Aspire hosted Azure Storage instances

**Comment by csharpfritz** [comment]
I am having a hard time getting that StorageExplorer container connected with a proper connectionstring to a host Azurite emulator. 

Any ideas how to pull the connectionstring in AppHost and pass it as an environment variable?

**Comment by davidfowl** [comment]
Show me what you have currently?

**Comment by davidfowl** [comment]
```C#
var builder = DistributedApplication.CreateBuilder(args);


var storage = builder.AddAzureStorage("storage")
                     .RunAsEmulator(config => config.WithDataVolume())
                     .AddBlobs("blobs");

builder.AddContainer("storage-explorer", "sebagomez/azurestorageexplorer")
    .WithHttpEndpoint(targetPort: 8080)
    .WithEnvironment(e =>
    {
        e.EnvironmentVariables["AZURE_STORAGE_CONNECTIONSTRING"] = new ConnectionStringReference(storage.Resource, optional: false);
    })
    .ExcludeFromManifest();

builder.Build().Run();
```

RunAsEmulator will be used in run mode not publish mode so no need to guard it behind the IsDevelopment method. Our azure storage resource only exposes connection strings for specific resources like blob, queue or table. We don't expose the uber connection string since with all 3.

**Comment by csharpfritz** [comment]
Very cool!  That appears to have that container running and connecting to the storage service.  I really need to access the tables browser, so I changed the connectionstring over to the tables instance and it doesn't appear to be connecting like the blobs connectionstring does.

There appears to be a few issues with the Storage Explorer container.  I'll connect with that package owner and see if we can get that in a better working order

**Comment by 19essibusa** [comment]
Hi please is this solution for the azure storage explorer going to eventually be officially integrated to .NET aspire as a container like pgAdmin? That would be so helpful if possible. I am having issues connecting the Microsoft azure monitor to the azurite instance created by aspire.

**Comment by NiklasEi** [comment]
Configuring the storage explorer like shown above doesn't seem to work for me. Did someone get this to work for a local Azurite blog storage?

On the first glance, it looks like an issue on the side of storage explorer, not Aspire, so I opened sebagomez/azurestorageexplorer#173

**Comment by swissarmykirpan** [comment]
```Our azure storage resource only exposes connection strings for specific resources like blob, queue or table. We don't expose the uber connection string since with all 3.```

@davidfowl it would be useful to get this uber connection string. Happy to contribute.

**Comment by swissarmykirpan** [comment]
@csharpfritz another alternative may be change the Azure Storage Resource Endpoints to use Azure Storage Explorer Direct Links https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-direct-link

**Comment by davidfowl** [comment]
Filed an issue https://github.com/dotnet/aspire/issues/6234.

Closing this as there's no locally hostable storage explorer that we would embed by default.
