### ISSUE TITLE
Any http or https endpoint added to a project resource without a target port map to the default port when published

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3786]
The manifest publisher [special cases http or https endpoints for project resources](https://github.com/dotnet/aspire/blob/bafcacd4e5e571a7551381e3a734138dd64bf8bc/src/Aspire.Hosting/Publishing/ManifestPublishingContext.cs#L293) and does not attempt to allocate a target port for them. This behavior differs from runtime behavior as each endpoint is unique.

We have this logic to let the tool set the default the port, but instead we should have the ability to mark those endpoints specially so other http endpoints get allocated target ports.

**Comment by davidebbo** [comment]
I can see two paths here:

1. Add a first class `IsDefault` property to `EndpointAnnotation`:
  - Only allow one endpoint per scheme to have it set
  - Use some logic to automatically set it for some endpoints. e.g. at the very least [this logic](https://github.com/dotnet/aspire/blob/a891b99472315073888103ab66dc1223a0bea9d0/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs#L366-L383) would set it. But probably also the first call to `WithHttpEndpoint` if a TargetPort is not passed in.
2. Simply rely on *it's default if the name matches the scheme*, which is sort of what's happening right now in some places.

We probably need 1., but the question more whether this issue is where we do it.

If we do 2., it could be as simple as changing the manifest publishing code from:

```c#
(ProjectResource, var scheme, null, _) when scheme is "http" or "https") => null
```

to

```c#
(ProjectResource, var scheme, null, _) when scheme is "http" or "https" && string.Equals(endpoint.Name, endpoint.UriScheme, StringComparisons.EndpointAnnotationName) => null
```

We do need to watch for breaking changes, though to some extent it's inevitable.

**Comment by davidfowl** [comment]
I was thinking that this is a project resource specific property. This whole idea of a default endpoint is currently scoped to projects.

**Comment by davidebbo** [comment]
> I was thinking that this is a project resource specific property.

I see. And you're talking **public** property on `ProjectResource`? We'd have to think about the API model for people to set this. e.g.

```c#
builder.AddProject(..., defaultHttpEndpoint="foo", defaultHttpsEndpoint="bar")
```

But that feels quirky as it's decoupled from the Endpoint declaration.

Or if we keep it internal and use heuristics to set it, we side step the object model concerns.

**Comment by davidebbo** [comment]
Other question: would it be ignored in Run mode, and only affect Publish mode?

**Comment by davidfowl** [comment]
> Or if we keep it internal and use heuristics to set it, we sidestep the object model concerns.

This. 

I consider the public API issue to be this one https://github.com/dotnet/aspire/issues/4472

> Other question: would it be ignored in Run mode, and only affect Publish mode?

Publish mode only. If you want to think about this issue another way. This change makes publish mode work more like run mode. Right now every http endpoint is supposed to be a different endpoint, not part of the same endpoint.

Another way of thinking about this is that a negative port (or some sentinel value) means "this is the default port". Right now that value is null, but it makes it hard to distinguish "generate a random port" vs "use the default port"

**Comment by davidebbo** [comment]
Ok, I'll take a crack at it.

And I assume that you mean the sentinel value as an internal mechanism to flow this bit, and not as something that we expose to users to set explicitly on their TargetPort, right?

**Comment by davidfowl** [comment]
> And I assume that you mean the sentinel value as an internal mechanism to flow this bit, and not as something that we expose to users to set explicitly on their TargetPort, right?

That's right. I was just using it visualize the problem 😄. I think internal state on the project resource is good enough.

**Comment by davidebbo** [comment]
Lets' move from implementation to spec, and identify exactly in what scenarios we want to treat an endpoint as Default. In terms of resulting behavior, it's straightforward:
- Those identified as 'default' don't get a TargetPort allocated
- The rest does, unless they explicitely specify a TargetPort

Let's look at scenarios:

### Implied endpoints

You don't specify any endpoints, and we add default http & https endpoints in `WithProjectDefaults`. This is the most obvious case where we treat them as Default.

### Explicit nameless endpoint

Seems pretty clear that it should be viewed as default.

```c#
var svc = builder.AddProject(...)
    .WithHttpEndpoint()
```

### Explicit named endpoint

I would say it's still viewed as Default.

```c#
var svc = builder.AddProject(...)
    .WithHttpEndpoint(name: "foo")
```

### Multiple explicit endpoints

The first has a custom name, and the second doesn't. Which one is Default? I'd say the first, though it could be argued that the one with the default name should be Default.

```c#
var svc = builder.AddProject(...)
    .WithHttpEndpoint(name: "foo")
    .WithHttpEndpoint()
```

### Kestrel endpoints

I think we treat them the same way as if they had been explicitely defined.

### Conclusion

Should we just say that the Default is always **whichever one is declared first** (for each scheme), regardless of its name? It is after all more or less what we're doing in [this code](https://github.com/dotnet/aspire/blob/a891b99472315073888103ab66dc1223a0bea9d0/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs#L359-L393).

Side note: I don't understand the right side of the `||` is [this line](https://github.com/dotnet/aspire/blob/a891b99472315073888103ab66dc1223a0bea9d0/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs#L362) (which I think came from you). It matches an endpoint that is named http but doesn't have the http scheme (or same for https). What's the scenario here?
