### ISSUE TITLE
[Cosmos .NET SDK] - Introduce New User Agent to Identify Usage

### ISSUE THREAD

**Issue by kundadebdatta** [dotnet/aspire#3789]
### Description:

The purpose of this task is to populate the `ApplicationName` parameter in the `CosmosClientOptions` so that the user agent can be generated with the necessary suffix. This will help the cosmos db team to identify the request is originated from Aspire. A sample usage can be found below:

```
            CosmosClientOptions cosmosClientOptions = new CosmosClientOptions();
            cosmosClientOptions.ApplicationName = "AspireMicrosoftAzureCosmosDBClient";
            cosmosClientOptions.AllowBulkExecution = false;
            cosmosClientOptions.HttpClientFactory = () => new HttpClient();
```

A sample of the user agent will look like the below:

`cosmos-netstandard-sdk/3.39.1|0|X64|Microsoft Windows 10.0.22635|.NET 6.0.29|N|F 00000111|AspireMicrosoftAzureCosmosDBClient|`

### Acceptance Criteria:

- The cosmos .NET SDK team needs to introduce a new user agent to identify and usage of aspire.

**Comment by kirankumarkolli** [comment]
Just adding the ApplicationName in Aspire code base will generate the required user-agent right?

Is it the length of the user-agent the issue?

**Comment by kundadebdatta** [comment]
This is addressed with the following PRs:

- https://github.com/dotnet/aspire/pull/3876
- https://github.com/dotnet/aspire/pull/3906
