### ISSUE TITLE
Creating Password 

### ISSUE THREAD

**Issue by wangkanai** [dotnet/aspire#3803]
Reference to the new interface added in Aspire Preview 5, https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-5?tabs=dotnet-cli#automatic-password-generation

But setting your own username and password with `IResourceBuilder<ParameterResource>` does not expose any setter method to add the username & password to the parameter resource. I have tried `WithEnvironment(string name, string value)`, which I still get the error

```console
Failed to apply configuration value 'MYSQL_ROOT_PASSWORD'. A dependency may have failed to start.
```

This is my app host configurations

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var sqlPassword = builder.AddParameter("sql-password", true)
                         .WithEnvironment("MYSQL_ROOT_PASSWORD", DatabaseConstants.Password);

var sqlMySql = builder.AddMySql(ResourceConstants.SqlMySql, sqlPassword, 60100)
                      .WithEnvironment(ResourceConstants.SqlMySql, ResourceConstants.SqlMySql);
``` 

So I'm not sure if this is a bug or my miss used.

**Comment by davidfowl** [comment]
That's not how you set the password. Also attaching WithEnvironment to a Parameter is an API issue that will be fixed by GA 😄.

See this https://github.com/dotnet/docs-aspire/issues/672#issue-2242008335

**Comment by wangkanai** [comment]
I am honored to get a reply from David Fowler himself. Thank you for pointing me in the right direction, I have not got a working solution.

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var sqlPassword = builder.CreateStablePassword(ResourceConstants.SqlPassword, lower: true, upper: true, numeric: true,
                                               special: true, minLower: 1, minUpper: 1, minNumeric: 1, minSpecial: 1);

var sqlMySql = builder.AddMySql(ResourceConstants.SqlMySql, sqlPassword, 60100)
                      .WithEnvironment(ResourceConstants.SqlMySql, ResourceConstants.SqlMySql);
```

**Comment by davidfowl** [comment]
WithEnvironment  isn't required.
