### ISSUE TITLE
[AzureTools][Aspire] Container state in dashboard takes too long to respond after stopping/deleting a container in Podman desktop

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#3807]
**Clean machine**: Win11 x64 23h2 ENU
**VS Version**: VS 17.10.0 Preview 4.0 [34814.37.d17.10]
**Aspire Version:** 8.0.0-preview.6.24214.1 
Apply NuGet Feeds
**Podman Desktop:** 1.9.1
**Podman CLI:** 5.0.1

**REPRO STEPS:**
1. Create an Aspire starter project with "Use Redis for caching (requires Docker)" checked.
2. F5/execute `dotnet run` in the AppHost project path and open the dashboard.
3. Stop/Delete the running container in Podman Desktop -> Refresh the dashboard in the browser.

**Expect:**
The state of running container changes "Existed/Removed".
![Actu1](https://github.com/dotnet/aspire/assets/62053665/bd19d8ec-deb5-4402-a2fc-e96cc38ecf22)

**Actual:**
The state of running container changes to “Existed" or "Removed" **after about 6 minutes**.

**More Info:**
1. This issue also **reproduces** on VS 17.10 Preview 4.
2. This issue **doesn't reproduce** for **Docker Desktop**.

**Comment by davidfowl** [comment]
There seems to be several bugs:
- https://github.com/dotnet/aspire/issues/2816
- Dashboard update takes a while
- We may not be handling removed resources properly in the apphost

@karolz-ms

**Comment by karolz-ms** [comment]
Ping myself or @danegsta if it turns out that DCP does not tell the app host/dashboard soon enough about the demise of the container.

**Comment by karolz-ms** [comment]
@leslierichardson95 for now I will remove myself and `area-orchestrator` label from this issue because there is no known problem with the orchestrator here. If it turns out that DCP is not doing what it needs to do, feel free to re-add me and re-apply the label.

**Comment by v-mengwe** [comment]
@davidfowl Verified on the Aspire 9.0.0-preview.4.24456.4 with Podman 1.12.0 and Podman CLI 5.2.2, the state of running container changes to “Existed" after stopping the running container in Podman about 7 minutes, whereas the status of a running container changes to “Existed” very quickly after stopping the container in Docker Desktop. Is it by design?

**Comment by davidfowl** [comment]
7 minutes is too long. @karolz-ms did you observe this?

**Comment by v-mengwe** [comment]
@karolz-ms Verified on the Aspire 8.2.1 with Podman 1.12.0 and Podman CLI 5.2.2 on VS 17.10.7, the state of running container changes to “Existed" after stopping the running container in Podman **about 5 minutes**. Is this issue only fixed in the latest Aspire 9.0?

**Comment by karolz-ms** [comment]
@v-mengwe correct, you need DCP release 8.3 or later to enjoy the fix.

**Comment by v-mengwe** [comment]
Verified on the Aspire 9.0.0-preview.4.24475.6 with Podman 1.12.0 and Podman CLI 5.2.3 on VS 17.12 Preview 3, this issue doesn't reproduce for now.
