### ISSUE TITLE
[WebToolsE2E][Aspire][Win arm64] When creating an Aspire project and run it in CMD, you need to enter a token every time you run it.

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#3808]
**REGRESSION INFO:** New feature on Aspire 8.0 preview 6

**INSTALL STEPS**

1.Clean machine: Win11 arm64 23h2 ENU
2.Install SDK 8.0.204
3.Install Aspire 8.0 Preview 6 [8.0.0-preview.6.24214.1]
4.Apply NuGet Feeds

**REPRO STEPS**

1.Open Command Prompt, run the following commands to create and run the project
```
dotnet new aspire -o aspire1
cd aspire1/aspire1.AppHost
dotnet run
```
2.Open Edge(Defaut) browser to run, enter token to log in, the page works fine
3.Close browser, then use Edge to run

**Note:** 
1.This also happens in Google Chrome and Firefox.
2.After paste the token and login succeed in browser, there shows 2 cookies in browser settings. but if close browser, then use browser to run again, there shows only 1 cookie.
(the 'Allow site to save and read cookie data' was checked by default in browser settings.)
3.This issue does not repro on Win x64/Mac OS/Linux

**ACTUAL**
Every time you run the same project, you need to enter a token.
![image](https://github.com/dotnet/aspire/assets/88425944/9cf8cb0b-330d-4099-bf40-8f8bc5c4c55f)
![test1](https://github.com/dotnet/aspire/assets/88425944/b1d2f70e-8a55-4b15-b925-f11331f9aaa8)

**EXPECTED**
Only needs to be entered once.

**Comment by davidfowl** [comment]
This is fixed in GA by using a persistent cookie.

**Comment by leslierichardson95** [comment]
See David's comment above :)

**Comment by v-sherryfan** [comment]
Verified  that this issue does not reproduce on Aspire 8.0 GA (8.0.0-preview.7.24224.5) + sdk 8.0.204
