### ISSUE TITLE
Service Discovery: allow configuration to replace URI scheme for HTTP calls

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/aspire#381]
~eg, replace "http://.*" with "https://.*"~

Latest proposal was to support something like "svc://" that would be replaced with "http://" or "https://" based on service discovery configuration.

**Comment by DamianEdwards** [comment]
Last discussion on this produced the idea of an explicit scheme that would need to be specified in the address for service discovery to perform this action, e.g. "svc://basketservice". The "svc" would be replaced by "http" or "https" based on service discovery configuration/behavior. The hope would be this feature could help us solve the current issues that forced us to use "http" everywhere in our templates, etc.

**Comment by danmoseley** [comment]
We don't see this for P3 cutoff

**Comment by davidfowl** [comment]
@ReubenBond we want to get something here for preview4

**Comment by ReubenBond** [comment]
@davidfowl I thought you were against this idea? Let's discuss it

**Comment by davidfowl** [comment]
I as against the idea if the scheme was specified. If the scheme is `auto://` then its fine.

**Comment by DamianEdwards** [comment]
Someone suggested `httpx://` to opt-in to scheme resolution today so I'm putting it here 😁

**Comment by danmoseley** [comment]
We have to do in P5

**Comment by DamianEdwards** [comment]
This is done now thanks to #2719 yeah @ReubenBond?

**Comment by ReubenBond** [comment]
Yes, we can close this
