### ISSUE TITLE
[WebToolsE2E][Aspire] When running "dotnet watch", the URL without token is automatically opened and the token authentication pops up, instead of automatically opening the URL with token and logging in like vs.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#3812]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.204
3. Install .NET Aspire 8.0.0-preview.6.24214.1
4. Apply NuGet Feeds

**REPRO STEPS**

1. Go to browser settings > delete localhost cookies
2. Running with `dotnet watch`
    - Open CMD, create an aspire starter app using following code
       ```
       dotnet new aspirestarter -o aspire4
       cd aspire4\aspire4.AppHost
       dotnet watch      
      ```
    - Automatically open the URL without the token, and then dashboard token authenticaton popup
    ![image](https://github.com/dotnet/aspire/assets/71361488/41b2a2f0-110a-427b-afe9-6e3208580ec0)
    ![image](https://github.com/dotnet/aspire/assets/71361488/3824d00d-075c-4cd5-946a-060a1699c6e2)

**Note:**

 Unlike `dotnet watch`, we can decide to open the url without token or with token url when running with 'dotnet run'.
    ![image](https://github.com/dotnet/aspire/assets/71361488/42ccb6f2-eb8d-4337-9836-59188138b2ee)

**ACTUAL**

The URL without token is automatically opened, so you need to manually enter the token value to log in.

**EXPECTED**

For the `dotnet watch` scenario, similar to VS, it will automatically open the URL with the token and log in.

**Comment by davidfowl** [comment]
dotnet watch is being re-designed to work with aspire. That work is happening in 9.0.200 SDK which is not shipping with .NET 9. This has been fixed in that branch.

You can see the work items for watch and aspire here https://github.com/dotnet/sdk/issues?q=is%3Aissue%20label%3AAspire%20
