### ISSUE TITLE
[WebToolsE2E][Aspire] Add some code to Aspire project and publish again, it will shows "Didn't find new changes."

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#3829]
REGRESSION INFO: Also reproduce on Aspire P5

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 5 [rel.d17.10-34818.151] includes Aspire 8.0 P6 [8.0.0-preview.6.24214.1]
3. Apply dotnet-tools Feed
4. Install latest daily azd [1.9.0-beta.1-daily.3712265]
5. Install git [2.44.0.windows.1]

**REPRO STEPS**
1. Create a new Aspire Starter App project using VS or CLI
2. Open Command Prompt and navigate to the solution path of this project
3. Run 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment named bennett, press enter
4. Run 'azd up', and select Subscription to WTE and select Location to East US, press enter
5. Open the program.cs of the AppHost project add follow code:
`var apiService = builder.AddProject<Projects.AspireApp6_ApiService>("apiservice").WithExternalHttpEndpoints();`
![image](https://github.com/dotnet/aspire/assets/72899617/5a6ed2fc-ac7a-4b32-a73f-5baf0629be7c)
6. Publish again

**ACTUAL**
It will shows Didn't find new changes.
![image](https://github.com/dotnet/aspire/assets/72899617/2e2ec4c2-a3b0-44f5-b663-d39fa54dce58)

**Comment by davidfowl** [comment]
AZD issue. Can you move this to https://github.com/Azure/azure-dev/issues

**Comment by v-bennettyue** [comment]
Close this issue because the repo is wrong.
