### ISSUE TITLE
Augment EventHubs support to include EventHubBufferedProducerClient

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspire#3832]
Today, the Event Hub implementation facilitates registration only of the [EventHubProducerClient](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.producer.eventhubproducerclient?view=azure-dotnet) and the [EventHubConsumerClient](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.consumer.eventhubconsumerclient?view=azure-dotnet). I'd like to request that it also facilitate registration of the [EventHubBufferedProducerClient](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.producer.eventhubbufferedproducerclient?view=azure-dotnet), which shouldn't require much more than just adding an extension method for it as the bulk of the work is already there for the existing implementations.

**Comment by eerhardt** [comment]
Fixed by https://github.com/dotnet/aspire/pull/3833.
