### ISSUE TITLE
Dashboard metrics view crashes when viewing metrics of a Node.js app running with a Dapr sidecar

### ISSUE THREAD

**Issue by asimmon** [dotnet/aspire#3844]
> Full repro case in this repo: https://github.com/asimmon/aspire-node-metrics-bug

An error banner with "An unhandled error has occurred" appears at the bottom of the **metrics view** if I try to display the metrics of an instrumented Node.js express app running **with a Dapr sidecar**:

```csharp
builder.AddNpmApp("nodeapp", Path.Combine("..", "nodeapp"), "watch")
    .WithDaprSidecar()
    .WithHttpEndpoint(port: 3000, env: "PORT")
    .WithEnvironment("NODE_TLS_REJECT_UNAUTHORIZED", builder.Environment.IsDevelopment() ? "0" : "1");
```

Here's the error:

![image](https://github.com/dotnet/aspire/assets/14242083/a49ae8b2-0c39-4213-87f2-29c7115a7eb5)

The error does NOT appear if:

- I remove the Dapr sidecar, OR
- I pass new `DaprSidecarOptions` options with an `AppId` property set to something else than the Node.js app resource name, like so:

```csharp
builder.AddNpmApp("nodeapp", Path.Combine("..", "nodeapp"), "watch")
    .WithDaprSidecar(new DaprSidecarOptions
    {
        AppId = "nodeapp-renamed" // <-- FIX
    })
    .WithHttpEndpoint(port: 3000, env: "PORT")
    .WithEnvironment("NODE_TLS_REJECT_UNAUTHORIZED", builder.Environment.IsDevelopment() ? "0" : "1");
```

With one of these two changes, the metrics are shown:

![image](https://github.com/dotnet/aspire/assets/14242083/d46b4f89-4d58-4a19-8940-5b7cf1e0794d)

**Comment by davidfowl** [comment]
@JamesNK

**Comment by JamesNK** [comment]
Fix https://github.com/dotnet/aspire/pull/3861
