### ISSUE TITLE
How to configure Azure container app environment  workload type

### ISSUE THREAD

**Issue by mmacka** [dotnet/aspire#3901]
Is it possible to instruct aspire project to provision container app environment  with workload type other than "Consumption only"?

Even if it would not be possible to set specific type like "D4" it would be great help to allow provisioning container app environment which allows manual change of workload type.

Applications can overgrow resources provided by default type and than it becomes an issue.

**Comment by davidfowl** [comment]
No, there's no way to customize this from the apphost at this time. You can run `azd infra synth` and tweak the generated bicep and yaml
