### ISSUE TITLE
Add a warning when using a later AppHost package than workload exists

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#3920]
ref: https://github.com/dotnet/aspire/issues/3867

In this scenario the user has an older workload (e.g., preview 3) but adds new Aspire.Hosting.AppHost packages (preview6).  The expectation is that they'd get preview6 orchestration capabilities, but that is not the case if the workload is not updated to match.

We should consider warning (or blocking?) in this situation basically where DCP/AppHost/Dashboard are not 'matching'

**Comment by davidfowl** [comment]
We plan to make these mixed scenarios work post preview.

**Comment by joperezr** [comment]
This is no longer an issue as the versions of DCP and Dashboard now match the reference to AppHost package. I'm closing this for now, but feel free to reopen @timheuer if you think there is anything else we should do here.
