### ISSUE TITLE
Required additional customization of DbContext causes logs to not show up

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspire#3926]
I'm not sure if this is a bug or not.
In my project I have to perform additional configuration into the DbContext, specifically, adding interceptors and setting up NetTopologySuite.
Something I noticed is that, when I do that, the EF Core queries stop showing up in the logs.
I tried to use the .NET Aspire Enrich method, however, I need access to the ServiceCollection, but the signature does not have any overload with it.
In this project, I only see the logs for ApplicationDbContext, which does not have the additional setup of the interceptors nor the NetTopologySuite.
I'm currently on Preview 4.

Complete Code here: https://raw.githubusercontent.com/pticostaricags/FairPlayCombined/development/src/FairPlayCombinedSln/FairPlayTube/Program.cs

![image](https://github.com/dotnet/aspire/assets/3481899/9f1588e6-7de0-4667-a5d0-27f21899223d)

Logs when login into the application.

![image](https://github.com/dotnet/aspire/assets/3481899/cd66b26c-3955-4dce-a668-19c6588b5501)

When loading the home page, even before logging in, I'm expecting to see the query loading the data from the VideoInfo table, using the customized DbContext.

**Comment by davidfowl** [comment]
cc @sebastienros

**Comment by efonsecab** [comment]
Fixed by changing order and moving back to Services.AddDbContext
![image](https://github.com/dotnet/aspire/assets/3481899/02cc7de1-060b-4d94-9279-6d550da23722)

Logs: 
![image](https://github.com/dotnet/aspire/assets/3481899/70551b68-048f-47c5-8674-5206dd544fba)
