### ISSUE TITLE
Environment Variables not getting overridden when debugging

### ISSUE THREAD

**Issue by cecilphillip** [dotnet/aspire#3932]
### Problem

When a project is added with `IDistributedApplicationBuilder.AddProject`, it injects various [environment variables](https://github.com/dotnet/aspire/blob/bade408eecae2cb080b6de111c97bc290bd2c776/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs#L59) by default; like `OTEL_EXPORTER_OTLP_ENDPOINT`. 

However when debugging, subsequent calls to `WithEnvironment` don't seem to override those values if they exist and app configuration still returns the value set in `AddProject`.

```csharp
var apiService = builder.AddProject<Projects.AspireEnvIssue_ApiService>("apiservice")
    .WithEnvironment("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4318");
```

The Dashboard always shows the (correct) overridden value,
<img width="603" alt="Screenshot 2024-04-24 at 6 33 53 PM" src="https://github.com/dotnet/aspire/assets/350882/762f7d53-416c-4009-bdbd-0b8c5aa18d54">

 but this is not the value shown in the debugger
<img width="756" alt="Screenshot 2024-04-24 at 6 50 03 PM" src="https://github.com/dotnet/aspire/assets/350882/e70bbcd6-c156-4ef2-be04-652937d6d871">

If I run the project on the command line, the correct value is returned from the app configuration.
```
> dotnet run --environment Development --project ./AspireEnvIssue.AppHost/AspireEnvIssue.AppHost.csproj
```

So this issue only shows up when debugging. 

### Environment
- MacOs Sonoma 14.1.2
- .NET SDK 8.0.204

** I haven't verified this behavior in Visual Studio

### Sample Repo
https://github.com/cecilphillip/aspire-env-issue

**Comment by mitchdenny** [comment]
Doing some research:

| OS | Launch Method |Debugger Attached? |Result |
|-|-|-|-|
|Windows|VS|Yes|Override success|
|Windows|VS|No|Override success|
|Windows|`dotnet run`|No|Override success|
|Windows|`dotnet watch`|No|Override success|
|Windows|Rider|Yes|Override success|
|Windows|Rider|No|Override success|
|Windows|Rider with Aspire plugin|Yes|Override success|
|Windows|Rider with Aspire plugin|No|Override success|

So far I haven't been able to reproduce (on Windows).

**Comment by mitchdenny** [comment]
I just tried your repro as well and was not able to reproduce. I notice that you are using Rider. Do you have any plugins installed for Aspire that the Rider team has shipped. I'm wondering whether they are doing some dynamic injection of the variables to intercept OTLP output or something.

**Comment by mitchdenny** [comment]
... either that or it is an OS specific issue.

**Comment by mitchdenny** [comment]
I think I've figured it out. I'm 90% sure this is the Aspire plugin. When I was testing it previously I wasn't actually activating the Aspire plugin for Rider, this time I did and I was able to reproduce your behavior:

![image](https://github.com/dotnet/aspire/assets/513398/2a6fc8fe-e1ac-4ebb-9310-98d932e79992)

When you launch with Rider's launch configuration it must be dynamically injecting the OTLP exporter URL so it can intercept the traffic.

**Comment by mitchdenny** [comment]
If you turn off this setting it works as expected:

<img width="476" alt="image" src="https://github.com/dotnet/aspire/assets/513398/4eb9b44b-d303-4006-b3ea-5a4bbdcde1b1">

**Comment by cecilphillip** [comment]
@mitchdenny Thanks for looking into this Mitch. Yep that fixes it for me.
I'll close this issue

ping @rafaelldi just as an FYI

**Comment by rafaelldi** [comment]
Yes, I set the environment variable to intercept and show the telemetry data in the plugin. I will think about how to do it another way. I am really sorry for the inconvenience.

**Comment by cecilphillip** [comment]
@rafaelldi nothing to be sorry about. We're all just trying to figure it out together. Very much appreciate the work you've put in.
