### ISSUE TITLE
Update docker images to use semantic version tags

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#3933]
The plan in https://github.com/dotnet/aspire/issues/1997#issuecomment-1924592452 was to use a "floating version" tag for docker images where we could take new security/patch updates automatically but not take breaking changes.

If the underlying docker image follows https://semver.org/, this would mean we would ideally depend on the `major` version tag of the docker image, or `major.minor` if available and security/critical bug fixes were released on that tag.

Some of our hard-coded tags use this model today. Some of the underlying docker images don't support `major` or `major.minor` tags.

But there are some docker images that have semantic versioned images, but we are using too specific versioned of a tag, meaning that we won't pick up security and critical bug fixes. The ones I'm aware of are:

https://github.com/dotnet/aspire/blob/bade408eecae2cb080b6de111c97bc290bd2c776/src/Aspire.Hosting.MongoDB/MongoDBContainerImageTags.cs#L10

https://github.com/dotnet/aspire/blob/bade408eecae2cb080b6de111c97bc290bd2c776/src/Aspire.Hosting.MySql/MySqlContainerImageTags.cs#L10

https://github.com/dotnet/aspire/blob/bade408eecae2cb080b6de111c97bc290bd2c776/src/Aspire.Hosting.PostgreSQL/PostgresContainerImageTags.cs#L10

https://github.com/dotnet/aspire/blob/bade408eecae2cb080b6de111c97bc290bd2c776/src/Aspire.Hosting.Redis/RedisContainerImageTags.cs#L10

https://github.com/dotnet/aspire/blob/bade408eecae2cb080b6de111c97bc290bd2c776/src/Aspire.Hosting.Seq/SeqContainerImageTags.cs#L10

We should update these images to follow the above plan.

See also https://github.com/dotnet/aspire/pull/3839#discussion_r1578541000

cc @mitchdenny @timheuer

**Comment by mitchdenny** [comment]
Started a discussion over at Datalust on Seq versioning:https://github.com/datalust/seq-tickets/discussions/2184
