### ISSUE TITLE
Inconsistent result from WithEnvironment string interpolation and reference overloads.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#3937]
Consider the following AppHost code:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var container1 = builder.AddContainer("server", "hello-world")
                        .WithHttpEndpoint(targetPort: 3000);

var container2 = builder.AddContainer("client", "hello-world")
                        .WithEnvironment("ENDPOINT_VIA_REFERENCE", container1.GetEndpoint("http"))
                        .WithEnvironment("ENDPOINT_VIA_INTERPOLATION", $"{container1.GetEndpoint("http")}");

builder.Build().Run();
```

Note that this is two containers with a reference from one container to another. When this code is executed the values of `ENDPOINT_VIA_*` are different:

![image](https://github.com/dotnet/aspire/assets/513398/60dc9e7b-2bd4-44bc-9e24-8ae20043967b)

The endpoint reference version of the overload results in the internal docker host being referenced. The interpolated version uses the address as it would be visible from the host machine.

This inconsistency is probably a but. But it also begs the question - it may be useful to be able to get the endpoint URLs from different perspectives. For example if I am setting a callback/returnurl then I probably want a URL that is valid for a web browser, but if I am providing a URL for a S2S call then I probably want the docker host version.

**Comment by mitchdenny** [comment]
@davidfowl thoughts on how we shold approach this? I feel like they should produce the same result, but I can see utility in being able to get one URL or the other based on the scenario.

**Comment by davidfowl** [comment]
https://github.com/dotnet/aspire/issues/3735

**Comment by davidfowl** [comment]
Closing as dupe
