### ISSUE TITLE
Updated p6 Can't do work 

### ISSUE THREAD

**Issue by skyDuanXianBing** [dotnet/aspire#3938]
I nowday updated my project to p6,but it can't do normal work,(I don't do any change just for update of version), in the vscode 
![image](https://github.com/dotnet/aspire/assets/164180639/cf6d8fd3-bcbb-4b75-b684-85823a335f62)
I get this error .
in the vs, i don't get any error,but i can't work,i can't  connect dashboard  like this 
![image](https://github.com/dotnet/aspire/assets/164180639/acce610f-1b54-4828-80aa-b3db622b42a1)

**Comment by skyDuanXianBing** [comment]
should I set the ASPNETCORE_URLS ?

**Comment by skyDuanXianBing** [comment]
In the p5, I can normal work , like this 
![image](https://github.com/dotnet/aspire/assets/164180639/95d379cc-f23e-4701-9c5b-3d319d67e1f8)

**Comment by skyDuanXianBing** [comment]
I fix it to update aspire workloads

**Comment by timheuer** [comment]
All fixed now @skyDuanXianBing ?

**Comment by skyDuanXianBing** [comment]
> All fixed now @skyDuanXianBing ?

yes,to update your aspire's workloads. in this 
![image](https://github.com/dotnet/aspire/assets/164180639/38a34fd0-9637-4c29-9116-d5e3c7810db5)
