### ISSUE TITLE
"All" should use the same word

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspire#3940]
https://github.com/dotnet/aspire/blob/5fec81174cd305c806f66d4a532188f49bace69c/src/Aspire.Dashboard/Resources/xlf/StructuredLogs.es.xlf#L10-L14

https://github.com/dotnet/aspire/blob/5fec81174cd305c806f66d4a532188f49bace69c/src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf#L5-L9

**Comment by kvenkatrajan** [comment]
Thanks again for you contribution @Varorbc !!
