### ISSUE TITLE
Delisted 9.0 packages break solutions building with .NET 9 SDK previews

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspire#3941]
I've recently added Aspire to two ASP.NET Core apps, which I'm also testing with .NET 9 previews on a long-lived branch.

I saw a comment yesterday that the packages were being de-listed (https://github.com/dotnet/aspire/issues/830#issuecomment-2075856805), but short of completely deleting the AppHost project from the .NET 9 branch, I can't find a way to get the solution to build at all now.

I've tried removing the project reference from the AppHost (because 8.0 can't depend on 9.0) and downgrading it to `net8.0` temporarily, but dotnet restore fails because it can't find the workloads.

What's the fix here? Do I need to clear something out of a local cache?

It seems like the .NET 9 preview 3 SDK has some sort of hard dependency on the packages that have been de-listed making the solution unbuildable, unless I'm missing something really really basic and obvious.

```
Installing workloads: aspire
Skipping NuGet package signature verification.
Advertising manifest not updated. Manifest package for microsoft.net.sdk.aspire doesn't exist.
Installing workload manifest microsoft.net.sdk.android version 34.99.0-preview.3.231...
Installing workload manifest microsoft.net.sdk.ios version 17.2.9433-net9-p3...
Installing workload manifest microsoft.net.sdk.maccatalyst version 17.2.9433-net9-p3...
Installing workload manifest microsoft.net.sdk.macos version 14.2.9433-net9-p3...
Installing workload manifest microsoft.net.sdk.maui version 9.0.0-preview.3.10457...
Installing workload manifest microsoft.net.sdk.tvos version 17.2.9433-net9-p3...
Installing pack Aspire.Hosting.Sdk version 9.0.0-preview.2.24163.9...
Workload installation failed. Rolling back installed packs...
Rolling back pack Aspire.Hosting.Sdk installation...
Workload installation failed: Version 9.0.0-preview.2.24163.9 of package aspire.hosting.sdk is not found in NuGet feeds https://www.myget.org/F/aspnet-contrib/api/v3/index.json;https://api.nuget.org/v3/index.json.
```

The PR is here: https://github.com/martincostello/costellobot/pull/1077

**Comment by davidfowl** [comment]
Thanks @martincostello! We're going to re-list the packages that the workload installer depends on. We also opened an issue on the .NET SDK to support unlisted packages.

**Comment by joperezr** [comment]
Packages are now relisted, and I have validated in a brand new machine that the above commands seem to work now. @martincostello could you please try again to help us validate things are working again? Also, here is the link to the issue logged in the SDK around workloads and unlisted packages: https://github.com/dotnet/sdk/issues/40440

**Comment by joperezr** [comment]
Awesome, thanks for confirming. Closing this then, let us know if you hit any other issues, and again, thanks for the feedback!
