### ISSUE TITLE
[WebToolsE2E][Aspire]On MacOS, When running the Aspire application with http in CLI, after pasting the login token and clicking the "Log in" button, there is no response on safari browser.

### ISSUE THREAD

**Issue by v-polly** [dotnet/aspire#3942]
**REGRESSION INFO:**  Also repro on Aspire 8.0.0-preview.6.24214.1

**INSTALL STEPS**

1.Clean machine: MacOS
2.Install SDK 8.0.204(latest-released-build)
3.Install Aspire 8.0 GA workload version 8.0.0-preview.7.24224.7

**REPRO STEPS**

1.Open CMD, creating an Aspire App and enter launchSettings.json using following commands:
```
dotnet new aspire -o aspire1
cd aspire2/aspire2/aspire2.AppHost/Properties
open .
```
2.Open the launchSettings.json file and add some codes in it:
`"ASPIRE_ALLOW_UNSECURED_TRANSPORT": "true"`
![image](https://github.com/dotnet/aspire/assets/88425944/7eb59ed6-1d29-4173-b85d-7a1684b90ef1)
3.Run the project with http in CMD:
```
cd ..
dotnet run -lp http
```
4.Manually copy the url to safari browser > Paste the login token in the 'Enter token to log in' bar > click the "Log in" button.
![image](https://github.com/dotnet/aspire/assets/88425944/7eaa8ebb-5f09-4bc1-9079-fa5c0149e442)

**ACTUAL:**
After paste the token and click the "Log in" button, there is no response and can't go to aspire dashboard page.
![image](https://github.com/dotnet/aspire/assets/88425944/1986e2b4-0e56-4400-8ee4-0d96e05c7c25)

**NOTE:**
1.Run aspire project with https in CLI, it works well.
2.This issue only repro on safari browser [version 17.4.1(19618.1.15.11.14)], and if copy the url plus token  
to browser, also cannot log in.
3.This issue not repro on Edge/Google/FireFox browser.

**EXPECTED**
Can Log in succeed
![image](https://github.com/dotnet/aspire/assets/88425944/cb5a5514-6202-4004-962f-f0b2a34ac2ba)

**Comment by kvenkatrajan** [comment]
@balachir - is this the same as the internal bug on the cookie?

Does it work in chrome on mac?

**Comment by v-polly** [comment]
@kvenkatrajan This issue works well in chrome on Mac before and now.
I verified this bug on MacOS's Safari browser[version 17.4.1 (19618.1.15.11.14)].
Configuration:  aspire 8.0GA [8.0.0-preview.7.24229.8] + C# [[2.29.3](https://dev.azure.com/dnceng/internal/_build/results?buildId=2440823&view=results) main] + C# Dev Kit [[1.4.182](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=9498899&view=results) main] + SDK 8.0.204(latest-released-build). It dose not reproduce(The type token page pop-up once and can be successfully log-in onetime).
So close it.
 
(The Safari Is using the default configuration, Works fine without clearing cookie history)
![image](https://github.com/dotnet/aspire/assets/88425944/97628a0b-279a-4fef-8904-02606e36c9d0)

cc: @balachir
