### ISSUE TITLE
[WebToolsE2E][Aspire] There is an error in the code in the README file of the "Aspire.Azure.Messaging.ServiceBus", "Aspire.Azure.Storage.Blobs" and "Aspire.Azure.Storage.Queues" aspire components.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#3943]
**ACTUAL**
[Aspire.Azure.Messaging.ServiceBus](https://github.com/dotnet/aspire/tree/main/src/Components/Aspire.Azure.Messaging.ServiceBus#apphost-extensions)
![image](https://github.com/dotnet/aspire/assets/109339894/95a5a67b-c2a7-4c2c-9c9c-697c275e3775)

[Aspire.Azure.Storage.Blobs](https://github.com/dotnet/aspire/tree/main/src/Components/Aspire.Azure.Storage.Blobs#apphost-extensions)
![image](https://github.com/dotnet/aspire/assets/109339894/931dae56-217a-49b3-8bd6-3223b64b58e5)

[Aspire.Azure.Storage.Queues](https://github.com/dotnet/aspire/tree/main/src/Components/Aspire.Azure.Storage.Queues#apphost-extensions)
![image](https://github.com/dotnet/aspire/assets/109339894/a75568be-65e2-4ab0-b382-c9f7e6965d2f)

**EXPECTED**
Use the "?:" Operator
![image](https://github.com/dotnet/aspire/assets/109339894/8e6b3c96-df07-4544-8c0e-717c464d162c)

**Comment by davidfowl** [comment]
This was fixed
