### ISSUE TITLE
WithBindMount: create source directory (podman)

### ISSUE THREAD

**Issue by tmds** [dotnet/aspire#3946]
One distinction between `podman` and `docker` for bind mounts is that `docker` will create the specified path if it does not exist while `podman` will fail if it does not exist.

It would be nice if the Aspire orchestrator would create the directory when the orchestrator is `podman` so this difference doesn't bubble up and requires the user to handle it in the `AppHost`.

**Comment by davidfowl** [comment]
@karolz-ms Where do you think this logic should go?

**Comment by karolz-ms** [comment]
I agree with @tmds, having this logic in the orchestrator makes sense

**Comment by dbreshears** [comment]
This is fixed in the 0.4.0 version of DCP
