### ISSUE TITLE
GetEndpoint fails if project uses WithHttpsEndpoint

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspire#3947]
I'm experiencing issues with a local run simply not working and it's citing my use of GetEndpoint("https") pointing at back the project reference (no sample repro at the moment), but I saw this issue and wanted to jump in with my own use case that can't utilize the convenience of simply registering and injecting an HttpClient to make use of the project reference.

Especially when developing locally, I make use of localhost and the various ports the services are being dynamically assigned to for auth callabcks. This wouldn't be much of an issue except that various authentication providers require a callback URL when running on localhost that includes the port, so rather than set something statically, I thought I'd have Aspire populate the endpoint in an environment variable and pass that into the page's login link (again, not using HttpClient here), but it appears to work in some circumstances and not others. 

At least in my local repo, it's reproducible if I have the following:
```cs
var builder = DistributedApplication.CreateBuilder(args);

var api = builder.AddProject<Projects.MyApi>("myapi"); //This service starts up fine
var apiEndpoint = api.GetEndpoint("https");
api.WithEnvironment("ApiEndpoint", apiEndpoint);

var web = builder.AddProject<Projects.MyWeb>("myweb") // This service fails to launch
    .WithHttpsEndpoint()
    .WithReference(api)
    .WithEnvironment("ApiEndpoint", apiEndpoint);
var webEndpoint = web.GetEndpoint("https");
web.WithEnvironment("WebEndpoint", webEndpoint);

builder.Build().Run();
```

The error given in the service logs for MyWeb is "Failed to apply configuration value "WebEndpoint". A dependency may have failed to start". And it's true - it fails to start, but the MyApi project starts without issue.

I've been able to reproduce the issue [here](https://github.com/WhitWaldo/AspireEndpointRepro.git).

**Comment by IEvangelist** [comment]
Also, launch profiles are covered here: https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/launch-profiles

**Comment by WhitWaldo** [comment]
@davidfowl That makes a lot of sense - thank you for the explanation!
