### ISSUE TITLE
Dashboard UI issues with Safari

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#3958]
macOS Sonoma 14.4.1
Safari Version 17.4.1 (19618.1.15.11.14)
 
This is with a build from `main` with `HEAD` at 5fec81174cd305c806f66d4a532188f49bace69c.
1. The headers for the last few columns are at the bottom
2. The urls are not clickable, and neither are the View buttons.

<img width="2558" alt="Screenshot 2024-04-25 at 15 45 09" src="https://github.com/dotnet/aspire/assets/1472/0a769561-9bc4-4957-b2cc-a3d79e55f59a">

The following screenshot shows that the *cell* for the header row is too tall, and covers the other cells of the same column.

<img width="2547" alt="Screenshot 2024-04-25 at 17 22 02" src="https://github.com/dotnet/aspire/assets/1472/9c85ee60-2510-494f-9f11-a1e021209122">
Related issue: https://github.com/dotnet/aspire/issues/2272

cc @timheuer @adamint @JamesNK

**Comment by adamint** [comment]
I can repro this, it is a blocking issue for Safari users.

@vnbaaij for context 
- this is happening only for columns whose headers are not fluent-buttons
- this bug repros on _sometimes_ on the demo page
![image](https://github.com/dotnet/aspire/assets/20359921/9b7f9fc9-4b66-440b-a900-6e77f28f5c1c)
- it seems to be caused by `.col-title`'s `align-items: center` property. changing this value to `baseline` results in UI being shown as expected

**Comment by kvenkatrajan** [comment]
FYI - @danmoseley 

@adamint would the work around to add sorting work for GA? Im not sure we want to take a new fluent upgrade for GA at this time.

**Comment by vnbaaij** [comment]
Testing on Windows shows mixing the sort buttons and setting baseline for non-buttons leads to things not lining up:
![image](https://github.com/dotnet/aspire/assets/1761079/fb143336-6e96-4abb-9500-09dba7b61147)

I do not have a Safari device to test things on...

**Comment by adamint** [comment]
Clarifying that I was not suggesting baseline as a solution here, I don’t know enough yet to suggest one.

**Comment by kvenkatrajan** [comment]
@vnbaaij, @adamint, @tlmii  - thoughts on how to remediate this? We need this fixed for GA (snap date 5/2)

**Comment by vnbaaij** [comment]
@adamint I would try to get a Safari specific CSS fix in for solving this, if possible. Maybe it works/help if we target those specific headers with [-webkit-box-align](https://developer.mozilla.org/en-US/docs/Web/CSS/Webkit_Extensions#-webkit-box-align)

From MDN:
Use the [CSS flexible box layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout) with the standard [align-items](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items) property instead.

Or use the option Kay suggeste and make it a sortable column
