### ISSUE TITLE
Make container volumes visible from the dashboard

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3969]
Volume information doesn't show up anywhere in the dashboard. It should.

**Comment by kvenkatrajan** [comment]
@davidfowl Is this a UI related issue - does appmodel have this info?

**Comment by davidfowl** [comment]
Yea, the app model has the info. We need to add it to the resource server or we can tunnel it through properties in the resource server.

**Comment by davidfowl** [comment]
@leslierichardson95 @drewnoakes not critical but fit and finish currently missing from the dashboard's data model

**Comment by davidfowl** [comment]
@drewnoakes I'd like to see if we can make this fit into the dashboard and app model work. Today volumes don't show up at all and it's slightly annoying that there's no visible information in the dashboard. We can make incremental progress here by agreeing on what goes into the protocol and how it shows up in the dashboard (another table in the details view?)
