### ISSUE TITLE
Test templates aren't using latest stable test libraries

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#3975]
Out of the box NuGet shows updates available for the following libraries. We should bump to latest stable:

- [ ] Coverlet to 6.0.2
- [ ] xunit to 2.7.1
- [ ] xunit.runner.visualstudio to 2.5.8
- [ ] mstest 3.3.1
- [ ] nunit to 4.1.0
- [ ] nunit.analyzers to 4.2.0

**Comment by danmoseley** [comment]
xunit 2.9.0 and 2.8.2
mstest 3.4.3
nunit 4.1.0 and 4.2.0
