### ISSUE TITLE
Postgres/SQL Server EF components make it hard to run `dotnet ef` to create migrations, etc.

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#398]
Because the PostgreSQL and SQL Server EF components cause the app to fail on startup if the specified connection string isn't found in configuration, and that configuration is usually set by the AppHost project when running in the inner loop, you can't easily run `dotnet ef` to create a new migration, etc., as the `dotnet ef` actually runs the app in order to get a handle on the built host and container so it can interact with the `DbContext`.

We'll need to think about how to unblock this scenario.

**Comment by analogrelay** [comment]
This is basically the first issue that came up when I was playing with Aspire this weekend.

A couple ideas come to mind here:

In past projects, I've found it useful to keep "support" containers like databases running constantly in the background. That allows connecting tools like DataGrip for querying the database, and allows for running migrations, etc. It feels like it'd be useful to have a way to keep those containers running during development, even as the app you're working on is shutdown and restarted several times. [Docker Compose has "profiles"](https://docs.docker.com/compose/profiles/) which I've used for this in the past

The default behavior for AddPostgresContainer generates a random password each time. It feels like Aspire could leverage user-secrets here. In my app I generated my own db password and stored it in user secrets for the AppHost, then retrieved that value in Program.cs to pass to AddPostgresContainer. Then, I used a fixed db port number so I could connect as needed, for running migrations, using query/analysis tools, etc. It seems to me, some of that flow could be automated.

Some kind of command line tool might be useful here. The command `aspire run --reference postgres -- dotnet ef ...` command would create an ephemeral resource that references the postgres resource (thus getting env vars for it) and immediately run it.

**Comment by mitchdenny** [comment]
@DamianEdwards @davidfowl @karolz-ms ... the idea of persistent background containers is interesting. I think it would require some coordination between AppHost and DCP to do it right.

I think we'd still want containers to be emphemeral by default but with an AppHost API guesture we could mark them as being "potentially persistent". By potentially persistent, I mean if a container is marked to be retained after shutdown DCP would leave it alone, and then based on some criterial, DCP wouldn't attempt to recreate the container if it was already running.

How AppHost/DCP determines whether a container is suitable to be reused would be interesting. I'm thinking computing some hash of the definition of the container (so if password and bindings were stable it could be reused).

All that said ... @analogrelay - if your goal is to connect tools like DataGrip, you can actually set a persistent password and port for your Postgres container.

```csharp
var postgres = builder.AddPostgresContainer("postgres", password: "knockknock!", port: 1234);
```

**Comment by rcollina** [comment]
I thought I'd chime in, I've also been using persistent containers, which is something I'd love to see supported.
Developers have their own local dev env codified in a relatively simple Docker Compose file.

**Comment by analogrelay** [comment]
> All that said ... @analogrelay - if your goal is to connect tools like DataGrip, you can actually set a persistent password and port for your Postgres container.

Yep, that's what I did, though I used configuration to retrieve the password out of user-secrets.

> I should add that I think the pattern we've used in some of our samples around having a support container do database migrations is the better pattern than worrying about running dotnet ef migrate as it neatly solves the problem of how you handle migrations from app code in production.

I think you're right that using a support container like this would be a common pattern. However, I'd expect a dev to need to be able to execute _interactive commands that talk to a running database_ as part of their normal workflow. Creating migrations, applying migrations, reverting migrations are all things I've needed to do _interactively_ (as in not just "on startup") in the past when building an app. Having to start the entire app, then communicate with some kind of "admin" service feels like a significant step back in terms of functionality from how I've developed these apps in the past. Especially since these commands also tend to require building and modifying the app code.

> I think we'd still want containers to be emphemeral by default but with an AppHost API guesture we could mark them as being "potentially persistent". By potentially persistent, I mean if a container is marked to be retained after shutdown DCP would leave it alone, and then based on some criterial, DCP wouldn't attempt to recreate the container if it was already running.

To me this feels like exactly the approach I'd expect. In the past, projects I've worked on have used a `docker-compose.yml` to define the "persistent" services (Databases, caches, message busses, etc.) which stay running on developer machines even as the app itself is shutdown and restarted. Being able to express this in the AppHost (`persistent: true` or some such) would probably do the trick and meet my expectations. A persistent resource would not be stopped when the app is stopped, and on startup it'd just reuse the already-running instance **unless** there is some change in the resource that requires restarting (change of image, env vars, etc.)

**Comment by analogrelay** [comment]
(And just in case it isn't clear: Despite hitting this initial issue, this is **super cool** and y'all have built something really awesome)

**Comment by DamianEdwards** [comment]
Related #923

**Comment by peteraritchie** [comment]
Another thing to consider is when a container for the database might not be used.  I've worked in several environments where a local dbs were used in development.

**Comment by DamianEdwards** [comment]
@peteraritchie yep, in this case it can be orchestrated into the AppHost by using the methods that connect to an existing instance of your database, rather than those that start a container.

**Comment by josephaw1022** [comment]
> Not sure, we need more discussion with the ef team. Manually adding migrations is also a pain.

I agree that the process of creating and applying EF Core migrations can be streamlined. Collaborating with the EF Core team could be beneficial in developing a more automated approach. One potential solution is to centralize the DbContext and its migrations in a separate project. We could then leverage a NuGet package (which, to my knowledge, doesn't exist yet) that employs the FileSystemWatcher class ([Microsoft Documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-8.0)).

The idea would be to set up an event handler through this package that monitors changes in the DbContext classes. Upon detecting changes, it would automatically execute the dotnet ef command line interface to generate the necessary migration files. Subsequently, it would apply these migrations to update the database.

```cs

using eShopLite.CatalogDb;

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();
builder.AddNpgsqlDbContext<CatalogDbContext>("catalogdb");

// Proposed method to add a DbContext watcher
builder.AddDbContextWatcher();

var app = builder.Build();

// Utilize the DbContext watcher in a development environment
if (app.Environment.IsDevelopment())
{
    app.UseDbContextWatcher();
}

//...
```


This approach aims to automate the migration process, reducing manual intervention and potentially speeding up development cycles. However, it's crucial to carefully consider the implications of such automation, particularly in production scenarios if unchecked.

**Comment by zuraff** [comment]
Before the migrations are automated, the manual process must be streamlined.

Trying to use Postgres for the first time, I see the two problems:
1. The docker container is restarted each time the AppHost restarts. The DB looses its entire state on each restart.
2. The Postgres container uses ephemeral password and port number, and its somewhat tricky to find it out. Here is how I do it:
   * Password: in Aspire dashboard, see Containers >container of Postgres >Environment lookup POSTGRES_PASSWORD
   * Port: issue `docker ps` and lookup `PORTS` mapping.
   * The username is `postgres`
 
An option of mapping a volume with Postgres data to host's file system, as discussed in [this thread](https://stackoverflow.com/questions/57192475/postgresql-in-a-docker-container-on-windows-how-to-persist-data-to-a-local-wind) should solve #1. I do not see how to do that via the current Aspire public API, but [ContainerSpec.VolumeMounts](https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dcp/Model/Container.cs#L18) probably makes the change not too difficult.

An option of easy getting the connection string (and preferably stabilizing it across restarts) would allow to run EF migrations by passing it to [update](https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-database-update) command:
 `dotnet ef database update --connection <CONNECTION>`.

**Comment by DamianEdwards** [comment]
I don't think we want to automate running of migrations during the inner-loop. That operation has always been intended to be manually controlled by the developer such that the migration represents the set of changes intended, rather than a migration for each individual set of changes observed by something like a file watcher.

Having the `DbContext` in a separate project is a fine pattern and indeed is recommended by the EF team in certain contexts. Our eShop and eShopLite samples already do this. However this on its own doesn't improve anything with regards to running EF migrations during the dev inner-loop, as the issues are to do with connection string being available to the app's configuration, and the database itself being available, at the time the tool is run, `dotnet ef migrations create` or `dotnet ef database update`. When using .NET Aspire, the connection string info is usually passed in by the AppHost at runtime, and the database itself is likely being started as a container by the AppHost too.

Supporting containers that are run beyond a single launch/debug session could help here (#923) so that after an initial app launch, the database container would be available, but it still wouldn't solve the connection string in configuration issue.

**Comment by famda** [comment]
When I use docker compose locally, I normally use one of 2 options for migrations:

- have a separate worker project (dockerized) that I can execute using a docker profile with compose healthchecks (after the sqlserver container is ready to accept queries);

-  using a hosted service on the api (using the new features of dotnet 8 on hosted services - concurrent or not).

For local development works as a charm.

The first option is also nice when you execute on CI/CD pipelines.

**Comment by MichaelHochriegl** [comment]
I too just hit this and currently I'm not really keen on any of the workarounds I come up with. I'm not that familiar with Aspire yet, so I don't think that I can add much on how to best tackle this.

I just wanted to give this another nudge as it seems kinda important IMHO. I will sleep a night on it and maybe come up with a decent workaround for now.

**Comment by eerhardt** [comment]
Do we have any ideas how to solve this issue? Do we think #923 would solve it?

**Comment by MichaelHochriegl** [comment]
#923 is also thing that I would really like. To circumvent this issue here I came up with a rather hacky solution. I have written a `MigrationManager` app that has two modes to run in. One where it can create the migrations and one where I actually use it in my `Aspire.Host` to migrate the DB.

The project where I've implemented this is currently closed source, but I plan to get the repo up to speed and make it public shortly. I can provide a link here once I've done that if someone is interested.

**Comment by JamesNK** [comment]
I experimented with managing EF migrations and Aspire apps. It turns out the connection string isn't used when managing migrations. You can work around this limitation by adding a dummy connection string to the app with EF Core.

If you have a DB context called `db1` then in `appsettings.json`:
```cs
{
  "ConnectionStrings": {
    "db1": "Anything"
  }
}
```
This makes `dotnet ef` happy and the connection string is overriden by an environment variable with the real connection string when Aspire launches the app.

**Comment by JamesNK** [comment]
Fixed with https://github.com/dotnet/aspire/pull/2263

**Comment by davidfowl** [comment]
We need to doc the recommendation

**Comment by davidfowl** [comment]
The command line tool basically cannot be used to run migrations when using aspire.

**Comment by JamesNK** [comment]
https://github.com/dotnet/aspire/issues/2291
