### ISSUE TITLE
Https with YARP doesn't work for https and the ASP.NET Core Dev certificate

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3991]
The [ServiceDiscoveryDestinationResolver](https://github.com/dotnet/aspire/blob/104a1004681eaa9958ca74ed7d6a3aceeb31ec6c/src/Microsoft.Extensions.ServiceDiscovery.Yarp/ServiceDiscoveryDestinationResolver.cs#L87) sets the host name to the original host in local dev scenarios and this results in a `RemoteCertificateNameMismatch` since the dev cert expects localhost as the domain name (for SNI).

This can be worked around by forcing the host name to be localhost in dev scenarios but that's not a great solution:

https://github.com/dotnet/aspire/issues/836#issuecomment-2075656462

cc @ReubenBond

**Comment by ReubenBond** [comment]
Plan: special case localhost
* Change `ServiceDiscoveryDestinationResolver` logic so that if the service resolves to localhost, we *do not* set the Host property
* Add an option to opt-out and always respect YARP's Host value

In pseudocode:
```csharp
if (IsLocalhost(resolvedAddress) && !options.AlwaysUseConfigureHostValue)
{
    result.Host = null;
}
else
{
    result.Host = config.Host ?? originalUri.GetLeftPart(UriPartial.Authority);
}
```
