### ISSUE TITLE
azd infra synth fails with a project may only contain a single Aspire service and no other services at this time.

### ISSUE THREAD

**Issue by jonoabroad** [dotnet/aspire#3999]
1.  I'm opening this here as I assume it is Aspire related, but understand it may be better placed in the azd project.
2.  I have azd version 1.8.1 
3. I have a single AppHost with 3 deployable applications, `azd init` runs fine.

Raising an issue feels a bit overkill as Aspire is preview and infra synth is alpha.

**Comment by davidfowl** [comment]
Yes file this on https://github.com/Azure/azure-dev/issues

**Comment by jonoabroad** [comment]
Moving to the correct repository 
https://github.com/Azure/azure-dev/issues/3812
