### ISSUE TITLE
"Graph" not translated in 4 locales

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#4020]
@JamesNK raised this in the original issue - [#2877](https://github.com/dotnet/aspire/issues/2877) - graph still isn't translated:

![image](https://github.com/dotnet/aspire/assets/6385855/54be25af-4564-49fd-8391-3010b9eaf126)

this is true in zh-cn, fr-fr, pl-pl, pt-br (correction, not de, it's the same word there)

It's because the localizers thought it referred to the product as it's leading caps - @adamint perhaps someone on your team could add localization hints (https://aka.ms/commenting) - 2 instances in each file.

https://ceapex.visualstudio.com/CEINTL/_workitems/edit/968065
https://ceapex.visualstudio.com/CEINTL/_workitems/edit/968145 <-- when this is fixed, we need to take a change one way or another.

**Comment by joperezr** [comment]
This was fixed by https://github.com/dotnet/aspire/pull/4053
