### ISSUE TITLE
Customise Dockerfile Location

### ISSUE THREAD

**Issue by jack775544** [dotnet/aspire#4026]
## Introduction

Currently there is a method on executable resources `PublishAsDockerFile` which can optionally take build args. However in the manifest, this will always assume the Dockerfile is located at the root of the executable project. For some silly legacy reasons, I have a project where this is not the case. It would be nice if the location of the Dockerfile could be customise when this method is called.

## Proposed Solution

Add new overload for `PublishAsDockerFile`.

```cs
public static IResourceBuilder<T> PublishAsDockerFile<T>(this IResourceBuilder<T> builder, string dockerFilePath, IEnumerable<DockerBuildArg>? buildArgs = null) where T : ExecutableResource
```

**Comment by davidfowl** [comment]
I think we'll do this issue https://github.com/dotnet/aspire/issues/1852, which should solve this one as well.

**Comment by davidfowl** [comment]
Closing this as done
