### ISSUE TITLE
Unable to F5 .NET Aspire Started Application from VS

### ISSUE THREAD

**Issue by RussKie** [dotnet/aspire#4046]
Create a brand new **.NET Aspire Started Application** in VS and hit F5:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to configure dashboard resource because ASPNETCORE_URLS environment variable was not set.)
 ---> Microsoft.Extensions.Options.OptionsValidationException: Failed to configure dashboard resource because ASPNETCORE_URLS environment variable was not set.
```

https://github.com/dotnet/aspire/assets/4403806/cc0e4c85-1876-4291-9da9-5d14fc0bd69e

At the same time, if launched from cli, everything starts up as expected:

https://github.com/dotnet/aspire/assets/4403806/1f26c03e-7f60-4085-b171-d0cfb39b01ce

**Comment by davidfowl** [comment]
Can you share more details:

What version of the workload is installed?
What version of visual studio are you running?
What version of the .NET SDK are you using?

**Comment by RussKie** [comment]
I should have tought of that.

VS: latest IntPre Version 17.11.0 Preview 1.0 [34829.292.main]
Workload: latest after running `dotnet workload install aspire`

<details>
<summary>dotnet --info</summary>

```

.NET SDK:
 Version:           8.0.300-preview.24203.14
 Commit:            b7e38f457d
 Workload version:  8.0.300-manifests.e5e1222f
 MSBuild version:   17.10.0+4f6b1bb28

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300-preview.24203.14\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300-preview.24203, VS 17.11.34829.292
   Manifest Version:    8.0.0-preview.6.24214.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.6.24214.1\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  6.0.421 [C:\Program Files\dotnet\sdk]
  7.0.408 [C:\Program Files\dotnet\sdk]
  8.0.104 [C:\Program Files\dotnet\sdk]
  8.0.204 [C:\Program Files\dotnet\sdk]
  8.0.300-preview.0.24216.11 [C:\Program Files\dotnet\sdk]
  8.0.300-preview.24203.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

</details>

**Comment by RussKie** [comment]
I just tried the same project in VS Preview (Version 17.10.0 Preview 6.0), and it's all working. Looking like IntPre is busted

https://github.com/dotnet/aspire/assets/4403806/26c61d12-5389-4b08-9964-b1c7442810e8

**Comment by rmarinho** [comment]
Seems I m hitting this on VSCODE on Mac 

```
 SCEAspire git:(main) ✗ dotnet --info 
.NET SDK:
 Version:           8.0.203
 Commit:            5e1ceea679
 Workload version:  8.0.200-manifests.1f2e3bea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.203/

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.0-preview.6.24214.1/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.0.0-preview.6.24214.1/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.7/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.3
  Architecture: arm64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  6.0.420 [/usr/local/share/dotnet/sdk]
  7.0.314 [/usr/local/share/dotnet/sdk]
  7.0.315 [/usr/local/share/dotnet/sdk]
  8.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```

**Comment by kvenkatrajan** [comment]
> Seems I m hitting this on VSCODE on Mac

The .NET Aspire Preview 6 compatible version of C# dev kit and C# extensions are available in prerelease this week and are expecting this to be propagated to the release channel next Tuesday(5/6). 
![image](https://github.com/dotnet/aspire/assets/102772054/de88a136-5d85-4e58-a3db-b2b1d19ddf25)

![image](https://github.com/dotnet/aspire/assets/102772054/465c01ad-d439-46d0-a156-1259c043348c)

Please test with these versions and let u sknow if you still the issue.


CC: @tmeschter

**Comment by kvenkatrajan** [comment]
> VS: latest IntPre Version 17.11.0 Preview 1.0 [34829.292.main]

Hmm.  I have an older version of preview 1 (Version 17.11.0 Preview 1.0 [34825.264.main]) and it works fine. Can you zip up and share a copy of your solution please? CC: @BillHiebert , @vijayrkn

**Comment by tmeschter** [comment]
@rmarinho @justinyoo You're seeing the exact same `Microsoft.Extensions.Options.OptionsValidationException: Failed to configure dashboard resource because ASPNETCORE_URLS environment variable was not set.` exception in VS Code as @RussKie mentioned in the first post?

**Comment by tmeschter** [comment]
Oh, @rmarinho, @justinyoo: Any chance you're using a configuration in a launch.json to launch the app host project? If you remove the launch.json and let C# Dev Kit take care of the launch does it work?

**Comment by justinyoo** [comment]
@tmeschter I didn't use `launch.json`. Only used C# Dev Kit

**Comment by justinyoo** [comment]
> > Seems I m hitting this on VSCODE on Mac
> 
> The .NET Aspire Preview 6 compatible version of C# dev kit and C# extensions are available in prerelease this week and are expecting this to be propagated to the release channel next Tuesday(5/6). ![image](https://private-user-images.githubusercontent.com/102772054/327432487-de88a136-5d85-4e58-a3db-b2b1d19ddf25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2OTExNjUsIm5iZiI6MTcxNDY5MDg2NSwicGF0aCI6Ii8xMDI3NzIwNTQvMzI3NDMyNDg3LWRlODhhMTM2LTVkODUtNGU1OC1hM2RiLWIyYjFkMTlkZGYyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQyMzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmVkMDk5YWI1NTAzZmYwODVkOGY2MTc0NTQ4ZjU0Njk1MTRlNDQzMzQ5NmQ0NjM1ZmIxZmI0NTNkNjMxNTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.93sKzDE3K69r-3OIMi5OneAmeLA3FTw0AKBKHOG3Pho)
> 
> ![image](https://private-user-images.githubusercontent.com/102772054/327432606-465c01ad-d439-46d0-a156-1259c043348c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2OTExNjUsIm5iZiI6MTcxNDY5MDg2NSwicGF0aCI6Ii8xMDI3NzIwNTQvMzI3NDMyNjA2LTQ2NWMwMWFkLWQ0MzktNDZkMC1hMTU2LTEyNTljMDQzMzQ4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQyMzAxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWU2M2Y0NTJlZTU0ZTEwMjRjNmJkNmE4MDdmYzU2ZDA2YzU5M2NlNDllYTgyMWE5NmJkODEzMGM4ZjUwNjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p-7RxVLZysBKVdIE4OuozjfSWH3Q05-mcWETt4CPhDg)
> 
> Please test with these versions and let us know if you still the issue.
> 
> CC: @tmeschter

I switched both to the preview release, and the issue has gone away. I used to have the latest stable release version, which had the issue.

**Comment by kvenkatrajan** [comment]
@justinyoo  - Great! We will keep you posted when the prerelease bits gets to the release channel.

**Comment by RussKie** [comment]
I update to the latest VS IntPre (Version 17.11.0 Preview 1.0 [34901.157.main]), and whilst I can now do F5 and the dashboard launches the projects don't start:
![image](https://github.com/dotnet/aspire/assets/4403806/8c5c3fe4-dbf4-4d2f-898e-76fefd0520c6)

The same project from VS Pre - "just works" (c):
![image](https://github.com/dotnet/aspire/assets/4403806/2b2a959e-9993-4a30-a42a-134d8d04adc1)

**Comment by kvenkatrajan** [comment]
@RussKie  we have fix being merged in Version 17.11.0 Preview 2.0 and should be in the builds later this week. Please update the thread once you've tried it out. Thanks for your patience!

**Comment by joperezr** [comment]
Small update, we took this one through QB mode so it will make it into 17.11 Preview 1.

**Comment by joperezr** [comment]
This is done and checked in so closing the issue.
