### ISSUE TITLE
`aspire-mstest`, and `aspire-nunit` templates are broken

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4056]
Steps to reproduce:

1. `dotnet new aspire -o asp0`
2. `cd asp0; dotnet new aspire-nunit -o testProject`

It is trying to restore `Aspire.Tests1.csproj` instead of `testProject.csproj`.

![Screenshot 2024-05-01 at 19 09 48](https://github.com/dotnet/aspire/assets/1472/110aab65-de1b-4960-9915-7f4635e602e4)

Fix:
```diff
diff --git a/src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json b/src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
index 516fd9c49..31c19eb8b 100644
--- a/src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
+++ b/src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
@@ -58,7 +58,7 @@
   },
   "primaryOutputs": [
     {
-      "path": "Aspire.Tests1.csproj"
+      "path": "Aspire.Tests.1.csproj"
     }
   ],
   "postActions": [
diff --git a/src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json b/src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
index 7574e8980..a2a43d986 100644
--- a/src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
+++ b/src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
@@ -58,7 +58,7 @@
   },
   "primaryOutputs": [
     {
-      "path": "Aspire.Tests1.csproj"
+      "path": "Aspire.Tests.1.csproj"
     }
   ],
   "postActions": [
```

cc @DamianEdwards feel free to include this in your PR, or I can open a separate one.
cc @joperezr

**Comment by radical** [comment]
Another issue with the `aspire-nunit` template is that it's missing:
```csharp
using NUnit.Framework;
using NUnit.Framework.Legacy;
```

.. or maybe we should use newer api instead of `ClassicAssert`.

**Comment by DamianEdwards** [comment]
Wait that was fixed as part of the initial PR I thought?

**Comment by DamianEdwards** [comment]
Wait that was fixed as part of the initial PR I thought?

**Comment by radical** [comment]
> Wait that was fixed as part of the initial PR I thought?

Which one? This is an issue with `main`.

**Comment by DamianEdwards** [comment]
The original PR that added the NUnit test project. See https://github.com/dotnet/aspire/pull/3777#discussion_r1577034214

**Comment by DamianEdwards** [comment]
Seems it was fixed in the starter template but not the commented out code in the standalone NUnit template. I'll add that to my existing PR.

**Comment by Evangelink** [comment]
Oh so sorry I missed that!
