### ISSUE TITLE
WithEndpoint shows up on all resources and isn't constrained to IResourceWithEndpoints

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4059]
This shows an azure storage resource which doesn't support adding endpoints:

<img width="615" alt="image" src="https://github.com/dotnet/aspire/assets/95136/861d40c6-228f-4708-b92f-54bdcc439c57">

**Comment by mitchdenny** [comment]
I was going to say this is fixed .. but there is another dimension. Storage for example actually implements `IResourceWithEndpoints` because it returns an `EndpointReference` which takes an `IResourceWithEndpoints` in the constructor.

**Comment by mitchdenny** [comment]
Closing this. I think Azure Storage is a special case but I don't think we can fix this without breaking API. We would need the notion of a resource that has endpoints, but can't mutate them.
