### ISSUE TITLE
[WebToolsE2E][Aspire] Using CMD to create Aspire Starter App, restored failed with errors: "error NU1202: Package Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 is not compatible with net8.0 (.NETCoreApp,Versio n=v8.0)"

### ISSUE THREAD

**Issue by Allinylatoza** [dotnet/aspire#4062]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2.  Install VS 17.10 Preview 7 from PR 548020 [ Includes Aspire 8.0.0-preview.7.24251.11, sdk 8.0.300-preview.24203.14 ]
3. Apply NuGet dotnet-tools Feeds

**REPRO STEPS**
1. Open CMD, creating an Aspire Starter App using following commands: 
dotnet new aspire-starter -o aspirestartNew

**ACTUAL:**
Failed to restored with errors.
![image](https://github.com/dotnet/aspire/assets/156404305/8fa14b1b-b0c8-423e-a11e-76313291bae8)

Note: 
C:\Users\v-alatoza\aspirestartNew\aspirestartNew.ServiceDefaults\aspirestartNew.ServiceDefaults.csproj : error NU1202:
Package Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 is not compatible with net8.0 (.NETCoreApp,Versio
n=v8.0). Package Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 supports: net9.0 (.NETCoreApp,Version=v9
.0) [C:\Users\v-alatoza\aspirestartNew\aspirestartNew.sln]
C:\Users\v-alatoza\aspirestartNew\aspirestartNew.ApiService\aspirestartNew.ApiService.csproj : error NU1202: Package Mi
crosoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). P
ackage Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 supports: net9.0 (.NETCoreApp,Version=v9.0) [C:\Us
ers\v-alatoza\aspirestartNew\aspirestartNew.sln]

**EXPECTED**
Restore successfully.

**Comment by v-qushi** [comment]
It works on 17.10 Preview 6(Includes Aspire 8.0.0-preview.6.24214.1)

**Comment by v-sherryfan** [comment]
Verified that this issue is not reproduced on VS 17.10 Preview 7 FB [include 8.0.0-preview.7.24251.11]
