### ISSUE TITLE
Consider adding Links section when viewing traces/spans

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspire#4085]
SignalR is working on improving the Spans it creates, part of that is removing method calls from the parent span but adding a Link back to the parent span. See https://github.com/dotnet/aspnetcore/pull/55439

It would be nice to show the Link information (and potentially clickable link to go to the linked span) in the dashboard.

**Comment by davidfowl** [comment]
Dupe of https://github.com/dotnet/aspire/issues/2577

**Comment by BrennanConroy** [comment]
🙄 ugh, I even looked through issues.
