### ISSUE TITLE
[WebToolsE2E][Aspire] Add a SPA project to .NET Aspire Application project, the dropdowns of 'Structured', 'Traces' and 'Metrics' on the dashboard don't contain the SPA project.

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#4088]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 7 [rel.d17.10-34902.84] (Includes Aspire 8.0.0-preview.7.24251.11)
3. Install node.js

**REPRO STEPS**

1. New Project > .NET Aspire Application > named it 'AspireApp6' > .NET 8.0 > Create
2. Right-click Solution > Add > New Project > Choose 'React and ASP.NET Core'/'Angular and ASP.NET Core' > Check 'Enlist in .NET Aspire orchestration' > Create
4. Set .AppHost project as start app, build and F5
5. On the dashboard, open 'Structured logs' board, and click dropdown

**ACTUAL**
The dropdown doesn't contain web project.
'Structured':
![image](https://github.com/dotnet/aspire/assets/72899617/9a7ae7ad-04ce-4a2f-a769-b797b9d48c91)

'Traces':
![image](https://github.com/dotnet/aspire/assets/72899617/fe2ca10e-8793-4e6c-8dda-22cd0769597a)

'Metrics':
![image](https://github.com/dotnet/aspire/assets/72899617/6f344189-c7a9-499b-831f-2c87e275989e)

Open Program.cs of the server project, there is no code like 'builder.AddServiceDefaults();'
![image](https://github.com/dotnet/aspire/assets/72899617/4d325777-f069-4297-8f98-525e3044551a)

**Notes:**
1. This issue only repro on SPA project. There is a similar bug here [#3169](https://github.com/dotnet/aspire/issues/3169) about others project and have been fixed.
2. Manually add code 'builder.AddServiceDefaults()' in the Program.cs file of the server project, this issue will not repro.
3. On Dev17.10 P6 (Includes Aspire 8.0.0-preview.6), this issue only repro on 'Angular and ASP.NET Core' project.

**EXPECTED**
The dropdown contain web project.
'Structured':
![image](https://github.com/dotnet/aspire/assets/72899617/1b669b04-dfa6-4f71-b04a-21e69f07f175)
'Traces':
![image](https://github.com/dotnet/aspire/assets/72899617/d11701c7-a951-4727-8006-c481434b2d1d)
'Metrics':
![image](https://github.com/dotnet/aspire/assets/72899617/faa6a034-0605-4b5b-8701-010999873b59)

Open Program.cs of the server project, there is the code like 'builder.AddServiceDefaults();'
![image](https://github.com/dotnet/aspire/assets/72899617/6b554449-1036-4c02-8678-396e90c25a20)

**Comment by davidfowl** [comment]
This is by design. The front end project needs to be explicitly designed to send telemetry to the dashboard. We don't handle anything outside of .NET projects by default today.
