### ISSUE TITLE
Allow specifying service (interface) and implementation when calling AddNpgsqlDbContext

### ISSUE THREAD

**Issue by nwoolls** [dotnet/aspire#4114]
Currently the method `AddNpgsqlDbContext` only allows for a concrete context type to be specified. This makes it difficult to use with both unit testing and Clean Architecture without jumping through a few additional hoops.

It would be nice of there was an overload to `AddNpgsqlDbContext<TContext>()` with the signature `AddNpgsqlDbContext<TContextService, TContextImplementation>()` as there is for most of the existing EF extension methods for DI.

**Comment by sebastienros** [comment]
Thak you for your contribution. [We have decided](https://github.com/dotnet/aspire/issues/1403) that we would only support these two methods right now, the one with common defaults, and the one that can be extended. As discussed in the linked PR the recommendation is to create your own extension method or try to add it to the https://github.com/aspirant-project/aspirant project.
