### ISSUE TITLE
Can visual studio wake up docker from resource saver mode?

### ISSUE THREAD

**Issue by mip1983** [dotnet/aspire#4120]
When I've left my machine a while or woken it up, it can resume with docker in resource saver mode in the background. When I go to debug my aspire project, I get this error:

```
System.AggregateException: 'One or more errors occurred. (Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.7.24251.11\tools\dcp.exe info returned non-zero exit code -1)'

Inner Exception
InvalidOperationException: Command C:\Program Files\dotnet\packs\Aspire.Hosting.Orchestration.win-x64\8.0.0-preview.7.24251.11\tools\dcp.exe info returned non-zero exit code -1
```

If I go into docker desktop and hit resume, it starts working fine. Is it possible for visual studio/aspire to automatically detect if docker is asleep and wake it up by itself?

**Comment by karolz-ms** [comment]
@mip1983 thank you for letting us know about this issue. We have been working with Docker to fix hangs upon resumption from resource saver state here: https://github.com/dotnet/aspire/issues/2075 Unfortunately, based on what Docker people told us, there is no way for Visual Studio to wake Docker up if it locks up in resource saver mode. That lock-up should simply never happen.

Separately I have opened a bug to make the error message more actionable if we detect that Docker CLI is unresponsive: https://github.com/dotnet/aspire/issues/4691

Based on these two issues, I think we have covered what needs fixing. I will close this issue. Thanks again for helping us make Aspire better.
