### ISSUE TITLE
Visual Studio Integration breaks if Schema Store is down

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#4121]
After upgrading my project to Preview 7, I'm getting the following errors if trying to run the project in Visual Studio
```
Severity    Code    Description    Project    File    Line    Suppression State
Error (active)        The remote server returned an error: (503) Server Unavailable.    MyApp.Aspire.AppHost    C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\WebTools.Aspire\Microsoft.WebTools.Aspire.targets    47
Error (active)        The operation has timed out    MyApp.Aspire.UnitTests    C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VisualStudio\WebTools.Aspire\Microsoft.WebTools.Aspire.targets    47   
```
Looking at fiddler, its seems that https://json.schemastore.org/appsettings.json is the url that's returning a 503.  This error also seems to horribly break IntelliSense- as it stops being able to find any of the types in the Aspire packages.

![image](https://github.com/dotnet/aspire/assets/289860/51193f19-7dac-436e-806b-6b00b665466f)

This is a Visual Studio specific issue - both the `dotnet run` and VS Code can run & debug the project without issue.

**Comment by timheuer** [comment]
@vijayrkn FYI -- I know we have internal tracking on this one as well.

**Comment by mitchdenny** [comment]
I believe this was fixed before GA.

**Comment by davidfowl** [comment]
@vijayrkn can you confirm?
