### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by pmdot** [dotnet/aspire#4122]
Hey everybody!

About some renaming performed in preview 7. By https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members - DisableHealthChecks, DisableMetrics, DisableRetry, DisableTracing **should be given noun phrase or adjective names** as is mentioned. So the previous naming of these was the right one i think. Wasn't it? Disable as a word, is a verb. They should be transformed into methods, as DisableHealthChecks() whit internal business logic. Or transformed into non verbal word or phrase.

Greetings,
Petar

**Comment by danmoseley** [comment]
@sebastienros  could you share why in API review we decided to change these to negative sense (eg Tracing to DisableTracing)? Negative sense can be harder to grok (ie DisableTracing=true is little harder to read than Tracing=false)

It seems to me though that if they are negative sense then indeed according to the API guidelines they should be something like TracingDisabled.

@eerhardt

**Comment by mitchdenny** [comment]
This tracks with my understanding of the conversation. The change was very deliberate

**Comment by danmoseley** [comment]
Sounds good. 

Given we can not really change this now (last build complete) I'm going to close this. @pmdot, appreciate the call out though.
