### ISSUE TITLE
Finished processes always show with a warning

### ISSUE THREAD

**Issue by wmeints** [dotnet/aspire#4127]
When a process finishes, the dashboard shows it with a warning. But I believe this to be incorrect. When a process exits with code 0 it's successfully completed. So the dashboard shouldn't display a warning at all. 

I am running several processes to migrate databases in Python and I only want to see a warning when the migration tool fails.

Is it possible to change this behavior?

**Comment by davidfowl** [comment]
I agree this behavior is strange. We can fix it post GA. 

cc @kvenkatrajan

**Comment by DamianEdwards** [comment]
Perhaps we can use the regular variant (non-filled) of the same checkmark icon and with the underline, like this? 
![image](https://github.com/dotnet/aspire/assets/249088/fbd2120f-3d73-4477-b293-d10c09944044)

**Comment by pierrebelin** [comment]
Hello ! Can I take this one as my first issue on Aspire ?

**Comment by DamianEdwards** [comment]
@pierrebelin You just need to have a resource added that will run to completion, e.g. just calling `dotnet --version`

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddExecutable("dotnet-version", "dotnet", Environment.CurrentDirectory, "--version");

builder.Build().Run();
```

![image](https://github.com/dotnet/aspire/assets/249088/af67bedb-0e91-4741-94e9-a9d9eb46fc79)

**Comment by pierrebelin** [comment]
Appreciated @DamianEdwards ! I've created the PR related to this issue with the icon you named

**Comment by drewnoakes** [comment]
Thanks for fixing this @pierrebelin. Choosing this issue as completed.
