### ISSUE TITLE
Dashboard thinks my service is finished while it's not

### ISSUE THREAD

**Issue by wmeints** [dotnet/aspire#4129]
I'm running two python projects connected to the dashboard. One is a batch process that finishes. The other is a Flask service that's supposed to keep running. The dashboard doesn't think so.

![image](https://github.com/dotnet/aspire/assets/1550763/e402fa44-75d5-419a-b9e6-056bb1f03464)

I checked the logs and manually opened the URL for the flask service. It works normally and I can see traces flowing into the dashboard. I'm not sure what's going on here, but it looks like the dashboard is confusing two resources. 

Note: The executable is the same for both resources, however the arguments are different because while I'm running `opentelemetry-instrument` in both cases, I'm using it to instrument two different executables.

**Comment by davidfowl** [comment]
@wmeints Are you still seeing this?

**Comment by karolz-ms** [comment]
We made some fixes in this area that will ship in the next Aspire release (8.1). If this continues to be a problem for 8.1, please open a new issue--TIA!
