### ISSUE TITLE
[WebToolsE2E][Aspire] With SDK 8.0.300 + Aspire 8.0 GA, dotnet new aspire-starter does not work due to manifest provider returned a duplicate manifest ID 'microsoft.net.sdk.android'.

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#4145]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU

1. Install SDK 8.0.300
    - Apply feed for SDK 8.0.300
    
1. Install Aspire 8.0 GA

   - Apply the "darc-pub-dotnet-aspire" feed for Aspire 8.0 GA
   
1. Install cred helper (run from Windows PowerShell admin prompt) 

    `iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) }" `

**REPRO STEPS**

1. Run `dotnet --info`  -- works fine
 
    ![image](https://github.com/dotnet/aspire/assets/78580199/fd0c4901-f1c9-4b0a-8da8-a3294cf8f9b4)

1. Run `dotnet workload list`

    ![image](https://github.com/dotnet/aspire/assets/78580199/b807e2f7-04e9-487b-9f3d-d50bc4386fee)

1. Run `dotnet new aspire-starter -o Aspire-StarterApp01`

 
**ACTUAL**
Template creation failed

![image](https://github.com/dotnet/aspire/assets/78580199/f1ea57b1-a435-47e9-a385-61f18a0e6f11)

**EXPECTED**
Template creation should succeed

**Comment by v-elenafeng** [comment]
This issue can also be reproduced with a clean install of VS 17.10 GA (with Aspire 8.0 GA)+ Web workload when creating a new template using the CLI, but works fine using VS.

**Comment by balachir** [comment]
@joperezr are we missing an additional feed? It seems that 'dotnet new aspire-starter' doesn't work using CLI with above steps.

**Comment by balachir** [comment]
The error seems similar to an issue that was reported earlier as well - internal Bug 2048871.

**Comment by balachir** [comment]
Elena and I investigated today and it seems like a possible feed permissions issue. But still, we have two machines that Elena and I setup - she can still reproduce the issue on her machine and I cannot reproduce the issue on my machine. We'll continue doing more investigation on Monday.

**Comment by v-elenafeng** [comment]
I installed a new machine today and can still reproduce this issue, it happens randomly and the failure rate is about 50%.

![image](https://github.com/dotnet/aspire/assets/78580199/9249ef68-b5d2-4bb8-a547-b2eee88d5288)

**Comment by balachir** [comment]
@joperezr @marcpopMSFT with the correct feeds applied, we seem to still run into this issue about 50% of the time, even within the same Command Prompt session as you can see in Elena's screenshot. Can you investigate, please?

**Comment by marcpopMSFT** [comment]
To summarize the investigation, there appears to be a parallelism issue within the template engine that affects workload related templates. Daniel is still digging into possible fixes but the short-term workaround (besides the customer just trying again) is to have the aspire templates remove the workload constraint. It should not be necessary within templates provided by workloads and appears to be causing duplicate resolution of the same workload.  That's our recommendation for 8.0.1 version of the aspire workload.
https://github.com/dotnet/aspire/blob/main/src/Aspire.ProjectTemplates/templates/aspire-apphost/.template.config/template.json#L26-L31

**Comment by dsplaisted** [comment]
Here are the details that I found in my investigation: https://github.com/dotnet/templating/issues/7946#issuecomment-2108853692

**Comment by v-elenafeng** [comment]
Close this issue as it was fixed both on Aspire 8.0.1 and 8.1 Preview 1.
