### ISSUE TITLE
Plotly JS used by dashboard is out of date by 10 months

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#4148]
The dashboard is currently using Plotly JS version [2.26.0 which was released in Aug 2023](https://github.com/plotly/plotly.js/releases/tag/v2.26.0). We should update it to the latest version ([2.32.0](https://github.com/plotly/plotly.js/releases/tag/v2.32.0) at time of creating this issue) and determine how to automate keeping it up to date.

**Comment by martincostello** [comment]
I have an action that may be useful to you if you consumed it from a CDN: https://github.com/martincostello/update-static-assets

I use it to keep stuff like swagger-ui and font-awesome up to date: https://github.com/martincostello/website/pull/1805
