### ISSUE TITLE
Dashboard should configure response compression & caching for static assets

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#4150]
The dashboard currently doesn't configure compression or caching headers for the static assets it delivers, including libraries like plotly (which is [3.5 MB](https://github.com/dotnet/aspire/issues/4149)).

We should configure the response compression middleware to ensure that at least static assets are compressed (and potentially the HTML output too), and investigate setting cache headers for static assets with versioned paths to help improve the client-side experience.

**Comment by danmoseley** [comment]
Just curious is this only noticeable in the case where the dashboard is on a different machine?

**Comment by DamianEdwards** [comment]
> Just curious is this only noticeable in the case where the dashboard is on a different machine?

From a UX perspective, most likely.

**Comment by DamianEdwards** [comment]
TBC the dashboard is configuring the `no-cache` header for static assets, which forces the browser to honor the E-tag and/or `Last-Modified` headers sent, which usually results in 304 Not Modified responses for the static assets, so that's less of an issue than I originally thought.
