### ISSUE TITLE
[AzureTools][Aspire] The description of Aspire is ".NET Aspire SDK (Preview)" instead of ".NET Aspire SDK" when executing "dotnet workload search" command

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#4156]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.11.0 Preview 1.0 [34909.67.d17.11]
**Aspire Version:** 8.0.0
Apply NuGet Feeds

**REPRO STEPS:**

1. Install VS 17.11.0 Preview 1.0 [34909.67.d17.11].
2. Run `dotnet workload search` in the command prompt.

**Expect:**
The description of Aspire is ".NET Aspire SDK".

**Actual:**
The description of Aspire is ".NET Aspire SDK (Preview)".
![image](https://github.com/dotnet/aspire/assets/62053665/f0782c1b-eb41-4c39-9a6f-078ce60a8d22)

**Comment by balachir** [comment]
@joperezr is this string in Aspire or should the issue move to the SDK team? Including @marcpopMSFT and @dsplaisted for awareness.

**Comment by joperezr** [comment]
Great find, this was missed when doing the branding changes to remove Preview. We'll have to fix this on 8.1.

**Comment by v-mengwe** [comment]
It's fixed.
![image](https://github.com/dotnet/aspire/assets/62053665/f76bf2a6-b306-4cc1-8fb4-01194450d8ce)
