### ISSUE TITLE
Install aspire workload Fail

### ISSUE THREAD

**Issue by skyDuanXianBing** [dotnet/aspire#4157]
when  I want to install aspire workload,it try to install  Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.Msi.x64 (8.0.21),which can't find in nuget,but nuget have  Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.Msi.x64 (8.0.21) this package,why ?
![image](https://github.com/dotnet/aspire/assets/164180639/60f509e2-21c1-4963-94a3-fb2b87b17d8c)

**Comment by skyDuanXianBing** [comment]
why install aspire wanting to install Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.Msi.x64 (8.0.21) package?...

**Comment by davidfowl** [comment]
What .NET SDK version are you using?

**Comment by skyDuanXianBing** [comment]
I fix that I change .net 8.0 version to 8.0.204 to fix this problem
