### ISSUE TITLE
[WebToolsE2E][Aspire] Navigate to any module on dashboard, the color of the module icon does not change to purple.

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#4164]
**REGRESSION INFO**: Worked in Aspire 8.0.0, such as: Dev17.10 GA, Dev17.11 P1 and Dev17.11 P2

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU

1. Install SDK 8.0.302
1. Install Aspire 8.1 (8.1.0-preview.1.24259.4)

    - Apply feeds: dotnet8feed 

**REPRO STEPS**
1. New Project > .NET Aspire Starter Application > name it 'AspireApp1' >Framework：.NET 8.0 > Create
2. Build and F5

**ACTUAL** 
Move to any module on dashboard, the color of the module icon does not change to purple
![Animation](https://github.com/dotnet/aspire/assets/72899617/9ee0b022-a475-429b-b39d-5b5771763f75)

**EXPECTED** 
Move to any module, the color of the module icon changes to purple
![image](https://github.com/dotnet/aspire/assets/72899617/646c2b6d-0265-4a21-91fc-bb63742c3947)

**Comment by Rita003** [comment]
@kvenkatrajan This issue also repro on .NET Aspire 8.0.2, it doesn't repro on .NET Aspire 8.0.1. Is this an intentional change?

**Comment by leslierichardson95** [comment]
@vnbaaij do you know if this issue is based on a change or regression in the underlying component?

**Comment by vnbaaij** [comment]
I don't think so but need to check to make sure. Will take a look tomorrow.

**Comment by radical** [comment]
@kvenkatrajan Are we tracking a list of automated dashboard tests that would be useful to add? This might be a good candidate too.

**Comment by vnbaaij** [comment]
The active AppBar item was not getting the accent color set. Could not find how/when that was changed, but I fixed it for v4.9:
![image](https://github.com/dotnet/aspire/assets/1761079/002a6c8d-fa7e-4fb5-9984-44291bad4b87)

**Comment by vnbaaij** [comment]
An update to Fluent UI Blazor library v4.9.0 needs to be done to have the mentioned PR be applied

**Comment by v-bennettyue** [comment]
This issue not repro on 17.10.5 + Aspire 8.1.1, so close it
