### ISSUE TITLE
Arguments are passed/parsed differently to hosted apps depending if app host started with `dotnet run` or from Visual Studio project system

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/aspire#4165]
**Edited**: it turns out this is not Windows vs macOS, it is Visual Studio run vs `dotnet run`

See example projects here: https://github.com/frankbuckley/aspire-test

On Windows, run AspireTest.AppHost from Visual Studio (or, on Mac use solution add-in to Visual Studio code to run project). In logs:

```
args[0]: --option
args[1]: an
args[2]: argument
args[3]: --combined
args[4]: an argument
args[5]: --option
args[6]: an argument
```

On Windows or macOS, run using AspireTest.AppHost `dotnet run`. In logs:

```
args[0]: --option
args[1]: an argument
args[2]: --combined "an argument"
args[3]: --option
args[4]: "an argument"
```

![image](https://github.com/dotnet/aspire/assets/5655810/67506736-ae23-4fc9-8fc0-bac56a4b9a21)

**Comment by davidfowl** [comment]
cc @eerhardt

**Comment by davidfowl** [comment]
cc @BillHiebert @karolz-ms This is part of speccing launch profile processing.

**Comment by karolz-ms** [comment]
@davidfowl this is a very old bug. The repro repo is no longer available.

@frankbuckley is this problem still happening for you? Sorry for very long delay. I believe we fixed some issues in this space before Aspire went GA

**Comment by frankbuckley** [comment]
> @davidfowl this is a very old bug. The repro repo is no longer available.
> 
> @frankbuckley is this problem still happening for you? Sorry for very long delay. I believe we fixed some issues in this space before Aspire went GA

@karolz-ms - not sure - seem to recall we worked around - will see if I can resurrect repro and check...

**Comment by karolz-ms** [comment]
Thank you @frankbuckley ! We will take a look.

@BillHiebert FYI. I need to double-check, it might be that I give you wrong arguments over the wire, or maybe you are not parsing them right. The `dotnet run` behavior seems correct to me.

**Comment by karolz-ms** [comment]
@BillHiebert @tlmii 

I debugged DCP and looked at what the arguments look like in the run session request sent from DCP to the IDE. This is what I found:

```json
"args":["--option","an argument","--combined \"an argument\"","--option","\"an argument\""]
```

To me it looks correct. So looks like the IDE has trouble interpreting this payload. I am going to remove the orchestrator tag from the issue for now but feel free to re-add it if it turns out DCP is to blame after all.

@vijayrkn FYI

**Comment by BillHiebert** [comment]
@karolz-ms I'll take a look

**Comment by BillHiebert** [comment]
I think VS is working correctly. VS takes the arguments and concatenates them with a space so in the example:
 
[ "--option", "an argument", "--combined \"an argument\"", "--option", "\"an argument\"" ]
 
The command line for the process maps to: --options an argument --combined "an argument" --option "an argument"
 
which the OS will convert to:
arg[0] --option
arg[1] an
arg[2] argument
arg[3] --combined
arg[4] an argument
arg[5] --option
arg[6] an argument
 
 You get the same running that command line from a console app.  From the consuming projects perspective, it seems right.

**Comment by vijayrkn** [comment]
> You get the same running that command line from a console app. I think to match the DCP I need to quote the arguments. I will play that.

This part of the VS fix is checked-in. Should be available in the next preview version of VS. Resolving the issue.
