### ISSUE TITLE
Change the name of the aspire template to use 'App' instead of 'Applicaton'

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/aspire#4178]
We should use 'App' instead of 'Application' to be consistent in Visual Studio.

![image](https://github.com/dotnet/aspire/assets/1283154/11a4e689-3b5f-4151-94ff-c05c61991060)

cc @vijayrkn @BillHiebert @bradygaster

**Comment by vijayrkn** [comment]
https://github.com/dotnet/aspire/blob/e8b77e626befac92a5d51a0dfb24ab56f00aa5ba/src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json#L14

**Comment by davidfowl** [comment]
This was done
