### ISSUE TITLE
[WebToolsE2E][Aspire] When installing vs from PR (9.0 insertion), if 9.0 is checked, the Aspire project cannot be created using the CLI.

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#4182]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
1. Install VS 17.11 Preview 2 [buildId=9577192] from PR 525045 pre-released build.

    - Web workload
    - Includes Aspire 8.0.0
    - Check 9.0 runtime
    - Check .NET SDK (preview)

1. Apply the "darc-pub-dotnet-aspire" and SDK 9.0 feed 

**REPRO STEPS**
1. Open CMD, creating an Aspire Starter App using following commands:
`dotnet new aspire-starter -o aspirestarter`

**ACTUAL**
![image](https://github.com/dotnet/aspire/assets/72899617/22acd044-3360-4fd7-965a-5abb500af04f)
Failed to instatiate template '.NET Aspire Starter Application', the following constraints are not met:
   workload: The constraint 'workload' failed to initialize: Could not find workload 'microsoft-net-runtime-android-net8' extended by workload 'android' in manifest 'microsoft.net.sdk.android' [C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.sdk.android\34.99.0-preview.4.261\WorkloadManifest.json]

To run the template anyway, use '--force' option:
   dotnet new aspire-starter -o aspirestarter --force

For details on the exit code, refer to https://aka.ms/templating-exit-codes#100

**Note**: It can be created successfully by VS.

**EXPECTED**
Created successfully
![image](https://github.com/dotnet/aspire/assets/72899617/820c3211-7475-4104-9863-3eb71c799da0)

**Comment by v-elenafeng** [comment]
Fixed in the latest build [buildId=9819549] of the PR 525045.
