### ISSUE TITLE
[WebToolsE2E][Aspire] When installing VS from PR (9.0 insertion), then running the "dotnet workload update" command fails: "Could not find workload 'microsoft-net-runtime-android-net8..."

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#4196]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install VS 17.11 Preview 2 [buildId=9577192] from PR 525045 pre-released build.

    - Web workload
    - Includes Aspire 8.0.0
    - Check 9.0 runtime
    - Check .NET SDK (preview)
    - Apply the "darc-pub-dotnet-aspire" and SDK 9.0 feed

**REPRO STEPS**

1. Open CMD and run the following commands:
`dotnet workload update`

Note: If not check 9.0 runtime and .NET SDK (preview), this issue will not repro.

**ACTUAL**
![image](https://github.com/dotnet/aspire/assets/72899617/388ff19f-b32b-4992-81a7-cb8814cc120d)
No workloads installed for this feature band. To update workloads installed with earlier SDK versions, include the --from-previous-sdk option.
Workload update failed: Could not find workload 'microsoft-net-runtime-android-net8' extended by workload 'android' in manifest 'microsoft.net.sdk.android' [C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.4\microsoft.net.sdk.android\34.99.0-preview.4.261\WorkloadManifest.json]

**Comment by v-elenafeng** [comment]
Fixed in the latest build [buildId=9819549] of the PR 525045.
