### ISSUE TITLE
Support specifying a path for custom endpoints

### ISSUE THREAD

**Issue by cfbao** [dotnet/aspire#4199]
Some apps' best entrypoint URL isn't the root path, but some path below that, e.g. http://localhost:12345/swagger.

If using `AddProject`, we can now get the Aspire dashboard to show a custom path by specifying appropriate properties in launchSettings.json.
However, for executable resources with custom endpoints (added using [WithEndpoint](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.resourcebuilderextensions.withendpoint?view=dotnet-aspire-8.0)), there's no way for the dashboard to show a custom path, because [EndpointAnnotation](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.applicationmodel.endpointannotation?view=dotnet-aspire-8.0) doesn't support that.

It'd be nice to support specifying a path for custom endpoints, and have the dashboard display that to be more helpful.

**Comment by SteWilson** [comment]
This would be useful when configuring the endpoint for the cosmos emulator when running locally. I have to keep adding /_explorer/index.html

**Comment by davidfowl** [comment]
Closing this as dupe of https://github.com/dotnet/aspire/issues/5209
