### ISSUE TITLE
Got " Hosting failed to start" error in "Quickstart: Build your first .NET Aspire app"

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/aspire#4208]
After running `dotnet run --project AspireSample/AspireSample.AppHost`, I got the following error:

<img width="936" alt="image" src="https://github.com/dotnet/docs-aspire/assets/17007651/ba8f37b5-d5e4-4330-9e86-ca31ec6c6ebf">

**Comment by davidfowl** [comment]
@nicholasyin Are you using the latest version?

**Comment by nicholasyin** [comment]
> @nicholasyin Are you using the latest version?

By the time of my reply yes I was using the latest version. Now I'm not sure. I've quit trying aspire on Mac already.

**Comment by davidfowl** [comment]
Is this issue still relevant? Should we close it?
