### ISSUE TITLE
Dashboard doesn't pick up launchUrl when specifying a custom endpoint

### ISSUE THREAD

**Issue by davidebbo** [dotnet/aspire#4212]
Steps:
- Start with a new Aspire starter solution
- In the AppService's LaunchSettings.json, remove all the `applicationUrl` entries
- In the AppHost, manually add an endpoint, e.g.

```c#
var apiService = builder.AddProject<Projects.AspireApp2_ApiService>("apiservice")
    .WithEndpoint(name: "http", scheme: "http", port: 5007);
```

Result:
The API Service endpoint shows up as `http://localhost:5007/` in the dashboard, instead of the expected `http://localhost:5007/weatherforecast`.

So it seems that if you don't use the profile `applicationUrl`, the whole profile ends up getting ignored, even though conceptually, the start url and the endpoint are somewhat orthogonal.

**Comment by davidebbo** [comment]
Ok, so I take it this is by design, per #2548?

**Comment by davidebbo** [comment]
Though I could see either behavior being valid depending on the situation. In general, adding an endpoint via code does *not* cause the entire launch profile to be ignored, since things like `environmentVariables` are still applied.

So it comes down to whether `launchUrl` should be viewed as global to the profile, or specific to the endpoints defined in the profile.

So let's say you do want a different launch URL in the endpoint to define via code. Is there a way to do this? e.g. it would be something like this (which doesn't exist):

```c#
var apiService = builder.AddProject<Projects.AspireApp2_ApiService>("apiservice")
    .WithEndpoint(name: "http", scheme: "http", port: 5007, launchUrl: "weatherforecast");
```

Anyway, fairly minor issue in the grand order of things.

/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
You're correct @davidebbo (nice to talk to you again 😄) that this is currently by design. The `launchUrl` stuff is kinda special right now and I agree it would be nice if it were properly modeled such that it could be set per endpoint rather than be a special-case thing for endpoints from launch profiles.

**Comment by davidebbo** [comment]
Yep, makes sense! Closing this for the time being.

And yes, nice connecting again, it's been a while! I was a matter of time before the .NET world pulled me back in 😆.
