### ISSUE TITLE
[AzureTools][Aspire] An error occurs in the command prompt when clicking "Console" tab in the left again or more times 

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#4213]
**REGRESSION INFO:** Aspire 8.0.0 also reproduces

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10.0 [34916.146.d17.10]
**Aspire Version:** 8.0.1
Apply NuGet Feeds

**REPRO STEPS:**

1. Create a new Aspire starter App -> F5 in VS.
2. Click "Console" tab in the left -> Select apiservice resource -> Click "Resource" tab -> Click "View" under 'Logs' for apiservice project -> The webpage automatically jumps to 'Console logs'. 
3. Click "Console" tab in the left again or more times. 

**Expect:**
No error occurs in the command prompt.

**Actual:**
An error occurs in the command prompt.
![Actual](https://github.com/dotnet/aspire/assets/62053665/ebfe368c-1de2-4753-a91d-5b064a732310)

**More Info:**
1. This issue **doesn't reproduce** for the dashboard running this project using CLI.
2. This issue is unstable, you can F5 again when it does not reproduce.

**Comment by karolz-ms** [comment]
We had an internal thread about this issue. @JamesNK commented:

> The console logs page starts a gRPC call to the host. That call streams logs to the dashboard. The error occurs because rapidly clicking on the console logs page will start and then immediately cancel that call. That then causes a server error if timing is right.

Removing the `area-orchestrator` label because the issue is not related to DCP.

**Comment by leslierichardson95** [comment]
@v-mengwe checking in, are you still experiencing this issue?

**Comment by davidfowl** [comment]
This is a dashboard issue, we should be making these errors debug level.

**Comment by v-mengwe** [comment]
> @v-mengwe checking in, are you still experiencing this issue?

This issue still reproduces on Aspire 8.2.0.
![image](https://github.com/user-attachments/assets/0fc42cae-19f7-43d8-97e1-29168e2a8779)

**Comment by JamesNK** [comment]
Requires change in grpc-dotnet: https://github.com/grpc/grpc-dotnet/pull/2527. 

Blocked until a grpc-dotnet version with this fix is available.

**Comment by adamint** [comment]
@JamesNK is there any update on this?

**Comment by JamesNK** [comment]
No

**Comment by v-mengwe** [comment]
Verified on the VS 17.13.0 Preview 2.0 [35523.93.main] with Aspire 9.1.0-preview.1.24574.1, this issue doesn't reproduce.
