### ISSUE TITLE
Standalone Mode - Data being aggregated under a single application service name

### ISSUE THREAD

**Issue by bobby-driggs** [dotnet/aspire#4217]
I am using the Aspire Dashboard via Docker "latest" (Aspire version: 8.0.0-preview.7.24251.11+4952a6e837599afd6bc710bd6c010a2eacd65763) in stand alone mode for local development.

I have two separate applications ("App1" and "App2") configured in Program.cs identically like so, where the only deviation is the `serviceName` argument for the `.AddService` call: 

```
        var otelResourceBuilder = ResourceBuilder
            .CreateEmpty()
            .AddTelemetrySdk()
            .AddEnvironmentVariableDetector()
            .AddService(
                serviceName: "App1", // "App2" on the second app
                serviceInstanceId: Environment.MachineName);

        builder.Logging.AddOpenTelemetry(uu =>
        {
            uu.SetResourceBuilder(otelResourceBuilder);

               // ... options omitted
        });
        
        builder.Services.AddOpenTelemetry()
            .ConfigureResource(options =>
            {
                options = otelResourceBuilder;
            })
            .WithMetrics(uu =>
            {
               // ... registrations omitted
                uu.SetResourceBuilder(otelResourceBuilder);
            })
            .WithTracing(uu =>
            {
               // ... registrations omitted
                uu.SetResourceBuilder(otelResourceBuilder);
            });
```

I was expecting that when i run both applications at the same time, I could use the service drop down, and select each app individually to see their respective tracing and logging and metrics, etc.

However, I believe there is some bug that is aggregating everything under the first application's service name: In this screen shot, App2 was the first to hit the Aspire Dashboard, and you can see that when App1 started later, their logs were also grouped under App2's resource.

![image](https://github.com/dotnet/aspire/assets/9810149/fedc8fec-a79e-4ff3-bd6a-d1c114a8fcd7)

At first I thought it was an issue on my side, but after double and triple checking the service names, restarting the docker container, waiting 15+ minutes thinking the logs would switch, everything gets stuck under the first resource. 

To sanity check myself, I pulled down the Jaeger all-in-one docker container, and ran the same app, and they appropiately broke out the services as I would have expected to:

![image](https://github.com/dotnet/aspire/assets/9810149/4038b174-bc04-43f1-a441-9ec9daf6c37c)

Is this actually a bug with the Aspire Dashboard or am I just incorrectly registering the service?

**Comment by SaifAqqad** [comment]
I found the cause of this issue: [TelemetryRepository.cs L143 - L179](https://github.com/dotnet/aspire/blob/6d41a31700c10250f5d33154c9556d1f52b5a2cb/src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs#L143-L179)

It seems the dashboard differentiates apps based on the instance id (`service.instance.id`) first and then the service name, which means if you're setting the instance id to something related to the running machine (like `Environment.MachineName`) it will cause the dashboard to treat all apps as the same service.

While this does make sense in a cloud context, I think it might be worth it to change this behavior when running in standalone mode.

**Comment by SaifAqqad** [comment]
@niltor The dashboard treats apps with same `serviceInstanceId` as the same service and it uses the `serviceName` to group different instances of the same app under one service

If you add the service name to the Instance id it should work as expected
```csharp
var resource = ResourceBuilder.CreateDefault()
    .AddService(serviceName: serviceName, serviceInstanceId: $"{serviceName}-{Environment.MachineName}");
```

**Comment by bobby-driggs** [comment]
> @niltor The dashboard treats apps with same `serviceInstanceId` as the same service and it uses the `serviceName` to group different instances of the same app under one service
> 
> If you add the service name to the Instance id it should work as expected
> 
> ```cs
> var resource = ResourceBuilder.CreateDefault()
>     .AddService(serviceName: serviceName, serviceInstanceId: $"{serviceName}-{Environment.MachineName}");
> ```

Good investigating @SaifAqqad .

Looking at the ResourceSelect component github.com/dotnet/aspire/blob/main/src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor

It is clear that it is using the instance id the list. The serviceName _does_ become a part of the replica set name however.

I modifed my code like so:

```
        var otelResourceBuilder = ResourceBuilder
            .CreateEmpty()
            .AddTelemetrySdk()
            .AddEnvironmentVariableDetector()
            .AddService(
                serviceName: "App1", // or "App2"
                serviceInstanceId: Guid.NewGuid().ToString());
```

Started and stopped both apps twice, and got this: 
![image](https://github.com/dotnet/aspire/assets/9810149/ac343cec-be71-4669-b283-116dc8418957)

If you start and stop one of the services, and only run the second service once, you get this:

![image](https://github.com/dotnet/aspire/assets/9810149/e10a64eb-96bb-4935-be6b-bbbf692f78ad)

Definately something magical is happening behind the scenes to determine if it should show the instance id (if there is more than one) or the service name. 

---

All that said, since my use case is very local, (in prod we will be using DataDog), ill probably just take your approach of concatenating the machine name to the service name for the instance id

**Comment by SaifAqqad** [comment]
>Although we can change the configuration to distinguish them, the current behavior is counterintuitive.
>
>The current behavior has shown that serviceName cannot distinguish applications (when instanceId is the same), which is problematic in itself.

Although I agree that in the case of the aspire dashboard (which is intended to be used during local development) it makes sense to distinguish between services regardless of the `serviceInstanceId` (which is usually set to the machine name by most people).

The way it's implemented in the dashboard is based on how it's specified in the [OpenTelemtery spec](https://opentelemetry.io/docs/specs/semconv/attributes-registry/service/#service-attributes) which is that the `service.instance.id` must be globally unique, and from that point of view, it makes more sense for the exporters to define the the correct instance id based on the environment it's running in (i.e don't use `Enivronment.MachineName` locally since it's not globally unique).
