### ISSUE TITLE
AddContainer fails cryptically if a fully qualified image name is used

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#4218]
If you're familiar with docker, you may try to do one of the following

```cs
var redis= builder.AddContainer("redis", "redis:latest");
var sql = builder.AddContainer("sql", "mcr.microsoft.com/mssql/server:2022-latest");
```

Both of these will be accepted by the app host builder, but will then fail with a cryptic error later on:
```terminal
could not create the container    {"Container": {"name":"reds"}, "Reconciliation": 3, "error": "CreateContainer command returned error code 1 Stdout: '' Stderr: 'invalid reference format\n'"}
```

This is because aspire expects the registry, image and tag to be provided separately i.e.
```cs
var redis = builder.AddContainer("redis","redis", "latest");
var sql = builder.AddContainer("sql", "mssql/server", "2022-latest").WithImageRegistry("mcr.microsoft.com");
```

This seems like an easy mistake for users familiar with docker to make.  This could be improved by either:

1. Fail fast if a fully qualified reference is provided to `AddContainer(string, string)` (i.e. does the string contain `:` or `.`)
2. Accept a fully qualified reference in `AddContainer(string, string)`

**Comment by DamianEdwards** [comment]
If it's possible for us to know by inspecting the string whether a registry URL is included (like the `docker run` CLI seems to) then we should make this just work IMO.

**Comment by afscrome** [comment]
Closing as this seems to be a duplicate of #4355 which has more detail
