### ISSUE TITLE
Should use ContainerRepository instead of ContainerImageName in container builds

### ISSUE THREAD

**Issue by amolenk** [dotnet/aspire#4231]
When using `azd up` to deploy to Azure, the container build emits a warning: 

`CONTAINER003: The property 'ContainerImageName' was set but is obsolete - please use 'ContainerRepository' instead.`

Normally this isn't a problem because it's just a warning, but it'll break the deployment if you specify `MSBuildTreatWarningsAsErrors` to `true` (which is useful for maintaining code quality).

**Comment by davidfowl** [comment]
cc @rajeshkamal5050

**Comment by efonsecab** [comment]
I also just got this issue when trying to publish directly from within Visual Studio:

![image](https://github.com/dotnet/aspire/assets/3481899/e8af565b-cb52-4520-8821-5a33bd9cb35a)

**Comment by davidfowl** [comment]
@vhvb1989

**Comment by vhvb1989** [comment]
Fixed on https://github.com/Azure/azure-dev/issues/3966.
Should be ready in azd-daily version in a couple hours.  

Let me know if you have any questions. Thanks for reporting this.
