### ISSUE TITLE
Update `WithArgs` to accept object array

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#4237]
I'd like to be able to do the following

```cs
builder
  .AddExecutable(...)
  .WithEndpoint(name: "endpoint")
  .WithArgs("-p", builder.Resource.GetEndpoint("endpoint").Property(EndpointProperty.Port));
```

But this doesn't work as the `WithArgs` callback only accepts string array params - https://github.com/dotnet/aspire/blob/d4acce5704b8f086cd38c2e29b2766669d8a1277/src/Aspire.Hosting/ResourceBuilderExtensions.cs#L162-L165

For now, can work around this with the callback overload that does accept objects
```cs
return builder
  .AddExecutable(...)
  .WithArgs(context =>{
      context.Args.Add("-p");
      context.Args.Add(builder.Resource.GetEndpoint(endpointName).Property(EndpointProperty.TargetPort));
    });
```

**Comment by mitchdenny** [comment]
Sounds reasonable. I'm putting on the backlog for now.
