### ISSUE TITLE
Use different cookie name for dashboard

### ISSUE THREAD

**Issue by jack775544** [dotnet/aspire#4263]
## Introduction

Currently the aspire dashboard uses 2 cookies for authentication
* `.AspNetCore.Cookies`
* `.AspNetCore.Antiforgery.<id>`

These cookie names are the defaults for ASP.NET Core. This means that when making an ASP.NET application that uses cookie auth, there is a cookie name conflict with the dashboard since both will be running on `localhost`. This means that when logging into the hosted application, you are logged out of the dashboard and vice versa.

While this can be worked around by changing the cookie name from the application side, it is not a great experience to have the dashboard conflict with the out of the box cookie auth in ASP.NET core.

## Proposal

Use a different cookie name for the dashboard so its login cookie doesn't conflict with other ASP.NET Core applications by default.

## Notes

This may be related to some of the causes of #3899

**Comment by davidfowl** [comment]
cc @kvenkatrajan

**Comment by DamianEdwards** [comment]
Seems like a good idea. Shall we just go with something like:

- `.Aspire.Dashboard.Auth`
- `.Aspire.Dashboard.Antiforgery.<id>`
