### ISSUE TITLE
Break up the TestProject to individual projects per Resource/component

### ISSUE THREAD

**Issue by joperezr** [dotnet/aspire#4294]
Today, we have a single project which we use for several different component's tests which stands up several containers and services. As discussed offline, we want to break this project apart into individual ones per Resource, which will also allow us to add resource-specific tests to ensure things are working as expected. One example of resource-specific tests, would be to validate that resources that support volumes are working as expected.

@davidfowl has volunteered in taking a first stab at this and separate one resource project to see how it looks like, and we can then parallelize the effort from there.

# Components:
- [x] [Aspire.Hosting.Azure.Tests](https://github.com/dotnet/aspire/pull/5013)
- [x] [Aspire.Hosting.Garnet.Tests](https://github.com/dotnet/aspire/pull/4871)
- [x] [Aspire.Hosting.Kafka.Tests](https://github.com/dotnet/aspire/pull/4910)
- [x] [Aspire.Hosting.MongoDB.Tests](https://github.com/dotnet/aspire/pull/5017)
- [x] [Aspire.Hosting.MySql.Tests](https://github.com/dotnet/aspire/pull/4925)
- [x] [Aspire.Hosting.Nats.Tests](https://github.com/dotnet/aspire/pull/5002)
- [x] [Aspire.Hosting.NodeJs.Tests](https://github.com/dotnet/aspire/pull/5142)
- [x] [Aspire.Hosting.Oracle.Tests](https://github.com/dotnet/aspire/pull/4943)
- [x] [Aspire.Hosting.Postgres.Tests](https://github.com/dotnet/aspire/pull/4862)
- [x] [Aspire.Hosting.Python.Tests](https://github.com/dotnet/aspire/pull/4915)
- [x] [Aspire.Hosting.Qdrant.Tests](https://github.com/dotnet/aspire/pull/4879)
- [x] [Aspire.Hosting.RabbitMQ.Tests](https://github.com/dotnet/aspire/pull/5130)
- [x] [Aspire.Hosting.Redis.Tests](https://github.com/dotnet/aspire/pull/4468)
- [x] [Aspire.Hosting.SqlServer.Tests](https://github.com/dotnet/aspire/pull/5056)
- [x] [Aspire.Hosting.Valkey.Tests](https://github.com/dotnet/aspire/pull/4930)
- [x] [Aspire.Hosting.Elasticsearch.Tests](https://github.com/dotnet/aspire/pull/4430)
- [x] [Aspire.Hosting.Keycloak.Tests](https://github.com/dotnet/aspire/pull/4289)
- [x] [Aspire.Hosting.Milvus.Tests](https://github.com/dotnet/aspire/pull/4875)
- [x] [Aspire.Hosting.AWS.Tests](https://github.com/dotnet/aspire/pull/5281)
- [x] [Aspire.Hosting.Dapr](https://github.com/dotnet/aspire/pull/5282)

**Comment by radical** [comment]
It would be useful to add your name next to the item that you want to take, like `Aspire.Hosting.Valkey.Tests (assigned: @radical)`.

**Comment by Alirexaa** [comment]
I'm currently working on Aspire.Hosting.MongoDB.Tests.

**Comment by eerhardt** [comment]
> I'm currently working on Aspire.Hosting.MongoDB.Tests.

I added your name beside it.

Are you able to complete [Extract Aspire.Hosting.Garnet.Tests project (dotnet/aspire#4871)](https://github.com/dotnet/aspire/pull/4871)?

**Comment by Alirexaa** [comment]
> Are you able to complete [Extract Aspire.Hosting.Garnet.Tests project (dotnet/aspire#4871)](https://github.com/dotnet/aspire/pull/4871)?

Yes, But I want to fix #4870 first.

**Comment by eerhardt** [comment]
> > Are you able to complete [Extract Aspire.Hosting.Garnet.Tests project (dotnet/aspire#4871)](https://github.com/dotnet/aspire/pull/4871)?
> 
> Yes, But I want to fix #4870 first.

I don't think we should block the testing work on that. We can extract the existing tests, and add whatever functional tests work, without that issue being fixed. Then when the issue is fixed, it can add the appropriate tests at that time.

**Comment by Alirexaa** [comment]
I will work on Aspire.Hosting.SqlServer.Tests

**Comment by joperezr** [comment]
@sebastienros will follow up and skip the remaining tests, log an issue, and have this work complete.
