### ISSUE TITLE
Make sure all of our tests are debug-able from a CI standpoint

### ISSUE THREAD

**Issue by joperezr** [dotnet/aspire#4298]
@davidfowl recently mentioned that we should make sure that for all of the tests we have running in CI, we should make sure that enough assets and logs are collected as part of the run such that if they were to fail, we would have as much information as possible to be able to understand what might be wrong and to try to fix it. Now that we are working on adding a lot of infrastructure to be able to write new tests, it would be really good to keep this in mind.

In terms of this issue, as a goal it would be good to make a pass through all of the tests we currently run and validate that we have checks in place to collect logs, dumps, and other relevant assets that might help in the situation where they would fail.

- [x] Get resource logs in test output (https://github.com/dotnet/aspire/pull/5193)

**Comment by radical** [comment]
Closing this as we now have logs, blame dumps etc being generated, and collected. If there are more tasks to be done for this then we can open new issues with specific asks.
