### ISSUE TITLE
Container port not exposed when using `WithVolume()`

### ISSUE THREAD

**Issue by silverxjohn** [dotnet/aspire#4299]
I noticed that when I added `.WithVolume()`, the created container is not exposing the port.

Relevant code:

```cs
var postgresPassword = builder.AddParameter("postgresql-password", secret: true);

var postgres = builder.AddPostgres("postgres", password: postgresPassword, port: 63015)
    .WithVolume();
```

### Without `WithVolume()`
<img width="724" alt="Screenshot 2024-05-25 at 8 40 07 PM" src="https://github.com/dotnet/aspire/assets/7147884/a48075b0-aed4-4c2c-9294-ac708189f68f">

### With `WithVolume()`
<img width="721" alt="Screenshot 2024-05-25 at 8 41 15 PM" src="https://github.com/dotnet/aspire/assets/7147884/a1346e2b-c2e8-460e-82f2-47bcbd103711">

**Comment by davidfowl** [comment]
That code sample you pasted doesn't compile. `WithVolume` takes a required argument. Is that the code you are actually using?

<img width="646" alt="image" src="https://github.com/dotnet/aspire/assets/95136/d7d539c7-5c48-478e-a406-597cfb4b6c52">

**Comment by silverxjohn** [comment]
Sorry, I was actually using `WithDataVolume()` but I found this from [StackOverflow](https://stackoverflow.com/questions/78522830/net-aspire-cant-connect-to-database-with-volume-withvolume#comment138448855_78522830) so I thought I'd change it to `WithVolume()`

**Comment by davidfowl** [comment]
Everything seems to be working fine but the docker desktop UI does not show the ports. It doesn't seem to be related to using volumes either:

<img width="706" alt="image" src="https://github.com/dotnet/aspire/assets/95136/68858643-165b-4638-97f4-058378c06cab">

**Comment by silverxjohn** [comment]
That's weird. I've tried multiple times and it sometimes exposes the port other times not. Could just be a problem with my machine. Sorry to bother you. Thanks

**Comment by afscrome** [comment]
Could this be a variation of 4066?  If the new postgres container tries to start up before the previous one has fully shut down, the port may be blocked by the old instance.

**Comment by mitchdenny** [comment]
This smells more like a Docker Desktop UX bug.

**Comment by karolz-ms** [comment]
> Could this be a variation of #4066? If the new postgres container tries to start up before the previous one has fully shut down, the port may be blocked by the old instance.

If that were the case, the container would just fail to start, and not run without the port mapping. So I doubt this is related to #4066

**Comment by dbreshears** [comment]
Looks like this is external to Docker Desktop.   Going to close but if you run into an issue where Aspire is not binding the ports correctly, re-open this.
