### ISSUE TITLE
Multiple overview pages are opened in VS after creating a new Aspire app using the starter template

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#43]
Creating a new Aspire app using the starter template results in overview pages being opened for both the ApiService and Web projects. We should likely have an Aspire specific page instead.

<img width="462" alt="image" src="https://github.com/dotnet/aspire/assets/249088/b0cc22e3-ddf4-42de-888e-c94104db039c">

**Comment by davidfowl** [comment]
@vijayrkn ?

**Comment by DamianEdwards** [comment]
Pretty sure this was fixed
