### ISSUE TITLE
Can't publish Aspire Project using Visual Studio because of failure to parse Danish time format

### ISSUE THREAD

**Issue by Trubador** [dotnet/aspire#4301]
I am using Danish time format and Visual Studio on Windows 11 failed to publish my Aspire 8 project to Azure until I changed to United States time format. I hope you will fix this :)

**Comment by davidfowl** [comment]
Can you show the error message you are getting?

**Comment by timheuer** [comment]
@Trubador Just confirming if you use the `azd` CLI as well do you see the same error?

**Comment by timheuer** [comment]
Confirming this is in the VS/azd communication it looks like, can repro (changed regional time format time indicators from `:` to `.` and can repro.  

Azure Developer CLI log output:
```
26-May-24 09.31.53: Info Starting AzDev server...
azd vs-server --cwd D:\source\repos\timeformattest
Port: 62974, ProcessID: 59072, Version: 1.9.3-daily.3809552
azd vs-server service 'ServerService/v1.0' attached
azd vs-server service 'EnvironmentService/v1.0' attached
26-May-24 09.34.05: Error initializing provisioning manager: resolving bicep parameters file: fetching current principal id: getting tenant id for subscription 07268dd7-4c50-434b-b1ff-67b8164edb41. Error: resolving user access to subscription '07268dd7-4c50-434b-b1ff-67b8164edb41' : unmarshalling response: parsing time "2024-05-26T17.41.31.951Z" as "2006-01-02T15:04:05Z07:00": cannot parse ".41.31.951Z" as ":"
26-May-24 09.35.50: Error initializing provisioning manager: resolving bicep parameters file: fetching current principal id: getting tenant id for subscription 07268dd7-4c50-434b-b1ff-67b8164edb41. Error: resolving user access to subscription '07268dd7-4c50-434b-b1ff-67b8164edb41' : unmarshalling response: parsing time "2024-05-26T17.41.31.396Z" as "2006-01-02T15:04:05Z07:00": cannot parse ".41.31.396Z" as ":"
```

@vhvb1989 @anvillan @ellismg

**Comment by Trubador** [comment]
It seems azd and visual studio publish only fails for the initial attempt using danish time format, subsequent attempts succeed.

**Comment by mitchdenny** [comment]
Opened issue the azd side. I'll leave this open so we don't loose track of this but it'll need to be fixed in AZD.

**Comment by anvillan** [comment]
Hey @mitchdenny @timheuer 

I have created PR !556385 in VS-WebTool with the fix.

**Comment by anvillan** [comment]
@vhvb1989 

For starters, this will be fixed for VS 17.11 and internally available early next week. It should be GA in our next 17.11 release window.

I have also prepared a backport to VS 17.10; need to work with PM so in can be included in the next patch, as well.

**Comment by mitchdenny** [comment]
Thanks for jumping on this.

**Comment by v-elenafeng** [comment]
Checked again using the VS 17.10.4 FB, the scenario is working fine.
