### ISSUE TITLE
I created a project with the aspire-starter template and pressed F5. I'm waiting, but the resources remain "loading".

### ISSUE THREAD

**Issue by recruitans** [dotnet/aspire#4306]
I am using visual studio version 17.10. I created a project with the aspire-starter template and pressed F5. I'm waiting, but the resources remain "loading". I haven't changed the code at all, there is no error in the log.

![image](https://github.com/dotnet/aspire/assets/28866278/9155e644-b518-4430-bc31-54e26312bd87)

![image](https://github.com/dotnet/aspire/assets/28866278/44751932-670c-4d55-94c1-f67f34fce46d)

![image](https://github.com/dotnet/aspire/assets/28866278/ad3393f2-51f1-40d5-b6b3-612f5aa6cfdc)

![image](https://github.com/dotnet/aspire/assets/28866278/77a988ab-4fe8-4c67-9f9d-c10d35e0194e)

![image](https://github.com/dotnet/aspire/assets/28866278/905e9b06-db4b-4df3-aaa3-8c4c976b1a7e)

![image](https://github.com/dotnet/aspire/assets/28866278/f8f073c2-e509-4894-8d6b-159ccfb9e16b)

**Comment by davidfowl** [comment]
Can you go to your apphost's appsettings.json and turn on dashboard logs:

```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Aspire.Hosting.Dcp": "Warning",
      "Aspire.Hosting.Dashboard": "Warning"
    }
  }
}
```

**Comment by recruitans** [comment]
![image](https://github.com/dotnet/aspire/assets/28866278/3f4fa80b-2eec-4770-b240-12d4b99cdb24)

**Comment by Kboxoxx** [comment]
> I am using visual studio version 17.10. I created a project with the aspire-starter template and pressed F5. I'm waiting, but the resources remain "loading". I haven't changed the code at all, there is no error in the log.
> 
> ![image](https://private-user-images.githubusercontent.com/28866278/333901954-9155e644-b518-4430-bc31-54e26312bd87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTA3MjYsIm5iZiI6MTcxNjkxMDQyNiwicGF0aCI6Ii8yODg2NjI3OC8zMzM5MDE5NTQtOTE1NWU2NDQtYjUxOC00NDMwLWJjMzEtNTRlMjYzMTJiZDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1MzM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZjZlMjU0YTE2OTRlNzlmYWM1NjE0ZDZiZDdiYzZmYWY3MjYzY2ZlMjUxZGI0YTUwYjYxYmU2NzU1ZjVjZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxbjKAKaGzxJZAA1PPVdRQVt_4sRvKALPMKvFlurdbA)
> 
> ![image](https://private-user-images.githubusercontent.com/28866278/333902196-44751932-670c-4d55-94c1-f67f34fce46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTA3MjYsIm5iZiI6MTcxNjkxMDQyNiwicGF0aCI6Ii8yODg2NjI3OC8zMzM5MDIxOTYtNDQ3NTE5MzItNjcwYy00ZDU1LTk0YzEtZjY3ZjM0ZmNlNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1MzM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZmJiMTg4ZjhmNDNmZTRmYzNhOWU3Y2NiNDc2MTIzMGU1NzdmMGUxNDU0MDkzZWU5NDBjMWIwZjVlNzE5MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iR2WIAjMr2VfJNcftv2UWCQs7GQoS07xK-i1j0Dc24Y)
> 
> ![image](https://private-user-images.githubusercontent.com/28866278/333902242-ad3393f2-51f1-40d5-b6b3-612f5aa6cfdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTA3MjYsIm5iZiI6MTcxNjkxMDQyNiwicGF0aCI6Ii8yODg2NjI3OC8zMzM5MDIyNDItYWQzMzkzZjItNTFmMS00MGQ1LWI2YjMtNjEyZjVhYTZjZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1MzM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDZjMDE1MmJmZjYwZTJiYjcwMWNkNWM3MjE5ZTAzZGU5YzQ0YzU1OGFhMjE2NTM2Yzk0M2VkNDA5OGJmNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfX-Ef6m56F5EpscEDxiAuKL6h1HPXqnyrJrfOtT9wM)
> 
> ![image](https://private-user-images.githubusercontent.com/28866278/333902306-77a988ab-4fe8-4c67-9f9d-c10d35e0194e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTA3MjYsIm5iZiI6MTcxNjkxMDQyNiwicGF0aCI6Ii8yODg2NjI3OC8zMzM5MDIzMDYtNzdhOTg4YWItNGZlOC00YzY3LTlmOWQtYzEwZDM1ZTAxOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1MzM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNzM4NWI5MjQ2YTQ5ZWJjOGRkNDc4OGM5NDgwYWU2MzkzNzgwMTMxYWFiMDk0ODAyZDJlMDY5ODIzNjliMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UBiRCwbzDq47np0pJ7aKauyadh2KjkWdWwcqLq1yKOA)
> 
> ![image](https://private-user-images.githubusercontent.com/28866278/333902454-905e9b06-db4b-4df3-aaa3-8c4c976b1a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTA3MjYsIm5iZiI6MTcxNjkxMDQyNiwicGF0aCI6Ii8yODg2NjI3OC8zMzM5MDI0NTQtOTA1ZTliMDYtZGI0Yi00ZGYzLWFhYTMtOGM0Yzk3NmIxYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1MzM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYTAwYjAwY2RjN2Y0OTNlYjg0M2RhNGNjNGMzNzBhYWMwMDMzMDZhNzFmNzI1NjRjNTRlYmIxMDRkYmRiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EnrAEzIZfFfx-s1tXbASghbZ4uRMLzG7zxpXoEyyNSs)
> 
> ![image](https://private-user-images.githubusercontent.com/28866278/333902515-f8f073c2-e509-4894-8d6b-159ccfb9e16b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTA3MjYsIm5iZiI6MTcxNjkxMDQyNiwicGF0aCI6Ii8yODg2NjI3OC8zMzM5MDI1MTUtZjhmMDczYzItZTUwOS00ODk0LThkNmItMTU5Y2NmYjllMTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDE1MzM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NjJmODk0MjA4ZTJlYWE2NWQ2NmFiYTE1NWEyMzRkY2M0OWYyZTgwYWM4NjM4Y2E1YWIwNmJkNjcyYTczYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WWxpOGYYtA3CRHR4x5J8uV0ALlow0_YjuCcXw9MhhN8)
