### ISSUE TITLE
aspire to an existing project error startup

### ISSUE THREAD

**Issue by viniciusverasdossantos** [dotnet/aspire#4307]
I added aspire to an existing project... when I try to start it, the print error occurs.
If I remove the Web_api project and leave only RabbitMq, it works normally. Any tips?

![image](https://github.com/dotnet/aspire/assets/16549732/4029b860-97d3-4193-ab81-221938953ea3)

**Comment by davidfowl** [comment]
Looks like your launch profile has invalid JSON.

**Comment by viniciusverasdossantos** [comment]
that was it! I don't understand why when running the webapi directly there was no error! thnakyou!!

**Comment by davidfowl** [comment]
@mitchdenny what do you think?

**Comment by mitchdenny** [comment]
Totally looks like an invalid launch profile to me. Can you repro it in a project that you can post to GitHub so we can take look.

**Comment by davidfowl** [comment]
We could throw a better exception with the project name and launchSettings path.
