### ISSUE TITLE
[WebToolsE2E][Aspire] Add Aspire.Azure.Security.KeyVault component, the page cannot be loaded after publishing.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#4314]
**REGRESSION INFO**: Repro on Aspire 8.0.1 and Aspire 8.0.0

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.11 Preview 2 [34927.71.main] (Includes Aspire 8.0.0)
3. Install Aspire 8.1 Preview 1 [8.1.0-preview.1.24277.1]
4. Apply NuGet Feeds
5. Install Docker Dektop
6. Install azd [1.9.3]

**REPRO STEPS**

1. New Project > ASP.NET Core Empty project > name it 'AspireKeyVault05'> 8.0 > check 'Enlist in Aspire Orchestration'
2. Right-click the AspireKeyVault05 > Add > .NET Aspire package > check 'Include prerelease' > change 'Package source' to 'All' > install Aspire.Azure.Security.KeyVault with matched version
3. Open Program.cs of AspireKeyVault05 project, replace it with the following code:
```
using Azure.Identity;

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();
var keyVaultEndpoint = new Uri(Environment.GetEnvironmentVariable("VaultUri"));
builder.Configuration.AddAzureKeyVault(keyVaultEndpoint, new VisualStudioCredential());
var app = builder.Build();

app.MapDefaultEndpoints();

//app.MapGet("/", () => "Hello World!");
string? _mySecret = builder.Configuration["myAppSetting"];
var result = string.IsNullOrEmpty(_mySecret) ? "Null" : _mySecret;
app.MapDefaultEndpoints();
app.MapGet("/", async context =>
{
await context.Response.WriteAsync($"Secret is {result}");
});

app.Run();
```
4. Open launchSettings.json of the AspireKeyVault05 project and add the following code to ‘"https":{"environmentVariables";{}}’
```
"VaultUri": "https://xxx.vault.azure.net/"
"AZURE_USERNAME": "xxx@microsoft.com"
```
5. Build and F5 - The page can successfully display the secret value.
![image](https://github.com/dotnet/aspire/assets/109339894/ffcdfbd9-3e31-44d9-b77a-35056ebb3b26)

6. Open Program.cs of AspireKeyVault05.AppHost project, add `.WithExternalHttpEndpoints()`
7. Right-click solution > Open folder in file explorer, In the opened folder, right-click any place > open in terminal
8. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter
9. Running 'azd up'
10. Open the resource group, click the container app , open 'Application Url'

**ACTUAL**
After a long time of loading the page, it will show "stream timeout".
![image](https://github.com/dotnet/aspire/assets/109339894/5f6431e4-478e-4672-a55d-c7442d1f8754)

Aspire Dashboard: 
![image](https://github.com/dotnet/aspire/assets/109339894/875b2bf4-adcb-4343-88f7-e03dcd77c306)

Console logs: 
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Uri..ctor(String uriString)
   at Program.<Main>$(String[] args) in C:\Users\v-reinawang\source\repos\AspireKeyVault05\AspireKeyVault05\Program.cs:line 6

**EXPECTED**
After publishing, the page can be opened successfully.

**Comment by davidfowl** [comment]
Looks like you don't have `VaultUri` environment variable set. You set the value in `appsettings.json` and deploying it to the server. What is settings VaultUri?

The other problem is that you are hard coding `VisualStudioCredential` which doesn't work in deployed environments.

**Comment by mitchdenny** [comment]
This is a bit of an odd bug? It uses Aspire but its not really using Aspire to manage the hookup of KeyVault - then there is the credential issue that David has mentioned.

**Comment by v-reinawang** [comment]
So should I add other settings? Or my steps are wrong?

**Comment by davidfowl** [comment]
Your steps are not correct.

> Open launchSettings.json of the AspireKeyVault05 project and add the following code to ‘"https":{"environmentVariables";{}}’

You are setting configuration in **launchSettings.json** which is used when running, it is not used when you deploy.

This is why you are getting a null reference:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
at System.ArgumentNullException.Throw(String paramName)
at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
at System.Uri..ctor(String uriString)
```

The VaultUri is null because you didn't set it in the right place. Look at your container app environment, it doesn't have any settings that can be used at runtime.

This is what I mentioned earlier:

>  You set the value in appsettings.json and deploying it to the server.

**Comment by v-reinawang** [comment]
I tried another step to replace steps 4:
1. Right-click the AspireKeyVault05.AppHost project > Add > .NET Aspire package > install Aspire.Hosting.Azure.KeyVault with matched version
2. Open Program.cs of AspireKeyVault05.AppHost project, add following codes:
```
//builder.AddProject<Projects.AspireKeyVault05>("aspirekeyvault05");

var keyVault = builder.AddConnectionString("secretConnectionName", "VaultUri");

builder.AddProject<Projects.AspireKeyVault05>("aspirekeyvault05")
    .WithExternalHttpEndpoints()
    .WithReference(keyVault);
```
3. Open appsettings.json of AspireKeyVault05.AppHost project, add following codes:
```
"ConnectionStrings": {
 "secretConnectionName": "https://aspkey1.vault.azure.net/"
},
```
After successfully publishing, the secret still cannot be displayed. It looks like the problem with 'VisualStudioCredential' you mentioned before. Is there any solution for this?
![image](https://github.com/dotnet/aspire/assets/109339894/14d3e714-d731-4b83-bbdc-483c097b6667)

Console logs:
Unhandled exception. Azure.Identity.CredentialUnavailableException: Visual Studio Token provider can't be accessed at /home/app/.IdentityService/AzureServiceAuth/tokenprovider.json
1 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/app/.IdentityService/AzureServiceAuth/tokenprovider.json'.
2 at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
3 at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
4 at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
5 at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
6 at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
7 at System.IO.File.ReadAllText(String path, Encoding encoding)
8 at Azure.Identity.FileSystemService.ReadAllText(String path)
9 at Azure.Identity.VisualStudioCredential.GetTokenProviderContent(String tokenProviderPath)
10 --- End of inner exception stack trace ---
11 at Azure.Identity.VisualStudioCredential.GetTokenProviderContent(String tokenProviderPath)
12 at Azure.Identity.VisualStudioCredential.GetTokenProviders(String tokenProviderPath)
13 at Azure.Identity.VisualStudioCredential.GetTokenImplAsync(TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
14 at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
15 at Azure.Identity.VisualStudioCredential.GetTokenImplAsync(TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
16 at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
17 at Azure.Identity.VisualStudioCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
18 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
19 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
20 at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
21 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
22 at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
23 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequest(HttpMessage message, TokenRequestContext context)
24 at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallengeAsyncInternal(HttpMessage message, Boolean async)
25 at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
26 at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallenge(HttpMessage message)
27 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
28 at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
29 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
30 at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
31 at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
32 at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
33 at Azure.Core.Pipeline.RedirectPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
34 at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
35 at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
36 at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
37 at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
38 at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
39 at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
40 at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
41 at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
42 at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
43 at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
44 at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
45 at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
46 at Azure.Core.Pipeline.HttpPipeline.SendRequest(Request request, CancellationToken cancellationToken)
47 at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
48 at Azure.Security.KeyVault.KeyVaultPipeline.GetPage[T](Uri firstPageUri, String nextLink, Func`1 itemFactory, String operationName, CancellationToken cancellationToken)
49 at Azure.Security.KeyVault.Secrets.SecretClient.<>c__DisplayClass15_0.<GetPropertiesOfSecrets>b__0(String nextLink)
50 at Azure.Core.PageResponseEnumerator.<>c__DisplayClass0_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint)
51 at Azure.Core.PageResponseEnumerator.FuncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
52 at Azure.Pageable`1.GetEnumerator()+MoveNext()
53 at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load()
54 at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
55 at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
56 at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, SecretClient client, AzureKeyVaultConfigurationOptions options)
57 at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, Uri vaultUri, TokenCredential credential, KeyVaultSecretManager manager)
58 at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, Uri vaultUri, TokenCredential credential)
59 at Program.<Main>$(String[] args) in C:\Users\v-reinawang\source\repos\AspireKeyVault04\AspireKeyVault04\Program.cs:line 7

**Comment by davidfowl** [comment]
Excellent, now the other piece of my original feedback from here https://github.com/dotnet/aspire/issues/4314#issuecomment-2134604694.

> The other problem is that you are hard coding VisualStudioCredential which doesn't work in deployed environments.

You should use `DefaultAzureCredential`

**Comment by v-reinawang** [comment]
Thanks. After I use `DefaultAzureCredential`, this issue will not repro, I will close it.
