### ISSUE TITLE
Kafka component - using a service registered in DI to build serializer / deserializer is not possible

### ISSUE THREAD

**Issue by g7ed6e** [dotnet/aspire#4323]
`AddKafkaConsumer` and `AddKafkaProducer` does not provide access to `IServiceProvider` inside parameters named configureBuilder. 
The below diff would allow one to register `ISerializer<T>` / `IDeserializer<T>` in DI and pull these services to set serializers / deserializers using configureBuilder parameters. That would make possible to use a DI registered service to create serializer/ deserializer instances too.
```diff
-    public static void AddKafkaConsumer<TKey, TValue>(this IHostApplicationBuilder builder, string connectionName,
- Action<KafkaConsumerSettings>? configureSettings = null, Action<ConsumerBuilder<TKey, TValue>>? configureBuilder = null)
+    public static void AddKafkaConsumer<TKey, TValue>(this IHostApplicationBuilder builder, string connectionName,
+ Action<KafkaConsumerSettings>? configureSettings = null, Action<IServiceProvider, ConsumerBuilder<TKey, TValue>>? configureBuilder = null)
```

**Comment by mitchdenny** [comment]
@eerhardt interested in your thoughts here.
