### ISSUE TITLE
Tests hang when using xUnit and DistributedApplicationTestingBuilder if an exception is thrown in the AppHost project before the host is built

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#4330]
`DistributedApplicationTestingBuilder.CreateAsync` hangs forever if there's an exception thrown in the AppHost project before `Build()` is called, e.g. when attempting to add multiple resources with the same name:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var pg = builder.AddPostgres("pg")
var db = pg.AddDatabase("pg"); // <-- Same name as the server resource above it

builder.Build().Run();
```

The Output window in Visual Studio in the "Tests" source shows just that an exception was thrown but no detail:

<img width="497" alt="image" src="https://github.com/dotnet/aspire/assets/249088/0620fbe2-46e8-4704-be3b-ba171da88b90">

This is pretty frustrating when trying to do anything "test first" as the exception is just not visible. We should try and make the call to `CreateAsync` fail if the AppHost throws.

/Cc @ReubenBond

**Comment by ReubenBond** [comment]
I opened #4331 with a fix
