### ISSUE TITLE
Visual Studio Publish does not enclose the path with quotes

### ISSUE THREAD

**Issue by Kumima** [dotnet/aspire#4347]
If the path has spaces, then it won't work.

From azd:
> 2024/5/31 13:22:49: Error AzDev server failed to start.
2024/5/31 13:22:50: Info Starting AzDev server...
azd vs-server --cwd D:\Projects\Visual Studio Projects\AspireStarter
Error: failed to change directory to D:\Projects\Visual: chdir D:\Projects\Visual: The system cannot find the file specified.
Microsoft.VisualStudio.Shell.ServiceUnavailableException: The RpcServer service is unavailable.
at Microsoft.VisualStudio.ConnectedServices.Azure.AzDev.Rpc.RpcServer.<StartAsync>d__22.MoveNext()

From Visual Studio Publish UI, I'm using 2022 17.11.0 Preview 1.1 and 17.10.1.
> Publish profile creation failed.
Unable to store profile 'D:\Projects\Visual Studio Projects\AspireStarter\AspireStarter.AppHost\TEST'

**Comment by mitchdenny** [comment]
@bradygaster PTAL

**Comment by timheuer** [comment]
@vijayrkn

**Comment by anvillan** [comment]
Hey,

We have addressed this issue with PR !555610 (in VS WebTools). 

The change has been merged into main and we are preparing a 17.10 backport for it.

**Comment by mitchdenny** [comment]
Thanks @anvillan! We'll close this issue off then.
