### ISSUE TITLE
MongoDB Authentication

### ISSUE THREAD

**Issue by Crazyht** [dotnet/aspire#4348]
For the MongoDB package, I need to be able to set an initial Username and Password to enable authentication.

This can be done by using MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD environment variables.

This parameter must also be passed to mongo-express and used in the connection string.

**Comment by davidfowl** [comment]
This isn't supported today for mongo, but if you're interested feel free to send a PR with this support. You can model it after the postgres resource.

**Comment by Crazyht** [comment]
PR request build failed, but I can see why here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=696252&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=25461519-4e76-58ab-2938-2b66c09712e4&l=23

Aspire.Azure.Data.Tables are not touched by my commit, so this test failed for probably a good reason, but I don't see which one :(
