### ISSUE TITLE
[Aspire.Host] Add Kafka-ui support

### ISSUE THREAD

**Issue by MadL1me** [dotnet/aspire#4354]
Add similar extension method as `WithPgAdmin` but for Kafka which will use **_[kafka-ui](https://github.com/provectus/kafka-ui)_** as UI provider for kafka brokers, or any other ui of choice (but I think kafka-ui is a good option):

```cs
var builder = DistributedApplication.CreateBuilder(args);

builder.AddKafka("kafka")
    .WithKafkaUi();

builder.Build().Run();
```

**Comment by davidfowl** [comment]
This was added in main, here https://github.com/dotnet/aspire/pull/3882

It’s not in any release as yet.

**Comment by MadL1me** [comment]
Oh, I see. Sorry, I didn't checkout out the closed issues
