### ISSUE TITLE
Dashboard should show custom resources

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#436]
Today the dashboard shows projects, containers, executables, while these are the core "launchable" primitives, things like AzureServiceBus and PostgresConnection don't show up. We should show other resources that come the application model directly that aren't part of the DCP model.

In eshoplite, there's no way to see the azure service bus resource:

<img width="1134" alt="image" src="https://github.com/dotnet/aspire/assets/95136/7fb28812-6c40-46bb-ac5d-01eee59f8e5a">

**Comment by davidfowl** [comment]
@kvenkatrajan Putting this in preview3 (it might slip to 4)

**Comment by smitpatel** [comment]
In order for us to show custom resources we need to invert our current way of computing view models for dashboard. Right now we get data from dcp and fill in places from application model where needed (specifically for endpoint details from launch profiles).
In inverted way, we will basically utilize the resources which are in application model and for well-known resource kinds like Executable/Container, we will ask dcp to provide information regarding current run and fill the view model.

**Comment by davidfowl** [comment]
After this change we will be using the distributed application model as the source of truth, not dcp. Dcp will enrich the values resources with data about what’s actually running

**Comment by drewnoakes** [comment]
Status update:

- The communication protocol between AppHost and Dashboard supports arbitrary resource types. The UI will show custom resources.
- With #1542, we can show all property name/value pairs a resource defines.
- We must still update the AppHost's implementation of the resource service to pull from the Distributed Application Model.
- Getting new resource types will draw out requirements and designs for further improvements.
