### ISSUE TITLE
What is the difference between AddKeyedSqlServerClient and AddSqlServerClient? 

### ISSUE THREAD

**Issue by datovy-edam** [dotnet/aspire#4368]
### Describe the issue or suggestion

Is not clear What is the difference between AddKeyedSqlServerClient and AddSqlServerClient?  If documentation about it exists, I could not find it, and if it does exists, please provide link.

**Comment by eerhardt** [comment]
Moving to dotnet/aspire repo to track fixing the XML docs.

**Comment by datovy-edam** [comment]
Understood, thanks for quick response.
