### ISSUE TITLE
How to Debug Multiple Dapr Projects Managed by Aspire

### ISSUE THREAD

**Issue by xiaofang-code** [dotnet/aspire#4376]
Hello,

I am managing several WebAPI projects with Aspire. These WebAPI projects use Dapr for microservice interactions. When I create an Aspire project and add these WebAPI projects with Aspire support, including the aspire.Dapr dependency, I encounter errors when trying to run them.

I would like to know how to migrate existing Dapr-based WebAPI projects to be managed by Aspire.

**Comment by mitchdenny** [comment]
Can you provide more detail about the errors you are experiencing. It would be helpful if you could create a small repo in a GitHub repository and link it here so we can quickly reproduce what you are seeing.

**Comment by xiaofang-code** [comment]
Here is my GitHub demo: https://github.com/xiaofang-code/dapr_aspireDemo.

My goal is to be able to set breakpoints and step into the code while making requests through Aspire, to facilitate development and debugging. This demo currently throws errors, possibly due to issues in the JSON.

Thank you for your help.

> Can you provide more detail about the errors you are experiencing. It would be helpful if you could create a small repo in a GitHub repository and link it here so we can quickly reproduce what you are seeing.您能否提供有关您遇到的错误的更多详细信息。如果您可以在 GitHub 存储库中创建一个小型存储库并将其链接到此处，这将很有帮助，以便我们可以快速重现您所看到的内容。

**Comment by davidfowl** [comment]
What errors do you encounter? Can you show them here?

**Comment by xiaofang-code** [comment]
> What errors do you encounter? Can you show them here?您遇到什么错误？你能在这里展示它们吗？

Here is the error I get when running the demo:

`System.Text.Json.JsonException: “The JSON value could not be converted to System.Nullable`1[System.Boolean]. Path: $.profiles.CheckoutService.dotnetRunMessages | LineNumber: 5 | BytePositionInLine: 33.”
`
If possible, please pull the demo repository, run it, and check for more detailed information.
https://github.com/xiaofang-code/dapr_aspireDemo

Thank you for your help.

**Comment by davidfowl** [comment]
Where does that exception come from? Can you show the entire call stack?

**Comment by xiaofang-code** [comment]
> Where does that exception come from? Can you show the entire call stack?这个异常从何而来？你能显示整个调用堆栈吗？
This is the error message I received after running the program:
`System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to System.Nullable`1[System.Boolean]. Path: $.profiles.CheckoutService.dotnetRunMessages | LineNumber: 5 | BytePositionInLine: 33.
  Source=System.Text.Json
  StackTrace:
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   在 System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   在 Aspire.Hosting.LaunchProfileExtensions.GetLaunchSettings(IProjectMetadata projectMetadata) 在 /_/src/Aspire.Hosting/LaunchProfileExtensions.cs 中: 第 83 行
   在 Aspire.Hosting.LaunchProfileExtensions.GetLaunchSettings(ProjectResource projectResource) 在 /_/src/Aspire.Hosting/LaunchProfileExtensions.cs 中: 第 29 行
   在 Aspire.Hosting.LaunchProfileExtensions.TrySelectLaunchProfileFromEnvironment(ProjectResource projectResource, String& launchProfileName) 在 /_/src/Aspire.Hosting/LaunchProfileExtensions.cs 中: 第 118 行
   在 Aspire.Hosting.LaunchProfileExtensions.SelectLaunchProfileName(ProjectResource projectResource) 在 /_/src/Aspire.Hosting/LaunchProfileExtensions.cs 中: 第 159 行
   在 Aspire.Hosting.LaunchProfileExtensions.GetEffectiveLaunchProfile(ProjectResource projectResource, Boolean throwIfNotFound) 在 /_/src/Aspire.Hosting/LaunchProfileExtensions.cs 中: 第 34 行
   在 Aspire.Hosting.ProjectResourceBuilderExtensions.WithProjectDefaults(IResourceBuilder`1 builder, Boolean excludeLaunchProfile, String launchProfileName) 在 /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs 中: 第 229 行
   在 Aspire.Hosting.ProjectResourceBuilderExtensions.AddProject[TProject](IDistributedApplicationBuilder builder, String name) 在 /_/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs 中: 第 57 行
   在 Program.<Main>$(String[] args) 在 C:\Users\xiaofang\Desktop\lanlue\dapr_aspireDemo\AspireApp\AspireApp.AppHost\Program.cs 中: 第 13 行

  此异常最初是在此调用堆栈中引发的: 
    System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedBoolean(System.Text.Json.JsonTokenType)
    System.Text.Json.Utf8JsonReader.GetBoolean()
    System.Text.Json.Serialization.Converters.NullableConverter<T>.Read(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions)
    System.Text.Json.Serialization.Metadata.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader)
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T, out bool)
    System.Text.Json.Serialization.JsonDictionaryConverter<TDictionary, TKey, TValue>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out TDictionary)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T, out bool)
    System.Text.Json.Serialization.Metadata.JsonPropertyInfo<T>.ReadJsonAndSetMember(object, ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader)
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    ...
    [调用堆栈已截断]

内部异常 1:
InvalidOperationException: Cannot get the value of a token type 'String' as a boolean.
`
My ultimate goal is to take over the existing Dapr project through Aspire and debug the code locally. Does the official team have any demos or resources that they can provide for reference?

**Comment by xiaofang-code** [comment]
> Your launch profile is broken. This is what it’s complaint about您的启动配置文件已损坏。这就是投诉的内容
> 
> https://github.com/xiaofang-code/dapr_aspireDemo/blob/0a85acc1a9f508fc4753696aa9827da5c86be9eb/Services/order-processor/Properties/launchSettings.json#L6
> 
> That remove the quotes around “true”删除“true”周围的引号

Thank you! I have resolved the issue and can now use it successfully.

**Comment by kwaazaar** [comment]
That's weird: I just had the same issue, also for the dotnetRunMessages. Must have been generated this way by an early version of Visual Studio or Rider.

**Comment by chris31389** [comment]
I had this issue too.  I found that it was the launchsettings.json in my service projects rather than the AppHost project that had the `"true"` that I needed to update to `true`.
