### ISSUE TITLE
Blazor WASM Project: Tracing & Metrics

### ISSUE THREAD

**Issue by venkyrs** [dotnet/aspire#4387]
Is there a way to configure a Blazor WASM App to send traces and metrics to the Aspire Dashboard?
I could not find any samples.

**Comment by davidfowl** [comment]
No, the dashboard doesn’t support telemetry from the browser.

**Comment by venkyrs** [comment]
Thank @davidfowl 
Basically we can only launch the Blazor WASM app from Aspire but things like service discovery, tracing and metrics are not supported.

**Comment by davidfowl** [comment]
You can read this very long and interesting thread on why https://github.com/dotnet/aspire/discussions/1914

**Comment by davidfowl** [comment]
Closing this as a dupe of that. We'll come to a resolution and open an issue with concrete next steps.
