### ISSUE TITLE
update README for Aspire.Azure.Security.KeyVault to require package reference to Aspire.Hosting.Azure

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#440]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 from build main-34219.241
3. Install latest 8.0 SDK: 8.0.100-rtm.23519.30
4. Apply NuGet Feeds
5. Install Aspire workload
6. Install Docker Desktop

**REPRO STEPS**
1. In the VS, create a new project > ASP.NET Core Empty > give a name 'AppWithKv1' > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Build solution 
3. Right click the AppWithKv1 project > Add > Aspire Component > Set Package source to 'All' and check 'Include prerelease' option > install the latest prerelease version of 'Aspire.Azure.Security.KeyVault'
4. Open Program.cs of the AppWithKv1.AppHost project

**ACTUAL**
README.md of the Aspire.Azure.Security.KeyVault package has the following lines. But when I try to do `builder.AddAzureKeyVault` in the Program.cs of AppWithKv1.AppHost project, the method is not available. Even if I add the Aspire.Azure.Security.KeyVault package directly as a component of AppWithKv1.AppHost project, I still cannot get this to work.

![image](https://github.com/dotnet/aspire/assets/8246794/aef88694-fbe8-4c02-9c56-2ee17d97432e)

**From README.md**
In your AppHost project, add a Key Vault connection and consume the connection using the following methods:

```csharp
var keyVault = builder.AddAzureKeyVault("secrets");

var myService = builder.AddProject<Projects.MyService>()
                       .WithReference(keyVault);
```

The `AddAzureKeyVault` method will read connection information from the AppHost's configuration (for example, from "user secrets") under the `ConnectionStrings:secrets` config key. The `WithReference` method passes that connection information into a connection string named `secrets` in the `MyService` project. In the _Program.cs_ file of `MyService`, the connection can be consumed using:

**EXPECTED**
We should be able to do `AddAzureKeyVault` from the AppHost project.

**Comment by eerhardt** [comment]
This should apply to all Azure components, not just Key Vault. Reopening to add it to the other READMEs.
