### ISSUE TITLE
Not able to load aspire dashboard on cloud 

### ISSUE THREAD

**Issue by bahuja** [dotnet/aspire#4408]
I have deployed the app on azure container registry though Visual studio . App is working fine, However when I am trying to load aspire dashboard, its throwing following exception. Kindly look into this. 

![image](https://github.com/dotnet/eShop/assets/15103972/edc32df5-0d9b-416d-99a2-46add13b0a70)

**Comment by mitchdenny** [comment]
@bahuja can you provide some more details on the version of AZD that you have installed?

**Comment by davidfowl** [comment]
@bahuja There was an issue that I think is fixed on the ACA side now.

**Comment by bahuja** [comment]
Yes , I am not getting this issue anymore since and same seems to be
resolved.

*Regards*


*Brijender Ahuja*


*E: ***@***.*** ***@***.***>*
