### ISSUE TITLE
Dashboard: Traces & Log messages - viewer for long fields

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspire#4412]
There is an initiative to use OTel to provide telemetry for LLM applications - recording the prompt and response text. These are typically long and can be plain text or json. When looking at these in the Aspire dashboard, in the trace and logs view, the details pane has a one line display with a "..." and button to copy to the dashboard. 

![image](https://github.com/dotnet/aspire/assets/54915162/21feb552-b51e-4488-a584-e350138ba291)

Visual Studio debugger has the same problem when its showing variables in the watch window. It has an option to pop out the value in a modal dialog, where text can be more easily examined. We should have something similar for the dashboard.

![image](https://github.com/dotnet/aspire/assets/54915162/fbd19c75-7dfe-46f4-af6b-cb67a854681d)

![image](https://github.com/dotnet/aspire/assets/54915162/6c86ec3e-623b-4b01-a279-9f79d952eb73)

When the text is opened in the viewer, we should have a quick mechanism to sniff to see if it looks to be json, and then provide an option to format the content as json - as it typically will not have any formatting. The VS one has the ability to do base64, url encoding/decoding. Those are probably not needed here, but JSON and possibly XML formatting would be very useful.
If it fails to parse that would also be really useful to know, so spitting out the error in those cases would be good.

**Comment by davidfowl** [comment]
This feels very important. Makes the dashboard a bit unusable with large text values.

**Comment by samsp-msft** [comment]
I am thinking something like: 
![image](https://github.com/dotnet/aspire/assets/54915162/67e451f3-baec-4318-b65c-86d6b560fd10)

**Comment by leslierichardson95** [comment]
TODO: Figure out an owner here.

**Comment by samsp-msft** [comment]
This will also be needed for events on spans in the trace details view, as those will also have the same long messages attached.

**Comment by adamint** [comment]
@kvenkatrajan for assignment.

**Comment by adamint** [comment]
> I am thinking something like: ![image](https://private-user-images.githubusercontent.com/54915162/338293704-67e451f3-baec-4318-b65c-86d6b560fd10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTAyNjgsIm5iZiI6MTcyMTE0OTk2OCwicGF0aCI6Ii81NDkxNTE2Mi8zMzgyOTM3MDQtNjdlNDUxZjMtYmFlYy00MzE4LWI2NWMtODZkNmI1NjBmZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE3MTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDBlZjdlN2Q0ZTUzMjg0NzRjMTI4ODAxOGZkNjdiMjBlODVkZDA0MTQwNzc4ZTc0YzJiZWY0MTVjYWQ2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m18u6-ycB-u7M70Y_N5Pc1OGJv8hOdBfAZH3vRHghsQ)

@samsp-msft we already have a button there for copying the grid value. We could replace with a button that opens a little tooltip where you can choose your action?

**Comment by adamint** [comment]
As per discussion with @leslierichardson95 and @samsp-msft, we would like to have a button to open a menu, where you will be able to choose whether to open this popup or copy the cell text.

**Comment by davidfowl** [comment]
Sweet!
