### ISSUE TITLE
Truncated Endpoint Column flashes whenever resource status changes

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#4417]
On the resource dashboard, if the endpoints column for a resource is truncated, whenever the resoruce status changes for a resoruce, then the endpoint value in the resource's row briefly flashes.

Whenver the resource updates, the endpoint column will briefly flash without the `+N` icon for truncation
<img alt="image" src="https://github.com/dotnet/aspire/assets/289860/39ab7834-a195-4c37-ba8b-c0f73794ddcb">

Before settling back to displaying `+N`
<img alt="image" src="https://github.com/dotnet/aspire/assets/289860/c6f94aec-a864-47c2-b354-098dcca64c77">

Below is a simple app that can be used to reproduce this.

This is definitely not a major issue, but it is an irritating one.

````cs
var builder = DistributedApplication
    .CreateBuilder(args);

builder.AddExecutable("pwsh", "pwsh.exe", ".")
    .WithArgs("-Command", "Start-Sleep -Seconds 9999")
    .WithEndpoint(name: "One", port: 5551, isProxied: false)
    .WithEndpoint(name: "Two", port: 5553, isProxied: false)
    .WithEndpoint(name: "Three", port: 5553, isProxied: false);

builder.Services.AddLifecycleHook<TestHook>();
await builder.Build().RunAsync();

public class TestHook(ResourceNotificationService resourceNotificationService) : IDistributedApplicationLifecycleHook
{
    public Task AfterResourcesCreatedAsync(DistributedApplicationModel appModel, CancellationToken cancellationToken = default)
    {
        var resource = appModel.Resources.Single(x => x.Name == "pwsh");
        _ = RotateStatus();
        return Task.CompletedTask;

        async Task RotateStatus()
        {
            while(true)
            {
                await Task.Delay(1000);
                await resourceNotificationService.PublishUpdateAsync(resource, x => x);
            }
        }
    }
}
```

**Comment by mitchdenny** [comment]
@adamint PTAL.
