### ISSUE TITLE
Add Elasticsearch component

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/aspire#4418]
- Add the Elasticsearch resource.
- Add the Elasticsearch client (Elastic.Clients.Elasticsearch)

Is there any plan to add these components to aspire?

**Comment by mitchdenny** [comment]
We haven't got it on the backlog right now but we would definately be open to having a PR for it if you are up for contributing. If not we can pop this on the backlog and see when someone can pick it up. Seems like it would be a useful addition.

**Comment by Alirexaa** [comment]
I am ready to contribute to this. if there is nothing to say I can start it.

**Comment by Alirexaa** [comment]
Elasticsearch resource added in [this](https://github.com/dotnet/aspire/pull/4430/commits/2141fb53412e622d3302727fa6df1ad06e04c525) commit but for the client, **Elastic.Clients.Elasticsearch** package is not in the package sources. only **Elasticsearch.Net** is available (already deprecated)

**Comment by stevejgordon** [comment]
Hey, @Alirexaa. Thanks for starting on this. It's something we'd been planning to do at Elastic, but we hadn't managed to prioritise it yet. I might have some time in a week to send on this. I'm happy to review and build on what you're doing. We had some thoughts on the different options for resources as it would be useful to support the local docker container but also Elastic cloud for ease, too. I'm OOO this week, but I'm happy to discuss more next week.

**Comment by mitchdenny** [comment]
@stevejgordon  ... @Alirexaa is getting pretty close to have this done and ready to merge. If you wanted to take a look now would be a good time before it merges!
