### ISSUE TITLE
Support adding multiple ConfigureConstruct callbacks to `AzureConstructResource`

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4424]
## Background and Motivation

This allows for mutating existing resources beyond the original construction.

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:
```diff
namespace Aspire.Hosting.Azure;

public static class AzureConstructResourceExtensions
{
+    public static IResourceBuilder<T> ConfigureConstruct<T>(this IResourceBuilder<T> builder, Action<ResourceModuleConstruct> configure) where T : AzureConstructResource;
}
```

## Usage Examples

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddAzureKeyVault("kv").ConfigureConstruct(r =>
{
    r.GetSingleResource<KeyVault>().AddOutput("name", k => k.Name);
});

builder.Build().Run();
```

## Risks

Low

**Comment by davidfowl** [comment]
@mitchdenny I'd love to get this for 8.1 to unblock some scenarios.

**Comment by mitchdenny** [comment]
This would require on the backing field hack?

**Comment by davidfowl** [comment]
I'll send a PR, I made ConfigureConstruct internal set, but we can add another field as well.
