### ISSUE TITLE
[WebToolsE2E][Aspire][Unstable] After successfully publishing an Aspire project, the 'Aspire Dashboard' page fails to load after publishing

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#4446]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install Dev17.10.2 (Includes Aspire 8.0.0)
1. Install azd [azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)]

**REPRO STEPS**

1. New Project > .NET Aspire Starter App > name it 'AspireApp3'> 8.0 > Create
1. Right-click the AspireApp3.AppHost > Publish > Azure Container Apps for .NET Aspire > next > Under 'AzDev Environment', select following settings > next
	• Subscription name: WTE
	• Location: East US
	• Environment name: type your own name
1. Click 'Finish' > 'Close' > Click 'Publish' button on the summary page
1. After publish finished, open 'Aspire Dashboard' url from output window as below:
![image](https://github.com/dotnet/aspire/assets/72899617/3c48276b-605f-4acc-8b91-a7721ae44df6)

**ACTUAL**
Failed to open the Aspire Dashboard page
![image](https://github.com/dotnet/aspire/assets/72899617/2af995fe-4aa9-4c0f-94a7-19342da5a95c)
Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 

**Note**: This issue also repro on a clean machine with SDK 8.0.302 + Aspire 8.0.1 + azd [azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)].

**EXPECTED**
The Aspire Dashboard page successfully loaded
![image](https://github.com/dotnet/aspire/assets/72899617/f44ecce9-98c6-4a9a-81a4-826f17c796f7)

**Comment by samsp-msft** [comment]
@snehapar9 - can you take a look?

**Comment by snehapar9** [comment]
@v-bennettyue thanks for reporting this issue. It's a known error - This error occurs if roles/role bindings is not associated with the right service account so the dashboard client does not have the required permissions to display resources.

We are actively working on the fix. Will keep you posted when it gets rolled out.

Thank you for your patience.

**Comment by leslierichardson95** [comment]
@snehapar9 is there any update on this issue?

**Comment by kvenkatrajan** [comment]
Closing since fix has already been rolled out.
