### ISSUE TITLE
Add an API to easily extract a resource's environment variables as a dictionary

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#4464]
Resources are configured by way of setting environment variables in AppHost projects, e.g. calling `WithEnvironment`. In some scenarios it would be beneficial to be able to easily extract all the environment variable details for a resource as an `IReadOnlyDictionary<string, string?>` or similar, allowing for the values to be used in other contexts, e.g. injecting into the configuration of a `WebApplicationFactory` instance in a test.

We should add a method that makes it easy to get environment variable values for a resource, e.g.:

```diff
public static class ResourceExtensions
{
    public static bool TryGetEnvironmentVariables(this IResource resource, [NotNullWhen(true)] out IEnumerable<EnvironmentCallbackAnnotation>? environmentVariables)
+   public static Task<IReadOnlyDictionary<string, string?>> GetEnvironmentVariableValuesAsync(this IResourceWithEnvironment resource);
}
```

**Comment by davidfowl** [comment]
This needs to be async.

**Comment by DamianEdwards** [comment]
@davidfowl updated

**Comment by mitchdenny** [comment]
Update on this for work item review. the PR is close but we may wish to move the API into `Aspire.Hosting.Testing` given its usage scenario. If we are leaving it where it is, then we might want a few API tweaks (discussed in PR).
