### ISSUE TITLE
Endpoints refinements for 8.1

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4471]
This issue is tracking all of the endpoint refinements that we want to get for 8.1

- https://github.com/dotnet/aspire/issues/3456 (and https://github.com/dotnet/aspire/pull/4438)
- https://github.com/dotnet/aspire/issues/3749
- https://github.com/dotnet/aspire/issues/3786
- https://github.com/dotnet/aspire/issues/4470
- https://github.com/dotnet/aspire/issues/4521
- https://github.com/dotnet/aspire/issues/4472

**Comment by danmoseley** [comment]
#4472 is all that's left so closing and we can track that
