### ISSUE TITLE
Allow users to define what endpoints are selected as ASPNETCORE_URLS, HTTP/HTTPS_PORTS and Kestrel endpoints

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4472]
When defining endpoints on project resources, we have some default heuristics for expressing which of these endpoints are included in ASPNETCORE_URLS and which ones are included at publish time for HTTP/HTTPS_PORTS or if kestrel endpoints are defined, a way to use those.

We'd like to add some methods to allow overriding how these get included as an override in case you need to tweak the behavior. The ultimate escape hatch is setting the environment variable yourself as we don't override what users set, but maybe a more explicit way to configure set it would make sense.

This will be turned into an API proposal once we figure out the pattern.

**Comment by davidfowl** [comment]
I like the idea but should we do named based on a filter?

**Comment by davidebbo** [comment]
Agreed that a callback pattern makes sense.

Additional thoughts:
- `EndpointReference` should have some sort of Source field that indicates where it came from, e.g. Kestrel vs Automatic vs User
- Beyond disabling magic env injection, it would be good to have a way to get rid of endpoints.

Putting it all together (naming is shaky, so focus on concept first):

```c#
public static IResourceBuilder<ProjectResource> FilterEndpoints(
    this IResourceBuilder<ProjectResource> builder, Func<EndpointReference, EndpointFilterState> filter);

public enum EndpointFilterState
{
    Keep,
    KeepWithoutVarsInjection,
    Discard
}

public enum EndpointSource
{
    Automatic,
    KestrelConfiguration,
    UserDefined
}

var project = builder.AddProject<TestProject>("proj")
    .WithHttpEndpoint()
    .FilterEndpoints(e => {
        if (e.EndpointName == "hp1")
        {
            return EndpointFilterState.KeepWithoutVarsInjection;
        }
        else if (e.Source == EndpointSource.KestrelConfiguration)
        {
            return EndpointFilterState.Discard;
        }
        return EndpointFilterState.Keep;
    })
```

**Comment by davidebbo** [comment]
Alternative is to not return values from the callback, and make methods available to do `Discard()` and `SkipEnvironmentInjection()`, e.g.

```
    .FilterEndpoints(e => {
        if (e.EndpointName == "hp1")
        {
            e.SkipEnvironmentInjection();
        }
        else if (e.Source == EndpointSource.KestrelConfiguration)
        {
            e.Discard();
        }
    });
```

**Comment by davidfowl** [comment]
We want to keep endpoints references decoupled from how the project chooses to use them (synthetic or not), that's why I prefer a model that sets decides what endpoints to include and for what purpose.

> Beyond disabling magic env injection, it would be good to have a way to get rid of endpoints.

This should be available generally on all resources. @mitchdenny we can't do this today easily.

**Comment by davidebbo** [comment]
Ok, so to summarize, there are 3 things:
1. Ability to control which endpoints get injected as env variable. That's the core of this issue.
2. Some kind of Source property on endpoints so users can make category based decisions (e.g. do something only to endpoints coming from Kestrel). This is additive and could be done separately.
3. Ability to easily remove endpoints: that needs to apply to all resources, so let's keep it separate (should open new issue)

So focusing solely on 1. and tweaking the original proposal to be filter based, something like:

```c#
public static IResourceBuilder<ProjectResource> SkipEnvironmentInjectionForEndpoints(
    this IResourceBuilder<ProjectResource> builder, Func<EndpointReference, bool> filter)


var project = builder.AddProject<TestProject>("proj")
    .WithXxx()
    .SkipEnvironmentInjectionForEndpoints(e =>
    {
        return e.EndpointName == "hp1";
    })
```

Yeah, the name is ugly, and I'm open to suggestions.

**Comment by davidfowl** [comment]
```C#
public static IResourceBuilder<ProjectResource> BindHttpEndpoints(
    this IResourceBuilder<ProjectResource> builder, Func<EndpointReference, bool> includeFilter);

public static IResourceBuilder<ProjectResource> WithEndpointsInEnvironment(
    this IResourceBuilder<ProjectResource> builder, Func<EndpointReference, bool> includeFilter);

public static IResourceBuilder<ProjectResource> WithAspNetCoreUrls(
    this IResourceBuilder<ProjectResource> builder, Func<EndpointReference, bool> includeFilter);
```

```C#
var project = builder.AddProject<TestProject>("proj")
    .WithReference(cache)
    .BindHttpEndpoints(e =>
    {
        return e.EndpointName == "hp1";
    });
```

**Comment by davidebbo** [comment]
I see, so you're reversing the semantics from my `Skip` method.

My preference among those would be `WithEndpointsInEnvironment`. `BindHttpEndpoints` feels a little vague, and I think the name needs to include the word Endpoints, making `WithAspNetCoreUrls` not ideal.

But anyway, the important part is to agree on the pattern so I can look at implementing. We can always tweak the name a bit later.

**Comment by mitchdenny** [comment]
Why do we need another method, can't we make this a property on the endpoint itself and set it via the `WithEndpoint("name", Action<...> ...)` callback?

**Comment by davidfowl** [comment]
The endpoint shouldn't define how project resources use them.

**Comment by davidebbo** [comment]
Also, we want to be able to affect endpoints that don't come from an explicit WithXxx call, like Kestrel and default endpoints.

**Comment by davidebbo** [comment]
I went with the name `WithEndpointsInEnvironment`. Though one thing that slightly bothers me about it is that it makes it sound like if you don't call it, you don't get the environment, when it's more the opposite: you need to call it and return false to **not** get it. Not a huge deal, but slightly quirky.

Question: should the filter take in a `EndpointReference` or a `EndpointAnnotation`? I have the former now, but the latter makes it more consistent with `WithEndpoint` (the callback flavor). It also avoids creating throwaway `EndpointReference` wrappers that don't really add any value.

**Comment by davidfowl** [comment]
I think EndpointAnnotation just like WithEndpoint does

**Comment by davidebbo** [comment]
> I think EndpointAnnotation just like WithEndpoint does

Done.

**Comment by davidfowl** [comment]
Should the name of the method have http in it?

**Comment by davidebbo** [comment]
Yes, maybe `WithHttpEndpointsInEnvironment`? And obviously, we mean http or https, but it might not be clear to people, since there are distinct `WithHttpEndpoint` and `WithHttpsEndpoint` methods.
