### ISSUE TITLE
[AzureTools][Aspire] Fail to F5 a Aspire starter project with an error on Podman CLI 5.1.1

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#4476]
**Regression:** This issue **doesn't reproduce** on Podman CLI 5.1.0

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** 17.10.2 Preview 1.0 [35011.241.d17.10]
**Aspire Version:** 8.1.0-preview.1.24311.1 
Apply NuGet Feeds
**Podman Desktop:** 1.10.3
**Podman:** 5.1.1

**REPRO STEPS:**

1. Create a Aspire starter project with use Redis for caching checked.
2. Right click on AppHost project -> Open Folder in File Explorer.
3. Run the app in AppHost project path -> dotnet run.
4. Check whether no error pops up.

**Expect:**
No error pops up.

**Actual:**
An error pops up.
![image](https://github.com/dotnet/aspire/assets/62053665/7bf43683-91b5-4b00-a735-dd9ca0054975)
Another similar bug pops up after adding the environment variable DOTNET_ASPIRE_CONTAINER_RUNTIME=podman.
![image](https://github.com/dotnet/aspire/assets/62053665/1d1ca7b0-641f-443b-8b7a-f94c50416cb0)

**Comment by dbreshears** [comment]
@v-mengwe, have you verified podman is running correctly?   Try the suggestions such as 'podman system connection list' and 'podman machine init' and see if you get errors or not and share them.

**Comment by timheuer** [comment]
Just as a data point, I'm running Podman 5.1.1 and cannot repro -- after updating I did have to ensure that my podmane machin instance was running `podman machine start` (as noted in the output above)

**Comment by v-mengwe** [comment]
@dbreshears Thanks for the guidance. There is no system connection after executing 'podman system connection list' command.
![image](https://github.com/dotnet/aspire/assets/62053665/bfad137f-563c-471c-92df-a73cced3f479)
This issue can be fixed by the following workaround:
![image](https://github.com/dotnet/aspire/assets/62053665/ea8c03c5-a6b0-4bf9-9ca2-a187bf68595a)
Does this mean that we'd better execute this workaround to avoid this situation after every Podman CLI update?

**Comment by dbreshears** [comment]
@v-mengwe ,  I don't know if this is standard behavior with Podman after an update,  or specific to this update.   But you may need to in order to get Podman operational for use by Aspire.  Closing since no bug on this and external to Podman.
