### ISSUE TITLE
Serilog fails to integrate with Aspire structured logging view?

### ISSUE THREAD

**Issue by krzysiek-b** [dotnet/aspire#4490]
Hi,

I use Serilog to log and seems it does not work out of the box. For now it's not so clear which part of the code is failing. Is Serilog using its logger factory doing something which is not supported by .NET Aspire, or other way around?

https://github.com/serilog/serilog-extensions-hosting/issues/91

**Comment by davidfowl** [comment]
It's not an aspire issue not, it's a serilog issue. The answer is here https://github.com/serilog/serilog-extensions-hosting/issues/91#issuecomment-2164209934

**Comment by mitchdenny** [comment]
@davidfowl close?
