### ISSUE TITLE
[WebToolsE2E][Aspire] The aspire template should show ".NET Aspire Empty App" instead of ".NET Aspire Application" after installing Aspire 8.1 on non-ENU OS.

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#4495]
**REGRESSION INFO**: Not a Regression, it's a new change in Aspire 8.1

**INSTALL STEPS**
1. Clean machine: Win11 x64 22h2 FRA
2. Install SDK 8.0.302
3. Install Aspire 8.1.0-preview 1.24312.5

**REPRO STEPS**
1. Run the below code in CMD.
`dotnet new list aspire`

**Note**
1. This issue works well on ENU OS.

**ACTUAL**
The aspire template shows ".NET Aspire Application"
![Screenshot 2024-06-13 154450](https://github.com/dotnet/aspire/assets/88122107/ba3eed24-df5d-4ff9-9941-d6b5a8d9050c)

**EXPECTED**
The aspire template shows ".NET Aspire Empty App"
![Screenshot 2024-06-13 154531](https://github.com/dotnet/aspire/assets/88122107/56009809-5284-468c-9b3e-579dd89b10ad)

**Comment by thimok** [comment]
In the first image, it is using the French translation. It seems only the English locale has been updated to reflect the new name:
![image](https://github.com/dotnet/aspire/assets/20819818/124e58fc-d290-48fd-bcfd-e0fd16b203b4)

https://github.com/dotnet/aspire/commit/90cd4b58a78379650a584b297e4328fdd5319bb6

**Comment by balachir** [comment]
This seems related to @joperezr 's comments in https://github.com/dotnet/aspire/issues/4509#issuecomment-2168558664

**Comment by danmoseley** [comment]
this seems to be fixed in https://github.com/dotnet/aspire/pull/3924
it now has
>name": "Application vide .NET Aspire",

Please verify in next build.

**Comment by Rita003** [comment]
@danmoseley Verify the aspire template shows "Application vide .NET Aspire" on the latest Dev17.11 Preview 3 + Aspire 8.1 in non-ENU OS. But in the ENU OS, the aspire template shows ".NET Aspire Empty **App**" instead of ".NET Aspire Empty **Application**", I want to confirm if this is a problem?
![Screenshot 2024-07-02 151331](https://github.com/dotnet/aspire/assets/88122107/e7267aa1-bfc0-47dc-8387-8f8570349d65)
