### ISSUE TITLE
Dashboard: OTLP AnyValue is mapped to a string value which is insufficient for object graphs

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspire#4506]
The OTLP proto uses the type `AnyValue` throughout the type definitions when it is expressing a value. `AnyValue` is a variant equivalent, used to map strings, numbers booleans etc. From .NET telemetry production, today, we only use those types. However the proto spec for `AnyValue` can also contain arrays and maps. 

From [common.proto](https://github.com/dotnet/aspire/blob/bda316874feb6087ffee04eb6b0529574d40cf79/src/Aspire.Dashboard/Otlp/opentelemetry/proto/common/v1/common.proto#L28C1-L67C2): 
``` proto
// AnyValue is used to represent any type of attribute value. AnyValue may contain a
// primitive value such as a string or integer or it may contain an arbitrary nested
// object containing arrays, key-value lists and primitives.
message AnyValue {
  // The value is one of the listed fields. It is valid for all values to be unspecified
  // in which case this AnyValue is considered to be "empty".
  oneof value {
    string string_value = 1;
    bool bool_value = 2;
    int64 int_value = 3;
    double double_value = 4;
    ArrayValue array_value = 5;
    KeyValueList kvlist_value = 6;
    bytes bytes_value = 7;
  }
}

// ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
// since oneof in AnyValue does not allow repeated fields.
message ArrayValue {
  // Array of values. The array may be empty (contain 0 elements).
  repeated AnyValue values = 1;
}

// KeyValueList is a list of KeyValue messages. We need KeyValueList as a message
// since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need
// a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to
// avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches
// are semantically equivalent.
message KeyValueList {
  // A collection of key/value pairs of key-value pairs. The list may be empty (may
  // contain 0 elements).
  // The keys MUST be unique (it is not allowed to have more than one
  // value with the same key).
  repeated KeyValue values = 1;
}

// KeyValue is a key-value pair that is used to store Span attributes, Link
// attributes, etc.
message KeyValue {
  string key = 1;
  AnyValue value = 2;
}
```

The dashboard typically is converting instances of AnyValue to string [using](https://github.com/dotnet/aspire/blob/bda316874feb6087ffee04eb6b0529574d40cf79/src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs#L74C13-L83C11) 
``` c#
    public static string GetString(this AnyValue value) =>
        value.ValueCase switch
        {
            AnyValue.ValueOneofCase.StringValue => value.StringValue,
            AnyValue.ValueOneofCase.IntValue => value.IntValue.ToString(CultureInfo.InvariantCulture),
            AnyValue.ValueOneofCase.DoubleValue => value.DoubleValue.ToString(CultureInfo.InvariantCulture),
            AnyValue.ValueOneofCase.BoolValue => value.BoolValue ? "true" : "false",
            AnyValue.ValueOneofCase.BytesValue => value.BytesValue.ToHexString(),
            _ => value.ToString(),
        };
```
This doesn't account for these other types. 

The simple/hack fix would be to also convert these to strings, but we probably need to consider storing attributes with an equivalent to `AnyValue`, and have appropriate display functionality that can display a graph of values.

I am expecting this to become an issue with Event definitions in OTLP - which overlay over the logs specification. https://github.com/open-telemetry/oteps/blob/main/text/0202-events-and-logs-api.md. Events body will be an AnyValue which is typically going to be a dictionary/map.

**Comment by lmolkova** [comment]
thanks for creating the issue @samsp-msft !

I just realized it also reproduces with array attributes:

<img width="1051" alt="image" src="https://github.com/dotnet/aspire/assets/2347409/38d0545e-1d72-47b0-8382-03215395783b">

(attribute is of `ArrayValue`)
