### ISSUE TITLE
[WebToolsE2E][Aspire] Create a Blazor Web App select WebAssembly/Auto with aspire , add the code '.WithReplicas(2)', after running with F5, only one of the two additional pop-up URLs can be loaded normally

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#4512]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install Dev17.11 Preview 2 (Includes Aspire 8.0.0)

**REPRO STEPS**

New Project > Blazor Web App with render mode WebAssembly/Auto (Server and WebAssembly) > .NET 8.0 (Preview) > checked 'Enlist in Aspire orchestration' > Create
Add codes '.WithReplicas(2)' to Program.cs file under .AppHost project, F5 to run
![image](https://github.com/dotnet/aspire/assets/72899617/4f04fc60-9341-4b7b-9ded-3b4365bebf25)

**ACTUAL**
Only one of the two additional pop-up URLs can be loaded normally
![image](https://github.com/dotnet/aspire/assets/72899617/8b6cc1ac-1f5c-4296-80bc-cc89ec250f92)

**Notes**: You will encounter this bug [#4511](https://github.com/dotnet/aspire/issues/4511) on 17.10.x

**EXPECTED**
Both URLs can be loaded normally

**Comment by balachir** [comment]
@v-bennettyue can you clarify whether this issue reproduces using CLI? eg: on a clean machine with SDK 8.0.302 + Aspire 8.0.0 / Aspire 8.0.1 ? If yes, we should remove VS out from the INSTALL STEPS.

**Comment by v-bennettyue** [comment]
@balachir I didn't find a way to create a normal project plus aspire using only the CLI. If I create a Blazor Web App using VS, select WebAssembly/Auto with aspire, add the code '.WithReplicas(2)', and then open CMD to run dotnet run/dotnet watch, this issue cannot be repro.

**Comment by v-bennettyue** [comment]
I opened a [bug 2090883](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2090883) to track, so close this bug
