### ISSUE TITLE
Aspire local orchestrator crashes on shutdown if UDP endpoint is used

### ISSUE THREAD

**Issue by karolz-ms** [dotnet/aspire#4518]
### Repro steps
1. Create an Aspire application with custom resource like described here: https://github.com/dotnet/aspire/issues/4247#issuecomment-2127747960
2. `dotnet run` it
3. Shut down via Ctrl-C

### Expected
The app shuts down cleanly, including the dashboard process and all containers.

### Actual
Aspire dashboard process and all containers persist.

Looks like DCP is crashing on shutdown 😬

**Comment by karolz-ms** [comment]
The orchestrator controller process is crashing during app execution, before shutdown

**Comment by karolz-ms** [comment]
The fix will be part of Aspire 8.1 release.

**Comment by cecilphillip** [comment]
Thanks for fixing this.

**Comment by SvenVandenbrande** [comment]
What is the ETA for release 8.1?

**Comment by SvenVandenbrande** [comment]
@karolz-ms  That is another feed? The "daily" builds? Or ...

**Comment by karolz-ms** [comment]
@SvenVandenbrande https://github.com/dotnet/aspire/blob/main/docs/using-latest-daily.md
