### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#4520]
The [new Issue Page](https://github.com/dotnet/aspire/issues/new/choose) currently makes it look like you're only interested in Api proposals and security vulnerabilities.  Yes there is a "Open a blank issue" option but it's a bit hidden
![image](https://github.com/dotnet/aspire/assets/289860/24063e20-2738-4496-b8cd-9bfaa50e47eb)

Is it worth adding at least Feature & Bug templates so the New Issue page is a bit more welcoming, e.g. [aspnetcore](https://github.com/dotnet/aspnetcore/issues/new/choose)
![image](https://github.com/dotnet/aspire/assets/289860/d563d21d-8710-4a81-ad3a-58e0e917d73f)

**Comment by mitchdenny** [comment]
@maddymontaquila if I recall from a recent meeting you were interested in this area?
