### ISSUE TITLE
Add flag to disable reading kestrel configuration section for adding endpoints

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4521]
## Background and Motivation

We automatically read kestrel endpoints now after https://github.com/dotnet/aspire/issues/3456. This is a breaking change and we want to let users opt-out of this behavior just like they can opt out of the launch profile.

## Proposed API

```diff
namespace Aspire.Hosting;

public static class ProjectResourceBuilderExtensions
{
+  public static IResourceBuilder<ProjectResource> AddProject<TProject>(this IDistributedApplicationBuilder builder, string name, Action<ProjectResourceOptions> configure) where TProject : IProjectMetadata, new();
+  public static IResourceBuilder<ProjectResource> AddProject(this IDistributedApplicationBuilder builder, string name, string projectPath, Action<ProjectResourceOptions> configure)
}

+public class ProjectResourceOptions
+{
+    public string? LaunchProfileName { get; set; }
+    public bool ExcludeLaunchProfile { get; set; }
+    public bool ExcludeKestrelEndpoints { get; set; }
+}
```

## Usage Examples

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject<Projects.EventHubsConsumer>("consumer", o => o.ExcludeKestrelEndpoints = true);

builder.Build().Run();
```

## Alternative Designs

Another bool passed to both overloads of AddProject.

**Comment by KennethHoff** [comment]
`ExcludeConfiguration` feels very non-descript. What configuration is excluded? Kestrel configuration? Should it be called `ExcludeKestrelConfiguration` then?

**Comment by davidebbo** [comment]
> `ExcludeConfiguration` feels very non-descript. What configuration is excluded? Kestrel configuration? Should it be called `ExcludeKestrelConfiguration` then?

Agreed that `ExcludeConfiguration` is too vague.

@davidfowl did you mean for this flag to also disable reading the Kestrel EndpointDefaults Protocols? Note that we had logic for this before #3456.

If yes, then name it `ExcludeKestrelConfiguration`. If no, then we can go with `ExcludeKestrelEndpoints`.

**Comment by davidebbo** [comment]
@davidfowl Looking at this deeper, there is some really tricky semantics with the current overloads. Compare the following calls:

```c#
        appBuilder.AddProject<TestProject>("projectName");

        appBuilder.AddProject<TestProject>("projectName", launchProfileName: null);
```

They look equivalent, but the second explicitely causes launch profiles to be excluded. So there are really 3 scenarios:
1. Use the default launch profile (first overload)
2. Use the specific launch profile (second overload with a profile)
3. Disable all profile logic (second overload with null)

As a result, I don't think your proposed `ProjectResourceOptions` is sufficient, because it can't differentiate between 1. and 3. We may need to add an `ExcludeLaunchProfile` property to it.

**Comment by mitchdenny** [comment]
Couple of thoughts. How do you feel about `Action<ProjectResourceOptions>` instead of just the object argument. That way any inferred defaults could be applied?

**Comment by davidfowl** [comment]
> Couple of thoughts. How do you feel about Action<ProjectResourceOptions> instead of just the object argument. That way any inferred defaults could be applied?

I like that. I almost went that way initially but it does make it harder to just re-use options. Should it be another overload?

**Comment by davidfowl** [comment]
Updated the API

**Comment by mitchdenny** [comment]
Do we need a few more people from the team to cast an eye over this from an API review perspective. Want to make sure we are getting a broad enough set of opinions.

/cc @ReubenBond @eerhardt

**Comment by eerhardt** [comment]
I'm not sure I get the value of `Action<ProjectResourceOptions>` over just taking `ProjectResourceOptions`. "Any inferred defaults" can be applied in the constructor of `ProjectResourceOptions`. Do we expect the defaults to come from somewhere else in the future? (like configuration) If so, then the Action makes sense.

Other than that the API looks good to me. Just need to update the usage example, and add more `+` to the diff in the top comment to make it correct.

**Comment by davidfowl** [comment]
> Do we expect the defaults to come from somewhere else in the future? (like configuration) If so, then the Action makes sense.

Yep.
