### ISSUE TITLE
Flaky test: Aspire.Azure.Messaging.WebPubSub.Tests.ConformanceTests.LoggerFactoryIsUsedByRegisteredClient

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4547]
Aspire.Azure.Messaging.WebPubSub.Tests.ConformanceTests.LoggerFactoryIsUsedByRegisteredClient(registerAfterLoggerFactory: False, useKey: False)
Assert.Contains() Failure
Not found: Azure.Core
In value:  List<String> ["Microsoft.Extensions.Hosting.Internal.ApplicationL"..., "Microsoft.Extensions.Hosting.Internal.Host", "Microsoft.Hosting.Lifetime"]

cc @vicancy @eerhardt

**Comment by eerhardt** [comment]
How often have we seen this fail?

@vicancy - can you investigate?

**Comment by davidfowl** [comment]
Saw it once

**Comment by mitchdenny** [comment]
Adding the backlog while we collect more instances (would be good to get links to builds).

**Comment by vicancy** [comment]
Maybe race condition in https://github.com/dotnet/aspire/blob/main/tests/Aspire.Components.Common.Tests/TestLoggerFactory.cs#L18? It is not thread safe.
