### ISSUE TITLE
Dashboard trims spaces included in a project's name

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4550]
If you create a project with `dotnet new aspire-starter -t none -o "aspire  sta-rter.test-none"`, with the name including two spaces, then in the dashboard the `apiservice` project has it's path listed as `aspire sta-rter.test-none.ApiService.csproj`. Note the single space.

cc @JamesNK @joperezr

**Comment by mitchdenny** [comment]
![image](https://github.com/dotnet/aspire/assets/513398/86ad2bf7-927c-4b91-a569-31eb61527d42)

This looks like a case of HTML collapsing whitespace.

**Comment by mitchdenny** [comment]
@kvenkatrajan PTAL

**Comment by radical** [comment]
> ![image](https://private-user-images.githubusercontent.com/513398/340899500-86ad2bf7-927c-4b91-a569-31eb61527d42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjcyMjIsIm5iZiI6MTcxODc2NjkyMiwicGF0aCI6Ii81MTMzOTgvMzQwODk5NTAwLTg2YWQyYmY3LTkyN2MtNGI5MS1hNTY5LTMxZWI2MTUyN2Q0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMzE1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGEzMDJhOWE1N2ZhYWI5MjRlYTRhNmNhYzhlNGJkYzVjNDkwOTE2OThhZDE1ZWYxY2ZlZTMzZjIzYmM5NzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OIla1LVEfIweenio5vadQ2uWLoD0cczFigLCjwobW3Q)
> 
> This looks like a case of rendering collapsing whitespace. The HTML itself contains multiple spaces.

Interesting. I'm checking the value here - https://github.com/dotnet/aspire/blob/95aca25e7b61ac9cb26a1ed3b5a1b7e2cd50b010/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs#L165-L166

I wonder if I'm doing that wrong. This is the API being used - https://playwright.dev/dotnet/docs/api/class-locator#locator-inner-text

**Comment by radical** [comment]
The `title` on the `span` has the path with the correct spaces, but the "inner text" has a single space.

<img width="1094" alt="Screenshot 2024-06-18 at 23 59 47" src="https://github.com/dotnet/aspire/assets/1472/5c7fb9c0-9465-4498-9b0b-ad810f6e2c57">

**Comment by adamint** [comment]
> rendering collapsing whitespace

That devtools preview is not correct, if you double-click the text you will see that the inner text has multiple spaces, but they are collapsed due to our `white-space` property. I'll close this @radical 

<img width="1252" alt="image" src="https://github.com/user-attachments/assets/a5e4d997-bb84-457c-8e4f-01078c24ab4b">
