### ISSUE TITLE
Docs: Add docs for `GetEnvironmentVariableValuesAsync`

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/aspire#4551]
we add [GetEnvironmentVariableValuesAsync](https://github.com/dotnet/aspire/blob/0837fd06f7c9cc7571e9cb07721d814343ff59af/src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs#L68-L109) method at PR #4530

add some `<remarks>` which cover where this method is useful and considerations around the sync nature. As well as one or two `<example>` sections that cover its usage.

**Comment by mitchdenny** [comment]
Closing this since we wouldn't defer adding XML doc comments before merging the PR. XML doc comments should always go in with the PR that adds the API.
