### ISSUE TITLE
Azure storage emulator connection string does not work with container resources

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#4562]
We hardcode 127.0.0.1:

https://github.com/dotnet/aspire/blob/c3d1e743d3da450d6fdaf0ff8ad78cb423e7d9cf/src/Aspire.Hosting.Azure.Storage/AzureStorageResource.cs#L60-L62

**Comment by mitchdenny** [comment]
Adding to backlog for now.

**Comment by davidfowl** [comment]
I'm going to take a look at this one.

**Comment by davidfowl** [comment]
Turns out this isn't an issue because we replace strings coming from connection strings with the container host.
