### ISSUE TITLE
SignalR client (js) does not receive messages from hub when running through Aspire app host

### ISSUE THREAD

**Issue by jornhd** [dotnet/aspire#4563]
We have an application that has Vue 3 frontend, a BFF (.NET8) and a backend API (.NET8 WebApi). The API has a SignalR message hub and sends messages to the Vue client. We've used Project Tye to run this solution locally with great success, and now we wanted to migrate to Aspire. The migration went well, all the components runs fine and works together, except that the SignalR client stopped receiving messages. 
The server (api) is set to send messages on certain events, and the client is set to receive these messages with `connection.on("<messageType>", data)`
It seems to connect to the hub. The "negotiate" call (https) gets a response, but the next call using wss never gets a response. 
We've tried to change to both LongPolling and ServerSentEvent. Both seems ok, meaning that the network calls all gets 200, but the client never gets the messages from the server.
This was no problem prior to adding Aspire app host.
Does anyone have an idea of how this problem can be solved?

**Comment by mitchdenny** [comment]
If possible could you put together a minimal repro and post it up to GitHub so we can clone it down and take a look.

**Comment by davidfowl** [comment]
Putting this in 8.1. There are several issues people have reported with SignalR that we need to investigate.

- https://www.reddit.com/r/dotnet/comments/1dgn8a4/signalr_problem_with_net_aspire/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
- https://github.com/dotnet/aspire/discussions/2266
- https://github.com/dotnet/aspire/issues/1660

**Comment by jornhd** [comment]
I'm working on a repro. The minimal one (without access token) worked fine, so I need to add auth and possibly more until I get the error. But this takes time I don't really have, so it could be a while to get it done.

**Comment by jornhd** [comment]
Accidently closed.

**Comment by jornhd** [comment]
Closing this issue. There must have been some other issue that was causing the problem. Works fine now.
