### ISSUE TITLE
Exception thrown during startup of AppHost project

### ISSUE THREAD

**Issue by mvslegt** [dotnet/aspire#4611]
After adding .NET Aspire Orchestrator Support in Visual Studio to an existing solution (via the context menu Add> option). The xxx.AppHost project throws an exception during startup.

"**_Property CliPath: The path to the DCP executable used for Aspire orchestration is required.; Property DashboardPath: The path to the Aspire Dashboard binaries is missing._**"

StackTrace:

```
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in System.Threading.Tasks\Task.cs:line 1912
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in System.Threading.Tasks\Task.cs:line 2402
   at System.Threading.Tasks.Task.Wait() in System.Threading.Tasks\Task.cs:line 2352
   at Aspire.Hosting.DistributedApplication.Run() in /_/src/Aspire.Hosting/DistributedApplication.cs:line 338
   at Program.<Main>$(String[] args) in ..\xxx.AppHost\Program.cs:line 9

```
LaunchSetings:

`{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "profiles": {
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "https://localhost:17207;http://localhost:15102",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ENVIRONMENT": "Development",
        "DOTNET_DASHBOARD_OTLP_ENDPOINT_URL": "https://localhost:21229",
        "DOTNET_RESOURCE_SERVICE_ENDPOINT_URL": "https://localhost:22184"
      }
    },
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "http://localhost:15102",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ENVIRONMENT": "Development",
        "DOTNET_DASHBOARD_OTLP_ENDPOINT_URL": "http://localhost:19240",
        "DOTNET_RESOURCE_SERVICE_ENDPOINT_URL": "http://localhost:20141"
      }
    }
  }
}
`

When I create a new ASPIRE sample project from the Visual Studio ASPIRE project template, it starts without any problems.

Visual Studio Version: 17.10.2
.NET version: 8.0.300

**Comment by davidfowl** [comment]
Did you install the aspire workload?

**Comment by mvslegt** [comment]
I think there is an issue resolving the path to the dcp cli when the Aspire projects are installed in a nested folder structure. I had them installed in **_"C:\Users\slegtmar\sources\xxx\Products\Tools\xxx.AppHost"_**. When I install the Aspire projects in my **_"C:\Temp"_** folder, it seems to work fine.

**Comment by adampaquette** [comment]
Same issue here. I installed the workload from Visual Studio Installer, it failed then uninstalled and tried `dotnet workload install aspire`. I also copied the project to c:\temp and debugged but without success.
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maccatalyst                17.2.8053/8.0.100      VS 17.11.35017.193
ios                        17.2.8053/8.0.100      VS 17.11.35017.193
maui-windows               8.0.40/8.0.100         VS 17.11.35017.193
android                    34.0.113/8.0.100       VS 17.11.35017.193
```

**Comment by adampaquette** [comment]
In my case, I was doing a simple functional test and this error appeared.
```c#
[Fact]
public void Test()
{
    var options = new DistributedApplicationOptions { AssemblyName = typeof(Tests).Assembly.FullName, DisableDashboard = true };
    var appBuilder = DistributedApplication.CreateBuilder(options);
    var postgres = appBuilder.AddPostgres("CatalogDB")
        .WithImage("ankane/pgvector")
        .WithImageTag("latest");
    var app = appBuilder.Build();
    
    app.Run();
}
```

I added the following in my FonctionalTests.csproj to resolve the issue:
```
<PropertyGroup>
    <IsAspireHost>true</IsAspireHost>
</PropertyGroup>

<ItemGroup>
  <PackageReference Include="Aspire.Hosting.AppHost" />
</ItemGroup>
```

I only had a reference to `Aspire.Hosting.PostgreSQL` before.

Also, if I remvoe the 2 nugets, Rider proposes me to add `Aspire.Hosting` and I can compile with it but I can't run. It is kind of a tricky setup for onboarding.

**Comment by mitchdenny** [comment]
@mvslegt the `Aspire.Hosting.AppHost` dependency should be added to the AppHost project automatically from the template (its in the template!). Did you hand-craft the AppHost or did you use the built-in template?

**Comment by mvslegt** [comment]
I just used the built in template from Visual Studio.

**Comment by mitchdenny** [comment]
Oh wait ... it looks like you might be hitting a Windows path length issue. There is not much we can do on the .NET side about this unfortunately. FWIW I always put my source in a folder off root (e.g. `C:\Code`).

@adampaquette you mentioned you had to manually add `Aspire.Hosting.AppHost`?

**Comment by mvslegt** [comment]
@mitchdenny I actually doubt that that is the issue here. When I add the aspire projects in this folder "**C:\Users\slegtmar\sources\xxx" it gives the same error. Thats only a depth of 4 levels.

**Comment by mitchdenny** [comment]
@mvslegt can you do the following:

```dotnet new aspire-starter```

And add the result to a GitHub repo and share it here? I'm really curious about what you are experiencing and I'd like to be able to try and repro it.

**Comment by mitchdenny** [comment]
I'm not able to reproduce this on my side. Can you provide price instructions:

1. Open visual studio ...
2. File New Project (provide name specifics etc)

Alternatively, a short screen recording?

**Comment by mvslegt** [comment]
@mitchdenny Hmm crazy thing is I can't reproduce it either on  a new clean solution. Not even with the same depth of folder structure. It seems to be some sort of mishap due to the way this customer solution has been organized. Anyhow Thanx for your support. You may close this issue.
