### ISSUE TITLE
Display metrics exemplars in metrics table view

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#4639]
PR https://github.com/dotnet/aspire/pull/4629 adds exemplars to plotly graph. But they're not yet available in the table view.

**Comment by samsp-msft** [comment]
What I would propose for the table view is to add a column for the spanid, title, and show them if its available for that data point.

This may need some re-thinking of the histogram representation as we just show the P50, 90, 99 values. I would love to get more insight into the values in the buckets.
The other answer would be to show just a list of the histogram values that have exemplars and show those with the spanid & title.  You could have options to sort by timestamp or by value.

**Comment by JamesNK** [comment]
Design I came up with: https://github.com/dotnet/aspire/pull/4629#issuecomment-2191033744
