### ISSUE TITLE
Getting error To build this project, the following workloads must be installed: aspire even though this workload is installed

### ISSUE THREAD

**Issue by gdodd1977** [dotnet/aspire#4644]
Randomly I started getting the error NETSDK1147	To build this project, the following workloads must be installed: aspire during my build. I ran dotnet workload list and see this:

![image](https://github.com/dotnet/aspire/assets/29410398/9d20c918-df7c-45be-b400-00b770a97654)

I also confirmed in Visual studio installer that Aspire is installed.

![image](https://github.com/dotnet/aspire/assets/29410398/a1a773e9-fff7-4aeb-b0ad-3a99a7c72467)

Is there some cache I need to clear or something to fix this?

EDIT: I also did this and still getting same error:

![image](https://github.com/dotnet/aspire/assets/29410398/935a0a52-96f8-481b-9bcb-a11ffa5d11d7)

I'm on VS 2022 Version 17.10.3

**Comment by davidfowl** [comment]
cc @joperezr

**Comment by joperezr** [comment]
Thanks for the report, @gdodd1977. Can you please  run `dotnet --info` from the directory where you are trying to build your project? Could you also try to run `dotnet workload install aspire` to see if that fixes it?. I know you ran restore, but in some weird cases we've seen that calling install is actually fixing the issue.

**Comment by gdodd1977** [comment]
Thanks @joperezr! Looks like 'dotnet workload install aspire' worked!
