### ISSUE TITLE
Need a way to get to an IServiceProvider from EnvironmentCallbackContext

### ISSUE THREAD

**Issue by karolz-ms** [dotnet/aspire#4658]
Scenario: I am writing an environment callback handler and want to configure my resources slightly differently depending on what version of DCP I am using. To do this, I would like to get an instance of IDcpDependencyCheckService from a service provider. 

According to @mitchdenny there isn't a good way to do this today.

**Comment by mitchdenny** [comment]
@karolz-ms is this blocking for 8.1? Just thinking about priorities. I think it should be easy enough to do.

**Comment by karolz-ms** [comment]
@mitchdenny it would help, otherwise I would have to do a workaround that then would need to be taken out in subsequent releases.

**Comment by mitchdenny** [comment]
Addressed in #4668
