### ISSUE TITLE
Python support on build agents and helix machines

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#4659]
We want to run live tests of Aspire apps that involve the startup of python code (not in a container) In order to support this we need Python installed and in the path on build agents and helix machines.

**Comment by radical** [comment]
Both build and helix machines have python available.

**Comment by radical** [comment]
> Both build and helix machines have python available.

I tested by running the python tests in https://dev.azure.com/dnceng-public/public/_build/results?buildId=720618&view=results . Check the trx for `Aspire.Hosting.Tests`.
