### ISSUE TITLE
ApplicationLifecycleHook container starting/downloading progress status for dashboard

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/aspire#4664]
## Background and Motivation
during application startup containers may need to be downloaded and the dashboard should show the progress of the download status in terms of layer & percentage similar to the docker console; so that developers are aware the download is in progress and/or not slow or frozen/failed.

## Risks

**Comment by davidfowl** [comment]
This has been fixed in the main branch https://github.com/dotnet/aspire/pull/4601

**Comment by 3GDXC** [comment]
@davidfowl I've built aspire from the 'main' branch; however I'm not seeing any progress messages in the dashboard for containers that are downloading? where would I need to look for these? are these on the dashboard resource page front and centre are within the logs for the container?
