### ISSUE TITLE
Add tests for templates

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#47]
The templates currently have no unit test coverage. We should look at porting some of the template testing infrastructure from dotnet/aspnetcore to enable us to get some template test coverage.

**Comment by danmoseley** [comment]
@DamianEdwards we have some tests now, how would you describe the gap (or should we close this now)

**Comment by DamianEdwards** [comment]
Happy for engineering to decide as I haven't looked at the tests added. If we have basic coverage now of project create, build, run, publish from all our templates we can close and open specific issues to add missing coverage when necessary.
