### ISSUE TITLE
After 10K traces the count in the dashboard does not update

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#4706]
Refer to : https://github.com/microsoft/azure-container-apps/issues/1213

https://github.com/microsoft/azure-container-apps/issues/1213#issuecomment-2195497452

**Comment by JamesNK** [comment]
@snehapar9 Is the dashboard not updating with new traces, or has the number stopped at 10k? The number stopping at 10k is expected, as that's the in-memory limit. At that point, old traces are removed as new traces are added.

Continuing to increase the number without the data isn't technically possible.

What about adding an indication somewhere to the UI that the memory limit has been reached and old traces are being removed?

**Comment by leslierichardson95** [comment]
> @snehapar9 Is the dashboard not updating with new traces, or has the number stopped at 10k? The number stopping at 10k is expected, as that's the in-memory limit. At that point, old traces are removed as new traces are added.
> 
> Continuing to increase the number without the data isn't technically possible.
> 
> It seems like the problem is that the user thinks telemetry is no longer updating. What about adding an indication somewhere to the UI that the memory limit has been reached and old traces are being removed?

@JamesNK @kvenkatrajan could we consider adding a disclaimer like "The 10,000 most-recent traces are displayed"?  It could be added as a subtitle that persists under the Traces header.

**Comment by JamesNK** [comment]
There is a PR here: https://github.com/dotnet/aspire/pull/4799. The text is easy to change.

I don't think it should be something that is always displayed. The majority of the time the dashboard won't reach the maximum data limit. The message should be displayed in that situation, and not unnecessarily.
