### ISSUE TITLE
[AzureTools][Aspire] Fail to execute the `dotnet run` command with an error for a .NET Aspire Starter Application with redis checked when the Docker Desktop is Windows container

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#4715]
**Regression:** Not a regression, this issue also **reproduces** on VS 17.10.3 with Aspire 8.0.0

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10.3
**Aspire Version**: 8.0.2
Apply NuGet Feeds
**Docker Desktop:** 4.32.0

**REPRO STEPS:**

1. Make sure the Docker Desktop is Windows container.
2. Create a new .NET Aspire Starter Application with redis checked -> Run `dotnet run` in the AppHost.project folder.
3. Check whether succeeds to execute the command.

**Expect:**
1. Succeed to execute the command without any error.
2. [It would be better to make the error message clearer if Aspire does not support Docker Desktop Windows container](https://github.com/dotnet/aspire/issues/4717).

**Actual:**
Fail to execute the command with an error.
![image](https://github.com/dotnet/aspire/assets/62053665/42fefd08-cc2d-4bf1-914d-906516495d13)

**Comment by danegsta** [comment]
There isn't a Windows container image for the redis:7.2 image, which is what the error is reporting.

**Comment by davidfowl** [comment]
By design.
