### ISSUE TITLE
[WebToolsE2E][Aspire][Safari]The dashboard page is messed up and clicking any link does not work on MacOS.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#4716]
**REGRESSION INFO**: worked in Aspire 8.0.1 and Aspire 8.0.2

**INSTALL STEPS**

1. Clean machine: MacOS Sonoma(14.3) x64
2. Install latest released SDK 8.0.302 
3. Install Aspire 8.1 [8.1.0-preview.1.24328.1]
4. Apply dotnet8 feed

**REPRO STEPS**

1. Open Terminal, run following command to create an Aspire Starter App project
```
dotnet new aspire-starter -o aspire1
cd aspire1/aspire1.AppHost
dotnet run
```
2. Open dashboard url

**NOTE:**

- This issue does not repro on Edge browser, only on Safari.

**ACTUAL**
![image](https://github.com/dotnet/aspire/assets/71361488/422cf80b-2a0b-48cc-bdc2-4574198d8b4d)

**EXPECTED**
![image](https://github.com/dotnet/aspire/assets/71361488/13952dd9-e9d0-4347-8144-8f6a33551598)

**Comment by vnbaaij** [comment]
Ok, I know where this is coming from. Will revert that change in v4.8.2

**Comment by v-sherryfan** [comment]
Not repro on Aspire 8.1.0-preview.1.24328.6
