### ISSUE TITLE
Enable Aspire projects to use multiple ports configured in ASPNETCORE_URLS or applicationUrl

### ISSUE THREAD

**Issue by vfportero** [dotnet/aspire#4727]
For our multitenant environment, we have configured multiple HTTPS ports for the API project on localhost as follows:

```
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "profiles": {
    "Lucera.Api.SignUp": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "https://localhost:40501;https://localhost:40502;https://localhost:40503;https://localhost:40504;https://localhost:40507;https://localhost:40508"
      },
      "applicationUrl": "https://localhost:40501"
    }
  }
}
```

When we run this launch profile directly, all the specified ports are mapped and work perfectly. However, when this profile is added to the AppHost Aspire project, only the first port works:

```
builder.AddProject<Projects.Lucera_Api_SignUp>("lucera-api-signup");
```
![image](https://github.com/Azure/azure-dev/assets/1107782/def2cc68-5120-4bbd-9334-b354c53e9da8)

In another ticket, I noticed that it is possible to map different ports using the applicationUrl property when the protocols (http & https) are different. However, when using the same protocol with multiple ports, only the last one works.

Is there a way to achieve this with Aspire?

Thank you!

**Comment by davidfowl** [comment]
Fixed in https://github.com/dotnet/aspire/pull/5481
