### ISSUE TITLE
Aspire Debugging in VS Code Exists with Code 0 if any project is setup to run and exit (i.e. like EF Core Migrations)

### ISSUE THREAD

**Issue by jhancock-taxa** [dotnet/aspire#4739]
If you have a project that runs and finishes then vs code exits the aspire host debugging and just gest "The program AppHost has exited with code 0 (0x0)." (Even if there is other projects that continue to run)

It works fine as long as you don't have a project that runs and exits. But since this will be common because of EF Core, this is important.

It works fine in VS.net and Rider.

**Comment by natelaff** [comment]
No comments on this yet? I have been banging my head as I've been trying to migrate from Windows to Mac using VS Code and getting my environment set up. Can confirm this issue exists with something like Migrations running. The host shuts down entirely. Did you find a workaround @jhancock-taxa ?

**Comment by bradygaster** [comment]
I ran into this working on a sample myself. I'll be investigating this behavior in both VS and VS Code and looking into a fix. I presume it'd be ideal that only the app doing the work that's expected to exit shut down, not the whole Aspire app. Agreed that's a frustrating opportunity.

**Comment by davidfowl** [comment]
I believe VS does not quit when the debugger is attached and this is a VS code debugger issue.

**Comment by davidfowl** [comment]
cc @WardenGnaw

**Comment by WardenGnaw** [comment]
This will happen with an older version of C# Dev Kit and C# Extension debugger.

With launching multiple processes, we also wanted to handle shutting down everything when the user stopped debugging. One issue was the migration processes that would exit early, and we accidently counted that as the processes terminating and should shut down everything.

This should not happen in the latest version of C# Dev Kit ([v1.11.6](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit)) + C# Extension ([v2.45.25](https://github.com/dotnet/vscode-csharp/releases/tag/v2.45.25)).

**Comment by davidfowl** [comment]
Closing this as fixed!
