### ISSUE TITLE
[WebToolsE2E][Aspire][Unstable] Create a web project with check 'Enlist in Aspire orchestration', code "builder.AddProject<Projects.WebApplication1>("webapplication1");" is not loaded

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#4746]
**REGRESSION INFO**: Worked in Dev17.11 P2 (Includes Aspire 8.0.0)

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install VS 17.12 Preview 1 from main branch
    - Web workload
    - Includes Aspire 8.0.0

**REPRO STEPS**
1. New Project > Razor Page > .NET 8.0 > checked 'Enlist in Aspire orchestration' > Create
1. After creating successfully, open Program.cs file of the AppHost project

**ACTUAL**
Code "builder.AddProject<Projects.WebApplication1>("webapplication1");" is not loaded
![image](https://github.com/dotnet/aspire/assets/72899617/73705be6-ddeb-4e94-a02c-5ed8ee7db627)
After running, there is nothing in the dashboard page
![image](https://github.com/dotnet/aspire/assets/72899617/124feb9c-03ae-4db7-84c7-6e78516947dc)

**EXPECTED**
![image](https://github.com/dotnet/aspire/assets/72899617/6a93dffe-971c-4c72-a8a0-bc5595f8aba4)

**Comment by v-bennettyue** [comment]
this bug seems like a VS issue, so close this issue and link this [Bug 2113999](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2113999).

**Comment by v-bennettyue** [comment]
This issue not repro on Dev17.11 P4 [[buildId=9851025](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9851025&view=results)] from [PR 563340](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/563340).

**Comment by v-elenafeng** [comment]
Checked the fix with 17.11 P4 FB.
