### ISSUE TITLE
ConfigSchemaGenerator should ignore casing of configuration keys

### ISSUE THREAD

**Issue by bart-vmware** [dotnet/aspire#4773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using ConfigSchemaGenerator, the casing of segments in the config path should be ignored. This is because configuration keys in .NET are case-insensitive.

For example, the following entries should be merged into a single subtree:
```c#
[assembly: ConfigurationSchema("Management:Endpoints:Health", typeof(HealthEndpointOptions))]
[assembly: ConfigurationSchema("management:endpoints:Actuator", typeof(HypermediaEndpointOptions))]
```

I would expect the difference in casing to be ignored, so that the JSON fragment below is produced:
```json
{
  "type": "object",
  "properties": {
    "Management": {
      "type": "object",
      "properties": {
        "Endpoints": {
          "type": "object",
          "properties": {
            "Actuator": {},
            "Health": {}
          }
        }
      }
    }
  }
}
```

The actual behavior is that no unification takes place:
```json
{
  "type": "object",
  "properties": {
    "Management": {
      "type": "object",
      "properties": {
        "Endpoints": {
          "type": "object",
          "properties": {
            "Health": {}
          }
        }
      }
    },
    "management": {
      "type": "object",
      "properties": {
        "endpoints": {
          "type": "object",
          "properties": {
            "Actuator": {}
          }
        }
      }
    }
  }
}
```

The same problem possibly applies to the class properties.

### Anything else?

This should be easy to fix, because `JsonObject` has a constructor that takes a `JsonNodeOptions`, which contains the boolean property `PropertyNameCaseInsensitive`.

**Comment by eerhardt** [comment]
> /cc @eerhardt I'd be happy to work on a PR to address this.

Thanks. That would be appreciated!
