### ISSUE TITLE
Prompt failure:Handle Deployment to Cluster    Failed to apply manifests to cluster.  Error: Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by Alex-Yaf** [dotnet/aspire#4791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 ----Handle Deployment to Cluster----------------------------------------------------------------------------------------------------------
(!) Failed to apply manifests to cluster.
(!) Error: Value cannot be null. (Parameter 'path1')

### Expected Behavior

(!) Failed to apply manifests to cluster.
(!) Error: Value cannot be null. (Parameter 'path1')

### Steps To Reproduce

(!) Failed to apply manifests to cluster.
(!) Error: Value cannot be null. (Parameter 'path1')

### Exceptions (if any)

no

### .NET Version info

.net8

### Anything else?

use cmd

**Comment by davidfowl** [comment]
Is this an aspirate issue?

**Comment by youkezan** [comment]
I also encountered this problem

**Comment by youkezan** [comment]
aspirate run Can be deployed to k8s      
aspirate apply  can not

**Comment by youkezan** [comment]
i use minikube

**Comment by davidfowl** [comment]
Can you file this issue here https://github.com/prom3theu5/aspirational-manifests/issues
