### ISSUE TITLE
Help URL output when using DefaultAzureCredential 404s

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspire#4801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If using `DefaultAzureCredential` with Azure provisioning, the following log message is output:

https://github.com/dotnet/aspire/blob/2249f7d4d114784ed4f117a60b1b2963d971bd92/src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs#L324-L326

The `aka.ms` link given does not go to the intended documentation and instead lands the browser at `bing.com`.

### Expected Behavior

The link directs the user to the appropriate documentation.

**Comment by davidfowl** [comment]
cc @IEvangelist

**Comment by IEvangelist** [comment]
> cc [@IEvangelist](https://github.com/IEvangelist)

@davidfowl - I don't own that aka.ms link. Are you thinking that we should update the source to point to some new docs about this or something? @scottaddie, would you like this to point to your docs for the details on the `DefaultAzureCredential`?

**Comment by scottaddie** [comment]
@IEvangelist Yes, please. See https://aka.ms/azsdk/net/identity/credential-chains#defaultazurecredential-overview.

**Comment by IEvangelist** [comment]
See #6342
