### ISSUE TITLE
Exception in Aspire.Hosting when trying to call builder.AddAzureSearch() or .AddAzureStorage() using .NET 9

### ISSUE THREAD

**Issue by mcbeev** [dotnet/aspire#4802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In .NET 9, I'm trying to add either an AzureSearch resource or AzureStorage resouece to an AppHost project and I receive an exception in Aspire.Hosting.

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load type 'Aspire.Hosting.ApplicationModel.KnownResourceStateStyles' from assembly 'Aspire.Hosting, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.)
 ---> System.TypeLoadException: Could not load type 'Aspire.Hosting.ApplicationModel.KnownResourceStateStyles' from assembly 'Aspire.Hosting, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Aspire.Hosting.Azure.AzureProvisioner.<>c.<BeforeStartAsync>b__11_11(CustomResourceSnapshot s)
```

### Expected Behavior

I expected it to work and provision an Azure resource without error.

### Steps To Reproduce

```
var builder = DistributedApplication.CreateBuilder(args);

builder.AddAzureSearch("aisearch");

//or attempting: 
//var blobs = builder.AddAzureStorage("storage")

builder.Build().Run();
```

### Exceptions (if any)

Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load type 'Aspire.Hosting.ApplicationModel.KnownResourceStateStyles' from assembly 'Aspire.Hosting, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.)
 ---> System.TypeLoadException: Could not load type 'Aspire.Hosting.ApplicationModel.KnownResourceStateStyles' from assembly 'Aspire.Hosting, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Aspire.Hosting.Azure.AzureProvisioner.<>c.<BeforeStartAsync>b__11_11(CustomResourceSnapshot s)

### .NET Version info

.NET SDK:
 Version:           9.0.100-preview.5.24307.3
 Commit:            35b2c21ea6
 Workload version:  9.0.100-manifests.949230c4
 MSBuild version:   17.11.0-preview-24279-02+b963c24ef

**Comment by davidfowl** [comment]
This should be resolved now with later releses.
