### ISSUE TITLE
use icons for service status in dashboard

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#484]
Consider replacing the text in the State column with icons (plus accessible text through aria/hover) in order to reduce the wall of text on the dashboard and make it quicker and easier to scan for state.

I guess the possible states are Exited, FailedToStart, Paused, Pending, Removed, Running, Unknown 

We could do this short term with something like the open source bootstrap icons?

**Comment by davidfowl** [comment]
This is fixed in the latest
