### ISSUE TITLE
Failing test `Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4851]
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2492446&view=ms.vss-test-web.build-test-results-tab&runId=53858631&resultId=100204&paneView=debug

```
  Failed Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme [10 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Locator expected to be visible 
Call log:
  - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
  - waiting for GetByText("TestResource")
  Stack Trace:
     at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, FrameExpectOptions expectOptions, Object expected, String message) in /_/src/Playwright/Core/AssertionsBase.cs:line 84
   at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue[] expectedText, Object expected, String message, FrameExpectOptions options) in /_/src/Playwright/Core/AssertionsBase.cs:line 64
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightFixture.GoToHomeAndWaitForDataGridLoad(IPage page) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightFixture.cs:line 28
   at Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.<AppBar_Change_Theme>b__1_0(IPage page) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs:line 25
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightTestsBase.RunTestAsync(Func`2 test) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightTestsBase.cs:line 27
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightTestsBase.RunTestAsync(Func`2 test) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightTestsBase.cs:line 31
   at Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme() in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs:line 23
--- End of stack trace from previous location ---
```

This failed earlier also - https://dev.azure.com/dnceng-public/public/_build/results?buildId=735297&view=results

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "waiting for GetByText(\"TestResource\")",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng/internal/_build/results?buildId=2492446
**Error message validated:** `[waiting for GetByText("TestResource")`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/11/2024 1:42:31 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[771348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771348)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771348&view=ms.vss-test-web.build-test-results-tab&runId=19704690&resultId=100053)|dotnet/aspire#5087|
|[771310](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771310)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771310&view=ms.vss-test-web.build-test-results-tab&runId=19703914&resultId=100135)|dotnet/aspire#5168|
|[771302](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771302)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771302&view=ms.vss-test-web.build-test-results-tab&runId=19703604&resultId=100101)|dotnet/aspire#5201|
|[771281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771281)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771281&view=ms.vss-test-web.build-test-results-tab&runId=19703126&resultId=100258)|dotnet/aspire#5240|
|[770989](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770989)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770989&view=ms.vss-test-web.build-test-results-tab&runId=19696002&resultId=100204)|dotnet/aspire#5201|
|[770585](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770585)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770585&view=ms.vss-test-web.build-test-results-tab&runId=19683872&resultId=100063)|dotnet/aspire#5236|
|[2511721](https://dev.azure.com/dnceng/internal/_build/results?buildId=2511721)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2511721&view=ms.vss-test-web.build-test-results-tab&runId=53992387&resultId=100149)||
|[770078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770078)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770078&view=ms.vss-test-web.build-test-results-tab&runId=19666766&resultId=100087)|dotnet/aspire#5018|
|[2510728](https://dev.azure.com/dnceng/internal/_build/results?buildId=2510728)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2510728&view=ms.vss-test-web.build-test-results-tab&runId=53985297&resultId=100359)||
|[2507561](https://dev.azure.com/dnceng/internal/_build/results?buildId=2507561)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2507561&view=ms.vss-test-web.build-test-results-tab&runId=53963861&resultId=100198)||
|[2507219](https://dev.azure.com/dnceng/internal/_build/results?buildId=2507219)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2507219&view=ms.vss-test-web.build-test-results-tab&runId=53960307&resultId=100172)||
|[763318](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763318)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763318&view=ms.vss-test-web.build-test-results-tab&runId=19403762&resultId=100010)|dotnet/aspire#5123|
|[2504407](https://dev.azure.com/dnceng/internal/_build/results?buildId=2504407)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2504407&view=ms.vss-test-web.build-test-results-tab&runId=53938025&resultId=100075)||
|[2504341](https://dev.azure.com/dnceng/internal/_build/results?buildId=2504341)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2504341&view=ms.vss-test-web.build-test-results-tab&runId=53937069&resultId=100103)||
|[2502563](https://dev.azure.com/dnceng/internal/_build/results?buildId=2502563)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2502563&view=ms.vss-test-web.build-test-results-tab&runId=53927193&resultId=100300)||
|[746566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746566)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746566&view=ms.vss-test-web.build-test-results-tab&runId=18872026&resultId=100142)|dotnet/aspire#4925|
|[2497429](https://dev.azure.com/dnceng/internal/_build/results?buildId=2497429)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2497429&view=ms.vss-test-web.build-test-results-tab&runId=53890639&resultId=100162)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|9|17|

**Comment by radical** [comment]
@adamint could you please disable this test till it is fixed?

**Comment by sebastienros** [comment]
Multiple occurences today

```
  Failed Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme [7 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Locator expected to be visible 
Call log:
  - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
  - waiting for GetByText("TestResource")
  Stack Trace:
     at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, FrameExpectOptions expectOptions, Object expected, String message) in /_/src/Playwright/Core/AssertionsBase.cs:line 84
   at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue[] expectedText, Object expected, String message, FrameExpectOptions options) in /_/src/Playwright/Core/AssertionsBase.cs:line 64
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightFixture.GoToHomeAndWaitForDataGridLoad(IPage page) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightFixture.cs:line 28
   at Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.<AppBar_Change_Theme>b__1_0(IPage page) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs:line 25
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightTestsBase.RunTestAsync(Func`2 test) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightTestsBase.cs:line 27
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightTestsBase.RunTestAsync(Func`2 test) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightTestsBase.cs:line 31
   at Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme() in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs:line 23
```

I will disable it

**Comment by sebastienros** [comment]
@radical there is `[ActiveIssue("https://github.com/dotnet/aspire/issues/4623", typeof(PlaywrightProvider), nameof(PlaywrightProvider.DoesNotHavePlaywrightSupport))]
` on the class, should it still be running?

**Comment by radical** [comment]
> @radical there is `[ActiveIssue("https://github.com/dotnet/aspire/issues/4623", typeof(PlaywrightProvider), nameof(PlaywrightProvider.DoesNotHavePlaywrightSupport))] ` on the class, should it still be running?

That one will only skip the tests on OSes where we don't have playwright support right now, which is Linux. But it looks like the test is still failing on Windows, so disabling it till it is fixed makes sense.
