### ISSUE TITLE
Aspire Schema missing Dockerfile buildArgs spec

### ISSUE THREAD

**Issue by JonathanGiles** [dotnet/aspire#4864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Recently support for Dockerfile buildArgs was added in [this PR](https://github.com/dotnet/aspire/pull/2851), but it seems like the [latest schema](https://github.com/dotnet/aspire/blob/main/src/Schema/aspire-8.0.json) (or the [latest published schema](https://json.schemastore.org/aspire-8.0.json)) does not yet state that `buildArgs` is valid configuration on a `dockerfile.v0`.

### Expected Behavior

I would expect that given a valid `buildArgs`, such as that below, my IDE should not fail the json I am writing due to the schema validation failing. Example `buildArgs` that I expect to work:

```json
  "buildArgs" : {
    "BASE_IMAGE" : "${storage-explorer-image.image}"
  }
```

**Comment by mitchdenny** [comment]
Ah thanks for spotting this. We'll get this added into our version of the schema and update the test coverage. I'll also get it uploaded to schemastore.

**Comment by mitchdenny** [comment]
https://github.com/SchemaStore/schemastore/pull/4067
