### ISSUE TITLE
Extract Hosting Components tests project

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/aspire#4865]
We need to move the hosting components test from `Aspire.Hosting.Tests` to a separate project for each component.
for example, we did this for Redis at https://github.com/dotnet/aspire/pull/4468.

Also, we need to add  Functional tests for each component.

# Components:
- [ ] [Aspire.Hosting.Garnet.Tests](https://github.com/dotnet/aspire/pull/4871)
- [ ] Aspire.Hosting.Kafka.Tests
- [ ] Aspire.Hosting.MongoDB.Tests
- [ ] Aspire.Hosting.MySql.Tests
- [ ] Aspire.Hosting.Nats.Tests
- [ ] Aspire.Hosting.NodeJs.Tests
- [ ] Aspire.Hosting.Oracle.Tests
- [ ] [Aspire.Hosting.Postgres.Tests](https://github.com/dotnet/aspire/pull/4862)
- [ ] Aspire.Hosting.Python.Tests
- [ ] Aspire.Hosting.Qdrant.Tests
- [ ] Aspire.Hosting.RabbitMQ.Tests
- [ ] Aspire.Hosting.SqlServer.Tests
- [ ] Aspire.Hosting.Valkey.Tests
- [ ] [Aspire.Hosting.Elasticsearch.Tests](https://github.com/dotnet/aspire/pull/4430)
- [ ] [Aspire.Hosting.Keycloak.Tests](https://github.com/dotnet/aspire/pull/4289)
- [ ] [Aspire.Hosting.Milvus.Tests](https://github.com/dotnet/aspire/pull/4875)

**Comment by Alirexaa** [comment]
I will take care of this and send separate PRs for the rest of the components.
@eerhardt  @radical @mitchdenny @davidfowl

**Comment by radical** [comment]
cc @sebastienros

**Comment by eerhardt** [comment]
I'm currently working on Aspire.Hosting.Qdrant.Tests.

**Comment by eerhardt** [comment]
Duplciate of https://github.com/dotnet/aspire/issues/4294.
