### ISSUE TITLE
Trying to use AddExecutable to launch sqlpackage on startup, fails because it can't resolve connection string

### ISSUE THREAD

**Issue by drdr-kr** [dotnet/aspire#4940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a minimalist Aspire app up and running, which has SQL Server added using the Aspire hosting package

```
var sqldb = builder.AddSqlServer("sql")
    // Mount the init scripts directory into the container.
    .WithBindMount("./sqlserverconfig", "/usr/config")
    // Mount the SQL scripts directory into the container so that the init scripts run.
    .WithBindMount("./sqlsetup", "/docker-entrypoint-initdb.d")
    // Run the custom entrypoint script on startup.
    .WithEntrypoint("/usr/config/entrypoint.sh")
    .WithHealthCheck()
    ;

var addressBookDb = sqldb.AddDatabase("AddressBook");
```

I'm trying to launch sqlpackage as an executable during startup to bring the database up to the expected state like so

```
var sqlpackage = builder.AddExecutable("sqlpackage", "C:\\Dev\\Playground\\AspireApp1\\AspireApp1.AppHost\\sqlpackage\\sqlpackage.exe", Environment.CurrentDirectory, 
        "/Action:Publish", 
        "/SourceFile:../sqlsetup/db.dacpac",
        "/TargetConnectionString:\"%ConnectionStrings__AddressBook%\"")
    .WithReference(addressBookDb)
//.WaitFor(sqldb)
    ;
```

however, despite trying a few different formats I can't get sqlpackage to recognise the connection string. I think it's probably because the value is escaped when running it's not able to recognise the environment variable. I've tried

"/TargetConnectionString:\"%ConnectionStrings__AddressBook%\""
"/TargetConnectionString:\"$ConnectionStrings__AddressBook\""
"/TargetConnectionString:\"$ConnectionStrings__AddressBook$\""

![image](https://github.com/user-attachments/assets/02f7ffb8-a656-48ee-9f72-23e00351287a)

![image](https://github.com/user-attachments/assets/c8931576-7dd8-484c-a80c-2b811c28cc9a)

**Comment by ErikEJ** [comment]
You could also have a look at: https://www.nuget.org/packages/MSBuild.Sdk.SqlProj.Aspire
