### ISSUE TITLE
[AzureTools][Aspire] Logging output doesn't show in the "Console logs" window if the same resource is clicked after clicking "Select a resource" on the Dashboard

### ISSUE THREAD

**Issue by amnabatr1sha** [dotnet/aspire#4960]
**Regression:** A regression, this issue **doesn't reproduce** on Aspire 8.0.0

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10.5 Preview 1.0 [rel.d17.10-35117.246]
**Aspire Version:** 8.1.0-preview.1.24367.2
Apply NuGet Feeds

**REPRO STEPS:**

1. Launch VS and create a new project with 'Enlist in .NET Aspire orchestration' checked -> F5/Ctrl+F5 the project.
2. Click "View" of the project or container under the "Logs" in the Dashboard.
3. Click on "Select a resource" -> Click on the same resource as step 2.
4. Check whether there is logging output in the "Console logs" window.

**Expect:**
The logging output shows in "Console logs" window.
![image](https://github.com/user-attachments/assets/e77fe0aa-7557-4dc5-b57a-ef45be1f2015)

**Actual:**
The logging output doesn't show in "Console logs" window.
![Consolelog1](https://github.com/user-attachments/assets/659b338f-91e3-4131-8387-edf841490334)

**More Info:**
1. This issue **doesn't reproduce** when clicking directly on either resource.
2. This issue **doesn't reproduce** when clicking on either resource again (after the step 3).

**Comment by balachir** [comment]
@kvenkatrajan given that this issue is marked as a regression from 8.0 and Adam has a fix, should we consider this for 8.1? I've set the milestone to 8.1 with medium pri for now.

**Comment by v-mengwe** [comment]
Verify this issue fixed on the latest Aspire 8.1.0-preview.1.24368.5.

**Comment by amnabatr1sha** [comment]
Verified on VS 17.10.5 with Aspire 8.1.0, this issue doesn't reproduce.
