### ISSUE TITLE
Modify Milvus hosting resource to use generated password by default

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#4966]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Miluvs changed to support config-based password default (instead of global default) (see: https://github.com/milvus-io/milvus/issues/33058). This bug tracks modifying reacting to that change in the Aspire.Hosting.Milvus package to enable a generated default password if none provided, similar to other resources.  This will only work on a later tagged image of the milvus container image. /cc @eerhardt

**Comment by Alirexaa** [comment]
Milvus `2.4.7` was released recently, we should cover this PR in 8.2
