### ISSUE TITLE
Two elasticsearch tests failing, blocking CI

### ISSUE THREAD

**Issue by adamint** [dotnet/aspire#4968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Two tests are failing, blocking CI builds 
- Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTests.WithDataVolumeShouldPersistStateBetweenUsages
- Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTests.WithDataBindMountShouldPersistStateBetweenUsages

It has happened today in at least three builds
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=746622&view=ms.vss-test-web.build-test-results-tab&runId=18874030&resultId=100007&paneView=debug
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=746608&view=ms.vss-test-web.build-test-results-tab&runId=18873810&resultId=100000&paneView=debug
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=746566&view=ms.vss-test-web.build-test-results-tab&runId=18871958&resultId=100000&paneView=debug

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "at Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTests.*(WithDataVolumeShouldPersistStateBetweenUsages|WithDataBindMountShouldPersistStateBetweenUsages)",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[746747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746747)|dotnet/aspire|[Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTests.WithDataBindMountShouldPersistStateBetweenUsages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746747&view=ms.vss-test-web.build-test-results-tab&runId=18876886&resultId=100004)|dotnet/aspire#4967|
|[746622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746622)|dotnet/aspire|[Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTests.WithDataBindMountShouldPersistStateBetweenUsages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746622&view=ms.vss-test-web.build-test-results-tab&runId=18874030&resultId=100006)|dotnet/aspire#4957|
|[746566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746566)|dotnet/aspire|[Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTests.WithDataBindMountShouldPersistStateBetweenUsages](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746566&view=ms.vss-test-web.build-test-results-tab&runId=18871958&resultId=100000)|dotnet/aspire#4925|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|3|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=746622
**Error message validated:** `[at Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTests.*(WithDataVolumeShouldPersistStateBetweenUsages|WithDataBindMountShouldPersistStateBetweenUsages)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/18/2024 9:34:58 PM UTC

**Comment by eerhardt** [comment]
@Alirexaa - can you take a look?

**Comment by Alirexaa** [comment]
> @Alirexaa - can you take a look?

Hey @eerhardt, I can fix that but I don't have access to my pc until 2 next days (I mean Saturday).

If you can wait until Saturday, revert commit or disable test, after that i will fix that.

**Comment by eerhardt** [comment]
Ok, great!

There is no rush here. We are disabling the tests for now in https://github.com/dotnet/aspire/pull/4969/.
