### ISSUE TITLE
Failing `ConformanceTests.LoggerFactoryIsUsedByRegisteredClient` - missing log category

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4972]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=759099
Build error leg or test failing: 
Aspire.Azure.AI.OpenAI.Tests.ConformanceTests.LoggerFactoryIsUsedByRegisteredClient(registerAfterLoggerFactory: True, useKey: True)
Pull request: https://github.com/dotnet/aspire.git/pull/5108

```
Aspire.Azure.Messaging.WebPubSub.Tests.ConformanceTests.LoggerFactoryIsUsedByRegisteredClient(registerAfterLoggerFactory: False, useKey: False)

Assert.Contains() Failure
Not found: Azure.Core
In value:  ConcurrentBag<String> ["Microsoft.Hosting.Lifetime", "Microsoft.Extensions.Hosting.Internal.Host", "Microsoft.Extensions.Hosting.Internal.ApplicationL"...]

Stack trace
   at Aspire.Components.ConformanceTests.ConformanceTests`2.LoggerFactoryIsUsedByRegisteredClient(Boolean registerAfterLoggerFactory, Boolean useKey) in /_/tests/Aspire.Components.Common.Tests/ConformanceTests.cs:line 289
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```
Another instance:
```

Assert.Contains() Failure
Not found: Azure.Identity
In value:  ConcurrentBag<String> ["Azure.Core", "Microsoft.Hosting.Lifetime", "Microsoft.Extensions.Hosting.Internal.Host", "Microsoft.Extensions.Hosting.Internal.ApplicationL"...]
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Not found: Azure.(Identity|Core)",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=759099
**Error message validated:** `[Not found: Azure.(Identity|Core)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/29/2024 7:58:19 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
cc @eerhardt @vicancy

**Comment by vicancy** [comment]
Test is till failing despite https://github.com/dotnet/aspire/pull/4588/files, investigating

**Comment by radical** [comment]
Closing this as it hasn't been hit in at least a month.

**Comment by radical** [comment]
I think what would help for tests like this is to be logging the messages, so we can see which messages might have been unexpected, or missing that had these extra categories.
