### ISSUE TITLE
Providing the wrong project to `DistributedApplicationTestingBuilder.CreateAsync` causes tests to hang

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/aspire#4975]
I accidentally mistyped a test using `DistributedApplicationTestingBuilder.CreateAsync` and gave it the type of the test project rather than the AppHost project I wanted to test.

When the test started up, it proceeded to hang during the creation of the builder with no obvious reason or feedback as to what was wrong.

Through my debugging I found that it was hanging on this line: https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Testing/DistributedApplicationFactory.cs#L45

Further debugging seemed to suggest that the `TaskCompletionSource` `_builderTcs` never completed. Stepping through all the code, and it turns out that this line is hit: https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Testing/DistributedApplicationEntryPointInvoker.cs#L101

Since the `_appTcs` has an exception raised on it, `OnNext` (https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Testing/DistributedApplicationEntryPointInvoker.cs#L144-L156) method is never executed and the `_applicationBuilderListener`'s `OnNext` method (https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Testing/DistributedApplicationEntryPointInvoker.cs#L176) never runs, so the `_builderTcs` (which has been passed down) is never completed.

While it was a user error that resulted in this, it would be helpful if there was some information surfaced up on a failure to start the AppHost in a test (or the mistakenly provided project), rather than having the test hang indefinitely.

**Comment by ReubenBond** [comment]
This is likely already fixed in main, so hopefully you will not hit this issue once the next release is available

**Comment by aaronpowell** [comment]
Will that likely hit 8.1?

**Comment by ReubenBond** [comment]
Definitely

**Comment by ReubenBond** [comment]
This is the relevant PR: https://github.com/dotnet/aspire/pull/4331

**Comment by ReubenBond** [comment]
Closing for now, since this ought to be fixed in v8.1.0. If you are still seeing this, please open a new issue and reference this one.
