### ISSUE TITLE
[WebToolsE2E][Aspire][Unstable] After installing Aspire 8.1, opening and updating 8.0.0 project to 8.1, an unhandled error has occurred when navigating to Metrics in Aspire dashboard

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#4979]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.5
3. Install Aspire 8.1 [8.1.0-preview.1.24368.5]

**REPRO STEPS**

1. Open existing 8.0.0 Aspire Starter project, update the package "Aspire.Hosting.AppHost" to 8.1 
2. Build solution and run
3. Navigate to Metrics in Aspire dashboard and click each instrument

**ACTUAL**
The page shows "An unhandled error has occurred. Reload" with some errors in CMD: 

> Aspire.Hosting.Dashboard.Microsoft.AspNetCore.Components.Server.Circuits.CircuitsHost[111]
> Unhandled exception in circuit '2qtt4IHCIu5rjK13YEj08B-gKWQdQ6dk6fegIpV0'.
> System.ObjectDisposesException: Cannot access a disposed object.

![BUG](https://github.com/user-attachments/assets/63317cb5-9f08-49cb-bbd9-1120476c4536)

**NOTE**
1. When clicking on [Resources / Console / Structured / Traces] in the aspire dashboard the error disappears.
2. This issue is unstable and doesn't show up right away when navigating to Metrics
3. It doesn't repro when creating 8.1 aspire project

**EXPECTED**
There should be no errors when clicking on any instrument in the Metrics

**Comment by vmykagapuz** [comment]
I'm not able to reproduce the issue today with open existing 8.0.0 to 8.0.2 and open existing 8.0.0 to 8.1

**Comment by samsp-msft** [comment]
should probably go in 8.2

**Comment by balachir** [comment]
@samsp-msft jfyi, I gave this scenario a try now using Aspire 8.1 candidate build and I'm unable to reproduce this issue.

**Comment by vmykagapuz** [comment]
@balachir I can repro this issue today on 17.11 P7 FB, but it can only reproduce on the first creation of the project for aspire starter template.

**Comment by JamesNK** [comment]
Is that Aspire 8.1? There are changes that should prevent this error from happening in the latest dashboard built from the main branch.

**Comment by vmykagapuz** [comment]
@JamesNK Yes, I installed 17.11 P7 FB with aspire 8.1.0

**Comment by JamesNK** [comment]
As far as I know, there isn't a plan to keep updating 8.1. The next version will come from the latest source code, where this should be fixed, so it's just useful to know if it is still a problem there.

**Comment by vmykagapuz** [comment]
I verified this and it doesn't reproduce in Aspire 8.1.1
