### ISSUE TITLE
how to use  custom image tag?

### ISSUE THREAD

**Issue by FeiJerry** [dotnet/aspire#4998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/37815098-bf07-47f1-bf91-45cbb9b58606)

**What do I want to do with the latest version？**

![image](https://github.com/user-attachments/assets/f7ca66d8-b669-4940-885d-2e364fc7b57f)

**Comment by davidfowl** [comment]
Use [WithImageTag](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.containerresourcebuilderextensions.withimagetag?view=dotnet-aspire-8.0)
