### ISSUE TITLE
Let me change language of dashboard

### ISSUE THREAD

**Issue by rosieks** [dotnet/aspire#5009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When I launch Aspire dashboard it showes with Polish language. Most developers in Poland don't use polish language in development tools and all polish terms releted to programming sounds unfamiliar/funny for us. For that reason please provide a way to change UI language to English 

### Describe the solution you'd like

I would like to have UI to change language in Aspire Dashboard or other way to change language

**Comment by adamint** [comment]
@kvenkatrajan
