### ISSUE TITLE
[WebToolsE2E][Aspire] After installing SDK 9.0, create an aspire project and run dotnet watch, the line with URL + the token authentication information does not appear

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#5010]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK .NET 8.0.303
3. Install Aspire:
    - dotnet workload update
    - dotnet workload install aspire
4. Install SDK .NET 9.0 Preview 6

**REPRO STEPS**
1. Create an aspire project:
    - Open command line and run: dotnet new aspire -o aspire1
2. cd aspire1\aspire1.AppHost and run: dotnet dev-certs https
3. Run: dotnet watch

**Note**: This issue also repro after installing SDK 9.0 Preview 7.

**ACTUAL**
The line with URL + the token authentication information does not appear, 
![image](https://github.com/user-attachments/assets/2dfb3ab2-9870-411b-a1e1-e05470ff020b)

**EXPECTED**
Information display is normal
![image](https://github.com/user-attachments/assets/ba41b4d7-60de-4c1b-9791-48e9f4da7844)

**Comment by davidfowl** [comment]
This is a bug in the .NET SDK https://github.com/dotnet/sdk/pull/44290
