### ISSUE TITLE
[WebToolsE2E][Aspire] Opening the "Aspire Dashboard" URL for a deployed Aspire project fails with an error "Access to aspire-dashboard.xxx.io was denied"

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#5028]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.303
3. Install Aspire 8.0.2
4. Install latest released azd v1.9.5
5. Install git v2.45.2

**REPRO STEPS**
1. Open CMD, run following command to create an Aspire Starter App project and deploy it
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
azd init
azd up
```
2. After successful deployment, open the deployed "Aspire Dashboard" URL

**Note:**
1. This issue also repro on Aspire 8.1.0
2. Wait for a while and refresh the page manually, Aspire Dashboard can be displayed normally.

**ACTUAL**
Opening the deployed 'Aspire Dashboard' URL displays below. After waiting for a while and manually refreshing the page, it can be displayed normally.
![Screenshot 2024-07-23 172314](https://github.com/user-attachments/assets/66a35a6d-94e5-460e-aa95-866409266651)
![Screenshot 2024-07-23 171231](https://github.com/user-attachments/assets/90c8054d-bca7-4047-b762-742f28604144)

**EXPECTED**
![Screenshot 2024-07-23 172438](https://github.com/user-attachments/assets/da6aa334-32d9-41a6-a56f-a76d8c83ac27)

Error Log:
```
Access to aspire-dashboard.ext.greenmushroom-fc87ca70.eastus2.azurecontainerapps.io was denied, You don't have the user rights to view this page.
HTTP ERROR 403
```

**Comment by CoolIOT** [comment]
Hi there,

I encountered the same issue, which has significantly hindered my productivity. Please prioritize a fix for this problem.

thx
![Aspire-Dashboard-Error](https://github.com/user-attachments/assets/7cc99655-f494-472a-8557-5088e0f0db2b)

**Comment by v-elenafeng** [comment]
@balachir This issue has not occurred in the past 3 days. Can we consider closing this?

**Comment by Rita003** [comment]
This issue doesn't repro in recent tests, close it now.
