### ISSUE TITLE
CORS gets null after azd deploy

### ISSUE THREAD

**Issue by umnex** [dotnet/aspire#5029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Azure DevOps Pipelines to deploy Aspire. Once the container app is deployed, I use Azure portal to set CORS. After subsequent deployment, the CORS get empty.

### Expected Behavior

CORS should be persisted across deployments.

### Steps To Reproduce

1. Deploy an Aspire App using azd deploy
2. set CORS values using azure portal
3. Deploy the App again
4. Verify CORS in azure portal
5. CORS will be empty

**Comment by umnex** [comment]
Is there any update on this? I also tried setting an Environment Variable named CORS_ALLOWED_ORIGINS with an array containing the hosts but it doesn't work.

**Comment by vhvb1989** [comment]
Created https://github.com/Azure/azure-dev/pull/4325 to help here.  Yet another temp tactical customization until the AppHost can model everything about the ACA
