### ISSUE TITLE
Docker image is not being built when using `AddDockerFile`

### ISSUE THREAD

**Issue by SWarnberg** [dotnet/aspire#5052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since Azure Functions is not yet supported in Aspire, I thought that creating a Dockerfile in the Function project would give me better control in the deployed App. I get problems when Aspire deploys the project (like the gRPC error).

However, referencing the documentation at https://learn.microsoft.com/en-us/dotnet/aspire/app-host/withdockerfile, which states that you can specify a _Dockerfile to build_ when the app host is starting, the Docker image is **not** being built.

I've added the following to the app host project:
```csharp
builder.AddDockerfile("orders-functions", "../", "Orders.Functions/Dockerfile")
  .WithReference(orderDb);
```

When running the project, I can clearly see that the image is not being built. Instead, the console shows the following error, which indicates that the image should already exist.
```
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      could not create the container    {"Container": {"name":"orders-functions-vvcfhwtf"}, "Reconciliation": 8, "error": "CreateContainer command returned error code 1 Stdout: '' Stderr: 'Unable to find image 'orders-functions-image-bad8fa60d770c3ca8865d4b2b9fd99a6210f915d:latest' locally\nError response from daemon: pull access denied for orders-functions-image-bad8fa60d770c3ca8865d4b2b9fd99a6210f915d, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\n'"}
```

### Expected Behavior

According to the documentation, the docker image should be built when the app host is running. Or is there a step in the documentation that is missing?

### Anything else?

- .NET Aspire 8.1.0
- .NET 8.0
- Azure Functions v4, isolated runtime.

**Comment by davidfowl** [comment]
Did you update everything?

**Comment by SWarnberg** [comment]
Frameworks and packages? Yes, everything on latest version (as of today).

**Comment by rocklau** [comment]
same issue

**Comment by davidfowl** [comment]
Did you update the workload?

**Comment by ronnygunawan** [comment]
I updated the workload to 8.1.0. Didn't resolve the problem.

**Comment by rocklau** [comment]
fix now.`sudo dotnet workload update`

**Comment by rocklau** [comment]
Thanks guys.

**Comment by mhenry-cb** [comment]
For me, I had to update the workload and update Visual Studio from 17.10.4 to 17.10.5, and then it worked.

**Comment by SWarnberg** [comment]
Yes, now it works with latest workloads and versions.
