### ISSUE TITLE
Failing `SqlServer`, and `SqlClient` tests

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#5057]
Update: The tests have been updated to [work around](https://github.com/dotnet/aspire/pull/5058) this issue. But once the image is fixed, that should be reverted.

----
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=753141
Build error leg or test failing: Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/aspire/pull/5043

This is always failing on CI now.

[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-pull-5043-merge-a6140b7c8bf24e4189/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/1/console.784ba2f2.log?helixlogtype=result) trails with:
```
[testcontainers.org 00:09:47.16] Execute "/opt/mssql-tools/bin/sqlcmd -Q SELECT 1;" at Docker container b1bad4065fe2
[testcontainers.org 00:09:47.22] Execute "/opt/mssql-tools/bin/sqlcmd -Q SELECT 1;" at Docker container 122d54403432
[testcontainers.org 00:09:47.22] Execute "/opt/mssql-tools/bin/sqlcmd -Q SELECT 1;" at Docker container 5dc1ce5edf1a
Aborting test run: test run timeout of 600000 milliseconds exceeded.
```

Also, `Aspire.Microsoft.Data.SqlClient.Tests` ([log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspire-refs-pull-4850-merge-e899b6850f76437c9a/Aspire.Microsoft.Data.SqlClient.Tests/1/console.950b93a9.log?helixlogtype=result)) is failing.

cc @eerhardt @joperezr 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
More info in https://github.com/testcontainers/testcontainers-dotnet/issues/1220 and https://github.com/microsoft/mssql-docker/issues/892 .

**Comment by radical** [comment]
The tests are not really "disabled", but a workaround has been applied. I'm adding `disabled-tests` label here just so it can be tracked as a TODO.

**Comment by eerhardt** [comment]
@radical - can this be closed? We worked around the issue.
