### ISSUE TITLE
Allow resource properties to be marked as secret

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#5065]
Today, environment variables are shown in the UI as a series of dots (like a password mask) and the user must flip a toggle to show them. This prevents accidental disclosure to onlookers, such as when screen sharing.

We should add the same facility to resource _properties_, and allow each property to define whether it is a secret or not. Such secret properties would be displayed as masked in the UI by default.

**Comment by drewnoakes** [comment]
Pulled out of #2415.

**Comment by joperezr** [comment]
@drewnoakes is this on track for 8.2 milestone or should it get pushed?

**Comment by drewnoakes** [comment]
I'm working towards 8.2, yes.

**Comment by drewnoakes** [comment]
Work here is likely to conflict with #5266.

**Comment by drewnoakes** [comment]
PR in review https://github.com/dotnet/aspire/pull/5380
