### ISSUE TITLE
Console Logs incorrectly interleave stderr and stdout

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#5074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When an application writes to both stdout and stderr, the log lines in `Console logs` do not always end up in the expected order.

If running powershell with `1..100 |% { Write-Host "StdOut"; Write-Error "stderr"` then whilst the order of items in an individual stream is correct, the way in which items interleave between stdout and stderr is incorrect.  Sometimes you'll get all the stdout entries first, other times all the stderr lines first.  Occasionally logs will come up in some odd interleavings

![image](https://github.com/user-attachments/assets/3b357f4c-db99-4fd8-b764-e507429e0610)

### Expected Behavior

When running `1..100 |% { Write-Host "StdOut"; Write-Error "stderr"` in PowerShell directly, then lines match the order when running PowerShell natively - each line alternating between `stdout` and `stderr` in order

<img width="565" alt="image" src="https://github.com/user-attachments/assets/70b0198a-44fb-4594-a375-42707de943d0">

### Steps To Reproduce

```
builder
    .AddExecutable("temp", "pwsh.exe", ".")
    .WithArgs("-Command", "1..100 |% { Write-Host \"StdOut $_\"; Write-Error \"stderr $_\" } ")
    ;
```

### Exceptions (if any)

N/A

### .NET Version info

```
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.d7126b9e
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300, VS 17.10.35027.167
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  6.0.424 [C:\Program Files\dotnet\sdk]
  8.0.300-preview.24203.14 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\src\My App\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Anything else?

Possibly related to the ordering issue at https://github.com/dotnet/aspire/issues/4522#issuecomment-2187396105

**Comment by danmoseley** [comment]
Hi @afscrome is this related to .NET Aspire? If not then I'd suggest to close this and open the issue in https://github.com/PowerShell/PowerShell

**Comment by afscrome** [comment]
@danmoseley This is an aspire issue - the PowerShell example above is just a minimal repro.  I have seen this same ordering issue occur in other reosurces hosted through `AddExecutable`

A slightly clearer example can be seen with the following.  This simulates an app processing 10 items, in which the 7th fails.
```ps
1..10 |% {
   Write-Host $_;
   if($_ -eq 7) {
      Write-Error 'ERROR'
   } 
}
```

```cs
builder
    .AddExecutable("temp", "pwsh.exe", ".")
    .WithArgs("-Command", "1..10 |% { Write-Host $_; if($_ -eq 7) { Write-Error 'ERROR'}  }")
    ;
```

If you run this in PowerShell, you'll get the following output every time
![image](https://github.com/user-attachments/assets/640afbb6-7b67-4cda-a3a2-8f70c3e5b79e)

However run this through aspire, and the error can show up anywhere

![image](https://github.com/user-attachments/assets/ff3e6a72-99be-40cf-8b66-ade237b87ac4)
or on a second attempt
![image](https://github.com/user-attachments/assets/fdd2ea75-50e1-401f-b0b2-a8c796af5426)

The error being showing in the wrong place can at best be confusing and worst case send you on a wild goose change troubleshooting the issue.  With the first aspire screenshot, you may be confused how processing can fail before your app started to process the first time.  With the second screenshot, you may go off and assume the error happened processing the 10th item, and go and investigate that rather than the 7th item.

**Comment by JamesNK** [comment]
Yes this should be fixed
