### ISSUE TITLE
Aspire Hosting Testing failure to reach referenced container

### ISSUE THREAD

**Issue by maldworth** [dotnet/aspire#5076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running an integration test, the included container cannot be hit. If the Aspire App Host is ran normally with `F5`, it works.

### Expected Behavior

Running through the integration test, the referenced docker container should be able to be called by the API.

### Steps To Reproduce

This [reproduction repo](https://github.com/maldworth/AspireAppIntTestingIssue) is dead simple. It is the Aspire xUnit template, plus the addition of:
- [gotenberg container ](https://github.com/maldworth/AspireAppIntTestingIssue/blob/dfbcc1bae98c1a246a529a150f9c3e25ff2f29c8/AspireApp1.AppHost/Program.cs#L5)
- [an endpoint /generatepdf](https://github.com/maldworth/AspireAppIntTestingIssue/blob/dfbcc1bae98c1a246a529a150f9c3e25ff2f29c8/AspireApp1.ApiService/Program.cs#L44)
- an [integration test](https://github.com/maldworth/AspireAppIntTestingIssue/blob/dfbcc1bae98c1a246a529a150f9c3e25ff2f29c8/AspireApp1.Tests/ApiTests.cs#L24)

If you run the project normally, and just visit the endpoint https://localhost:7524/generatepdf  it works, and the output.pdf is downloaded.

If you run the integration test, it fails on this line: https://github.com/maldworth/AspireAppIntTestingIssue/blob/dfbcc1bae98c1a246a529a150f9c3e25ff2f29c8/AspireApp1.ApiService/Program.cs#L61

because it is unable to hit the gotenberg. My guess is this is something to do with binding/network of the test host being unable to hit the gotenberg endpoint.

### Exceptions (if any)

http 500, unable to hit the gotenberg server.

### .NET Version info

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.34944930
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.35027.167
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  7.0.317 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by ReubenBond** [comment]
Hi @maldworth please upgrade to Aspire 8.1 and let us know if that fixes this for you.

**Comment by maldworth** [comment]
Hello @ReubenBond

I just updated to 8.1 (and also updated the [reproduction repo](https://github.com/maldworth/AspireAppIntTestingIssue) too), and still the same error.

**Comment by maldworth** [comment]
Had some more time to dig deeper into this issue. Turns out added containers don't map with the https+http://<hostname>
so I followed the instructions here instead, and everything worked as expected

https://github.com/dotnet/aspire/discussions/4501
