### ISSUE TITLE
Container for Azure EventHubs emulator fails to startup successfully in Podman

### ISSUE THREAD

**Issue by jbparker** [dotnet/aspire#5097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The [local EventHubs emulator](https://learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-event-hubs-component?tabs=dotnet-cli#app-host-usage) does not startup successfully when using the **Aspire.Hosting.Azure.EventHubs** extension method [RunAsEmulator()](https://github.com/dotnet/aspire/blob/8b603eab5bb8934c0b9a3a1a7d9bb9edd5c2828b/src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs#L128).

Two containers (**eventhub** and **eventhub-storage**) are started, but the **eventhub** container fails with the message `Emulator Start up probe Unsuccessful. MetadataStore Health status: Unhealthy BlobStore Health status: Unhealthy`.

After failing the health checks, the event hub container eventually exits:

![podman-containers](https://github.com/user-attachments/assets/0091b11a-e9b0-40cb-b6e6-6a19a819ae26)

### Expected Behavior

EventHubs containers created by Aspire hosting should start, pass health checks, and be accessible for Aspire component usage.

### Steps To Reproduce

https://github.com/jbparker/AspireEventHub

Forked from https://github.com/davidfowl/AspireEventHub and updated to use [Event Hubs emulator](https://learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-event-hubs-component?tabs=dotnet-cli#app-host-usage) from https://github.com/dotnet/aspire/issues/3412

### Exceptions (if any)

The event hub container (`eventhubns`) logs health check errors:

> fail: a.a.aaW[0]
>       Emulator Start up probe Unsuccessful. MetadataStore Health status: Unhealthy BlobStore Health status: Unhealthy
> fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[103]
>       Health check Emulator Health Check with status Unhealthy completed after 27907.2647ms with message 'Emulator Start up probe Unsuccessful. MetadataStore Health status: Unhealthy BlobStore Health status: Unhealthy'
> Retry 1 encountered an exception: Emulator Health Check failed.. Waiting 00:00:00 before next retry.
> ... (meanwhile, after 2nd retry)
> An error occurred: Emulator Health Check failed.

Naturally, the `EventHubsConsumer` and `EventHubsApi` projects throw exceptions trying to access the emulated Event Hubs namespace.

Of note, the storage container (`eventhubns-storage`) has logs that show it was able to start _successfully_:

> Azurite Blob service is starting at http://0.0.0.0:10000
> Azurite Blob service is successfully listening at http://0.0.0.0:10000
> Azurite Queue service is starting at http://0.0.0.0:10001
> Azurite Queue service is successfully listening at http://0.0.0.0:10001
> Azurite Table service is starting at http://0.0.0.0:10002
> Azurite Table service is successfully listening at http://0.0.0.0:10002

### .NET Version info

**_.NET SDK:_** 8.0.303
**_Workloads:_** Aspire 8.1.0/8.0.100
**_Runtime environment:_** Windows, 10.0.22631
**_.NET runtimes:_** Microsoft.AspNetCore.App 8.0.7, Microsoft.NETCore.App 8.0.7, Microsoft.WindowsDesktop.App 8.0.7

### Anything else?

I'm unsure if this is an issue with using Podman or something dealing directly with Azurite/etc and not Aspire.

Using:

- .NET Aspire 8.1 packages/workload
- Podman version 5.1.1
- Visual Studio Enterprise 2022 v17.10.5

**Comment by davidfowl** [comment]
Same as https://github.com/dotnet/aspire/pull/4192

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/issues/5584

**Comment by davidfowl** [comment]
5584
