### ISSUE TITLE
Custom filtering by attributes in Traces

### ISSUE THREAD

**Issue by rolfik-mycronic** [dotnet/aspire#5100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Logs can be filtered by record attributes. I would like to filter also Traces and Metrics records like logs.
Thank You

### Additional context

Here is my context explained:
https://github.com/dotnet/aspire/issues/4103#issuecomment-2242326164

**Comment by JamesNK** [comment]
Metrics already have support for filtering by attributes.

Traces should have this feature.
