### ISSUE TITLE
[tests] Mismatched .bicep generated in `AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#5113]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=759660
Build error leg or test failing: Aspire.Hosting.Azure.Tests..AsAzurePostgresFlexibleServerViaRunMode
Pull request: https://github.com/dotnet/aspire/pull/5099

```
  Failed Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode [30 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 1390)
Expected: ···resource postgreSqlFirewallRule_T9qS4dcOa 'Microsoft.DBforPos···
Actual:   ···resource postgreSqlFlexibleServerDatabase_d6dHHd3yx 'Microsof···
                                 ↑ (pos 1390)
  Stack Trace:
     at Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode() in /_/tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs:line 1433
--- End of stack trace from previous location ---
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Expected: .*resource postgreSqlFirewallRule",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=759660
**Error message validated:** `[Expected: .*resource postgreSqlFirewallRule`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/29/2024 11:21:03 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[764179](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764179)|dotnet/aspire|[Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764179&view=ms.vss-test-web.build-test-results-tab&runId=19433412&resultId=100098)|dotnet/aspire#5155|
|[763604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763604)|dotnet/aspire|[Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763604&view=ms.vss-test-web.build-test-results-tab&runId=19413356&resultId=100026)|dotnet/aspire#5145|
|[763593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763593)|dotnet/aspire|[Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763593&view=ms.vss-test-web.build-test-results-tab&runId=19412342&resultId=100035)|dotnet/aspire#4943|
|[762906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762906)|dotnet/aspire|[Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762906&view=ms.vss-test-web.build-test-results-tab&runId=19392038&resultId=100044)|dotnet/aspire#5017|
|[761326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761326)|dotnet/aspire|[Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761326&view=ms.vss-test-web.build-test-results-tab&runId=19338284&resultId=100008)|dotnet/aspire#5110|
|[759974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759974)|dotnet/aspire|[Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759974&view=ms.vss-test-web.build-test-results-tab&runId=19293948&resultId=100082)|dotnet/aspire#5099|
|[759660](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759660)|dotnet/aspire|[Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode](https://dev.azure.com/dnceng-public/public/_build/results?buildId=759660&view=ms.vss-test-web.build-test-results-tab&runId=19283788&resultId=100017)|dotnet/aspire#5099|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|6|7|

**Comment by radical** [comment]
From the test log file:
```
[xUnit.net 00:00:06.20]     Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode [FAIL]
[xUnit.net 00:00:06.20]       Assert.Equal() Failure
[xUnit.net 00:00:06.20]                                        ↓ (pos 1390)
[xUnit.net 00:00:06.20]       Expected: ···resource postgreSqlFirewallRule_T9qS4dcOa 'Microsoft.DBforPos···
[xUnit.net 00:00:06.20]       Actual:   ···resource postgreSqlFlexibleServerDatabase_d6dHHd3yx 'Microsof···
[xUnit.net 00:00:06.21]                                        ↑ (pos 1390)
[xUnit.net 00:00:06.21]       Stack Trace:
[xUnit.net 00:00:06.21]         /_/tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs(1433,0): at Aspire.Hosting.Azure.Tests.AzureBicepResourceTests.AsAzurePostgresFlexibleServerViaRunMode()
[xUnit.net 00:00:06.21]         --- End of stack trace from previous location ---
[xUnit.net 00:00:06.21]       Output:
[xUnit.net 00:00:06.21]         targetScope = 'resourceGroup'
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         @description('')
[xUnit.net 00:00:06.21]         param location string = resourceGroup().location
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         @description('')
[xUnit.net 00:00:06.21]         param administratorLogin string
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         @secure()
[xUnit.net 00:00:06.21]         @description('')
[xUnit.net 00:00:06.21]         param administratorLoginPassword string
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         @description('')
[xUnit.net 00:00:06.21]         param keyVaultName string
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         resource keyVault_IeF8jZvXV 'Microsoft.KeyVault/vaults@2022-07-01' existing = {
[xUnit.net 00:00:06.21]           name: keyVaultName
[xUnit.net 00:00:06.21]         }
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         resource postgreSqlFlexibleServer_hFZg1J8nf 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' = {
[xUnit.net 00:00:06.21]           name: toLower(take('postgres${uniqueString(resourceGroup().id)}', 24))
[xUnit.net 00:00:06.21]           location: location
[xUnit.net 00:00:06.21]           tags: {
[xUnit.net 00:00:06.21]             'aspire-resource-name': 'postgres'
[xUnit.net 00:00:06.21]           }
[xUnit.net 00:00:06.21]           sku: {
[xUnit.net 00:00:06.21]             name: 'Standard_B1ms'
[xUnit.net 00:00:06.21]             tier: 'Burstable'
[xUnit.net 00:00:06.21]           }
[xUnit.net 00:00:06.21]           properties: {
[xUnit.net 00:00:06.21]             administratorLogin: administratorLogin
[xUnit.net 00:00:06.21]             administratorLoginPassword: administratorLoginPassword
[xUnit.net 00:00:06.21]             version: '16'
[xUnit.net 00:00:06.21]             storage: {
[xUnit.net 00:00:06.21]               storageSizeGB: 32
[xUnit.net 00:00:06.21]             }
[xUnit.net 00:00:06.21]             backup: {
[xUnit.net 00:00:06.21]               backupRetentionDays: 7
[xUnit.net 00:00:06.21]               geoRedundantBackup: 'Disabled'
[xUnit.net 00:00:06.21]             }
[xUnit.net 00:00:06.21]             highAvailability: {
[xUnit.net 00:00:06.21]               mode: 'Disabled'
[xUnit.net 00:00:06.21]             }
[xUnit.net 00:00:06.21]             availabilityZone: '1'
[xUnit.net 00:00:06.21]           }
[xUnit.net 00:00:06.21]         }
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         resource postgreSqlFirewallRule_t5EgXW1q4 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2023-03-01-preview' = {
[xUnit.net 00:00:06.21]           parent: postgreSqlFlexibleServer_hFZg1J8nf
[xUnit.net 00:00:06.21]           name: 'AllowAllAzureIps'
[xUnit.net 00:00:06.21]           properties: {
[xUnit.net 00:00:06.21]             startIpAddress: '0.0.0.0'
[xUnit.net 00:00:06.21]             endIpAddress: '0.0.0.0'
[xUnit.net 00:00:06.21]           }
[xUnit.net 00:00:06.21]         }
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         resource postgreSqlFlexibleServerDatabase_d6dHHd3yx 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-03-01-preview' = {
[xUnit.net 00:00:06.21]           parent: postgreSqlFlexibleServer_hFZg1J8nf
[xUnit.net 00:00:06.21]           name: 'db'
[xUnit.net 00:00:06.21]           properties: {
[xUnit.net 00:00:06.21]           }
[xUnit.net 00:00:06.21]         }
[xUnit.net 00:00:06.21]         
[xUnit.net 00:00:06.21]         resource keyVaultSecret_Ddsc3HjrA 'Microsoft.KeyVault/vaults/secrets@2022-07-01' = {
[xUnit.net 00:00:06.21]           parent: keyVault_IeF8jZvXV
[xUnit.net 00:00:06.21]           name: 'connectionString'
[xUnit.net 00:00:06.21]           location: location
[xUnit.net 00:00:06.21]           properties: {
[xUnit.net 00:00:06.21]             value: 'Host=${postgreSqlFlexibleServer_hFZg1J8nf.properties.fullyQualifiedDomainName};Username=${administratorLogin};Password=${administratorLoginPassword}'
[xUnit.net 00:00:06.21]           }
[xUnit.net 00:00:06.21]         }
[xUnit.net 00:00:06.21]         
```

Looking at the expected bicep in https://github.com/dotnet/aspire/blob/c3b47ef65b4234693f44c6255df7e9d4ab87a43c/tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs#L1397-L1431
.. the expected has:
```bicep
resource postgreSqlFirewallRule_T9qS4dcOa 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2023-03-01-preview' = {
  parent: postgreSqlFlexibleServer_hFZg1J8nf
  name: 'AllowAllIps'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '255.255.255.255'
  }
}

resource postgreSqlFlexibleServerDatabase_QJSbpnLQ9 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-03-01-preview' = {
  parent: postgreSqlFlexibleServer_hFZg1J8nf
  name: 'dbName'
  properties: {
  }
}
```

.. but the generated manifest has this instead:

```bicep
resource postgreSqlFlexibleServerDatabase_d6dHHd3yx 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-03-01-preview' = {
  parent: postgreSqlFlexibleServer_hFZg1J8nf
  name: 'db'
  properties: {
  }
}
```

The following code suggests that `AllowAllIps` is added for `Run` mode, but it is not being added here?
https://github.com/dotnet/aspire/blob/c3b47ef65b4234693f44c6255df7e9d4ab87a43c/src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresExtensions.cs#L73-L78


cc @mitchdenny

**Comment by mitchdenny** [comment]
@radical this build failure came from a PR, how do we know it wasn't something in the PR that caused it to fail?

(the error is surprising actually)

**Comment by radical** [comment]
> @radical this build failure came from a PR, how do we know it wasn't something in the PR that caused it to fail?
> 
> (the error is surprising actually)

Yeah, this was hit in https://github.com/dotnet/aspire/pull/5099 which doesn't seem to have any related changes, AFAICS.

**Comment by radical** [comment]
@mitchdenny this has been hit on 3 different PRs now.

**Comment by mitchdenny** [comment]
Yep. I'm going to disable the test and try to see if I can figure out what is going on.
