### ISSUE TITLE
Hosting Azure Storage does not return connection strings

### ISSUE THREAD

**Issue by Valkozaur** [dotnet/aspire#5115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to acquire the connection string of Azure Storage Blobs and Queues while executing the Aspire.Host project.
I tried everything I could think of but I did not manage to acquire it. 
Interesting enough when I pass the to my API project WithReference in the variables of the project I do receive the connection string.

### Expected Behavior

Be possible to acquire the connection string of the blob storage or queue on Aspire.Host run.

### Steps To Reproduce

```
using Microsoft.Extensions.Hosting;

var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");

var storage = builder.AddAzureStorage("Storage");

if (builder.Environment.IsDevelopment())
{
    storage.RunAsEmulator();
}

var blobs = storage.AddBlobs("BlobConnection");
var queues = storage.AddQueues("QueueConnection");

var blobConnectionString = blobs.Resource.ConnectionStringExpression.GetValueAsync(default);


var apiService = builder.AddProject<Projects.AspireTest_ApiService>("apiservice");

builder.AddProject<Projects.AspireTest_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(cache)
    .WithReference(apiService);

builder.Build().Run();
```

### Exceptions (if any)

```
System.InvalidOperationException: 'The endpoint `blob` is not allocated for the resource `Storage`.'
```

### .NET Version info

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.d7126b9e
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300, VS 17.10.35122.118
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by davidfowl** [comment]
You can't use the API that way. The resolution of those values are deferred because they are usually not ready during application startup. What are you trying to do?

**Comment by Valkozaur** [comment]
I am trying to run Kernel Memory service as a container. 
The container image of this service works by mounting a local appsettings.Development.json to the container internal appsettings.json file.

```
builder.AddContainer("kernel-memory", "kernelmemory/service", "latest")
    .WithImageRegistry("docker.io")
    .WithBindMount("kernel.memory.appsettings.Development.json", "/app/appsettings.Development.json", true)
    .WithEnvironment(callback => callback.EnvironmentVariables.Add("ASPNETCORE_ENVIRONMENT", "Development"));

async Task BuildKernelMemorySettings()
{
    var kernelMemorySettings = File.ReadAllText("kernel.memory.appsettings.Development.json");
    var openAiConnectionString = await openai.Resource.ConnectionStringExpression.GetValueAsync(default);
    var (openaiendpoint, openaikey) = ExtractEndpointAndKey(openAiConnectionString);

    var jsonNode = JsonNode.Parse(kernelMemorySettings);
    jsonNode["KernelMemory"]["Services"]["AzureOpenAIEmbedding"]["Endpoint"] = openaiendpoint;
    jsonNode["KernelMemory"]["Services"]["AzureOpenAIEmbedding"]["APIKey"] = openaikey;
    jsonNode["KernelMemory"]["Services"]["AzureOpenAIText"]["Endpoint"] = openaiendpoint;
    jsonNode["KernelMemory"]["Services"]["AzureOpenAIText"]["APIKey"] = openaikey;
    jsonNode["KernelMemory"]["Services"]["Qdrant"]["Endpoint"] = "https://localhost:6333";
    jsonNode["KernelMemory"]["Services"]["Qdrant"]["APIKey"] = qdrant.Resource.ApiKeyParameter.Value;
    //jsonNode["KernelMemory"]["Services"]["AzureBlobs"]["ConnectionString"] = await blobs.Resource.ConnectionStringExpression.GetValueAsync(default);
    //jsonNode["KernelMemory"]["Services"]["AzureQueues"]["ConnectionString"] = await queues.Resource.ConnectionStringExpression.GetValueAsync(default);

    File.WriteAllText("kernel.memory.appsettings.Development.json", jsonNode.ToString());
}
```

**Comment by Valkozaur** [comment]
@davidfowl Am I doing this right, is there a better way to achieve it?

**Comment by davidfowl** [comment]
Take a look at how WithPgAdmin works

https://github.com/dotnet/aspire/blob/232e434c79acd2bd1221ad05a5d2dd5118018804/src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs#L84

**Comment by Valkozaur** [comment]
Having a hook for when the container hooks up. That is a genius move. 
I will check if this was documented anywhere and otherwise I might suggest changes.

**Comment by Valkozaur** [comment]
Hey @davidfowl 
It worked flawlesly. I managed to aquire the connection strings. 
Though, I couldn't think of a good way to delay the container startup until the callback for setting endpoints was invoked. 

What would be the best way to achieve that?

**Comment by Valkozaur** [comment]
For whoever finds this I managed to aquire the connection strings like that:
var kernelMemory = builder.AddContainer("kernel-memory", "kernelmemory/service", "latest")
    .WithImageRegistry("docker.io")
    .WithBindMount("kernel.memory.appsettings.Development.json", "/app/appsettings.json")
    .WithEnvironment(callback => callback.EnvironmentVariables.Add("ASPNETCORE_ENVIRONMENT", "Development"))
    .WithReference(blobs)
    .WithReference(queues)
    .WithEnvironment(
        callback =>
        {
            var connectionString = callback.EnvironmentVariables["ConnectionStrings__blobs"];
            callback.EnvironmentVariables.Add("KernelMemory__Services__AzureBlobs__ConnectionString", connectionString);
        })
    .WithEnvironment(
        callback =>
        {
            var connectionString = callback.EnvironmentVariables["ConnectionStrings__queues"];
            callback.EnvironmentVariables.Add("KernelMemory__Services__AzureQueues__ConnectionString", connectionString);
        })
    ;

**Comment by davidfowl** [comment]
If you just want the value in a different environment variable then you can do this:

```C#
var kernelMemory = builder.AddContainer("kernel-memory", "kernelmemory/service", "latest")
    .WithImageRegistry("docker.io")
    .WithBindMount("kernel.memory.appsettings.Development.json", "/app/appsettings.json")
    .WithEnvironment(callback => callback.EnvironmentVariables.Add("ASPNETCORE_ENVIRONMENT", "Development"))
    .WithEnvironment("KernelMemory__Services__AzureBlobs__ConnectionString", blobs)
    .WithEnvironment("KernelMemory__Services__AzureQueues__ConnectionString", queues);
```

**Comment by Valkozaur** [comment]
Hey @davidfowl your code works, it also makes it super clean.. thanks.
Now I face another issue though, the generated connection string is:
```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://host.docker.internal:61222/devstoreaccount1;
```

When the container tries to create a queue I get an exception, I checked the azurite logs and this is the result:
```
-09-02T14:00:27.877Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 info: QueueStorageContextMiddleware: RequestMethod=PUT RequestURL=http://host.docker.internal/delete-generated-files RequestHeaders:{"host":"host.docker.internal:61572","x-ms-version":"2018-11-09","accept":"application/xml","x-ms-client-request-id":"3a95397e-18b5-4ce7-a40d-3ae9e763ded1","x-ms-return-client-request-id":"true","user-agent":"azsdk-net-Storage.Queues/12.18.0 (.NET 8.0.7; Alpine Linux v3.20)","x-ms-date":"Mon, 02 Sep 2024 14:00:22 GMT","authorization":"SharedKey devstoreaccount1:JOmKGBzEHz1pb5AQehQfdU7xpimHkEyXmu1GnVOrY8g=","content-length":"0"} ClientIP=192.168.127.1 Protocol=http HTTPVersion=1.1
2024-09-02T14:00:27.878Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 info: QueueStorageContextMiddleware: Account=delete-generated-files Queue=undefined Message=undefined MessageId=undefined
2024-09-02T14:00:27.879Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 verbose: DispatchMiddleware: Dispatching request...
2024-09-02T14:00:27.893Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
2024-09-02T14:00:27.895Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2024-09-02T14:00:27.907Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 error: ErrorMiddleware: ErrorName=UnsupportedRequestError ErrorMessage=Incoming URL doesn't match any of swagger defined request patterns.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders=undefined ErrorHTTPBody=undefined ErrorStack="UnsupportedRequestError: Incoming URL doesn't match any of swagger defined request patterns.\n    at dispatchMiddleware (/opt/azurite/dist/src/queue/generated/middleware/dispatch.middleware.js:41:30)\n    at /opt/azurite/dist/src/queue/generated/ExpressMiddlewareFactory.js:49:47\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/opt/azurite/node_modules/express/lib/router/index.js:328:13)\n    at /opt/azurite/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/opt/azurite/node_modules/express/lib/router/index.js:346:12)\n    at next (/opt/azurite/node_modules/express/lib/router/index.js:280:10)\n    at queueStorageContextMiddleware (/opt/azurite/dist/src/queue/middlewares/queueStorageContext.middleware.js:97:5)\n    at /opt/azurite/dist/src/queue/middlewares/queueStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (/opt/azurite/node_modules/express/lib/router/layer.js:95:5)"
2024-09-02T14:00:27.907Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 error: ErrorMiddleware: Set HTTP code: 400
2024-09-02T14:00:27.907Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 error: ErrorMiddleware: Set HTTP body: undefined
2024-09-02T14:00:27.908Z 6419cfd6-b51c-4dd7-98c0-32262af4fca5 info: EndMiddleware: End response. TotalTimeInMS=32 StatusCode=400 StatusMessage=undefined Headers={"server":"Azurite-Queue/3.31.0"}
```

I believe it might be because of the host.docker.internal dns resolution. 
Maybe the correct place for asking this question is the Azurite issues, if that is the case I will move the question there.
