### ISSUE TITLE
aspire-dashboard Structured logs -> Log entry details -> Resource attributes not always correct/seem cached

### ISSUE THREAD

**Issue by dlosch** [dotnet/aspire#5126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, 

when exporting otel logging data from a .NET app to both Seq and Aspire Dashboard (8.0.2 and 8.1.0 show same behavior), aspire dashboard doesn't seem to render attribute values under Structured logs -> Log entry details -> Resource -> attributes correctly at all times (sometimes it seems parts of the attributes get cached). 

First of all, displayed values for a specific log entry differ between seq (correct) and aspire dashboard (not correct).

1.) Run the app, attribute foo=value1
2.) Seq and Aspire dashboard display the entry with foo=value1
3.) stop app, change value to foo=newValue
4.) re run app
5.) Seq=>foo=newValue, aspire dashboard (no restart of container) foo=value1

Yesterday, with 8.0.2, I also had issues that some attribute pairs did not show up at all at times in aspire dashboard (not a rendering issue).

 

### Steps To Reproduce

- asp.net 8 app
- builder.Services.AddLogging(logging => logging.AddOpenTelemetry(openTelemetryLoggerOptions => {
            openTelemetryLoggerOptions.SetResourceBuilder(
[...]
                    .AddAttributes(new Dictionary<string, object> {
[...]

### .NET Version info

SDK 8.0.303
Runtime: 8.0.7
AOT publish

### Anything else?

Affects aspire-dashboard 8.1.0 and 8.0.2

**Comment by adamint** [comment]
I think the important part is here:

> 5.) Seq=>foo=newValue, aspire dashboard (**no restart of container**) foo=value1

**Comment by samsp-msft** [comment]
James - this seems like an issue with how we associate resources on each batch to the last. We probably need some kind of hash of all the resource properties to account for potential differences.

**Comment by JamesNK** [comment]
@dlosch What do you expect to happen when a resource adds and remove attributes?

For example:

1.) Run the app, attribute foo=true
2.) Seq and Aspire dashboard display the entry with foo=true
3.) stop app, change attribute to bar=true
4.) re run app
5.) ???

Should a resource now display foo and bar, or just bar?

**Comment by dlosch** [comment]
Would prefer option 3 if possible. I only superficially scanned over the open telemetry spec, but my interpretation was that the attributes are effectively scoped to the log entry (at least regarding the output)(?) Are resource attributes transmitted independently (and only if changed) from log entries and then correlated back, or are these attributes attached to each record (when adding a console logger, they are attached to each log entry)?

A quick test showed that Seq behaves as in option 3.

Otherwise, the dashboard is superb, has helped me track down several not obvious issues with aot (logging+metrics).

**Comment by liammclennan** [comment]
Seq stores all the resource data on all events - so Option 3.

**Comment by JamesNK** [comment]
Sounds like option 3 is the way to go. It will be a non-trivial change but hopefully not too difficult.

**Comment by JamesNK** [comment]
Fixed with https://github.com/dotnet/aspire/pull/5526
