### ISSUE TITLE
Provide ability to configure resource provisioning after creation

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/aspire#5127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When I'm using a provisioning package to create an Azure resource, I may want to do some configuration to that resource to adjust how it is provisioned (change SKU, enable/disable features, etc.).

The way we do that now is to pass a callback of the type `Action<IResourceBuilder<SomeAzureResource>, ResourceModuleConstruct, CDKResourceDef>` which is then called by Aspire when provisioning.

The problem is that if you want to create an extension that modifies something on the resource _after_ it has initially been added to the AppHost, it's not possible.

An example of this can be seen in [this (prototype) PR](https://github.com/dotnet/aspire/pull/4335), to enable Vector support I had to create a wrapper for the hosting package method. While this does work in isolation, it becomes a problem if I wanted to have another extension to do something, like enable CRYPTO, as I can't modify the callback.

### Describe the solution you'd like

It would be more preferable if the callback was attached to the `AzureConstructResource`, allowing you to create something like this:

```csharp
builder.AddPostgres("pg")
  .AsAzurePostgresFlexibleServer()
  .EnableVectors()
  .EnableCrypto();
```

The `AsAzurePostgresFlexibleServer` method could still take a callback, but it would add it to a stack of callbacks that are executed during the invocation of `AzureConstructResource.ConfigureConstruct`.

**Comment by davidfowl** [comment]
Fixed in https://github.com/dotnet/aspire/pull/4434
