### ISSUE TITLE
`WithDockerfile()` does not build the Dockerfile hence a container cannot be created.

### ISSUE THREAD

**Issue by mustafa-korkmaz** [dotnet/aspire#5158]
### Describe the issue or suggestion

I would like to see the `docker build` logs when a `WithDockerfile()` method is used. Currently, I always get an error as follows and cannot solve my problem.

```
Unable to find image 'redis-image-db61fbc162c74c1d7fcb3344f69e92b5c3063bf2:latest' locally\nError response from daemon: pull access denied for redis-image-db61fbc162c74c1d7fcb3344f69e92b5c3063bf2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\n'"}
```
This is how I try to create the Redis container
```csharp
IResourceBuilder<RedisResource> redis = builder
    .AddRedis("redis")
    .WithDockerfile("redis")
    .WithEndpoint("tcp", endpoint =>
    {
        endpoint.Port = 6379;
        endpoint.TargetPort = 6379;
    });
```

Below is the structure of my _redis_ folder
![image](https://github.com/user-attachments/assets/26bdaa7d-6086-4095-91eb-eb7d521bb136)

And here is my `Dockerfile` content
```
FROM redis

COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

**Comment by haacked** [comment]
I had a similar problem. It turned out that while I updated all the aspire libraries in my solution to 8.1.0, I hadn't updated the workload.

```bash
dotnet workload update
dotnet workload install aspire
```

And restarted my IDE. That fixed it for me.

**Comment by mustafa-korkmaz** [comment]
Yes, I was missing the update for the aspire workload. Thanks!
