### ISSUE TITLE
Consider adding support for Redis Insight as an alternative to RedisCommander

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/aspire#5165]
RedisInsight (https://github.com/RedisInsight/RedisInsight) is another popular (>5K stars on GitHub) web-based admin dashboard for Redis that should consider adding support to Aspire.Hosting.Redis

![Redis Insight Browser screenshot](https://raw.githubusercontent.com/RedisInsight/RedisInsight/main/.github/redisinsight_browser.png)

**Comment by samsp-msft** [comment]
I think this may be a components issue rather than dashboard as its the component that causes the container to be run etc.
