### ISSUE TITLE
[WebToolsE2E][Aspire] The Aspire dashboard "Details View" will be displayed when click on any unlinked section in the project line

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#5175]
**REGRESSION INFO:** Work in Aspire 8.1.0

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.303
3. Install Aspire 8.1.1-preview.1.24404.2
4. Apply feed

**REPRO STEPS**
1. Open CMD, create an Aspire Starter App using following commands:
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
```
2. Dotnet run the project in CMD, and open URL in the browser.
`dotnet run`
3. In the Resources, Click on any unlinked section in the project line

**Note:**
1. Hovering the mouse over the type any unlinked section in the project line, the mouse show a hyperlink gesture icon

**ACTUAL**
The "Details View" will be displayed
![Click](https://github.com/user-attachments/assets/c5c0ed03-ae9d-4965-9abf-20af3e53817f)

**EXPECTED**
The "Details View" does not appear when clicking any unlinked section in the project line.

**Comment by drewnoakes** [comment]
@Rita003 this was an intentional change, per https://github.com/dotnet/aspire/pull/5000.

**Comment by adamint** [comment]
Closing, see above comment for details.
