### ISSUE TITLE
[AzureTools][Aspire] The resource isn't redisplayed when dragging the left border of the dashboard until only details are displayed and then clicking the maximize icon on the page

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#5197]
**Regression Info:** A **Regression**, this issue doesn't reproduce on Aspire 8.1.0

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.12.0 Preview 2.0 [35205.153.main]
**Aspire Version:** 8.1.1-preview.1.24405.5
**azd Version:** 1.9.5
Apply NuGet Feeds

**REPRO STEPS:**
1. Create an Aspire starter project -> F5.
2. Click "View" under the Details -> Click the "Split vertical" icon -> Drag the left border to reduce the length of the Dashboard page until only the details are shown.
3. Click on the maximize icon on the page or drag the left/right border to grow the length of the Dashboard page.
4. Check whether the resource is redisplayed. 

**Expect:**
The resource is redisplayed.
![expect](https://github.com/user-attachments/assets/b6b1b484-ae7d-453d-a232-10bf6ba30b57)

**Actual:**
The resource isn't redisplayed, still only the details are shown.
![Actual](https://github.com/user-attachments/assets/1ae57182-a867-4b91-8a22-626028ab184e)

**More Info:**
This issue also **reproduces** when dragging the right border to reduce the length of the Dashboard page until only the details are shown.

**Comment by drewnoakes** [comment]
Another video of this issue:

![detail-view-snap](https://github.com/user-attachments/assets/ab854018-5a96-431b-8e8a-e1f3ab7c633e)
