### ISSUE TITLE
Upgrade EF components to 9.0

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/aspire#5207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

EF 9.0 introduced [engine-specific API for SQL Server, Azure SQL and Azure Synapse](https://github.com/dotnet/efcore/pull/34052).  If `UseAzureSynapse` or `UseAzureSql` is called by the user in `AddDbContext`, then `EnrichSqlServerDbContext` will throw, because it calls `UseSqlServer` and now that results in conflicting configuration.

EF 9.0 also has a [number of significant improvements](https://github.com/dotnet/efcore/issues?q=sort%3Aupdated-desc+is%3Aissue+label%3Aarea-aspire+milestone%3A9.0.0+is%3Aclosed+) for migrations scenarios relevant to Aspire.

### Describe the solution you'd like

`EnrichSqlServerDbContext` should call `ConfigureSqlEngine` with `EnableRetryOnFailureByDefault` instead of `UseSqlServer`.

Additionally, it and other EF components should call `ConfigureDbContext` instead of `PatchServiceDescriptor` as that depends on implementation details.

**Comment by davidfowl** [comment]
@sebastienros can you take this one?
