### ISSUE TITLE
[WebToolsE2E][Aspire] After successfully publishing an aspire project, navigate to any module on the dashboard, the module icon color does not change.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#5213]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.303
3. Install Aspire 8.1.0
4. Install latest released azd v1.9.5
5. Install git v2.46.0

**REPRO STEPS**

1. Open CMD, run following command to create an Aspire Starter App project and deploy it
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
azd init
azd up
```
2. After successful deployment, open the deployed "Aspire Dashboard" URL

**Note**: 
1. This issue also repro on Aspire 8.1.1-preview.1.24406.7
2. There is a similar bug [#4164](https://github.com/dotnet/aspire/issues/4164) about running aspire project

**ACTUAL**
Navigate to any module on the dashboard, the module icon color does not change.
![aspire1](https://github.com/user-attachments/assets/324d54f5-a6a8-4e5a-878d-c85366982210)

**EXPECTED**
Move to any module, the color of the module icon changes to purple
![image](https://github.com/user-attachments/assets/4f7ffac5-84e1-44fa-b7bf-8e182c8b9dc8)

**Comment by v-reinawang** [comment]
The version of the dashboard after publishing is 8.0.2. This is a known bug [#4510](https://github.com/dotnet/aspire/issues/4510).
![image](https://github.com/user-attachments/assets/0df1abab-aa83-45c9-bf05-9344508d6966)

Because of [this similar issue](https://github.com/dotnet/aspire/issues/4164) when running aspire project does not repro on Aspire 8.1.1. So is this issue related to the version of the dashboard after publishing?

**Comment by adamint** [comment]
@v-reinawang if it doesn't repro on 8.1.1, we can close

**Comment by v-reinawang** [comment]
@adamint I install Aspire 8.1.1, this issue will still repro after publishing the project.

After publishing, the version displayed on the dashboard is 8.0.2. I don't know if this issue is related to this.
![image](https://github.com/user-attachments/assets/1207028f-cf68-4422-b015-56b09ef5ea49)

**Comment by adamint** [comment]
This is an ACA issue, not our issue. See #4510 (last comment). They have not updated their dashboard version
