### ISSUE TITLE
Dynamically place login tooltip, preferring bottom

### ISSUE THREAD

**Issue by adamint** [dotnet/aspire#5214]
See https://github.com/dotnet/aspire/pull/5151

This would be blocked on fluentui-blazor adding the ability to select a preferred positioning for a tooltip.

**Comment by JamesNK** [comment]
Add a link to the feature request in fluentui-blazor repo please

**Comment by adamint** [comment]
Unfortunately, we are blocked on fluent webcomponents

https://github.com/microsoft/fluentui-blazor/issues/2491

There is no plan to add that feature, so I'm going to close this as not possible.
