### ISSUE TITLE
"View logs" link from Traces doesn't show logs

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#5228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking the "View Logs" link on a trace, I'd expect it to show logs assosciated with the trace, but instead it shows no results

![image](https://github.com/user-attachments/assets/db7f2e9d-19b4-49f2-9da7-d9e1093b6544)

Interestingly, if you click on the "Filter", then the field name seems to be missing

![image](https://github.com/user-attachments/assets/5c74ae06-7a3e-4722-b45e-50694d8ffba6)

If you add in the traceid filter, then traces do show up, and the filter in the url changes from `TraceId` to `log.traceid`

https://localhost:17127/structuredlogs?filters=TraceId:equals:a348a0cfcb70b0188d38a3ba0a97a68e
https://localhost:17127/structuredlogs?filters=log.traceid:equals:a348a0cfcb70b0188d38a3ba0a97a68e

### Expected Behavior

I'd expect clicking the"View Logs" link to show me all the logs associated with the trace
![image](https://github.com/user-attachments/assets/1a15837c-5d32-430c-8972-f770f1afc406)

### Steps To Reproduce

Click the "View Logs" link on a trace
<img width="613" alt="image" src="https://github.com/user-attachments/assets/7c003646-eebd-4d0d-816a-df1c5878fde3">

### Exceptions (if any)

N/A

### .NET Version info

```
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.d7126b9e
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300, VS 17.10.35027.167
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  6.0.424 [C:\Program Files\dotnet\sdk]
  8.0.300-preview.24203.14 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Anything else?

Aspire 8.1

**Comment by adamint** [comment]
@JamesNK

**Comment by JamesNK** [comment]
Thanks for reporting this.

This issue is a known bug in 8.1. It's fixed in https://github.com/dotnet/aspire/pull/5023. The next version of Aspire will include this fix.

**Comment by afscrome** [comment]
Awesome.  Thanks @JamesNK.
