### ISSUE TITLE
Running aspire project with only SDK 9.0 P6 / 9.0 P7 fails: "You must install or update .NET to run this application."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#5232]
**INSTALL STEP**
1. Repro OS: Windows/Linux/Mac OS
2. Install latest released sdk 9.0 P6
3. Install latest released Aspire 8.1.0
    - dotnet workload update
    - dotnet workload install aspire

**REPRO STEPS**

1. Open CMD, create an aspire starter app and run
    ```
    dotnet new aspire-starter -o aspire01
    cd aspire01/aspire01.AppHost
    dotnet run
    ```
**ACTUAL**
You must install or update .NET to run this application.
![image](https://github.com/user-attachments/assets/947dc7e5-66e2-47f3-a28c-6d078f3ad2e1)

**Note:**
- This issue also repro on sdk 9.0 P7
- Running normal web app is fine (Note: This refers to the 9.0 web app project, not 8.0)

**EXPECTED**
![image](https://github.com/user-attachments/assets/777498dd-fccf-4475-9f01-3e433bee5ef1)

**Additional Info**
C:\Users\v-sherryfan>dotnet --info
.NET SDK:
 Version:           9.0.100-preview.6.24328.19
 Commit:            ef4c241666
 Workload version:  9.0.100-manifests.21d7f649
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24328.19\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 9.0.100-preview.6
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.0-preview.6.24327.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24327.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by joperezr** [comment]
Moved. Also added you @marcpopMSFT to the aspire repo so you can do this in the future for other issues.

**Comment by balachir** [comment]
I talked to @v-elenafeng about this some more. The issue here is that net8 runtime is not installed, so this scenario will not work and that's By Design.
