### ISSUE TITLE
Parameter naming flexibility

### ISSUE THREAD

**Issue by pedershk** [dotnet/aspire#5237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The .AddParameter command today expects to find parameters in the Parameters configuration secftion or Parameters__ environment variable naming scheme. 

We have a more complex configuration setup that looks like this:

ServiceConfiguration:SubService:AzureMaps:Key (for example) in the configuration file.

We can't currently define this as a Parameter for publishing, since that would require us to read it from Parameters:AzureMapsKey instead. 

### Describe the solution you'd like

Is there a way for AddParameter to function correctly for publishing that would allow us to keep the current naming structure and say, provide an environment variable ServiceConfiguration__SubService__AzureMaps__Key to satisfy the parameter? As it stands today, we have to create an appsetings.production.json file on deployment and ignore the best practice of using .AddParameter to satisfy these parameters (of which we have many).

**Comment by pedershk** [comment]
#4429 Would solve this, I guess. Until then - does someone have an alternate way of approaching this - such as setting parameter value from a configuration item through some backchannel method?

**Comment by davidfowl** [comment]
Sounds like you're looking for AddParameterFromConfiguration from those set of methods. That won't pull the value for publish though as there's still a prompt that for the value (unless PublishDefaultValue is used).

**Comment by davidfowl** [comment]
cc @davidebbo

**Comment by davidebbo** [comment]
> unless PublishDefaultValue is used

But per our discussion, `PublishDefaultValue` would not result in pulling the value from config, right?

**Comment by davidfowl** [comment]
This is about which configuration section AddParameter looks at (IIUC).

**Comment by davidfowl** [comment]
Though I guess now you can do:

```
builder.AddParameter("param", builder.Configuration["ServiceConfiguration:SubService:AzureMaps:Key"]);
```

**Comment by davidebbo** [comment]
Right, or more fully:
```c#
builder.AddParameter("param", builder.Configuration["ServiceConfiguration:SubService:AzureMaps:Key"]).PublishDefaultValue();
```

Kind of ugly, though.

**Comment by pedershk** [comment]
> Though I guess now you can do:
> 
> ```
> builder.AddParameter("param", builder.Configuration["ServiceConfiguration:SubService:AzureMaps:Key"]);
> ```

Yes, this is a good solution now, and seems more in line with how the configuration system in .Net works on a whole, as this would cover all use cases of where the parameter is actually stored (config file, environment variable, and so on).

**Comment by davidebbo** [comment]
@pedershk is your goal to have the value coming from config be published? Or is it only to be used in Run mode?

**Comment by pedershk** [comment]
> @pedershk is your goal to have the value coming from config be published? Or is it only to be used in Run mode?

Ideally both. During publishing (GH Actions) it would be nice to set Environment variables to satisfy Parameters - in addition to what's been discussed here about their placement in Configuration.

Basically the ability to treat Parameters as if they were just another dotnet Configuration item.

**Comment by davidfowl** [comment]
> Ideally both. During publishing (GH Actions) it would be nice to set Environment variables to satisfy Parameters - in addition to what's been discussed here about their placement in Configuration.

That's an azd feature that already exists today.

@vhvb1989 did we document this yet?

**Comment by pedershk** [comment]
> > Ideally both. During publishing (GH Actions) it would be nice to set Environment variables to satisfy Parameters - in addition to what's been discussed here about their placement in Configuration.
> 
> That's an azd feature that already exists today.
> 
> @vhvb1989 did we document this yet?

Yes. I'm aware that it exists in general, but using it with Parameters today requires the Parameters__Parameter syntax. The suggestions in this thread linking it to Configuration system would work better than how it works today for us.

**Comment by davidfowl** [comment]
I think that changes the feature request. We need to describe the name of the environment variable where this parameter will come from in publish. The default value isn't what you want, nor is it the configuration key as it doesn't apply in deployment scenarios.

I like the idea though but it's not a default value, it's name of the env variable from which to get the default value. 

@davidebbo This adds another pivot to the many variables 😄

**Comment by pedershk** [comment]
Sorry to complicate things, but not sure what you mean here. If the Parameter is bound to the Configuration system like suggested - wouldn't that use environment. Variables by default if they're enabled for use in the configuration system?

**Comment by davidebbo** [comment]
@davidfowl what would the manifest look like when doing this? Would it be something like (making up some env syntax):

```json
            {
              "type": "parameter.v0",
              "value": "{pass.inputs.value}",
              "inputs": {
                "value": {
                  "type": "string",
                  "default": {
                    "value": "{env:MAPS_KEY}"
                  }
                }
              }
            }
```

And then whoever consumes the manifest would know to look up the `MAPS_KEY` env for that value?

**Comment by davidfowl** [comment]
Yes I was thinking of something like this

**Comment by davidebbo** [comment]
If we agree that a parameter (`publishAsEnvironment`, or whatever we call it) works better than a separate call, I can start working on it.

But we should also start the conversation about coming up with the right manifest schema for this. /cc @vhvb1989 @mitchdenny. What I have above (`"readFromEnvironment": "SOME_ENV_VAR"`) is just some random thing I came up with for illustration.

**Comment by davidebbo** [comment]
Actually, let's step back. Instead of explicitely having to state that the value can be set via some env variable, why not just say that in `azd deploy`, *any* parameter value can be set via environment, or equivalent command line switches?

**Comment by pedershk** [comment]
> Actually, let's step back. Instead of explicitely having to state that the value can be set via some env variable, why not just say that in `azd deploy`, _any_ parameter value can be set via environment, or equivalent command line switches?
> 
> This way, there is no change to Aspire, and it's generally available on all params. What's the drawback?

Agreed, that's the behavior I was expecting when first starting to explore parameters, to be honest.

**Comment by davidfowl** [comment]
Undocumented features:

https://github.com/Azure/azure-dev/issues/3597

**Comment by mitchdenny** [comment]
I really do think mapping parameters to environment variables is a deployment tool concept.

**Comment by davidebbo** [comment]
> Undocumented features:
> 
> [Azure/azure-dev#3597](https://github.com/Azure/azure-dev/issues/3597)

Long thread to read through. 🤯 Would be nice to have a concise summary of what the feature is somewhere. Though above. @pedershk [suggests](#issuecomment-2336754433) that this azd feature as it exists today is not ideal?

> I really do think mapping parameters to environment variables is a deployment tool concept.

Right, I think we're saying the same thing, and if so that there is no Aspire work needed here.

**Comment by davidfowl** [comment]
Closing this as not planned
