### ISSUE TITLE
Mask button position

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#5258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It feels wrong that buttons shift position on mouse overover when there is a mask button.

![image](https://github.com/user-attachments/assets/7ecba0d5-01ae-403b-bb02-f2fd2de334aa)

![maskbutton-position](https://github.com/user-attachments/assets/8f8ff338-2512-4951-bf34-c548a8c757b8)

### Expected Behavior

I think the default mask button position should be where the `...` button appears to avoid shifting.

**Comment by adamint** [comment]
We've changed the position of the menu icon so this no longer is an issue
