### ISSUE TITLE
[WebToolsE2E][Aspire] Create an Aspire Starter project, the Program.cs of the xxx.Web project is missing the line 'app.UseHttpsRedirection()'.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#526]
**INSTALL STEPS**

1. Clean machine: Win11 x64 22h2 ENU
2. Install VS 17.9 P1 from build main-34225.308
3. Install latest 8.0 SDK: 8.0.100-rtm.23525.5
4. Apply NuGet Feeds
5. Install Aspire workload

**REPRO STEPS**

1. In the VS, create a new project > Aspire Starter Application > .NET 8.0 > Create
2. Open Program.cs of xxx.Web project.

**ACTUAL**
The Program.cs of the xxx.Web project is missing the line `app.UseHttpsRedirection()`, which is there in web apps.
![image](https://github.com/dotnet/aspire/assets/82028229/a274b3fe-6962-450c-854a-975ed8dff119)

**Some notes:**

1. This issue doesn't repro on web project with 'Enlist in Aspire' option checked.
2. Due to this issue, clicking the different endpoint urls on the dashboard, will navigate to the corresponding links. Will not navigate to the same "https://" link as the web app.

**EXPECTED**
Like there in the web project:
![image](https://github.com/dotnet/aspire/assets/82028229/cca75a16-aa8a-4c65-beb2-95ae09752e65)

**Comment by joperezr** [comment]
Moving to Preview 5 in favor of removing milestone preview TBD.

**Comment by DamianEdwards** [comment]
Part of #2453
