### ISSUE TITLE
[tests] `DockerApiException` - `https://netaspireci.azurecr.io/v2/library/redis/manifests/7.2` - `Connection refused`

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#5284]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=775071
Build error leg or test failing: Aspire.StackExchange.Redis.Tests.AspireRedisExtensionsTests.Aspire.StackExchange.Redis.Tests.AspireRedisExtensionsTests.CanAddMultipleKeyedServices
Pull request: https://github.com/dotnet/aspire/pull/5252

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "DockerApiException : Docker API responded with status code=InternalServerError.*Get.*https://netaspireci.azurecr.io.*connect: connection refused",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=775071
**Error message validated:** `[DockerApiException : Docker API responded with status code=InternalServerError.*Get.*https://netaspireci.azurecr.io.*connect: connection refused`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/14/2024 1:15:32 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[775071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775071)|dotnet/aspire|[Aspire.StackExchange.Redis.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775071&view=ms.vss-test-web.build-test-results-tab&runId=19825846&resultId=101371)|dotnet/aspire#5252|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by eerhardt** [comment]
My guess is that ACR was having issues last night. Hopefully they are resolved today.

**Comment by radical** [comment]
> My guess is that ACR was having issues last night. Hopefully they are resolved today.

Haven't seen that again today. This can be re-opened if it is hit again. Closing.
