### ISSUE TITLE
Create DashpageChart component to render a single chart in a dashpage

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#5287]
When showing a single metric, we make generous use of the screen real estate.

For dashpages, we'll want a more constrained view, as we want to show multiple metrics in the same area.

We need a component that displays:

- A chart
- A table
- A means to toggle between chart/table
- A means to show the filter

The toggle and filters should be accessed via a discrete icon in the corner. They must be accessible.

---

## Single metric view

![image](https://github.com/user-attachments/assets/1c4280d8-1edf-46fd-b0e9-7a897e532b01)

## DashpageChart view (proposed)

Similar to Azure Data Explorer dashboard components:

![image](https://github.com/user-attachments/assets/b11aac7a-5467-4923-afa2-2360a44e30df)

**Comment by adamint** [comment]
We need to rebase main onto feature/dashpages in order to get some necessary components - specifically `GridColumnManager`. We ned it to allow us to show filters properly

(the value updates toggle has also not yet been added)
