### ISSUE TITLE
Custom filters in dashboard traces

### ISSUE THREAD

**Issue by lvde0** [dotnet/aspire#5290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am using the standalone dashboard and would really like to filter the traces for properties (e.g. http status code, or custom ones I enriched the spans with). Are there any plans to implement that?

### Describe the solution you'd like

Filter option similar to the one in structured logs.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/pull/5984

**Comment by JamesNK** [comment]
Duplicate of https://github.com/dotnet/aspire/issues/5100

Already done and will ship in Aspire 9.
