### ISSUE TITLE
Local build should not require npm

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspire#5292]
Repro:

Vanilla OS, clone

```
./build.sh
```

Result:

```
/home/aspnet/src/aspire/playground/BrowserTelemetry/BrowserTelemetry.Web/BrowserTelemetry.Web.csproj(25,5): error MSB3073: The command "npm install" exited with code 127.
```

**Comment by sebastienros** [comment]
@JamesNK

**Comment by radical** [comment]
Even if you have npm installed, on a fresh build I get:
`Module not found : error : Can't resolve './scripts/index.js' in '/workspaces/aspire/playground/BrowserTelemetry/BrowserTelemetry.Web'`.

**Comment by radical** [comment]
> Even if you have npm installed, on a fresh build I get: `Module not found : error : Can't resolve './scripts/index.js' in '/workspaces/aspire/playground/BrowserTelemetry/BrowserTelemetry.Web'`.

@joperezr fixed that one - https://github.com/dotnet/aspire/pull/5327 !

**Comment by sebastienros** [comment]
Can't we just skip building the web assets on every build?

https://github.com/dotnet/aspire/blob/main/playground/BrowserTelemetry/BrowserTelemetry.Web/BrowserTelemetry.Web.csproj#L35

Why not just expect devs to update the file when necessary, like when some work is done on the project or when dependencies are updated?

**Comment by davidfowl** [comment]
I agree
