### ISSUE TITLE
Define a default set of dashpages to ship with the dashboard

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#5303]
The dashboard will ship with a default set of dashpages, configured via a `dashpages.json` file (per #5289 and #5302).

We need to define that initial set.

@samsp-msft the file format is still in flux, but if you list out the titles and what metrics they contain, I can do the rest.

**Comment by samsp-msft** [comment]
Here is a list. I used JSON notation just as a convenience.
RequiredMetrics : show the group when you see this list of metrics. In these cases its only one per group.
Breakout: If possible break out each value of this dimension into its own line on the graph. It's a nice to have feature. #4906.

This exercise made me realize how close we are to the edge of a very deep hole. I can see wanting to be able to define filters, use tables rather than graphs for specific metrics - essentially become something much richer like Grafana.

[
    {
        "Title": "ASP.NET",
        "RequiredMetrics" : ["http.server.request.duration"],
        "Metrics" : [
            {
                "Name" : "http.server.request.duration"
            },
            {
                "Name": "http.server.active_requests"
            },
            {
                "Name": "kestrel.active_connections"
            },
            {
               "Name": "aspnetcore.routing.match_attempts",
               "Breakout": "http.route"
            }
        ]
    },
    {
        "Title": "Runtime (Instrumentation Library)",
        "RequiredMetrics" : ["process.runtime.dotnet.assemblies.count"],
        "Metrics" : [
            {
                "Name" : "process.runtime.dotnet.gc.heap.size"
            },
            {
                "Name": "process.runtime.dotnet.exceptions.count"
            },
            {
                "Name": "process.runtime.dotnet.thread_pool.queue.length"
            },
            {
               "Name": "process.runtime.dotnet.monitor.lock_contention.count"
            },
            {
                "Name": "process.runtime.dotnet.jit.methods_compiled.count"
            }
        ]
    },
    {
        "Title": "HttpClient",
        "RequiredMetrics" : ["http.client.open_connections"],
        "Metrics" : [
            {
                "Name" : "http.client.request.duration",
                "Breakout" : "server.address"
            },
            {
                "Name": "http.client.active_requests"
            },
            {
                "Name": "http.client.connection.duration"
            },
            {
               "Name": "http.client.open_connections"
            }
        ]
    },
    {
        "Title": "NgpSQL",
        "RequiredMetrics" : ["db.client.connections.usage"],
        "Metrics" : [
            {
                "Name" : "db.client.commands.duration",
                "Breakout" : "pool.name"
            },
            {
                "Name": "db.client.commands.executing",
                "Breakout" : "pool.name"
            },
            {
                "Name": "db.client.connections.usage",
                "Breakout" : "state"
            },
            {
               "Name": "db.client.commands.bytes_read",
               "Breakout" : "pool.name"
            },
            {
                "Name": "db.client.commands.bytes_written",
                "Breakout" : "pool.name"
            }
        ]
    }
]

**Comment by drewnoakes** [comment]
@samsp-msft `Runtime (Instrumentation Library)` requires `process.runtime.dotnet.assemblies.count` but then doesn't include it. Is that intentional?

BTW if you don't specify any required instruments then the dashpage is filtered out if no instruments match. Required metrics extend that filtering.

**Comment by drewnoakes** [comment]
@samsp-msft we don't have the concept of "breakout" yet, so I included that data but left it commented out.
