### ISSUE TITLE
Make it easy to identify services are logging errors on the projects/executables pages

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#533]
As a follow up to https://github.com/dotnet/aspire/issues/227, we've received more feedback that a similar strategy could be applied to the projects/executables overview page to make it easier to know what to do next when things are happening with their service. The only thing that the dashboard has today are logs, and the state of the process (we don't yet have health checks integrated).

- [ ] - Change the background color and use an icon for services that are finished state (not sure which one).
- [ ] - If a process exits with a non-zero exit code (finished state with non zero exit code), show an error icon. (same pattern as an error log)
- [x] - When a service logs and error (via structured logging), show an indicator that there are errors in the log with a link to navigate to a filtered view of that service with just the error logs. This indicator clears once the logs are viewed.

**Comment by kvenkatrajan** [comment]
@smitpatel with the revised API for logs is there a way to indicate the states of 1,2 in the response back to the dashboard for display?

CC: @adamint

**Comment by smitpatel** [comment]
There is nothing much related to revised API here, data is already there for most part. Purely UI concern. For exit codes, I will check if we get it from dcp.
