### ISSUE TITLE
[AzureTools][Aspire] The containers created by .withdockerfile are "Failed to start" with an error

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#5372]
**Regression:** A **regression**, this issue **doesn't reproduce** on VS 17.11.1 with Aspire 8.1.0

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.11.1
**Aspire Version:** 8.1.1-preview.1.24420.10
**Docker Desktop:** 4.34.0
Apply NuGet Feeds

**REPRO STEPS:**

1. Create a new .NET Aspire Starter Application.
2. Right-click the ApiService project -> Add -> Docker Support -> Linux and Dockerfile.
3. Right-click the web project -> Add -> Docker Support -> Linux and Dockerfile.
4. Add .withdockerfile codes in the programs.cs file of AppHost project.
```
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");
var container = builder.AddContainer("apicontainer", "apiimage")
                       .WithDockerfile("../.", "./AspireApp1.ApiService/Dockerfile");

var container1 = builder.AddContainer("webcontainer", "webimage")
                       .WithDockerfile("../.", "./AspireApp1.Web/Dockerfile");
var apiService = builder.AddProject<Projects.AspireApp1_ApiService>("apiservice");

builder.AddProject<Projects.AspireApp1_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(cache)
    .WithReference(apiService);

builder.Build().Run();
```
5. Edit the code of Dockerfile under the ApiService project and web project(change the path of the .csproj file) -> Add the Nuget.config file to all projects that added dockerfile -> Add code COPY ["../nuget.config", "."] into Dockerfile file for both dockerized project.
    ![image](https://github.com/user-attachments/assets/c31b68c0-373c-48cd-b255-c13c895a23cc)
    ![image](https://github.com/user-attachments/assets/d1b03b58-0355-410b-9f4c-71e1c2c4fa89)
6. F5/CTRL+F5/Run `dotnet run` in the AppHost.project folder.
7. Check whether the containers are running without any error.

**Expect:**
The containers are "Running" without any error.

**Actual:**
The containers are "Failed to start" with an error.
![image](https://github.com/user-attachments/assets/384e219a-0afe-4892-8b48-d1d31efe143a)
![image](https://github.com/user-attachments/assets/3ced4067-8b35-4a6e-8b46-2bfe8797ff81)

**More Info:**
Create this project using Aspire 8.1.0 -> Open it on Aspire 8.1.1-preview.1.24420.10 -> The containers are running without any error.

**Comment by danegsta** [comment]
@v-mengwe from the error output, it looks like this was using a nightly build of Aspire (which requires nugets from the nightly feed instead of nuget.org). The build output in the image indicates that the nuget restore step in the Docker build couldn't find the required nuget package versions, which generally means that an appropriate `nuget.config` isn't being copied into the Dockerfile prior to the restore command being run.

When running these tests against nightly Aspire builds, you'll need to make sure the project has a `nuget.config` with the appropriate nightly feeds configured and that the Dockerfile is updated to copy the `nuget.config` file into the build before restore is run.

**Comment by danegsta** [comment]
Turns out this is a case sensitivity issue; Linux containers only match `NuGet.Config`, not `nuget.config`. You'll need to either create the config with that filename, or give it the case sensitive matching name when you copy into the container.

**Comment by v-mengwe** [comment]
Change `nuget.config` to `NuGet.Config`, this issue still reproduces.
![image](https://github.com/user-attachments/assets/4ec66acf-aced-420d-a0a9-219cb869d295)

This issue **doesn't reproduce** on Aspire 8.1.0 using the same `nuget.config` or `NuGet.Config`.

**Comment by danegsta** [comment]
You need a nuget config with the nightly feed(s) to restore nightly builds; you can copy the one from the root of the Aspire repo and use that. 8.1.0 is the current public release on nuget.org, so it doesn’t require a nuget.config at all (which is why it works, but the nightly doesn’t).

**Comment by v-mengwe** [comment]
This issue **doesn't reproduce** for no, close this issue with this workaround.
1. Change the feed as below of NuGet.config file.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<add key="dotnet-toolsfeed" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
	</packageSources>
<configuration>
```
2. Add code `COPY ["AspireApp4.ApiService/NuGet.Config", "."]` or `COPY ["AspireApp4.Web/NuGet.Config", "."]` in the Dokcerfile.
