### ISSUE TITLE
Remove primary constructor from AzureOpenAIDeployment

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspire#5375]
The `AzureOpenAIDeployment` has a primary constructor with default values in it.
We should get rid of these optional arguments in the constructor as this change the public API when we need to update the defaults.

Current API:
```c#
public class AzureOpenAIDeployment(string name, string modelName, string modelVersion, string skuName = "Standard", int skuCapacity = 8)
```

Options are:

1- Use nullable arguments, define default on properties
```c#
public class AzureOpenAIDeployment(string name, string modelName, string modelVersion, string? skuName, int? skuCapacity)
```

2- Remove optional arguments from the ctor
```c#
public class AzureOpenAIDeployment(string name, string modelName, string modelVersion)
```

3- Remove all properties from the ctor, like we do for settings classes
```c#
public class AzureOpenAIDeployment
{
   ...
}
```

**Comment by davidfowl** [comment]
@sebastienros are you going to do this? Is it important for 9.x?

**Comment by sebastienros** [comment]
The change is simple, I think this could be done for 9 since it's about changing the api shape. Who should be involved to decide, is it worth a formal api review?

**Comment by davidfowl** [comment]
Open a PR with the change.
