### ISSUE TITLE
Pgadmin cannot connect Postgres on WSL2

### ISSUE THREAD

**Issue by tungphuong** [dotnet/aspire#5379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Aspire version 8.1.0; I have set up Pgadmin and Postgres. All containers are up, we can see the server list in Pgadmin but when accessing the pg server we get the error "connection is bad: Name does not resolve"

`var db = builder.AddPostgres("postgres", port: 5432).WithPgAdmin();`

Error from Pgadmin

![image](https://github.com/user-attachments/assets/e6975027-6320-4d02-8905-bfe871833201)

### Expected Behavior

Can connect and access Pg database from Pgadmin

### .NET Version info

.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.011fccd5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.1/8.0.100

**Comment by davidfowl** [comment]
@danegsta Is this the same as https://github.com/dotnet/aspire/pull/4192?

**Comment by davidfowl** [comment]
Pretty sure it is

**Comment by davidfowl** [comment]
Closing as it should be fixed as #5584
