### ISSUE TITLE
[WebToolsE2E][Aspire] After adding the 'Aspire.Hosting.Azure.Redis' package and publishing the project, the loading time when creating/updating resources (Redis cache) is too long, about 35 minutes or more.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#5383]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.401
3. Install Aspire 8.1.0

    - dotnet workload update
    - dotnet workload install aspire

4. Install azd [1.9.6] and Git [2.46.0]

**REPRO STEPS**

1. Open CMD, creating an Aspire Starter App using following commands:
```
dotnet new aspire-starter -o AspireRedis
cd AspireRedis/AspireRedis.Apphost
dotnet add package Aspire.Hosting.Azure.Redis --version 8.1.0
```
2. Replace the contents of the Program.cs file in the AspireRedis.AppHost project with the following code:
```
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache")
                   .PublishAsAzureRedis();

var apiService = builder.AddProject<Projects.AspireRedis_ApiService>("apiservice")
                        .WithReference(cache);

builder.AddProject<Projects.AspireRedis_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(cache)
    .WithReference(apiService);

builder.Build().Run();
```
3. Navigate to AspireRedis folder, run `azd init`, select 'Use code in the current directory' > Confirm and continue initializing my app > type a new environment name, press enter
4. Run `azd auth login` to log in azd.
5. Run `azd up`

    - Azure Subscription: WTE
    - Azure location: East US 2

**NOTE**: 
1. If you add the Aspire.Hosting.Redis package or check 'Use Redis for caching' when creating a project using VS, this issue will not be reproduced.
2. It seems to be caused by adding 'PublishAsAzureRedis()'.

**ACTUAL**
Loading time takes too long when Creating/Updating resources (Cache for Redis), it takes about 35 minutes or more.
![image](https://github.com/user-attachments/assets/f02a7d61-928b-46bc-85bc-ca66743153ca)

**EXPECTED**
The time of creating/updating resources (Redis cache) can be shortened.

**Comment by davidfowl** [comment]
This is a problem with the azure redis service, not aspire.
