### ISSUE TITLE
426 Upgrade Required

### ISSUE THREAD

**Issue by relounge** [dotnet/aspire#5386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to reach my aspire dashboard on Azure I get 426 Upgrade Required. Previously (after some bugfixes on the side of the Aspire development team) it was working ok. Now "426 Upgrade Required" all the time. And I don't understand what kind of upgrade is required.

### Expected Behavior

Dashboard opens

### Steps To Reproduce

- Have your code deployed to azure
- Enable aspire dashboard
- Try to reach it

### Exceptions (if any)

426 Upgrade Required in the response of the dashboard request

### .NET Version info

8.0

### Anything else?

Aspire hosting libs version is 8.1.0

**Comment by davidfowl** [comment]
cc @snehapar9

**Comment by relounge** [comment]
now it works, thank you
