### ISSUE TITLE
Aspire Redis Commander setup issue

### ISSUE THREAD

**Issue by masonyc** [dotnet/aspire#5391]
### Describe the issue or suggestion

Hi 
I was exploring Aspire by following a guide at https://github.com/csharpfritz/BigBadBlog/blob/main/docs/1-Introduction.md. However, when I try to add Redis Commander to Aspire, it seems like the port setup to Redis on the commander container is not correct? It refuses to connect to the Redis instance if I query inside the Commander.

Screenshot below:
![screenshot_07082024_163518](https://github.com/user-attachments/assets/e47318e6-3746-4e87-99b9-3e3c04e57fe5)

Logs:
![screenshot_07082024_163641](https://github.com/user-attachments/assets/7fdf3847-e392-4bea-ba78-4682d34a30fd)

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspire/issues/5584
