### ISSUE TITLE
.WithDataVolume() and predefined password with Postgres DB cause auth to fail

### ISSUE THREAD

**Issue by impworks** [dotnet/aspire#5399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using a password parameter and `.WithDataVolume()` on a Postgres resource, I get the authorization exception when trying to actually connect to the database.

### Expected Behavior

Connection succeeds

### Steps To Reproduce

**AspireHost/Program.cs:**

```
var dbUsername = builder.AddParameter("DatabaseUsername");
var dbPassword = builder.AddParameter("DatabasePassword");

var pgsql = builder.AddPostgres("postgres", dbUsername, dbPassword).WithDataVolume();
var mydb = pgsql.AddDatabase("mydb");
var myapi = builder.AddProject<Projects.My_Api>("myapi").WithReference(db).WithExternalHttpEndpoints();
```

If I remove either `.WithDataVolume()` call, or `dbPassword` parameter in the `.AddPostgres()` call from the Host config, it works. Only the combination of those two fails.

**AspireHost/appsettings.json:**
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Aspire.Hosting.Dcp": "Warning"
    }
  },
  "Parameters": {
    "DatabaseUsername": "postgres",
    "DatabasePassword": "super-password"
  }
}

```

**MyApi/Program.cs:**
```
var connstr = builder.Configuration.GetConnectionString("mydb");
builder.Services.AddDbContextFactory<MyDataContext>(opts => { opts.UseNpgsql(connstr).UseSnakeCaseNamingConvention(); });
```

### Exceptions (if any)

```
Npgsql.PostgresException
  HResult=0x80004005
  Message=28P01: password authentication failed for user "postgres"
  Source=Npgsql
  StackTrace:
   at Npgsql.Internal.NpgsqlConnector.<ReadMessageLong>d__233.MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.Internal.NpgsqlConnector.<AuthenticateSASL>d__2.MoveNext()
   at Npgsql.Internal.NpgsqlConnector.<Authenticate>d__0.MoveNext()
   at Npgsql.Internal.NpgsqlConnector.<<Open>g__OpenCore|213_1>d.MoveNext()
   at Npgsql.Internal.NpgsqlConnector.<Open>d__213.MoveNext()
   at Npgsql.UnpooledDataSource.<Get>d__6.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlConnection.<<Open>g__OpenAsync|42_0>d.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenInternalAsync>d__70.MoveNext()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__66.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.<Exists>d__19.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.<Exists>d__19.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.<ExistsAsync>d__24.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.<GetAppliedMigrationsAsync>d__30.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.<MigrateAsync>d__4.MoveNext()
   at MyApi.DatabaseInitializer.<MigrateDatabaseAsync>d__1.MoveNext() in C:\src\MyApi\DatabaseInitializer.cs:line 40
```

### .NET Version info

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.56cd0383
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300, VS 17.10.35122.118
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.425 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### Anything else?

Libraries used in Aspire Host:

```
<PackageReference Include="Aspire.Hosting.AppHost" Version="8.1.0" />
<PackageReference Include="Aspire.Hosting.PostgreSQL" Version="8.1.0" />
```

Libraries used in Api:

```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.5" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.5">
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
```

This exact same problem has already been discussed in #4461 which is closed as "fixed in 8.1".
I still have it version 8.1.0, so it's actually **not fixed**.
Moreover, looking at PR #4507 I do not see anything related to this particular combination of the 2 features that cause the error.

**Comment by eerhardt** [comment]
Can you try deleting your volume in Docker Desktop and try again? If you created the volume with a different username/password and then changed the password after it won't work. The username/password gets saved in the volume the first time. And it can't be reused with a different password.

**Comment by impworks** [comment]
Thanks a lot, this solved the issue!
