### ISSUE TITLE
Write JSON schema for Aspire manifest format.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#54]
We will be using the ```$schema``` attribute to specify the version of the manifest format we are using. That means we need a JSON schema which documents the format. We also need to think about where we host it.

**Comment by danmoseley** [comment]
@mitchdenny what remains here after your PR #3684 ?

**Comment by mitchdenny** [comment]
Just update the manifest writing code to emit $schema. I'll put up a PR. It's a nice to have.
