### ISSUE TITLE
Hide columns when space is limited because of the details view

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#5435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Dashboard grids now hide columns when browser window is small to make them usable:

![image](https://github.com/user-attachments/assets/81444f61-d8e3-40fc-9939-2ae1a0113f8e)

However, columns aren't hidden when the details view is open and reduces the screen real estate of the grid:

![image](https://github.com/user-attachments/assets/2199d240-6472-4dd6-8988-4a600cb9eed3)

### Describe the solution you'd like

When the details view is open, hide columns if the grid has limited screen space to make it eaiser to read.

**Comment by adamint** [comment]
Nope, I can unassign myself
