### ISSUE TITLE
[AzureTools][Aspire] Filters overlap with each other when there are more than 2 filters on the "Structured" page in the minimised Dashboard

### ISSUE THREAD

**Issue by amnabatr1sha** [dotnet/aspire#5437]
**Regression:** Not a regression, this issue **also reproduces** on Aspire 8.1.0

**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.11.2 Preview 1.0 [35223.180.d17.11]
**Aspire Version:** 8.1.1-preview.1.24425.2 
**Apply NuGet Feeds**

**REPRO STEPS:**

1. Launch VS and create a new project with 'Enlist in .NET Aspire orchestration' checked -> F5/Ctrl+F5 the project.
2. Click "**Add filter**" under the "**Structured**" in the Dashboard -> Apply filter.
        Parameter: "**Message**"
        Condition: "**contains**"
        Value: "listening"
                                    <img width="251" alt="image" src="https://github.com/user-attachments/assets/c262ee0d-5e75-43f0-a0b8-c61161765983">
3. Repeat step 2 until there are more than 2 filters -> Minimise the page.
5. Check whether the filters overlap with each other.

**EXPECT:**
The filters doesn't overlap with each other.
<img width="772" alt="image" src="https://github.com/user-attachments/assets/8caa9c29-473d-4703-a2fc-a1332f40c4fd">

**ACTUAL:**
The filters overlap with each other.
![Consolelog2](https://github.com/user-attachments/assets/12e2d45e-e95f-4d4e-aacd-4d19b19ab0d0)

**More Info:**
This issue **also reproduces** when there are more than 3 filters on a maximised page.

**Comment by v-mengwe** [comment]
@amnabatr1sha Verified on Aspire 9.0.0-preview.4.24454.1, we can't add the same filters for now. But the filters still overlap with each other when add different filters.
![image](https://github.com/user-attachments/assets/2d188f91-e47a-4ac8-ba97-bb8fdb616eff)

**Comment by amnabatr1sha** [comment]
Verified on Aspire 9.0.0-preview.4.24459.11, this issue doesn't reproduce
