### ISSUE TITLE
"View logs" button in traces doesn't redirect to logs with correct filter

### ISSUE THREAD

**Issue by thijscornelis** [dotnet/aspire#5438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the Traces view in the aspire dashboard allows you to navigate to the logs that correspond with the traces using the "View logs" button.

When clicking the button, the structured logs page is opened `/structuredlogs?traceId=<traceId>`, **no logs are shown**.

If you open the selected filters, you can see that no field is selected, the traceId is correct. Selecting the field TraceId and applying the filter changes the url to `/structuredlogs?filters=log.traceid:equals:<traceId>`, now logs are visible.

### Expected Behavior

Using the "View logs" button should apply filters and show logs to the user

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
Thanks for the bug report. This has been fixed here - https://github.com/dotnet/aspire/pull/5023. The next Aspire version includes the bug fix.
