### ISSUE TITLE
Update Arcade and Tooling on the repo to use 9.0

### ISSUE THREAD

**Issue by joperezr** [dotnet/aspire#5446]
In order to be able to test and target net9.0, our repository needs to be using the 9.0 version of Arcade as well as the 9.0 SDK. This issue is to track the work of doing that.

**Comment by eerhardt** [comment]
Note that when we do this - `$(NetCurrent)` will now be `net9.0`. So we need to make sure we are targeting the correct TFM after this change.

**Comment by joperezr** [comment]
Good point, will make sure to keep this in mind.

**Comment by radical** [comment]
update: wip - https://github.com/dotnet/aspire/pull/5483/
