### ISSUE TITLE
After upgrade to 8.2.0 AddAzureServiceBus disabled "Local Authentication" (SAS)

### ISSUE THREAD

**Issue by ryanheath** [dotnet/aspire#5494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrade to 8.2.0 out Azure ServiceBus "Local Authentication" was disabled.
How can we configure the appHost to keep this enabled?

// Ryan

**Comment by davidfowl** [comment]
Part of our "secure by default" initiative (https://github.com/dotnet/aspire/pull/4938):

You should be able to turn it back on with:

```C#
builder.AddAzureServiceBus("sb")
       .ConfigureConstruct(c =>
        {
#pragma warning disable AZPROVISION001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
            var ns = c.GetSingleResource<ServiceBusNamespace>()!;
            ns.AssignProperty(p => p.DisableLocalAuth, "false");
future updates. Suppress this diagnostic to proceed.
        })
```

**Comment by eerhardt** [comment]
This change happened in https://github.com/dotnet/aspire/pull/4938. It is part of our security work to make the Azure resources meet best practices. It is a best practice to use managed identity to connect to Azure Service Bus. See https://learn.microsoft.com/security/benchmark/azure/baselines/service-bus-security-baseline?toc=%2Fazure%2Fservice-bus-messaging%2FTOC.json#im-3-manage-application-identities-securely-and-automatically.

By default, your Aspire app will use managed identity to connect to the Service Bus. So local authentication was disabled.

To keep this enabled, you can use this experimental API:

#pragma warning disable AZPROVISION001 //  Need to use the experimental API to customize the service bus namespace
var sb = builder.AddAzureServiceBus("servicebus", (_, _, serviceBusNamespace) =>
{
    serviceBusNamespace.AssignProperty(p => p.DisableLocalAuth, "false");
})
#pragma warning restore AZPROVISION001 //  Need to use the experimental API to customize the service bus namespace

**Comment by davidfowl** [comment]
@eerhardt do we put this elsewhere?

**Comment by eerhardt** [comment]
> @eerhardt do we put this elsewhere?

Where are you thinking that people would see it? In our docs?  Note we did it for more than just ServiceBus.

https://github.com/dotnet/aspire/pull/4774

https://github.com/dotnet/aspire/pull/5041

https://github.com/dotnet/aspire/pull/4744

**Comment by davidfowl** [comment]
Docs and release notes

**Comment by ryanheath** [comment]
Thanks guys!
