### ISSUE TITLE
Rate metrics are not displayed properly

### ISSUE THREAD

**Issue by leidegre** [dotnet/aspire#5496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I opened a [discussion](https://github.com/dotnet/aspire/discussions/5495#discussion-7112311) about this but I think this might be a bug.

I have a instrument that is using the unit `By/s` which is later exported via OTLP to Aspire dashboard (standalone) but this is showing up in the dashboard as "Bytes Perseconds" which seems wrong.

![image](https://github.com/user-attachments/assets/ee6ca608-556f-428b-b862-42c7be0266be)

This might be specific to OTLP so I tried to change the unit to `bytes_per_second` this shows up with a nicer label but it isn't really presenting as a throughput or rate metric, i.e. one over.

### Expected Behavior

I would expect this to be recognized as a rate metric of correct units. I would also expect the Aspire dashboard to present this data using MB/s or something suitable and not like now, where it's not even recognizing that these are bytes.

**Comment by eerhardt** [comment]
fyi @JamesNK

**Comment by leidegre** [comment]
Related PR, https://github.com/dotnet/aspire/pull/5506
