### ISSUE TITLE
WithContainerLifetime behavior and follow up work

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#5523]
Work items:
- [x]  - Hash the project path and attach it to the name of the persistent container
- [x] - Change the method name to WithLifetime 
- ~[ ] - Change the enum to ContainerLifetime.CreateIfNotExistsPersistOnExist~
- [x] - File a documentation issue for this feature that details the agreed upon behavior

----

@danegsta I was experimenting with `WithContainerLifetime(...)` and noticed that if I add `WithContainerLifetime(ContainerLifetimeType.Persistent)` start the app. Then stop it, then remove `WithContainerLifetime(ContainerLifetimeType.Persistent)` and start it again I end up with two containers.

![image](https://github.com/user-attachments/assets/95737c96-c308-45ab-8671-feedc2882f4f)

We should probably figure out whether this is desirable behavior or not. In my head I thought that when the apphost started it would detect that there is already a container and then when it shuts down it would tear it down (rather than creating a new container).

I think this is more of a discussion around expected behaviors than a bug.

/cc @davidfowl @DamianEdwards @maddymontaquila @karolz-ms

**Comment by davidfowl** [comment]
Why would it use the previously setup one? How does it know that it should use it?

**Comment by danegsta** [comment]
I don’t know that we could attempt to cleanup old persistent containers without risking deleting containers users wanted to keep. I look at persistent containers as a “create only” (and eventually a “create or update only”) mode where we can create the container if it doesn’t exist, but we’ll never delete it just to cleanup resources.

**Comment by DamianEdwards** [comment]
👍 to @danegsta's comment. Perhaps we should consider changing the naming of the options here to more closely align with the  behavior, e.g. `WithContainerInstance(ContainerInstanceAction.Create)`?

**Comment by danegsta** [comment]
It's a mouthful, but maybe `ContainerLifetimeType.CreateIfNotExistsPersistOnExit` to make the full behavior explicit in the type name.

I think there are a few different scenarios we need to consider for a container with a given name. For startup it comes down to what we do if a container with the given name doesn't exist, what we do if a container with the desired name already exists and was created by DCP, and finally what we do if a container with the desired name already exists but wasn't created by DCP (labels on the container will be used to identify DCP managed containers).

### Startup
| Scenario | Container Doesn't Exist | Container Already Exists (DCP) | Container Already Exists (Not DCP) |
| --------- | ----------------------- | ------------------------------- | ----------------------------------- |
| Default   | Create                               | Error                                             | Error                                                    |
| Persistent | Create                            | Update if config hash changed | Use existing                                        |

### Shutdown
| Scenario | Action |
| -------- | -------- |
| Default   | Remove |
| Persistent | Keep |

**Comment by davidfowl** [comment]
I like this idea of making it explicit.

**Comment by DamianEdwards** [comment]
Just to zero in on naming for a moment, the other container specific extension methods like `WithImage`, `WithImageTag`, `WithBindMount`, etc. don't have the word `Container` in them, and the `Type` in `ContainerLifetimeType` seems redundant, so should we just make this more like `.WithLifetime(ContainerLifetime.CreateIfNotExistsPersistOnExit)`?

**Comment by davidfowl** [comment]
Do we want to use a name based on the apphost? If I have 2 projects with the same container name it'll reuse that container I think.

**Comment by DamianEdwards** [comment]
> Do we want to use a name based on the apphost? If I have 2 projects with the same container name it'll reuse that container I think.

Yeah, for other things like implicit volume names (from `WithDataVolume`) we include the apphost name for this reason.

**Comment by davidfowl** [comment]
Follow up work items:
- [ ]  - Hash the project path and attach it to the name of the persistent container
- [ ] - Change the method name to WithLifetime 
- [ ] - Change the enum to ContainerLifetime.CreateIfNotExistsPersistOnExist
- [ ] - File a documentation issue for this feature that details the agreed upon behavior

**Comment by mitchdenny** [comment]
Should we make it `ResourceLifetime`. Even though we don't support doing this with executable resources, I can imagine a point in the future where we might want to give it a shot (plenty of issues to solve there though).

**Comment by DamianEdwards** [comment]
I'm not sure all resources will support the same lifetimes though? Honestly it's impossible to know at this point but we can always add overloads that take different enums.

**Comment by danegsta** [comment]
https://github.com/dotnet/aspire/pull/5630 will update the API to `WithLifetime` and `ContainerLifetime.CreateIfNotExistsPersistOnExit`

**Comment by danegsta** [comment]
https://github.com/dotnet/aspire/pull/5627 added initial support for detecting AppModel config changes and re-creating "persistent" containers in that scenario.

**Comment by danegsta** [comment]
API method has been updated to WithLifetime and the enum is now ContainerLifetime.Persistent with a more verbose doc comment explaining some of the behavior.

**Comment by davidfowl** [comment]
3 things left over here @danegsta https://github.com/dotnet/aspire/issues/5523#issuecomment-2336580334

**Comment by danegsta** [comment]
I'm working on the PR to append a hash of the project as a container name postfix; do we want to consider adding the ability to to override the container name behavior to let users reference containers they created outside of Aspire? Basically should users be able to either disable the postfix via some `WithLifetime()` override or via a new `ContainerNameAnnotation` + `WithContainerName()`?

**Comment by davidfowl** [comment]
That would be a very nice bonus feature (see https://anthonysimmon.com/referencing-external-docker-containers-dotnet-aspire-custom-resources/), I wonder if exposing it via WithContainerName + WithLifetime is correct though. Would we modify that container definition to match what the DCP resource expects? (For e.g. if the endpoint information wasn't correct).

**Comment by danegsta** [comment]
We already support arbitrary container names in DCP (we actually require the container name to be set for persistent containers), so everything should work just fine. To me it comes down to whether we want to support arbitrarily customizing container names only for persistent containers or as a general feature.

**Comment by danegsta** [comment]
Last remaining item should be documentation; I'll file a work item now that the API and behavior is finalized.

**Comment by danegsta** [comment]
Doc issue is here: https://github.com/dotnet/docs-aspire/issues/1660

**Comment by danegsta** [comment]
Closing this issue since the follow up work is all complete.
