### ISSUE TITLE
AppHost cannot reference self contained project

### ISSUE THREAD

**Issue by jmezach** [dotnet/aspire#5535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While working on adding an AppHost project to one of our existing projects we ran into an error in our CI pipeline:

```
/opt/hostedtoolcache/dotnet/sdk/8.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1253,5): error NETSDK1151: The referenced project '../ACL/ACL.csproj' is a self-contained executable.  A self-contained executable cannot be referenced by a non self-contained executable.  For more information, see https://aka.ms/netsdk1151
```

This occurred after we added a reference to another project in our solution to our AppHost project. This project needs to be self contained for deployment reasons, so we cannot really change this right now. We have worked around the issue for now by not referencing the project, but using the `AddProject()` overload that takes a path to a project file.

What is interesting is that I was able to run the project locally using `dotnet run`. Our CI pipeline was failing with the above message upon restoring the workload using `dotnet workload restore <solution-file>`.

### Expected Behavior

I would expect our CI pipeline to be able to build the project correctly even with this reference.

### Steps To Reproduce

1. Create an AppHost project (with dotnet new aspire-apphost)
2. Create a new project (for example using dotnet new webapi)
3. Add both projects to a solution (using dotnet sln add)
4. Edit the project file of the WebAPI project and add `<SelfContained>True</SelfContained>` to it
5. Run `dotnet workload restore <solution-file>` and see the above error

### Exceptions (if any)

See description of the bug.

### .NET Version info

 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/hostedtoolcache/dotnet/sdk/8.0.401/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [/opt/hostedtoolcache/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/opt/hostedtoolcache/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/opt/hostedtoolcache/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by davidfowl** [comment]
cc @joperezr

**Comment by joperezr** [comment]
Thanks for posting the issue, @jmezach. I just tried this locally and it worked fine for me. Are you sure you are adding a project reference from the AppHost project to your webapi project? This is required in order to make sure that we set the right properties on the project reference so MSBuild won't do checks like the one that is failing for you.

In case you do have the project reference set, can you please share your sample repro here as well as the output of running `dotnet workload list`?
