### ISSUE TITLE
Can't access all my endpoints from the dashboard

### ISSUE THREAD

**Issue by webreidi** [dotnet/aspire#5541]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have an Aspire app that has an API with 2 endpoints. I expect to be able to click on them both from the dashboard, and see a +1 next to the first one, but when I click on the +1, my weatherforecast endpoint is not listed.

![Image](https://github.com/user-attachments/assets/1297d25b-8ca1-4082-8eb9-02a9587bd3c2)

### Expected Behavior

When I click the +1, I would see a link to my weatherforecast endpoint.

### Steps To Reproduce

1. Create a .NET starter application.
2. Add a second endpoint to the API project
3. Run the application

### .NET Version info

.NET SDK:
 Version:           9.0.100-preview.7.24407.12
 Commit:            d672b8a045
 Workload version:  9.0.100-manifests.2aef0cee
 MSBuild version:   17.12.0-preview-24374-02+48e81c6f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22635
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.7.24407.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    35.0.0-preview.7.41/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.android\35.0.0-preview.7.41\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json  
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    17.5.9231-net9-p7/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.ios\17.5.9231-net9-p7\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    17.5.9231-net9-p7/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.maccatalyst\17.5.9231-net9-p7\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: SDK 9.0.100-preview.7, VS 17.12.35209.166
   Manifest Version:    9.0.0-preview.7.24407.4/9.0.100-preview.7
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.7\microsoft.net.sdk.maui\9.0.0-preview.7.24407.4\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      9.0.0-preview.7.24405.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.304 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.7.24407.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24405.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]        

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### Anything else?

Same in both VS and VS Code with C# Dev Kit.

**Comment by davidfowl** [comment]
Endpoints defined in your application don't show up on the dashboard. The urls displayed are based on what is in launch settings (a combination of the applicationUrl and the launchUrl

**Comment by maddymontaquila** [comment]
We definitely need to improve docs on this - it's kind of confusing that we call it an endpoint but it's not like. Your app endpoints. It's just the endpoint aspire creates. Very good catch

**Comment by webreidi** [comment]
I have four listed in my launchsettings.json, but only 2 appear.

**Comment by davidfowl** [comment]
Can you share your launch settings? We may have just fixed this.

**Comment by webreidi** [comment]
https://github.com/webreidi/codel-cloud-native/blob/main/Codel-Cloud-Native.ApiService/Properties/launchSettings.json

**Comment by davidfowl** [comment]
This project has 4 launch profiles and the names are duplicated, so there are really 2, http and https. A single launch profile is selected when you run in aspire, and the endpoints reflect that. When you run in visual studio, the IDE specifies the launch profile via an env variable that the apphost reads and uses to determine which profile to use (the playy button in the IDE selects the profile).

````JSON
{
"https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "applicationUrl": "https://localhost:7310;http://localhost:5558",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
}
```

When https is selected, there are 2 URLs (https://localhost:7310;http://localhost:5558) and the lauchUrl is "weatherforecast". This is what the dashboard will show. We don't aggregate all of the launch profiles in the launch settings file to produce those endpoints.
