### ISSUE TITLE
`ResourceNotificationService.WaitForResourceAsync` should throw when resource enters a terminal state

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#5544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If a resource fails to start properly and goes to a terminal state before the state being waited for, then `ResourceNotificationService.WaitForResourceAsync` can hang indefinitely.

### Expected Behavior

If a resource enters a known terminal state (e.g. `FailedToStart`, `Exited`, `Finished`), and that state is not the state being waited on, the `WaitForResourceAsync` should throw an exception to fail fast, rather than leaving the task hanging forever.

This will make troubleshooting unexpected states transitions in tests harder as you'll end up with a hanging test or a timeout, when you could instead fail with an error informing you that the resource reached a terminal state

### Steps To Reproduce

In the following example, the `fake` resource will fail to start (as the executable does not exist), however the call to `WaitForResourceAsync("fake", KnownResourceStates.Running)` will hang indefinitely.

```cs
var builder = DistributedApplication.CreateBuilder(args);

builder.AddExecutable("fake", "doesnotexist", ".");

var app = builder.Build();

var notificationService = app.Services.GetRequiredService<ResourceNotificationService>();
var wait = notificationService.WaitForResourceAsync("fake", KnownResourceStates.Running);

var appTask = app.RunAsync();

Console.WriteLine("Start Waiting");
await wait;
```

I'd expect this to throw an error along the lines of `Resource "fake" entered a terminal state ("FailedToStart") before the target state "Running"`

### .NET Version info

```
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.57f7c351
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.10.35201.131
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.304 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by davidfowl** [comment]
cc @mitchdenny we should make these changes as part of waitfor

**Comment by mitchdenny** [comment]
There are some other overloads for `WaitForResourcesAsync` which allow you to specify multiple target states. We probably won't change the one with a single target state because we are introducing start/stop/restart capabilities at which point we would want this wait to wait until it was restarted and did enter the running state.

If you want to detect terminal states you can use the overload that allows you to specify multiple target states.

We are also adding `WaitFor` support which adds an additional overload that takes a predicate that allows for more fine granted filtering of the resource events (we are using this for health check integration with resources).
