### ISSUE TITLE
Auto provisioning is not robust to removing its data from User Secrets

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspire#5545]
I blew away the resource group that had been used as part of the auto provisioning. It took a while to find where the data was stored locally. Removing the content from the file and rebuilding/restarting the app didn't work. It failed because the info it wanted was not in the file. I had to remove the guid from the project file to be able to get the project to re-create the resources.

The code that is looking for the user secrets and trying to read the data needs to be more resilient to it not having the data that it expects.

**Comment by davidfowl** [comment]
> Removing the content from the file and rebuilding/restarting the app didn't work

Can you explain what didn't work? I'd expect removing the user secrets content to work.

**Comment by samsp-msft** [comment]
Could not repro again. closing for now.
