### ISSUE TITLE
Unknown container state shows up green in the dashboard

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#5550]
I thought we fixed this @adamint ?

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/b95b15bf-1fd4-41fd-804e-9f63d5ce9817">

Repro is to delete the container using docker desktop and leave the dashboard running. 

PS @karolz-ms @danegsta, shouldn't DCP auto recreate the container in this case? The object hasn't been deleted at the DCP level, just the backing container in the container runtime.

**Comment by adamint** [comment]
We had fixed it, it may have regressed. I will investigate

**Comment by karolz-ms** [comment]
> PS @karolz-ms @danegsta, shouldn't DCP auto recreate the container in this case? The object hasn't been deleted at the DCP level, just the backing container in the container runtime.

Maybe. Not sure. The concern is getting into an infinite loop where DCP is re-creating the container and something else is killing it.

**Comment by adamint** [comment]
Looks like it regressed [here](https://github.com/dotnet/aspire/commit/3bcf24fe7d24fba323753f548f4f606714bbb20c#diff-efa95af64443f5ecd31a836f36a41e5cdda1776dbadb131f0ff194dec9bb7034).

**Comment by davidfowl** [comment]
Couldn't be, this bug is 3 weeks old and that PR is 1 week ago 😄

**Comment by adamint** [comment]
> Couldn't be, this bug is 3 weeks old and that PR is 1 week ago 😄

I totally misread and saw this bug as a week old. oops :)
