### ISSUE TITLE
Re-enable ProjectSpecificTests.AzureFunctionsTests after Core Tools update

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspire#5564]
Running the Azure Functions integration tests end-to-end in our repo is currently blocked on a bug during build of the Azure Functions worker project:

> fail: AzureFunctionsEndToEnd.AppHost.Resources.funcapp[0] 1: 2024-09-05T07:09:43.6820000Z Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2

There's ongoing discussion about this in https://github.com/Azure/azure-functions-core-tools/issues/3594 and a potential bug fix in https://github.com/Azure/azure-functions-core-tools/pull/3773. The bug fix has not be released in publicly available Core Tools bits. 

The issue does not repro locally and only in CI builds.

**Comment by davidfowl** [comment]
Fixed by https://github.com/dotnet/aspire/pull/5591

**Comment by captainsafia** [comment]
Let's keep this open to track consuming the actual updated Core Tools bits with the fix instead of just using the workaround.
