### ISSUE TITLE
Expose health check status in the dashboard

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#5569]
In #5515 we are introducing health checks into resources so that when `WaitFor` is used and a health check is associated with a resource it blocks dependent resources from starting up until the check enters either a terminal state or is healthy.

We want to light up this feature in the dashboard so that developers can reason why a particular resource is not healthy. The key features are:

1. [x] The status on each resource should have its status and its health status ... e.g. `Running (Healthy)` or `Running (Unhealthy)`. If the resource does not have any health checks associated with it then the health status can be ommitted.
2. [ ] If the status is unhealthy, the text `Unhealthy` should be a hyperlink that brings up the resource details panel and displays the health checks section.
3. [ ] The health checks section in the panel should list all the checks in the resource (typically just one but there can be more).
4. [ ] The health check will need to show not just the health check entry status, but also any messag/exception details.

**Comment by drewnoakes** [comment]
In the dashboard we can show them as another section in the Resource Details view, along with properties, endpoints and env vars.

I assume we won't need the ability to mask these values. They don't seem like sensitive information.

**Comment by davidfowl** [comment]
cc @leslierichardson95 this is part of the 9.x work.

**Comment by joperezr** [comment]
Next steps: Agree on what the UI will be and what the contract is between App Model and Dashboard. This is part of the WaitFor story.

**Comment by joperezr** [comment]
cc: @samsp-msft @leslierichardson95

**Comment by davidfowl** [comment]
I've done the first bullet (which I think is the min bar for 9). We can attempt to design the health checks panel or expand the existing details view to add health checks there.

Thoughts?

**Comment by drewnoakes** [comment]
I'm working on showing these in the details area.

![image](https://github.com/user-attachments/assets/b8734445-84b6-4595-a7b8-e820eda6769c)

If there's a description or exception, they'll be displayed. I haven't seen an example of either in practice though, so am not sure what formatting they might need. For example, should the exception be displayed in monospace, preformatted?

While here I've also added details about "Waits For":

![image](https://github.com/user-attachments/assets/f9b90408-da15-418a-965a-8e0fb8028b41)

> If the status is unhealthy, the text Unhealthy should be a hyperlink that brings up the resource details panel and displays the health checks section.

We don't currently have a way to navigate to a section in the details pane. We could collapse all other sections and force the details view to be open.

**Comment by mitchdenny** [comment]
For the exception we'll probably want to be able to bring it up in its own window like we can with some of the other values in the dashboard (although it is fine to get to that via the panel here). People will probably want it to be preformatted text (see how it looks?).

**Comment by mitchdenny** [comment]
When I say people ... I'm using my sample size of one :)
