### ISSUE TITLE
Use kubernetes resourceVersion to call into List + Watch to compute view models

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspire#558]
Currently, we start watches over kubernetes resources when dashboardViewModelService is started. This happens in background even before the dashboard page started to render so we generally get initial list computed by the time we show the table. If you refresh the page, then the cache is invalidated and same computation will reoccur. This causes minor delay in computing whole list as (we look over events through watch 1 at a time) so user sees rows getting added to table one by one. Actual display depends on computer speed.

We can use kubernetes resourceVersion by calling into List first before starting watch, this will give us snapshot in kubernetes right away. For first use of dashboard it may not change much as all things may not be updated yet (so watches will bring most data), but for subsequent refreshes, it will compute the view models much faster as we can correlate resources in snapshot together.

**Comment by davidfowl** [comment]
@karolz-ms @drewnoakes is this still relevant?

**Comment by drewnoakes** [comment]
Refreshing the dashboard no longer hits DCP APIs. It hits the resource service which will batch all resources into a single update. So I don't think the approach described here would apply any more, post split.
