### ISSUE TITLE
Include end time for resources that complete

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#5623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When a resource finishes, it would be nice if an `End Time` field could be added to the resource along side the `Start Time`

### Describe the solution you'd like

I'd like to see an `End Time` alongside the `Start Time`.  A `Duration` would also be nice.
<img width="785" alt="image" src="https://github.com/user-attachments/assets/e718aca2-c98e-430e-9531-aff30b10c261">

### Additional context

Sample code: 
```cs
builder.AddExecutable("oneSec", "pwsh", ".",
    "-NoProfile",
    "-NoLogo",
    "-NonInteractive",
    "-Command",
    "Write-Host 'Starting Migration'; Start-Sleep -Seconds 1; Write-Host 'Done'");
```

**Comment by davidfowl** [comment]
@karolz-ms does DCP expose the end time?

**Comment by karolz-ms** [comment]
@davidfowl it does https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dcp/Model/Executable.cs#L101 and https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dcp/Model/Container.cs#L277

**Comment by davidfowl** [comment]
@JamesNK might be an interesting addition after we add Stop/Start
