### ISSUE TITLE
Should `WithPgAdmin` / `WithPgWeb` wait for `Postgres` to start?

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#5624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

With the new `WaitFor`, should extension containers such as `PgAdmin`, `PgWeb` wait for the parent container.

For example in the below screenshot you can see that PgAdmin has started before the Postgres container has finished pulling.
![image](https://github.com/user-attachments/assets/51d1484a-623b-46c8-9e12-ce15c55c6665)

It doesn't do any harm to start them early, but equally it makes no sense to have them running before the resource they're used for exists.   Similarly if the resource fails of fully initialise, it may be helpful to have the admin tools around to diagnose the problem.  (Does it make sense to have a version of the `WaitFor` method that only waits for resource start up, and not health checks to pass)

### Describe the solution you'd like

If we think they should wait, then we should add the appropriate `.WaitFor()` calls into the `WithPgAdmin`, `WithPgWeb` calls.  (As well as any similar extension container e.g. Redis Commander)

### Additional context

Can repro with the following 

1. Remove local postgres images to ensure it takes extra time to stat
```bash
docker image rm docker.io/library/postgres:16.4 -f
```
2. Run Postgres & PgAdmin.
```cs
var builder = DistributedApplication.CreateBuilder(args);

builder.AddPostgres("server")
    .WithPgAdmin();

builder.Build().Run();
```

**Comment by mitchdenny** [comment]
Closing this issue. We deliberately don't wait for Postgres to start because in the case of PgAdmin it can connect to multiple servers/databases and having one server fail to start should not preclude you from using it to manage the other databases.

If folks really need it to wait for some reason they can use the callback on `WithPgAdmin` to add a `WaitFor` on the postgres resource.
