### ISSUE TITLE
Volume readonly icon too small

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#5635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See https://github.com/dotnet/aspire/pull/5572

### Expected Behavior

Icon should be:
* 16x16
* Vertical middle aligned with text

### Steps To Reproduce

View container with readonly volume in dashboard details view.

**Comment by drewnoakes** [comment]
I tried it at 20 and 16 and felt both looked too large.

**Comment by JamesNK** [comment]
Icon didn't look properly aligned with text which is probably why it looked bad unless small. The state icon is 16x16: 

![image](https://github.com/user-attachments/assets/cfbe5599-6030-4735-8361-5af22573db6d)
