### ISSUE TITLE
Adding replicas makes service disappear from the dashboard

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#567]
When changing from a single replica to multiple replicas, we lose the ability to see the main service in the dashboard. Today, we only show the replicas when instead it would be ideal if we showed the service itself, and replicas grouped under each service.

**Comment by davidfowl** [comment]
@drewnoakes We want to make sure this is solved with the new refactoring of the dashboard. We need to make sure we can model this in the API and UI.

**Comment by davidfowl** [comment]
cc @kvenkatrajan

**Comment by adamint** [comment]
related: #1782
