### ISSUE TITLE
Property CliPath: the path to the dcp executable used for Aaspire orchestration is required; Property DashboardPath: The path to the Aspire Dashboard binaries is missing

### ISSUE THREAD

**Issue by hydra1102** [dotnet/aspire#5674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

accrording to https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?pivots=dotnet-cli
1st   dotnet new aspire-starter --use-redis-cache --output AspireSample
2nd  modify the csproj file
3rd  dotnet  restore  and succeeded
4th  donet build  and succeeded
5th  dotnet run --project AspireSample/AspireSample.AppHost

when i run 5th step,the error occured:
Property CliPath: the path to the dcp executable used for Aaspire orchestration is required; Property DashboardPath: The path to the Aspire Dashboard binaries is missing

### Expected Behavior

how can i fix the problem and run normally

### .NET Version info

![4444](https://github.com/user-attachments/assets/8ede093b-aedc-4bef-bba5-ce7ce99b8d73)

### Anything else?

the log content:
<img width="648" alt="111" src="https://github.com/user-attachments/assets/2dfe259e-522d-4a95-b7ea-11aa53b78440">

when 2nd step i write the aspire1.AppHost.csproj file content:
![3333](https://github.com/user-attachments/assets/ba613beb-774e-4f35-a57f-8757eac47a6f)

**Comment by danegsta** [comment]
@hydra1102 this looks like the same issue as https://github.com/dotnet/aspire/issues/5486; you'll likely need to update your SDK to a newer version than 8.0.100. Other Fedora/RHEL users are reporting that installing SDK 8.0.401 works to unblock them. Basically, the build targets are expecting linux-x64 for the SDK architecture, but with 8.0.100 some distros are reporting custom architecture values for the check we make (i.e. fedora-x64 or rhel-x64 instead of linux-x64).

**Comment by hydra1102** [comment]
@danegsta  thanks. I have installed the sdk 8.0.401 by script, and run the aspire-starter succeeded

**Comment by joperezr** [comment]
Thanks for the report, @hydra1102. I have put up a PR https://github.com/dotnet/aspire/pull/5695 that will fix this issue and you'll be able to remove the manual workarounds and won't need to pin to an older workload any longer.

**Comment by kovacsandras2014** [comment]
Hello, I have the same issue on Ubuntu 22.04. Having upgraded Aspire to 8.2 and modified my AppHost.csproj as above, I got the same error. Upgrading to SDK 8.0.401 didn't help.

**.NET version and workloads**
<img width="863" alt="image" src="https://github.com/user-attachments/assets/f2844f3d-94da-49df-8bf3-42f5a38565ce">

**OS version**
<img width="830" alt="image" src="https://github.com/user-attachments/assets/dfa3101e-5a17-4ba1-9a76-dc0fd7d4ec80">

Any idea or workaround how can I get my project to run?

**Comment by kovacsandras2014** [comment]
Uninstall/reinstall Aspire workload, clean and rebuild the solution has solved the problem.

**Comment by DclearEE** [comment]
> Uninstall/reinstall Aspire workload, clean and rebuild the solution has solved the problem.

This worked for me. For anyone using the CLI the commands are
`dotnet workload uninstall aspire`
`dotnet workload install aspire`

**Comment by snuup** [comment]
the same problem and nothing of the above helped. please repoen this.

**Comment by joperezr** [comment]
@snuup can you please run `dotnet workload update --print-rollback` and paste the output you get?

**Comment by lnaie** [comment]
I have a non flat structure of the Aspire project, on WIndows 11. That's the difference from the default template. I like that setup.
Could you please document how to configure these 2 variables that copilot suggested that could fix the problem:
```
{
  "CliPath": "path/to/dcp/executable",
  "DashboardPath": "path/to/dashboard/binaries"
}
```
