### ISSUE TITLE
[WebToolsE2E][Aspire] There are some garbled characters in the Aspire dashboard Console log after installing SDK 9.0 RC2

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#5716]
**REGRESSION INFO:** 
Work in SDK 8.0.401 + Aspire 8.2.0
Work in SDK 9.0 RC1 + Aspire 9.0 P4

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0.100-rc.2.24463.45

    - Apply feed for SDK 9.0 RC2

3. Install Aspire 9.0.0-preview.4.24463.11
    - Apply the dotnet8 feed for Aspire 9.0P4

**REPRO STEPS**
1. Open CMD, create an Aspire Starter App using following commands:
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
```
2. Dotnet run the project in CMD, and open URL in the browser.
`dotnet run`
3. Click the "Console" option on the Aspire dashboard left, and select the apiservice/webfrontend resource.

**Note:**
1. This issue also repro on SDK 8.0.401 + SDK 9.0 RC2 + Aspire 8.2.0.
2. This issue doesn't repro when running the Aspire Starter App in VS/VSCode

**ACTUAL**
There are some garbled characters in the console log
![Screenshot 2024-09-14 172119](https://github.com/user-attachments/assets/7d857d96-02ce-430b-80dc-97a786f51a0d)

**EXPECTED**
There is no garbled code in the console log
![Screenshot 2024-09-14 164442](https://github.com/user-attachments/assets/83ba5176-9ce7-40f1-9fce-fee4d4e2110a)

**Comment by davidfowl** [comment]
Does this happen on every project and only at the beginning?

**Comment by Rita003** [comment]
> Does this happen on every project and only at the beginning?

@davidfowl This issue happens on every project every time

**Comment by davidfowl** [comment]
@JamesNK can you look at this?

**Comment by JamesNK** [comment]
I searched for some of the garbled characters and they match up with some ANSI escape sequences

https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#common-private-modes

`ESC[?25h` = show cursor
`ESC[?25l` = hide cursor

Hmm, is .NET 9 doing some funky stuff when the console starts up now? Introduced in RC2?

**Comment by davidfowl** [comment]
cc @stephentoub ?

**Comment by stephentoub** [comment]
> Hmm, is .NET 9 doing some funky stuff when the console starts up now? Introduced in RC2?

Not to my knowledge. And I don't see any meaningful changes in System.Console in the last several months.

Plus if this is actually Windows as cited, System.Console on Windows doesn't emit ANSI escape sequences; it uses the Win32 APIs for interactions. It only uses ANSI escape sequences on Unix.

**Comment by JamesNK** [comment]
[`DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_system_console_allow_ansi_color_redirection) is set to true.

Maybe it is added in the Microsoft.Extensions.Logging layer?

Regardless of where they're being added, the Aspire console UI shouldn't print them. If there is an unknown/unsupport sequence then it shouldn't be prints. And to avoid blank lines, perhaps skip adding the line of output if it is 100% unsupported control characters.

**Comment by JamesNK** [comment]
Some of the strings didn't look like the ANSI codes as I know them. I searched more to see if I could find them and got:

https://conemu.github.io/en/AnsiEscapeCodes.html#ConEmu_specific_OSC

`ESC]9;4;3;0\` in the garbage text is for setting progress state in the taskbar.

**Comment by JamesNK** [comment]
I think the console output is coming from here:

https://github.com/dotnet/msbuild/blob/5bab860b2477f03050f170473a2563c5217d546f/src/Framework/Logging/AnsiCodes.cs#L95-L123

How could msbuild logging leak into the app's console output?

**Comment by rainersigwald** [comment]
Are y'all invoking the `dotnet run` command and piping its output into this? That might repro this (https://github.com/dotnet/msbuild/issues/10579, fix just approved for RC2).

**Comment by davidfowl** [comment]
Yes!

**Comment by Rita003** [comment]
@JamesNK Verify this bug shows blank lines after installing the latest SDK 9.0.100-rc.2.24474.11 + Aspire 9.0.0-preview.4.24474.5 in today's validation. Do we expect blank lines not to be displayed?
![Screenshot 2024-09-25 180335](https://github.com/user-attachments/assets/92f21586-f82f-4e19-a89a-fc3c5363a098)

**Comment by JamesNK** [comment]
Yes, that is expected. My fix removed the bad characters, but adding a new line isn't considered bad.

The complete fix is inside .NET SDK. Try out the version suggested in [this comment](https://github.com/dotnet/msbuild/issues/10579#issuecomment-2370818582) (or later).

**Comment by v-elenafeng** [comment]
@JamesNK Rita used a newer build than the one in the comment, not sure why the lines were not removed completely.

Btw, this issue is also reproduced in SDK 9.0 RC2 + Aspire 8.2.1, are we considering fixing it for Aspire 8.2.1 as well? cc: @joperezr @balachir

**Comment by JamesNK** [comment]
I don't think so. It's not a high impact bug.

**Comment by v-elenafeng** [comment]
@JamesNK The msbuild issue [10579 ](https://github.com/dotnet/msbuild/issues/10579) has been fixed. But this issue is still reproducible with SDK 9.0 RC2 + Aspire 8.2.1 / Aspire 9.0 rc1 (fixed the garbled characters but left lines with the time but no content in the console). Is this a different issue? What can we do to fix this at its root? Open an another bug in the dotnet/msbuild repo?

**Comment by JamesNK** [comment]
Looks like https://github.com/dotnet/msbuild/issues/10579 isn’t completely fixed according to comments on it.

Blank lines are coming from the sdk, not Aspire. We can only wait until it is fixed there.

**Comment by v-elenafeng** [comment]
From what I‘ve read, the issue [10579 ](https://github.com/dotnet/msbuild/issues/10579) is now only reproes with Win server 2012 which doesn't support VT100.  Not sure if there will be a deeper fix for that and the issue has also been closed.
