### ISSUE TITLE
Redis, Garent and Valkey doesn't have playground app

### ISSUE THREAD

**Issue by Alirexaa** [dotnet/aspire#5723]
It's difficult for me to check the new changes I made work before writing new tests. For example, checking Redis Insight works before writing a functional test.
We should add a playground app for these resources.

* [x] Redis playground (#5726)
* [x] Garent playground (#5087)
* [x] Valkey playground (#5818)

**Comment by Alirexaa** [comment]
I will work on this ASAP.

**Comment by davidfowl** [comment]
I think we should use a single app for garnet, redis and, valkey until we have a different client integration (today they all use the same one).
