### ISSUE TITLE
Better Azure resource name scheme

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#5756]
## Problem

In 8.x, we used an early/alpha version of Azure.Provisioning. This version used a naming scheme for Azure resources that tried to be the least common denominator of all resources.

```C#
        protected string GetGloballyUniqueName(string resourceName)
            => $"toLower(take('{resourceName}${{uniqueString(resourceGroup().id)}}', 24))";
```

This causes problems like [Invalid Cloud deployment of Azure Service Bus topics - name truncation (dotnet/aspire#5341)](https://github.com/dotnet/aspire/issues/5341).

The new version of Azure.Provisioning has a [better scheme](https://github.com/Azure/azure-sdk-for-net/blob/60109aee76c8e70143efebc1e304a550273aceae/sdk/provisioning/Azure.Provisioning/src/Primitives/ResourceNamePropertyResolver.cs#L201-L214) that has information about what names the resource type allows (max length, valid characters, etc.).

```C#
    public override BicepValue<string>? ResolveName(
        ProvisioningContext context,
        Resource resource,
        ResourceNameRequirements requirements)
    {
        string prefix = SanitizeText(resource.ResourceName, requirements.ValidCharacters);
        string separator =
            requirements.ValidCharacters.HasFlag(ResourceNameCharacters.Hyphen) ? "-" :
            requirements.ValidCharacters.HasFlag(ResourceNameCharacters.Underscore) ? "_" :
            requirements.ValidCharacters.HasFlag(ResourceNameCharacters.Period) ? "." :
            "";
        BicepValue<string> suffix = GetUniqueSuffix(context, resource);
        return BicepFunction.Take(BicepFunction.Interpolate($"{prefix}{separator}{suffix}"), requirements.MaxLength);
    }
```

However, we are not able to take advantage of this new scheme. It is a breaking change to take this new naming scheme. If someone used 8.x to deploy to Azure, then updated to 9.0 and deployed again they would get duplicate resources since the naming scheme changed. For example, there is a separator now and `toLower` is no longer called in bicep but instead the `resource.ResourceName` is sanitized first before putting it in the bicep. If the resource doesn't allow upper case characters, the ResourceName is lowered. For resources that support upper case characters, this means a different resource name.

The new naming scheme is better than the old, but maintaining compatibliity is not allowing us to use it.

## Proposed Solution

Allow for a user to customize the Azure CDK `ProvisioningContext` object that we use to build bicep. This will allow users to "opt in" to different naming conventions (including using the .NET Aspire 8.x naming scheme).

To do this, add a new class

```csharp
public class AzureProvisioningOptions
{
    public ProvisioningContext ProvisioningContext { get; } 
}
```

This will be an `IOptions` class, which can be configured as a typical IOptions object. Users can configure it to and modify the ProvisioningContext as necessary.

We also add a ResourceNameResolver that encodes the 8.x behavior:

```
public sealed class AzureResourceNamePropertyResolverAspireV8 : DynamicResourceNamePropertyResolver {}
```

Users who want to keep the 8.x naming scheme can write the following code at the beginning of their AppHost:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.Services.Configure<AzureProvisioningOptions>(options =>
{
    options.ProvisioningContext.PropertyResolvers.Insert(0, new AzureResourceNamePropertyResolverAspirev8());
});
```

~We should add a compatibility switch to allow developers who upgrade to the new version of .NET Aspire to continue using the same "deployment version" as a previous version.~

~One way we could do this is to allow `Annotations` on the `IDistributedApplicationBuilder`. One of the annotations would be an `AzureDeploymentVersion` annotation that would have values like:~

* 8
* 9
* Current

~`Current` would be the default if there is no annotation specified. We would add new versions as we needed. And new breaking changes to the bicep would be gated behind a check if the specified AzureDeploymentVersion was "new enough".~

~This allows people to use the `9.0` .NET Aspire, but continue to use the old naming scheme.~

~We would also use this in other behavior changes - like when we change Azure PostgreSQL and Redis to use managed identity by default. Other "better defaults, but breaking changes" would do the same.~

cc @mitchdenny @davidfowl @tg-msft

**Comment by tg-msft** [comment]
Consider exposing this via a default value like `AddAzureStorage(..., AzureDeploymentVersion version = Current)`?  This would let us compile in the constant when not specified to avoid binary breaks but otherwise float on latest.  It's effectively how we handle service versions for Azure's data plane.  You could also do `AddAzureStorage(..., AzureDeploymentVersion? version = null)` and translate `null` into whatever's in the `Annotations` if you want an easy global default.

**Comment by eerhardt** [comment]
@tg-msft - so your suggestion is to have both a "global" `AzureDeploymentVersion` for the whole app, as well as one for each Resource. And if the value is provided on a specific Resource that overrides the "global" value?

**Comment by tg-msft** [comment]
Yes.  I think you're going to want more granularity than "all 8" or "all 9."  We could always start globally though and add per-resource overrides in the future.

**Comment by eerhardt** [comment]
Linking with @mitchdenny's proposal: https://github.com/dotnet/aspire/issues/3121 to make this `class` based instead of a version enum / number.

**Comment by mitchdenny** [comment]
I'd actually like to obsolete the existing `PublishAsXYZ/AzXYZ` methods and just have `WithAzure<T>` with a `WithAzure` that has a default T that mimics current behavior. Then we obsolete the old methods.

**Comment by eerhardt** [comment]
I've updated this proposal to remove the versioning part. Instead, we can solve this issue by allowing users to customize the ProvisioningContext being used to produce bicep.
