### ISSUE TITLE
Add option to Aspire template to create a test project that uses the AppHost

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#579]
Once we solidify the story for #416 we should consider adding an option in the templates (empty and starter) to include a test project that references the AppHost project and uses it to coordinate startup of the relevant projects when running under an integration test.

**Comment by stbau04** [comment]
Are there any examples for the integration tests? https://github.com/dotnet/aspire/issues/416 is closed but there is no publically available samples/documentation/pr providing information on how this is thought

**Comment by DamianEdwards** [comment]
I started to build one in a branch in the aspire-samples repo but turned it into feature work instead as I wasn't happy with the experience. On mobile right now so can't link issue but if you search for issues authored by me about testing you'll find it. @davidfowl is going to work on it in preview 4.

**Comment by stbau04** [comment]
I think you mean https://github.com/dotnet/aspire/issues/1704?

**Comment by davidfowl** [comment]
Moving to P5. @ReubenBond is working on the test scenario.
