### ISSUE TITLE
Azure Redis should support managed identity

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#5794]
Similar to [Azure PostgreSQL should support managed identity (dotnet/aspire#5793)](https://github.com/dotnet/aspire/issues/5793), we should support managed identity when publishing an Azure Cache for Redis resource.

### Proposal

Add a new enum that gets passed into `.[Publish]AsAzureRedis()` that switches which kind of auth is used.

```C#
namespace Aspire.Hosting.Azure;

public enum AzureRedisAuth
{
    Password = 0,
    ActiveDirectory = 1 // Note the name used in bicep and ARM is `aad-enabled`
}

// user code
builder.AddRedis("cache")
    .PublishAsAzureRedis(AzureRedisAuth.ActiveDirectory);
```

cc @mitchdenny @davidfowl @tg-msft @sebastienros @radical

**Comment by Meir017** [comment]
We might need to use https://github.com/Azure/Microsoft.Azure.StackExchangeRedis for this

**Comment by eerhardt** [comment]
> We might need to use https://github.com/Azure/Microsoft.Azure.StackExchangeRedis for this 

Yes, that is what the actual app that connects to Azure Cache for Redis would need to use to authenticate. This is the reason why I'm not proposing to make ActiveDirectory auth the default, because it would break apps that didn't use Microsoft.Azure.StackExchangeRedis. This is similar to PostgreSQL in #5793.

**Comment by eerhardt** [comment]
Note the above proposed API wasn't implemented. See #5966 for a discription of the approved API.
