### ISSUE TITLE
[Dashboard] Clicking "View Logs" in Trace navigates to wrong querystring

### ISSUE THREAD

**Issue by brettwinters** [dotnet/aspire#5796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clicking View Logs in a trace navigates to : `/structuredlogs?spanId=xxxxxxx`  which does not find the logs. But when I manually filter using the same spanId: `/structuredlogs?filters=log.spanid:equals:xxxxxxx` it correctly lists the logs

Original issue: #5438, #4005

It looks like it was supposed to be fixed already in 8.1 : #5026 

### Expected Behavior

Either fix the querystring so that `/structuredlogs?spanId=xxxxxxx` works or use `/structuredlogs?filters=log.spanid:equals:xxxxxxx`

**Comment by JamesNK** [comment]
This is fixed in 8.2.
