### ISSUE TITLE
Direct link to console log doesn't refresh logs

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspire#5864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the main branch on eShop, the link "View Console Logs" opens a new page but the log remains empty. It's only when we use the drop down list to select another resource that the logs show up.

![image](https://github.com/user-attachments/assets/8cb1608d-f159-4cdf-8daa-6bad9775fb8d)

![image](https://github.com/user-attachments/assets/8eae76f5-e44d-470e-84cc-3443babe7521)

It reproes for every resource, and repeats every time we open the logs using the same link.

Refreshing the page also fixes the issue.

### Expected Behavior

The logs should refresh by themselves.

### Steps To Reproduce

Use eShop with the Aspire main branch packages. Haven't tries with the local playground apps.

**Comment by davidfowl** [comment]
@JamesNK the console logs UI might need some playwright tests. We seem to regress this behavior pretty often

**Comment by JamesNK** [comment]
@sebastienros Are you rebased on the latest source code? This was recently fixed.

**Comment by JamesNK** [comment]
I talked with @sebastienros and he said this error was on his branch. I'm pretty sure this is just a case of running code that doesn't have an earlier fix.
