### ISSUE TITLE
[tests] Install the new analyzers for workload tests

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#5876]
For analyzers in general, we should install these for the workload/template tests too, have them turned on, and use `warnAsError` so we can catch issues that users might run into.

_Originally posted by @radical in https://github.com/dotnet/aspire/issues/5775#issuecomment-2370157368_

**Comment by eerhardt** [comment]
> we should install these for the workload/template tests too

The analyzer comes as part of the AppHost nuget package, so it is already installed.

> have them turned on

I believe the analyzer is already enabled, by default.

> and use `warnAsError`

This might be the only work we need to do. If we don't already, we should have warnings as errors in these tests.

**Comment by DamianEdwards** [comment]
The analyser just added reports at the error level by default, so I'm not sure there's anything to do here?

**Comment by radical** [comment]
Thanks for the feedback. Indeed it seems the main thing is to enable `warnAsError`. But related to that I found that analzyers are not working for playground apps - https://github.com/dotnet/aspire/issues/5883 , but msbuild doesn't error out about it!

I will fix that, and add the `warnAsError`.

**Comment by DamianEdwards** [comment]
> But related to that I found that analzyers are not working for playground apps

Is this in Helix you mean? They seem to work locally in VS for playground apps just fine.

**Comment by radical** [comment]
> > But related to that I found that analzyers are not working for playground apps
> 
> Is this in Helix you mean? They seem to work locally in VS for playground apps just fine.

Yeah. We build `Aspire.Playground.Tests.csproj` on helix itself, but the `Analyzers` `src` project isn't available there. But that's probably not needed because the playground apps would be referencing the `AppHost` nuget package, right? Sorry, I haven't had a change to dig into this yet.

**Comment by DamianEdwards** [comment]
> because the playground apps would be referencing the AppHost nuget package

Correct, and it includes the analyzer.

**Comment by radical** [comment]
Workload tests are already using `TreatWarningsAsErrors` for all the template tests. And the playground issue is tracked in https://github.com/dotnet/aspire/issues/5883, so closing this.
