### ISSUE TITLE
Regression: ReplicasAndProxylessEndpointThrows test fails

### ISSUE THREAD

**Issue by davidebbo** [dotnet/aspire#5898]
`ReplicasAndProxylessEndpointThrows` is disabled in CI per #4651, but I was running it frequently and it was passing reliably.

It became broken a few days ago due to a5b3bcfddb3478ab34f207251929d531322d1a85. The root of the problem is that the new code never calls `ExecutableReplicaSet.Create`, and no `ExecutableReplicaSet` instance is ever created.

Yet `ApplicationExecutor` has error handling logic that tests for it, and this is why the test is failing:

```c#
if (appResource.DcpResource is ExecutableReplicaSet ers && ers.Spec.Replicas > 1)
{
    throw new InvalidOperationException($"Resource '{modelResourceName}' uses multiple replicas and a proxy-less endpoint '{ea.Name}'. These features do not work together.");
}
```

It seems like a valid error detection situation, which has regressed.

**Comment by davidfowl** [comment]
cc @JamesNK
