### ISSUE TITLE
Elasticsearch container failing with 137 error

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#5915]
Here is what RNS is giving us:

![image](https://github.com/user-attachments/assets/625853f0-3b4c-494d-b187-d1ba1a15cac3)

Based on a web search this appears to be due to a memory deficiency:

https://discuss.elastic.co/t/error-elasticsearch-exited-unexpectedly-with-exit-code-137/361047

@radical I just wanted to better understand the environment on the Helix machines. Do you know how much ram they have, and do we know to which degree test execution is parallelized in Helix?

**Comment by radical** [comment]
> @radical I just wanted to better understand the environment on the Helix machines. Do you know how much ram they have,

Looking at a helix log `docker info` says:
```
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.744GiB
```

> and do we know to which degree test execution is parallelized in Helix?

We shouldn't be running any tests in parallel on helix, as of 2 weeks ago.

**Comment by mitchdenny** [comment]
OK .. in that case I'm going to change some of our verification tests that need a second container to use one that is much lighter weight. Maybe we can improve reliability that way.

8GB seems a bit on the light side though.

**Comment by joperezr** [comment]
Seems from the above that this was addressed by using a different container image, so I'm closing this for now. @mitchdenny please reopen if that is not the case.
