### ISSUE TITLE
[WebToolsE2E][Aspire] Some strings in the Aspire Dashboard under Structured logs | Level are not localized in non-ENU OS.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#5916]
**REGRESSION**
1. Reproduce in 8.1.0 and 8.2.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 22h2 CHS
2. Install VS 17.11.4
3. Install Aspire 8.2.1

**REPRO STEPS**

1. Create Aspire App project
2. Build solution and F5
3. Navigate to Structured logs and click dropdown button under Level

**ACTUAL**
The strings [Trace/Debug/Information/Warning/Error/Critical] under Level section are not localized
![image](https://github.com/user-attachments/assets/5777efbf-0bb3-4942-b9c5-083f2ac95a3c)

**EXPECTED**
These strings should be localized.

**Comment by vmykagapuz** [comment]
This issue is also reproduce in aspire 9.0 p4 build.

**Comment by JamesNK** [comment]
These come from API values. They intentionally weren't localized.
