### ISSUE TITLE
Starter template app broken if created with default options but run with http launch profile

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#592]
An app created with the starter template is broken if created with the default options but run with the "http" launch profile. This is because by default https is enabled, which creates the projects with two launch profiles, one for "http" and one for "https", but the URL emitted in the frontend project for the API service is "https://", so when launched with the "http" profile, the API service is not listening on https and so the call fails.

We should consider changing the templates so that only one launch profile is emitted depending on the options used, i.e. "http" or "https".

**Comment by DamianEdwards** [comment]
We'll need to revisit this at some point to reconsider whether we want to add HTTPS support back to the templates and how to improve the E2E for all environments.

**Comment by davidfowl** [comment]
Related to https://github.com/dotnet/aspire/issues/381

**Comment by DamianEdwards** [comment]
We should start looking at this in preview 4 if possible.

**Comment by joperezr** [comment]
Moving to Preview 5 in favor of removing milestone preview TBD.

**Comment by DamianEdwards** [comment]
Part of #2453
