### ISSUE TITLE
Update Redis Component to use ILoggerFactory

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#594]
StackExchange.Redis version [2.7.4 has been released](https://github.com/StackExchange/StackExchange.Redis/releases/tag/2.7.4). We should update the Redis component to this version.

Along with this update, a new API was introduced: https://github.com/StackExchange/StackExchange.Redis/pull/2051. This API allows a ConfigurationOptions to specify an `ILoggerFactory` to be used when the ConnectionMultiplexer needs to log information.

We should populate this ILoggerFactory in the Component and remove this class:

https://github.com/dotnet/aspire/blob/12af412b50c7533a75748edae2776d70a64c890e/src/Components/Aspire.StackExchange.Redis/AspireRedisExtensions.cs#L145-L150

**Comment by davidfowl** [comment]
We did this https://github.com/dotnet/aspire/pull/1628
