### ISSUE TITLE
[WebToolsE2E][Aspire] When adding a package to the AppHost project, an error occurs: Package 'Aspire.Hosting.Azure.Storage' is incompatible.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#5950]
**REGRESSION INFO**: Worked in Aspire 8.2.0 and Aspire 8.2.1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.402
3. Install Aspire 9.0.0-preview.4.24475.11

**REPRO STEPS**

1. Open CMD, run following command to create an Aspire Starter App project
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
```
2. Run the following command to install the Aspire package:
`dotnet add package Aspire.Hosting.Azure.Storage --version 9.0.0-preview.4.24475.11`

**NOTE**: This happens not only in Aspire.Hosting.Azure.Storage, but also in other packages, for example: Aspire.Hosting.Azure.CosmosDB, Aspire.Hosting.Azure.KeyVault, etc.

**ACTUAL**
Cannot add packages to AppHost project.
![image](https://github.com/user-attachments/assets/3d3d0c0f-ab07-44ac-86ea-e764f80c5a2f)

info :   NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49a1bb2b-12b0-475f-adbd-1560fc76be38/nuget/v3/flat2/azure.provisioning/index.json 133ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49a1bb2b-12b0-475f-adbd-1560fc76be38/nuget/v3/flat2/azure.provisioning.keyvault/index.json 138ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/49a1bb2b-12b0-475f-adbd-1560fc76be38/nuget/v3/flat2/azure.provisioning.storage/index.json 321ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_packaging/11fce3f3-5bc0-4ab8-9b15-28ca0686642a/nuget/v3/flat2/azure.provisioning.keyvault/index.json 293ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_packaging/886f5339-879a-4b9e-872f-bca710da5d8d/nuget/v3/flat2/azure.provisioning.keyvault/index.json 268ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_packaging/11fce3f3-5bc0-4ab8-9b15-28ca0686642a/nuget/v3/flat2/azure.provisioning.storage/index.json 394ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_packaging/886f5339-879a-4b9e-872f-bca710da5d8d/nuget/v3/flat2/azure.provisioning/index.json 302ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_packaging/11fce3f3-5bc0-4ab8-9b15-28ca0686642a/nuget/v3/flat2/azure.provisioning/index.json 398ms
info :   NotFound https://pkgs.dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_packaging/886f5339-879a-4b9e-872f-bca710da5d8d/nuget/v3/flat2/azure.provisioning.storage/index.json 421ms
error: NU1102: Unable to find package Azure.Provisioning with version (>= 1.0.0-alpha.20240918.3)
error:   - Found 6 version(s) in nuget.org [ Nearest version: 0.3.0 ]
error:   - Found 0 version(s) in dotnet8.0
error:   - Found 0 version(s) in dotnet9.0rc2
error:   - Found 0 version(s) in dotnet8
error: NU1102: Unable to find package Azure.Provisioning.Storage with version (>= 1.0.0-alpha.20240918.3)
error:   - Found 3 version(s) in nuget.org [ Nearest version: 0.2.0 ]
error:   - Found 0 version(s) in dotnet8.0
error:   - Found 0 version(s) in dotnet9.0rc2
error:   - Found 0 version(s) in dotnet8
error: NU1102: Unable to find package Azure.Provisioning.KeyVault with version (>= 1.0.0-alpha.20240918.3)
error:   - Found 3 version(s) in nuget.org [ Nearest version: 0.2.0 ]
error:   - Found 0 version(s) in dotnet8.0
error:   - Found 0 version(s) in dotnet9.0rc2
error:   - Found 0 version(s) in dotnet8
info :   CACHE https://api.nuget.org/v3/vulnerabilities/index.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.09.24.23.37.09/vulnerability.base.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.09.24.23.37.09/2024.09.25.23.37.11/vulnerability.update.json
warn : NU1903: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
error: Package 'Aspire.Hosting.Azure.Storage' is incompatible with 'all' frameworks in project 'C:\Users\v-reinawang\AspireStarterApp\AspireStarterApp.AppHost\AspireStarterApp.AppHost.csproj'.

**EXPECTED**
The package can be added successfully.

**Comment by davidfowl** [comment]
You need this feed:

```xm
    <add key="azure-sdk-devfeed" value="https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json" />
```

or

```
dotnet nuget add source --name azure-sdk-devfeed https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json
```

**Comment by v-reinawang** [comment]
Yes, after I added this feed, I can successfully add the package to the AppHost project. So is this expected?

**Comment by davidfowl** [comment]
until we ship yes. Packages will be on nuget eventually
