### ISSUE TITLE
[AzureTools][Aspire] It would be better if the tooltip pos up when hovering over the stop icon below the "Action" in the Dashboard

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#5953]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.12.0 Preview 3.0 [35325.140.main]
Aspire Version: 9.0.0-preview.4.24475.6
Apply NuGet Feeds
**Podman Desktop:** 1.12.0
**Podman CLI:** 5.2.3

**REPRO STEPS:**

1. Create an Aspire starter project with "Use Redis for caching (requires Docker)" checked.
2. Update package references to all of Aspire dependencies to version `9.0.0-preview.4.24475.6 `-> Add `<Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0-preview.4.24475.6" />` to the AppHost project file.
3. F5 -> Hover over the stop icon below the "Action".
    ![image](https://github.com/user-attachments/assets/0d2b4997-a452-439c-bc40-a9bd028b8a79)
4. Check whether the tooltip pos up.

**Suggestion:**
It would be better if the tooltip pos up.
![image](https://github.com/user-attachments/assets/6c588b14-d720-4dcd-bcc4-7d48f19bc74e)

**Actual:**
No tooltip pos up.

**More Info:**
Similarly, the tooltip message should change as the icon changes.

**Comment by DamianEdwards** [comment]
Was this fixed by #5969?

**Comment by v-mengwe** [comment]
Verified on the Aspire 9.0.0-preview.4.24478.1, this issue is fixed.
![image](https://github.com/user-attachments/assets/e857f843-c14b-4be1-bf4b-15097019c0c3)
