### ISSUE TITLE
[WebToolsE2E][Aspire] In Aspire 9.0 RC1 dashboard there are some strings that are not localized in non-ENU OS.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#5980]
INSTALL STEPS
1. Clean machine: Win11 x64 22h2 DEU
2. Install VS 17.12 Preview 3
3. Install Aspire 9.0 RC1

REPRO STEPS
1. Create Aspire Starter App
2. Build solution and run the project

ACTUAL

The following are the strings that are not localized

1. The "Close" in Settings
![image](https://github.com/user-attachments/assets/728da70f-5cd1-4fd8-bfd9-c35208abaf0d)

2. In Resources

- The "Actions" & [View Details/Console logs/Structured logs/Traces/Metrics/Restart] under 3 dots button
![image](https://github.com/user-attachments/assets/8abbb76e-a655-4ad0-b9f0-2970ea2067e8)

3. The "None" option in Console and Metrics
![image](https://github.com/user-attachments/assets/7344367a-512c-46d4-84e7-42c472292b74)

4. In Structured and Traces

- The "All" option in Resource and Level under Structured
![image](https://github.com/user-attachments/assets/64d3bcd4-8fbb-4c62-981c-3628f1b88e4f)
![image](https://github.com/user-attachments/assets/3cdede7c-4622-49a1-b5b2-5e77f17a5665)

- The "Filters" & "No filters"
![image](https://github.com/user-attachments/assets/f016f7e3-f992-4745-90c0-0e5d7e575f96)

- The "Add Filter" under Filters section
![image](https://github.com/user-attachments/assets/2868e0b5-abe1-4a92-9fc0-2c7e88c2155d)

- The strings option under Parameter
![image](https://github.com/user-attachments/assets/301d8faa-ac43-40fd-898d-54163b852d06)

- The "contains" & "not contains" in Condition
![image](https://github.com/user-attachments/assets/661d0800-a572-421e-9d64-ab3783568a2e)

5. The "Restart" under 3 dots button in aspire dashboard after publish
![image](https://github.com/user-attachments/assets/519bc7cb-1e8e-4235-b511-9fb6202564c5)

EXPECTED
The mentioned strings should be localized.

**Comment by vmykagapuz** [comment]
I updated the Actual Result adding more items of untranslated strings found in KOR and CHS OS.

**Comment by drewnoakes** [comment]
@vmykagapuz it's helpful to know if a translation is missing in just one language, or in all languages.

1. If just one language, then the loc team needs to make a fix.

2. If all languages, there's a chance that it's a product bug, and we're not using a localized value in that part of the UI.

There are some fixes for the second scenario in https://github.com/dotnet/aspire/pull/6348.

**Comment by vmykagapuz** [comment]
@drewnoakes We'll check with the latest build next Monday and classify the issue according to your suggestion.
