### ISSUE TITLE
[AzureTools][Aspire] There is no "Health State" option in the "Resource" when viewing detail for a container created by .withdockerfile

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#5982]
**Clean machine:** Win11 x64 23H2 ENU
**VS Version:** VS 17.12.0 Preview 3.0 [35326.43.main]
**Aspire Version:** 9.0.0-preview.4.24475.6
Apply NuGet Feeds
**Docker Desktop:** 4.32.2

**REPRO STEPS:**

1. Create a new .NET Aspire Starter Application.
2. Right-click the web project -> Add -> Docker Support -> Linux and Dockerfile.
3. Add .withdockerfile codes in the programs.cs file of AppHost project.

```
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");

var apiService = builder.AddProject<Projects.AspireApp2_ApiService>("apiservice");
var container = builder.AddContainer("dockercontainer", "dockerimage")
                       .WithDockerfile("../.", "./AspireApp2.Web/Dockerfile");
builder.AddProject<Projects.AspireApp2_Web>("webfrontend")
       .WithExternalHttpEndpoints()
       .WithReference(cache)
       .WithReference(apiService);

builder.Build().Run();
```
4. Add the NuGet.Config file to the web project-> Add code `COPY ["AspireApp2.Web/NuGet.Config", "."]` into Dockerfile file for the web project.
5. F5 -> Click "View Detail" of the container created by .withdockerfile.
6. Check whether there is a "Health State" option in the "Resource".

**Expect:**
There is a "Health State" option in the "Resource".
![image](https://github.com/user-attachments/assets/abc546f7-b8d0-4668-8477-3a6e35a3dd6e)

**Actual:**
There is no "Health State" option in the "Resource".
![image](https://github.com/user-attachments/assets/d8e21807-448a-432f-be49-f36474489a8d)

**Comment by davidfowl** [comment]
That’s by design, heath checks are need to be explicitly added for the health state to show up. We add them for pre built containers, not custom ones built with docker files. That’s up to the user to do.

**Comment by v-mengwe** [comment]
Got it, thanks for the update, close this issue due to it is "by design".
