### ISSUE TITLE
Tracking of resource state for project that crashes on startup gets out of sync

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#5985]
Using Aspire build 9.0.0-preview.4.24477.2

Running application at https://github.com/DamianEdwards/AspireStarterDb

The project `AspireStarterDb.ApiDbService` crashes shortly after starting due to a failing background service (this is expected). The state of the resource in the dashboard is inconsistent though, with it sometimes showing the project as still running, despite it having an exit code and the process not existing. Attempting to stop the resource from the dashboard yields a message that the command was successful but the state doesn't change. In some cases this state inconsistency happens immediately after running the AppHost, in other cases it takes a few cycles of restarting the failing project from the dashboard before the state seemingly gets out of sync.

Repros from both Visual Studio and `dotnet run`.

https://github.com/user-attachments/assets/8ce3a437-38b0-4506-9b6c-525df1a184c5

**Comment by karolz-ms** [comment]
The scenario works fine with DCP 0.8.6 that is slated to be integrated with Aspire 9 later today. We made a couple of fixes to Executable change tracking recently and I have a strong suspicion that one of them fixed this issue.

**Comment by DamianEdwards** [comment]
@karolz-ms this is still reproducing for me with DCP 0.8.7

If I make an orchestrated project fail during start (non-zero exit code) then the dashboard reports it as running **AND** having an exit code:

![image](https://github.com/user-attachments/assets/4a3b855a-6b4a-4487-a474-ff60e52106f4)

**Comment by davidfowl** [comment]
@DamianEdwards we're at 0.8.8 now on main, try updating.

**Comment by DamianEdwards** [comment]
This still repros for me using DCP 0.8.8

**Comment by DamianEdwards** [comment]
@danegsta and I went through the repro on my machine yesterday and the latest changes to DCP improve this for CLI but in IDE scenarios I can still repro it every time. @danegsta is working on a larger change that will hopefully solve this properly for 9 GA.
