### ISSUE TITLE
The dashboard should let me dynamically configure the log level for a service (or globally)

### ISSUE THREAD

**Issue by baronfel** [dotnet/aspire#599]
There's a Spring Boot Admin UI for toggling log levels for categories at runtime: https://www.baeldung.com/spring-boot-changing-log-level-at-runtime

Today we can do this by changing appsettings.json and letting the provider reload the file, but we should plumb this into the dashboard so that devs have an intuitive way to briefly tweak the levels.

**Comment by davidfowl** [comment]
This would be awesome as a command but I'm moving this out of scope for now.

**Comment by davidfowl** [comment]
Oh great this is a dupe. Closing.
