### ISSUE TITLE
Stylesheet missing on dashboard.

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#6001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When opening the dev tools on the 9.0.0-preview.4.24477.2 dashboard started by the app host, there is a stylesheet that failed to apply
![image](https://github.com/user-attachments/assets/f27a44ba-94a0-442a-81f9-ac31839d7949)

Going to the url in a browser results in a 404
![image](https://github.com/user-attachments/assets/65e233a0-5ea6-4849-b46d-08a4865346fc)

### Expected Behavior

No errors in the dev tools

### Steps To Reproduce

1. Create a new Aspire AppHost project using `9.0.0-preview.4.24477.2`
2. Run the project
3. Go to the aspire dashboard (e.g. https://localhost:17206/login?t=e4b62341a0d90a27e08ee3347540dde)
4. Check the browser developer tools for errors

### Anything else?

Microsoft Edge
Version 129.0.2792.52 (Official build) (64-bit)

**Comment by adityamandaleeka** [comment]
This is being fixed in https://github.com/dotnet/aspire/pull/6019
