### ISSUE TITLE
Add logging to Dashboard

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspire#602]
Most of the dashboard work happens in background thread. Whenever something goes wrong it is hard to find what failed since exception doesn't bubble up from background thread, it would silently terminate. Add logging for dashboard so we can investigate failures easily/faster and can get logs from users who are running into issues.

**Comment by davidfowl** [comment]
@drewnoakes I'm going to close this issue but you can do clean up to the dashboard as we do more work and refactoring on it.
