### ISSUE TITLE
[WebToolsE2E][Aspire] On a clean Windows machine with only .NET 9 SDK installed, run `dotnet new install Aspire.ProjectTemplates` and we get error that it is not supported

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#6026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install .NET SDK 9.0 RC2 - latest version
    - Apply dotnet9rc2feed
    - Run cred helper to authenticate the feed
1. Install Aspire.ProjectTemplates - latest version **9.0.0-preview.4.24480.1**
    - Add dotnet8 feed
    - `dotnet new install Aspire.ProjectTemplates:9.0.0-preview.4.24480.1 --force`

**EXPECTED**
Aspire project templates are installed successfully

**ACTUAL**
Error saying that the Aspire.ProjectTemplates are not supported

![image](https://github.com/user-attachments/assets/086a846c-70b7-4d9f-b1df-1a0bb8a87bc6)

**dotnet --info**
![image](https://github.com/user-attachments/assets/ade907e8-e503-4c13-974c-0e24434a3678)

**dotnet workload list**
![image](https://github.com/user-attachments/assets/f1213c78-8039-4e5a-a87c-67819b8fef5c)

**Comment by DamianEdwards** [comment]
I think the work for this is still in progress, right @radical?

**Comment by DamianEdwards** [comment]
This has been merged now so we should be able to try this again with latest drop.

**Comment by balachir** [comment]
@radical I can get this to work now. Can we close this issue?

![image](https://github.com/user-attachments/assets/990ba2b9-01a7-4098-ae9d-6aa736d5a66e)

**Comment by radical** [comment]
> I can get this to work now.
Thank you!

> Can we close this issue?

Yes.
