### ISSUE TITLE
Add logging when user-defined Storage resource tramples default Host storage

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspire#6034]
The implementation currently auto-configures a storage resource with the name `azFuncHostStorage` when no storage resource is configured. If a storage resource with the same name is already defined, it will use that one instead.

```
builder.AddAzureStorage("azFuncsHostStorage");

builder.AddAzureFunctionsProject<Projects.MyFuncs>("MyFuncs");
```

We should add a warning log when this happens to alert that user that this behavior is happening. This will have particular impact when they are publishing since only the storage resource that we allocate is configured with the `StorageAccountContributor` permissions that are required for blob triggers.

**Comment by davidfowl** [comment]
FYI, it can't trample, it will just throw, when resource names are duplicated.

**Comment by captainsafia** [comment]
We've taken a different approach here and are instead generated unique default host storage resource names to avoid conflicting.
