### ISSUE TITLE
Ubuntu 24.04 Postgres unable to resolve names

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/aspire#6052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On an Ubuntu 24.04 developer workstation with a fresh docker install, I am unable to connect to the database with messages reported in the dashboard the name resolution failed.

### Expected Behavior

Able to connect to the database with no errors

### Steps To Reproduce

1. Create the default .NET Aspire template
2. Add the `Aspire.Hosting.Postgresql` package to the AppHost projec
3. Add a postgres server with PgAdmin:

```csharp
builder.AddPostgres("db").WithPgAdmin();
```

4. Start the application and navigate to the PgAdmin instance after the database is started.  
5. Open the list of servers and attempt to connect to the 'db' instance

### Exceptions (if any)

Error resolving name for 'db'

**Comment by davidfowl** [comment]
You might be running into this https://github.com/dotnet/aspire/issues/5584

**Comment by csharpfritz** [comment]
Ah, there it is... this is a duplicate of #5379 except I am seeing it on Ubuntu
