### ISSUE TITLE
Dashboard's details page has a pop-up that shows up hidden under another element

### ISSUE THREAD

**Issue by davidebbo** [dotnet/aspire#6109]
Video says it all. I can provide more info in that's not clear. That's with latest github bits.

https://github.com/user-attachments/assets/42974dd4-ad76-4632-9414-73cd428357ae

**Comment by drewnoakes** [comment]
cc @vnbaaij @JamesNK following changes to how popups are presented. Is there something we need on our side to prevent this, or should we file a bug against the Blazor FluentUI repo?

**Comment by JamesNK** [comment]
https://github.com/microsoft/fluentui-blazor/issues/2761

**Comment by davidebbo** [comment]
Verified.

**Comment by vnbaaij** [comment]
Fixed on our side for next release as well: https://github.com/microsoft/fluentui-blazor/pull/2772
