### ISSUE TITLE
Resources in a waiting state should not show up as healthy

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#6125]
<img width="936" alt="image" src="https://github.com/user-attachments/assets/5e9cb573-cc89-447c-9d41-cd0347320937">

**Comment by davidfowl** [comment]
cc @drewnoakes

**Comment by drewnoakes** [comment]
What would you like to see instead?

Does the answer change if the resource has health checks or not?

**Comment by davidfowl** [comment]
nothing, there's no health state, it's null

**Comment by davidfowl** [comment]
Not available

**Comment by davidfowl** [comment]
Health state also shows up for finished resources

![Image](https://github.com/user-attachments/assets/43e87207-475d-4d9e-a00e-d6faed90269a)

**Comment by drewnoakes** [comment]
We could just filter out the property based on state, in the app host.
