### ISSUE TITLE
Remove exception details UX now that we can view log message

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#6130]
![image](https://github.com/user-attachments/assets/a7045f1a-3c91-4314-8dc4-56439b575de7)

We have https://github.com/dotnet/aspire/pull/6064. We can consider a top level button to view the log message

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
It’s still useful. Exception and message are different. Without this, the only way to know there is an exception is to open details.

**Comment by davidfowl** [comment]
The current ux isn’t great, think it should be a button thst opens the same pop up instead of being triggered on hover

**Comment by JamesNK** [comment]
Could give it a try

**Comment by drewnoakes** [comment]
Proposed fix in https://github.com/dotnet/aspire/pull/6230
