### ISSUE TITLE
ToSnapshot in ApplicationExecutor removes Urls that may have been added to the state earlier.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#6133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was experimenting with adding URLs for Codespaces and I noticed that even though I was adding some URLs to the resource snapshot via an event, by the time the dashboard was visible they weren't there. The underlying issue is that in ToSnapshot we get the URLs but don't retain the existing ones.

### Expected Behavior

When a Url is added to a resource snapshot it should survive the startup of container and executable resources.

### Steps To Reproduce

Add this to your `Program.cs`:

```csharp
builder.Eventing.Subscribe<BeforeResourceStartedEvent>(async (@e, ct) =>
{
    var rns = e.Services.GetRequiredService<ResourceNotificationService>();

    await rns.PublishUpdateAsync(e.Resource, s =>
    {
        var additionalUrl = new List<UrlSnapshot>()
        {
            new UrlSnapshot("via Codespaces", "https://blah.blah.blah", false)
        };

        return s with
        {
            Urls = [.. additionalUrl]
        };
    });
});
```

**Comment by davidfowl** [comment]
I don’t think this is a bug , I think the fix is to allow modeling URLs as an annotation.

**Comment by mitchdenny** [comment]
I am 90% there with you on that. I think adding a `UrlAnnotation` or somethin similar is definately warranted. It would simplify quite a few things in terms of propogating URLs between snapshots of resource replicas for example.

That said I do think that there is a bug here in that `ToSnapshot` shouldn't blow away the URLs either.

I guess if URLs were an annotation it would become similar to the injection of health status into the snapshot.

**Comment by davidfowl** [comment]
It has to blow away the URLs it’s the source of truth. It’s the same reason you can’t update other properties out of band that dcp also updates.
