### ISSUE TITLE
AddAzurePostgresFlexibleServer(..).RunAsContainer(...).AddDatabase(...) results in missing annotations on child resources

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#6146]
When using the new `AddAzurePostgresFlexibleServer(...)` method with `RunAsContainer(...)` the annotations from child resources are not copied to the internally instanced `PostgresDatabaseResource` instances. This would result in some mechanisms like WithCommand(...) not working.

Picked it up whilst looking to support `WaitFor` with child resources.

**Comment by eerhardt** [comment]
@mitchdenny - is there a way to listen when an Annotation is added/removed to a resource's Annotation collection? That way we can sync up the annotations between the 2 child resources.
