### ISSUE TITLE
[WebToolsE2E][Aspire] After installing Aspire.ProjectTemplates.9.0.net8 via `dotnet new install`, two copies of Aspire project templates show up when we run `dotnet new list` and in VS New Project dialog

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#6149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**SET UP THE REPRO**

1. Clean machine: Win11 x64 23h2 ENU
1. Install SDK 8.0.402
    - from download page
1. Install Aspire 8.2.1 workload
    - dotnet workload update
    - dotnet workload install aspire
1. View the installed Aspire 8.x templates
    - dotnet new list
    - Works fine, Aspire templates show up
    - ![image](https://github.com/user-attachments/assets/b57b374a-1421-42c8-9847-45420a92d290)

**REPRO STEPS**

1. Install Aspire.ProjectTemplates - latest version **9.0.0-preview.4.24504.11**
    - Add dotnet8 feed
    - `dotnet new install Aspire.ProjectTemplates.9.0.net8::9.0.0-preview.4.24504.11--force`
    - Templates get installed fine
    - ![image](https://github.com/user-attachments/assets/4f4b1959-1e84-4bb6-91f5-45b21ba2058d)

1. Run `dotnet new list`

**ACTUAL**
1. Two sets of Aspire project templates show up
    -  ![image](https://github.com/user-attachments/assets/d4460bef-70fd-4777-b6f8-b242cd4e654f)

1. On a machine with VS installed too, two sets of Aspire project templates show up in New Project dialog
    - ![image](https://github.com/user-attachments/assets/dace6d41-66b4-4407-8918-4b0eb94b4b66)

**EXPECTED**
Two sets of Aspire templates showing up with the same names is confusing. The new set of templates should override the old ones.

**Comment by v-sherryfan** [comment]
Fixed on latest Aspire 9.0.0-rc.1.24511.1. @balachir Can you close this issue, please?

**Comment by balachir** [comment]
@v-sherryfan thanks for confirming. Closed now.
