### ISSUE TITLE
[WebToolsE2E] For an Azure Function app under Aspire orchestration, we don't show any Structured logs, traces and metrics

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#6153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install VS 17.12 Preview 3, latest build
    - includes .NET SDK 9.0 rc2
    - includes Aspire 8.2.0 workload
1. Install Aspire.ProjectTemplates - latest version **9.0.0-preview.4.24504.11**
    - Add dotnet8 feed
    - `dotnet new install Aspire.ProjectTemplates.9.0.net8::9.0.0-preview.4.24504.11--force`
    - Templates get installed fine

**REPRO STEPS**
1. New Project > Azure Functions app > .NET 8.0 Isolated > Http Trigger > Anonymous authentication > FunctionApp8
    - Also choose to 'Enlist in Aspire'
    - ![image](https://github.com/user-attachments/assets/cafc2825-9266-4e71-81e2-3dcc2eecc697)

2. Create project, build and Ctrl+F5 on the AppHost
3. Dashboard shows the Function app and we can navigate to the Console logs successfully
    - ![image](https://github.com/user-attachments/assets/15abfbe1-5d9a-4eb0-bbae-3ea00752e8a6)
    - ![image](https://github.com/user-attachments/assets/5c2310db-3753-4d81-958f-2304ce998ae2)

5. Try to view Structured logs, Traces and Metrics

**ACTUAL**
Structured logs, Traces and Metrics show up empty

![image](https://github.com/user-attachments/assets/25ee21ff-4260-416c-8bd5-75ecccb4cad9)

![image](https://github.com/user-attachments/assets/dd469b84-87cb-444e-baac-1eed2583f1bf)

![image](https://github.com/user-attachments/assets/d8ad89a2-6774-46e3-84be-7de3dcbe9429)

**EXPECTED**
 Structured logs, Traces and Metrics to be shown correctly

### .NET Version info
![image](https://github.com/user-attachments/assets/9c24a71e-74b3-4509-a4e3-25d29310476e)

**Comment by balachir** [comment]
I discussed with @vijayrkn and he mentioned that this needs to be fixed on the tooling side. Hence, I've added the `area-tooling` label.

**Comment by vijayrkn** [comment]
Tagging @captainsafia @phenning to track any pending scaffolding updates in functions.

**Comment by captainsafia** [comment]
@vijayrkn Some parts of this require a new build of the Azure Functions Core Tools in order to light up metric fully in the dashboard. This is in addition to the work to support the `AddServiceDefaults` support in the scaffolding.

We're tracking getting a new version of Core Tools over in https://github.com/dotnet/aspire/issues/6033.

**Comment by joperezr** [comment]
This needs re-verification.

**Comment by v-bennettyue** [comment]
This issue not repro on Dev17.12 GA + Aspire 9.0 GA, azure function tools is 4.99.

**Comment by balachir** [comment]
Structured logs and traces show up now. So I'll go ahead and close this issue. Metrics don't show up yet, we are tracking that one as a separate issue - https://github.com/dotnet/aspire/issues/6482.
