### ISSUE TITLE
[WebToolsE2E] For an Azure Function app under Aspire orchestration, errors in console do not show up in Resources pane of the dashboard

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#6154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install VS 17.12 Preview 3, latest build
    - includes .NET SDK 9.0 rc2
    - includes Aspire 8.2.0 workload
1. Install Aspire.ProjectTemplates - latest version **9.0.0-preview.4.24504.11**
    - Add dotnet8 feed
    - `dotnet new install Aspire.ProjectTemplates.9.0.net8::9.0.0-preview.4.24504.11--force`
    - Templates get installed fine

**REPRO STEPS**
1. New Project > Azure Functions app > .NET 8.0 Isolated > Http Trigger > Anonymous authentication > FunctionApp8
    - Also choose to 'Enlist in Aspire'
    - ![image](https://github.com/user-attachments/assets/cafc2825-9266-4e71-81e2-3dcc2eecc697)

2. Create project, build and Ctrl+F5 on the AppHost

3. Dashboard shows the Function app and we can navigate to the Console logs successfully
    - ![image](https://github.com/user-attachments/assets/15abfbe1-5d9a-4eb0-bbae-3ea00752e8a6)
    - ![image](https://github.com/user-attachments/assets/5c2310db-3753-4d81-958f-2304ce998ae2)

4. Back in VS, add new Function > Blob Trigger > Blob8.cs
    - ![image](https://github.com/user-attachments/assets/4173d44e-0e5b-4707-bb49-10504dfebce2)

5. Connect it to Azure Storage account

6. Ctrl+F5 again

**ACTUAL**
The Blob trigger fails to initialize due to a known issue. We can see this error called out in the Console logs. But the error does not propagate and show in the Resources pane.

![image](https://github.com/user-attachments/assets/b50187d4-913a-436d-8af0-c4d3973f6645)

Resources pane seems to indicate that everything works well.

![image](https://github.com/user-attachments/assets/995edf4e-2a7e-499b-b541-c001ebe473b8)

If we run the Functions app stand-alone, then we can see the errors clearly in the console

![image](https://github.com/user-attachments/assets/27ceb8f7-227d-4620-9988-e426ca03f296)

**EXPECTED**
Resources pane should show errors when there are errors in the console log

### .NET Version info
![image](https://github.com/user-attachments/assets/9c24a71e-74b3-4509-a4e3-25d29310476e)

**Comment by captainsafia** [comment]
@balachir Can you file another issue for the fact that you get this error when adding the Blob trigger? I believe this is the result of the code that is generated by the Connected Service integration and @vijayrkn would want this on the radar.

**Comment by balachir** [comment]
@captainsafia yes, fixing the actual error is tracked by bug 2254186 in AzDO.

**Comment by vijayrkn** [comment]
This should be fixed now. Resolving.
