### ISSUE TITLE
Container resources show a relevent status when not running because of missing container runtime

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#6169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Follow up to https://github.com/dotnet/aspire/issues/5533. Logging was added to app host and resource logs.

Container resources currently have a status of "Unknown". We should do better:

![image](https://github.com/user-attachments/assets/373fdba6-a5e8-4acf-856c-b350c0c4a81c)

### Describe the solution you'd like

DCP displays a status when the container runtime can't be found or isn't running. MissingRuntime? UnhealthyRuntime?

**Comment by davidfowl** [comment]
cc @dbreshears @danegsta
