### ISSUE TITLE
Clean up Azure Hosting APIs

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#6174]
We should do an API Review for the Azure Hosting APIs. Specifically:

- Remove the Experimental callbacks, for example
https://github.com/dotnet/aspire/blob/a8b1a619d67549243342dfd2c92cfaf26905cb65/src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs#L42-L43
    - Instead, callers will call `builder.AddAzureStorage("storage").ConfigureConstruct(c => ...)` if they want to customize the Azure resource

- Rename `ResourceModuleConstruct` to `AzureResourceInfrastructure` since it inherits from `Azure.Provisioning.Infrastructure`.

- Rename `AzureConstructResource` to `AzureProvisioningResource`

- Rename `ConfigureConstruct` to `ConfigureInfrastructure`
    - This matches the Azure.Provisioning naming of this type.

We should also take a holistic view of all our Azure Hosting APIs and do an API Review on them to make sure all the things we are shipping for 9.0 make sense for the long term.

cc @mitchdenny @davidfowl @tg-msft

**Comment by eerhardt** [comment]
* Expose `ContainerAppCustomizationAnnotation` publicly - cc @davidfowl

**Comment by davidfowl** [comment]
Rename `AddContainerAppsInfrastructure` to `AddAzureContainerAppsInfrastructure`.
