### ISSUE TITLE
Avoid writing manifest to disk for unit tests

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#618]
In #617 we added tests to verify that the manifest resources that we were emitting were suffixed with v0. We don't like hitting the disk for unit tests like this so we want to figure out a way that we can intercept actual I/O from the Utf8JsonWriter and write to memory instead and then read that data back for our assertions.

**Comment by davidfowl** [comment]
Did you do this one @mitchdenny ?

**Comment by mitchdenny** [comment]
Yes
