### ISSUE TITLE
ASPNETCORE_ENVIRONMENT is always Development

### ISSUE THREAD

**Issue by giammin** [dotnet/aspire#6185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Changing this environment variable in  launchSettings.json doesn't seem to have any effect on the application. It seems like something is setting DOTNET_ENVIRONMENT to development no matter what.

### Expected Behavior

setting environment variable (DOTNET_ENVIRONMENT ) in launchSettings.json should be reflected in the application  

### Steps To Reproduce

https://github.com/giammin/AspireEnvironmentIsAlwaysDevelopment

### .NET Version info

.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.3da906bd
 MSBuild version:   17.11.3+0c8610977

<details>
  <summary>additional info</summary>
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.11.35312.102
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  6.0.425 [C:\Program Files\dotnet\sdk]
  8.0.108 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
</details>

### Anything else?

I think this is related to this other bug: https://github.com/dotnet/aspire/issues/2101

**Comment by eerhardt** [comment]
In your WebApplication1, it looks like you are explicitly setting `Development`:

https://github.com/giammin/AspireEnvironmentIsAlwaysDevelopment/blob/88c23acdee81b6cadcbd0468153c57b11723d7eb/WebApplication1/Properties/launchSettings.json#L11

You would need to add a new launch setting profile in this file for `staging` that used the right environment variable.

**Comment by giammin** [comment]
isn't launch settings used only when launching a project directly?

**Comment by eerhardt** [comment]
Check out https://learn.microsoft.com/dotnet/aspire/fundamentals/launch-profiles to learn how Aspire and the launch profiles work. In short, the launch settings of each project are used (since you are starting multiple projects - the AppHost and each individual project).

**Comment by giammin** [comment]
ok thanks, so this is by design. 
closing this issue
