### ISSUE TITLE
Is Eventing still experimental in 9.0?

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#6196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Are events still experimental in 9.0.  Several of the events still state so in their XML docs.  I recall early on you had to do a `#pragma`  suppression to use the eventing api, but that no longer is required so I assume they're no longer experiemtnal.

https://github.com/search?q=repo%3Adotnet%2Faspire+%22This+experimental+event%22&type=code
https://github.com/dotnet/aspire/blob/371eb529769e898ac9a621fac86a2ff56df9094f/src/Aspire.Hosting/ApplicationModel/BeforeStartEvent.cs#L9
https://github.com/dotnet/aspire/blob/371eb529769e898ac9a621fac86a2ff56df9094f/src/Aspire.Hosting/ApplicationModel/AfterResourcesCreatedEvent.cs#L9
https://github.com/dotnet/aspire/blob/371eb529769e898ac9a621fac86a2ff56df9094f/src/Aspire.Hosting/ApplicationModel/AfterEndpointsAllocatedEvent.cs#L9

But other events don't call themselves experimental
https://github.com/dotnet/aspire/blob/371eb529769e898ac9a621fac86a2ff56df9094f/src/Aspire.Hosting/ApplicationModel/ConnectionStringAvailableEvent.cs#L9
https://github.com/dotnet/aspire/blob/371eb529769e898ac9a621fac86a2ff56df9094f/src/Aspire.Hosting/ApplicationModel/ResourceHealthyEvent.cs#L9

### Expected Behavior

If eventing is experimental, XML docs shouldn't claim they are.

**Comment by davidfowl** [comment]
@mitchdenny looks like it needs to be cleaned up.
