### ISSUE TITLE
Can't run the same Asp.net Core project multiple times with the different name. 

### ISSUE THREAD

**Issue by barbel840113** [dotnet/aspire#6197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This issue has not been resolved or rectified yet: https://github.com/dotnet/aspire/issues/1072. I still can't run or add more than one of the same project (under a different name) to the Microsoft Aspire Project. 

### Steps To Reproduce

Scaffold the new Aspire Project and register the service API multiple times under different names. 

### Exceptions (if any)

Should be able to run multiple projects of the same type under different names. 

### .NET Version info

.NET 8.0

**Comment by davidfowl** [comment]
Can you provide more details? The sample code and what error you ran into?

**Comment by barbel840113** [comment]
@davidfowl  here is the code. 

`var builder = DistributedApplication.CreateBuilder(args);

var apiServiceA = builder.AddProject<Projects.AspireTest_ApiService>("apiservice-a");

var apiServiceB = builder.AddProject<Projects.AspireTest_ApiService>("apiservice-b");

builder.AddProject<Projects.AspireTest_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(apiServiceB)
    .WithReference(apiServiceA);

builder.Build().Run();
`
Error message, which I am getting is 

`info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: D:\Projects\AspireTest\AspireTest.AppHost
fail: Aspire.Hosting.Dcp.dcpctrl.ServiceReconciler[0]
      could not start the proxy {"ServiceName": {"name":"apiservice-b-https"}, "Reconciliation": 9, "error": "could not start the proxy for the service: listen tcp [::1]:7526: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."}
fail: Aspire.Hosting.Dcp.dcpctrl.ServiceReconciler[0]
      could not start the proxy {"ServiceName": {"name":"apiservice-b-http"}, "Reconciliation": 10, "error": "could not start the proxy for the service: listen tcp [::1]:5488: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."}  `

**Comment by barbel840113** [comment]
The use case is to have background tasks running inside the API and perform specific tasks based on the configuration. For example Task A -> create record, Task B -> update record etc.. However, I do not want to create a new project or service for each background host, which involves deployment, configuration, etc. I hope this makes sense. 

Best Regards

Mike

**Comment by barbel840113** [comment]
@davidfowl I can confirm, that your solution is working fine. Thank you for your help. 

Best Regards
