### ISSUE TITLE
[WebToolsE2E] When running 'dotnet watch' on the AppHost project, changes made in a project under orchestration do not get hot reloaded by dotnet watch

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#620]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 from build main-34231.268
3. Install latest 8.0 SDK: build 8.0.100-rtm.23530.10
4. Install Aspire workload
5. Apply NuGet Feeds

**REPRO STEPS**
1. In the VS, create a new project > ASP.NET Core Web App (Razor Pages) > give a name 'WebAppRp1' > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Build solution 
3. Open command prompt > navigate to the WebAppRp1.AppHost folder
4. Run 'dotnet watch'
5. Back in VS, open WebAppRp1 > Index.cshtml 
6. Make an edit - eg: Change 'Welcome' to 'Welcome 123'

**ACTUAL**
'dotnet watch' does not hot reload the changes. It detects the file change and restarts 'dotnet watch'

**Workaround** - refresh the browser manually

**EXPECTED**
Running 'donet watch' on the WebAppRp1.Apphost should watch for changes in the projects being orchestrated?

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/sdk/issues/36971
