### ISSUE TITLE
[WebToolsE2E][Aspire] There are some errors "SocketClosed (ReadEndOfStream, last-recv: 0) on localhost:xxx/Subscription" when opening the webfrontend Weather page and stopping the cache container in the Aspire Dashboard

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#6200]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0.100-rc.2.24474.11
3. Install Aspire 9.0.0-rc.1.24506.1

    - Apply the dotnet8 feed for Aspire 9.0
4.  Install Docker Desktop

**REPRO STEPS**
1. Open CMD, create an Aspire Starter with Redis project using following commands:
```
dotnet new aspire-starter --use-redis-cache -o AspireApp
cd AspireApp/AspireApp.AppHost
```
2. Dotnet run the project in CMD, and open URL in the browser.
`dotnet run`
3. Click the endpoint of webfrontend project, open the Weather page.
4. Return to the Aspire Dashboard, stop the cache container

**ACTUAL**
There are some error messages in the webfrontend Structured
![dashboard4](https://github.com/user-attachments/assets/34368f78-b38a-4ac3-a1c2-4f2e3a6752ba)
![image (1)](https://github.com/user-attachments/assets/70330090-1f16-4ec1-9b42-e315f332c719)

**Error Log**
`SocketClosed (ReadEndOfStream, last-recv: 0) on localhost:58974/Subscription, Idle/MarkProcessed, last: SUBSCRIBE, origin: ReadFromPipe, outstanding: 0, last-read: 0s ago, last-write: 5s ago, keep-alive: 60s, state: ConnectedEstablished, mgr: 9 of 10 available, in: 0, in-pipe: 0, out-pipe: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, v: 2.8.16.12844`

**Comment by davidfowl** [comment]
This is by design. Stackexchange redis logs when the connection breaks and those logs show up in the dashboard.
