### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.Microsoft.EntityFrameworkCore.SqlServer, a warning appears: Package 'System.Runtime.Caching' 8.0.0 has a known high severity vulnerability

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#6226]
**REGRESSION INFO**: Repro on Aspire 8.2.0 and Aspire 8.2.1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.12 Preview 3 [35409.206.d17.12][Include SDK 9.0.100-rc.2.24474.11]
3. Install Aspire 9.0.0-rc.1.24509.13

**REPRO STEPS**

1. Create a new project > .NET Aspire 9 Starter App > named it 'AspireApp' > .Net 9.0 (Preview) > Create
2. Right click AspireApp.Web > Add > .NET Aspire package > Install Aspire.Microsoft.EntityFrameworkCore.SqlServer (Version 9.0.0-rc.1.24509.13)

**NOTE**: 
1. If TargetFramework selects net8.0, this issue will also be repro.
2. Create Razor Pages ~ individual project. This issue is not repro because the Microsoft.EntityFrameworkCore.SqlServer package references System.Runtime.Caching (6.0.0)
3. Package 'System.Runtime.Caching' Release Date:
![Image](https://github.com/user-attachments/assets/43838e4b-b203-4886-833e-f7f46f7cf73b)

**ACTUAL**
A warning appears: Package 'System.Runtime.Caching' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-qj66-m88j-hmgj
![Image](https://github.com/user-attachments/assets/29bcd492-02b3-45fd-a134-62d7f199eab7)

![Image](https://github.com/user-attachments/assets/f075f80e-4e8c-46bb-90ae-45e8e0c09a5a)

**EXPECTED**
No warning

**Comment by lommez** [comment]
I'm having the same problem.
Any solution for this?

**Comment by eerhardt** [comment]
> I'm having the same problem. Any solution for this?

For now, you can add an explicit `<PackageReference Include="System.Runtime.Caching" Version="8.0.1" />` which will remove the warning.

**Comment by eerhardt** [comment]
This package being marked as vulnerable was a mistake. See https://github.com/github/advisory-database/pull/4904/ which is correcting the advisory with the correct package name.

We just need to wait for nuget.org to be updated and this warning will go away.

**Comment by eerhardt** [comment]
https://www.nuget.org/packages/System.Runtime.Caching/8.0.0 is no longer marked vulnerable in nuget.org. This issue can now be closed.
