### ISSUE TITLE
AppHost Dashboard CORS Configuration

### ISSUE THREAD

**Issue by DGAISmith** [dotnet/aspire#6249]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There was a discussion here [Issue 4917](https://github.com/dotnet/aspire/issues/4917) about adding CORS configuration to the Dashboard when run Standalone and via the AppHost.  The work appears to have been actioned here [PR 5212](https://github.com/dotnet/aspire/pull/5212).  From my reading of this, it looks like when running Standalone the DASHBOARD__OTLP__CORS__ALLOWEDORIGINS env var (see [Docs](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/configuration?tabs=bash#otlp-cors)) can be used to set the origins to something suitable for the use case.  However when the AppHost starts the Dashboard, ALLOWEDORIGINS is automatically set based on the endpoints configured in the AppHost's resources.

If the above is true, this creates an unsurmountable problem when using a Resource in the AppHost which has a custom local domain name.  It is currently not possible to configure the AppHost to use a custom domain name when defining resources - they will get a localhost:[RandomPort] instead (this limitation has been discussed several times in the Issues list).  This will presumably be auto-added to the Dashboard CORS origins list when the AppHost starts up.  But if that Resource is a SPA with a custom domain (manually added to the local hosts file, and using a self-signed cert), telemetry sent to the Dashboard will be blocked by CORS.  This prevents the use of browser-sourced telemetry in these scenarios.

Tagging @JamesNK due to the nature of the work and his existing involvement, question was asked originally on the docs repo here - [Issue 1588](https://github.com/dotnet/docs-aspire/issues/1588#issuecomment-2405073806).

Many thanks.

### Describe the solution you'd like

Possible options - allow the use of custom domains in WithEndpoint() style builder methods (which would presumably then be passed on in the auto-CORS behaviour).  Or allow the use of DASHBOARD__OTLP__CORS__ALLOWEDORIGINS (or similar) to **add** to the auto-CORS origin list when running the Dashboard via AppHost.

**Comment by JamesNK** [comment]
Good news, I was just working on this. PR: https://github.com/dotnet/aspire/pull/6250

> Or allow the use of DASHBOARD__OTLP__CORS__ALLOWEDORIGINS (or similar) to add to the auto-CORS origin list when running the Dashboard via AppHost.

This is the solution I added.

**Comment by DGAISmith** [comment]
> Good news, I was just working on this. PR: [#6250](https://github.com/dotnet/aspire/pull/6250)
> 
> > Or allow the use of DASHBOARD__OTLP__CORS__ALLOWEDORIGINS (or similar) to add to the auto-CORS origin list when running the Dashboard via AppHost.
> 
> This is the solution I added.

Wow, can't argue with that kind of turnaround.  I'm glad my users don't expect me to be fixing things while they're logging their tickets....
