### ISSUE TITLE
[WebToolsE2E][Aspire] Run the aspire project, select a project resource on the console page, and restart this project resource successfully on the resource page, but some errors appear in the CMD dialog box

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#6265]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.12 Preview 3 FB
3. Install Aspire 9.0.0-rc.1.24511.1

**REPRO STEPS**

1. File > New project > .NET Aspire 9 Starter App > create
2. Build and run
3. On the daskboard, navigate to console page and select apiservice resource
4. Navigate to Resources page, click 'Restart' option behind the apiservice resource

**Note**: If only F5 to run and then click 'Restart', there is no error

**ACTUAL**
Restart succeeded, but some errors occurred in CMD dialogimage
![Image](https://github.com/user-attachments/assets/1fd9c70d-24d0-4d73-a81b-d238a97b1cd7)
![Image](https://github.com/user-attachments/assets/c28c12ec-3a0a-4523-822f-b27823de3db8)

fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
could not remove process's standard output file {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 24, "path": "C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
could not remove process's standard error file {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 24, "path": "C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
could not remove process's standard output file {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 25, "path": "C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_out_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
could not remove process's standard error file {"Executable": {"name":"apiservice-pwvnzjwk"}, "Reconciliation": 25, "path": "C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10", "error": "remove C:\Users\v-xxx\AppData\Local\Temp\aspire.grwrxwhu.0xn\apiservice-pwvnzjwk_err_152e1834-0940-46ad-b6ea-643e79995b10: The process cannot access the file because it is being used by another process."}

**EXPECTED**
Restart succeeded and no error occur

**Comment by v-bennettyue** [comment]
There is a similar bug here: https://github.com/dotnet/aspire/issues/5853, and it have been fixed.

**Comment by joperezr** [comment]
@dbreshears will follow up here to see if this can be reproduced. If the feature is completely broken then this might be an RC1 blocker.

**Comment by danegsta** [comment]
This looks to be a timing issue between stopping log streaming when deletion is requested for a resource and deleting the logs for said resource.
