### ISSUE TITLE
[WebToolsE2E][Aspire] When running a console app with Aspire 9.0 added, there is no info on the console page

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#6266]
**REGRESSION INFO**: Not repro on Aspire 8.2.1 and Aspire 8.2.0

**INSTALL STEPS**

Clean machine: Win11 x64 23h2 ENU
Install Dev17.12 Preview 3 FB
Install Aspire 9.0.0-rc.1.24511.1

**REPRO STEPS**

File > New project > console app > .NET 8.0 > create
Right-click console project > Add >  .NET Aspire orchestrator support ~ 9.0
Build and run

**Note:** 
1. After clicking restart on the dashboard, the logs info appears
2. The probability of this problem occurring: More than 80%

**ACTUAL**
The state of consoleapp is "Running" not "Finished" 
![Image](https://github.com/user-attachments/assets/a66a4599-eb22-47dd-ac1a-afc3450ab0ca)
Navigate to Console page and select consoleapp resource, there are no logs info
![Image](https://github.com/user-attachments/assets/fd602aaa-68bc-433c-9502-52a86e30ea6e)

**EXPECTED**
The state of consoleapp is "Finished" 
![Image](https://github.com/user-attachments/assets/e9d7a821-a55e-494f-ab2d-f1f9c20dea47)
Navigate to Console page and select consoleapp resource, there are some logs info
![Image](https://github.com/user-attachments/assets/8d4a2a80-ea40-4693-8de1-d44afa77f2a4)

**Comment by davidfowl** [comment]
@JamesNK you have the most context about the most recent logging changes. Can you look into this? Unclear which component has the issue (app model, dcp or the dashboard).

**Comment by JamesNK** [comment]
I can't reproduce in the latest source code. @v-bennettyue Can you preproduce in latest source?

**Comment by v-bennettyue** [comment]
@JamesNK I can still repro this issue on Dev17.12 P3 + Aspire 9.0.0-rc.1.24511.1, the probability of this issue occurring now: More than 50%. It is easier to reproduce if you are creating it for the first time.

However, when the log information appears, the state of consoleapp will randomly encounter the following two in the dashboard:
![Image](https://github.com/user-attachments/assets/b0b0f09b-cf35-4f9f-a82c-1691a6975412)
![Image](https://github.com/user-attachments/assets/19bedcf4-2e06-4b33-9f1d-136ab35aa582)
Which one is the expected result?

**Comment by JamesNK** [comment]
We can't fix this in RC1. RC1 is done. It's shipped. Testing in RC1 doesn't seem to have any value.

Does it occur in the latest source? If it does then I can fix it for the next version we ship.

**Comment by dbreshears** [comment]
Unable to reproduce this as well.  For the expected result question above,  based on the repro steps,  the state should be Finished and Action should be the start icon since the consoleapp will run to completion.  Please do see if that still reproduces in the latest build

**Comment by v-mengwe** [comment]
**More Info:**
The state of Console C# App project still shows "Finished" in the dashboard if setting a breakpoint in code `Console.WriteLine("Hello, World!");` of Program.cs file. But the state of Console C# App project randomly shows "Finished" or "Running" in the dashboard if there is no breakpoint.

**Comment by v-bennettyue** [comment]
This issue not repro on Dev17.12 P3 + Aspire GA (9.0.0-rc.2.24519.2), so close it.
