### ISSUE TITLE
Get .net local secrets in dapr

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/aspire#6273]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Secrets set locally using `dotnet user-secrets` in my apphost project cannot be exposed through dapr.

### Describe the solution you'd like

If I set up secrets locally in my aspire apphost project using `dotnet user-secrets`, I'd love to be able to fetch those secrets using dapr secret APIs.

**Comment by davidfowl** [comment]
This issue would be better suited on the dapr project itself.

**Comment by davidfowl** [comment]
I think the dapr .NET sdk maintainers might have ideas on how it could work. The aspire team sent experts on dapr and this feature needs to be designed to extend the dapr side car.

**Comment by joperezr** [comment]
[Triage] - Based on the discussion above, we are closing this as not planned. Please feel free to reopen if you have any follow up questions/comments.
