### ISSUE TITLE
Strange behavior of applications when launched through Aspire

### ISSUE THREAD

**Issue by IlyaNavodkin** [dotnet/aspire#6274]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi all. I want to launch multiple .net applications without using launchsetting.json. And it’s ideal to redefine the ports yourself using env files.

When I manually override ports for applications, I get strange behavior when launching applications:
1. apiservice - does not have swagger, it feels like it doesn’t work. 

![Image](https://github.com/user-attachments/assets/d9a337e4-b491-4f90-ae59-7c4a5ed80384)

2. webfrontend does not display the main styles of the application

![Image](https://github.com/user-attachments/assets/a85e09c9-3684-41a1-a54c-7445f2b0e96b)

Is it possible to launch applications without launchsetting json?

### Expected Behavior

I expect the apiservice to run a swagger, and for the webfrontend to have basic webfrontend styles. Ideally, in the future I want AspireApp2.AppHost to configure all applications based on the env file

### Steps To Reproduce

Repo => https://github.com/IlyaNavodkin/AspireApp2

### .NET Version info

.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.9e3391ed
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.10.34928.147
   Manifest Version:    8.0.21/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.21\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.10.34928.147
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.10.34928.147
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.10.34928.147
   Manifest Version:    34.0.95/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.95\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: VS 17.10.34928.147
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by davidfowl** [comment]
That repository is private

**Comment by IlyaNavodkin** [comment]
> That repository is private

Sorry, I opened the repository

**Comment by DamianEdwards** [comment]
If you don't have specify a launch profile for the project then it's likely you end up running them in the "Production" environment, as usually the required environment variable is set via the launch profile. This is likely the cause of the swagger endpoint not being available, as in the default templates it's only added in the "Development" environment, and the static assets feature is setup by default such that the assets won't be found when running the project in place if the environment isn't "Development" (this is due to the different way the `ContentRoot` and `WebRoot` paths are set, along with the static assets bundling system, to be optimized for running during the developer inner-loop vs. a published app).

Also, for non-proxied projects/executables, specifying both `port` and `targetPort` is redundant. Simply specify either `port` or `targetPort`.

If you update your app host code to the following it should work:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");

var apiService = builder.AddProject<Projects.AspireApp2_ApiService>("apiservice", launchProfileName: null)
    // This will pass through the environment name from the app host
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", builder.Environment.EnvironmentName)
    .WithHttpEndpoint(port: 11444, isProxied: false)
    .WithHttpsEndpoint(port: 11445, isProxied: false);

builder.AddProject<Projects.AspireApp2_Web>("webfrontend", launchProfileName: null)
    // This will pass through the environment name from the app host
    .WithEnvironment("ASPNETCORE_ENVIRONMENT", builder.Environment.EnvironmentName)
    .WithExternalHttpEndpoints()
    .WithHttpEndpoint(port: 11434, isProxied: false)
    .WithHttpsEndpoint(port: 11435, isProxied: false)
    .WithReference(cache)
    .WithReference(apiService);

builder.Build().Run();
```

**Comment by IlyaNavodkin** [comment]
It was stupid of me to launch the application without development mode. Thanks for pointing this out to me!
