### ISSUE TITLE
Wrong Credentials for AzurePostgresFlexibleServer

### ISSUE THREAD

**Issue by osyyyS** [dotnet/aspire#6284]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a simple API with that uses a Postgres Database with .PublishAsAzurePostgresFlexibleServer().
When I publish my App Host to **Azure,** it creates a Key Vault with a **connectionstring**. 
However, the username inside the connectionstring is wrong.
I can fix it by changing the connection string manually, but the next time I deploy the application. It gets changed back to the wrong one.
There might be an easy fix that I missed since I'm new to aspire, but I could find it.

This is my AppHost:
```csharp
var builder = DistributedApplication.CreateBuilder(args);

var postgres = builder.AddPostgres("postgresserver")
  .WithDataVolume()
  .PublishAsAzurePostgresFlexibleServer();
  
var db = postgres.AddDatabase("db");

var server = builder.AddProject<Server>("server")
  .WithReference(db)
  .WithExternalHttpEndpoints();

builder.Build().Run();
```

### Exceptions (if any)

Unhandled exception. Npgsql.PostgresException (0x80004005): 28P01: password authentication failed for user "***"

### .NET Version info

8.0.401

### Anything else?

aspire 8.2.0/8.0.100 VS 17.12.35323.107

**Comment by davidfowl** [comment]
What's the username and what is the expected username?

**Comment by mitchdenny** [comment]
@osyyyS based on your description I suspect that you have a local `config.json` file which contains the old username. Take a look in `.azure/<envname>/config.json` - this is probably the username that it keeps getting reset back to?

**Comment by mitchdenny** [comment]
Moving to backlog as I am now pretty confident this is not a blocking issue for 9.0.

**Comment by osyyyS** [comment]
@mitchdenny You were right, there was an old username in ``config.json``. Thanks for the help 😁
