### ISSUE TITLE
Installing Aspire workload in Ubuntu installs 8.0 preview instead of 8.2 workload

### ISSUE THREAD

**Issue by codekoenig** [dotnet/aspire#6287]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I tried to install Aspire 8.2 on a fresh Ubuntu install, but can't get it to install 8.2 ... after installing Aspire workload, it shows 8.0-preview manifest to be installed. It even mentions there's an update available, but after running ``dotnet workoad update`` it remains on 8.0-preview and again informs me about an available update.

Here's shell output of my attempt to install and update:

```shell
bernhard@bernhard-Surface-Book-3:~/source/repos/Growatch/Growatch.AppHost$ dotnet workload install aspire

Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.10...
Installing workload manifest microsoft.net.workload.emscripten.current version 8.0.10...
Installing workload manifest microsoft.net.workload.emscripten.net6 version 8.0.10...
Installing workload manifest microsoft.net.workload.emscripten.net7 version 8.0.10...
Installing workload manifest microsoft.net.workload.mono.toolchain.net6 version 8.0.10...
Installing workload manifest microsoft.net.workload.mono.toolchain.net7 version 8.0.10...
Installing workload manifest microsoft.net.sdk.aspire version 8.2.1...
Installing workload manifest microsoft.net.sdk.android version 34.0.143...
Installing workload manifest microsoft.net.sdk.ios version 18.0.8303...
Installing workload manifest microsoft.net.sdk.maccatalyst version 18.0.8303...
Installing workload manifest microsoft.net.sdk.macos version 15.0.8303...
Installing workload manifest microsoft.net.sdk.maui version 8.0.82...
Installing workload manifest microsoft.net.sdk.tvos version 18.0.8303...
Installing pack Aspire.Hosting.Sdk version 8.0.0-preview.1.23557.2...
Writing workload pack installation record for Aspire.Hosting.Sdk version 8.0.0-preview.1.23557.2...
Installing pack Aspire.ProjectTemplates version 8.0.0-preview.1.23557.2...
Writing workload pack installation record for Aspire.ProjectTemplates version 8.0.0-preview.1.23557.2...
Installing pack Aspire.Hosting.Orchestration.linux-x64 version 8.0.0-preview.1.23557.2...
Writing workload pack installation record for Aspire.Hosting.Orchestration version 8.0.0-preview.1.23557.2...
Installing pack Aspire.Hosting version 8.0.0-preview.1.23557.2...
Writing workload pack installation record for Aspire.Hosting version 8.0.0-preview.1.23557.2...
Garbage collecting for SDK feature band(s) 8.0.100...
Uninstalling workload manifest microsoft.net.workload.emscripten.net7 version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.macos version 15.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.tvos version 18.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.android version 34.0.143/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.maccatalyst version 18.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.workload.mono.toolchain.net7 version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.ios version 18.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.workload.emscripten.current version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.workload.mono.toolchain.net6 version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.maui version 8.0.82/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.aspire version 8.2.1/8.0.100...
Uninstalling workload manifest microsoft.net.workload.emscripten.net6 version 8.0.10/8.0.100...

Successfully installed workload(s) aspire.

bernhard@bernhard-Surface-Book-3:~/source/repos/Growatch/Growatch.AppHost$ dotnet workload list

Installed Workload Id      Manifest Version                     Installation Source
-----------------------------------------------------------------------------------
aspire                     8.0.0-preview.1.23557.2/8.0.100      SDK 8.0.100        

Use `dotnet workload search` to find additional workloads to install.

Updates are available for the following workload(s): aspire. Run `dotnet workload update` to get the latest.

bernhard@bernhard-Surface-Book-3:~/source/repos/Growatch/Growatch.AppHost$ dotnet workload update

Skipping NuGet package signature verification.
Updated advertising manifest microsoft.net.sdk.aspire.
Updated advertising manifest microsoft.net.workload.emscripten.net7.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.emscripten.net6.
Updated advertising manifest microsoft.net.workload.emscripten.current.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net6.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.workload.mono.toolchain.current.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net7.
Installing workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.10...
Installing workload manifest microsoft.net.workload.emscripten.current version 8.0.10...
Installing workload manifest microsoft.net.workload.emscripten.net6 version 8.0.10...
Installing workload manifest microsoft.net.workload.emscripten.net7 version 8.0.10...
Installing workload manifest microsoft.net.workload.mono.toolchain.net6 version 8.0.10...
Installing workload manifest microsoft.net.workload.mono.toolchain.net7 version 8.0.10...
Installing workload manifest microsoft.net.sdk.aspire version 8.2.1...
Installing workload manifest microsoft.net.sdk.android version 34.0.143...
Installing workload manifest microsoft.net.sdk.ios version 18.0.8303...
Installing workload manifest microsoft.net.sdk.maccatalyst version 18.0.8303...
Installing workload manifest microsoft.net.sdk.macos version 15.0.8303...
Installing workload manifest microsoft.net.sdk.maui version 8.0.82...
Installing workload manifest microsoft.net.sdk.tvos version 18.0.8303...
Installing pack Aspire.Hosting.Sdk version 8.0.0-preview.1.23557.2...
Pack Aspire.Hosting.Sdk version 8.0.0-preview.1.23557.2 is already installed.
Writing workload pack installation record for Aspire.Hosting.Sdk version 8.0.0-preview.1.23557.2...
Installing pack Aspire.ProjectTemplates version 8.0.0-preview.1.23557.2...
Pack Aspire.ProjectTemplates version 8.0.0-preview.1.23557.2 is already installed.
Writing workload pack installation record for Aspire.ProjectTemplates version 8.0.0-preview.1.23557.2...
Installing pack Aspire.Hosting.Orchestration.linux-x64 version 8.0.0-preview.1.23557.2...
Pack Aspire.Hosting.Orchestration.linux-x64 version 8.0.0-preview.1.23557.2 is already installed.
Writing workload pack installation record for Aspire.Hosting.Orchestration version 8.0.0-preview.1.23557.2...
Installing pack Aspire.Hosting version 8.0.0-preview.1.23557.2...
Pack Aspire.Hosting version 8.0.0-preview.1.23557.2 is already installed.
Writing workload pack installation record for Aspire.Hosting version 8.0.0-preview.1.23557.2...
Garbage collecting for SDK feature band(s) 8.0.100...
Uninstalling workload manifest microsoft.net.workload.emscripten.net7 version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.macos version 15.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.tvos version 18.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.android version 34.0.143/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.maccatalyst version 18.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.workload.mono.toolchain.net7 version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.ios version 18.0.8303/8.0.100...
Uninstalling workload manifest microsoft.net.workload.emscripten.current version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.workload.mono.toolchain.net6 version 8.0.10/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.maui version 8.0.82/8.0.100...
Uninstalling workload manifest microsoft.net.sdk.aspire version 8.2.1/8.0.100...
Uninstalling workload manifest microsoft.net.workload.emscripten.net6 version 8.0.10/8.0.100...

Successfully updated workload(s): aspire.

bernhard@bernhard-Surface-Book-3:~/source/repos/Growatch/Growatch.AppHost$ dotnet workload list

Installed Workload Id      Manifest Version                     Installation Source
-----------------------------------------------------------------------------------
aspire                     8.0.0-preview.1.23557.2/8.0.100      SDK 8.0.100        

Use `dotnet workload search` to find additional workloads to install.

Updates are available for the following workload(s): aspire. Run `dotnet workload update` to get the latest.

```

### Expected Behavior

Aspire 8.2 installed, but it remains on 8.0-preview

OR

Any mention in the documentation that 8.2 is not available/supported on Linux yet

### Steps To Reproduce

On a fresh Ubuntu 24.04 installation:

* Install .NET SDK 8.0 from Microsoft (or Ubuntu) apt sources
* Install Aspire workload by execuintg ``dotnet workload install aspire``
* Execute ``dotnet workload list``
* Note that 8.0-preview is installed and an update notification text appears that there's an update available for Aspire
* Run ``dotnet workload update``
* Run  ``dotnet workload list``
* Note that version is still 8.0-preview and the update available notification appears again

### .NET Version info

.NET SDK:
 Version:           8.0.110
 Commit:            87a66bb3d1
 Workload version:  8.0.401-baseline.24412.2

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  24.04
 OS Platform: Linux
 RID:         ubuntu.24.04-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.110/

.NET workloads installed:
 Workload version: 8.0.401-baseline.24412.2
 [aspire]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.0-preview.1.23557.2/8.0.100
   Manifest Path:       /home/bernhard/.dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.0.0-preview.1.23557.2/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.110 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

**Comment by codekoenig** [comment]
After continued research, I'm thinking this has to do with the feature bands of the SDK. On Windows, he have .401 SDK, but on Linux it's .110 - both are to current ones in their band as I understand. The feature bands documentation although mentions that there should be compatibility and issues are not expected. But to me this is quite confusing.

**Comment by codekoenig** [comment]
Ok so after some more research and reading more documentation and blog posts on the whole topic of feature bands, the whole situation about Ubuntu & Microsoft feeds and what changed in Ubuntu 24.04 and so forth ... 

... I understand that:

* This is not a bug, and not directly related to Aspire
* It's more about an unfortunate situation about how dotnet apt packages are handled by distros like Ubuntu and Microsoft before and this leads to a whole lot confusion, and feature bands contributing to that
* What I did wrong:
  * I should not have installed dotnet in Ubuntu 24.04 from Microsoft sources but directly from Ubuntu
  * I need to have .401 SDK feature band installed also on Linux, the comments i found about theoretical parity between the latest feature bands do not seem to be what I understood
  * Even if I had installed from Ubuntu sources, I would still have got .110 feature band max and this would still not work with Aspire 8.2
  * So .401 SDK needs to be installed on Ubuntu from manual install scripts as distros won't upgrade to newer feature bands within a major .NET SDK release

I still would leave this open for now as I think Aspire's documentation or workload installation could be quite a bit optimized here to make this less painful for someone going into this underestimating the complexity that is dotnet on Ubuntu like me:

* The direct dependency between specific SDK versions and specific Aspire workload versions is not at least obviously documented, for example here would be a good point to mention this: https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/setup-tooling?tabs=linux&pivots=dotnet-cli ... on Windows it's less a problem as you just download the SDK from the link and you get the latest and greatest. But for Linux it's bit of a trap as you won't get the latest feature band from the package managers
* There could also be a info/warning for Linux that you won't get the latest SDKs needed for Aspire 8.2 without using manual install scripts
* The workload install CLI output is misleading, as it mentions it installs a 8.2 mainfest and later even mentions hey, there's an update available, but executing the recommended update command does nothing despite the success message ``Successfully updated workload(s): aspire.`` - would be great if this would fail with some kind of error saying hey, with that old SDK Aspire 8.2 no bueno.

**Comment by joperezr** [comment]
Hey @codekoenig, so sorry for not replying earlier. Thank you so much for all of the details that you have provided as well as all of the research that you have done. While you are correct that SDK bands in Ubuntu are a bit different (especially when installed from a package manager) I would still believe that you should be able to install the Aspire workload manually if needed. Doing `dotnet workload update` and then `dotnet workload install aspire` should be getting you 8.2.2 version of Aspire, as opposed to 8.0 preview 1 which is very old. Can you please confirm that this work for you? Also, you should be able to try Aspire 9 RC1 which no longer requires a workload to be installed, and that will ship GA next week when Aspire 9 ships, so this should no longer be an issue then.
