### ISSUE TITLE
[WebToolsE2E] Publish Azure Function app under Aspire orchestration, the publish succeeds but the ACA fails to load successfully

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#6297]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
1. Install VS 17.12 Preview 3, latest build
    - includes .NET SDK 9.0 rc2
    - includes Aspire 8.2.0 workload
1. Install Aspire.ProjectTemplates - latest version **9.0.0-rc.1.24511.1**
    - Add dotnet8 feed
    - `dotnet new install Aspire.ProjectTemplates::9.0.0-rc.1.24511.1 --force`
    - Templates get installed fine
1. Install azd (latest daily build), 
    - Installed version 1.11.0-beta.1-daily.4210036

**REPRO STEPS**
1. New Project > Azure Functions app > .NET 8.0 Isolated > Http Trigger > Anonymous authentication > FunctionApp_net80_15
    - Also choose to 'Enlist in Aspire'

1. Run the app locally (Ctrl+F5 using VS) - works fine
1. Open command-line, run `azd init` and `azd up` - publish completes successfully
1. Click on the ACA endpoint in the publish output to open it

**ACTUAL**
ACA page shows that the container app is stopped or does not exist.

![Image](https://github.com/user-attachments/assets/e4c98324-d9e1-40fe-a4ff-856998b13d45)

Container app shows activation failed in the Azure portal

![Image](https://github.com/user-attachments/assets/e2f45864-7e65-4f0a-80e0-aca2a2d48a61)

**EXPECTED**
ACA to be available and running after publish

**Comment by captainsafia** [comment]
@balachir I believe that you may be running into this issue because the Functions templates are not yet updated to use the latest versions of their packages which provide container support. I've added a note about this in the instructions but here it is for posterities sake.

> Before moving forward with this scenario, verify that the project file for your Functions project is using at least version 2.0.0-preview2 of the Microsoft.Azure.Functions.Worker.Sdk and 2.0.0-preview1 version of the Microsoft.Azure.Functions.Workerpackage.

Can you confirm the versions referenced in the project you deployed and see if updating to the above resolves the issue?

**Comment by KennethHoff** [comment]
I tried out the azd integration for the first time today, and with lastest Aspire 8.* as well as the latest preview here (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json) I experience the same `Error 404 - This Container App is stopped or does not exist.` error.

This is with something as simple as:

```c#
// AppHost Program.cs
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject<Projects.WebApi>("web-api");

builder.Build().Run();

// WebApi Program.cs
var builder = WebApplication.CreateSlimBuilder(args);

var app = builder.Build();

app.MapGet("/", () => TypedResults.Ok("Hallo"));

app.Run();
```

**Comment by captainsafia** [comment]
@KennethHoff It looks like you're running into an issue with a Minimal API project. I'd recommend filing a new issue for that. This bug relates to deployment for Azure Functions.

**Comment by KennethHoff** [comment]
(I figured out my problem btw; It was because I seemingly needed `.WithExternalHttpEndpoints()` on my `web-api` resource. I couldn't find that in any of the quick start documentations for azd w/ Aspire however..)

**Comment by captainsafia** [comment]
@balachir Does this issue still repro with the latest versions of Visual Studio and Aspire? The Functions templates should be updated to use the correct versions in Visual Studio now.

**Comment by joperezr** [comment]
Hey @balachir, have you had a chance to test this one again? It would be good to validate that this is fixed.

**Comment by v-elenafeng** [comment]
This doesn’t look like a real issue or specific to functions app, we need to add the code `.WithExternalHttpEndpoints()` to expose the app. And by default only the frontend web app in the aspire-starter template is exposed.

**Comment by captainsafia** [comment]
@v-elenafeng The `WithExternalHttpEndpoints` is definitely part of the problem. However, based on the fact that the container itself appears to be in a bad state there is probably an issue with deployment in the bits used as well.

![Image](https://github.com/user-attachments/assets/22c97aeb-fef7-472c-a45e-d1caa0b4a6e5)

**Comment by balachir** [comment]
@captainsafia @v-elenafeng I tried this again today and I'm able to get this to work now for Functions (.NET 8 Isolated) template. Two changes are needed to get the deployment to ACA to work successfully.
- Add `WithExternalHttpEndpoints`
    - ![Image](https://github.com/user-attachments/assets/992d9355-ccf1-4583-857c-3e65255293e0)
- Update the Functions.Worker packages in Functions app to latest 2.0.0 versions.
    - ![Image](https://github.com/user-attachments/assets/c7c8d858-3075-469b-9d44-af2f714415e5)

After I do this, I can get the Functions app and dashboard showing in Azure.

![Image](https://github.com/user-attachments/assets/f5b415be-0a88-42c2-b854-8552fa2fcc2c)

![Image](https://github.com/user-attachments/assets/cdf517ea-9bc7-49aa-bb7e-5574929f1422)

I'll go ahead and close this issue. We can open a new one if there are additional problems.
