### ISSUE TITLE
Add WithDataVolume to Redis Insights

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#6299]
## Background and Motivation

When using Redis Insights, every time you F5 and launch the container you get prompted with a privacy and license acceptance prompt the first time you hit the Redis Insights page.

To solve this, we should add a method that configures a data volume on the container. That way you only need to accept the license and privacy statement the first time.

## Proposed API

```diff
namespace Aspire.Hosting;

public static class RedisBuilderExtensions
{
+    public static IResourceBuilder<RedisInsightResource> WithDataVolume(this IResourceBuilder<RedisInsightResource>, string? name = null);
}
```

## Usage Examples

```csharp
var redis = builder.AddRedis("redis")
    .WithDataVolume()
    .WithRedisInsight(i => i.WithDataVolume());
```

**Comment by Alirexaa** [comment]
I will work on this.

**Comment by eerhardt** [comment]
> I will work on this.

Thanks @Alirexaa. If we are able to merge it before Friday it can make the 9.0.0 release. If not, it can catch the next release. Not a huge problem.

**Comment by eerhardt** [comment]
But it may be better if we fix [WithRedisInsight and ContainerLifetime.Persistent causes multiple instances to show up (dotnet/aspire#6111)](https://github.com/dotnet/aspire/issues/6111) either before or at the same time.

**Comment by Alirexaa** [comment]
> Thanks [@Alirexaa](https://github.com/Alirexaa). If we are able to merge it before Friday it can make the 9.0.0 release. If not, it can catch the next release. Not a huge problem.

I'm not sure PR is prepared for tomorrow.

**Comment by eerhardt** [comment]
> I'm not sure PR is prepared for tomorrow.

that's totally fine. Not a problem. It can get in when it gets in.
