### ISSUE TITLE
Support Azure Functions in Azure Container Apps

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/aspire#6324]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

No clarity on how I would develop and register an Azure Function running on Azure Container Apps within an Aspire apphost.

### Describe the solution you'd like

It would be nice to be able to develop Azure Functions that run in Azure Container Apps from within Aspire.

Just as important would be to have support for dapr throughout all this, including triggers.  See dapr examples in the 2nd link below.

### Additional context

- I think this might be related:  https://github.com/dotnet/aspire/issues/920
- https://techcommunity.microsoft.com/t5/apps-on-azure-blog/general-availability-of-azure-functions-on-azure-container-apps/ba-p/4145577
- https://learn.microsoft.com/en-us/azure/azure-functions/functions-deploy-container-apps

**Comment by davidfowl** [comment]
This is part of the work to support azure functions. I'm going to close this as https://github.com/dotnet/aspire/issues/920 is the tracking issue. There will be documentation when the feature is fully supported. You can read https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/dotnet-aspire-9-release-candidate-1?tabs=unix&pivots=visual-studio#azure-functions-support-preview to see the current support. We'll have more official docs and When Aspire 9.0 ships.
