### ISSUE TITLE
`HostUrl` no longer accepts non Uri values

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#6330]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In 8.x, I had some code setting an connection string to an environment variable wrapped in HostUrl.  This code was intended to take a connection string that had `127.0.0.1` in it, and convert it to `host.docker.internal` when used within a container.

After upgrading to 9.0-rc1, the container resource now fails to start, and fails with a cryptic error `Failed to apply configuration value 'foo'. A dependency may have failed to start.`

It looks like 9.x now assumes that HostUrl is a Uri, so I'm guessing this is what's failing
https://github.com/dotnet/aspire/blob/7d23b1d37f2962e1448eaa6c5888aff59587e64b/src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs#L98

### Expected Behavior

Either for `HostUrl` to work as it did in 8.x, or for a more actionable error.

The error seems to be logged at https://github.com/dotnet/aspire/blob/7d23b1d37f2962e1448eaa6c5888aff59587e64b/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs#L1363, however the inner exception is not logged to the resource logger so can't be seen.  Given that the resource has failed to start, and there will be nothing further, I think it's better to include the inner exception  in the LogCritical call so you've got something to investigate the root cause with.

![Image](https://github.com/user-attachments/assets/9f48f578-5044-468a-b2c5-3cfc82953a17)

If HostUrl is kept as it is, I'd also expect the `Url` constructor parameter to have `StringSyntaxAttribute.Uri`
https://github.com/dotnet/aspire/blob/4f7dbd485c260e25f92f4cacdef724bddb93967a/src/Aspire.Hosting/ApplicationModel/HostUrl.cs#L10

### Steps To Reproduce

```cs
builder.AddContainer("test", "redis", "latest")
    .WithEnvironment(x =>
    {
        x.EnvironmentVariables["foo"] = new HostUrl("Server=127.0.0.1,1433;User ID=sa;Password=REDACTEd;TrustServerCertificate=true;Database=REDACTED");
    });
```

### Exceptions (if any)

Console Logs
> 2024-10-16T09:07:39 Failed to apply configuration value 'foo'. A dependency may have failed to start.

### .NET Version info

<Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0-rc.1.24511.1" />

```
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.47119bbc
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.403\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400, VS 17.11.35222.181
   Manifest Version:    8.2.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.1\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  6.0.427 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\src\AC.Aspire\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by davidfowl** [comment]
cc @davidebbo

**Comment by davidfowl** [comment]
HostUrl was meant to be a URL 😄.

**Comment by afscrome** [comment]
> HostUrl was meant to be a URL 😄.

That is reasonable - my main pain here was the lack of information telling me what the problem was - the only way to solve was a combination of trial & error and reading the Aspire source code.  I was happy doing that, but many wouldn't be.  (Although equally, `HostUrl` is pretty buried and undocumented so it's unlikely to be used by those not happy with diving into the Aspire source code 😅)

I'm perfectly happy if the solution is to keep the 9.0 behavior of `HostUrl` only working for URLs but improve the errors in such a way that make it clear that's what the problem is.  If that's the case, I can PR some error improvements.

**Comment by davidebbo** [comment]
Darn, yeah, that's unexpected. I wish `HostUrl` has been kept internal! 😓 

@davidfowl if we want to preserve the behavior, I think we need to go back to string replacement for HostUrl, which is ugly.

What's your take: take the breaking change (maybe with improved error), or preserve compat?

**Comment by davidebbo** [comment]
As far as improving errors, it comes down to this code is `ApplicationExecutor`:

```c#
            catch (Exception ex)
            {
                resourceLogger.LogCritical("Failed to apply configuration value '{ConfigKey}'. A dependency may have failed to start.", kvp.Key);
                _logger.LogDebug(ex, "Failed to apply configuration value '{ConfigKey}'. A dependency may have failed to start.", kvp.Key);
                failedToApplyConfiguration = true;
            }
```

The resource logger has a general message, but doesn't include anything from the inner exception, which would have given clues.

Alternatively, if you set `"Aspire.Hosting.Dcp": "Debug"` in the appsetings log level, you'd see the exception in the host's console window, but it's not a great experience. Hard to know to do this, and hard to find it in the flow of debug output.
