### ISSUE TITLE
Key Vault Health Check Creates Warnings

### ISSUE THREAD

**Issue by michaelmcneilnet** [dotnet/aspire#6331]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The Key Vault health check calls `GET https://myvault.vault.azure.net/secrets/AzureKeyVaultSecretsHealthCheck/?api-version=7.5`, which doesn't exist. I understand the need to ping the vault to check the connection is there. However, this results in a warning being logged by Azure.Core for the 404, which adds a lot of noise to my logs.

### Expected Behavior

Either no warning is logged, or a way to filter out the specific warning resulting from the health check  is documented. I don't want to filter out all Azure.Core warnings.

### Steps To Reproduce

Add the aspire key vault integration to app, with health checks enabled.

### Exceptions (if any)

```
info: Azure.Core[1]
      Request [49d21e0f-bdb6-40f3-8637-1b302c3200d9] GET https://mykeyvault.vault.azure.net/secrets/AzureKeyVaultSecretsHealthCheck/?api-version=7.5
      Content-Type:application/json
      Accept:application/json
      x-ms-client-request-id:49d21e0f-bdb6-40f3-8637-1b302c3200d9
      x-ms-return-client-request-id:true
      User-Agent:azsdk-net-Security.KeyVault.Secrets/4.6.0 (.NET 8.0.10; Ubuntu 24.04.1 LTS)
      Authorization:REDACTED
      client assembly: Azure.Security.KeyVault.Secrets
warn: Azure.Core[8]
      Error response [49d21e0f-bdb6-40f3-8637-1b302c3200d9] 404 Not Found (00.0s)
      Cache-Control:no-cache
      Pragma:no-cache
      x-ms-keyvault-region:uksouth
      x-ms-client-request-id:49d21e0f-bdb6-40f3-8637-1b302c3200d9
      x-ms-request-id:ff136367-01e7-4298-aabf-76b2ad78fbd5
      x-ms-keyvault-service-version:1.9.1753.1
      x-ms-keyvault-network-info:conn_type=Subnet;addr=100.100.196.109;act_addr_fam=InterNetworkV6;
      x-ms-keyvault-rbac-assignment-id:REDACTED
      X-Content-Type-Options:REDACTED
      Strict-Transport-Security:REDACTED
      Date:Wed, 16 Oct 2024 09:02:43 GMT
      Content-Length:328
      Content-Type:application/json; charset=utf-8
      Expires:-1
```

### Anything else?

<PackageVersion Include="Aspire.Azure.Security.KeyVault" Version="9.0.0-rc.1.24511.1" />

**Comment by michaelmcneilnet** [comment]
In addition, if key vault charges per operation, does this health check increase our costs?

**Comment by davidfowl** [comment]
Take a look at the docs here https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/master/src/HealthChecks.Azure.KeyVault.Secrets to see if you can control what secret it uses for the health check.
