### ISSUE TITLE
[WebToolsE2E][Aspire] After stopping the project in Resources the icon for finished is different from expected result in Aspire 9.0 GA

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6335]
**REGRESSION**
1. Worked in Aspire 9.0 RC1

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.12 (Release channel)
3. Install Aspire 9.0 GA
`dotnet new install Aspire.ProjectTemplates::9.0.0-preview.5.24515.5 --force`

**REPRO STEPS**
1. Create Aspire Starter App
2. Build solution and run the project
3. Under "Actions" stop the project in Resources

**ACTUAL**
The icon beside Finished is different from the expected result
![Image](https://github.com/user-attachments/assets/86e4a4f3-91e9-4e6a-a5ff-1d538fd2a5b4)

**EXPECTED**
The icon should be a check icon
![Image](https://github.com/user-attachments/assets/4faa39b1-a751-4176-a824-65904367fd44)

**Comment by v-elenafeng** [comment]
This is an intentional change. See: https://github.com/dotnet/aspire/pull/6231.

**Comment by davidfowl** [comment]
Yep!

cc @drewnoakes
