### ISSUE TITLE
Aspire Testing: the ability to collect Aspire AppHost logs

### ISSUE THREAD

**Issue by alexavrutin** [dotnet/aspire#6336]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying out writing integration tests with Aspire for an application involving a number of microservices and a SQL Server resource. So far the impression is very positive. However, when I attempted to run the tests on Azure DevOps, they failed due to timeout during the initialisation of SQL Server. I'm trying to debug the issue but I can't get the logs from Aspire apphost. The logs are posted to console when I run Aspire as an application. But when it's the a test project that initializes the Aspire apphost, the logs are not appended to the test host's own logs and aren't displayed when running dotnet test. 

### Describe the solution you'd like

It would be good to have an ability to automatically collect Aspire apphost logs (and optionally resources' own logs) and dispatch them to the test host so that they would be displayed by dotnet test. 

### Additional context

I'm using Aspire 8.2.1 on .Net 8.0.403 on Ubuntu 22.04.5 LTS.

**Comment by davidfowl** [comment]
What test framework are you using?

**Comment by alexavrutin** [comment]
I use NUnit 4.2.2

**Comment by davidfowl** [comment]
I don't know if it's possible to circumvent the test framework. Associating output with a test AFAIK is test framework specific.

**Comment by alexavrutin** [comment]
Ok, got it. I'll close the issue then.
