### ISSUE TITLE
DCP logs many Info level messages per second when app host is started but container runtime isn't available

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#6341]
Our templates configure logging in the app host project such that only warning level or above messages from `Aspire.Hosting.Dcp` come through, but I was updating a sample and it didn't have that logging configuration. When I start it without the container runtime running, I get many logs per second from DCP until I manually start the container runtime (see below). This seems unideal 😄 

https://github.com/user-attachments/assets/88c69026-e512-4873-bfb9-57da3f018f7a

FYI @dbreshears @danegsta @karolz-ms @mitchdenny

**Comment by davidfowl** [comment]
cc @dbreshears @danegsta
