### ISSUE TITLE
Dashboard resource grid state issues

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#6351]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Two issues:

* RuntimeUnhealthy shouldn't display a green tick
* The state column isn't display a tooltip for most items. It is added one for "Finished" (see screenshot below) but there is no tooltip for "Runtime unhealthy" which would be useful because it's cut off. If the is no custom tooltip for a state (I think there is for "Finished") then fallback to a tooltip with the humanized state value.

![Image](https://github.com/user-attachments/assets/5961bc4c-1983-437a-9fef-ad2207645805)

**Comment by adamint** [comment]
fixed in linked pr
