### ISSUE TITLE
Access to the individual startup sequence of each referenced .net app

### ISSUE THREAD

**Issue by ErikBIMobject** [dotnet/aspire#6369]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have several services (asp net core) in different repos and Im running them together in aspire by linking the .csproj files into the aspire repo. 
Something I have found tricky is that I need to make some adjustments to the code to handle the aspire components and I dont really like that in my prod code. One of these is to apply the service defaults: we can do it in the aspire solution, but it wont work when you run the code back in the "original" repo. 

If I compare it to my "normal" api endpoint tests I would make a new class that inherits from WebApplicationFactory<T> and replace some things in my servicecollection in startup. To avoid having this "test" code on production. 

### Describe the solution you'd like

I would like to get access to the WebHostBuilder or ServiceCollection during the start up phase of the .net apps in the context of the apphost. 
Like this: 
```
var artifactApi = builder.AddProject<Projects.ArtifactApi>("artifactapi")
    .WithResourceServices(services=>
{
//replace something 
})

```

**Comment by davidfowl** [comment]
That’s no feasible in the app host

**Comment by joperezr** [comment]
I'm closing the issue given the above. @ErikBIMobject Feel free to reopen if you have any follow up questions.
