### ISSUE TITLE
[WebToolsE2E][Aspire] The endpoint link for the API project in the dashboard is incorrect and lacks the suffix '/weatherforecast'.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#6370]
**REGRESSION INFO**: Worked in Aspire 9.0 RC1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0 RC2
3. Install Aspire 9.0 GA [9.0.0-rc.2.24517.3]

**REPRO STEPS**
1.Open CMD, create an Aspire App using following commands:
```
dotnet new aspire-starter -o aspire
cd aspire/aspire.AppHost
```
2. Dotnet run the project in CMD, and open URL with token:
   `dotnet run`

**ACTUAL**:
The endpoint link of the API project is incorrect.
![Image](https://github.com/user-attachments/assets/5ae2be1c-2cdd-4046-8d9d-5d4dd4c688b1)
![Image](https://github.com/user-attachments/assets/bf058b28-e76e-4ac8-9d9b-82fbfc0b00ae)

**EXPECTED**
The link should be https://localhost:xxxx/weatherforecast
![Image](https://github.com/user-attachments/assets/339a1634-a5a3-4182-b048-cd40499dbce5)
![Image](https://github.com/user-attachments/assets/6916c675-6c23-4f0a-a3dd-ee7d43d32dd9)

**Comment by jinzhao1127** [comment]
For the Web API project , need to configure the launch URL to point to the `/weatherforecast ` endpoint by customers,  accordineg to https://github.com/dotnet/aspnetcore/pull/57682. So you can try to add `launchUrl": "weatherforecast",` in launchSetting.json file for your project.

**Comment by radical** [comment]
@DamianEdwards Is this related to the template changes?

**Comment by v-reinawang** [comment]
Close it as by design.
