### ISSUE TITLE
[WebToolsE2E][Aspire] For the case of aspire-starter net9.0 + Aspire 8.2, it silently uses Aspire 9.0. It should give a warning or error instead.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#6396]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0 GA coherent
3. Install Aspire 9.0 GA [9.0.0-rc.2.24519.2]
    - add dotnet8 feed
    - dotnet new install Aspire.ProjectTemplates::9.0.0-rc.2.24519.2 --force

**REPRO STEPS**

1.Open CMD and try an invalid scenario, such as:
```
dotnet new aspire-starter -o aspire01 -f net9.0 --aspire-version 8.2

```
**ACTUAL**
For the net9.0 + Aspire 8.2 case, it silently uses Aspire 9.0
![Image](https://github.com/user-attachments/assets/3cd94c23-834e-4832-a806-af12221b70ee)

**EXPECTED**
For the net9.0 + Aspire 8.2 case, it should give a warning or error instead.

**Comment by DamianEdwards** [comment]
I'm don't think the template engine supports showing errors for invalid combinations like is being suggested here does it @phenning? When we discussed this scenario we talked about how the auth options for the existing ASP.NET Core templates have similar behavior where some options are simply ignored if other option values specified don't support them.

**Comment by phenning** [comment]
@baronfel I believe that is correct. The only indication here is when you type dotnet new aspire-starter -h is that there is an indication that it only applies when framework == net8.0

**Comment by joperezr** [comment]
This is a gap in the templating engine, and there is nothing for us to do here, so I'll go ahead and close this for now.
