### ISSUE TITLE
[WebToolsE2E][Aspire][Tracking] After the final build of Aspire 9.0 is completed, the branding should be 9.0.0.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#6398]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.12 GA
3. Install Aspire 9.0 GA [9.0.0-rc.2.24519.2]
    - add dotnet8 feed
    - dotnet new install Aspire.ProjectTemplates::9.0.0-rc.2.24519.2 --force

**REPRO STEPS**

1. New > Create a .NET Aspire Starter App > .NET 9.0 (Preview) > Create

   - AspNetCore.OpenApi
   ![Image](https://github.com/user-attachments/assets/4d62c0a5-cc44-487d-92eb-cabafb428c19)

   - Http.Resilience
   ServiceDiscovery
![Image](https://github.com/user-attachments/assets/f68f1e48-5418-4052-968b-bf78ff187371)

   - Aspire.Hosting.Testing
   ![Image](https://github.com/user-attachments/assets/652bad9a-f1d0-4b0e-b0ba-36993b56d0c8)

**ACTUAL**
The Aspire 9.0 brand is 9.0.0-rc.2.xxx

**EXPECTED**
The Aspire 9.0 brand should be 9.0.0

**Comment by balachir** [comment]
@joperezr most packages have the correct 9.0.0 branding now. So, I suggest we can close this issue. Please go ahead and close it if you agree.

**Note**: There's a different branding related issue where some packages have 9.0.0-rtm branding. We've opened a separate issue to track that one - https://github.com/dotnet/aspire/issues/6428.

**Comment by joperezr** [comment]
Closing now as the branding issues have been resolved. Feel free to reopen if something is found.
