### ISSUE TITLE
Container state briefly becomes "Runtime unhealthy" during restart

### ISSUE THREAD

**Issue by karolz-ms** [dotnet/aspire#6421]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When restarting a container, sometimes its state becomes "Runtime unhealthy" for a few seconds even though the container runtime (Docker or Podman) does not seem to be in any bad state. 

### Expected Behavior

We should not routinely see "runtime unhealthy" state during container restart. It should smoothly transition via Stopping -> Exited -> Building (the image) -> Running state sequence.

### Steps To Reproduce

1. Open Aspire solution (Aspire main repo) in Visual Studio.
2. Set `playground/dockerfile/WithDockerfile.AppHost` as the startup project.
3. F5 (https launch profile)
4. Repeatedly restart the `mycontainer` container. While doing so, observe what states it transitions through.

**Comment by davidfowl** [comment]
Putting this in 9.0 as it's new behavior.

**Comment by SteveSandersonMS** [comment]
Agreed, and I'd expand this to include the regular "start" flow as well.

While I understand the "unhealthy" terminology is intended to mean "we cannot currently confirm it is healthy" and so it's technically true, it's really jarring to see what look like error messages (especially given the color/icons) when nothing is wrong.

**Comment by karolz-ms** [comment]
Well, technically, there is something wrong, namely, the Docker image build fails, for no good reason. So we want to compensate for this (retry), but we need to be a bit careful--too much retrying and performance will suffer, especially if the container runtime IS in fact, unhealthy. 

But yes, the way I expect this to be fixed will address the regular start scenario as well.

**Comment by SteveSandersonMS** [comment]
> Well, technically, there is something wrong, namely, the Docker image build fails, for no good reason

The message also appears during normal startup when the Docker image build doesn't fail.

**Comment by karolz-ms** [comment]
It turns out that the container status reflects reality. During heavy usage the Docker CLI will sometimes fail. That includes the periodic Docker runtime health check DCP is running in the background. When that check fails, containers that are being actively managed by DCP will show "runtime unhealthy" status.
