### ISSUE TITLE
Aspire.Hosting.Milvus shipped stable in 8.2 but is now shipping preview in 9.0

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#6431]
Aspire.Hosting.Milvus already shipped stable in 8.1 and 8.2. 

However, https://github.com/dotnet/aspire/pull/5707 added a dependency from Aspire.Hosting.Milvus to Milvus.Client. Milvus.Client doesn't have a stable version yet.

https://github.com/dotnet/aspire/pull/6388 marked this package as `SuppressFinalPackageVersion=true` for this reason.

If we don't ship a "stable" 9.0.0 package, people will continue using the 8.2.1 Aspire.Hosting.Milvus package with Aspire 9.0 because that is the latest "stable" version.

We need to decide what to do here for 9.0.0.

cc @mitchdenny @davidfowl @timheuer @DamianEdwards @Alirexaa

**Comment by eerhardt** [comment]
One option is to revert https://github.com/dotnet/aspire/pull/5707 so we can ship stable again.

Another option is to ship a `9.0.0-rc.2` version of this package and write docs explaining to people that they should be using this rc2 version with 9.0, even though it is not stable.

**Comment by mitchdenny** [comment]
Probably not a literal revert of that PR. I'll put up the PR this morning taking the health checks out and then we can decide if that's the route we want to go.

**Comment by eerhardt** [comment]
Re-opening for the backport to 9.0. See https://github.com/dotnet/aspire/pull/6451.

**Comment by eerhardt** [comment]
The fix was ported to release/9.0 and will ship with 9.0. Closing
