### ISSUE TITLE
Use custom grid for resource volumes

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#6444]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Resource volumes are displayed in standard property grid. It always has two columns: name/value.

Resource volumes have more than two values, and mashes multiple values into the values column. For example, the mapped path and volume type are both in value:

![Image](https://github.com/user-attachments/assets/608188d2-1b4f-4873-824f-f5256e49d1c3)

### Describe the solution you'd like

Add custom grid with three columns to properly format all data.

**Comment by joperezr** [comment]
We already use custom grids on Health Checks grid, so if someone wants to pick this up, we would just do the same but for resource volumes.

**Comment by willibrandon** [comment]
Agreed, it looks nicer when values have their own columns. Is something like this what you had in mind?

![Image](https://github.com/user-attachments/assets/ea19d749-9dcd-4d0a-9341-a525fb26e6f3)

**Comment by JamesNK** [comment]
Yes, that's great.
