### ISSUE TITLE
[WebToolsE2E][Aspire] Running with new Azure Function + Aspire, the error appears: "Application Insights SDK has not been added. Please add and configure the Application Insights SDK..."

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#6452]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.12 GA
3. Install Aspire 9.0 GA 
4. Apply feed

**REPRO STEPS**
1. New > Azure Function > .NET 9.0 Isolated (Preview) > Select "Http trigger" as Function, click "Enlist in Aspire orchestration" > Create
2. Build and run

**Note**: 
1. This is the new Azure Functions, the contents of Program.cs file are as follows
![Image](https://github.com/user-attachments/assets/9ca51679-3671-405f-b30a-519b8d62f2df)
2. The AzureFunctionsTools version as follow:
![Image](https://github.com/user-attachments/assets/fa3f863e-9872-4824-81db-5846286f299c)
3. When I run the Azure Function alone, it succeeds

**ACTUAL**:
An error will occur:
Microsoft.Extensions.Options.OptionsValidationException: 'Application Insights SDK has not been added. Please add and configure the Application Insights SDK. See https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service for more information.'
![Image](https://github.com/user-attachments/assets/69bd8ff7-f1e4-4684-8639-c338b8ac41c5)

**EXPECTED**
Run successfully

**Comment by captainsafia** [comment]
@mattchenderson Our CTI testing team ran into this issue as well. Any chance there's an issue on the Functions repo we can cross-link to?

@v-bennettyue This is a known issue for now but let's use this to track eventually reverifying this scenario.

**Comment by captainsafia** [comment]
Update: we think https://github.com/microsoft/ApplicationInsights-dotnet/pull/2908 will resolve this. I'm trying to validate this now with a local build of those changes against the template.

**Comment by joperezr** [comment]
Chatted about this during triage. For this one we will need to get a new version of App Insights SDK to nuget and then for the Functions templates to use that version.

**Comment by captainsafia** [comment]
Unfortunately, it looks like it'll take a while for the root cause that was referenced above to be resolved.

For the time being, you can work around this problem by commenting out the following line in the `Extensions.cs` of the service defaults project.

```diff
builder.Services.ConfigureHttpClientDefaults(http =>
{
    // Turn on resilience by default
-    http.AddStandardResilienceHandler();
+   //http.AddStandardResilienceHandler();

    // Turn on service discovery by default
    http.AddServiceDiscovery();
});
```

This should help unblocking testing for related scenarios like https://github.com/dotnet/aspire/issues/6297 and https://github.com/dotnet/aspire/issues/6482.

**Comment by captainsafia** [comment]
> Unfortunately, it looks like it'll take a while for the root cause that was referenced above to be resolved.

@balachir Correcting myself here. The Functions team has pushed an update to their templates in VS that comments out the problematic code.

If you run this scenario again and ensure that you're using the latest version of the toolset, you shouldn't run into this issue anymore.

You can verify the version of the Functions templates you are running on by opening the only file in the `%LocalAppData%/AzureFunctionsTools/Tags/v4/` and it should contain the following content:

![Image](https://github.com/user-attachments/assets/1e74dda8-4545-4d7a-862e-6e61714020c3)

**Comment by v-bennettyue** [comment]
@captainsafia @balachir This issue not repro on .net 9.0 Azure Functions + Aspire, the latest version of the toolset is 4.101.0.

**Comment by captainsafia** [comment]
> @captainsafia @balachir This issue not repro on .net 9.0 Azure Functions + Aspire, the latest version of the toolset is 4.101.0.

Great! Glad the new updates resolve this issue. Can we close this out or did you notice other problems?

**Comment by v-bennettyue** [comment]
There is no other issue, close this issue as fixed.

**Comment by mwiedemeyer** [comment]
I've just created a new FunctionApp project in the latest VS preview with ga .net9 and got the same error.
The project/dependencies are up to date.

If I comment out `http.AddStandardResilienceHandler();` in the ServiceDefaults project, it works fine. So it seems to be the same error as mentioned above.

**Comment by captainsafia** [comment]
@mwiedemeyer This was resolved in the Functions templates by disabling the logic that brought in the Application insights SDK.

When you go to your project file do you observe that package references associated with Application Insights are commented out in the default template?

If they are not, your Visual Studio might be pulling an older version of the Azure Functions templates.

Try restarting Visual Studio or searching for Azure Functions in your options panel and selection "Check for toolset update".

**Comment by mwiedemeyer** [comment]
Sorry, my bad. You are right. I've updated the functions tools from within VS and now the packages and startup code is commented. However, if I enable it, I have the same error. So what is the idea how to use it with app insights?

**Comment by captainsafia** [comment]
@mwiedemeyer Yes, this is an unfortunate issue with the way the Application Insight SDK registers its dependencies. This bug is tracked on the Applicaton Insights SDK over at https://github.com/microsoft/ApplicationInsights-dotnet/issues/2879. There's currently a PR open to resolve this in a future version of the SDK over at https://github.com/microsoft/ApplicationInsights-dotnet/pull/2908.

In the meantime, you can workaround this issue by temporarily disabling the `http.AddStandardResilienceHandler();` call in the default ServiceDefaults project.
