### ISSUE TITLE
[AzureTools][Aspire] There is no “Show All“ and ”Show value" icons in the opened detail page when viewing details of a resource in the Structured logs page

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire#6453]
**Regression:** Not a regression, this issue also reproduces on VS 17.10 with Aspire 9.0 P4

**Clean machine:** Win11 x64 23H2 ENU
**VS Version:** VS 17.12.0 Preview 3.0 [35409.206.d17.12]
**Aspire Version:** 9.0.0
Apply NuGet Feeds

**REPRO STEPS:**

1. Create a new Aspire starter App -> F5.
2. In the Dashboard -> Structured logs -> View details of a resource.
3. Check whether “Show All“ and ”Show value" icons in the opened detail page.

**Expect:**
“Show All“ and ”Show value" icons in the opened detail page.
![Image](https://github.com/user-attachments/assets/9facc3d0-6bde-42fe-9055-82198f6778d7)

**Actual:**
There is no “Show All“ and ”Show value" icons in the opened detail page.
![Image](https://github.com/user-attachments/assets/65821890-54c8-4605-bb7e-ceb69f9b1638)

**Comment by adamint** [comment]
This is intended behavior, as there are no sensitive environment variables in this view!
