### ISSUE TITLE
Allow for most flexibility for `HostStorage `on `AzureFunctionsProjectResource`

### ISSUE THREAD

**Issue by MarcinJuraszek** [dotnet/aspire#6464]
## Background and Motivation

Currently, `HostStorage` on `AzureFunctionsProjectResource` is typed as `AzureStorageResource?`. This is limiting, and prevents us from providing externally-run [Azurite](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage) instance as a target.

We want to continue using locally run Azurite because we use Azure Storage for more than just host storage for Azure Functions. The other data we use it for has to be persisted between Aspire AppHost runs, and even OS restarts. We've tried using containerized setup with Volumes but found it flaky.

## Proposed API

A new interface could be introduced with whatever parts of `AzureStorageResource` orchestrating a Functions project requires. Maybe `IAzureFunctionsHostStorage`? Then `AzureFunctionsProjectResource.HostStorage` could be updated to use that interface instead of `AzureStorageResource?` class.

In addition to the above, `IResourceBuilder<AzureFunctionsProjectResource>.WithHostStorage` extension method would have to be updated to take `IResourceBuilder<TStorage> where TStorage : IAzureFunctionsHostStorage`.

**Comment by MarcinJuraszek** [comment]
I don't remember much details unfortunately. It's been a while since I tried it, and back then we were trying it mostly with CosmosDb emulator and not Azure Storage. Maybe I should give it another shot. But still, I think having the flexibility here would be useful.

**Comment by davidfowl** [comment]
> But still, I think having the flexibility here would be useful.

We don't have way to model typed external resources and I wouldn't change this method. Instead, I would make it possible to get an azurite external reference via RunAsEmulator. That way there's still a storage resource. I'd prefer if you used a persistent container and volume though.

**Comment by MarcinJuraszek** [comment]
We will give a persistent container with a data volume a try and report back if we see it being unreliable.
