### ISSUE TITLE
[WebToolsE2E][Aspire] For an Azure Function app under Aspire orchestration, we don't show any metrics info even if select function resource

### ISSUE THREAD

**Issue by v-bennettyue** [dotnet/aspire#6482]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.12 GA
3. Install Aspire 9.0 GA
4. Apply feed

**REPRO STEPS**

1. New > Azure Function > .NET 8.0 Isolated (Long Term Support) > Select "Http trigger" as Function, click "Enlist in Aspire orchestration" > Create
2. Build and run
3. Navigate to Metrics of the dashboard

**Note**: For .net 9.0 azure function, it will encounter bug [#6452](https://github.com/dotnet/aspire/issues/6452)

**ACTUAL**
There is Function resource available, but there is no information on the page
![Image](https://github.com/user-attachments/assets/eccad3f1-d881-43ec-a705-db590f8cbccc)

**EXPECTED**
There is complete function information on Metrics page

**Comment by captainsafia** [comment]
@v-bennettyue Can you confirm what version of the `Aspire.Hosting.Azure.Functions` package is being referenced in your project file? I _think_ that you might be on an older version which is what is causing this issue.

**Comment by balachir** [comment]
@captainsafia I'm able to reproduce this too. The version I see in the csproj is `9.0.0-rtm.24523.16`.

**Comment by captainsafia** [comment]
@balachir Hmmm....something might have gone wrong with the scaffolding then. We don't ship a `9.0.0-rtm.24523.16` version of the `Aspire.Hosting.Azure.Functions` package. Perhaps that's the version you're seeing of the `Aspire.Hosting` package?

**Comment by balachir** [comment]
@captainsafia I tried this again using the latest version of Functions templates (version 4.100.0). I can still reproduce this issue that's described in the Repro Steps. It shows the Metrics tab, but when you select the function app, it says "No metrics for the selected resource". 

Here's my AppHost project file - this matches the versions available from the latest 9.0 Aspire build.

![Image](https://github.com/user-attachments/assets/6442f2bb-0e3f-4e96-aea6-6ff3d8f26dbe)

**Comment by joperezr** [comment]
@captainsafia is investigating into this further. This may require changes on the aspire repo.

**Comment by balachir** [comment]
@v-bennettyue can you try the workaround that Safia mentioned in #6452 ? Does that solve this issue?

**Comment by v-bennettyue** [comment]
@captainsafia @balachir This issue not repro on .net 9.0 Azure Functions + Aspire, but it still repro on .net 8.0 Azure Functions + Aspire, the latest version of the toolset is 4.101.0.

**Comment by captainsafia** [comment]
> @captainsafia @balachir This issue not repro on .net 9.0 Azure Functions + Aspire, but it still repro on .net 8.0 Azure Functions + Aspire, the latest version of the toolset is 4.101.0.

Yes, this is expected behavior for now. Only the 9.0 templates have been updated for Functions. Once we have confidence in the quality of those, we'll make the same updates to the 8.0 templates. We'll let you know when that happens.

**Comment by balachir** [comment]
@captainsafia thanks, it's great that this works for 9.0 Functions template now. I believe we don't need to track this as a blocking issue for Aspire 9.0 GA release anymore. Shall we still keep this issue active to track the 8.0 Functions template case? If you agree, you can go and update the milestone and priority as appropriate. Thanks!

**Comment by captainsafia** [comment]
@captainsafia Let's go ahead and close this out for now.

We're primarily targeting support for .NET 9 with the preview of this feature. As GA approaches, we'll do another round of testing for .NET 8.
