### ISSUE TITLE
[WebToolsE2E][Aspire] The Aspire 9 templates package needs to be updated to include Aspire 8.2.2 templates

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#6483]
**INSTALL STEPS**
1. Install VS 17.12 GA, with Aspire 8.2.0 checked in VS installer.
2. Install Aspire 9.0.0

**REPRO STEPS**
1. Create an Aspire 8.2 App by running `dotnet new aspire-starter -o AspireStarterApp01 -f net8.0 --aspire-version 8.2`

**ACTUAL**
Version of 8.2 template created is 8.2.1.
![Image](https://github.com/user-attachments/assets/e8383d59-80f5-461d-b163-1fd8445d8e47)

**EXPECTED**
It should be updated to 8.2.2.

**Comment by DamianEdwards** [comment]
@joperezr given 8.2.2 is out today, I'm assuming we should take a fix for this in 9.0

**Comment by joperezr** [comment]
Great find! Yes we need to fix this for 9.

**Comment by v-elenafeng** [comment]
Checked that this issue has been fixed in the latest aspire9 build.
