### ISSUE TITLE
Make VolumeNameGenerator public

### ISSUE THREAD

**Issue by ejsmith** [dotnet/aspire#6490]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the solution you'd like

Please make the VolumeNameGenerator class public so that other 3rd party packages can use it. There is a lot of logic in there to generate a proper volume name. Why make 3rd party packages recreate that same logic?

**Comment by davidfowl** [comment]
Yes, this should be public.

**Comment by los93sol** [comment]
> Yes, this should be public.

I took a swag at this one.

**Comment by danmoseley** [comment]
done
