### ISSUE TITLE
New integration : lakeFS

### ISSUE THREAD

**Issue by RudyCo** [dotnet/aspire#6508]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

lakeFS provides version control over the data lake, and uses Git-like semantics to create and access those versions. See [lakeFS](https://docs.lakefs.io/).

### Describe the solution you'd like

Ability to register a lakeFS container in `AppHost` and use it as a service in clients project.

**Comment by Alirexaa** [comment]
Please log the proposal in https://github.com/CommunityToolkit/Aspire repo
