### ISSUE TITLE
Error viewing container volumes when a same host path is mounted at different places in a container using .NET Aspire 9 RC1

### ISSUE THREAD

**Issue by asimmon** [dotnet/aspire#6509]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Using .NET Aspire 9 RC1, if the container has two or more bind mounts where the host path is the same, trying to open the container resource details in the dashboard will fail with the error "An unhandled error has occurred. [Reload]."

![Image](https://github.com/user-attachments/assets/42851ef7-b302-4d72-a2f8-d03d4910e4cb)

There are cases where the same file or directory could be mounted in different places. It is common to mount a certificate authority bundle to these container paths:

```
/etc/ssl/certs/ca-certificates.crt                // Debian/Ubuntu/Gentoo etc.
/etc/pki/tls/certs/ca-bundle.crt                  // Fedora/RHEL 6
/etc/ssl/ca-bundle.pem                            // OpenSUSE
/etc/pki/tls/cacert.pem                           // OpenELEC
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem // CentOS/RHEL 7
/etc/ssl/cert.pem                                 // Alpine Linux
```

This is valid in Docker Desktop:

![Image](https://github.com/user-attachments/assets/3c7ac464-e158-4aa8-a0d8-56975d46e5cd)

### Steps To Reproduce

```csharp
var builder = DistributedApplication.CreateBuilder(args);

builder.AddContainer("myapp", "mcr.microsoft.com/dotnet/samples", "aspnetapp")
    .WithBindMount("file.txt", "/foo/file.txt")
    .WithBindMount("file.txt", "/bar/file.txt");

builder.Build().Run();
```

### Anything else?

Nothing else, much love.

**Comment by drewnoakes** [comment]
Thanks very much for the great bug report @asimmon.

This bug reproduces in `release/9.0-rc1` but not in `release/9.0`. It was fixed in #6241.

FYI @JamesNK
