### ISSUE TITLE
[WebToolsE2E][Aspire] The "Actions" section and 'Column width' of the Resources, Structured, and Traces pages in the dashboard is not localized in non-ENU OS.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#6520]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 CHS
2. Install VS 17.12 GA
3. Install Aspire 9.0.0

**REPRO STEPS**

1. Create Aspire Starter App
2. Build solution and run the project

**NOTE**: This issue also repro on KOR OS and DEU OS.

**ACTUAL**:
The "Actions" section of the Resources, Structured, and Traces pages in the dashboard is not localized.
![Image](https://github.com/user-attachments/assets/9bbfeac4-c2b2-4282-85eb-e28a940dae02)
![Image](https://github.com/user-attachments/assets/7ca91e6e-3d68-470d-91c1-64f4901ed13c)
![Image](https://github.com/user-attachments/assets/012ae121-6b3f-4a27-b478-17818d4efa60)
![Image](https://github.com/user-attachments/assets/b9d2142b-f2f2-484a-a74d-c7dcdf4171b2)
![Image](https://github.com/user-attachments/assets/4f33f78e-fa84-41e1-827b-337985f511df)
The 'Column width' of the Resources, Structured, and Traces pages in the dashboard is not localized
![Image](https://github.com/user-attachments/assets/d7685c06-820f-4253-9010-faf192692efc)

**EXPECTED**:
The "Actions" section and 'Column width' are localized.

**Comment by balachir** [comment]
Do we need to fix this for Aspire 9.0 GA? @joperezr @JakeRadMSFT

**Comment by joperezr** [comment]
Great find, but I don't think we'll be able to take this in for 9, especially since we'd need the loc team to fix this so sounds like something we should target for our first servicing. @JakeRadMSFT thoughts?
