### ISSUE TITLE
[WebToolsE2E][Aspire] Running aspire project using CLI, the "Finished" status is marked red when clicking the Stop button of a project under Actions.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6521]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
3. Install SDK 9.0 GA
4. Install Aspire 9.0 GA 
5. Install VS or VSCode

**REPRO STEPS**
1. Open Command Prompt, run the following code to create an aspire starter app
`dotnet new aspire-starter -o aspire1`
2. Run the following command:
`cd aspire1/aspire1.AppHost`
`dotnet run`
3.  Open any url to go dashboard
4. Click the 'Stop' button any project under Actions

**ACTUAL**
Run the project using CLI, the "Finished" status under State is marked in red.
![Image](https://github.com/user-attachments/assets/587b8dd5-c451-4db9-84c9-8d765c4b5f41)

**EXPECTED**
Run the project using VS and VS Code, the "Finished" status under State is marked in gray.
![Image](https://github.com/user-attachments/assets/87c0461b-11f3-4cea-bbdd-8c45eeac4637)

**Comment by vmykagapuz** [comment]
This issue is the same with the issue [#6030](https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html) but its already fixed.

**Comment by joperezr** [comment]
Sounds like this might be an inconsistency of how dcp handles the projects that are launching? Or perhaps something different in app model? cc: @karolz-ms @mitchdenny

**Comment by karolz-ms** [comment]
@balachir @joperezr I assume this is not a ship-stopper for 9.0?

**Comment by joperezr** [comment]
I don't think so either, but it would be good to understand what the issue is and see if this is something we can fix in our first servicing

**Comment by karolz-ms** [comment]
Agreed

**Comment by davidfowl** [comment]
This is by design, a change by @drewnoakes

**Comment by joperezr** [comment]
Ok, let's review today in our workitem meeting and then either close if by design or update milestone + Priority if not as this is not blocking for 9.0.

**Comment by drewnoakes** [comment]
I changed it to be grey in #6231:

![Image](https://github.com/user-attachments/assets/4c5dbe9a-bee7-446d-996d-a0a3324b602e)

 I'm not sure how it ended up red. Perhaps @adamint knows, as he made some changes to statuses when working on health checks.

**Comment by drewnoakes** [comment]
The code hasn't changed since my PR:

https://github.com/dotnet/aspire/blob/be2a8955e7b9bc9e3ca0c397045322be40669b39/src/Aspire.Dashboard/Model/ResourceStateViewModel.cs#L31-L42

The icon in the screenshot looks like `ErrorCircle`, which would suggest a non-zero exit code.

@vmykagapuz what tool tip do you see on the state cell? It will tell you if the exit was unexpected and the exit code if it was non-zero.

**Comment by danmoseley** [comment]
Should there be a way (hover?) to see the actual exit code?

**Comment by davidfowl** [comment]
Details view?

**Comment by drewnoakes** [comment]
The state cell's tool tip does show the exit code too, if non-zero.

https://github.com/dotnet/aspire/blob/be2a8955e7b9bc9e3ca0c397045322be40669b39/src/Aspire.Dashboard/Model/ResourceStateViewModel.cs#L98-L112

**Comment by vmykagapuz** [comment]
@drewnoakes Regarding to the tool tip you mentioned, it shows "Project exited unexpectedly with exit code 1"
![Image](https://github.com/user-attachments/assets/f16b5550-5f71-49e0-ae7a-df9741a75e89)

**Comment by davidfowl** [comment]
Moving to the backlog. This isn’t a blocker. We should understand why dcp doesnt gracefully shutdown processes though.

cc @karolz-ms
