### ISSUE TITLE
[WebToolsE2E][Aspire][Unstable] Deploying 9.0 aspire project, the information in Console log shows "You must install or update .NET to run this application."

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6522]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
3. Install SDK 9.0 GA
4. Install Aspire 9.0 GA 
5. Install VS or VSCode

**REPRO STEPS**
1. Open Command Prompt, run the following code to create an aspire starter app
`dotnet new aspire-starter -o aspire1`
2. Deploy the project in CLI using the following commands:
```
azd init
azd up
```
4. Click the link of aspire dashboard
5. Navigate to Console logs and select any Resources

**NOTE**
1. This issue is unstable when deploying 9.0 aspire project.

**ACTUAL**
The State of the project is on 'Pending' and the information shown in Console log of the Resources is different from the usual log infromation.
![Image](https://github.com/user-attachments/assets/2bd14dd3-a85f-4a93-a24f-aba67e0f540e)
![Image](https://github.com/user-attachments/assets/f82c9aeb-4312-4776-9626-38bdcb34c678)

**EXPECTED**
The State of the project must show 'Running' and the information shown should be the same with the image below.
![Image](https://github.com/user-attachments/assets/73087976-eb7a-4671-b966-ca04f8d3c71e)

**Comment by joperezr** [comment]
This is expected as there are no base images that have the GA runtime installed. Can we validate that `net8` publishing works as we would expect that scenario to be testable.

**Comment by vmykagapuz** [comment]
@joperezr This issue is unstable it sometimes shows up and sometimes its not. Its also reproduce when deploying with .net8 project.

**Comment by davidfowl** [comment]
This should not happen when released versions. If you are using builds that aren’t yet public then it can happen. It shouldn’t be unstable.

**Comment by vmykagapuz** [comment]
> [@joperezr](https://github.com/joperezr) This issue is unstable it sometimes shows up and sometimes its not. Its also reproduce when deploying with .net8 project.

For todays validation, I verified that this issue is not reproduce in .NET8 project.

**Comment by joperezr** [comment]
Thanks for confirming. I'm closing this for now. Please feel free to reopen if we see it again.

**Comment by vmykagapuz** [comment]
This issue is not reproduced in latest-released of VS 17.12
