### ISSUE TITLE
VS Code issues with debugging Azure Functions projects

### ISSUE THREAD

**Issue by joperezr** [dotnet/aspire#6535]
Tracking these two issues primarily:

- https://github.com/microsoft/vscode-azurefunctions/pull/4299
- https://github.com/microsoft/vscode-azurefunctions/pull/4309

**Comment by captainsafia** [comment]
Both PRs on the Azure Functions side have now been merged (pending release on November 7th).

@WardenGnaw How are we looking on the PR on the VS Code side?

**Comment by joperezr** [comment]
Keeping this issue open to track the C# Dev Kit update that is left.

**Comment by joperezr** [comment]
The 2 changes above introduced a (non-aspire-related) regression, which required another fix from their side. We should be ready to validate final build.

**Comment by captainsafia** [comment]
All the dependencies needed for this have shipped:

C# Dev Kit: v1.13.9
C# Extension: v2.55.28
Azure Functions Extension: v1.16.0
