### ISSUE TITLE
[WebToolsE2E][Aspire][Mac] The project state still shows "Running" after clicking the stop button under "Actions" in Aspire dashboard when `dotnet watch` the Aspire starter project on Mac OS.

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#6541]
**INSTALL STEPS**

1. Clean machine: Mac OS
2. Install SDK 9.0 GA

    - Apply SDK 9.0 GA feed

3. Install Aspire 9.0 GA

    - Apply Aspire 9.0 GA feed

**REPRO STEPS**
1. Open CMD, create an Aspire Starter App using following commands:
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp
```
2. Dotnet watch the project in CMD.
`dotnet watch`
3. Click the 'Stop' button any project under "Actions"

Note:
1. This issue doesn't repro on Windows.
2. This issue doesn't repro when `dotnet run` the Aspire project on Mac OS.

**ACTUAL**
After the project is successfully stopped, the state still displays "Running".
![Image](https://github.com/user-attachments/assets/d2e2d097-18c7-4728-9ec7-7c8690eec7f9)

**EXPECTED**
After the project is successfully stopped, the state should displays "Finished".
![Image](https://github.com/user-attachments/assets/c6a51fb6-bef2-4048-a478-9c6ec5e0f5b4)

**Comment by davidfowl** [comment]
Dotnet watch is being rewritten to better support .NET Aspire projects. We won’t be fixing any issues with Watch and aspire until then. The sdk version is 9.0.200 (which is within the 9.1 timeframe)

**Comment by joperezr** [comment]
We already have an issue tracking the support for dotnet watch, so I'm closing this one for now in favor of that.
