### ISSUE TITLE
[WebToolsE2E][Aspire] When you delete another project in Aspire orchestration, the code in the APPHost/Program.cs is not updated.

### ISSUE THREAD

**Issue by Yangfanyue** [dotnet/aspire#6542]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.11.5 (include Aspire 8.1.0)

**REPRO STEPS**

1. Create .NET Aspire Empty App.
2. Right-click Solution > Add a new project > ASP .NET Core Web App (Razor Pages) with "Enlist in .NET Aspire orchestration".
3. Remove the Web project.
4. Build the Aspire project.

**ACTUAL:**
When I delete the web project, it will get an error:"CS0234	The type or namespace name 'WebApplication1' does not exist in the namespace 'Projects' (are you missing an assembly reference?)"
![Image](https://github.com/user-attachments/assets/0754346b-1b17-40da-9706-960feb46d661)

**EXPECTED:**
When deleting the Web project, the code in the Program.cs file should be automatically deleted.

**Comment by davidfowl** [comment]
This so by design.
