### ISSUE TITLE
[WebToolsE2E][Aspire] Two Aspire Starter Apps cannot be published to the same resource group at the same time.

### ISSUE THREAD

**Issue by Yangfanyue** [dotnet/aspire#6544]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.403
3. Install Aspire 8.2.2 

    - Run 'dotnet workload update'
    - Run 'dotnet workload install aspire'

4. Install azd (azd version 1.10.3)
5. Install git (git version 2.47.0.windows.2)

**REPRO STEPS**

1. Create two Aspire Starter Apps.
2. Publish these two Aspire Starter Apps to the same Resource group using CLI at the same time.

**ACTUAL:**
Two Aspire Starter Apps cannot be published to the same resource group.
![Image](https://github.com/user-attachments/assets/2b04e6da-984c-4e19-a43f-e9a8dc4d3691)
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:
Deployment Error Details:
AlreadyInUse: The registry DNS name acrflgr3loyj2pmk.azurecr.io is already in use. You can check if the name is already claimed using following API: https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/checknameavailability

**EXPECTED:**
Two Aspire Starter Apps can be published to the same resource group at the same time.

**Comment by davidfowl** [comment]
Can you move this to https://github.com/Azure/azure-dev/issues

**Comment by joperezr** [comment]
Closing this as you can't really transfer across orgs. @Yangfanyue Can you please log an issue in the repo that @davidfowl suggested above?
