### ISSUE TITLE
[WebToolsE2E][Aspire] The web page cannot be opened automatically after debugging the aspire project in VS Code.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#655]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install latest 8.0.100 SDK
3. Install VS Code
4. Install latest-released C# DevKit
5. Apply NuGet Feeds
6. Install Aspire workload

**REPRO STEPS**

1. Create an Aspire Application in CMD  and open with VSCode
```
  dotnet new aspire -o Aspire
  cd Aspire
  code .
```
2. Right-click the xxx.AppHost project > Debug > Start New Instance

**ACTUAL**
The web page cannot be opened automatically, you need to manually click the url in the debug console
![image](https://github.com/dotnet/aspire/assets/71361488/bb32afa8-7a5f-4a72-9988-5fab46ee2ec2)

**Note**
The webapp projects without Aspire can automatically open web pages after debugging

**EXPECTED**
The webpage can be opened automatically after debugging
![image](https://github.com/dotnet/aspire/assets/71361488/ceea4d68-3a11-4a78-be65-61c331806fc5)

**Comment by ElanHasson** [comment]
@DamianEdwards @timheuer 

Is there a manual workaround for this? My project runs, just no dashboard...

**Comment by timheuer** [comment]
With the project running the logs will show the endpoint for the dashboard. There may be some port forwarding you have to do a little manually when in devcontainer. I will check my workflow and post here any specific steps.

**Comment by timheuer** [comment]
@ElanHasson I wasn't able to get a workaround -- the dashboard works for me, but the subsequent app ports aren't forwarded

**Comment by davidfowl** [comment]
Can we link this to the vscode issue?

**Comment by joperezr** [comment]
Pending validation.

**Comment by v-sherryfan** [comment]
Verified this issue that it is not reproduce on VS Code CDK (1.5.6) + Aspire 8.0.0-preview.5.24175.9.
