### ISSUE TITLE
The <DcpPath> property doesn't work in test projects

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#6565]
Using the [`<DcpPath>` property ](https://github.com/dotnet/aspire/blob/92b8506f05f41bf2ba6634ed6b0dd63a46b64ca1/src/Aspire.Hosting.AppHost/build/Aspire.Hosting.AppHost.targets#L195) to override the directory to load *dcp* from doesn't work in tests using `Asprie.Hosting.Testing`, whether the property is set in the source app host project *.csproj* file, or the test project's *.csproj* file.

**Comment by dbreshears** [comment]
@DamianEdwards    I was able to make this work by setting DCPDir in the app host project _HealthChecksUI.csproj_, rebuilt it and then ran the single  test _SamplesIntegrationTests.AppHostTests.AppHostRunsCleanly(appHostPath: "HealthChecksUI.AppHost.dll")_ 

```
<DCPDir>c:\temp</DCPDir>
```

**Comment by DamianEdwards** [comment]
Hmmm neither I nor @karolz-ms could get this to work. Slightly confused now 🙃

**Comment by karolz-ms** [comment]
I believe we got this to work eventually.
