### ISSUE TITLE
OpenTelemetry.Instrumentation.SqlClient.TracerProviderBuilderExtensions should be public

### ISSUE THREAD

**Issue by JanEggers** [dotnet/aspire#6574]
I would like to use OpenTelemetry.Instrumentation.SqlClient.TracerProviderBuilderExtensions without changing my existing AddDbContext call wich is currently not possible because said class is internal. please make it public.

**Comment by davidfowl** [comment]
It's 80 LoC vendored into this repo from https://www.nuget.org/packages/OpenTelemetry.Instrumentation.SqlClient/1.9.0-beta.1 since it's not yet shipped as a non prerelease version. We're not going to expose this API publicly as the long-term goal is to use this pacakge once it is stable.
