### ISSUE TITLE
[WebToolsE2E][Aspire] Run the project using 'dotnet watch', the information of Web and ApiService projects is displayed in CMD.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#6587]
**REGRESSION INFO**: worked in SDK 9.0.100 + Aspire 9.0.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0.200-preview.0.24529.19
3. Install Aspire 9.0.0

**REPRO STEPS**
1. Open CMD, run following command to create an Aspire Starter App project
```
dotnet new aspire-starter -o AspireApp10
cd AspireApp10/AspireApp10.AppHost
```
2. Use `dotnet watch` to run the project

**ACTUAL**
The information of Web and ApiService projects is displayed in CMD.
![Image](https://github.com/user-attachments/assets/e9ef3c42-08c0-4da1-ad91-a4932bfcde03)

**EXPECTED**
Only AppHost project information is displayed in CMD.
![Image](https://github.com/user-attachments/assets/ff145429-adec-43f8-9663-c4e795b5f89d)

**Comment by davidfowl** [comment]
dotnet watch is being rewritten to work better with aspire, work is happening in 9.0.200 SDK which is not shipping with .NET 9. This has been fixed in that branch.

You can see the work items for watch and aspire here https://github.com/dotnet/sdk/issues?q=is%3Aissue%20label%3AAspire%20
