### ISSUE TITLE
Support Local QA Environments

### ISSUE THREAD

**Issue by dansiegel** [dotnet/aspire#6594]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently resources such as Azure SqlServer and Azure Storage run as local containers in development but when deploying these are excluded from the manifest and the actual Azure services are utilized. We need better support so that development teams can make local non-debug deployments which still utilize these containers so that QA can be done locally before PRs are merged and CI deploys to Azure.

### Describe the solution you'd like

```cs
builder.AddAzureSqlServer("sql-server")
    .PreserveContainer(builder.Environment == "QA");
```

**Comment by joperezr** [comment]
Discuss this during Triage. Currently, the default answer for doing this would either be having the QA team clone the project and run F5, or alternatively deploy to a staging environment that QA can use for testing. Is that something that can work for your use-case?

**Comment by dansiegel** [comment]
> Discuss this during Triage. Currently, the default answer for doing this would either be having the QA team clone the project and run F5, or alternatively deploy to a staging environment that QA can use for testing. Is that something that can work for your use-case?

Sorry I had missed your reply @joperezr. Running local isn't really an issue at all.. but for a local staging environment the concern would be to be able to deploy to another machine. The concern here would be to consider that you still want local Docker Resources for things like SQL Server, Storage, etc... that would normally be split off into actual provisioned Azure Resources. TBH I haven't had a chance to really dig into Aspir8, I'm not sure if perhaps the answer here would be that it could be part such a solution.
