### ISSUE TITLE
Sql Always On Availibility Group Support

### ISSUE THREAD

**Issue by gabriel-systems** [dotnet/aspire#6598]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the solution you'd like

Please consider supporting Sql Always On Availability Group configuration & deployments by adding extension methods .EnableAOAG( )

**Comment by davidfowl** [comment]
For Azure SQL?

**Comment by joperezr** [comment]
Thanks for posting this issue @gabriel-systems, can you please add more information about what specific feature you are talking about and what is the use case from the Aspire point of view? Is this specific about Azure SQL?
