### ISSUE TITLE
mixed platforms

### ISSUE THREAD

**Issue by gabriel-systems** [dotnet/aspire#6606]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to create a aspire project that allows the running of both windows & linux containers using the '--platform' switch; at present this looks to fail due to lack of support by aspire; as I am able to run both linux & windows containers for the commandline.

### Describe the solution you'd like

add extension methods to services/containers that support window/linux & both platforms; eg.  .AsWindowsContainer() or .AsLinuxContainer( )

**Comment by davidfowl** [comment]
We work support windows containers (see https://github.com/dotnet/aspire/issues/854).

**Comment by joperezr** [comment]
Closing as a dupe of #854 as per the above.
