### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by NikiforovAll** [dotnet/aspire#6621]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to start with something simple, like closing the "details" tab by clicking the ESC button. 

Another idea:

* Opening help for keyboard shortcuts by pressing "?"
* Navigating the resources tab by pressing 

### Describe the solution you'd like

Support keyboard shortcuts in general

**Comment by joperezr** [comment]
@NikiforovAll thanks for opening this. We have a help section on the top right that shows the shortcuts, and "?" is also supported (you may need to hit shift as well depending on your keyboard). Tab navigation is also supported.

I'm closing this for now as we support both of these, but if you find any others we don't support or have any follow up questions or comments please feel free to reopen.
