### ISSUE TITLE
How to Disable Local Provisioning

### ISSUE THREAD

**Issue by aligneddev** [dotnet/aspire#6623]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to use .Net Aspire, but I already have existing Azure resources that we've created with Terraform.

The Microsoft CoPilot points me to https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/local-provisioning and says I can add this to my settings file.

"Azure": {
  "Provisioning": {
    "Enabled": false
  },
  "SubscriptionId": "",
  "ResourceGroup": "",
  "Location": ""
},

Aspire starts, but fails with "Missing subscription configuration" in the dashboard logs.

If I enter real values, it still tries to provision.

Provisioning AppConfig...
Deploying AppConfig to rg-cus-appconfig
Error provisioning AppConfig.
Azure.RequestFailedException: The template deployment failed with error: 'Authorization failed

```
using Microsoft.Extensions.Configuration;

var builder = DistributedApplication.CreateBuilder(args);

var appConfig = builder.AddAzureAppConfiguration("AppConfig");
builder.AddProject<Projects.ApiService>("apiservice")
    .WithReference(appConfig);
builder.Build().Run();
```

dotnet user-secrets set ConnectionString:AppConfig "<connection-string>"

### Describe the solution you'd like

Can I just disable auto provisioning with an appsettings (as CoPilot suggests, but it isn't documented)?

**Comment by davidfowl** [comment]
To use an existing resource, you would skip all of this and directly use `AddConnectionString`.
