### ISSUE TITLE
Run Resource Commands from Console Logs Page

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#6626]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I've been doing some iteration of onboarding some db migrations into Aspire, which has involved me 

1. Go to Dashboard
2. Go to Console Logs
3. See Error and tweak migrations scripts to fix
4. Go back to the Dashboard to restart the resource
5. Go back to Console Logs to see why the process errored this time

As I'm able to iterate on the migrations outside of aspire, I can test changes by simply restarting the migration resoruce, rather than rebuilding the whole app host.

### Describe the solution you'd like

I'd like the ability to be able to start / stop and restart a resource (and potentially any other resource command) directly from the Console Logs page, without having to go back to to the dashboard and then back to console logs.  That way I could stay on the console log page the entire time - view errors, fix them then restart the migrations from within the console logs page.

Something like:
![Image](https://github.com/user-attachments/assets/6ebffcd9-c9c3-4d78-901d-95927d572982)

**Comment by malisancube** [comment]
Very nice idea. 

1. I've needed the ability to export the logs/traces. This would help in various instances including reporting, rather than using screenshots for traces. 

2. Additionally if there is Commands that can be used on multiple Resources at the same time.

3. Adding a way to notify on custom thresholds/conditions that can be added as filters.

**Comment by joperezr** [comment]
Would this only be applicable to console logs? @drewnoakes mentioned during triage that we may want to consider putting this in other telemetry places.

**Comment by afscrome** [comment]
Yes, would definitely make sense in other telemetry place where the telemetry is scoped to a single resource.  (i.e. it may not make as much sense in a trace crossing several different resources, unless it is clear which resource the commands apply to)

**Comment by JamesNK** [comment]
PR here: https://github.com/dotnet/aspire/pull/6819

I'm just adding it to console logs for now. Console logs is more directly related to resources compared to telemetry. e.g. telemetry pages run without a resource service in standalone mode.

Can always change in the future.
