### ISSUE TITLE
PromQL Dashboard Definitions

### ISSUE THREAD

**Issue by braydonk** [dotnet/aspire#6679]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The standalone dashboard tool is awesome for traces and logs! What I would really like to see is a level of customization for the metrics dashboards. Currently, the raw values of the metrics are graphed, which works for some metrics. But there may be metrics like monotonic sums where what we actually want to graph is the rate of change over time (the derivative), and there isn't a way currently to represent some more complex aggregations in a metric dashboard.

### Describe the solution you'd like

Ideally, I would love to see an interface that would allow me to specify dashboards through [PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/). 

### Additional context

PromQL was chosen here primarily because it seems to be (?) the most popular metric query language at this time. I am open to any better options as well (or perhaps even an extensible query engine interface, but maybe that's thinking too far ahead).

**Comment by davidfowl** [comment]
We're not going to implement PromQL in the dashboard, at that point just use the grafana stack.

**Comment by braydonk** [comment]
Okay that's fine. Thanks!
