### ISSUE TITLE
Azurite Emulator for .NET9 Requires Image Version Bump

### ISSUE THREAD

**Issue by jsedlak** [dotnet/aspire#6692]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Upon updating an Aspire project that uses Azure Storage, and specifically the `RunAsEmulator` method, the following error is encountered. 

> 'The API version 2025-01-05 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 

**Potentially Important Detail**: This particular project uses Azure Storage for clustering in Microsoft Orleans, and it is in that project where the error occurs.

The `RunAsEmulator` method specifies the default image version is 3.32.0.

Manually specifying 3.33.0 resolves the error.

### Expected Behavior

Using `RunAsEmulator` should work with defaults in .NET9 without specifying an image version.

### Steps To Reproduce

1. Create an Aspire Project with an AppHost
2. Add an Orleans Silo
3. Map Orleans to use Azure Storage, running as an emulator (azurite) for clustering and grain storage
4. Run the project

### Exceptions (if any)

The API version 2025-01-05 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 

### .NET Version info

.NET 9
SDK Version: 9.0.100

**Comment by adityamandaleeka** [comment]
This is already fixed in main with https://github.com/dotnet/aspire/pull/6670

**Comment by joperezr** [comment]
We will ship this in 9.1. Closing.
