### ISSUE TITLE
Version 9.0.0 of Aspire.Npgsql.EntityFrameworkCore.PostgreSQL Package Does Not Exist on NuGet

### ISSUE THREAD

**Issue by MarcelMichau** [dotnet/aspire#6697]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hi there!

Not sure if I might be missing something, but there does not seem to be a final `9.0.0` version of the `Aspire.Npgsql.EntityFrameworkCore.PostgreSQL` published to NuGet.

At time of writing, these are the available versions on NuGet:

![Image](https://github.com/user-attachments/assets/3ca97c6e-45e4-489e-b2b2-6137062fc9bd)

### Expected Behavior

I expect a `9.0.0` version to be published to align with the .NET 9 release.

### Steps To Reproduce

N/A

### .NET Version info

N/A

**Comment by joperezr** [comment]
This is expected as the Npgsql EF package hadn't shipped stable when we were preparing our 9.0.0 build, so we shippied it as 9.0.0-rc.2... Now that they have shipped, we are getting ready to ship our 9.0.0 stable aspire integration in the next few days.

**Comment by joperezr** [comment]
Closing this as the change required for this was merged earlier today into release/9.0 branch. Feel free to reopen if you have any other questions.

**Comment by eerhardt** [comment]
https://www.nuget.org/packages/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL/9.0.0 is now live on nuget.org.
