### ISSUE TITLE
Dashboard tooltips do not appear dark in dark mode

### ISSUE THREAD

**Issue by willibrandon** [dotnet/aspire#6700]
Hello, thanks for the great work.

I've noticed when setting the dashboard theme to dark mode that the tooltips do not appear dark.
Would it be possible to make the dashboard tooltips darker when it is in dark mode?

![Image](https://github.com/user-attachments/assets/b258a49a-ab1c-41fb-92a5-23179e08e939)

**Comment by willibrandon** [comment]
I should add that if I set my Windows theme to dark, and set the dashboard theme to System, the dashboard tooltips appear dark.

![Image](https://github.com/user-attachments/assets/17d42aca-233b-45fe-9f99-bd010d1fc125)

It only appears to be an issue when the Windows theme is not dark, and the dashboard theme is set to Dark.

**Comment by JamesNK** [comment]
I don't think there is anything we can do about that. That tooltip is styled by the browser.

If I set GitHub to dark mode in a browser I get the same experience.

GH in dark mode, browser in light mode:
![Image](https://github.com/user-attachments/assets/0dd6e9b8-f1de-4d54-8328-865b06ab16f8)

GH in dark mode, browser in dark mode:
![Image](https://github.com/user-attachments/assets/dba334dd-62dc-4cb4-bc02-86491bc7f0f7)

**Comment by willibrandon** [comment]
I understand, and since the tooltips do appear dark when I use a dark system theme, I think this issue can be closed.
