### ISSUE TITLE
Restore fails on linux for Aspire.Hosting.Orchestration.linux-x64

### ISSUE THREAD

**Issue by GabschD** [dotnet/aspire#6757]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I'm trying to build an aspire project in an Azure DevOps pipeline (self hosted on a VMSS with ubuntu 22-04) and it fails on restore.
I found a similar issue, but it [mentions 8.2](https://github.com/dotnet/aspire/issues/6287) so maybe its a diffferent one.

```
Failed to download package 'Aspire.Hosting.Orchestration.linux-x64.9.0.0' from 'https://api.nuget.org/v3-flatcontainer/aspire.hosting.orchestration.linux-x64/9.0.0/aspire.hosting.orchestration.linux-x64.9.0.0.nupkg'.
         The download of 'https://api.nuget.org/v3-flatcontainer/aspire.hosting.orchestration.linux-x64/9.0.0/aspire.hosting.orchestration.linux-x64.9.0.0.nupkg' timed out because no data was received for 60000ms.
           The operation has timed out.
```

As those links are actually empty.

Csproj for reference:

```
<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>...</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="....Service.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0" />
  </ItemGroup>
</Project>
```

### Expected Behavior

Packages get restored without issues

### .NET Version info

dotnet 9.0.0

**Comment by davidfowl** [comment]
cc @joperezr

**Comment by joperezr** [comment]
Thanks for your report @GabschD . By looking at the original error message, seems like this was just a timeout on NuGet, perhaps there was something wrong with the service or network when you tried to run your build? Can you repro this still? Also, can you share what is the workaround that seemed to fix it for you?

**Comment by GabschD** [comment]
i @joperezr,

I clicked the link on Friday and got a 404, but maybe I had a typo in it - can't reporduce it.
They seem to be available now.

My workaround was to set the follwing:

``` xml
<PropertyGroup>
  <SkipAddAspireDefaultReferences>true</SkipAddAspireDefaultReferences>
</PropertyGroup>

<ItemGroup>
  <PackageReference Include="Aspire.Dashboard.Sdk.linux-x64" Version="8.2.0" />
  <PackageReference Include="Aspire.Hosting.Orchestration.linux-x64" Version="8.2.0" />
</ItemGroup>
```

It downloaded them instantly and never timed out. Removing it resulted in the timeout.

**Comment by davidfowl** [comment]
@GabschD update to the 9.0 version of Aspire. It works with both .NET 8 and 9

**Comment by GabschD** [comment]
@davidfowl Thank you for your time. Everything works now.

**Comment by joperezr** [comment]
Glad to hear that. Closing this now. Feel free to re-open if you have any follow-up questions.
