### ISSUE TITLE
Navigating across links in Traces tab doesn't appear to work

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#6771]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When Traces have "Link" and "Backlinks", navigating to these linked traces doesn't navigate to the linked issue. The dashboard stays at the current trace.

### Expected Behavior

I expect the linked trace to be shown in the dashboard.

### Steps To Reproduce

1. Checkout https://github.com/dotnet/aspire/pull/6770, which adds support for RabbitMQ v7. The traces emitted from this new version have links instead of parent-child relationships between traces.
2. Run the TestShop playground app.
3. Add an item to the basket and click the "cart" button to checkout
4. In the Dashboard, navigate to the trace for the orderprocessor that received the message
5. At the bottom of that trace, find the linked trace that sent the message and click "View"

![Image](https://github.com/user-attachments/assets/bb442b7e-1b13-4b31-8045-82068a6422d1)

### Anything else?

cc @JamesNK

**Comment by JamesNK** [comment]
I can repo it. Links between spans in one trace work, but links between spans in different traces is broken.
