### ISSUE TITLE
Missing space in source column for NPM

### ISSUE THREAD

**Issue by rosieks** [dotnet/aspire#6784]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In dashboard in source column there is missing space for NPM resource:
![Image](https://github.com/user-attachments/assets/727947d6-ce90-4b67-ad0d-970143bf8ca2)

### Expected Behavior

There should be spaces between npm and dev

**Comment by davidfowl** [comment]
This was fixed https://github.com/dotnet/aspire/issues/6585.
