### ISSUE TITLE
Bicep modules should allow to override the sku

### ISSUE THREAD

**Issue by naillizard** [dotnet/aspire#6822]
https://github.com/dotnet/aspire/blob/8761d7223c296429b068eafe404945c918e6f577/playground/bicep/BicepSample.AppHost/appConfig.module.bicep#L17

trying to override the sku as follows.

```
var appConfiguration = builder.AddAzureAppConfiguration("appc-vrp-dev-ae").WithParameter("sku", "free");
```

I can confirm that it passes the argument to bicep and compiles it, but throws a warning as the parameter is not used.

So the resource always gets created using the `standard` sku as it's hard coded in the template on line 17.

All modules that I've checked don't allow the sku to be overriden, the App Configuration one does have the parameter defined, but does not utilise it in the template.

**Comment by davidfowl** [comment]
These bicep modules are dynamically generated. If you want to change the sku, you can set it like so:

```C#
var appConfig = builder.AddAzureAppConfiguration("appConfig")
                       .ConfigureInfrastructure(infra =>
                       {
                           var sku = new ProvisioningParameter("sku", typeof(string));

                           var store = infra.GetProvisionableResources().OfType<AppConfigurationStore>().Single();
                           store.SkuName = sku;
                       })
                       .WithParameter("sku", "standard");
```

This uses parameters, but you can set it directly as well:

```C#
var appConfig = builder.AddAzureAppConfiguration("appConfig")
                       .ConfigureInfrastructure(infra =>
                       {
                           var store = infra.GetProvisionableResources().OfType<AppConfigurationStore>().Single();
                           store.SkuName = "free";
                       })
```
