### ISSUE TITLE
Azure Key Vault component: map has no entry for key "SECRETS_VAULTURI"

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspire#6825]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In what appears to be very similar to [this discussion](https://github.com/dotnet/aspire/discussions/4074) I've attempted to deploy a .NET 8 application running the latest Aspire versions with an Azure Key Vault deployment.

Each deployment of "azd deploy" fails with:

> ERROR: failed deploying service 'abc123': failed executing template file: template: manifest template: 27:23: expected "manifest template" at <.Env.SECRETS_VAULTURI>: map has no entry for key "SECRETS_VAULTURI".

It doesn't seem to matter if I set the Vault URI in my appsettings.json or not, all deployments with the AzureKeyVault reference on my singular service appear to fail in the same way.

### Expected Behavior

I expected the solution to deploy without error.

### Steps To Reproduce

1. Add <PackageReference Include="Aspire.Hosting.Azure.KeyVault" Version="9.0.0"/> to AppHost
2. Add <PackageReference Include="Aspire.Azure.Security.KeyVault" Version="9.0.0"/> to client app
3. Update program.cs on client app:
```cs
var builder = WebApplication.CreateBuilder(args);
builder.AddAzureKeyVaultClient("secrets");
```
4. Update program.cs on app host:
```cs
const string azureKeyVaultRef = "secrets";
var secrets = builder.ExecutionContext.IsPublishMode
    ? builder.AddAzureKeyVault(azureKeyVaultRef)
    : builder.AddConnectionString(azureKeyVaultRef);

builder.AddProject<Projects.MyProject>("myproject")
  .WithReference(secrets);
```

Attempt an `azd deploy` and observe it fail.

### Exceptions (if any)

ERROR: failed deploying service 'abc123': failed executing template file: template: manifest template: 27:23: expected "manifest template" at <.Env.SECRETS_VAULTURI>: map has no entry for key "SECRETS_VAULTURI".

### .NET Version info

.NET SDKs installed:
  8.0.303 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

**Comment by davidfowl** [comment]
@WhitWaldo did you run azd provision first?

**Comment by WhitWaldo** [comment]
I tried and then it wanted me to provide a secret value for something and didn't like anything I typed in. I wound up just creating a brand new .NET 9 Aspire project and migrating everything over and it worked like a charm, so it was something about migrating between the two it just didn't care for.
