### ISSUE TITLE
Using custom class libraries (Non NuGet Based) in AppHost

### ISSUE THREAD

**Issue by KFKMan** [dotnet/aspire#6848]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We can't use libraries it's creating a lot of problem.
For example we need to use copy and paste const strings between projects and apphost, we can't create and use Shared library for storing component names.

Original issue => https://github.com/dotnet/aspire/issues/2769

### Describe the solution you'd like

Using your solution (https://github.com/dotnet/aspire/issues/2769#issuecomment-1989409888)

For Aspire Services use `AspireProjectResource` instead of the `ProjectReference`

**Comment by davidfowl** [comment]
You can set IsAspireProjectResource=false on the project reference
