### ISSUE TITLE
Postgres not starting on Aspire 9: could not create network

### ISSUE THREAD

**Issue by dvlprx** [dotnet/aspire#6851]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Postgres is not starting, with Aspire 9 because the subnet pool is full:

ErrorMessage:

```
fail: Aspire.Hosting.Dcp.dcpctrl.NetworkReconciler[0]
could not create the network as all available subnet ranges
from the default pool are allocated, retrying...
{
    "NetworkName": {"name":"default-aspire-network"}, 
    "Reconciliation": 16, 
    "Network": "default-aspire-network-o428ocs3sd", 
    "error": "object could not allocate required resources/nnetwork subnet pool full"
}
```

This happens after upgrading an existing solution to .Net 9 (that works with .Net 8,) as well with a new .Net9 / Aspire 9 project, that just adds a postrgesDb

Is there a way, to specify the aspire network name per aspire-project? I could not find any information on the web related to this.

### Expected Behavior

Postgres starts

### Steps To Reproduce

1. Create a new .Net Aspire 9 project
2. Add reference to Aspire.Hosting.PostgreSQL (9.0.0)
3. Create Main:

```
internal class Program
{
    private static void Main(string[] args)
    {
        var builder = DistributedApplication.CreateBuilder(args);

        var postgresEventStore = builder
            .AddPostgres("Postgres-TEST")
            .WithPgAdmin(); // web-ui for the postgres server

        builder.Build().Run();
    }
}
```
4. Start

### Exceptions (if any)

fail: Aspire.Hosting.Dcp.dcpctrl.NetworkReconciler[0]
could not create the network as all available subnet ranges
from the default pool are allocated, retrying...
{
    "NetworkName": {"name":"default-aspire-network"}, 
    "Reconciliation": 16, 
    "Network": "default-aspire-network-o428ocs3sd", 
    "error": "object could not allocate required resources/nnetwork subnet pool full"
}

### .NET Version info

.Net 9

**Comment by davidfowl** [comment]
Close the app and run `docker network prune`

There's a know issue where we leak networks in some cases (like if you use dotnet watch)

**Comment by davidfowl** [comment]
@dvlprx were you using dotnet watch?

**Comment by davidfowl** [comment]
cc @karolz-ms @dbreshears

**Comment by meum** [comment]
i had the same issue. can confirm that i used dotnet watch

**Comment by dvlprx** [comment]
> [@dvlprx](https://github.com/dvlprx) were you using dotnet watch?

nope .. 

I use Visual Studio 2022, latest update, + Codeium Extension
