### ISSUE TITLE
[WebToolsE2E][Aspire] When searching for Aspire.Hosting.Azure.AppContainers and Aspire.Hosting.Azure.Functions using the integration tag, these two packages are not found.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/aspire#6882]
**INSTALL STEPS**

1. Clean machine: Win11 x64 24h2 ENU
2. Install Dev17.12.3

   - Web workload
   - Includes Aspire 9.0.0 
   - Includes .NET SDK 9.0.101

3. Install Aspire 9.1.0-preview.1.24578.4

**REPRO STEPS**

1. Open VS > Create a new project > .NET Aspire Starter App > Framework: .NET 9.0 > Create.
2. Right-click AspireApp.AppHost > Add > .NET Aspire package
3. Change the search criteria to "tags:integration+hosting+azure+functions" or "tags:integration+hosting+azure"

**ACTUAL**
When the search criteria includes integration, the packages Aspire.Hosting.Azure.AppContainers and Aspire.Hosting.Azure.Functions cannot be found.
![Image](https://github.com/user-attachments/assets/86c0ce67-d62c-4c72-9f2d-8d4ca9ddfa9e)

![Image](https://github.com/user-attachments/assets/03905f62-3709-4ebd-b03c-e288a27bc923)

In fact, the tags of these two packages both contain integration
![Image](https://github.com/user-attachments/assets/1742dec0-010d-4874-922e-1a8c7b6db0ef)

![Image](https://github.com/user-attachments/assets/84876484-3337-4bc6-b099-fa3146fbb9ef)

**EXPECTED**
When using the tag integration, the packages Aspire.Hosting.Azure.AppContainers and Aspire.Hosting.Azure.Functions can be searched.

**Comment by davidfowl** [comment]
Yes this was recently fixed https://github.com/dotnet/aspire/pull/6832

**Comment by v-reinawang** [comment]
@davidfowl This issue still repro. 
When I search directly for the package name Aspire.Hosting.Azure.Functions, I can see that the integration tag has been added.
![Image](https://github.com/user-attachments/assets/d770787c-6c1c-4e8b-a974-189157781ee1)

But when I use "owner:Aspire tags:integration+hosting+functions" to search for this package, it shows that no package is found.
![Image](https://github.com/user-attachments/assets/67a64288-dae8-4c14-accf-84bb88289e6e)

When I delete the word integration from the search criteria and search for the package using "owner:Aspire tags:hosting+functions", I can find the package Aspire.Hosting.Azure.Functions.
![Image](https://github.com/user-attachments/assets/780d5ee4-fb0f-4bdc-bdeb-ff995d4a5ba9)
