### ISSUE TITLE
New instances of persistent containers are always created on each test run when using DistributedApplicationTestingBuilder

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#6888]
Container resources configured to be persistent with `.WithLifetime(ContainerLifetime.Persistent)` will get new instances created for every test run when using `DistributedApplicationTestingBuilder`, resulting in extra container instances that never get cleaned up.

This is due to `DistributedApplicationTestingBuilder` always setting a resource name suffix based on `Random.Shared.Next()` for every instance of a `DistributedApplication` that it creates:

https://github.com/dotnet/aspire/blob/973a62362af61ce7a00c51d361d2ad14a9e5acb2/src/Aspire.Hosting.Testing/DistributedApplicationFactory.cs#L163C14-L163C79

This behavior means that all resources created by `DistributedApplicationTestingBuilder` are always isolated, which conflicts with the idea of persistent containers.

We should consider introducing support for controlling the behavior of persistent containers from tests so that isolation (from regular app host runs and/or between test runs) can be an controlled, similar to the proposal for controlling volume isolation in #4462.

**Comment by afscrome** [comment]
Related to #6850.

**Comment by DamianEdwards** [comment]
@afscrome oh doh, I didn't find that one when I went searching 😢 
I'll close this as a dupe.
