### ISSUE TITLE
No tracing after adding the .NET Aspire Orchestrator Support

### ISSUE THREAD

**Issue by steentottrup** [dotnet/aspire#6894]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After I add ".NET Aspire Orchestrator Support" to my solution with 2 Workers, I'm getting no traces in the Aspire UI from the 2 workers.

### Expected Behavior

I expected any activities created in the workers would show up in the Aspire UI.

### Steps To Reproduce

The issue can be seen here: https://github.com/steentottrup/aspireotelissues
I've created a solution, added 2 worker projects, and then added the Aspire Orchestrator support (AppHost and service defaults.).
I was actually trying to figure out how to do tracing across boundaries (RabbitMQ), but with nothing showing up in tracing at all, that didn't work out. 

### .NET Version info

.NET 8, Aspire 9.

### Anything else?

To get anything other than null when I call StartActivity on the ActivitySource, I've had to add an ActivityListener. Why is this needed? In the Aspire starter project "it just works".

**Comment by davidfowl** [comment]
> I was actually trying to figure out how to do tracing across boundaries (RabbitMQ), but with nothing showing up in tracing at all, that didn't work out.

See https://github.com/dotnet/aspire/issues/562

cc @eerhardt

**Comment by steentottrup** [comment]
> See [#562](https://github.com/dotnet/aspire/issues/562). The rabbitmq client integration has no tracing outside of connecting to the endpoint.

But isn't the activities in the .NET code supposed to still show up? I'm creating an activity in one worker, and trying to continue it in another (not depending on any library doing it for me).

**Comment by davidfowl** [comment]
I didn't realize you were making your own activities:

These lines are not required and should be deleted.

https://github.com/steentottrup/aspireotelissues/blob/501d3b7426bf6e28ac00d13df325d96b88f0bf7e/src/WorkerTwo/Worker.cs#L33-L39
https://github.com/steentottrup/aspireotelissues/blob/501d3b7426bf6e28ac00d13df325d96b88f0bf7e/src/WorkerOne/MessageBroker.cs#L32-L38

You need to configure open telemetry tracing with your activity source (it is an activity listener):

https://github.com/steentottrup/aspireotelissues/blob/501d3b7426bf6e28ac00d13df325d96b88f0bf7e/src/AspireShowcase.ServiceDefaults/Extensions.cs#L61

That call to AddSource needs to pass the name of activity source e.g. "MessageBroker" see https://github.com/steentottrup/aspireotelissues/blob/501d3b7426bf6e28ac00d13df325d96b88f0bf7e/src/WorkerOne/MessageBroker.cs#L9.

**Comment by steentottrup** [comment]
> That call to AddSource needs to pass the name of activity source e.g. "MessageBroker" see https://github.com/steentottrup/aspireotelissues/blob/501d3b7426bf6e28ac00d13df325d96b88f0bf7e/src/WorkerOne/MessageBroker.cs#L9.

Thank you for getting back to me on this!

Stupid me, I knew that. I'm doing that on the workers I have running in production. Thank you!

So I did what you suggested, now I'm adding the sources (not sure whether I need to add "Worker" on the receiving end), but now I'm back to getting null when I call StartActivity. The reason why I picked up the lines with the ActivityListener from some StackOverflow post.

I understand this has (probably) nothing to do with Aspire, but it does make it a bit hard to get started, if it requires a lot of knowledge about activities/tracing to start using it with the Aspire templates.

The web/webapi starter set "just works", and I've tried looking into what's going on in HttpClient and on the server side, with the IHttpActivityFeature, but it has a lot of moving parts.

**Comment by eerhardt** [comment]
> To get anything other than null when I call StartActivity on the ActivitySource, I've had to add an ActivityListener. Why is this needed? 

Check out https://learn.microsoft.com/en-us/dotnet/core/diagnostics/observability-with-otel for a good overview of how things work.

Yes you need an ActivityListener. If no one is listening to the Activity, it isn't doing anything for perf reasons.

> In the Aspire starter project "it just works".

The reason it works is because of these lines in the starter app template:

https://github.com/dotnet/aspire/blob/28ded72163532b892e809a1e62e1f93bcea88b20/src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.0/Extensions.cs#L61-L65

**Comment by steentottrup** [comment]
> Check out https://learn.microsoft.com/en-us/dotnet/core/diagnostics/observability-with-otel for a good overview of how things work.
> Yes you need an ActivityListener. If no one is listening to the Activity, it isn't doing anything for perf reasons.
> 
> > In the Aspire starter project "it just works".
> 
> The reason it works is because of these lines in the starter app template:
> 

Got it! Thanks! I seem to have it working now.

Maybe you should have something that's not HttpClient/Web based in the example template for Aspire ? Something that doesn't just work out of the box, without using AddSource.

I could take a look and make a pull request?

**Comment by davidfowl** [comment]
Not a template but in the template no. In our samples repo sure (I think test shop has this already though)

**Comment by eerhardt** [comment]
Closing this issue as the question has been resolved.
