### ISSUE TITLE
Can't run Test Hosts in a remote WSL

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#6918]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you try to run an test with `DistributedApplicationTestingBuilder` with the remote test runner in visual studio against wsl, it fails with the error
```
System.IO.DirectoryNotFoundException : /mnt/s/AspireApp2/AspireApp2.Tests/bin/Debug/net8.0/S:\AspireApp2\AspireApp2.AppHost/
```

It looks like something is trying to use the path to the AppHost from windows within Linux which ends badly.

I'm guessing the VS remote runner compiles the app host on windows before running it in wsl.  However the windows compilation bakes in `Projects.AspireApp2_AppHost` with the windows path, which then doesn't resolve on wsl.
![Image](https://github.com/user-attachments/assets/c215cdf1-2d79-425a-833a-6a3b66024359)

### Expected Behavior

Tests to run.

### Steps To Reproduce

I reproed in a solution based on the Aspire Starter template, although I imagine this is reproduceable on any project.
 
1. Create a `testenvironments.json` file with the following```
{
    "version": "1",
    "environments": [
      {
        "name": "WSL-Ubuntu",
        "type": "wsl",
        "wslDistribution": "Ubuntu"
      }
    ]
  }
```

2. In the VS Test Explorer, select your WSL instance then try to run a test
![Image](https://github.com/user-attachments/assets/0ce65f12-9a93-45fb-a04a-b5ea21267f5c)


### Exceptions (if any)

_No response_

### .NET Version info

wsl
```
alex@DEVLAP290:/usr/local$ dotnet --info
.NET SDK:
 Version:           8.0.110
 Commit:            87a66bb3d1
 Workload version:  8.0.303-baseline.24317.8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.110/

.NET workloads installed:
 Workload version: 8.0.303-baseline.24317.8
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  8.0.110 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Windows
```
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  6.0.428 [C:\Program Files\dotnet\sdk]
  8.0.404 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Anything else?

![Image](https://github.com/user-attachments/assets/88e0cfac-8b79-46c8-9dce-347f03a1bb95)

Aspire 9.0

**Comment by DamianEdwards** [comment]
I think this is the same category of issue as trying to run an app host project from VS on WSL using the WSL launch profile that VS provides. If the project is built on Windows then copied to WSL (or a container) and run from there, it isn't going to work because as you point out the absolute paths to the project files are determined at build time.

Related #2874 #5117

Actually this might just be a dupe of #5442

**Comment by afscrome** [comment]
Yup, looks like an exact dupe of #5442.  Will close this one in favour of that.
