### ISSUE TITLE
Service bindings require a port but the API makes it seem like it is optional

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#693]
This blows up but compiles just fine:

```C#
builder.AddContainer("redis", "redis")
                   .WithServiceBinding();
```

Same:

```C#
builder.AddProject<Projects.AspireApp10_ApiService>("apiservice")
                        .WithServiceBinding(scheme: "http");
```

We should fix this so that the required arguments show up on the method. I spent time looking to see how to make DCP select random ports but it doesn't like it's possible.

To clean this up, we might need overloads that target `IResourceBuilder<T> where T : ContainerResource` for containers that have a container port and the generic one for everything else.

cc @mitchdenny

**Comment by jack775544** [comment]
For getting a random port, can't you just set the port to `0`? I have used that in the past for spinning up docker containers and not knowing what port I want to use ahead of time.

**Comment by mitchdenny** [comment]
@jack775544 -- ultimately this is what well end up doing (although we'll use null to signify random assignment). We don't let Docker do this part of our port selection; we defer that to DCP because it needs to spin up a reverse proxy in replica scenarios.

**Comment by davidfowl** [comment]
@karolz-ms I *think* https://github.com/dotnet/aspire/pull/946 will help here

**Comment by karolz-ms** [comment]
@davidfowl agreed. All part of "containers as means to run  services that my team doesn't own, but are part of larger app"

**Comment by davidfowl** [comment]
Closing this out. We still need to rename this API but @karolz-ms's changes made this much better:

```C#
builder.AddProject<Projects.AspireApp10_ApiService>("apiservice")
                        .WithServiceBinding(scheme: "http");
```

This works
