### ISSUE TITLE
[WebToolsE2E][Aspire] The description for changing the display language is not localized when changing the localization.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6933]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.12 P4 VAL (with Aspire 9.0.0)
3. Install latest Aspire 9.1.0-preview.1.24611.1

**REPRO STEPS**
1. Create .NET Aspire Starter App > .NET 9.0 (Standard Term Support) > Create
2. Build and F5
3. Click settings in Aspire dashboard > Change localization

**ACTUAL**
The description for changing the display language is not localized when changing the localization. 
![Image](https://github.com/user-attachments/assets/5e0469e4-8e38-46cf-96c3-1f90648547f7)

**EXPECTED**
After changing the display language, the "Language" tag and description should be localized.

**Comment by adamint** [comment]
Closing, as we are going to merge a dotnet-bot PR checking in localizations.

**Comment by v-reinawang** [comment]
Verify that this issue has been fixed in the latest Aspire 9.1.
