### ISSUE TITLE
[WebToolsE2E][Aspire] Changing the localization for display language in Aspire 9.1 dashboard, the string for new features in Console logs are not localized.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#6934]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2
2. Install VS 17.12 P4 VAL (with Aspire 9.0.0)
3. Install latest Aspire 9.1.0-preview.1.24611.1

**REPRO STEPS**
1. Create .NET Aspire Starter App > .NET 9.0 (Standard Term Support) > Create
2. Build and F5
3. Change the display language in Settings
4. Navigate to Console logs > Check the new added buttons

**NOTE**
1. This issue is reproduced with all the localized language included in Settings.

**ACTUAL**
1. Hover to stop button and check "Stop resource"
![Image](https://github.com/user-attachments/assets/bbb3e81d-e37a-4ebf-b1a7-a0753a843988)

2. Click the ellipsis button and check "Restart" 
![Image](https://github.com/user-attachments/assets/69c2c8cc-2837-41e6-be6d-509994512a00)

3. Hover to ellipsis button and check "Resource commands"
![Image](https://github.com/user-attachments/assets/b1441474-d38a-4e75-b47c-ed3ebaa79fcd)

4. Hover to settings icon in Console logs and check "Console log settings"
![Image](https://github.com/user-attachments/assets/d7bbb7ef-5bc5-4d4c-aaa4-91eb337f4248)

5. Click the settings icon in Console logs and cehck "Download logs/Hide timestamps"
![Image](https://github.com/user-attachments/assets/d804a29b-a4b0-408f-9ee5-6a2e56360a71)

**EXPECTED**
After changing the localization for displayed language, the mentioned strings should be localized.

**Comment by adamint** [comment]
Closing, as we are going to merge a dotnet-bot PR checking in localizations.
