### ISSUE TITLE
Add mongo db aspire component

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#694]
At a minimum via EF (https://devblogs.microsoft.com/dotnet/efcore-mongodb/) but also consider the non EF version

**Comment by josephaw1022** [comment]
Could the cosmos db emulator be utilized for this? 


![image](https://github.com/dotnet/aspire/assets/47674962/08f08223-7369-45dc-ad65-278f6cd3d577)


Like you could create a mongo db two ways


1. via the mongo image alone and utilize mongo express (more cloud native component)
 - this would essentially be what @mitchdenny  did in his pr 

2. Via the cosmos db emulator (more azure hosting component)
- similar to the way the way azurite is spun up via the useEmulator seen here https://github.com/dotnet/aspire/blob/60bd2b0b5c29ea02507265199070d4dac1fad712/src/Aspire.Hosting.Azure/AzureResourceExtensions.cs#L161

**Comment by davidfowl** [comment]
> Is it possible to use the Cosmos DB emulator for this purpose?

Possible yes? Do we want to no. I would treat the mongo support separate from cosmosdb support. 

> Using only the MongoDB image and leveraging Mongo Express, which aligns more with cloud-native components. This approach essentially mirrors what @mitchdenny implemented in his PR.

This is the approach we want to take, but we need to fix some things in the orchestrator to make this easier.

>Employing the Cosmos DB emulator, which is more akin to an Azure hosting component. This is similar to the way Azurite is initiated using useEmulator, as seen here: Aspire Hosting Azure Code.

This will be a different feature.

**Comment by mitchdenny** [comment]
I think this is done.
