### ISSUE TITLE
Add Temporal.io

### ISSUE THREAD

**Issue by NitroEvil** [dotnet/aspire#6973]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the solution you'd like

I'd like to know if Temporal.io would be considered to be added to the project as I feel it would be a good fit for Aspire based on, we have other similar tools that spin up a backend.

**Comment by davidfowl** [comment]
This wouldn’t be part of the core aspire. This might be a good candidate for the aspire community toolkit or for temporal to ship themselves.

Also this exists https://github.com/InfinityFlowApp/aspire-temporal

**Comment by NitroEvil** [comment]
Awesome, thanks for quick response.
