### ISSUE TITLE
Components - Create Zitadel IDP aspire component

### ISSUE THREAD

**Issue by MadL1me** [dotnet/aspire#6988]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

While the keycloak is widely used, there is some issues with it, especially in high load situations. There are a lot of different IDPs (Identitiy Providers), which can be used, with SDKs in dotnet as well (Auth0, LogTo, Authentic, etc)

The issues proposes adding component for one of the promising IDP, our company and many others using - [Zitadel](https://zitadel.com/). 

### Describe the solution you'd like

Add a new component for Zitadel Identity Provider, the way it is implemented for Keycloak

**Comment by davidfowl** [comment]
Consider submitting this as a proposal for the aspire community toolkit.
