### ISSUE TITLE
Remove `DcpHostService` and move logic into `DcpPublisher`.

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#70]
We don't want the `DcpHostService` being a background service anymore, we want it to be something we explicitly execute as a default publisher (similar to our earlier approach). We'll probably also want an extension method for the `IServiceCollection` to add Dcp and all its dependencies to DI.

**Comment by davidfowl** [comment]
Moving this to preview3. Preview2 will be focused on unblockers.
