### ISSUE TITLE
[WebToolsE2E][Aspire]After adding 'Aspire.Npgsql.EntityFrameworkCore.PostgreSQL' component and updating related codes, F5 failed with an exception: 'Some services are not able to be constructed ...'

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#744]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 from build [34307.189.d17.9] 
3. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web App(Razor Page) > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Right-click the Models folder > Add > Class, named Movie.cs and paste following codes:
```
	public class Movie
	{
	    public int ID { get; set; }
	    public string Title { get; set; } = string.Empty;
	    public DateTime ReleaseDate { get; set; }
	    public string Genre { get; set; } = string.Empty;
	    public decimal Price { get; set; }
	}
```
3. Right-click the Controllers folder > add > Controller > Mvc Controller with views, using Entity Framework:

    - Model class: Movies.cs
    - DbContext class: click '+' to create a new db context
    - Database provider: select PstgreSQL

4. Right-click the razor project > Add > Aspire component > Aspire.Npgsql.EntityFrameworkCore.PostgreSQL using matched version.
5. Open appsettings.json file under Razor project, type following codes:	
```
"Aspire": {
	    "Npgsql": {
	      "EntityFrameworkCore": {
	        "PostgreSQL": {
	          "DbContextPooling": true,
	          "HealthChecks": false,
	          "Tracing": false
	        }
	      }
	    }
	  }
```
6. Then open Program.cs of razor project, type following codes and replace with the DbContext created in step 3:
    `builder.AddNpgsqlDbContext<MyDbContext>("myConnection");`
7. Open appsettings.json of xxx.AppHost project, add following codes and replace with the connection string created in step 3:
```
"ConnectionStrings": {
	        "myConnection": "Host=myserver;Database=test"
	      }
```
8. Open Program.cs of xxx.AppHost project, add following codes:
```
var postgresdb = builder.AddPostgresContainer("pg").AddDatabase("postgresdb");

var myService = builder.AddProject<Projects.MyService>()
                       .WithReference(postgresdb);
```
9. F5

**ACTUAL**
F5 failed with an exception
![image](https://github.com/dotnet/aspire/assets/82028229/1313b844-b942-4a6e-b91b-58fa6644405d)
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.EntityFrameworkCore.Internal.IDbContextPool`1[WebApplication4.Data.WebApplication4Context] Lifetime: Singleton ImplementationType: Microsoft.EntityFrameworkCore.Internal.DbContextPool`1[WebApplication4.Data.WebApplication4Context]': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[WebApplication4.Data.WebApplication4Context]' from singleton 'Microsoft.EntityFrameworkCore.Internal.IDbContextPool`1[WebApplication4.Data.WebApplication4Context]'.) (Error while validating the service descriptor 'ServiceType: Microsoft.EntityFrameworkCore.Internal.IScopedDbContextLease`1[WebApplication4.Data.WebApplication4Context] Lifetime: Scoped ImplementationType: Microsoft.EntityFrameworkCore.Internal.ScopedDbContextLease`1[WebApplication4.Data.WebApplication4Context]': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[WebApplication4.Data.WebApplication4Context]' from singleton 'Microsoft.EntityFrameworkCore.Internal.IDbContextPool`1[WebApplication4.Data.WebApplication4Context]'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Users\v-cazhang\source\repos\WebApplication4\WebApplication4\Program.cs:line 14

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.EntityFrameworkCore.Internal.IDbContextPool`1[WebApplication4.Data.WebApplication4Context] Lifetime: Singleton ImplementationType: Microsoft.EntityFrameworkCore.Internal.DbContextPool`1[WebApplication4.Data.WebApplication4Context]': Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[WebApplication4.Data.WebApplication4Context]' from singleton 'Microsoft.EntityFrameworkCore.Internal.IDbContextPool`1[WebApplication4.Data.WebApplication4Context]'.

Inner Exception 2:
InvalidOperationException: Cannot consume scoped service 'Microsoft.EntityFrameworkCore.DbContextOptions`1[WebApplication4.Data.WebApplication4Context]' from singleton 'Microsoft.EntityFrameworkCore.Internal.IDbContextPool`1[WebApplication4.Data.WebApplication4Context]'.

**EXPECTED**
Running the solution succeed and can show the dashboard.

**Comment by eerhardt** [comment]
@DamianEdwards - how common do you imagine this scenario would happen? Is this something we should address soon?

**Comment by DamianEdwards** [comment]
Scaffolding use is pretty high, so I expect this will happen a lot. We could possibly update scaffolding to special-case detecting the Aspire methods, or we could look updating the Aspire methods to do runtime checks to better detect this situation and throw a helpful exception, perhaps only enabled when in development (another kind of DI validity check).

**Comment by DamianEdwards** [comment]
Yeah good point. It obviously doesn't scale to any other method that might be doing it under the covers but it seems like it's fair we should update our scaffolders to understand our top-level methods. Logged https://github.com/dotnet/Scaffolding/issues/2590 to track updating scaffolding.

**Comment by eerhardt** [comment]
@sebastienros - is this something you can handle in preview5? (since you did the EF API work in preview4). It should be simple enough to just check in the `AddXXXDbContext` methods (when the app is in "Development") if the DbContext has already been added to the DI container, and throw a useful exception.
