### ISSUE TITLE
[WebToolsE2E][Aspire] Click any option under 'Logs' on the dashboard, the selection locator's position will not change when collapse 'Logs'.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#754]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 from build [34307.189.d17.9]
3. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > .NET Aspire Starter Application > .NET 8.0 > Create
2. Ctrl F5
3. On the dashboard, click 'Executable' under 'Logs' 
4. Then collapse 'Logs'.

**ACTUAL**
The selection locator's position will not change accordingly, still remains in place.
![image](https://github.com/dotnet/aspire/assets/82028229/37cd4bab-3bd7-411b-b4b8-738a0c49bd84)
![image](https://github.com/dotnet/aspire/assets/82028229/5457ba40-0a01-4b9f-b750-91bcb5cd0021)

**EXPECTED**
Maybe should change to 'Logs'

**Comment by v-cazhang** [comment]
This issue doesn't repro on Aspire.ProjectTemplates.8.0.0-preview.2.23567.5.

**Comment by tlmii** [comment]
> After updating to Aspire.ProjectTemplates.8.0.0-preview.2.23567.5 from Aspire.ProjectTemplates.8.0.0-preview.1.23557.2, this issue doesn't repro.

Thanks @v-cazhang! Closing this issue per this update.
