### ISSUE TITLE
`AppHost` and `ServiceDefaults` projects are only created in the directory where the solution file is located

### ISSUE THREAD

**Issue by justinyoo** [dotnet/aspire#756]
Hi, Team.

When I create a front-end and back-end apps first and add Aspire orchestration projects later, both `AppHost` and `ServiceDefaults` projects are created and situated at the same level where the solution file is located.

## Repro

1. Create a solution file, `AspireSample.sln`, at the repository root, say `c:/dev/aspire-sample`.
2. Create a directory `src` under the repository root, that is `c:/dev/aspire-sample/src`
3. Create a Blazor app and Web API app under the `src` directory and link them to the solution file.
4. Add Aspire orchestration from the context menu of each Blazor app and Web API app project.
5. When a modal pops up, select `c:/dev/aspire-sample/src`, and create.
6. Both `AspireSample.AppHost` and `AspireSample.ServiceDefaults` projects are generated under `c:/dev/aspire-sample`.

## Expected

Both `AspireSample.AppHost` and `AspireSample.ServiceDefaults` projects should be generated under `c:/dev/aspire-sample/src`.

**Comment by phenning** [comment]
@BillHiebert I think you just made some changes to the dialog here which would impact this scenario where the user has a src folder that is a level below the sln file. 

Do we need to support this scenario via still being able to provide the path in the dialog?

**Comment by davidfowl** [comment]
@bradygaster can you make the call here?

**Comment by danmoseley** [comment]
@bradygaster  what do you prefer?

**Comment by joperezr** [comment]
Moving to Preview 5 in favor of removing milestone preview TBD.

**Comment by davidfowl** [comment]
Not sure this meets the p6 bar but putting it there.

**Comment by phenning** [comment]
This is now configurable as of 17.10 Preview 3, and we will also default to a src subfolder as well if the directory structure is such that there is a sln file, with a src subfolder and subfolders for each project under src.
