### ISSUE TITLE
High CPU when showing the logs view for an executable on the dashboard

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#760]
When viewing the streaming logs of an executable on the dashboard, the CPU use is very high and causes fans to spin up, etc. Navigating back to the dashboard home page returns CPU to low levels.

![image](https://github.com/dotnet/aspire/assets/249088/5241aaec-d7dc-4428-bd8b-2f15dfa2de68)

**Comment by DamianEdwards** [comment]
@dbreshears can we consider this for preview.2 please?

**Comment by dbreshears** [comment]
@DamianEdwards , considered for sure and prioritized startin soon, but I don't think this is likely to make Preview 2 due to an external change in the Tilt API server, followed by 1 to 2 weeks of work in DCP, then the dashboard work.

**Comment by drewnoakes** [comment]
@karolz-ms @dbreshears any update on the likelihood of this landing any time soon? I'm working on console log streaming over gRPC and have to change a bunch of stuff in this area. https://github.com/microsoft/usvc/issues/8 makes it look like this is in progress, so if it's close it would change how I approach that work.

**Comment by karolz-ms** [comment]
@drewnoakes we are targeting log streaming from DCP for preview3, but the confidence is medium, and it will certainly not arrive in the next couple of weeks if that is what you are asking about.
