### ISSUE TITLE
Aspire.Hosting OTLP endpoint injection improvements

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#764]
The `Aspire.Hosting` OTLP endpoint injection logic should be updated to handle the following:

- Assign a random, unused port each time, rather than a hard-coded port.  A port in consistent range outside the typical ranges used for new app projects, e.g. 18900-18999, should be considered.
- Configure the OTLP endpoint to use HTTPS when the dashboard itself is listening on HTTPS. That way, when the user selects HTTPS as the launch profile, all communications in the Aspire app are HTTPS.
- Remove the environment variable definition for `DOTNET_DASHBOARD_OTLP_ENDPOINT_URL` in the Aspire templates *launchSettings.json* files, as they shouldn't be required after these changes.

See https://github.com/dotnet/astra/pull/587#discussion_r1336169357 for original context.

**Comment by smitpatel** [comment]
Out of 3 points mentioned above, 2nd is already done in main.
We need to assign random port to projects for OTLP endpoint and remove it from launchsettings file. Let's look into triage who would do the port assignment.

**Comment by davidfowl** [comment]
We did this!
