### ISSUE TITLE
workaround for startup delay when debugging

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#766]

**Comment by jack775544** [comment]
How do you actually debug an aspire application in the first place? I have created a new project using the aspire-starter dotnet new template but my breakpoints will only get hit in the app host project and not in any of the other projects (says the symbols are missing). Is there some IDE side setup required to enable proper debugging in Aspire projects?

**Comment by danegsta** [comment]
@jack775544 are you debugging using Visual Studio 2022 17.9 Preview 1? The Visual Studio tooling for Aspire (including automatic multiple service debugging) is only available in 17.9 Preview builds currently, not the 17.8 GA release.

**Comment by jack775544** [comment]
@danegsta Ahh that would make sense. I was using 17.8, I didn't realise debugging would require a newer version of Visual Studio as well.

On that note, is there any workaround for people not using Visual Studio (eg. using VSCode or Rider) or is debugging Aspire applications going to have to be explicitly supported by the IDE for it to work.

**Comment by davidfowl** [comment]
Debugger support requires work in the IDE https://github.com/dotnet/aspire/blob/main/docs/specs/IDE-execution.md

**Comment by danmoseley** [comment]
@jack775544 I opened https://github.com/dotnet/aspire/issues/845 to address your feedback. thanks!

**Comment by davidfowl** [comment]
@vijayrkn Can you follow up on this issue and close this bug if there's nothing else we need to do?

**Comment by danmoseley** [comment]
@vijayrkn ?

**Comment by BillHiebert** [comment]
@danmoseley the VS bug on this was fixed by @auott in 17.9.
