### ISSUE TITLE
Errors and logging for app model

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#767]
We desperately need to improve the nature of our error messages that we produce via exceptions and the way that we present them via logging for the application builder.

At the moment the cloud app model itself is in DI, but individual components/annotations are not. The key thing that we need to log is once the app model is handed over to the publishing target. So the main hosting code and the publishing targets need to get a logger and pass them to things like transformers where appropriate.

**Comment by stbau04** [comment]
@mitchdenny Is this task still up to date? What error messages do you mean exactly? Where are they thrown/logged?
I think i could spend some time on this one, but i am not sure what's the goal of it

**Comment by davidfowl** [comment]
I'm going to close this as its too vague We can do clean up as we refactor.
