### ISSUE TITLE
The MSBuild Output Items of the GenerateAspireManifest target aren't usable by other MSBuild logic

### ISSUE THREAD

**Issue by baronfel** [dotnet/aspire#774]
https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/build/Aspire.Hosting.targets#L111

We return the relative (intermediate) path from a project to the manifest for that project, but when calling this target from other logic we don't have a sense of the 'root' that we should use to construct an absolute path - for example to read the file and do something with it.

**Comment by gpproton** [comment]
I was considering trying this out on one of my project but the manifest can't publish project directly as docker image and maybe using docker compose.
Aspire is really a great project and i want to use it as soon as possible, but the publishing restriction to AKS is an issue for me.

**Comment by timheuer** [comment]
> but the publishing restriction to AKS is an issue for me

Can you explain what you mean by this where you are seeing a restriction being this explicit?

**Comment by davidfowl** [comment]
@gpproton This issue about the manifest itself, not publishing the application somewhere.

**Comment by baronfel** [comment]
I updated the title to hopefully be a bit more clear.

**Comment by danmoseley** [comment]
@baronfel @rainersigwald can you help set timeline expectations here?
