### ISSUE TITLE
Add support for expressing existing external HTTP services as resources in the hosting project

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#775]
Scenario is I have an external HTTP service that I want to connect to (similar to an existing Redis instance or existing PostgreSQL instance)  so I want to model it in my hosting project so that other resources can reference it and have service discovery configured so they can refer to it by the name I give it.

e.g.
 **MyApp.AppHost/Program.cs**
```csharp
var builder = DistributedApplication.CreateBuilder(args);

var weatherApi = builder.AddHttpService("weatherapi", "http://weather.internal.sda76erh.us.contoso.com");

builder.AddProject<Projects.Frontend>("frontend")
    .WithReference(weatherApi);

builder.Build().Run();
```

**MyApp.Frontend/Program.cs**
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();

builder.Services.AddHttpClient("weather", c => c.BaseAddress = new("http://weatherapi"));

var app = builder.Build();

app.MapGet("/", async (IHttpClientFactory hcf) => await hcf.CreateClient("weather").GetStringAsync("/weatherforecast"));

app.MapDefaultEndpoints();

app.Run();
```

**Comment by Kahbazi** [comment]
I'm interested in sending a PR for this issue. Could you assign this to me please?

These are the steps that I know that has to be done

- Add `HttpService` in `IDistributedApplicationBuilder.Resources`. 
- Write the resource in `ManifestPublisher`.
- Somehow make the Service Discovery works (I haven't figure this out yet!)


_BTW the description for 'help wanted' label seems wrong!_

**Comment by DamianEdwards** [comment]
@Kahbazi that'd be great! For service discovery the resource needs to have `ServiceBindingAnnotation` added that describes the details. We'd love to include this in preview.2 if you're able to contribute this within the next two weeks. Please let us know if you need any other help.

**Comment by mitchdenny** [comment]
We'd probably want this to behave more like something that participates in service discovery than a connection string.

**Comment by DamianEdwards** [comment]
> We'd probably want this to behave more like something that participates in service discovery than a connection string.

Right, is that not what adding a `ServiceBindingAnnotation` does?

**Comment by Kahbazi** [comment]
@DamianEdwards Is there any API Review process for this project or I just add the APIs that I think is needed and we would discuss them in the PR? I will send a draft PR before the weekend to make sure that this could be in preview 2.

**Comment by DamianEdwards** [comment]
@Kahbazi send the PR and we can discuss there, thanks!
