### ISSUE TITLE
Add support for an AppInsights azure resource

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#778]
Add an `AppInsightsResource` and associated provisioner. The resource type should be "azure.appinsights.v0".

**Comment by mitchdenny** [comment]
What is the goal of having the app insights resource? Is it to get the instrumentation key so you can inject it into the application?

**Comment by davidfowl** [comment]
Provisioning AI, to push telemetry to in azure prod scenarios.

**Comment by mitchdenny** [comment]
We could either model log analytics first, or model AppInsights and then AZD can ask the user if they want to link the AI instance with Log Analytics that it creates by default. In theory Log Analytics can be treated like a Kusto data source so there is potentially some value there.
