### ISSUE TITLE
Add Azure Cognitive Search Aspire Component

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#794]
We should have an Azure Cognitive Search component. See https://learn.microsoft.com/azure/search/

See https://www.nuget.org/packages/Azure.Search.Documents/

**Comment by levimatheri** [comment]
@eerhardt I'd be interested in taking this up, thanks.

**Comment by eerhardt** [comment]
@levimatheri - that would be great! Our hope is that this should be a lot like the Azure OpenAI component - see https://github.com/dotnet/aspire/pull/1475.

@tg-msft @sebastienros - anything in particular to be aware for Azure AI Search?

**Comment by sebastienros** [comment]
I also think it should look like Open Ai. One difference might be the connection that we made up. If AI Search doesn't have a connection string then it will be the same.
Deployments in Open AI should be equivalent to Indexes in AI Search. And maybe AI Search has a package for provisioning, which would be extra compare to Open AI.

**Comment by levimatheri** [comment]
@sebastienros One thing I realized is that `SearchClient` requires an `indexName`. In terms of the `ConnectionStrings` for Aspire, was wondering how to define this. What do you think about the following:

_With API Key_
```json
{
  "ConnectionStrings": {
    "aiSearchConnectionName": "Endpoint=https://{search_service}.search.windows.net/;IndexName={index_name};Key={account_key}"
  }
}
```

_With `TokenCredential`_:
```json
{
  "ConnectionStrings": {
    "aiSearchConnectionName": "Endpoint=https://{search_service}.search.windows.net/;IndexName={index_name}"
  }
}
```

So I don't think we can have _just_ the account endpoint since index name has to come along, i.e. this wouldn't be sufficient(?)
```json
{
  "ConnectionStrings": {
    "aiSearchConnectionName": "https://{search_service}.search.windows.net/"
  }
}
```

**Comment by sebastienros** [comment]
@levimatheri That's fine assume [this issue](https://github.com/dotnet/aspire/issues/1765) and the fact that we'll have to change it once it's implemented. And you confirm that AI search has no concept of connection string then?

**Comment by pedershk** [comment]
> @sebastienros One thing I realized is that `SearchClient` requires an `indexName`. In terms of the `ConnectionStrings` for Aspire, was wondering how to define this. What do you think about the following:

How does this play with applications that connect to multiple indexes? I believe this is a very common scenario (same as different models/deployments/instances with Azure OpenAI). Is [_Keyed DI Services_](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#keyed-di-services) now a thing in Aspire, or is every component still registered as a singleton in DI, without naming, hence blocking multiple connections to different services of the same type?

**Comment by levimatheri** [comment]
@pedershk There's an option to add Keyed component, see [OpenAI component](https://github.com/dotnet/aspire/blob/d86d905479547cf28f113ab6b9352a475cd74ffb/src/Components/Aspire.Azure.AI.OpenAI/AspireAzureOpenAIExtensions.cs#L49) for example.

**Comment by eerhardt** [comment]
I think the initial version of the Aspire Azure AI Search component would just register a [SearchIndexClient](https://learn.microsoft.com/dotnet/api/azure.search.documents.indexes.searchindexclient) as a singleton in DI. Then users can grab that out and call `GetSearchClient(string indexName)` in their app to be able to interact with the specific index.

This gives the users the most flexibility - they don't put index names in the connection information. And they can use different indexes if need be.

If they want to build a Keyed DI service over top of this, it would be very simple. Something like:

```C#
builder.Services.AddKeyedSingleton(KeyedService.AnyKey, static (sp, key) =>
{    
    var searchIndexClient = sp.GetRequiredService<SearchIndexClient>();
    return searchIndexClient.GetSearchClient((string)key);
});
```

And then in their app, they can just get a `[FromKeyedServices("indexName"] SearchClient client` when they want a SearchClient for the "indexName" index.

**Comment by levimatheri** [comment]
Makes sense, thanks

**Comment by levimatheri** [comment]
@eerhardt any idea why `SearchIndexClient` is not emitting any `ActivitySource` and failing [this test](https://github.com/dotnet/aspire/blob/c719174d0b59c6787dd3c9f0f6cf37f2c77bafa7/tests/Aspire.Components.Common.Tests/ConformanceTests.cs#L405)? Is there something specific I'm supposed to add on Aspire to get it return exported activities? Here's my [branch](https://github.com/levimatheri/aspire/tree/levimatheri/feat/azure-cognitive-search).

**Comment by levimatheri** [comment]
I encountered an issue trying to set up the provisioner for AI Search, it can't seem to find `Azure.ResourceManager.Search` in any of the feeds. Seeing the following error:

```
Unable to find package Azure.ResourceManager.Search. No packages exist with this id in source(s): dotnet-eng, dotnet-public, dotnet8
```

**Comment by sebastienros** [comment]
Fixing it, we need to add it to our internal feed. Should take a few minutes.

**Comment by levimatheri** [comment]
@sebastienros any luck? I'm still not able to find the package.

**Comment by sebastienros** [comment]
I added Azure.ResourceManager.Search version 1.2.1 and I can see that the pipeline worked, but I can't find it in the feed either. Will try again.

**Comment by sebastienros** [comment]
It should be ok now, I think I chose the wrong option the first time as it's a new package on the feed.

https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/azure.resourcemanager.search/index.json

**Comment by eerhardt** [comment]
Completed with #2070.
