### ISSUE TITLE
Add Qdrant Aspire Component

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#795]
We should make an Aspire Component for working with a Qdrant vector database.

See https://www.nuget.org/packages/Qdrant.Client/.

We should make sure that the Aspire Qdrant Component integrates well with [Semantic Kernel](https://github.com/microsoft/semantic-kernel). See also https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.Memory.Qdrant/

**Comment by glennc** [comment]
We should have a resource for Qdrant as well, should we have a separate issue for that or merge them into one?

**Comment by davidfowl** [comment]
They typically happen at the same time

**Comment by timheuer** [comment]
I actually started on a qdrant resource one last night...I can contribute maybe a starting point...

**Comment by davidfowl** [comment]
You're a dev now @timheuer

**Comment by glennc** [comment]
I have created a couple of throwaway ones for this as well @timheuer happy to look over yours and get it together :)

**Comment by timheuer** [comment]
> I have created a couple of throwaway ones for this as well @timheuer happy to look over yours and get it together :)

PR: https://github.com/dotnet/aspire/pull/3131

**Comment by eerhardt** [comment]
Completed with https://github.com/dotnet/aspire/pull/3131.
