### ISSUE TITLE
Add Azure SignalR Aspire Component

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#799]
We should add an Azure SignalR Component. See https://learn.microsoft.com/azure/azure-signalr/

See https://www.nuget.org/packages/Microsoft.Azure.SignalR

**Comment by vicancy** [comment]
The Microsoft.Azure.SignalR already contains a `AddAzureSignalR` method, and it is called after `AddSignalR`.  how about adding the ability to read from `connectionName` into `Microsoft.Azure.SignalR` instead, maybe `AddAzureSignalRWithConnectionName(this ISignalRServerBuilder builder, string connectionName)`?

The host and provisioning part for Azure SignalR is missing too, is there a plan to add the support? I am happy to contribute to that.

**Comment by davidfowl** [comment]
That sounds ideal @vicancy !

**Comment by vicancy** [comment]
Hi @eerhardt could you help add [Azure.ResourceManager.SignalR](https://www.nuget.org/packages/Azure.ResourceManager.SignalR) to the nuget source? This is the control plane SDK package for Azure SignalR.

**Comment by eerhardt** [comment]
> Hi @eerhardt could you help add [Azure.ResourceManager.SignalR](https://www.nuget.org/packages/Azure.ResourceManager.SignalR) to the nuget source? This is the control plane SDK package for Azure SignalR.

Running now. It should be done in a few minutes. Let me know if there are more you need added.

**Comment by davidfowl** [comment]
We're going to have this by preview4 thanks to @vicancy
