### ISSUE TITLE
Support working with Podman in addition to Docker

### ISSUE THREAD

**Issue by pakbaz** [dotnet/aspire#827]
Podman is an alternative to Docker with the same exact commands. aspire should support Podman instead of forcing to use docker as default containerization. Also, since Podman has full docker desktop compatibility this should be a fairly straight forward feature to add.

**Comment by pakbaz** [comment]
Through enabling docker compatibility this is not a problem for now

**Comment by DamianEdwards** [comment]
Going to re-open this as first-class support for Podman could still be interesting and would be good to get an indication of how important folks think it is.

**Comment by davidfowl** [comment]
cc @karolz-ms 😄

**Comment by karolz-ms** [comment]
@DamianEdwards what does "first class support for Podman" should mean, in practice? 

cc @tmds

**Comment by mkane91301** [comment]
Additionally, to be able to use any of the free OCI container runners (including docker) in WSL2 with port forwarding rather than needing to install any Windows app. In my company, this is the approved way of doing container development on Windows while running containers via a Windows app is not approved.

**Comment by DamianEdwards** [comment]
@karolz-ms I admit I'm ignorant of details but I imagine launching `podman` instead of `docker` would be a start, perhaps like:

```csharp
var builder = DistributedApplicationBuilder.Create();

// Use Podman for all containers
builder.UsePodman();

// Use Podman for a specific container resource
builder.AddRedisContainer("redis").UsePodman();

...
```

@mkane91301 Docker defaults to WSL2 on Windows these days, can you elaborate a bit more on what you mean? Is it that you don't want to install anything in Windows, but rather have the container host be in WSL2 itself, and have Aspire support directly running containers in WSL2 via various container runners?

**Comment by mkane91301** [comment]
> @mkane91301 Docker defaults to WSL2 on Windows these days, can you elaborate a bit more on what you mean? Is it that you don't want to install anything in Windows, but rather have the container host be in WSL2 itself, and have Aspire support directly running containers in WSL2 via various container runners?

That is 100% exactly what I mean!

**Comment by spboyer** [comment]
@DamianEdwards 
```
// Use Podman for all containers
builder.UseContainers();

// Use Podman for a specific container resource
builder.AddRedisContainer("redis").UseContainers();
```
I'd propose that we'd go with a `UseContainers` approach and have whatever container runtime is configured on the machine handle the calls.  This way Aspire can stay generic and not have to implement any API diffs to various runtimes.

**Comment by davidfowl** [comment]
Is this a switching thing? Why not make it global? What's the scenario for switching on a per container basis?

**Comment by tmds** [comment]
First class support for `podman` means it _just works_ on a system that has `podman` installed instead of `docker`.

When both `podman` and `docker` are installed, the tooling can prefer to use `docker` but there should be an opt-in for `podman`.

It should be a global thing, that is: all containers meant to be working together should be ran by the same container host.
I don't think there's reasons to make it per container. It would be more complex, and impose limitations on how the containers can interact.

**Comment by karolz-ms** [comment]
@mkane91301 what is the container runtime/CLI you are using inside WSL, most often?

**Comment by mkane91301** [comment]
> @mkane91301 what is the container runtime/CLI you are using inside WSL, most often?

Docker

**Comment by gorrilla10101** [comment]
I was coming to create a separate but similar issue. It's close enough related that I am going to put it here. I will happily move it if needed. 

It currently requires docker desktop specifically. I run rancher desktop with docker and it still won't run.

**Comment by WeihanLi** [comment]
Maybe we need a contain abstraction so that we could support different container runtimes across `docker`/`podman`/`containerd` etc

docker commands we used for now:

```sh
docker container inspect --format="{{json .Config.Env}}" <containerId>
podman container inspect --format="{{json .Config.Env}}" <containerId>

docker logs --follow -t <containerId>
podman logs --follow -t <containerId>

# https://docs.docker.com/engine/reference/commandline/ps/
docker ps --latest --quiet

# less `--latest` support (This option is not available with the remote Podman client, including Mac and Windows (excluding WSL2) machines)
# https://docs.podman.io/en/latest/markdown/podman-ps.1.html#latest-l
podman ps --quiet 
```

**Comment by tmds** [comment]
> `--latest`

This option is meant for users to have an easy way to refer to the last container they created.

As you are orchestrating containers from aspire, it's best to use the container id explicitly to avoid using a container that got created by something else (outside of aspire).

> Maybe we need a contain abstraction so that we could support different container runtimes across docker/podman/containerd etc

I can help to implement/test this.

**Comment by davidfowl** [comment]
That feels like premature abstraction to me. Do we feel like there are enough container runtimes being used on local machines to make that investment worthwhile?

**Comment by WeihanLi** [comment]
Since the docker desktop license changed since 4.0, a license may be required, though it may not a big deal for most users, we could still use the docker engine.

- https://docs.docker.com/desktop/release-notes/#400
- https://docs.docker.com/subscription/desktop-license/

Some of us would prefer using podman as a replacement.

For local dev purpose, most of us use only one container runtime, while some use the docker desktop, others use the podman & podman desktop, it's necessary to support podman from my side

Just some usage around me, let's see more cases from others

**Comment by davidfowl** [comment]
I agree, I think docker and podman are what we should support, other container runtimes can wait until we have proof there's significant enough usage (for development) to matter.

**Comment by mkane91301** [comment]
> Since the docker desktop license changed since 4.0, a license may be required, though it may not a big deal for most users, we could still use the docker engine.

The license is an ENORMOUS issue. It’s a total dealbreaker in my company. A Docker Desktop license is completely out of the question. The only option we’re given is the free docker daemon running in WSL2.

**Comment by WeihanLi** [comment]
Hi @davidfowl , I tried to add podman support, I could startup now, while the container still create failed

https://github.com/dotnet/aspire/compare/main...WeihanLi:podman-support?expand=1

![image](https://github.com/dotnet/aspire/assets/7604648/419bc5b2-1bfd-4d10-8238-84787e28cc55)

and I tried to search the log category and error msg, seemed there're more places outside of the codebase that using the `docker` directly? Anything I missed?

**Comment by davidfowl** [comment]
Yes there’s another component that needs to change that isn’t part of this code base.

**Comment by riverar** [comment]
Docker Desktop has restrictive licensing and is unusable for commercial development environments. Podman, containerd, etc. support would be great!

**Comment by danmoseley** [comment]
cc @baronfel who is interested in podman from SDK side

**Comment by tmds** [comment]
> who is interested in podman from SDK side

We've added support for Podman to the SDK container tooling as part of .NET 8.

**Comment by mkane91301** [comment]
Will this issue be coordinated with this issue: https://developercommunity.visualstudio.com/t/Visual-Studio-Container-tools-depend-on-/1537846#T-ND10537030

**Comment by biqas** [comment]
How can i run/configure Aspire on Windows where Windows is installed on a Mac on Parallels and Docker or Podman is running on Mac?

**Comment by karolz-ms** [comment]
Aspire is using Docker CLI, so as long as Docker CLI is functional within the OS where Aspire app is running, it should work.

**Comment by jamiebarrow** [comment]
Just adding some information. A suggestion mentioned in the Developer Community thread referenced above suggests creating a symlink of `docker.exe` pointing to `podman.exe` but alas this isn't a valid workaround. I receive the message below and the Aspire project doesn't run (tried with the eShop solution).

> Docker was found but appears to be unhealthy. Exit code for 'docker ps --latest --quiet' was 125.

Looking forward to "first class citizen" support of Podman :)

**Comment by davidfowl** [comment]
I've seen it working 😄

**Comment by tmds** [comment]
@danegsta https://github.com/dotnet/aspire/pull/2217 requires the user to set an envvar or pass an argument to make Aspire use Podman instead of Docker.

Can we make it so that when a system has `podman` and not `docker`, Aspire _just works_ and does not require any intervention from the user?

We've done this for the .NET 8 SDK container tooling. You can probably re-use some of that logic.

**Comment by danegsta** [comment]
We should be able to do that detection logic in the orchestrator if a runtime isn’t selected, without needing to make additional changes in the Aspire hosting layer.

**Comment by tmds** [comment]
This is what the SDK is doing: https://github.com/dotnet/sdk/blob/bc0fd0171338a01ca2377f1919a1474f017fbf93/src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs#L280-L314

**Comment by danegsta** [comment]
I'm definitely going to be borrowing the podman alias detection logic from the SDK.

**Comment by danegsta** [comment]
Just made the relevant change to pick an available runtime in the orchestrator; it'll flow into Aspire in the next insertion.

**Comment by danegsta** [comment]
Aspire now supports running containers with either Docker or Podman; you can force a specific runtime by passing the `—container-runtime` flag when running the AppHost from the command line or setting the `DOTNET_ASPIRE_CONTAINER_RUNTIME` environment variable (supported values for both are `docker` or `podman`). If no specific runtime is specified, we’ll select from the supported runtimes available on the current machine (defaulting to Docker if both Podman and Docker are installed and running).

**Comment by danegsta** [comment]
The current implementation uses the standard CLI for a given runtime (docker or podman) and requires it to be available on PATH. We have some detection for scenarios where the Docker CLI is an alias to another runtime and should ignore it in favor of Podman in that case.

**Comment by tmds** [comment]
Awesome, thank you!

**Comment by davidfowl** [comment]
@tmds can you put this through its paces before we ship? We have a week of validation next week so it would be great for you to play with it and report any issues so we can fix them.

**Comment by tmds** [comment]
I can't promise I'll get to it this week.
I'll definitely be trying it out on the short term, and help flush out podman issues (if there are any).

**Comment by davidfowl** [comment]
No problem

**Comment by jamiebarrow** [comment]
Linking to the preview 4 docs :)

https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-4#podman-support

**Comment by davidfowl** [comment]
Also check the known issues section. We’re still improving the podman support and there are gaps
