### ISSUE TITLE
How to attach the debugger to a service without Visual Studio?

### ISSUE THREAD

**Issue by Kralizek** [dotnet/aspire#834]
I'm trying to hit a breakpoint in a service while working with Rider.

I tried the following but never managed to get the breakpoint to work
- Debug the AppHost project from the UI
- Run AppHost from the console and attach the AppHost process (couldn't see the processes for other services)

**Comment by mwgustin** [comment]
Same question for VS Code + C# Dev Kit too.

**Comment by rudiv** [comment]
IDE Integration is required - [this is the only issue](https://youtrack.jetbrains.com/issue/RIDER-101760/.NET-Aspire-support) in Rider repo I could find on Aspire.

**Comment by PShipstone** [comment]
Hitting the breakpoint also seems to also be an issue with within Visual Studio.  This is my experience when running the [AspireWithDapr](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithDapr) sample.

![image](https://github.com/dotnet/aspire/assets/44038179/9fc77786-0202-44cb-ada4-2cd86ad15cba)

Can attach the debugger manually via "Debug > Attach to process" and selecting the required application, in my case the Dapr API Service.

![image](https://github.com/dotnet/aspire/assets/44038179/9ce000b1-c7bf-44cd-b23b-c17d86f046a9)

**Comment by DamianEdwards** [comment]
@PShipstone what version of Visual Studio are you using? Debugging all orchestrated projects when launching the AppHost project requires Visual Studio 2022 17.9 preview 1

**Comment by andi0b** [comment]
> IDE Integration is required - [this is the only issue](https://youtrack.jetbrains.com/issue/RIDER-101760/.NET-Aspire-support) in Rider repo I could find on Aspire.

Everyone who is interested in rider support should probably upvote this issue in the jetbrains bug tracker.

**Comment by thiagomaia971** [comment]
Any progress with this?

**Comment by Kralizek** [comment]
Personally, I opened the issue just to receive guidelines regardless the best approach to debug a project hosted in Aspire.

As I mentioned in the opening post, I didn't see any process for the projects and attaching to the AppHost.exe process didn't mark the debugger as attached.

So the question is:
Does a Aspire application require special arrangements from the IDE for a debug experience?

**Comment by Kralizek** [comment]
oh, here they are!

![image](https://github.com/dotnet/aspire/assets/2458439/264e6b86-b95a-4a2e-b401-50c80da6c3ec)

Thanks for the clarification!
