### ISSUE TITLE
How to get reload to work outside of Visual Studio?

### ISSUE THREAD

**Issue by Kralizek** [dotnet/aspire#835]
I'm trying to get my services reloaded automatically while working with JetBrains Rider.

I've tried the following:
- Used the [.NET Watch Run plugin](https://plugins.jetbrains.com/plugin/17951--net-watch-run-configuration). Nope.
- Started `dotnet watch run --project ./src/AppHost/`. Nope.

**Comment by DamianEdwards** [comment]
'dotnet watch' works from the command line but will tear down more than required until it's updated to implement the launch semantics. Same goes for Rider.

**Comment by Kralizek** [comment]
Just an update here: as far as I see, using `dotnet watch --project AppHost run` doesn't restart resource projects when modified. It works hitting CTRL+R on the terminal, but I would love the same experience as in `tye run --watch`

**Comment by Kralizek** [comment]
Projects are actually reloaded but some visual cue when a project is reloaded/restarted in the AppHost log would be a nice thing to have.

**Comment by DamianEdwards** [comment]
`dotnet watch` is being updated to better hand Aspire AppHost projects: https://github.com/dotnet/sdk/issues/36971

**Comment by ctolkien** [comment]
Is reload supposed to work even within VS right now? We're having to explicitly build again (which restarts all services)

**Comment by DamianEdwards** [comment]
It depends on what one means by reload. Hot Reload works for supported changes in the app projects but not in the AppHost project. Auto-rebuild and restart of app projects works in VS for app projects when launching without debugging but changes to the AppHost will cause all apps to restart. dotnet watch has been updated to better support Aspire scenarios and will be available in the .NET 9 SDK I believe.

This is a complicated problem which we will continue to make progress on release to release.

**Comment by DamianEdwards** [comment]
Aspire 8.1 added more logging in the AppHost project in that it now forwards logs from the resources being orchestrated. You can of course adjust the logging levels and filters too to see more logs.

**Comment by DamianEdwards** [comment]
> This message does not appear to be a standard ILogger format message.

Correct. That message is emitted by `dotnet watch` itself, not your applications.

> I'll test again with the .NET 9 SDK to compare. I'll need to wait until I'm on my home account for that.

I believe this should work in the .NET 9 SDK as it has the `dotnet watch` updates, right @davidfowl?

**Comment by davidfowl** [comment]
The work isn't in yet. It's still in a pull request. Track https://github.com/dotnet/sdk/issues/36971
