### ISSUE TITLE
[WebToolsE2E][Aspire] After adding Aspire.Microsoft.EntityFrameworkCore.Cosmos, add related code to the program.cs shows error: There is no argument given that corresponds to the required parameter 'databaseName' ...

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#873]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web App (Model-View-Controller) > .NET 8.0 > none > check 'Enlist in Aspire Orchestration' > Create.
2. Right-click the Models folder and add a new class file named Movie.cs, paste following codes:
```
public class Movie
	{
	    public int ID { get; set; }
	    public string Title { get; set; } = string.Empty;
	    public DateTime ReleaseDate { get; set; }
	    public string Genre { get; set; } = string.Empty;
	    public decimal Price { get; set; }
	}
```
3. Right-click the Controllers folder > Add > Controller > MVC Controller with views, using Entity Framework

    - Model class: Movies.cs
    - DbContext class: click '+' to create a new db context
    - Database provider: select Azure Cosmos DB

4. Right-click web project > Add > Aspire component > Aspire.Microsoft.EntityFrameworkCore.Cosmos > install
5. Open appsettings.json file of web project, add following codes:
```
"Aspire": {
	    "Microsoft": {
	      "EntityFrameworkCore": {
	        "Cosmos": {
	          "DbContextPooling": true,
	          "Tracing": false
	        }
	      }
	    }
	  }
```
7. Open Program.cs file of web project, add following code:
`builder.AddCosmosDbContext<MyDbContext>("myConnection");`

**ACTUAL**
Shows error under 'AddCosmosDbContext<MyDbContext>;':
There is no argument given that corresponds to the required parameter 'databaseName' of 'AspireAzureEFCoreCosmosDBExtensions.AddCosmosDbContext<TContext>(IHostApplicationBuilder, string, string, Action<EntityFrameworkCoreCosmosDBSettings>?, Action<DbContextOptionsBuilder>?)'
![image](https://github.com/dotnet/aspire/assets/82028229/bf25fe26-42c4-4655-b3fe-ccd8f66e4e33)

**Notes**:

1. According to the error message, change 'builder.AddCosmosDbContext<MyDbContext>("myConnection");' to 'builder.AddCosmosDbContext<MyDbContext>("myConnection"; "myConnection");', the error will disappear.
![image](https://github.com/dotnet/aspire/assets/82028229/67223456-705b-4ac8-8678-a51d94929712)

**EXPECTED**
No error shows

**Comment by Pilchie** [comment]
How do you expect Entity Framework to know what database name to use if you don't specify one?

**Comment by eerhardt** [comment]
@Pilchie - looks like we need to update the README for CosmosDB EF:

https://github.com/dotnet/aspire/blob/b6fd5fd42f0642940e8c97369c56ddb1c0828c91/src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/README.md?plain=1#L19-L25

Just following this README doesn't work.
