### ISSUE TITLE
AppHost lifetime should be separated from Dashboard lifetime

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#887]
Currently when running the AppHost project, the dashboard is hosted within the AppHost process. This means that when the AppHost project stops or restarts, the dashboard state is lost.

We should separate the AppHost and dashboard so that their lifetime is not tied. This will help contribute to other scenarios involving running the dashboard outside the AppHost and developer inner-loop too, e.g. #847, #846,

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/aspire/issues/1003
