### ISSUE TITLE
Dashboard plugins via nuget or project reference

### ISSUE THREAD

**Issue by aL3891** [dotnet/aspire#922]
It would be really cool to be able to make custom views for the dashboard and supply them via either a project reference or a nuget package (or just directly in the apphost i suppose). i suppose they'd be registered as part of DI in the actual apphost

This way you could supply domain specific views for telemetry data, or just custom tools to call things in your services for example

**Comment by davidfowl** [comment]
While this is very cool, we don’t want to get into the world of pluggable UI. It would be great if somebody forked the dashboard to do this work but it’s not going to be a priority for the team.

**Comment by aL3891** [comment]
Even if the actual ui isnt extensible, (like passing in a blazor component or something) perhaps a smaller scope alternative would be to register some sort of ICustomDashboardAction class with an attribute for where in the dashboard menu it would show up, that way you could toss in tools to do actions in your solution without creating a whole custom app to do it. 

I guess it could be even more constrained where you could either look at the swagger data for each service and generate a ui to call the service, or supply interface implementations that take a httpclient and return a response (or just poco instance) to be rendered.

I think it would be very handy to be able to call your services from the dashboard essentially

**Comment by davidfowl** [comment]
I love the idea, it just doesn't align with any short-term goals we have (v1). We're on a pretty tight schedule and features like this must be self-driven because the team has to build out support for other things (dotnet watch, vs code etc etc)

**Comment by aL3891** [comment]
No worries, i'll try to take a crack it to get a small prototype going that might be used for as a starting point post v1 :) 

Again, great to see something project tye evolve into more of a product!
