### ISSUE TITLE
https://aka.ms/aspire/1.0-third-party-notices redirects to Bing

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/aspire#924]
```
$ dotnet workload list

Installed Workload Id      Manifest Version                     Installation Source
-----------------------------------------------------------------------------------
aspire                     8.0.0-preview.1.23557.2/8.0.100      SDK 8.0.100

Use `dotnet workload search` to find additional workloads to install.

$ dotnet new aspire-starter
The template ".NET Aspire Starter Application" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspire/1.0-third-party-notices for details.
```

But the <https://aka.ms/aspire/1.0-third-party-notices> link redirects to <https://www.bing.com?ref=aka&shorturl=aspire/1.0-third-party-notices>, which does not display any third-party notices for .NET Aspire.

According to <https://github.com/dotnet/aspire/pull/670#issue-1975020529>, it should redirect to <https://github.com/dotnet/aspire/blob/main/THIRD-PARTY-NOTICES.TXT>…?  I don't understand the "1.0" in the aka.ms URL though, when .NET Aspire itself has a 8.0.0-preview.1 version number.

**Comment by DamianEdwards** [comment]
This is fixed now.
