### ISSUE TITLE
Dapr Sidecar resource name should not be appId

### ISSUE THREAD

**Issue by mile-abrettschneider** [dotnet/aspire#926]
Hi,

Aspire is really great so far!
Can't wait to use it in real projects!

While testing I noticed that the dapr sidecar that gets created with "WithDaprSidecar" is named by the appId.

This causes issues in a case like this:
```
builder.AddProject<Projects.App>("app")
    .WithDaprSidecar("app")
```

I would like my app to be available via http://app but also via dapr invocation when calling "app". Currently this configuration fails cause a resource with name "app" was already added.
I think it would be better if the sidecar executable resource would be called "{appId}-dapr" instead of just "{appId}".

https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs#L119

**Comment by davidfowl** [comment]
cc @philliphoff

**Comment by davidfowl** [comment]
@mile-abrettschneider the problem is that when you want to communicate via the sidecar, you need to use the name. It's unclear that the name would be "app-dapr" from above.

**Comment by WolfspiritM** [comment]
> @mile-abrettschneider the problem is that when you want to communicate via the sidecar, you need to use the name. It's unclear that the name would be "app-dapr" from above.

As far as I know all the communication with the sidecar happens via calls to localhost which include the appId to the target. For example `http://localhost:3602/v1.0/invoke/{appId}/method/checkout/100`. The sidecar then resolves that appId via Daprs own service discovery. The sidecar needs to know its own appId to take part in daprs service discovery, which is set here: https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs#L80C34-L80C34

I think the appId that is passed to the sidecar executable should stay the provided appId but the name of the resource ( https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs#L119C51-L119C56 ) should not be the appId to allow the main service to have the same name as the appId. 

In my opinion there is no need for the application to call the sidecar via the aspire service discovery resource name (e.g. app-dapr) as all the communication to the sidecar is always using localhost and from the sidecar daprs own service discovery based on the "--app-id" parameter takes over. Or does Aspire hook into Daprs service discovery somehow?

**Comment by mile-abrettschneider** [comment]
@davidfowl  As far as I know all the communication with the sidecar happens via calls to localhost which include the appId to the target. For example http://localhost:3602/v1.0/invoke/{appId}/method/checkout/100. The sidecar then resolves that appId via Daprs own service discovery. The sidecar needs to know its own appId to take part in daprs service discovery, which is set here: https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs#L80C34-L80C34

I think the appId that is passed to the sidecar executable should stay the provided appId but the name of the resource ( https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs#L119C51-L119C56 ) should not be the appId to allow the main service to have the same name as the appId.

In my opinion there is no need for the application to call the sidecar via the aspire service discovery resource name (e.g. app-dapr) as all the communication to the sidecar is always using localhost and from the sidecar daprs own service discovery based on the "--app-id" parameter takes over. Or does Aspire hook into Daprs service discovery somehow?

**Comment by davidfowl** [comment]
I agree with this, that we should make the resource name tied to the name of the "project-dapr" instead of the app id. Are you also saying the appId should be the same as the resource name? I might agree with that as well 😄. That would make the wire up much more natural:

```
builder.AddProject<Projects.App>("app")
    .WithDaprSidecar();
```

Then the usage would just be:

```
return client.InvokeMethodAsync<WeatherForecast[]>(HttpMethod.Get, "app", "weatherforecast");
```

**Comment by mile-abrettschneider** [comment]
The ability to specify the appId through that call should be retained. There might be some cases where people want it to differ. However, I believe it's a good idea to make the parameter optional and set it to the default project resource name if not explicitly defined. 😄

**Comment by davidfowl** [comment]
I made some changes in the PR
