### ISSUE TITLE
Add component + hosting integration testing

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#937]
We should add some integration tests which cover off spinning up a container for component X and connecting to it from within a service.
 
For example, we should have an integration test project which spins up all the containers we possibly can and connects to them from a service as part of a test run. The test might take a bunch of resources (memory/cpu time) but I don't think we have anything that would detect if things broke right now.

a rough sketch of what it could look like today:
 
* AppHost spins up containers for:
    * postgres db
    * sql db
    * redis
    * rabbitmq
* Then the test app adds all those components in "Main", including redundant ones:
    * EF npgsql
    * npgsql
    * EF sql
    * sql
    * redis
    * rabbitmq
* And then the test ensures all the correct DI services can be resolved, and tries 1 operation on each

I'm putting this under "area-app-model" for now because the hard part is automating the first part. Once we have a test which spins up the AppHost, adding the component part to the test is trivial.

cc @mitchdenny

**Comment by mitchdenny** [comment]
I think we've made good progress here over the last month, but we need to double check that that we are exercising each component. Additionally we need to make sure these test cases can run during CI. We should also support testing against Azure and other cloud providers for resource/component types for those environments.

**Comment by mitchdenny** [comment]
@JamesNK this just needs to be checked off now to make sure all the components are well represented (where they can run locally with external cloud dependencies).

**Comment by radical** [comment]
https://github.com/dotnet/aspire/pull/2534 has been merged. Are there any pending TODO items here?

**Comment by radical** [comment]
Marking this as closed by https://github.com/dotnet/aspire/pull/2534 .
