### ISSUE TITLE
Undo dependency on daily builds of Microsoft.Extensions.Http.Resilience

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#942]
> > This error does touch on the servicing conversation though. Are we guaranteed that Microsoft.Extensions.Http.Resilience version 8.1.0 will ship on nuget.org before we ship our preview2? cc @joperezr
> 
> The current plan is to ship 8.1.0 Jan 9th.

Sounds like we will need to back out updating this reference then.

_Originally posted by @eerhardt in https://github.com/dotnet/aspire/issues/939#issuecomment-1817149457_

**Comment by joperezr** [comment]
This is now done.

**Comment by eerhardt** [comment]
This doesn't appear to be done - we are still depending on 8.1.-preview:

https://github.com/dotnet/aspire/blob/c2b1b8fac46468fb3635f7e183a19a27395445dd/eng/Versions.props#L27

**Comment by joperezr** [comment]
I turned off the subscription, so we won't get any future update PRs which I thought was what this was tracking. I was already working on reverting the updates to 8.1 versions anyway, but I'm fine to not closing this until that is done.
