### ISSUE TITLE
Project Names with Spaces Break the Build

### ISSUE THREAD

**Issue by charper-work** [dotnet/aspire#945]
If you name your project something like "Test Aspire", and make no other changes to the Aspire Starter Project, and then build, it will break the build, as the generated code has spaces in it:

![image](https://github.com/dotnet/aspire/assets/142057534/b7f307bc-3b44-47c1-92e1-ade2286b852d)

Either you shouldn't allow spaces in project names at creation, or your code generation needs to replace all spaces with underscores, like it does for periods.

![image](https://github.com/dotnet/aspire/assets/142057534/bf6e54d1-1a5f-449d-9681-12fc494e89bb)

![image](https://github.com/dotnet/aspire/assets/142057534/db83712b-cf45-439f-8e76-6d55d3e37094)

![image](https://github.com/dotnet/aspire/assets/142057534/586d4d1b-6805-4de9-b199-0fc0d9fbfe96)

I am running on Windows 11.

**Comment by davidfowl** [comment]
Good catch! We should fix this one for preview2. If you want to send a PR, the fix should be here:

https://github.com/dotnet/aspire/blob/f4a75f37aef36a29f30252f21f2409d3c987f35c/src/Aspire.Hosting/build/Aspire.Hosting.targets#L22-L23

**Comment by malisancube** [comment]
This includes those with period(.) separator. e.g. Company.MegaProject

**Comment by Meir017** [comment]
Would it be better (and possible) to have the logic for the generated code be pure c# instead of having some of it in msbuild? I think that the tooling for using c# APIs insude msbuild files in not quite there yet

**Comment by charper-aim** [comment]
> Good catch! We should fix this one for preview2. If you want to send a PR, the fix should be here:
> 
> https://github.com/dotnet/aspire/blob/f4a75f37aef36a29f30252f21f2409d3c987f35c/src/Aspire.Hosting/build/Aspire.Hosting.targets#L22-L23

Sounds good, I can add a PR later today.

**Comment by davidfowl** [comment]
There's already a PR open https://github.com/dotnet/aspire/pull/953

**Comment by charper-work** [comment]
Ah, perfect, thank you!
