### ISSUE TITLE
Set container name to a deterministic value when launching

### ISSUE THREAD

**Issue by analogrelay** [dotnet/aspire#949]
When launching an Aspire app, the created containers are just given the default random docker names:

```
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                       NAMES
5ce3d9b00a89   plenary/shell:latest   "/shell/entrypoint.sh"   2 minutes ago   Up 2 minutes                               nice_swirles
166f578bc2a6   postgres:latest        "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   127.0.0.1:55839->5432/tcp   friendly_kirch
```

I have configured my app with a "shell" container to allow invoking dotnet tools like `dotnet-ef` in the context of a service, and I need to `docker exec` into it in order to run those commands. It'd be helpful if the containers had a consistent name like `[app]_[resource]` or similar, much like how `docker-compose` sets names. Then I could avoid having to look up the container name and could more easily script interactions with running containers (such as `exec`ing in to them).

**Comment by davidfowl** [comment]
Also worth following this issue https://github.com/dotnet/aspire/issues/398

**Comment by analogrelay** [comment]
Yep, I think the container name change is somewhat orthogonal to my specific case, so I filed this. I can see utility in exec-ing in to the running containers for various reasons. I'll chime in on the other issue with specific thoughts for EF tooling.

**Comment by DamianEdwards** [comment]
@davidfowl @karolz-ms @mitchdenny would changing the container naming logic require changes just to the app model or in DCP too?

**Comment by mitchdenny** [comment]
Container banking is handled by DCP.

**Comment by analogrelay** [comment]
@DamianEdwards I was actually going to send a PR but I quickly found that it was handled by DCP 😢

**Comment by karolz-ms** [comment]
@mitchdenny short of better devault in DCP, try passing `--name desired-container-name` via Container.Spec.Args; I believe that should do the trick https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dcp/Model/Container.cs#L42

**Comment by dbreshears** [comment]
DCP side of this in Preview 2.

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
I looked into this, and it is working today without any changes required in hosting. DCP now automatically sets a container name unless one is explicitly specified from hosting.

![image](https://github.com/dotnet/aspire/assets/303201/c1624e6a-9a00-4f4b-9c9c-8f3898979f10)

(Docker requires unique names. The random postfix on each name is a safety measure to prevent duplicates)

I'll update our DCP DTOs to include the new property, but we don't need to use it.

**Comment by DamianEdwards** [comment]
Are we adding support for setting the desired container name from an AppHost project?

**Comment by davidfowl** [comment]
I guess we need another issue?

**Comment by DamianEdwards** [comment]
#1855

**Comment by pedershk** [comment]
> (Docker requires unique names. The random postfix on each name is a safety measure to prevent duplicates)
> 
> I'll update our DCP DTOs to include the new property, but we don't need to use it.

The hostname changes with each restart of debugging for containers managed by the AppHost. This breaks RabbitMQ queue persistence (with fixed volume mounts configured as well) as queues are bound under a hostname directory. RabbitMQ's internal RabbitMQ naming can be changed by setting the NODENAME environment variable on the container which overrides this behavior - but this can be a source of frustration as no indication as to why queues disappear appear in any log.

The following works to override this behavior - but the ` .WithEnvironment("NODENAME", "rabbit@localhost")` statement should perhaps be a default when using the `AddRabbitMQContainer` method?

```
 var docGenRabbitMq = builder
     .AddRabbitMQContainer("rabbitmq-docgen", 9002, password: rabbitMqPassword)
     .WithEnvironment("NODENAME", "rabbit@localhost")
     .WithVolumeMount("rabbitmq-docgen-vol", "/var/lib/rabbitmq", VolumeMountType.Named);
```

**Comment by JamesNK** [comment]
@pedershk Could you create a new issue? That will ensure it will get looked at.

**Comment by pedershk** [comment]
> @pedershk Could you create a new issue? That will ensure it will get looked at.

Yes, sorry, didn't even notice that this one was closed. I blame lack of coffeee.

#2247
