### ISSUE TITLE
UI tests for the dashboard 

### ISSUE THREAD

**Issue by Meir017** [dotnet/aspire#958]
I think we should start adding UI tests for the dashboard. 
We could use Microsoft.Playwright and integrate with the TestServer by implementing a route fir redirecting the browser's traffic to the in memory TestServer

**Comment by leslierichardson95** [comment]
@Meir017 are you referring to UI tests for the dashboard itself or UI tests for the actual UI components that make up your Aspire app?

**Comment by danmoseley** [comment]
@kvenkatrajan shall we use this issue for getting 1 Playwright test running and checked in this week?

**Comment by kvenkatrajan** [comment]
#4386 - in review
