### ISSUE TITLE
Docker hosted API with aspire

### ISSUE THREAD

**Issue by andref15** [dotnet/aspire#966]
I don't know if this is an issue or just not supported...
I'm trying to add aspire to a project that has a web api with a docker launch profile. In the Program.cs of the AppHost project, I added the WithLaunchProfile call

    builder.AddProject<Projects.Server>("server").WithLaunchProfile("Docker");
    builder.AddContainer("Server", "server", "dev");

The application runns file when I use the http or https launch profile, however when using the docker profile, I get an exception during startup

    System.IO.IOException: 'Failed to bind to address http://127.0.0.1:15061: address already in use.'

the url in the exception is the url that the apphost uses but the exception occurs in the server application.
It seems like the docker profile is being ignored and the launch settings from the apphost are being applied to the server application. Are docker profiles not supported? Or am I doing something wrong in the setup?

I couldn't find any samples or documentation for using a docker profile.

**Comment by DamianEdwards** [comment]
We don't currently support running projects in Docker. See #969
