### ISSUE TITLE
PostgreSQL uses incorrect port

### ISSUE THREAD

**Issue by julioct** [dotnet/aspire#985]
Added the PostgreSQL container and database in AppHost:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var postgres = builder.AddPostgresContainer("postgres")
                      .AddDatabase("GameStore");
var blobs = builder.AddAzureStorage("storage")
                   .AddBlobs("blobs");

var backend = builder.AddProject<Projects.GameStore_Api>("backend")
                     .WithReference(postgres)
                     .WithReference(blobs);

builder.AddProject<Projects.GameStore_Frontend>("frontend")
       .WithReference(backend);

var app = builder.Build();

app.Run();

```

Then registered the DB context in my API:

```csharp
builder.AddNpgsqlDbContext<GameStoreContext>("GameStore");
```

But when the app starts and tries to access the DB it fails with:
`
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
`

I looked at the ports assigned to the container in Docker Desktop:

![image](https://github.com/dotnet/aspire/assets/2374270/8a446640-76ed-4418-8321-e2015d0e2567)

Then looked at the connection string in the API project env variables:

![image](https://github.com/dotnet/aspire/assets/2374270/e0a28431-3a24-4be7-9390-27dae0fc898c)

So the container is using port **61891** while my backend has been configured for port **61881**.

Which explains the failure.

Questions:
1. What am I doing wrong?
2. How to workaround?

**Comment by DamianEdwards** [comment]
Hmm that's very odd. Could you try cloning/download the [eShop Lite sample](https://github.com/dotnet/aspire-samples/tree/main/samples/eShopLite) and running that to see if that works for you?

**Comment by davidfowl** [comment]
Not sure it's the wrong port, the one handed out the dependencies is a proxy port managed by the orchestrator. The error is mroe likely because the database isnt up yet and your app needs to retry the connection until it is up. See https://github.com/dotnet/aspire/issues/692 for more information.

**Comment by julioct** [comment]
You are absolutely right, David. Even eShop Lite is using a different port than the one I see in Docker Desktop, and yet it works without issues.

As you mentioned, there's a proxy port, and I confirmed I can connect to that one just fine.

I think it works for eShop Lite because it does the DB data seeding in a hosted service while I'm doing the same directly in Program.cs in my backend, and somehow the hosted service is allowed a bit of more time before reaching the DB.

Adding a 5 secs delay to my current logic succeeds. I'll try moving to the hosted service approach.

However, for reference, this same approach I'm using works fine with the SQL Server component, and I can see it retrying like crazy until it succeeds. PostgreSQL is not doing the same.

**Comment by julioct** [comment]
OK, so this is what makes the difference in eShop Lite:

```csharp
        var strategy = dbContext.Database.CreateExecutionStrategy();
        ...
        await strategy.ExecuteAsync(() => dbContext.Database.MigrateAsync(cancellationToken));
```

Used the same in mine, and works great. The connection will be retried a bunch of times until it succeeds.

No need for a hosted service.
