### ISSUE TITLE
Container bindings not reflected in manifest

### ISSUE THREAD

**Issue by KieranFoot** [dotnet/aspire#988]
I'm currently in the process of making a tool to deploy my current project to Kubernetes. I can create most entries from the data provided, however, that is not the case when it comes to bindings.

The documentation states that ports are inferred to a degree, and for projects, I understand that. When it comes to containers, namely those where I provide custom port mapping via `.WithServiceBinding()`, the ports are not reflected in the manifest.

For example, the call `WithServiceBinding(containerPort: 3000, hostPort: 3000, name: "grafana-http", scheme: "http")` produces:

```json
"bindings": {
  "grafana-http": {
     "scheme": "http",
     "protocol": "tcp",
    "transport": "http"
  }
}
```

This can be correctly inferred as port 3000 is the only port exposed by the container in this case.

However, even if I add a custom port with the call `.WithServiceBinding(containerPort: 21, hostPort: 3001, name: "grafana-ssh", scheme: "http")`, the output is as below:

```json
"bindings": {
  "grafana-ssh": {
    "scheme": "http",
    "protocol": "tcp",
    "transport": "http"
  }
}
```

I would expect the port numbers to appear in the manifest in this case. Not withstanding the invalid container port, without them appearing in the manifest, I cannot go on to create the needed yaml files. In the above case I would expect to see output similar to:

```json
"bindings": {
  "grafana-ssh": {
    "scheme": "http",
    "protocol": "tcp",
    "transport": "http",
    "containerPort": 21,
    "hostPort": 3001 
  }
}
```

Looking through the source, I can see that `ManifestPublisher.WriteBindings()` does output `containerPort`, though clearly not in my circumstances, but under no circumstances does it output `hostPort`.

**Comment by davidfowl** [comment]
This change just missed preview1 but is fixed in preview2 https://github.com/dotnet/aspire/pull/739


> I'm currently in the process of making a tool to deploy my current project to Kubernetes. I can create most entries from the data provided, however, that is not the case when it comes to bindings.

Don't make a new tool, contribute to [this one](https://github.com/dotnet/aspire/issues/830#issuecomment-1820967946) so we and land on a design.

**Comment by KieranFoot** [comment]
> The host port is machine dependent and shouldn't be written to the manifest.

Yes, you're right.

> Don't make a new tool, contribute to https://github.com/dotnet/aspire/issues/830#issuecomment-1820967946 so we and land on a design.

I'll take a look and see if there is anything I can contribute. Thanks for pointing me in that direction, should save me some time.
