### ISSUE TITLE
Why is the package name not prefixed with Microsoft?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspire#990]
Why is the package name not prefixed with Microsoft?

Is there a plan to prefix the package name with Microsoft?

**Comment by RussKie** [comment]
Which package?

**Comment by DamianEdwards** [comment]
Thanks for the question. Part of the experience we hope to provide with .NET Aspire includes offering a set of **curated**, high-quality packages to make it easier to discover and use packages that work well together. This includes many packages that integrate well-known, essential, third-party libraries, e.g. Npgsql (for PostgreSQL), StackExchange.Redis (for Redis), etc. Having those packages start with the "Microsoft." prefix might cause some confusion to consumers and/or present issues when it comes to acceptable use of other products trademarks.

Additionally, the Microsoft.* prefix is reserved on nuget.org such that only packages owned or co-owned by the Microsoft NuGet account can use it. We'd like to leave space for .NET Aspire to evolve into more than simply a Microsoft-owned stack, especially given the incorporation of many third-party libraries. In the future, we'd like to explore models for more distributed-ownership of the .NET Aspire components and we didn't want a single vendor prefix to get in the way of that.

Finally, there are other package sets on nuget.org that don't use the Microsoft.* prefix despite being published by Microsoft, e.g. the modern Azure SDK packages, so this isn't a wholly new thing.

Hope that helps!

**Comment by DamianEdwards** [comment]
Appreciate your thoughts but we don't intend on changing the package naming scheme at this time for the reasons stated.
