### ISSUE TITLE
Project in a folder with full stop fails to build

### ISSUE THREAD

**Issue by josephwambura** [dotnet/aspire#991]
Project in a folder with full stop fails to build.

Tried with MyCompany.MyProjectName which fails to build, however MyProjectName builds

**Comment by josephwambura** [comment]
Cannot resolve the below.

var apiservice = builder.AddProject<Projects.MyCompany.MyProjectName_ApiService>("apiservice");

builder.AddProject<Projects.MyCompany.MyProjectName_Web>("webfrontend")
    .WithReference(apiservice);

**Comment by DamianEdwards** [comment]
Known issue and already fixed, thanks!

**Comment by josephwambura** [comment]
Will it be available in the next release or what do I need to do @DamianEdwards ?

**Comment by josephwambura** [comment]
Actually, when I modify manually it works.

`Projects.MyCompany.MyProjectName_ApiService` to `Projects.MyCompany_MyProjectName_ApiService`

and 

`Projects.MyCompany.MyProjectName_Web` to `Projects.MyCompany_MyProjectName_Web`

**Comment by davidfowl** [comment]
Fixed in https://github.com/dotnet/aspire/pull/953
