### ISSUE TITLE
Tagging of projects/services

### ISSUE THREAD

**Issue by ripebananas** [dotnet/aspire#994]
Hello,

I am fairly new to Aspire, so excuse me if my question is not relevant.
In Project Tye, different services can be tagged and then only specific ones can be run, e.g. `tye run --tags XXX`.
I could not find similar capability in Aspire when running the app host. Is there a plan to implement such functionality?

Thanks.

**Comment by DamianEdwards** [comment]
Not yet, but that's something we're tracking in #303
