### ISSUE TITLE
Azure deployed Aspire app won't allow POST to backend

### ISSUE THREAD

**Issue by julioct** [dotnet/aspire#998]
I have an Aspire app with a Blazor Frontend and a backend API:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var postgres = builder.AddPostgresContainer("postgres")
                      .AddDatabase("GameStore");
var blobs = builder.AddAzureStorage("storage")
                   .AddBlobs("blobs");

var backend = builder.AddProject<Projects.GameStore_Api>("backend")
                     .WithReference(postgres);                     

builder.AddProject<Projects.GameStore_Frontend>("frontend")
       .WithReference(backend)
       .WithReference(blobs);

var app = builder.Build();

app.Run();
```

After deploying the app to Azure via AZD as described [here](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth), the frontend is able to reach the API just fine, and all Frontend to Backend GET requests work without issues.

However, POST requests won't work and just redirect to a GET because the backend has been configured without insecure connections:

![image](https://github.com/dotnet/aspire/assets/2374270/3f4649c7-43d7-4d04-a376-e98748b73802)

Because of that, when client makes a POST to backend at http://backend, the ingress will not allow it, transform it into an HTTPS request and somehow that also turns it into a GET request, which is what my backend will receive in the end.

By allowing insecure connections in the ingress, the issue is fixed.

However, once I redeploy my app via AZD UP, the Insecure Connections setting is reset, and I have to re-enable.

How to configure my Aspire app so that ingress always allows insecure connections?

**Comment by davidfowl** [comment]
You have 2 options:

1. Disable https redirection.
2. Generate the infrastructure and set `allowInsecure: true`. See https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-azd-in-depth?tabs=windows#generate-bicep-from-net-aspire-app-model for instructions on how to do that. 

Once you do that, you'll have some yml files under each project. You should see `allowInsecure: false` (amongst other options)

**Comment by julioct** [comment]
@davidfowl I don't have any `UseHttpsRedirection()` calls in my apps, so they are not asking for HTTPS anywhere. 

However, setting `allowInsecure: true` via the yml files fixed the issue.

Thank you!

**Comment by davidfowl** [comment]
@julioct Can you file another issue here https://github.com/Azure/azure-dev? We'll need to tweak the default logic for how we determine to `AllowInsecure`.

**Comment by julioct** [comment]
@davidfowl Done! https://github.com/Azure/azure-dev/issues/3021

**Comment by davidfowl** [comment]
Closing this in favor of the azd issue.
