### ISSUE TITLE
Standard method(s) of trimming file paths

### ISSUE THREAD

**Issue by tlmii** [dotnet/aspire#999]
This stems most recently from https://github.com/dotnet/aspire/pull/987#issuecomment-1821889071 but we've discussed it in other issues and PRs in the past.

We have several places where we display file paths (Project's source location, executable's command and working directory, etc) and they can often be very long.

For simplicity right now we're just using the same ellipsis overflow for them as we use in other places, along with a tooltip. For example:

![image](https://github.com/dotnet/aspire/assets/9613109/1bb96d07-0328-4836-bbff-b40773466b0b)

As the comment above noted, this truncation is exactly backwards of what we want since the mostly likely interesting part is at the end.

We should figure out if there is a standard/common way of doing this (including a library if needed) and then make use of that consistently across the dashboard.

Two possibilities to consider:

1. Middle trimming: since the drive/root is often useful in a file path, as is the right-most segments, trimming something in the middle can be useful. E.g. `c:\src\repos\dev\this\that\project1\project1.csproj` becomes something like `c:\src\...project1\project1.csproj`
2. Diff trimming: When you've got a set of paths that are all similar, showing just the difference can be helpful. E.g. `c:\src\repos\project1\project1.csproj` and `c:\src\repos\project2\project2.csproj` become `...\project1\project1.csproj` and `...\project2\project2.csproj`.

**Comment by DamianEdwards** [comment]
👍 for "middle trimming"

**Comment by smitpatel** [comment]
How about path relative to AppHost project (or repo root)?
